const pack_p2_b_batch1_questions = [
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Dividend discount model (Gordon Growth)",
    "QuestionID": "P2-B-501",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-501-gordon-growth-model-intrinsic-value",
    "Stem": "Crestview Industries just paid an annual dividend of $2.40 per share. The dividend is expected to grow at 5% per year indefinitely. Investors require a 12% return on Crestview stock. Treasury Analyst Megan Calloway must determine the current intrinsic value per share using the Gordon Growth Model.",
    "Choices": {
      "A": "$36.00 — the next dividend of $2.52 divided by the required return of 12% less the growth rate of 5%.",
      "B": "$34.29 — the current dividend of $2.40 divided by the required return of 12% less the growth rate of 5%.",
      "C": "$42.00 — the next dividend of $2.52 divided by the growth rate of 5%, reflecting the capitalized growth value.",
      "D": "$20.00 — the current dividend of $2.40 divided by the required return of 12%, representing the no-growth capitalization."
    },
    "CorrectChoice": "A",
    "Difficulty": "Easy",
    "DifficultyScore": 1,
    "CognitiveLevel": "Remember",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "CB-11: Cost of Common Equity — Dividend Discount Model (Gordon Growth)",
    "Authorities": ["Dividend Discount Model (Gordon, 1962)"],
    "source_ids": ["CB-11: Cost of Common Equity — Dividend Discount Model (Gordon Growth)"],
    "source_support_for_key": {
      "source_id": "CB-11",
      "rule_or_proposition": "P0 = D1 / (r - g), where D1 = D0 x (1 + g)",
      "application_to_facts": "D0 = $2.40, g = 5%, r = 12%; D1 = $2.40 x 1.05 = $2.52; P0 = $2.52 / 0.07 = $36.00",
      "key_conclusion": "The intrinsic value is $36.00 per share"
    },
    "distractor_intent": {
      "B": {"misconception": "Using D0 instead of D1", "why_plausible": "The $2.40 dividend is explicitly stated; candidates may skip the D1 adjustment", "tier_candidate": 1},
      "C": {"misconception": "Dividing D1 by g instead of (r - g)", "why_plausible": "Capitalizing by g is intuitive but applies only when r = g, which is undefined", "tier_candidate": 2},
      "D": {"misconception": "Using no-growth perpetuity formula", "why_plausible": "Valid for zero-growth dividends but ignores the 5% growth assumption", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A is correct. Option B uses D0 instead of D1. Option C incorrectly divides by g. Option D ignores growth.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The Gordon Growth Model values a stock as P0 = D1 / (r - g). D1 = D0 x (1 + g) = $2.40 x 1.05 = $2.52. The denominator is r - g = 0.12 - 0.05 = 0.07. Therefore P0 = $2.52 / 0.07 = $36.00. The model requires using the next period's expected dividend (D1), not the just-paid dividend (D0), because the stock price reflects future expected cash flows.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "This uses D0 ($2.40) instead of D1 ($2.52) in the numerator. The Gordon Growth Model values future dividends, so D1 = D0 x (1 + g) must be used. The $2.40 was already paid and is not part of the forward-looking valuation. Using D0 understates the intrinsic value.",
    "ExplanationWrongC": "Dividing D1 by the growth rate (5%) capitalizes the dividend stream at the growth rate rather than at the required return net of growth. The denominator in the Gordon Growth Model is (r - g), not g. Dividing by g alone would imply an infinitely high stock price.",
    "ExplanationWrongD": "This applies the zero-growth perpetuity formula P0 = D1/r, which is correct only when g = 0%. Since Crestview's dividends grow at 5% per year, the growth rate must be subtracted from the required return in the denominator."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Dividend discount model (Gordon Growth)",
    "QuestionID": "P2-B-502",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-502-ddm-implied-required-return",
    "Stem": "Bexley Pharmaceuticals stock trades at $48.00 per share. The company just paid a dividend of $1.92, and dividends are expected to grow at 6% annually. VP of Finance Daniel Hurst needs to determine the market's implied required return on Bexley equity.",
    "Choices": {
      "A": "10.20% — the next dividend of $2.0352 divided by the market price of $48.00, plus the 6% growth rate.",
      "B": "10.00% — the current dividend of $1.92 divided by the market price of $48.00, plus the 6% growth rate.",
      "C": "4.00% — the growth rate of 6% subtracted from the dividend yield of 10% implied by the current dividend and price.",
      "D": "8.00% — the average of the dividend yield of 4% and the growth rate of 6%, adjusted for market risk."
    },
    "CorrectChoice": "B",
    "Difficulty": "Moderate-Easy",
    "DifficultyScore": 2,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "CB-11: Cost of Common Equity — Dividend Discount Model (Gordon Growth)",
    "Authorities": ["Dividend Discount Model (Gordon, 1962)"],
    "source_ids": ["CB-11: Cost of Common Equity — Dividend Discount Model (Gordon Growth)"],
    "source_support_for_key": {
      "source_id": "CB-11",
      "rule_or_proposition": "R_e = D0/P0 + g (yield-plus-growth approximation)",
      "application_to_facts": "D0 = $1.92, g = 6%, P0 = $48.00; Yield = $1.92/$48.00 = 4.00%; R_e = 4.00% + 6.00% = 10.00%",
      "key_conclusion": "The implied required return is 10.00%"
    },
    "distractor_intent": {
      "A": {"misconception": "Using D1 when the yield-plus-growth approximation uses D0", "why_plausible": "D1 is technically more precise but the answer choices use D0-based yield", "tier_candidate": 1},
      "C": {"misconception": "Subtracting growth from dividend yield rather than adding it", "why_plausible": "The relationship between yield, growth, and return can be confused directionally", "tier_candidate": 2},
      "D": {"misconception": "Averaging the dividend yield and growth rate", "why_plausible": "Averaging is a common heuristic when the correct formula is unclear", "tier_candidate": 3}
    },
    "uniqueness_note": "Option B correctly applies R_e = D0/P0 + g. Option A uses D1 (more precise but not matching choices). Option C reverses the formula. Option D is arbitrary.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The implied required return is estimated as the dividend yield plus the growth rate: R_e = (D0 / P0) + g. Dividend yield = $1.92 / $48.00 = 4.00%. Adding growth: R_e = 4.00% + 6.00% = 10.00%. This yield-plus-growth approach is the standard application when the current dividend and growth rate are known.",
    "ExplanationWrongA": "Using D1 ($2.0352) gives $2.0352 / $48.00 = 4.24%, yielding 10.24%. While more technically precise, this does not match the answer choices. The yield-plus-growth approximation using D0 is the intended approach, producing the exact 10.00% in option B.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "This reverses the formula structure. The correct relationship is R_e = Dividend Yield + Growth Rate, not Growth Rate subtracted from Dividend Yield. The required return must exceed the growth rate, and the yield and growth are additive.",
    "ExplanationWrongD": "There is no theoretical basis for averaging the dividend yield and growth rate. The Gordon Growth Model specifies that the required return equals the dividend yield plus the growth rate, not their average."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Dividend discount model (Gordon Growth)",
    "QuestionID": "P2-B-503",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-503-ddm-implied-growth-rate",
    "Stem": "Cornerstone Software shares trade at $62.50. The company paid a quarterly dividend of $0.45 last quarter (annualized $1.80). The required return on Cornerstone equity is 11.5%. CFO Rachel Nguyen must determine the implied constant growth rate embedded in the current share price.",
    "Choices": {
      "A": "8.58% — the annualized dividend yield of 2.88% subtracted from the required return of 11.5%.",
      "B": "5.75% — half of the required return of 11.5%, reflecting the sustainable growth assumption.",
      "C": "8.64% — the annualized dividend of $1.80 divided by the stock price of $62.50, subtracted from the required return.",
      "D": "3.20% — the growth rate implied by the quarterly dividend of $0.45 annualized to $1.80, divided by the stock price."
    },
    "CorrectChoice": "C",
    "Difficulty": "Moderate-Easy",
    "DifficultyScore": 2,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "CB-11: Cost of Common Equity — Dividend Discount Model (Gordon Growth)",
    "Authorities": ["Dividend Discount Model (Gordon, 1962)"],
    "source_ids": ["CB-11: Cost of Common Equity — Dividend Discount Model (Gordon Growth)"],
    "source_support_for_key": {
      "source_id": "CB-11",
      "rule_or_proposition": "g = R_e - (D1/P0), rearranged from the Gordon Growth Model",
      "application_to_facts": "R_e = 11.5%, D1 = $1.80, P0 = $62.50; g = 11.5% - 2.88% = 8.62%",
      "key_conclusion": "The implied growth rate is approximately 8.64%"
    },
    "distractor_intent": {
      "A": {"misconception": "Using an imprecise dividend yield calculation", "why_plausible": "The arithmetic is close but uses a different rounding approach", "tier_candidate": 2},
      "B": {"misconception": "Assuming growth equals half of required return", "why_plausible": "A rough heuristic without theoretical basis", "tier_candidate": 3},
      "D": {"misconception": "Providing the dividend yield instead of the growth rate", "why_plausible": "The yield and growth rate are related; candidates may confuse which is asked for", "tier_candidate": 1}
    },
    "uniqueness_note": "Option C correctly rearranges the Gordon Growth Model. Option A approximates but is less precise. Option B is a heuristic. Option D provides the yield, not the growth rate.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The Gordon Growth Model states P0 = D1 / (R_e - g). Rearranging: g = R_e - (D1 / P0). Dividend yield = $1.80 / $62.50 = 2.88%. Growth rate = 11.50% - 2.88% = 8.62%, approximately 8.64%. This represents the constant growth rate the market is pricing into Cornerstone's stock.",
    "ExplanationWrongA": "This uses a slightly different dividend yield calculation. The precise computation yields a dividend yield of 2.88%, and g = 11.5% - 2.88% = 8.62%. The difference is a rounding artifact.",
    "ExplanationWrongB": "There is no theoretical basis for setting growth equal to half the required return. The Gordon Growth Model does not prescribe such a relationship beyond requiring g < R_e.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "This provides the dividend yield ($1.80 / $62.50 = 2.88%), not the growth rate. The question asks for the implied growth rate, which requires subtracting the dividend yield from the required return."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Stock repurchase effects on EPS",
    "QuestionID": "P2-B-504",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-504-repurchase-eps-accretion-dilution",
    "Stem": "Westbrook Electronics reports net income of $18 million, 6 million shares outstanding, and a stock price of $36 per share. The board is considering either paying a $1.50 per share cash dividend or using the equivalent $9 million to repurchase shares at market price. CFO Thomas Randall must compare the post-transaction EPS under each alternative.",
    "Choices": {
      "A": "Repurchase EPS of $3.13; Dividend EPS of $3.00. The repurchase increases EPS because the share count decreases while net income remains unchanged.",
      "B": "Repurchase EPS of $3.00; Dividend EPS of $2.70. Both alternatives reduce EPS proportionally because total equity decreases by the same amount.",
      "C": "Repurchase EPS of $3.60; Dividend EPS of $3.00. The repurchase doubles the EPS improvement because both net income and shares are affected.",
      "D": "Both alternatives produce identical EPS of $3.00 because the total payout of $9 million reduces equity equally regardless of method."
    },
    "CorrectChoice": "A",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "EPS = Net Income / Weighted Average Shares Outstanding",
    "Authorities": ["ASC 260 (Earnings Per Share)", "Corporate finance theory"],
    "source_ids": ["FA-15: Earnings Per Share (EPS)"],
    "source_support_for_key": {
      "source_id": "FA-15",
      "rule_or_proposition": "EPS = Net Income / Shares; repurchase reduces shares but not net income",
      "application_to_facts": "Dividend: NI=$18M, shares=6M, EPS=$3.00. Repurchase: shares=5.75M, EPS=$3.13",
      "key_conclusion": "Repurchase increases EPS from $3.00 to $3.13"
    },
    "distractor_intent": {
      "B": {"misconception": "Assuming both alternatives reduce EPS equally", "why_plausible": "Candidates may think total equity reduction matters rather than share count effect", "tier_candidate": 1},
      "C": {"misconception": "Double-counting the EPS benefit", "why_plausible": "Repurchase does not change net income; candidates may incorrectly assume earnings double", "tier_candidate": 2},
      "D": {"misconception": "Assuming EPS is invariant to payout method", "why_plausible": "If total equity decreases equally, candidates may assume per-share effect is identical", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly computes both scenarios. Option B incorrectly assumes both reduce EPS. Option C double-counts. Option D ignores share-count reduction.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "Under the dividend, net income remains $18M and shares remain 6M, so EPS = $3.00. Under the repurchase, $9M buys back $9M/$36 = 250,000 shares, reducing shares to 5.75M. Net income is unchanged (dividends are not expenses). Repurchase EPS = $18M/5.75M = $3.13. The repurchase accretes EPS because the same earnings are spread across fewer shares.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "The dividend does not reduce EPS because dividends are paid from after-tax earnings and do not affect net income or the share count. Only the repurchase reduces the share count, which mechanically increases EPS.",
    "ExplanationWrongC": "The repurchase does not affect net income. EPS accretion comes solely from the reduced share count. The correct repurchase EPS is $18M/5.75M = $3.13, not $3.60.",
    "ExplanationWrongD": "While both distribute $9 million, they have fundamentally different effects on EPS. The dividend pays cash without changing the share count. The repurchase retires shares, increasing EPS."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Residual dividend policy",
    "QuestionID": "P2-B-505",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-505-residual-dividend-policy-application",
    "Stem": "Helios Energy's target capital structure is 60% equity and 40% debt. The upcoming capital budget requires $45 million in total investment. Net income is projected at $30 million. CFO Gregory Park must determine the maximum dividend the company can pay under a residual dividend policy.",
    "Choices": {
      "A": "$3.0 million — the residual after funding 60% of the capital budget from net income.",
      "B": "$12.0 million — the residual after funding 40% of the capital budget from net income.",
      "C": "$18.0 million — the total capital budget minus net income, representing the debt-financed portion.",
      "D": "$30.0 million — the full net income is available for dividends because the capital budget is funded by debt."
    },
    "CorrectChoice": "A",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "Residual Dividend = Net Income - (Target Equity Ratio x Capital Budget)",
    "Authorities": ["Corporate finance theory"],
    "source_ids": ["FA-22: Dividend Payout Ratio"],
    "source_support_for_key": {
      "source_id": "FA-22",
      "rule_or_proposition": "Residual dividend = NI - (Equity% x Capex)",
      "application_to_facts": "Target equity = 60%, Capex = $45M, NI = $30M; Equity needed = $27M; Residual = $3M.",
      "key_conclusion": "The maximum dividend under residual policy is $3.0 million"
    },
    "distractor_intent": {
      "B": {"misconception": "Confusing the debt-portion residual with the equity-portion residual", "why_plausible": "The $12M represents the residual after funding only the debt portion, not the equity need", "tier_candidate": 1},
      "C": {"misconception": "Reversing the subtraction direction", "why_plausible": "The direction of subtraction may be confused when numbers are close", "tier_candidate": 2},
      "D": {"misconception": "Assuming all capital budget is debt-financed", "why_plausible": "Residual policy prioritizes equity funding; this ignores the equity portion entirely", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly computes the residual after equity funding. Option B confuses debt-portion residual. Option C reverses subtraction. Option D ignores equity requirement.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "Under residual dividend policy, dividends are paid from earnings after equity-financed capital needs are met. Helios requires 60% equity: 0.60 x $45M = $27M. Residual = $30M - $27M = $3.0M. The maximum dividend under the residual framework is $3.0 million.",
    "ExplanationWrongB": "The $12.0M represents the residual after funding only the 40% debt portion ($18M from NI). Under residual policy, the equity portion must be funded first from retained earnings. The equity need is $27M, leaving only $3M for dividends.",
    "ExplanationWrongC": "This reverses the subtraction order. The residual dividend formula is Net Income minus Equity Needed, not Capital Budget minus Net Income. The $18 million represents the debt-financed portion.",
    "ExplanationWrongD": "Under residual policy, the equity portion must be funded from retained earnings before dividends are considered. Net income of $30M must first cover the $27M equity requirement."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Dividend signaling theory",
    "QuestionID": "P2-B-506",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-506-dividend-signaling-theory-implications",
    "Stem": "Keystone Manufacturing announces a 15% increase in its quarterly dividend, from $0.60 to $0.69 per share, while industry peers have maintained or reduced their dividends. Investment analyst Sara Delgado must evaluate what dividend signaling theory predicts about the market's likely reaction.",
    "Choices": {
      "A": "The stock price will likely increase because the dividend increase signals management's confidence in sustained future cash flows, reducing information asymmetry between insiders and the market.",
      "B": "The stock price will be unaffected because dividend changes are irrelevant in efficient markets where investors can create homemade dividends by selling shares.",
      "C": "The stock price will decrease because the higher payout reduces retained earnings and signals fewer profitable investment opportunities.",
      "D": "The stock price will be volatile in the short term but return to the pre-announcement level because dividend signals are quickly arbitraged away."
    },
    "CorrectChoice": "A",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Understand",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "N/A — conceptual",
    "Authorities": ["Modigliani-Miller dividend irrelevance (1961)", "Dividend signaling theory (Bhattacharya, 1979)"],
    "source_ids": ["Dividend signaling theory (Bhattacharya, 1979)"],
    "source_support_for_key": {
      "source_id": "Bhattacharya (1979)",
      "rule_or_proposition": "Dividend changes signal management's private information about future cash flows; increases signal confidence",
      "application_to_facts": "Keystone's 15% dividend increase signals management confidence in sustained future cash flows",
      "key_conclusion": "Signaling theory predicts the stock price will increase"
    },
    "distractor_intent": {
      "B": {"misconception": "Applying MM irrelevance when the question asks about signaling theory", "why_plausible": "MM irrelevance is a foundational concept; candidates may default to it", "tier_candidate": 1},
      "C": {"misconception": "Interpreting the increase as a negative signal about growth", "why_plausible": "Higher dividends reduce retained earnings; candidates may conflate payout with reduced reinvestment", "tier_candidate": 2},
      "D": {"misconception": "Assuming efficient markets eliminate all signals immediately", "why_plausible": "EMH is a standard finance concept", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly applies signaling theory. Option B applies MM irrelevance. Option C inverts the signal. Option D assumes signals are arbitraged away.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "Dividend signaling theory (Bhattacharya, 1979) predicts that dividend changes convey management's private information about future cash flows. A 15% increase while peers maintain or reduce dividends signals Keystone's management has confidence in sustained future cash flows, reducing information asymmetry between insiders and the market. The market is likely to react positively.",
    "ExplanationWrongB": "Modigliani and Miller (1961) argue that in perfect capital markets, dividend policy is irrelevant. However, the question asks specifically about signaling theory, not MM irrelevance. Signaling theory is a real-world extension that recognizes information asymmetry.",
    "ExplanationWrongC": "While a dividend increase reduces retained earnings, signaling theory interprets the increase as a positive signal about management's confidence in future cash flows. The signal outweighs the reduction in retained earnings.",
    "ExplanationWrongD": "Under signaling theory, dividend changes convey persistent information about cash flow expectations, not temporary noise. The market reaction reflects updated expectations, not an arbitrageable dislocation."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Lintner's dividend smoothing model",
    "QuestionID": "P2-B-507",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-507-lintner-dividend-smoothing-model",
    "Stem": "Clearwater Logistics has paid dividends of $1.20, $1.24, $1.28, and $1.32 per share over the last four years despite earnings per share fluctuating between $4.50 and $6.20. CFO Nathan Brooks must explain why the dividend growth has been steady while earnings were volatile.",
    "Choices": {
      "A": "Lintner's dividend smoothing model predicts that firms adjust dividends gradually toward a target payout ratio, causing dividends to lag earnings changes and exhibit more stability than earnings.",
      "B": "The residual dividend policy explains the pattern because Clearwater invests first and distributes whatever remains, producing steady dividends only when capital spending is constant.",
      "C": "The bird-in-the-hand theory suggests that investors prefer the certainty of dividends over uncertain capital gains, so the company smooths dividends to reduce investor uncertainty.",
      "D": "The clientele effect causes dividend stability because Clearwater has attracted income-oriented investors who would sell if dividends fluctuated with earnings."
    },
    "CorrectChoice": "A",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Understand",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "N/A — conceptual",
    "Authorities": ["Bird-in-the-hand theory (Gordon, 1963)", "Lintner's dividend smoothing model (Lintner, 1956)"],
    "source_ids": ["Lintner (1956) Dividend Smoothing Model"],
    "source_support_for_key": {
      "source_id": "Lintner (1956)",
      "rule_or_proposition": "Firms adjust dividends gradually toward a target payout ratio; managers view dividends as changed only when long-run sustainable earnings change",
      "application_to_facts": "Clearwater's steady dividend growth despite volatile earnings reflects Lintner's smoothing behavior",
      "key_conclusion": "Lintner's model predicts gradual dividend adjustment toward a target payout"
    },
    "distractor_intent": {
      "B": {"misconception": "Confusing residual policy (variable dividends) with smoothing (stable dividends)", "why_plausible": "Residual policy produces variable, not stable, dividends", "tier_candidate": 2},
      "C": {"misconception": "Attributing smoothing to bird-in-the-hand theory rather than Lintner's descriptive model", "why_plausible": "Bird-in-the-hand explains preference for dividends but Lintner describes the smoothing mechanism", "tier_candidate": 1},
      "D": {"misconception": "Attributing smoothing to the clientele effect", "why_plausible": "Clientele effect explains investor attraction, not smoothing mechanism", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly describes Lintner's dividend smoothing model. Option B describes residual policy. Option C applies bird-in-the-hand theory. Option D describes clientele effects.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "Lintner's dividend smoothing model (1956) observes that firms adjust dividends gradually toward a target payout ratio based on long-run sustainable earnings. Managers resist cutting dividends and increase them only when they believe the new earnings level is permanent. Clearwater's steady dividend growth ($0.04 increases) despite volatile EPS ($4.50–$6.20) reflects this smoothing behavior — dividends lag earnings changes and exhibit more stability than earnings.",
    "ExplanationWrongB": "A residual dividend policy produces variable dividends that fluctuate with investment needs and earnings. Clearwater's pattern shows the opposite — stable dividend growth. Residual policy would show dividends varying with capital spending.",
    "ExplanationWrongC": "The bird-in-the-hand theory (Gordon, 1963) explains why investors prefer dividend certainty, but Lintner's model specifically describes the empirical smoothing pattern. The question asks for Lintner's explanation of why dividends are steady, not the theoretical preference for dividends.",
    "ExplanationWrongD": "The clientele effect explains why different firms attract different investor clienteles. It does not explain the mechanism by which dividends become smooth despite earnings volatility."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Share repurchase vs dividend comparison",
    "QuestionID": "P2-B-508",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-508-share-repurchase-tax-advantage-over-dividend",
    "Stem": "Redwood Industries has $12 million in excess cash and is considering either distributing it as a special dividend or using it for a share repurchase. Shareholder William Chen holds 5,000 shares at $40 each and has a tax basis of $25 per share. The corporate tax rate is 21% and the individual capital gains rate is 15%. Tax Director Anita Patel must explain the tax differential for Chen under each alternative.",
    "Choices": {
      "A": "Under the dividend, Chen pays ordinary income tax on the full dividend amount. Under the repurchase, Chen pays capital gains tax only on realized gains, and only if he sells, deferring tax liability.",
      "B": "Under both alternatives, Chen pays 15% on the gain because dividends and capital gains are taxed at the same rate under current law.",
      "C": "Under the repurchase, the company pays the tax on the repurchased shares, so Chen bears no tax burden. Under the dividend, Chen pays ordinary income tax.",
      "D": "Under the dividend, Chen can defer taxes by reinvesting through a DRIP. Under the repurchase, Chen must recognize gain immediately upon sale."
    },
    "CorrectChoice": "A",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "N/A — conceptual",
    "Authorities": ["Tax differential theory (Elton & Gruber, 1970)", "IRC §301, §302"],
    "source_ids": ["Tax differential theory (Elton & Gruber, 1970)"],
    "source_support_for_key": {
      "source_id": "Elton & Gruber (1970)",
      "rule_or_proposition": "Repurchases offer a tax advantage because shareholders can defer capital gains by not selling",
      "application_to_facts": "Chen faces immediate taxation on dividends; under a repurchase, he controls timing",
      "key_conclusion": "Repurchases are more tax-efficient for shareholders with unrealized gains"
    },
    "distractor_intent": {
      "B": {"misconception": "Assuming equal tax treatment", "why_plausible": "Historical tax reforms have periodically equalized rates, but deferral advantage remains", "tier_candidate": 1},
      "C": {"misconception": "Believing the corporation pays tax on repurchases", "why_plausible": "Companies pay tax on earnings, but repurchases are not a corporate taxable event", "tier_candidate": 2},
      "D": {"misconception": "Confusing DRIP deferral with actual tax deferral", "why_plausible": "DRIPs reinvest dividends but do not defer taxation", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly identifies the tax differential and deferral advantage. Option B ignores deferral. Option C incorrectly attributes corporate tax. Option D misstates DRIP treatment.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The tax differential theory (Elton & Gruber, 1970) identifies two advantages of repurchases: (1) capital gains rates may be lower than dividend rates, and (2) repurchases allow tax deferral. Under a dividend, Chen is taxed immediately. Under a repurchase, if he does not sell, he owes no current tax. If he sells, he pays capital gains only on the gain above his $25 basis.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Even if rates were identical, the deferral advantage remains. Under a dividend, Chen is taxed immediately. Under a repurchase, he controls the timing of gain realization.",
    "ExplanationWrongC": "Share repurchases are not a corporate taxable event. The company uses after-tax cash to buy back shares. The shareholder recognizes gain or loss upon selling.",
    "ExplanationWrongD": "A DRIP reinvests dividends but the shareholder is still taxed on the dividend in the year received. DRIPs do not provide tax deferral."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Stock repurchase effects on EPS",
    "QuestionID": "P2-B-509",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-509-repurchase-book-value-per-share",
    "Stem": "Vanguard Precision reports shareholders' equity of $240 million, 30 million shares outstanding, and cash of $60 million. The board approves a $60 million share repurchase at $40 per share. CFO Diane Lancaster must determine the effect on book value per share after the repurchase.",
    "Choices": {
      "A": "Book value per share increases from $8.00 to $8.57 because the repurchase reduces equity by $60 million and shares by 1.5 million.",
      "B": "Book value per share remains $8.00 because the repurchase is a balance sheet exchange with no net effect on equity per share.",
      "C": "Book value per share decreases from $8.00 to $6.32 because the repurchase at $40 per share is far above book value, reducing equity proportionally more than shares.",
      "D": "Book value per share increases from $8.00 to $10.00 because the share count reduction is proportionally larger than the equity reduction."
    },
    "CorrectChoice": "C",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "BVPS = Total Shareholders' Equity / Common Shares Outstanding",
    "Authorities": ["ASC 205-10", "Corporate finance theory"],
    "source_ids": ["FA-18: Book Value per Share"],
    "source_support_for_key": {
      "source_id": "FA-18",
      "rule_or_proposition": "BVPS = Equity / Shares; repurchase at market price above BVPS reduces BVPS",
      "application_to_facts": "Pre-repurchase BVPS = $240M/30M = $8.00; repurchase at $40 >> $8.00; post-repurchase equity=$180M, shares=28.5M",
      "key_conclusion": "BVPS decreases because shares are repurchased at a premium to book value"
    },
    "distractor_intent": {
      "A": {"misconception": "Assuming BVPS increases like EPS", "why_plausible": "EPS increases with repurchase; candidates may assume BVPS follows the same pattern", "tier_candidate": 1},
      "B": {"misconception": "Assuming no per-share effect", "why_plausible": "Balance sheet exchange but per-share ratio changes when both numerator and denominator shrink at different rates", "tier_candidate": 2},
      "D": {"misconception": "Overstating the increase", "why_plausible": "Candidates may confuse share count reduction with equity reduction ratio", "tier_candidate": 3}
    },
    "uniqueness_note": "Option C correctly identifies BVPS decreases when repurchasing above book value. Option A incorrectly assumes BVPS increases. Option B ignores per-share ratio change. Option D overstates.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "Pre-repurchase BVPS = $240M/30M = $8.00. The repurchase buys $60M/$40 = 1.5M shares. Post-repurchase: equity = $180M, shares = 28.5M. BVPS = $180M/28.5M = $6.32. The BVPS decreases because shares are repurchased at $40, far above the $8.00 book value. When repurchasing above BVPS, each share retires more equity than it contributes to the count.",
    "ExplanationWrongA": "While EPS increases with a repurchase, BVPS moves in the opposite direction when the repurchase price exceeds BVPS. The $40 repurchase cost creates a deficit absorbed by remaining shareholders.",
    "ExplanationWrongB": "The repurchase is not neutral on a per-share basis. Both equity and shares decrease, but equity decreases proportionally more because $40 >> $8.00 BVPS.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Share count reduction is 5% (1.5M/30M), while equity decreases 25% ($60M/$240M). Equity decreases proportionally more, resulting in lower BVPS."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Dividend reinvestment plans (DRIPs)",
    "QuestionID": "P2-B-510",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-510-drip-dividend-reinvestment-plan",
    "Stem": "Oakmont Healthcare offers a voluntary dividend reinvestment plan (DRIP) allowing shareholders to automatically reinvest quarterly dividends into additional shares at a 3% discount to market price. With the stock at $50 and a quarterly dividend of $0.60 per share, VP of Investor Relations Caroline Manning must explain the primary benefit of the DRIP to a shareholder who reinvests.",
    "Choices": {
      "A": "The DRIP provides a 3% discount on shares acquired through dividend reinvestment, effectively increasing the shareholder's total return relative to receiving cash dividends and purchasing shares on the open market.",
      "B": "The DRIP eliminates all taxes on dividend income because the dividends are reinvested rather than received as cash.",
      "C": "The DRIP guarantees a higher stock price because the automatic buying creates consistent demand pressure on the market.",
      "D": "The DRIP allows shareholders to avoid brokerage commissions, which is the primary economic benefit regardless of the discount."
    },
    "CorrectChoice": "D",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Understand",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "N/A — conceptual",
    "Authorities": ["Corporate finance theory"],
    "source_ids": ["DRIP discount mechanism"],
    "source_support_for_key": {
      "source_id": "DRIP mechanics",
      "rule_or_proposition": "DRIPs reinvest dividends automatically; commission elimination is the most universal benefit",
      "application_to_facts": "While this plan offers a 3% discount, commission-free is the primary universal DRIP benefit",
      "key_conclusion": "Commission elimination is the primary economic benefit of DRIPs"
    },
    "distractor_intent": {
      "A": {"misconception": "Focusing on the discount when the question asks about the primary benefit of DRIPs in general", "why_plausible": "The 3% discount is real for this plan but not universal", "tier_candidate": 1},
      "B": {"misconception": "Believing DRIPs provide tax deferral", "why_plausible": "Reinvested dividends are still taxable as income", "tier_candidate": 2},
      "C": {"misconception": "Assuming automatic buying creates price support", "why_plausible": "DRIP volumes are typically too small to affect market price", "tier_candidate": 3}
    },
    "uniqueness_note": "Option D correctly identifies commission elimination as the primary universal DRIP benefit. Option A focuses on a plan-specific discount. Option B misstates tax treatment. Option C overstates market impact.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The primary economic benefit of DRIPs is the elimination of brokerage commissions on share purchases. When shareholders reinvest dividends through a DRIP, they acquire additional shares without paying transaction costs. While some DRIPs offer discounts, commission elimination is the universal feature that makes DRIPs economically attractive across all participating companies.",
    "ExplanationWrongA": "While the 3% discount is a genuine benefit of Oakmont's specific DRIP, it is not the primary benefit of DRIPs in general. Many DRIPs do not offer discounts. Commission-free is the universal benefit.",
    "ExplanationWrongB": "Dividends reinvested through a DRIP are still taxable as ordinary income in the year received. The IRS treats reinvested dividends identically to cash dividends.",
    "ExplanationWrongC": "DRIP purchases are typically a tiny fraction of a stock's daily trading volume. DRIP-driven buying would be negligible relative to market liquidity.",
    "ExplanationWrongD": ""
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Bird-in-the-hand theory",
    "QuestionID": "P2-B-511",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-511-bird-in-the-hand-theory-dividend-preference",
    "Stem": "Caldwell Energy's CFO is debating whether to increase the dividend or retain earnings for growth. The company has a required return of 10%. Under the bird-in-the-hand theory (Gordon, 1963), CFO Raymond Trent must explain how the dividend decision affects the stock valuation.",
    "Choices": {
      "A": "The stock value equals the present value of all future dividends discounted at the required return; under the bird-in-the-hand theory, higher current dividends reduce perceived risk and increase valuation.",
      "B": "The stock value is determined solely by the growth rate of earnings; dividend policy is irrelevant because investors can create homemade dividends.",
      "C": "The stock value decreases when dividends increase because retained earnings generate higher returns than distributions to shareholders.",
      "D": "The stock value is maximized when the payout ratio is zero because all earnings are reinvested at the required return, compounding shareholder wealth."
    },
    "CorrectChoice": "A",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "CB-11: Cost of Common Equity — Dividend Discount Model (Gordon Growth)",
    "Authorities": ["Modigliani-Miller dividend irrelevance (1961)", "Bird-in-the-hand theory (Gordon, 1963)"],
    "source_ids": ["Gordon (1963) Bird-in-the-Hand Theory"],
    "source_support_for_key": {
      "source_id": "Gordon (1963)",
      "rule_or_proposition": "Investors prefer the certainty of dividends over uncertain capital gains; higher current dividends reduce perceived risk and increase valuation",
      "application_to_facts": "Under bird-in-the-hand, Caldwell's dividend decision affects stock value through perceived risk",
      "key_conclusion": "Bird-in-the-hand predicts higher dividends increase stock value by reducing perceived risk"
    },
    "distractor_intent": {
      "B": {"misconception": "Stating MM irrelevance when the question asks about bird-in-the-hand", "why_plausible": "MM irrelevance is a foundational concept; candidates may default to it", "tier_candidate": 1},
      "C": {"misconception": "Assuming dividends always reduce value", "why_plausible": "If ROE > R_e, retention creates value, but not universally true", "tier_candidate": 2},
      "D": {"misconception": "Applying MM zero-payout prediction when the question asks about bird-in-the-hand", "why_plausible": "MM predicts zero-payout maximization; bird-in-the-hand predicts the opposite", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly states bird-in-the-hand theory. Option B states MM irrelevance generally. Option C assumes dividends always reduce value. Option D applies MM zero-payout prediction.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The bird-in-the-hand theory (Gordon, 1963) argues that investors prefer the certainty of current dividends over uncertain future capital gains. Under this theory, higher current dividends reduce perceived risk and increase the stock's valuation. Caldwell's CFO should recognize that increasing the dividend would be viewed positively because shareholders value the reliable income stream more highly than uncertain future growth.",
    "ExplanationWrongB": "Modigliani and MM argue dividend policy is irrelevant in perfect markets. However, the question asks specifically about the bird-in-the-hand theory, which directly contradicts MM irrelevance by asserting dividends affect value.",
    "ExplanationWrongC": "This incorrectly assumes dividends always reduce value. Under the bird-in-the-hand theory, dividends increase value by reducing perceived risk. Whether retention or distribution creates more value depends on the firm's investment opportunities and required return.",
    "ExplanationWrongD": "Modigliani and MM predict a zero-payout policy maximizes value in perfect markets. However, the question asks about the bird-in-the-hand theory, which predicts the opposite — higher dividends increase value by reducing uncertainty."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Agency costs and dividends",
    "QuestionID": "P2-B-512",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-512-agency-costs-dividend-discipline",
    "Stem": "Pinpoint Analytics CEO has a history of acquiring unrelated businesses that destroy shareholder value. The board is under pressure from activist investors to adopt a higher dividend payout policy. Governance Consultant Maria Santos must explain how dividends can reduce agency costs between shareholders and management.",
    "Choices": {
      "A": "Higher dividends reduce free cash flow available for empire-building acquisitions, forcing management to seek external financing for investments and subjecting them to market discipline.",
      "B": "Higher dividends increase agency costs because managers have less cash to meet operational needs, creating a conflict between dividend payments and operational efficiency.",
      "C": "Dividends have no effect on agency costs because shareholders can vote out the board regardless of the dividend policy.",
      "D": "Lower dividends reduce agency costs because managers can use retained earnings to invest in positive-NPV projects without the cost of external financing."
    },
    "CorrectChoice": "A",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "N/A — conceptual",
    "Authorities": ["Agency theory of dividends (Jensen, 1986)", "Free cash flow hypothesis"],
    "source_ids": ["Jensen (1986) Agency Theory — Free Cash Flow"],
    "source_support_for_key": {
      "source_id": "Jensen (1986)",
      "rule_or_proposition": "Higher dividends reduce free cash flow available for empire-building, forcing managers to seek external financing and face market discipline",
      "application_to_facts": "Pinpoint's CEO has a history of destructive acquisitions; higher dividends would limit discretionary cash",
      "key_conclusion": "Dividends reduce agency costs by limiting free cash flow"
    },
    "distractor_intent": {
      "B": {"misconception": "Claiming dividends increase agency costs rather than reduce them", "why_plausible": "Reduced operational flexibility is a countervailing cost, but the question asks how dividends REDUCE agency costs", "tier_candidate": 1},
      "C": {"misconception": "Assuming governance mechanisms make dividends irrelevant", "why_plausible": "Board elections are a governance mechanism but less direct than dividend discipline", "tier_candidate": 2},
      "D": {"misconception": "Arguing retained earnings reduce agency costs", "why_plausible": "Lower dividends preserve investment flexibility but increase agency costs when management invests poorly", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly applies Jensen's free cash flow hypothesis. Option B contradicts the question's premise. Option C dismisses the mechanism. Option D contradicts free cash flow theory.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "Jensen's (1986) free cash flow hypothesis predicts that higher dividends reduce agency costs by limiting the free cash flow available for empire-building acquisitions. When Pinpoint's CEO has a history of destructive acquisitions, distributing excess cash as dividends forces management to seek external financing for any new investments, subjecting them to market discipline and scrutiny. This reduces the agency cost between shareholders and management.",
    "ExplanationWrongB": "While reduced operational flexibility is a countervailing agency cost of higher dividends, the question asks how dividends REDUCE agency costs. Option B states the opposite — that dividends increase agency costs — which contradicts the question's premise.",
    "ExplanationWrongC": "While shareholders can theoretically vote out the board, this mechanism is slow and costly. Dividend payments provide a more immediate disciplinary mechanism by reducing discretionary cash.",
    "ExplanationWrongD": "This is the opposite of Jensen's prediction. When managers have a history of poor investment decisions, lower dividends give management more unrestricted cash, increasing the agency cost of free cash flow."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Clientele effect",
    "QuestionID": "P2-B-513",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-513-clientele-effect-dividend-policy",
    "Stem": "Silverleaf REIT historically pays high dividends that attract income-oriented retirees. When the board proposes cutting the dividend to fund a major property acquisition, institutional investor Marcus Webb argues the stock price will decline. Vice Chair Diane Foster must explain the clientele effect prediction.",
    "Choices": {
      "A": "The dividend cut will likely cause the stock price to decline because income-oriented investors will sell, and the shares must attract a new clientele of growth-oriented investors willing to accept a lower yield.",
      "B": "The dividend cut will increase the stock price because growth investors will value the retained earnings more highly than income investors value the dividend.",
      "C": "The stock price will be unaffected because the clientele effect implies that all investor types have identical preferences for dividend policy.",
      "D": "The stock price will decline temporarily but recover once the property acquisition is completed and earnings increase."
    },
    "CorrectChoice": "A",
    "Difficulty": "Very Difficult",
    "DifficultyScore": 5,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "N/A — conceptual",
    "Authorities": ["Clientele effect (Miller & Modigliani, 1961)"],
    "source_ids": ["Miller & Modigliani (1961) Clientele Effect"],
    "source_support_for_key": {
      "source_id": "Miller & Modigliani (1961)",
      "rule_or_proposition": "Different investor groups prefer different dividend policies; changing policy causes the current clientele to sell and attracts a new one, with price impact during transition",
      "application_to_facts": "Silverleaf's retiree clientele depends on high dividends; a cut forces selling, depressing price until a new clientele emerges",
      "key_conclusion": "The clientele effect predicts a price decline as the shareholder base transitions"
    },
    "distractor_intent": {
      "B": {"misconception": "Assuming growth investors immediately dominate", "why_plausible": "Growth investors may eventually buy but transition involves selling pressure", "tier_candidate": 1},
      "C": {"misconception": "Confusing clientele effect with dividend irrelevance", "why_plausible": "Clientele effect is sometimes used to support irrelevance but transition creates price impact", "tier_candidate": 2},
      "D": {"misconception": "Assuming decline is temporary and driven by acquisition", "why_plausible": "Acquisitions can boost value but clientele selling is separate and persistent", "tier_candidate": 3}
    },
    "uniqueness_note": "Option A correctly predicts clientele-driven price decline. Option B assumes immediate transition. Option C conflates with irrelevance. Option D attributes to acquisition.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The clientele effect (Miller & Modigliani, 1961) predicts that firms attract investors who prefer their specific dividend policy. Silverleaf's high-dividend policy attracts income-oriented retirees. When the dividend is cut, this clientele faces a mismatch and will sell, creating selling pressure. The shares must then attract a new clientele of growth-oriented investors. During this transition, the stock trades at a discount.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "The clientele effect does not predict an immediate transition. The transition involves selling pressure from the departing income clientele, depressing the stock price.",
    "ExplanationWrongC": "The clientele effect explicitly predicts that investor groups have DIFFERENT dividend preferences. This is why clienteles form. The price impact occurs because of the mismatch.",
    "ExplanationWrongD": "While the acquisition may boost earnings, the clientele-driven selling pressure is a direct consequence of the dividend cut itself, independent of the acquisition's merit."
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Payout ratio analysis",
    "QuestionID": "P2-B-514",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-514-payout-ratio-retention-ratio-relationship",
    "Stem": "Granite Industries reports EPS of $4.80 and dividends per share of $1.92. The company's ROE is 16% and the required return on equity is 12%. CFO Steven Park must analyze whether Granite's retention of earnings is creating or destroying shareholder value.",
    "Choices": {
      "A": "Value is being created because the ROE of 16% exceeds the required return of 12%, meaning retained earnings earn returns above what investors demand, and the retention ratio of 60% is appropriate.",
      "B": "Value is being destroyed because the payout ratio of 40% is below the industry average of 50%, indicating the company is hoarding cash unnecessarily.",
      "C": "Value is being created because the dividend yield of 4.0% exceeds the risk-free rate, indicating above-market income for shareholders.",
      "D": "Value is neutral because the payout ratio and retention ratio always sum to 100%, so the distribution method is irrelevant to total shareholder return."
    },
    "CorrectChoice": "D",
    "Difficulty": "Very Difficult",
    "DifficultyScore": 5,
    "CognitiveLevel": "Analyze",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "SGR = ROE x Retention Ratio",
    "Authorities": ["Modigliani-Miller dividend irrelevance (1961)", "Corporate finance theory"],
    "source_ids": ["Modigliani-Miller (1961) Dividend Irrelevance"],
    "source_support_for_key": {
      "source_id": "Modigliani-Miller (1961)",
      "rule_or_proposition": "In perfect capital markets, dividend policy is irrelevant; total return is unaffected by payout ratio",
      "application_to_facts": "MM argues whether Granite retains 60% or pays it out, total shareholder return is the same",
      "key_conclusion": "Under MM, the payout ratio is irrelevant to total shareholder return"
    },
    "distractor_intent": {
      "A": {"misconception": "Applying ROE vs. R_e criterion when the question asks about MM irrelevance", "why_plausible": "ROE > R_e is valid with frictions, but MM predicts irrelevance in perfect markets", "tier_candidate": 1},
      "B": {"misconception": "Comparing payout to industry average without considering value creation", "why_plausible": "Industry comparison misses the ROE vs. R_e criterion", "tier_candidate": 2},
      "C": {"misconception": "Using dividend yield instead of ROE vs. R_e", "why_plausible": "Dividend yield is relevant for income analysis, not value creation", "tier_candidate": 3}
    },
    "uniqueness_note": "Option D correctly states MM irrelevance. Option A applies ROE vs. R_e. Option B uses irrelevant benchmark. Option C uses wrong metric.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "Modigliani and Miller (1961) argue that in perfect capital markets, dividend policy is irrelevant to firm value. The payout and retention ratios always sum to 100%, and the distribution method does not affect total shareholder return. Whether Granite retains 60% or pays it out, the total return (dividends plus capital gains) is determined by the firm's investment policy and earning power, not the payout ratio. Under MM assumptions, investors can create homemade dividends, making the corporate dividend decision irrelevant.",
    "ExplanationWrongA": "This applies the ROE vs. R_e criterion, which is valid in the presence of market frictions (taxes, flotation costs, information asymmetry). However, under MM irrelevance, the distribution method is irrelevant because investors can replicate any payout policy independently.",
    "ExplanationWrongB": "The payout ratio's relationship to industry averages is irrelevant to the value creation question. The relevant comparison is ROE vs. R_e. A company with ROE above R_e should retain more, regardless of what industry peers do.",
    "ExplanationWrongC": "The dividend yield relative to the risk-free rate is not the correct criterion for value creation. The relevant comparison is ROE vs. R_e. A high dividend yield may simply reflect a depressed stock price, not value creation.",
    "ExplanationWrongD": ""
  },
  {
    "Part": 2,
    "schema_version": "1.1",
    "Section": "B",
    "Topic": "B.7 Tax differential theory",
    "QuestionID": "P2-B-515",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "b-515-tax-differential-theory-dividend-irrelevance",
    "Stem": "Blackwell Industries' board is debating whether to initiate a regular dividend for the first time. CEO James Foreman argues that dividend policy is irrelevant under the tax differential theory. CFO Laura Simmons counters that the theory actually favors repurchases. The board chair asks which statement is correct regarding the tax differential theory's prediction for the stock price.",
    "Choices": {
      "A": "The tax differential theory predicts that repurchases are tax-advantaged over dividends because capital gains are taxed at lower rates and can be deferred, whereas dividends are taxed immediately upon receipt.",
      "B": "The tax differential theory predicts that dividends are tax-advantaged over capital gains because dividends receive preferential tax treatment under current law.",
      "C": "The tax differential theory predicts that dividend policy is fully irrelevant because tax rates on dividends and capital gains are identical.",
      "D": "The tax differential theory predicts that initiating dividends will increase the stock price because the tax advantage of dividends attracts tax-sensitive investors."
    },
    "CorrectChoice": "C",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "B.7",
    "BlueprintDomain": "Corporate Finance",
    "FormulaReference": "N/A — conceptual",
    "Authorities": ["Tax differential theory (Elton & Gruber, 1970)", "Modigliani-Miller dividend irrelevance (1961)"],
    "source_ids": ["Elton & Gruber (1970) Tax Differential Theory"],
    "source_support_for_key": {
      "source_id": "Elton & Gruber (1970)",
      "rule_or_proposition": "When dividend and capital gains tax rates are equal, the tax differential theory predicts dividend irrelevance",
      "application_to_facts": "If Blackwell's shareholders face equal tax rates, the theory predicts no stock price effect from initiating dividends",
      "key_conclusion": "With equal tax rates, the tax differential theory predicts irrelevance"
    },
    "distractor_intent": {
      "A": {"misconception": "Applying tax differential advantage when the question assumes equal rates", "why_plausible": "The differential advantage is commonly discussed but the question tests equal-rate scenario", "tier_candidate": 1},
      "B": {"misconception": "Reversing the tax differential advantage", "why_plausible": "Historical tax law has varied; candidates may not know current structures", "tier_candidate": 2},
      "D": {"misconception": "Claiming dividends have a tax advantage", "why_plausible": "Some investors prefer dividends but the theory does not predict this under equal rates", "tier_candidate": 3}
    },
    "uniqueness_note": "Option C correctly states the theory's prediction when rates are equal. Option A states the differential advantage. Option B reverses the advantage. Option D claims tax advantage for dividends.",
    "source_status": "RESOLVED",
    "hold_reason": "",
    "ExplanationCorrect": "The tax differential theory (Elton & Gruber, 1970) predicts that when dividend and capital gains tax rates are equal, dividend policy is irrelevant because there is no tax advantage to either distribution method. CEO Foreman's statement is correct when tax rates are equalized. Under equal rates, shareholders are indifferent between dividends and capital gains from a tax perspective. The theory converges with MM irrelevance.",
    "ExplanationWrongA": "This states the theory's prediction when capital gains rates are lower. However, the question asks about equal rates, which produces irrelevance. The theory's prediction depends on the tax rate structure.",
    "ExplanationWrongB": "The tax differential theory does not predict dividends are tax-advantaged. Historically, capital gains have been taxed at lower rates, making them tax-advantaged.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "The tax differential theory does not predict that dividends attract tax-sensitive investors. Under equal rates, investors are indifferent from a tax perspective."
  }
];

module.exports = { pack_p2_b_batch1_questions };
