// P2-C-681 through P2-C-695 — Domain C Decision Analysis, LOS C.1 CVP Analysis Fundamentals
// Schema: v1.1 — all required fields including distractor_intent, source_ids, source_support_for_key
// Governance: Rules 2/6/9/10/11/13/14 active
// Distribution: 2E / 3ME / 5M / 3D / 2VD | R1/U3/Ap7/An3/Ev1 | 4A/4B/5C/2D, max streak 2

const pack_p2_c_batch5_questions = [
  {
    "Part": 2, "Section": "C", "Topic": "C.681 cost-behavior-relevant-range",
    "QuestionID": "P2-C-681", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-681-cost-behavior-relevant-range",
    "Stem": "Which of the following correctly describes cost behavior within the relevant range?",
    "Choices": {"A": "Total fixed costs remain constant and variable cost per unit remains constant", "B": "Total variable costs remain constant and fixed cost per unit remains constant", "C": "Total fixed costs increase proportionally with volume and variable cost per unit decreases", "D": "Both total fixed costs and variable cost per unit remain constant"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Within the relevant range, total fixed costs remain constant regardless of changes in activity level, while variable cost per unit remains constant. Total variable costs change in direct proportion to activity, but the per-unit variable cost does not. This is the fundamental assumption underlying CVP analysis.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Total variable costs change with activity level. Fixed cost per unit changes inversely with volume. This answer reverses the correct behavior patterns.",
    "ExplanationWrongC": "Total fixed costs remain constant within the relevant range. Variable cost per unit also remains constant. This describes behavior outside the relevant range.",
    "ExplanationWrongD": "While total fixed costs remain constant, this answer omits that total variable costs change with activity level. The correct answer (A) captures both sides completely.",
    "FormulaReference": "Cost behavior fundamentals",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Easy", "DifficultyScore": 1, "CognitiveLevel": "Remember", "CalculationItem": false,
    "CommonTrapReference": "Confusing total fixed costs with fixed cost per unit",
    "Authorities": ["IMA SMA on relevant costing", "Cost behavior theory"],
    "source_ids": ["DA-01: Cost behavior within relevant range"],
    "source_support_for_key": {"fixed_costs": "Total constant within relevant range", "variable_costs": "Total varies proportionally; per unit constant"},
    "distractor_intent": {"B": {"misconception": "Reversing fixed and variable behavior", "why_plausible": "Confusing which is constant in total vs per unit", "tier_candidate": "B"}, "C": {"misconception": "Fixed costs increase with volume", "why_plausible": "Outside relevant range they step up", "tier_candidate": "C"}, "D": {"misconception": "Incomplete answer", "why_plausible": "Partially correct but misses total variable cost distinction", "tier_candidate": "C"}},
    "uniqueness_note": "Option A uniquely captures both cost behaviors correctly.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Definition-match item"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.682 variable-costing-operating-income",
    "QuestionID": "P2-C-682", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-682-variable-costing-operating-income",
    "Stem": "Pinnacle Electronics manufactures a single product. Sales: 8,000 units at $80 each. Variable manufacturing cost: $35 per unit. Variable selling expense: $10 per unit. Fixed manufacturing overhead: $200,000. Fixed selling and administrative: $50,000. Using variable costing, what is operating income?",
    "Choices": {"A": "$30,000", "B": "$70,000", "C": "$310,000", "D": "$230,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Operating income = Sales - Variable costs - Fixed costs. Sales = 8,000 x $80 = $640,000. Variable costs = ($35 + $10) x 8,000 = $360,000. Fixed costs = $200,000 + $50,000 = $250,000. Operating income = $640,000 - $360,000 - $250,000 = $30,000.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$70,000 results from computing contribution margin ($280,000) minus only fixed manufacturing overhead ($200,000), omitting the $50,000 fixed selling and administrative expense.",
    "ExplanationWrongC": "$310,000 results from computing sales minus variable manufacturing costs only, omitting variable selling expenses.",
    "ExplanationWrongD": "$230,000 results from computing gross margin under absorption costing rather than contribution margin under variable costing.",
    "FormulaReference": "Variable costing operating income",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Omitting variable selling expenses; confusing variable with absorption costing",
    "Authorities": ["IMA SMA on relevant costing", "Variable vs. absorption costing theory"],
    "source_ids": ["DA-01: Variable costing income calculation"],
    "source_support_for_key": {"sales": "8,000 x $80 = $640,000", "variable_costs": "($35 + $10) x 8,000 = $360,000", "fixed_costs": "$200,000 + $50,000 = $250,000", "operating_income": "$640,000 - $360,000 - $250,000 = $30,000"},
    "distractor_intent": {"B": {"misconception": "Omitting fixed S&A expenses", "why_plausible": "Focus only on manufacturing costs", "tier_candidate": "B"}, "C": {"misconception": "Omitting variable selling expenses", "why_plausible": "Overlooked when computing contribution margin", "tier_candidate": "B"}, "D": {"misconception": "Confusing absorption with variable costing", "why_plausible": "Absorption starts with gross margin", "tier_candidate": "C"}},
    "uniqueness_note": "$30,000 uniquely results from the correct variable costing calculation.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $640K - $360K - $250K = $30K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.683 weighted-average-contribution-margin",
    "QuestionID": "P2-C-683", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-683-weighted-average-contribution-margin",
    "Stem": "Northridge Electronics manufactures Alpha (CM $40/unit) and Beta (CM $25/unit). Sales mix is 60% Alpha and 40% Beta by unit. What is the weighted average contribution margin per unit?",
    "Choices": {"A": "$32.50", "B": "$34.00", "C": "$34.50", "D": "$38.00"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "WACM = ($40 x 0.60) + ($25 x 0.40) = $24 + $10 = $34.00. The sales mix must be expressed as unit percentages for the WACM calculation.",
    "ExplanationWrongA": "$32.50 results from simple averaging: ($40 + $25) / 2 = $32.50. This assumes a 50/50 mix, contradicting the stated 60/40 mix.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "$34.50 results from using revenue-based weights instead of unit-based weights. The WACM uses unit sales mix.",
    "ExplanationWrongD": "$38.00 results from a miscalculation in the weighting formula. The correct approach weights each product CM by its unit mix percentage.",
    "FormulaReference": "DA-06: WACM = Sigma(Sales Mix_i x CM_i)",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Using revenue mix instead of unit mix",
    "Authorities": ["IMA SMA on relevant costing", "Multi-product CVP analysis"],
    "source_ids": ["DA-06: WACM formula"],
    "source_support_for_key": {"alpha": "$40 x 0.60 = $24", "beta": "$25 x 0.40 = $10", "WACM": "$24 + $10 = $34.00"},
    "distractor_intent": {"A": {"misconception": "Simple average without weighting", "why_plausible": "Common shortcut error", "tier_candidate": "B"}, "C": {"misconception": "Revenue mix instead of unit mix", "why_plausible": "Revenue percentages may differ", "tier_candidate": "C"}, "D": {"misconception": "Miscalculation in weighting", "why_plausible": "Arithmetic error", "tier_candidate": "C"}},
    "uniqueness_note": "$34.00 uniquely results from the correct WACM calculation.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $24 + $10 = $34"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.684 degree-of-operating-leverage",
    "QuestionID": "P2-C-684", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-684-degree-of-operating-leverage",
    "Stem": "Sunrise Industries reports contribution margin of $360,000 and operating income of $120,000. If sales increase by 10%, by what percentage will operating income increase?",
    "Choices": {"A": "20%", "B": "30%", "C": "10%", "D": "36%"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "DOL = $360,000 / $120,000 = 3.0. A 10% sales increase produces 3.0 x 10% = 30% increase in operating income.",
    "ExplanationWrongA": "20% results from an incorrect DOL calculation. The correct DOL is 3.0, producing 30%.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "10% assumes proportional change without the leverage effect of fixed costs.",
    "ExplanationWrongD": "36% results from using the CM ratio instead of DOL.",
    "FormulaReference": "DA-05: DOL = CM / Operating Income",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate-Easy", "DifficultyScore": 2, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Inverting DOL formula; confusing DOL with CM ratio",
    "Authorities": ["IMA SMA on relevant costing", "Operating leverage theory"],
    "source_ids": ["DA-05: DOL formula"],
    "source_support_for_key": {"DOL": "$360,000 / $120,000 = 3.0", "income_increase": "3.0 x 10% = 30%"},
    "distractor_intent": {"A": {"misconception": "Incorrect DOL", "why_plausible": "Formula error", "tier_candidate": "B"}, "C": {"misconception": "Ignoring leverage", "why_plausible": "No amplification assumed", "tier_candidate": "C"}, "D": {"misconception": "Using CM ratio", "why_plausible": "CM ratio x 60% = 36%", "tier_candidate": "C"}},
    "uniqueness_note": "30% uniquely results from DOL = 3.0 x 10%.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: DOL=3.0, 3.0x10%=30%"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.685 mixed-cost-separation-high-low",
    "QuestionID": "P2-C-685", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-685-mixed-cost-separation-high-low",
    "Stem": "Greenfield Manufacturing uses the high-low method. Month 3 (high): 12,000 units, $180,000 total cost. Month 1 (low): 4,000 units, $100,000 total cost. What is the predicted total cost at 9,000 units?",
    "Choices": {"A": "$142,500", "B": "$157,500", "C": "$135,000", "D": "$150,000"},
    "CorrectChoice": "D",
    "ExplanationCorrect": "VC per unit = ($180,000 - $100,000) / (12,000 - 4,000) = $10. Fixed cost = $180,000 - ($10 x 12,000) = $60,000. Predicted cost = $60,000 + ($10 x 9,000) = $150,000.",
    "ExplanationWrongA": "$142,500 results from a miscalculation of the variable cost per unit. The correct rate is exactly $10 per unit.",
    "ExplanationWrongB": "$157,500 results from an incorrect variable cost rate or fixed cost calculation.",
    "ExplanationWrongC": "$135,000 results from an incorrect fixed cost calculation. The correct fixed cost is $60,000.",
    "ExplanationWrongD": "",
    "FormulaReference": "High-low method",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Using non-extreme points; miscalculating fixed cost",
    "Authorities": ["IMA SMA on relevant costing", "Cost estimation theory"],
    "source_ids": ["DA-01: High-low method"],
    "source_support_for_key": {"VC": "$80,000 / 8,000 = $10", "FC": "$180,000 - $120,000 = $60,000", "predicted": "$60,000 + $90,000 = $150,000"},
    "distractor_intent": {"A": {"misconception": "Miscalculation of VC per unit", "why_plausible": "Arithmetic error in high-low ratio", "tier_candidate": "C"}, "B": {"misconception": "Incorrect VC rate or FC", "why_plausible": "Error in subtraction or division", "tier_candidate": "C"}, "C": {"misconception": "Incorrect FC", "why_plausible": "Error in FC calculation", "tier_candidate": "C"}},
    "uniqueness_note": "$150,000 uniquely results from the correct high-low calculation.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (D)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $60K + $10 x 9K = $150K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.686 breakeven-units-calculation",
    "QuestionID": "P2-C-686", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-686-breakeven-units-calculation",
    "Stem": "Oakfield Electronics sells a product for $200 per unit. Variable costs are $120 per unit. Fixed costs total $600,000. What is the breakeven point in units?",
    "Choices": {"A": "7,500 units", "B": "5,000 units", "C": "3,000 units", "D": "10,000 units"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "CM per unit = $200 - $120 = $80. Breakeven units = $600,000 / $80 = 7,500 units. At 7,500 units, total CM = 7,500 x $80 = $600,000, exactly covering fixed costs.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "5,000 results from using an incorrect CM per unit. The correct divisor is $80.",
    "ExplanationWrongC": "3,000 results from dividing fixed costs by selling price ($600,000 / $200 = 3,000), ignoring variable costs.",
    "ExplanationWrongD": "10,000 results from dividing by variable cost per unit ($600,000 / $120 = 5,000) and doubling.",
    "FormulaReference": "DA-01: BE = FC / CM per Unit",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Easy", "DifficultyScore": 1, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Dividing by selling price instead of CM",
    "Authorities": ["IMA SMA on relevant costing", "CVP analysis"],
    "source_ids": ["DA-01: Breakeven formula"],
    "source_support_for_key": {"CM": "$200 - $120 = $80", "BE": "$600,000 / $80 = 7,500"},
    "distractor_intent": {"B": {"misconception": "Wrong divisor", "why_plausible": "Incorrect CM per unit", "tier_candidate": "C"}, "C": {"misconception": "Using selling price", "why_plausible": "$200 is prominent", "tier_candidate": "B"}, "D": {"misconception": "Using variable cost", "why_plausible": "$120 may be used by mistake", "tier_candidate": "C"}},
    "uniqueness_note": "7,500 uniquely results from $600K / $80.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $600K / $80 = 7,500"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.687 absorption-costing-income",
    "QuestionID": "P2-C-687", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-687-absorption-costing-income",
    "Stem": "Oakmont Furniture: Production 10,000 units, sales 8,000 at $100 each. Variable manufacturing $35/unit. Fixed manufacturing overhead $200,000. Variable selling $8/unit. Fixed S&A $60,000. Under absorption costing, operating income?",
    "Choices": {"A": "$236,000", "B": "$196,000", "C": "$176,000", "D": "$256,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Fixed overhead per unit = $200,000 / 10,000 = $20. Absorption cost = $35 + $20 = $55. COGS = 8,000 x $55 = $440,000. Sales = $800,000. Gross margin = $360,000. S&A = $64,000 + $60,000 = $124,000. Operating income = $360,000 - $124,000 = $236,000.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$196,000 is variable costing income ($236,000 - $40,000 deferred overhead).",
    "ExplanationWrongC": "$176,000 is variable costing income without the inventory deferral adjustment.",
    "ExplanationWrongD": "$256,000 results from an arithmetic error in the multi-step calculation.",
    "FormulaReference": "Absorption costing income statement",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationItem": true,
    "CommonTrapReference": "Confusing absorption with variable costing",
    "Authorities": ["IMA SMA on relevant costing", "Absorption vs. variable costing"],
    "source_ids": ["DA-01: Absorption costing income"],
    "source_support_for_key": {"fixed_per_unit": "$200K/10K = $20", "absorption_cost": "$35 + $20 = $55", "COGS": "8K x $55 = $440K", "gross_margin": "$800K - $440K = $360K", "income": "$360K - $124K = $236K"},
    "distractor_intent": {"B": {"misconception": "Variable costing income", "why_plausible": "Yields $196K", "tier_candidate": "B"}, "C": {"misconception": "No inventory adjustment", "why_plausible": "Variable costing income", "tier_candidate": "B"}, "D": {"misconception": "Arithmetic error", "why_plausible": "Multi-step calculation", "tier_candidate": "C"}},
    "uniqueness_note": "$236,000 uniquely results from the absorption costing calculation.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $360K - $124K = $236K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.688 margin-of-safety-percentage",
    "QuestionID": "P2-C-688", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-688-margin-of-safety-percentage",
    "Stem": "Crestview Industries reports current sales of $500,000 and breakeven sales of $350,000. What is the margin of safety percentage?",
    "Choices": {"A": "30.0%", "B": "42.9%", "C": "70.0%", "D": "25.0%"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "MOS% = (($500,000 - $350,000) / $500,000) x 100 = ($150,000 / $500,000) x 100 = 30.0%. Sales can decline by 30% before reaching breakeven.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "42.9% inverts the ratio: $150K / $350K. Uses breakeven as denominator.",
    "ExplanationWrongC": "70.0% uses breakeven as numerator: $350K / $500K = 70%.",
    "ExplanationWrongD": "25.0% results from a calculation error with an incorrect breakeven figure.",
    "FormulaReference": "DA-04: MOS% = ((Actual - BE) / Actual) x 100",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate-Easy", "DifficultyScore": 2, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Inverting numerator and denominator",
    "Authorities": ["IMA SMA on relevant costing", "CVP analysis"],
    "source_ids": ["DA-04: Margin of Safety formula"],
    "source_support_for_key": {"margin": "$500K - $350K = $150K", "MOS": "$150K / $500K = 30%"},
    "distractor_intent": {"B": {"misconception": "Breakeven as denominator", "why_plausible": "Breakeven is prominent", "tier_candidate": "B"}, "C": {"misconception": "Ratio of BE to actual", "why_plausible": "Different concept", "tier_candidate": "C"}, "D": {"misconception": "Arithmetic error", "why_plausible": "Wrong BE figure", "tier_candidate": "C"}},
    "uniqueness_note": "30.0% uniquely results from the correct MOS formula.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $150K / $500K = 30%"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.689 high-low-variable-cost-estimation",
    "QuestionID": "P2-C-689", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-689-high-low-variable-cost-estimation",
    "Stem": "Ridgeline Services: High point 14,000 machine hours, $210,000 cost. Low point 6,000 machine hours, $130,000 cost. Variable maintenance cost per machine hour?",
    "Choices": {"A": "$10.00", "B": "$15.00", "C": "$35.00", "D": "$21.67"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "VC per hour = ($210,000 - $130,000) / (14,000 - 6,000) = $80,000 / 8,000 = $10.00.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$15.00 is the average cost at the high point ($210K / 14K = $15). Not the variable component.",
    "ExplanationWrongC": "$35.00 results from a miscalculation. The correct incremental calculation yields $10.00.",
    "ExplanationWrongD": "$21.67 is the average cost at the low point ($130K / 6K). Includes both fixed and variable.",
    "FormulaReference": "High-low method",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Using average cost instead of incremental cost",
    "Authorities": ["IMA SMA on relevant costing", "Cost estimation theory"],
    "source_ids": ["DA-01: High-low method"],
    "source_support_for_key": {"cost_change": "$210K - $130K = $80K", "activity_change": "14K - 6K = 8K", "VC": "$80K / 8K = $10"},
    "distractor_intent": {"B": {"misconception": "Average cost at high point", "why_plausible": "Clean division result", "tier_candidate": "B"}, "C": {"misconception": "Miscalculation", "why_plausible": "Arithmetic error", "tier_candidate": "C"}, "D": {"misconception": "Average cost at low point", "why_plausible": "Includes both components", "tier_candidate": "B"}},
    "uniqueness_note": "$10.00 uniquely results from the high-low incremental calculation.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $80K / 8K = $10"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.690 multi-product-breakeven-wacm",
    "QuestionID": "P2-C-690", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-690-multi-product-breakeven-wacm",
    "Stem": "Mitchell Electronics: Alpha (CM $40, 60% of units), Beta (CM $25, 40% of units). Fixed costs $170,000. Breakeven in total units?",
    "Choices": {"A": "4,250 units", "B": "5,000 units", "C": "6,800 units", "D": "3,400 units"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "WACM = ($40 x 0.60) + ($25 x 0.40) = $34. BE = $170,000 / $34 = 5,000 units.",
    "ExplanationWrongA": "4,250 uses Alpha CM alone ($170K / $40). Must use WACM of $34.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "6,800 uses Beta CM alone ($170K / $25). Ignores sales mix.",
    "ExplanationWrongD": "3,400 uses sum of CMs ($65) instead of weighted average.",
    "FormulaReference": "DA-06: Multi-product BE = FC / WACM",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationItem": true,
    "CommonTrapReference": "Using simple average CM instead of weighted average",
    "Authorities": ["IMA SMA on relevant costing", "Multi-product CVP"],
    "source_ids": ["DA-06: Multi-product breakeven"],
    "source_support_for_key": {"WACM": "$40(0.60) + $25(0.40) = $34", "BE": "$170K / $34 = 5,000"},
    "distractor_intent": {"A": {"misconception": "Single-product CM", "why_plausible": "Uses Alpha CM alone", "tier_candidate": "B"}, "C": {"misconception": "Beta CM alone", "why_plausible": "Lower CM yields higher BE", "tier_candidate": "C"}, "D": {"misconception": "Sum instead of weighted avg", "why_plausible": "Fundamentally incorrect", "tier_candidate": "C"}},
    "uniqueness_note": "5,000 uniquely results from $170K / $34.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $170K / $34 = 5,000"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.691 absorption-variable-reconciliation",
    "QuestionID": "P2-C-691", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-691-absorption-variable-reconciliation",
    "Stem": "Horizon Manufacturing produced 15,000, sold 12,000. Fixed mfg overhead $300,000. Variable costing income $180,000. Absorption costing income?",
    "Choices": {"A": "$240,000", "B": "$220,000", "C": "$180,000", "D": "$360,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Fixed overhead per unit = $300K / 15K = $20. Deferred overhead = 3,000 x $20 = $60,000. Absorption income = $180K + $60K = $240K.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$220K adds half the deferred overhead instead of the full $60K.",
    "ExplanationWrongC": "$180K is variable costing income itself. Methods differ when production != sales.",
    "ExplanationWrongD": "$360K doubles the variable income. The adjustment is $60K.",
    "FormulaReference": "Absorption vs. Variable reconciliation",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationItem": true,
    "CommonTrapReference": "Confusing adjustment direction",
    "Authorities": ["IMA SMA on relevant costing", "Costing reconciliation"],
    "source_ids": ["DA-01: Income reconciliation"],
    "source_support_for_key": {"fixed_per_unit": "$300K/15K = $20", "deferred": "3K x $20 = $60K", "absorption": "$180K + $60K = $240K"},
    "distractor_intent": {"B": {"misconception": "Partial deferral", "why_plausible": "Half the amount", "tier_candidate": "C"}, "C": {"misconception": "No difference assumed", "why_plausible": "Methods differ when inventory changes", "tier_candidate": "B"}, "D": {"misconception": "Doubling income", "why_plausible": "Arithmetic error", "tier_candidate": "C"}},
    "uniqueness_note": "$240K uniquely results from $180K + $60K deferred.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $180K + $60K = $240K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.692 target-profit-units",
    "QuestionID": "P2-C-692", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-692-target-profit-units",
    "Stem": "Lakeview Technologies: $150/unit selling price, $90/unit variable cost. Fixed costs $240,000. Target income $60,000. Required units?",
    "Choices": {"A": "4,000 units", "B": "5,000 units", "C": "6,000 units", "D": "3,000 units"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "CM per unit = $60. Required units = ($240K + $60K) / $60 = $300K / $60 = 5,000.",
    "ExplanationWrongA": "4,000 is breakeven ($240K / $60 = 4,000), not target profit volume.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "6,000 uses wrong CM per unit ($50 instead of $60).",
    "ExplanationWrongD": "3,000 uses wrong CM per unit ($80 instead of $60).",
    "FormulaReference": "DA-03: (FC + Target) / CM per Unit",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate-Easy", "DifficultyScore": 2, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Confusing breakeven with target profit",
    "Authorities": ["IMA SMA on relevant costing", "CVP target profit"],
    "source_ids": ["DA-03: Target profit formula"],
    "source_support_for_key": {"CM": "$150 - $90 = $60", "units": "$300K / $60 = 5,000"},
    "distractor_intent": {"A": {"misconception": "Breakeven instead of target", "why_plausible": "Breakeven formula is familiar", "tier_candidate": "B"}, "C": {"misconception": "Wrong CM per unit", "why_plausible": "Miscalculation", "tier_candidate": "C"}, "D": {"misconception": "Wrong formula", "why_plausible": "Arithmetic error", "tier_candidate": "C"}},
    "uniqueness_note": "5,000 uniquely results from the target profit formula.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $300K / $60 = 5,000"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.693 mixed-cost-identification",
    "QuestionID": "P2-C-693", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "select", "UniqueConceptKey": "C-693-mixed-cost-identification",
    "Stem": "Which of the following correctly identifies a mixed cost?",
    "Choices": {"A": "Monthly rent of $5,000 for a warehouse", "B": "Direct materials at $12 per unit", "C": "Electricity bill with a $200 monthly connection charge plus $0.15 per kilowatt-hour", "D": "Annual insurance premium of $18,000"},
    "CorrectChoice": "C",
    "ExplanationCorrect": "A mixed cost contains both fixed and variable components. The electricity bill has a $200 fixed monthly charge plus a $0.15 per kWh variable charge. This dual behavior defines mixed costs.",
    "ExplanationWrongA": "Rent is a pure fixed cost. It remains constant regardless of activity level with no variable component.",
    "ExplanationWrongB": "Direct materials are pure variable costs with no fixed component. Not mixed.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Insurance is a pure fixed cost with no variable component. Not mixed.",
    "FormulaReference": "Mixed cost = Fixed + (Variable rate x Activity)",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Understand", "CalculationItem": false,
    "CommonTrapReference": "Confusing fixed costs with mixed costs",
    "Authorities": ["IMA SMA on relevant costing", "Cost behavior theory"],
    "source_ids": ["DA-01: Mixed cost identification"],
    "source_support_for_key": {"definition": "Contains both fixed and variable components", "example": "$200 fixed + $0.15/kWh variable = mixed"},
    "distractor_intent": {"A": {"misconception": "Rent as mixed cost", "why_plausible": "Fixed, not mixed", "tier_candidate": "B"}, "B": {"misconception": "Direct materials as mixed", "why_plausible": "Variable, not mixed", "tier_candidate": "B"}, "D": {"misconception": "Insurance as mixed", "why_plausible": "Fixed, not mixed", "tier_candidate": "C"}},
    "uniqueness_note": "Only electricity has both fixed and variable components.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (C)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Conceptual identification"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.694 cm-ratio-interpretation",
    "QuestionID": "P2-C-694", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-694-cm-ratio-interpretation",
    "Stem": "A company has a CM ratio of 40%. If sales increase by $50,000, how much will operating income increase (fixed costs unchanged)?",
    "Choices": {"A": "$20,000", "B": "$50,000", "C": "$12,500", "D": "$30,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "CM increase = $50,000 x 40% = $20,000. Since fixed costs are unchanged, the entire CM increase flows to operating income.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$50,000 ignores that 60% goes to variable costs. Only the 40% CM contributes to profit.",
    "ExplanationWrongC": "$12,500 divides by CM ratio instead of multiplying.",
    "ExplanationWrongD": "$30,000 uses the variable cost ratio (60%) instead of the CM ratio (40%).",
    "FormulaReference": "Change in OI = Change in sales x CM ratio",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Understand", "CalculationItem": true,
    "CommonTrapReference": "Using variable cost ratio instead of CM ratio",
    "Authorities": ["IMA SMA on relevant costing", "CVP analysis"],
    "source_ids": ["DA-01: CM ratio interpretation"],
    "source_support_for_key": {"CM_ratio": "40% of each sales dollar", "increase": "$50K x 40% = $20K"},
    "distractor_intent": {"B": {"misconception": "Ignoring variable costs", "why_plausible": "Full increase seems to flow to profit", "tier_candidate": "B"}, "C": {"misconception": "Dividing by CM ratio", "why_plausible": "Formula error", "tier_candidate": "C"}, "D": {"misconception": "Using variable cost ratio", "why_plausible": "60% is the complement", "tier_candidate": "C"}},
    "uniqueness_note": "$20,000 uniquely results from $50K x 40%.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent answer: $50K x 40% = $20K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.695 absorption-variable-crossover",
    "QuestionID": "P2-C-695", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "select", "UniqueConceptKey": "C-695-absorption-variable-crossover",
    "Stem": "Vantage Corp: Fixed mfg overhead $400,000. Production 20,000, sales 18,000. Under which scenario would absorption and variable costing produce the same income?",
    "Choices": {"A": "When 20,000 units produced and 20,000 sold", "B": "When production exceeds sales by 2,000", "C": "When sales exceed production by 2,000", "D": "When fixed manufacturing overhead is zero"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Absorption and variable costing produce the same income only when production equals sales. No inventory change means no fixed overhead deferred or released.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Production > sales makes absorption income higher due to deferred overhead.",
    "ExplanationWrongC": "Sales > production releases deferred overhead, making absorption income lower.",
    "ExplanationWrongD": "Zero fixed overhead produces convergence but is a degenerate case, not the standard condition.",
    "FormulaReference": "Same income when Units produced = Units sold",
    "LOSTag": "C.1", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Very Difficult", "DifficultyScore": 5, "CognitiveLevel": "Evaluate", "CalculationItem": false,
    "CommonTrapReference": "Confusing which conditions produce convergence",
    "Authorities": ["IMA SMA on relevant costing", "Absorption vs. variable costing theory"],
    "source_ids": ["DA-01: Income convergence conditions"],
    "source_support_for_key": {"convergence": "Production = Sales implies no inventory change", "current": "2,000 x $20 = $40,000 deferred under absorption"},
    "distractor_intent": {"B": {"misconception": "Current condition produces convergence", "why_plausible": "Creates income difference, not convergence", "tier_candidate": "C"}, "C": {"misconception": "Sales > production converges", "why_plausible": "Still produces income difference", "tier_candidate": "C"}, "D": {"misconception": "Zero fixed overhead converges", "why_plausible": "Degenerate case", "tier_candidate": "C"}},
    "uniqueness_note": "Production = sales (20K = 20K) is the unique standard condition.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Conceptual judgment question"]
  }
]
