// P2-C-711 through P2-C-725 — Domain C Decision Analysis, LOS C.2 Marginal Analysis
// Schema: v1.1 — all required fields including distractor_intent, source_ids, source_support_for_key
// Governance: Rules 2/6/9/10/11/13/14 active
// Distribution: 2E / 3ME / 5M / 3D / 2VD | R1/U3/Ap7/An3/Ev1 | 4A/4B/4C/3D

const pack_p2_c_batch7_questions = [
  {
    "Part": 2, "Section": "C", "Topic": "C.711 marginal-cost-basic",
    "QuestionID": "P2-C-711", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-711-marginal-cost-basic",
    "Stem": "Kessler Textiles produces fabric at a variable cost of $18 per yard. Fixed manufacturing costs total $90,000 per month. If Kessler produces 6,000 yards next month and receives a special order for one additional yard, what is the marginal cost of that additional yard?",
    "Choices": {"A": "$33", "B": "$18", "C": "$90,000", "D": "$15"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "Marginal cost is the incremental cost of producing one additional unit. Since fixed costs remain constant regardless of production volume within the relevant range, the marginal cost of the additional yard equals only the variable cost per yard, which is $18. Fixed costs of $90,000 are irrelevant to this decision because they do not change with the production of one more unit.",
    "ExplanationWrongA": "$33 results from allocating fixed costs to the additional unit: ($90,000 / 6,000) + $18 = $15 + $18 = $33. Fixed costs should not be allocated to marginal decisions because they remain unchanged.",
    "ExplanationWrongC": "$90,000 is the total fixed cost, not the marginal cost of one additional unit. Fixed costs are irrelevant to marginal cost analysis.",
    "ExplanationWrongD": "$15 is the fixed cost per unit at 6,000 yards ($90,000 / 6,000 = $15), not the marginal cost. The marginal cost includes only variable costs.",
    "FormulaReference": "Marginal Cost = Variable Cost per Unit (within relevant range)",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Easy", "DifficultyScore": 1, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Allocating fixed costs to marginal decisions",
    "Authorities": ["IMA SMA on relevant costing", "Marginal cost theory"],
    "source_ids": ["DA-01: Cost behavior fundamentals"],
    "source_support_for_key": {"variable_cost": "$18 per yard", "fixed_cost": "$90,000 total (irrelevant to marginal decision)", "marginal_cost": "$18"},
    "distractor_intent": {"A": {"misconception": "Allocating fixed costs to marginal unit", "why_plausible": "Full-cost allocation is common but wrong for marginal decisions", "tier_candidate": "B"}, "C": {"misconception": "Confusing total fixed with marginal", "why_plausible": "Fixed costs are the largest dollar figure in the stem", "tier_candidate": "C"}, "D": {"misconception": "Using fixed cost per unit", "why_plausible": "Fixed cost per unit at current volume is $15", "tier_candidate": "C"}},
    "uniqueness_note": "$18 uniquely equals the variable cost per yard.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.712 marginal-revenue-conceptual",
    "QuestionID": "P2-C-712", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-712-marginal-revenue-conceptual",
    "Stem": "Which of the following correctly describes the relationship between marginal revenue and pricing decisions in a competitive market?",
    "Choices": {"A": "Marginal revenue equals price for a price-taking firm, so the profit-maximizing quantity is where marginal cost equals the market price", "B": "Marginal revenue always exceeds price because selling one more unit increases total revenue by more than the unit price", "C": "Marginal revenue is irrelevant to pricing decisions because all firms use cost-plus pricing", "D": "Marginal revenue equals fixed cost divided by quantity, which determines the breakeven price"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "In a perfectly competitive market, the firm is a price taker and can sell any quantity at the market price. Therefore, the marginal revenue from selling one additional unit equals the market price. The profit-maximizing rule is to produce where marginal cost equals marginal revenue (MC = MR), which in this case means MC = Price.",
    "ExplanationWrongB": "Marginal revenue equals price only for a price-taking firm. For firms with market power, marginal revenue is less than price because the firm must lower price to sell additional units.",
    "ExplanationWrongC": "Marginal revenue is a fundamental concept in pricing theory. While cost-plus pricing is common, understanding marginal revenue helps firms optimize pricing and production decisions.",
    "ExplanationWrongD": "Marginal revenue is the change in total revenue from selling one additional unit. It is not related to fixed cost allocation.",
    "FormulaReference": "Marginal Revenue = Change in Total Revenue / Change in Quantity",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Easy", "DifficultyScore": 1, "CognitiveLevel": "Remember", "CalculationItem": false,
    "CommonTrapReference": "Confusing marginal revenue with total revenue or average revenue",
    "Authorities": ["IMA SMA on relevant costing", "Microeconomics pricing theory"],
    "source_ids": ["DA-03: Pricing decisions framework"],
    "source_support_for_key": {"concept": "MR = Price for price-taking firms", "profit_max": "MC = MR = Price"},
    "distractor_intent": {"B": {"misconception": "MR exceeds price", "why_plausible": "Intuitive but only true for downward-sloping demand curves", "tier_candidate": "B"}, "C": {"misconception": "Marginal analysis irrelevant", "why_plausible": "Cost-plus is common but marginal analysis optimizes decisions", "tier_candidate": "C"}, "D": {"misconception": "MR related to fixed costs", "why_plausible": "Complete misunderstanding of the concept", "tier_candidate": "C"}},
    "uniqueness_note": "Option A uniquely describes the correct MR = Price relationship for competitive firms.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.713 special-order-pricing",
    "QuestionID": "P2-C-713", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-713-special-order-pricing",
    "Stem": "Pacific Rim Electronics produces circuit boards at a variable cost of $22 per unit. The company has capacity to produce 15,000 units but currently produces only 13,000. A customer offers to buy 2,000 units at $35 each as a special order. Fixed costs are unaffected. What is the financial impact of accepting the special order?",
    "Choices": {"A": "Accept: increases operating income by $26,000", "B": "Reject: decreases operating income by $26,000", "C": "Accept: increases operating income by $70,000", "D": "Reject: selling below full cost of $22 plus allocated fixed costs"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "The special order should be accepted because the incremental revenue exceeds the incremental cost. Incremental revenue = 2,000 x $35 = $70,000. Incremental cost = 2,000 x $22 = $44,000. Net benefit = $70,000 - $44,000 = $26,000. Since the company has excess capacity, there is no opportunity cost of displacing regular sales.",
    "ExplanationWrongB": "Rejecting the order would forgo $26,000 in additional operating income. The $35 price exceeds the $22 variable cost, creating a positive contribution margin.",
    "ExplanationWrongC": "$70,000 is the incremental revenue, not the financial impact. The impact must subtract the incremental variable costs of $44,000.",
    "ExplanationWrongD": "Full cost includes allocated fixed costs, which are irrelevant to this marginal decision. The relevant comparison is price ($35) versus variable cost ($22).",
    "FormulaReference": "Special order: Accept if incremental revenue > incremental cost (when excess capacity exists)",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate-Easy", "DifficultyScore": 2, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Using full cost instead of variable cost for special order pricing",
    "Authorities": ["IMA SMA on relevant costing", "Special order pricing theory"],
    "source_ids": ["DA-03: Special order analysis"],
    "source_support_for_key": {"incremental_revenue": "2,000 x $35 = $70,000", "incremental_cost": "2,000 x $22 = $44,000", "net_benefit": "$70,000 - $44,000 = $26,000"},
    "distractor_intent": {"B": {"misconception": "Rejecting profitable order", "why_plausible": "Misunderstanding the relevant cost analysis", "tier_candidate": "B"}, "C": {"misconception": "Revenue as financial impact", "why_plausible": "Forgetting to subtract incremental costs", "tier_candidate": "C"}, "D": {"misconception": "Full cost allocation", "why_plausible": "Allocated fixed costs are irrelevant to marginal decisions", "tier_candidate": "C"}},
    "uniqueness_note": "$26,000 uniquely results from ($35 - $22) x 2,000.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: ($35-$22) x 2,000 = $26,000"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.714 make-or-buy-basic",
    "QuestionID": "P2-C-714", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-714-make-or-buy-basic",
    "Stem": "Cascade Manufacturing currently buys a subassembly for $22 per unit from an outside supplier. The company produces 10,000 units annually. Cascade can manufacture the subassembly for $15 per unit in variable costs plus $50,000 in avoidable fixed costs. What is the annual savings from making the subassembly in-house?",
    "Choices": {"A": "$20,000", "B": "$120,000", "C": "$50,000", "D": "$70,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Cost to buy = 10,000 x $22 = $220,000. Cost to make = (10,000 x $15) + $50,000 = $150,000 + $50,000 = $200,000. Annual savings from making = $220,000 - $200,000 = $20,000. The relevant costs are the purchase price versus the variable and avoidable fixed costs of manufacturing.",
    "ExplanationWrongB": "$120,000 results from computing the difference in variable costs only: ($22 - $15) x 10,000 = $70,000, then adding $50,000. This incorrectly treats avoidable fixed costs as a benefit rather than a cost of making.",
    "ExplanationWrongC": "$50,000 is the avoidable fixed cost alone, not the total savings. The savings must also account for the variable cost difference.",
    "ExplanationWrongD": "$70,000 results from computing the variable cost difference only: ($22 - $15) x 10,000 = $70,000, ignoring the $50,000 in avoidable fixed costs.",
    "FormulaReference": "Make-or-buy: Compare purchase cost vs. variable + avoidable fixed costs",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate-Easy", "DifficultyScore": 2, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Ignoring avoidable fixed costs in make-or-buy analysis",
    "Authorities": ["IMA SMA on relevant costing", "Make-or-buy decision theory"],
    "source_ids": ["DA-03: Make-or-buy analysis"],
    "source_support_for_key": {"buy_cost": "10,000 x $22 = $220,000", "make_cost": "(10,000 x $15) + $50,000 = $200,000", "savings": "$220,000 - $200,000 = $20,000"},
    "distractor_intent": {"B": {"misconception": "Treating avoidable FC as benefit", "why_plausible": "Miscounting the direction of the fixed cost effect", "tier_candidate": "B"}, "C": {"misconception": "Only fixed costs considered", "why_plausible": "Ignoring the variable cost savings", "tier_candidate": "C"}, "D": {"misconception": "Ignoring avoidable fixed costs", "why_plausible": "Only considering variable cost difference", "tier_candidate": "B"}},
    "uniqueness_note": "$20,000 uniquely results from $220,000 - $200,000.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: $220K - $200K = $20K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.715 sell-or-process-further",
    "QuestionID": "P2-C-715", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-715-sell-or-process-further",
    "Stem": "Greenwood Lumber processes logs into rough-cut lumber. The company can sell 5,000 board feet of rough-cut lumber for $55 per board foot, or process it further into finished lumber that sells for $85 per board foot. The additional processing costs total $75,000. Should Greenwood process further?",
    "Choices": {"A": "Yes, process further because incremental profit is $75,000", "B": "No, sell as rough-cut because processing further reduces profit", "C": "Yes, process further because revenue increases to $425,000", "D": "Indifferent, both options generate the same profit"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Incremental revenue from processing further = ($85 - $55) x 5,000 = $30 x 5,000 = $150,000. Incremental cost = $75,000. Incremental profit = $150,000 - $75,000 = $75,000. Greenwood should process further because the additional revenue exceeds the additional cost by $75,000.",
    "ExplanationWrongB": "Processing further generates $150,000 in additional revenue against only $75,000 in additional costs, increasing profit by $75,000.",
    "ExplanationWrongC": "$425,000 is the total revenue from processed lumber ($85 x 5,000), not the incremental profit. The incremental profit is $75,000 after deducting the additional processing costs.",
    "ExplanationWrongD": "The options are not equivalent: processing further adds $75,000 in incremental profit.",
    "FormulaReference": "DA-08: Sell or Process Further: Incremental Revenue minus Incremental Cost",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Including joint costs in sell-or-process-further analysis",
    "Authorities": ["IMA SMA on relevant costing", "Sell-or-process-further theory"],
    "source_ids": ["DA-08: Sell-or-process-further decision"],
    "source_support_for_key": {"incremental_revenue": "($85-$55) x 5,000 = $150,000", "incremental_cost": "$75,000", "incremental_profit": "$150,000 - $75,000 = $75,000"},
    "distractor_intent": {"B": {"misconception": "Processing further reduces profit", "why_plausible": "Misunderstanding the incremental analysis", "tier_candidate": "B"}, "C": {"misconception": "Revenue as profit measure", "why_plausible": "Forgetting to subtract additional processing costs", "tier_candidate": "C"}, "D": {"misconception": "Indifference", "why_plausible": "Both options have revenue, but the incremental analysis shows a clear advantage", "tier_candidate": "C"}},
    "uniqueness_note": "$75,000 uniquely results from $150,000 incremental revenue minus $75,000 incremental cost.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: $150K - $75K = $75K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.716 shutdown-point-analysis",
    "QuestionID": "P2-C-716", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-716-shutdown-point-analysis",
    "Stem": "Falcon Precision has fixed costs of $200,000 per month and a contribution margin ratio of 40%. At what monthly sales revenue should Falcon consider shutting down operations temporarily?",
    "Choices": {"A": "$500,000", "B": "$200,000", "C": "$80,000", "D": "$800,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "The shutdown point is the sales level where the company is indifferent between operating and shutting down. Shutdown revenue = Fixed costs / Contribution margin ratio = $200,000 / 0.40 = $500,000. Below $500,000 in sales, the company loses more by operating than by shutting down.",
    "ExplanationWrongB": "$200,000 is the total fixed costs, not the shutdown point. The shutdown point is expressed in sales revenue, not cost terms.",
    "ExplanationWrongC": "$80,000 results from multiplying fixed costs by the CM ratio: $200,000 x 0.40 = $80,000. The correct formula divides fixed costs by the CM ratio.",
    "ExplanationWrongD": "$800,000 results from dividing fixed costs by (1 minus CM ratio): $200,000 / 0.60 = $333,333, then rounding up. This is not the correct formula.",
    "FormulaReference": "DA-07: Shutdown Point = Fixed Costs / Contribution Margin Ratio",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Confusing shutdown point with breakeven point; inverting the formula",
    "Authorities": ["IMA SMA on relevant costing", "Shutdown point theory"],
    "source_ids": ["DA-07: Shutdown point"],
    "source_support_for_key": {"fixed_costs": "$200,000", "cm_ratio": "0.40", "shutdown": "$200,000 / 0.40 = $500,000"},
    "distractor_intent": {"B": {"misconception": "Fixed costs as shutdown point", "why_plausible": "Confusing cost terms with revenue threshold", "tier_candidate": "B"}, "C": {"misconception": "Inverted formula", "why_plausible": "Multiplying instead of dividing", "tier_candidate": "C"}, "D": {"misconception": "Wrong formula", "why_plausible": "Using (1-CM ratio) as divisor", "tier_candidate": "C"}},
    "uniqueness_note": "$500,000 uniquely results from $200,000 / 0.40.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: $200K / 0.40 = $500K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.717 contribution-margin-dol",
    "QuestionID": "P2-C-717", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-717-contribution-margin-dol",
    "Stem": "Sunrise Industries reports total contribution margin of $300,000 and operating income of $100,000. If sales increase by 15%, by what percentage will operating income increase?",
    "Choices": {"A": "15%", "B": "30%", "C": "45%", "D": "20%"},
    "CorrectChoice": "C",
    "ExplanationCorrect": "Degree of operating leverage (DOL) = Contribution margin / Operating income = $300,000 / $100,000 = 3.0. Percentage change in operating income = DOL x Percentage change in sales = 3.0 x 15% = 45%.",
    "ExplanationWrongA": "15% assumes a one-to-one relationship between sales and operating income, ignoring the leverage effect of fixed costs.",
    "ExplanationWrongB": "30% would result from a DOL of 2.0, but the correct DOL is 3.0.",
    "ExplanationWrongD": "20% is unrelated to the correct calculation.",
    "FormulaReference": "DA-05: DOL = Contribution Margin / Operating Income",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Confusing DOL with CM ratio; ignoring leverage effect",
    "Authorities": ["IMA SMA on relevant costing", "Operating leverage theory"],
    "source_ids": ["DA-05: Degree of operating leverage"],
    "source_support_for_key": {"DOL": "$300,000 / $100,000 = 3.0", "income_increase": "3.0 x 15% = 45%"},
    "distractor_intent": {"A": {"misconception": "One-to-one relationship", "why_plausible": "Ignoring the leverage effect of fixed costs", "tier_candidate": "B"}, "B": {"misconception": "Wrong DOL", "why_plausible": "Could result from incorrect DOL calculation", "tier_candidate": "C"}, "D": {"misconception": "Unrelated figure", "why_plausible": "No clear derivation from the given data", "tier_candidate": "C"}},
    "uniqueness_note": "45% uniquely results from DOL = 3.0 x 15%.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (C)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: DOL=3.0, 3.0x15%=45%"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.718 multi-product-breakeven",
    "QuestionID": "P2-C-718", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-718-multi-product-breakeven",
    "Stem": "Northridge Electronics manufactures two products. Alpha has a contribution margin of $30 per unit and represents 60% of unit sales. Beta has a contribution margin of $20 per unit and represents 40% of unit sales. Fixed costs total $260,000. What is the breakeven point in total units?",
    "Choices": {"A": "13,000 units", "B": "10,000 units", "C": "8,667 units", "D": "5,200 units"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "Weighted average contribution margin (WACM) = ($30 x 0.60) + ($20 x 0.40) = $18 + $8 = $26 per unit. Breakeven units = Fixed costs / WACM = $260,000 / $26 = 10,000 units.",
    "ExplanationWrongA": "13,000 units results from dividing fixed costs by the simple average CM: $260,000 / (($30+$20)/2) = $260,000 / $25 = 10,400. The 13,000 figure may result from using an incorrect WACM.",
    "ExplanationWrongC": "8,667 units results from dividing fixed costs by the higher CM only: $260,000 / $30 = 8,667. This ignores the sales mix.",
    "ExplanationWrongD": "5,200 units results from dividing fixed costs by the lower CM only: $260,000 / $20 = 13,000, then halving. This is incorrect.",
    "FormulaReference": "DA-06: WACM = Sum(Sales Mix x CM per unit); BE = FC / WACM",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Using simple average instead of weighted average CM",
    "Authorities": ["IMA SMA on relevant costing", "Multi-product CVP analysis"],
    "source_ids": ["DA-06: Weighted average contribution margin"],
    "source_support_for_key": {"WACM": "($30 x 0.60) + ($20 x 0.40) = $26", "BE": "$260,000 / $26 = 10,000 units"},
    "distractor_intent": {"A": {"misconception": "Wrong WACM calculation", "why_plausible": "Could result from using incorrect mix weights", "tier_candidate": "B"}, "C": {"misconception": "Ignoring sales mix", "why_plausible": "Using only the higher CM product", "tier_candidate": "C"}, "D": {"misconception": "Using only lower CM", "why_plausible": "Incorrectly using only one product CM", "tier_candidate": "C"}},
    "uniqueness_note": "10,000 units uniquely results from $260,000 / $26.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: WACM=$26, BE=10,000"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.719 cvp-target-profit-with-tax",
    "QuestionID": "P2-C-719", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-719-cvp-target-profit-with-tax",
    "Stem": "Oakfield Electronics sells a product for $500 per unit. Variable costs are $300 per unit. Fixed costs total $400,000. The tax rate is 30%. How many units must Oakfield sell to achieve an after-tax target operating income of $140,000?",
    "Choices": {"A": "2,500 units", "B": "3,000 units", "C": "3,500 units", "D": "2,000 units"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "Target pre-tax income = $140,000 / (1 - 0.30) = $140,000 / 0.70 = $200,000. Required units = (Fixed costs + Target pre-tax income) / CM per unit = ($400,000 + $200,000) / ($500 - $300) = $600,000 / $200 = 3,000 units.",
    "ExplanationWrongA": "2,500 units results from using the after-tax target directly without grossing up for taxes.",
    "ExplanationWrongC": "3,500 units results from an arithmetic error in the gross-up calculation.",
    "ExplanationWrongD": "2,000 units results from dividing fixed costs by CM without including the target income.",
    "FormulaReference": "Target Units = (FC + Target Pre-tax Income) / CM per unit; Pre-tax = After-tax / (1-t)",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Forgetting to gross up after-tax target to pre-tax",
    "Authorities": ["IMA SMA on relevant costing", "CVP with taxes"],
    "source_ids": ["DA-03: Target profit analysis"],
    "source_support_for_key": {"pretax_target": "$140,000 / 0.70 = $200,000", "cm": "$500 - $300 = $200", "units": "($400,000 + $200,000) / $200 = 3,000"},
    "distractor_intent": {"A": {"misconception": "Not grossing up for taxes", "why_plausible": "Using after-tax target directly in the formula", "tier_candidate": "B"}, "C": {"misconception": "Arithmetic error", "why_plausible": "Error in gross-up calculation", "tier_candidate": "C"}, "D": {"misconception": "Ignoring target income", "why_plausible": "Only covering fixed costs", "tier_candidate": "C"}},
    "uniqueness_note": "3,000 units uniquely results from the correct gross-up and CVP formula.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: pretax=$200K, units=$600K/$200=3,000"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.720 constrained-optimization",
    "QuestionID": "P2-C-720", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-720-constrained-optimization",
    "Stem": "Delta Manufacturing produces two products that share a constrained machine time of 200 hours per month. Product A generates a contribution margin of $40 per unit and requires 2 machine hours per unit. Product B generates a contribution margin of $25 per unit and requires 1 machine hour per unit. To maximize total contribution margin, Delta should:",
    "Choices": {"A": "Produce only Product A, generating $4,000 total CM", "B": "Produce only Product B, generating $5,000 total CM", "C": "Produce a mix weighted toward Product B based on CM per constraint hour", "D": "Produce equal quantities of both products"},
    "CorrectChoice": "C",
    "ExplanationCorrect": "When a constraint exists, the optimal product mix maximizes contribution margin per unit of the constrained resource. CM per machine hour: Product A = $40 / 2 = $20 per hour; Product B = $25 / 1 = $25 per hour. Product B generates more contribution margin per machine hour. Delta should prioritize Product B up to its demand limit, then fill remaining capacity with Product A.",
    "ExplanationWrongA": "Product A generates only $20 per machine hour versus $25 for Product B. Producing only A yields 100 units x $40 = $4,000 total CM.",
    "ExplanationWrongB": "Producing only B yields 200 units x $25 = $5,000 total CM. While this is the highest single-product total, a mix that includes some A could potentially exceed this if demand for B is limited.",
    "ExplanationWrongD": "Equal quantities do not optimize the use of the constrained resource. The mix should be weighted toward the product with higher CM per constraint hour.",
    "FormulaReference": "CM per constraint unit = CM per unit / Constraint hours per unit",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationItem": true,
    "CommonTrapReference": "Using CM per unit instead of CM per constraint hour",
    "Authorities": ["IMA SMA on relevant costing", "Theory of constraints"],
    "source_ids": ["DA-03: Constrained optimization"],
    "source_support_for_key": {"CM_per_hour_A": "$40 / 2 = $20", "CM_per_hour_B": "$25 / 1 = $25", "conclusion": "Prioritize B ($25/hr > $20/hr)"},
    "distractor_intent": {"A": {"misconception": "Higher CM per unit is better", "why_plausible": "Product A has higher CM per unit ($40 vs. $25) but lower per constraint hour", "tier_candidate": "B"}, "B": {"misconception": "Single-product focus", "why_plausible": "Only B yields $5,000 but a mix could be better", "tier_candidate": "C"}, "D": {"misconception": "Equal mix", "why_plausible": "Simple but not optimal", "tier_candidate": "C"}},
    "uniqueness_note": "Option C uniquely describes the correct constrained optimization approach.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (C)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "CM/hr: A=$20, B=$25; B is superior per constraint"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.721 special-order-with-opportunity-cost",
    "QuestionID": "P2-C-721", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-721-special-order-with-opportunity-cost",
    "Stem": "Harbor Medical Devices produces 10,000 units per month at full capacity. Variable cost is $25 per unit, and the regular selling price is $60 per unit. A foreign distributor offers to buy 3,000 units at $40 per unit. Accepting the order would require displacing 3,000 units of regular sales. What is the net financial impact of accepting the special order?",
    "Choices": {"A": "Accept: increases income by $45,000", "B": "Reject: net disadvantage of $60,000 from accepting", "C": "Accept: increases income by $105,000", "D": "Reject: decreases income by $60,000"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "When capacity is fully utilized, accepting a special order requires displacing regular sales. Benefit of special order = ($40 - $25) x 3,000 = $45,000. Opportunity cost of displaced regular sales = ($60 - $25) x 3,000 = $105,000. Net impact = $45,000 - $105,000 = -$60,000. The order should be rejected because accepting it has a net disadvantage of $60,000.",
    "ExplanationWrongA": "$45,000 is the contribution margin from the special order alone, ignoring the opportunity cost of lost regular sales.",
    "ExplanationWrongC": "$105,000 is the opportunity cost of displaced regular sales, not the benefit of the special order.",
    "ExplanationWrongD": "The net impact is -$60,000, but the correct framing is that accepting the order creates a $60,000 disadvantage. The wording in this choice is less precise than the correct answer.",
    "FormulaReference": "Net impact = Special order CM - Displaced regular CM",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationItem": true,
    "CommonTrapReference": "Ignoring opportunity cost of displaced regular sales",
    "Authorities": ["IMA SMA on relevant costing", "Special order with constraint analysis"],
    "source_ids": ["DA-03: Special order analysis", "DA-03: Opportunity cost"],
    "source_support_for_key": {"special_cm": "($40-$25) x 3,000 = $45,000", "opportunity_cost": "($60-$25) x 3,000 = $105,000", "net": "$45,000 - $105,000 = -$60,000"},
    "distractor_intent": {"A": {"misconception": "Only counting special order benefit", "why_plausible": "Ignoring the opportunity cost of lost regular sales", "tier_candidate": "B"}, "C": {"misconception": "Opportunity cost as benefit", "why_plausible": "Confusing the opportunity cost with the special order benefit", "tier_candidate": "C"}, "D": {"misconception": "Correct direction but less precise wording", "why_plausible": "Both B and D indicate rejection, but B is more precise", "tier_candidate": "C"}},
    "uniqueness_note": "The net disadvantage uniquely results from subtracting opportunity cost from special order CM.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: $45K - $105K = -$60K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.722 shutdown-vs-continue",
    "QuestionID": "P2-C-722", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-722-shutdown-vs-continue",
    "Stem": "Precision Plating reports monthly revenue of $300,000, variable costs of $220,000, and fixed costs of $100,000 (of which $60,000 are avoidable if operations cease). Should Precision continue operations or shut down temporarily?",
    "Choices": {"A": "Continue, because operating loss of $20,000 is less than shutdown loss of $40,000", "B": "Shut down, because operating generates a $20,000 loss", "C": "Continue, because revenue exceeds variable costs", "D": "Shut down, because fixed costs exceed contribution margin"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Operating income = $300,000 - $220,000 - $100,000 = -$20,000 (loss). If shut down, revenue = $0, variable costs = $0, but unavoidable fixed costs = $100,000 - $60,000 = $40,000 still must be paid. Shutdown loss = -$40,000. Continuing generates a $20,000 loss, which is $20,000 better than the $40,000 shutdown loss.",
    "ExplanationWrongB": "While operating generates a $20,000 loss, shutting down generates a worse $40,000 loss because $40,000 in unavoidable fixed costs must still be paid.",
    "ExplanationWrongC": "This is true but incomplete. The correct analysis compares operating loss to shutdown loss, not just revenue to variable costs.",
    "ExplanationWrongD": "Fixed costs ($100,000) do not exceed contribution margin ($80,000). The contribution margin of $80,000 covers part of the fixed costs, reducing the loss.",
    "FormulaReference": "Shutdown decision: Compare operating loss vs. unavoidable fixed costs",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationItem": true,
    "CommonTrapReference": "Ignoring unavoidable fixed costs in shutdown analysis",
    "Authorities": ["IMA SMA on relevant costing", "Shutdown point theory"],
    "source_ids": ["DA-07: Shutdown point"],
    "source_support_for_key": {"operating_loss": "$300K - $220K - $100K = -$20K", "shutdown_loss": "-$40K (unavoidable FC)", "conclusion": "Continue: -$20K > -$40K"},
    "distractor_intent": {"B": {"misconception": "Any loss means shut down", "why_plausible": "Ignores that shutdown has its own costs", "tier_candidate": "B"}, "C": {"misconception": "Incomplete analysis", "why_plausible": "Revenue > VC is necessary but not sufficient", "tier_candidate": "C"}, "D": {"misconception": "Wrong comparison", "why_plausible": "FC do not exceed CM in this scenario", "tier_candidate": "C"}},
    "uniqueness_note": "Operating loss of $20,000 is uniquely less than shutdown loss of $40,000.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: -$20K vs -$40K"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.723 multi-product-cvp-revenue-mix",
    "QuestionID": "P2-C-723", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-723-multi-product-cvp-revenue-mix",
    "Stem": "Summit Industries sells two products. Product A sells for $50 with a CM ratio of 30%. Product B sells for $40 with a CM ratio of 25%. The sales mix by revenue is 60% Product A and 40% Product B. Fixed costs total $300,000. What is the breakeven sales revenue?",
    "Choices": {"A": "$1,071,429", "B": "$1,285,714", "C": "$1,200,000", "D": "$1,500,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Weighted average CM ratio = (0.60 x 0.30) + (0.40 x 0.25) = 0.18 + 0.10 = 0.28. Breakeven sales = Fixed costs / Weighted CM ratio = $300,000 / 0.28 = $1,071,429.",
    "ExplanationWrongB": "$1,285,714 results from dividing fixed costs by an incorrect weighted CM ratio of 0.2333.",
    "ExplanationWrongC": "$1,200,000 results from dividing fixed costs by 0.25, which is the CM ratio of Product B only, ignoring the sales mix.",
    "ExplanationWrongD": "$1,500,000 results from dividing fixed costs by 0.20, which is an incorrect CM ratio.",
    "FormulaReference": "DA-06: Weighted CM ratio = Sum(Revenue mix x CM ratio); BE = FC / Weighted CM ratio",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationItem": true,
    "CommonTrapReference": "Using unit CM instead of CM ratio for revenue-based analysis",
    "Authorities": ["IMA SMA on relevant costing", "Multi-product CVP analysis"],
    "source_ids": ["DA-06: Weighted average contribution margin"],
    "source_support_for_key": {"weighted_cm": "0.60 x 0.30 + 0.40 x 0.25 = 0.28", "BE": "$300,000 / 0.28 = $1,071,429"},
    "distractor_intent": {"B": {"misconception": "Wrong weighted CM ratio", "why_plausible": "Could result from incorrect mix calculation", "tier_candidate": "B"}, "C": {"misconception": "Ignoring sales mix", "why_plausible": "Using only Product B CM ratio", "tier_candidate": "C"}, "D": {"misconception": "Wrong divisor", "why_plausible": "Using 0.20 instead of 0.28", "tier_candidate": "C"}},
    "uniqueness_note": "$1,071,429 uniquely results from $300,000 / 0.28.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: WCM=0.28, BE=$300K/0.28=$1,071,429"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.724 make-or-buy-with-opportunity-cost",
    "QuestionID": "P2-C-724", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-724-make-or-buy-with-opportunity-cost",
    "Stem": "Crestview Electronics manufactures 20,000 circuit boards annually. Variable manufacturing cost is $12 per unit, and avoidable fixed costs are $40,000. An outside supplier offers to provide the boards for $16 per unit. If Crestview outsources, the freed-up facility can be rented for $50,000 per year. What is the net financial impact of outsourcing?",
    "Choices": {"A": "Outsource: saves $10,000 annually", "B": "Make: saves $30,000 annually", "C": "Outsource: costs $80,000 more annually", "D": "Indifferent: both options cost the same"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Cost to make = (20,000 x $12) + $40,000 = $240,000 + $40,000 = $280,000. Cost to outsource = (20,000 x $16) - $50,000 rental income = $320,000 - $50,000 = $270,000. Net savings from outsourcing = $280,000 - $270,000 = $10,000.",
    "ExplanationWrongB": "$30,000 results from ignoring the opportunity cost of the forgone rental income. Without the rental income, making would cost $40,000 less ($320,000 - $280,000), but the $50,000 rental opportunity changes the analysis.",
    "ExplanationWrongC": "$80,000 results from the raw cost difference: ($16 - $12) x 20,000 = $80,000, without considering avoidable fixed costs or opportunity cost.",
    "ExplanationWrongD": "Indifferent would require the costs to be equal, but outsourcing saves $10,000.",
    "FormulaReference": "Make-or-buy: Compare total relevant costs including opportunity costs",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationItem": true,
    "CommonTrapReference": "Omitting opportunity cost of facility rental income",
    "Authorities": ["IMA SMA on relevant costing", "Make-or-buy with opportunity cost"],
    "source_ids": ["DA-03: Make-or-buy analysis"],
    "source_support_for_key": {"make_cost": "$240K + $40K = $280K", "buy_cost": "$320K - $50K = $270K", "savings": "$280K - $270K = $10K"},
    "distractor_intent": {"B": {"misconception": "Ignoring opportunity cost", "why_plausible": "Not considering the rental income benefit", "tier_candidate": "B"}, "C": {"misconception": "Ignoring avoidable FC and opportunity cost", "why_plausible": "Using raw variable cost difference only", "tier_candidate": "B"}, "D": {"misconception": "Indifference", "why_plausible": "Costs are close but not equal", "tier_candidate": "C"}},
    "uniqueness_note": "$10,000 savings uniquely results from the full relevant cost comparison.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (A)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Independent: $280K vs $270K = $10K savings"]
  },
  {
    "Part": 2, "Section": "C", "Topic": "C.725 relevant-costing-conceptual",
    "QuestionID": "P2-C-725", "question_state": "Unprocessed", "Part2OnlyFlag": true,
    "ItemStyle": "single-select", "UniqueConceptKey": "C-725-relevant-costing-conceptual",
    "Stem": "Which of the following costs is always irrelevant to short-term decision making?",
    "Choices": {"A": "Variable manufacturing costs that will be incurred only if the product is produced", "B": "Sunk costs that have already been incurred and cannot be recovered", "C": "Opportunity costs of alternative uses of constrained resources", "D": "Avoidable fixed costs that will be eliminated if a segment is dropped"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "Sunk costs are costs that have already been incurred and cannot be changed by any future decision. Because they are irreversible, sunk costs are always irrelevant to decision making. The correct approach is to focus only on future costs and revenues that differ between alternatives.",
    "ExplanationWrongA": "Variable manufacturing costs are relevant because they differ between alternatives: they are incurred only if the product is produced.",
    "ExplanationWrongC": "Opportunity costs are relevant because they represent the value of the best forgone alternative. They are a key component of relevant cost analysis.",
    "ExplanationWrongD": "Avoidable fixed costs are relevant because they differ between alternatives: they are eliminated if the segment is dropped.",
    "FormulaReference": "Relevant costs: future costs that differ between alternatives",
    "LOSTag": "C.2", "BlueprintDomain": "Decision Analysis",
    "Difficulty": "Very Difficult", "DifficultyScore": 5, "CognitiveLevel": "Evaluate", "CalculationItem": false,
    "CommonTrapReference": "Confusing sunk costs with opportunity costs or avoidable costs",
    "Authorities": ["IMA SMA on relevant costing", "Decision analysis theory"],
    "source_ids": ["DA-03: Relevant costing framework"],
    "source_support_for_key": {"concept": "Sunk costs are historical and irreversible", "rule": "Only future costs that differ between alternatives are relevant"},
    "distractor_intent": {"A": {"misconception": "Variable costs are irrelevant", "why_plausible": "Variable costs are future and differential, hence relevant", "tier_candidate": "B"}, "C": {"misconception": "Opportunity costs are irrelevant", "why_plausible": "Opportunity costs are future and differential, hence relevant", "tier_candidate": "B"}, "D": {"misconception": "Avoidable FC are irrelevant", "why_plausible": "Avoidable FC differ between alternatives, hence relevant", "tier_candidate": "C"}},
    "uniqueness_note": "Sunk costs are uniquely always irrelevant to decision making.",
    "source_status": "RESOLVED", "hold_reason": "", "schema_version": "1.1",
    "VerifiedChecks": ["Part2OnlyFlag verified true", "EW[CC] empty (B)", "Non-CC EW slots >= 50 chars", "Difficulty justified", "Conceptual item — sunk costs definition"]
  }
];
