// P2-B-561 through P2-B-575 — Domain B, LOS B.5: Short-Term Financing and Cash Management
// Schema v1.1 | 15 items | Batch 5
// Answer: 4A / 4B / 4C / 3D, max streak 2

[
  {
    "QuestionID": "P2-B-561", "Part": 2, "Section": "B", "Topic": "B.5 Cash management - Baumol model",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Crestview Manufacturing operates from a central treasury that disburses cash in uniform amounts throughout the year. The firm's annual cash requirement is $2.8 million, each cash conversion transaction costs $35, and Crestview's opportunity cost on short-term marketable securities is 5%. What is the optimal cash conversion amount under the Baumol model?",
    "Choices": {"A": "$3,252", "B": "$4,427", "C": "$6,261", "D": "$8,120"},
    "CorrectChoice": "C",
    "ExplanationCorrect": "The Baumol model calculates optimal cash conversion as the square root of (2 times T times F divided by O), where T is the annual cash requirement ($2,800,000), F is the fixed transaction cost ($35), and O is the opportunity cost (0.05). Calculation: the square root of (2 x 2,800,000 x 35 / 0.05) equals the square root of 3,920,000,000, which is approximately $6,261.",
    "ExplanationWrongA": "$3,252 results from dividing T by the product of F and O without the square root and without multiplying by 2. A formula inversion error that understates the optimal conversion.",
    "ExplanationWrongB": "$4,427 is obtained by omitting the factor of 2 in the numerator. Dropping the 2 yields an understated optimal amount.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "$8,120 results from swapping the roles of F and O in the formula, producing a reciprocal relationship that overstates the optimal conversion amount.",
    "QuestionType": "numeric", "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationRequired": true,
    "distractor_intent": {"A": {"misconception": "Omitted square root and factor of 2", "why_plausible": "A common formula inversion", "tier_candidate": false}, "B": {"misconception": "Omitted factor of 2 in numerator", "why_plausible": "Incomplete formula produces a close range number", "tier_candidate": false}, "D": {"misconception": "Swapped F and O in the formula", "why_plausible": "Reciprocal error yields inflated amount", "tier_candidate": false}},
    "source_ids": ["Baumol T.W., 1952", "IMA CMA Part 2 LOS B.5"],
    "source_support_for_key": {"A": "Formula inversion understated amount", "B": "Numerator omission understated amount", "C": "sqrt(2TF/O) = sqrt(2 x 2,800,000 x 35 / 0.05) = $6,261", "D": "Reciprocal substitution overstates amount"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-562", "Part": 2, "Section": "B", "Topic": "B.5 Cash management - Miller-Orr model spread",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Vantage Logistics uses the Miller-Orr model to manage its cash balance. The firm's lower control limit is $300,000, the spread between the upper and lower limits is $180,000, and the daily opportunity cost of holding cash is 0.02%. What is the return point at which the treasury team would sell securities to replenish cash?",
    "Choices": {"A": "$360,000", "B": "$390,000", "C": "$420,000", "D": "$480,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "In the Miller-Orr model, the return point equals the lower limit plus one-third of the spread: Return Point = L + (1/3) x S = $300,000 + (1/3) x $180,000 = $300,000 + $60,000 = $360,000.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$390,000 assumes the return point is L + (1/2) x S, placing it at the midpoint. The Miller-Orr model uses one-third of the spread above the lower limit.",
    "ExplanationWrongC": "$420,000 results from computing L + (2/3) x S. The model positions the return point at one-third above the lower limit.",
    "ExplanationWrongD": "$480,000 is the upper control limit (L + S), not the return point. The firm sells down to the return point, not to the upper limit.",
    "QuestionType": "numeric", "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationRequired": true,
    "distractor_intent": {"B": {"misconception": "Used midpoint instead of one-third offset", "why_plausible": "Symmetric midpoint is intuitive but not Miller-Orr", "tier_candidate": false}, "C": {"misconception": "Used two-thirds offset from lower limit", "why_plausible": "Inverted fraction yields plausible but incorrect return point", "tier_candidate": false}, "D": {"misconception": "Confused upper control limit with return point", "why_plausible": "Upper limit is a named value making it easy to select", "tier_candidate": false}},
    "source_ids": ["Miller M.H. and Orr D., 1966", "IMA CMA Part 2 LOS B.5"],
    "source_support_for_key": {"A": "Return point = L + S/3 = $300,000 + $60,000 = $360,000", "B": "Midpoint is not Miller-Orr; model uses 1/3 offset", "C": "Two-thirds offset exceeds return point by design", "D": "Upper limit is the sell trigger not the return point"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-563", "Part": 2, "Section": "B", "Topic": "B.5 Float management - net float",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Meridian Food Services deposits its daily average receipts of $180,000 through a regional lockbox system. The average collection float is 3.5 days, and the average disbursement float is 1.5 days. What is Meridian's net float?",
    "Choices": {"A": "$540,000", "B": "$360,000", "C": "$630,000", "D": "$900,000"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "Net float equals collection float minus disbursement float. Net float = (3.5 - 1.5) x $180,000 = 2.0 x $180,000 = $360,000.",
    "ExplanationWrongA": "$540,000 would result from using 3.0 days of net float, rounding the collection float down.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "$630,000 is the gross collection float (3.5 x $180,000), ignoring disbursement float entirely.",
    "ExplanationWrongD": "$900,000 results from adding collection and disbursement floats (5.0 days x $180,000), double-counting the offset.",
    "QuestionType": "numeric", "Difficulty": "Easy", "DifficultyScore": 2, "CognitiveLevel": "Apply", "CalculationRequired": true,
    "distractor_intent": {"A": {"misconception": "Rounded collection float and omitted offset", "why_plausible": "Simplified calculation omits disbursement float", "tier_candidate": false}, "C": {"misconception": "Ignored disbursement float entirely", "why_plausible": "Gross collection float is a common default", "tier_candidate": false}, "D": {"misconception": "Added floats instead of netting", "why_plausible": "Adding both floats is a straightforward error", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Float management literature"],
    "source_support_for_key": {"A": "Rounded figures produce wrong net float", "B": "Net float = (3.5 - 1.5) x $180,000 = $360,000", "C": "Gross collection float ignores disbursement offset", "D": "Summing floats double-counts disbursement side"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-564", "Part": 2, "Section": "B", "Topic": "B.5 Short-term financing - commercial paper",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Apex Manufacturing issues $10 million of commercial paper with a 90-day maturity and a yield of 4.2%. The dealer placement fee is 0.15%, and the credit enhancement fee from the backing bank is 0.25%. What is the total annualized all-in cost to Apex of this commercial paper issuance?",
    "Choices": {"A": "4.60%", "B": "4.20%", "C": "4.85%", "D": "5.05%"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "The all-in cost = yield + dealer fee + credit enhancement fee = 4.2% + 0.15% + 0.25% = 4.60% per annum.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "4.20% is the base yield only, ignoring the dealer fee (0.15%) and credit enhancement fee (0.25%).",
    "ExplanationWrongC": "4.85% results from double-counting the dealer fee.",
    "ExplanationWrongD": "5.05% appears to misread the credit enhancement fee as 0.45% instead of 0.25%.",
    "QuestionType": "select", "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationRequired": true,
    "distractor_intent": {"B": {"misconception": "Omitted placement and enhancement fees", "why_plausible": "Base yield is the most visible number", "tier_candidate": false}, "C": {"misconception": "Double-counted dealer fee", "why_plausible": "Plausible miscalculation when fees listed separately", "tier_candidate": false}, "D": {"misconception": "Misread credit enhancement fee", "why_plausible": "Reading error that inflates total cost", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Fabozzi F.J., Capital Markets"],
    "source_support_for_key": {"A": "All-in cost = 4.2% + 0.15% + 0.25% = 4.60%", "B": "Excluding fees understates true cost", "C": "Double-counting dealer fee inflates rate", "D": "Misreading fee overstates cost"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-565", "Part": 2, "Section": "B", "Topic": "B.5 Cash concentration and pooling",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Goldman and Partners, a regional insurance company, maintains depository accounts at six banks across the Midwest. The treasury team sweeps excess balances above $200,000 from each regional account into a master concentration account at the lead bank each evening. Which cash management technique is Goldman and Partners employing?",
    "Choices": {"A": "Cash pooling with notional aggregation", "B": "Lockbox collection acceleration", "C": "Disbursement float optimization", "D": "Cash concentration via zero-balance accounts"},
    "CorrectChoice": "D",
    "ExplanationCorrect": "Goldman and Partners uses cash concentration with zero-balance accounts (ZBAs). Each regional account is swept to the $200,000 target each evening, with excess funds transferred to the master concentration account.",
    "ExplanationWrongA": "Notional pooling aggregates balances for interest calculation without physical transfers. Goldman physically sweeps funds.",
    "ExplanationWrongB": "Lockbox acceleration speeds up receipt processing. Goldman addresses existing balance management.",
    "ExplanationWrongC": "Disbursement float optimization involves timing payments. Goldman concentrates existing balances.",
    "ExplanationWrongD": "",
    "QuestionType": "select", "Difficulty": "Easy", "DifficultyScore": 1, "CognitiveLevel": "Understand", "CalculationRequired": false,
    "distractor_intent": {"A": {"misconception": "Confused physical sweep with notional aggregation", "why_plausible": "Both are concentration techniques but differ in mechanism", "tier_candidate": false}, "B": {"misconception": "Confused concentration with collection acceleration", "why_plausible": "Lockbox is a well-known cash management term", "tier_candidate": false}, "C": {"misconception": "Confused balance consolidation with payment timing", "why_plausible": "Both are cash management tools but different functions", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Cash concentration literature"],
    "source_support_for_key": {"A": "Notional pooling keeps balances in place; Goldman sweeps", "B": "Lockbox accelerates receipts; Goldman consolidates balances", "C": "Disbursement optimization addresses payment timing", "D": "Physical sweeps from regional accounts to master ZBA = cash concentration"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-566", "Part": 2, "Section": "B", "Topic": "B.5 Float management - lockbox cost-benefit",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Cascade Electronics currently mails invoices to customers, resulting in 5 days of collection float. The treasury team proposes implementing a regional lockbox system that would reduce collection float to 2 days while adding $2,400 per month in lockbox fees. Cascade's average daily collections are $60,000, and its opportunity cost of funds is 7%. What is the annual float-reduction benefit of the proposed lockbox system?",
    "Choices": {"A": "$12,600", "B": "$126,000", "C": "$152,400", "D": "$180,000"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "Float reduction = 5 - 2 = 3 days. Freed funds = 3 x $60,000 = $180,000. Annual benefit = $180,000 x 7% = $12,600.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$126,000 results from a decimal error, computing $180,000 x 70% instead of 7%.",
    "ExplanationWrongC": "$152,400 adds the annual lockbox fee ($28,800) to the freed funds rather than computing the opportunity cost savings.",
    "ExplanationWrongD": "$180,000 is the gross freed funds without applying the opportunity cost rate.",
    "QuestionType": "select", "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Analyze", "CalculationRequired": true,
    "distractor_intent": {"B": {"misconception": "Decimal error in opportunity cost rate", "why_plausible": "Decimal shift produces same order of magnitude", "tier_candidate": false}, "C": {"misconception": "Added fee to freed funds instead of computing savings", "why_plausible": "Combining freed funds with fee is plausible error", "tier_candidate": false}, "D": {"misconception": "Selected gross freed funds without opportunity cost", "why_plausible": "Raw float reduction is the most prominent number", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Float management case studies"],
    "source_support_for_key": {"A": "Annual benefit = 3 days x $60,000 x 7% = $12,600", "B": "Decimal error in opportunity cost computation", "C": "Fee addition confuses freed funds with benefit", "D": "Gross freed funds is not the benefit; the return is"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-567", "Part": 2, "Section": "B", "Topic": "B.5 Short-term financing - repurchase agreements",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Tidewater Capital has $50 million in Treasury securities and needs short-term funding for 10 days. Tidewater enters a repurchase agreement at 3.8% with a government securities dealer. Using a 360-day year, how much must Tidewater pay to repurchase the securities?",
    "Choices": {"A": "$50,000,000", "B": "$50,052,778", "C": "$50,104,110", "D": "$50,190,000"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "Interest = $50,000,000 x 3.8% x (10/360) = $52,778. Repurchase price = $50,000,000 + $52,778 = $50,052,778.",
    "ExplanationWrongA": "$50,000,000 is the face value with no interest added.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "$50,104,110 results from applying the rate to a 20-day period instead of 10 days.",
    "ExplanationWrongD": "$50,190,000 results from computing full-year interest ($1,900,000) without prorating for 10 days.",
    "QuestionType": "numeric", "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Apply", "CalculationRequired": true,
    "distractor_intent": {"A": {"misconception": "Ignored interest entirely", "why_plausible": "Face value is the most prominent number", "tier_candidate": false}, "C": {"misconception": "Doubled the term to 20 days", "why_plausible": "Misreading maturity produces plausible amount", "tier_candidate": false}, "D": {"misconception": "Used full-year interest without prorating", "why_plausible": "Annual rate without time adjustment is common error", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Repurchase agreement mechanics"],
    "source_support_for_key": {"A": "Face value without interest understates price", "B": "Repurchase = $50M + $50M x 3.8% x 10/360 = $50,052,778", "C": "Doubling term overstates accrued interest", "D": "Full-year interest without prorating is incorrect"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-568", "Part": 2, "Section": "B", "Topic": "B.5 Working capital financing - matching principle",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Westfield Industries finances all of its fixed assets and permanent current assets with long-term debt and equity, and finances only its temporary current assets with short-term borrowing. This approach is best described as which working capital financing strategy?",
    "Choices": {"A": "Aggressive strategy", "B": "Conservative strategy", "C": "Hedging or matching strategy", "D": "Zero-risk strategy"},
    "CorrectChoice": "C",
    "ExplanationCorrect": "The matching (or hedging) strategy matches financing maturity to asset maturity.",
    "ExplanationWrongA": "The aggressive strategy finances permanent current assets with short-term borrowing.",
    "ExplanationWrongB": "The conservative strategy uses long-term sources for some temporary current assets.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Zero-risk strategy is not a recognized financing approach.",
    "QuestionType": "select", "Difficulty": "Mod-Easy", "DifficultyScore": 2, "CognitiveLevel": "Understand", "CalculationRequired": false,
    "distractor_intent": {"A": {"misconception": "Confused matching with aggressive", "why_plausible": "Both use short-term but at different levels", "tier_candidate": false}, "B": {"misconception": "Confused matching with conservative", "why_plausible": "Conservative and matching overlap in long-term use", "tier_candidate": false}, "D": {"misconception": "Assumed risk-free approach exists", "why_plausible": "Plausible-sounding but fictitious strategy name", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Working capital management literature"],
    "source_support_for_key": {"A": "Aggressive uses short-term for permanent assets", "B": "Conservative uses long-term for temporary assets", "C": "Matching aligns financing maturity with asset maturity", "D": "Zero-risk is not a recognized term in finance"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-569", "Part": 2, "Section": "B", "Topic": "B.5 Short-term financing - lines of credit",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Northbridge Ventures obtains a $5 million committed line of credit from its lead bank. The bank charges a commitment fee of 0.40% on the unused portion of the line. Northbridge draws $3.2 million on the line during the first quarter and pays interest at prime plus 1.5%. If the prime rate is 5.5%, what is the total cost of the committed line of credit for the quarter?",
    "Choices": {"A": "$18,000", "B": "$38,000", "C": "$74,000", "D": "$57,800"},
    "CorrectChoice": "D",
    "ExplanationCorrect": "Drawn = $3,200,000; unused = $1,800,000. Interest rate = 7.0%. Quarterly interest = $3,200,000 x 7.0% / 4 = $56,000. Commitment fee = $1,800,000 x 0.40% / 4 = $1,800. Total = $57,800.",
    "ExplanationWrongA": "$18,000 represents only the commitment fee component, ignoring drawn interest.",
    "ExplanationWrongB": "$38,000 results from computing the commitment fee on the full line rather than the unused portion.",
    "ExplanationWrongC": "$74,000 annualizes the quarterly interest instead of prorating it.",
    "ExplanationWrongD": "",
    "QuestionType": "numeric", "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Apply", "CalculationRequired": true,
    "distractor_intent": {"A": {"misconception": "Computed only commitment fee", "why_plausible": "Commitment fee is visible but minor component", "tier_candidate": false}, "B": {"misconception": "Used total line instead of drawn balance", "why_plausible": "Rate on full line understates interest", "tier_candidate": false}, "C": {"misconception": "Annualized quarterly interest", "why_plausible": "Time-basis error inflates quarterly cost", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Bank credit facility literature"],
    "source_support_for_key": {"A": "Commitment fee alone understates total cost", "B": "Full line amount understates interest", "C": "Annualized rate overstates quarterly cost", "D": "Total = $56,000 interest + $1,800 fee = $57,800"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-570", "Part": 2, "Section": "B", "Topic": "B.5 Short-term financing - bridge financing",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Clearwater Industries is building a new manufacturing facility and needs $20 million to begin construction. The company plans to issue 20-year bonds in six months once the facility is partially completed and appraised. In the meantime, Clearwater obtains a six-month bridge loan from its investment bank. This bridge loan is best classified as what type of financing?",
    "Choices": {"A": "Permanent working capital financing", "B": "Interim or transition financing", "C": "Seasonal current asset financing", "D": "Spontaneous financing"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "Bridge financing is interim or transition financing providing temporary funding until permanent financing is arranged.",
    "ExplanationWrongA": "Permanent working capital financing is long-term funding for ongoing operations.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Seasonal financing addresses cyclical fluctuations.",
    "ExplanationWrongD": "Spontaneous financing arises from operations.",
    "QuestionType": "select", "Difficulty": "Mod-Easy", "DifficultyScore": 2, "CognitiveLevel": "Understand", "CalculationRequired": false,
    "distractor_intent": {"A": {"misconception": "Confused bridge with permanent financing", "why_plausible": "Bridge loans fund capital projects", "tier_candidate": false}, "C": {"misconception": "Assumed all short-term is seasonal", "why_plausible": "Seasonal financing is most common category", "tier_candidate": false}, "D": {"misconception": "Confused negotiated with spontaneous", "why_plausible": "Spontaneous financing is well-known concept", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Bridge financing literature"],
    "source_support_for_key": {"A": "Bridge loans are temporary not permanent", "B": "Bridge financing provides interim funding until permanent capital", "C": "Seasonal financing addresses cyclical needs", "D": "Spontaneous financing is operational and interest-free"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-571", "Part": 2, "Section": "B", "Topic": "B.5 Cash management - Miller-Orr model assumptions",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Which of the following is a key assumption underlying the Miller-Orr cash management model?",
    "Choices": {"A": "Cash inflows and outflows are predictable and uniform throughout the period", "B": "The firm maintains a fixed cash balance at all times", "C": "Daily cash flows follow a random walk with no discernible pattern", "D": "Transaction costs are zero and only opportunity costs are considered"},
    "CorrectChoice": "C",
    "ExplanationCorrect": "The Miller-Orr model assumes daily cash flows are random and unpredictable, following a random walk.",
    "ExplanationWrongA": "This describes the Baumol model assumption.",
    "ExplanationWrongB": "Miller-Orr allows the balance to fluctuate between upper and lower control limits.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "The Miller-Orr model incorporates both transaction costs and opportunity costs.",
    "QuestionType": "select", "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Remember", "CalculationRequired": false,
    "distractor_intent": {"A": {"misconception": "Confused Miller-Orr with Baumol", "why_plausible": "Baumol is the other major cash model", "tier_candidate": false}, "B": {"misconception": "Assumed fixed-balance policy", "why_plausible": "Fixed balance is intuitive but incorrect", "tier_candidate": false}, "D": {"misconception": "Assumed only one cost component", "why_plausible": "Simplifying to one cost type is common error", "tier_candidate": false}},
    "source_ids": ["Miller M.H. and Orr D., 1966", "IMA CMA Part 2 LOS B.5"],
    "source_support_for_key": {"A": "Baumol assumption not Miller-Orr", "B": "Miller-Orr allows fluctuation between limits", "C": "Random-walk cash flows are the defining assumption", "D": "Both transaction and opportunity costs drive solution"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-572", "Part": 2, "Section": "B", "Topic": "B.5 Cash flow forecasting - direct method",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Ironwood Steel is preparing a 13-week cash flow forecast. The controller's team tracks each customer payment individually, projects the exact timing of payroll disbursements, and schedules each vendor payment by invoice date. This approach is best described as which forecasting method?",
    "Choices": {"A": "Direct or receipts-and-disbursements method", "B": "Aggregate planning method", "C": "Probabilistic simulation method", "D": "Seasonal adjustment method"},
    "CorrectChoice": "A",
    "ExplanationCorrect": "The direct (or receipts-and-disbursements) method forecasts cash flows by tracking individual transactions.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "The aggregate planning method uses high-level categories not individual transactions.",
    "ExplanationWrongC": "Probabilistic simulation uses probability distributions not scheduled transactions.",
    "ExplanationWrongD": "Seasonal adjustment applies historical patterns not individual transaction tracking.",
    "QuestionType": "select", "Difficulty": "Easy", "DifficultyScore": 1, "CognitiveLevel": "Remember", "CalculationRequired": false,
    "distractor_intent": {"B": {"misconception": "Confused detailed tracking with aggregate", "why_plausible": "Aggregate methods are a common alternative", "tier_candidate": false}, "C": {"misconception": "Assumed probabilistic modeling", "why_plausible": "Monte Carlo is a sophisticated technique", "tier_candidate": false}, "D": {"misconception": "Confused transaction tracking with seasonal", "why_plausible": "Seasonal adjustment is a standard tool", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Cash forecasting literature"],
    "source_support_for_key": {"A": "Direct method tracks each receipt and disbursement individually", "B": "Aggregate uses categories not individual transactions", "C": "Probabilistic uses distributions not scheduled invoices", "D": "Seasonal adjustment applies patterns not transactions"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-573", "Part": 2, "Section": "B", "Topic": "B.5 Short-term financing - banker's acceptances",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Lakeshore Trading Company needs to pay a foreign supplier $2 million for imported components. The supplier demands guaranteed payment, but Lakeshore wants to delay cash outflow for 60 days. Lakeshore's bank issues a banker's acceptance for the full amount. Which of the following best describes Lakeshore's financing arrangement?",
    "Choices": {"A": "Lakeshore borrows directly from the bank at the prime rate", "B": "The bank lends the $2 million and charges commitment fees", "C": "The supplier extends trade credit to Lakeshore for 60 days", "D": "The bank guarantees payment creating a money-market instrument sellable at a discount"},
    "CorrectChoice": "D",
    "ExplanationCorrect": "A banker's acceptance is a bank-guaranteed promise to pay, creating a negotiable money-market instrument.",
    "ExplanationWrongA": "A banker's acceptance is not a direct bank loan.",
    "ExplanationWrongB": "This describes a committed line of credit, not a banker's acceptance.",
    "ExplanationWrongC": "Trade credit is extended by the supplier, not by a bank.",
    "ExplanationWrongD": "",
    "QuestionType": "select", "Difficulty": "Moderate", "DifficultyScore": 3, "CognitiveLevel": "Understand", "CalculationRequired": false,
    "distractor_intent": {"A": {"misconception": "Confused acceptance with bank loan", "why_plausible": "Both involve a bank but different mechanism", "tier_candidate": false}, "B": {"misconception": "Confused acceptance with line of credit", "why_plausible": "Lines of credit are common bank tool", "tier_candidate": false}, "C": {"misconception": "Assumed supplier provided credit", "why_plausible": "Trade credit is common short-term financing", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Money market instruments literature"],
    "source_support_for_key": {"A": "Banker's acceptance is a guarantee not a loan", "B": "Lines of credit involve commitment fees; acceptances do not", "C": "The bank not the supplier provides the guarantee", "D": "Banker's acceptance = bank-guaranteed payment sold at discount"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-574", "Part": 2, "Section": "B", "Topic": "B.5 Working capital financing - conservative strategy",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Pinnacle Components finances all of its fixed assets and permanent current assets with long-term debt and equity. Additionally Pinnacle finances a portion of its seasonal current asset needs with long-term sources keeping short-term borrowing to a minimum. Which working capital financing strategy does this describe?",
    "Choices": {"A": "Matching strategy", "B": "Conservative strategy", "C": "Aggressive strategy", "D": "Zero-risk strategy"},
    "CorrectChoice": "B",
    "ExplanationCorrect": "The conservative strategy uses long-term financing for all fixed assets, all permanent current assets, and even a portion of temporary current assets.",
    "ExplanationWrongA": "The matching strategy uses short-term sources for all temporary current assets.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "The aggressive strategy uses short-term borrowing for permanent current assets.",
    "ExplanationWrongD": "Zero-risk strategy is not a recognized approach.",
    "QuestionType": "select", "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Analyze", "CalculationRequired": false,
    "distractor_intent": {"A": {"misconception": "Confused conservative with matching", "why_plausible": "Both use long-term for permanent assets", "tier_candidate": false}, "C": {"misconception": "Confused conservative with aggressive", "why_plausible": "These are opposite strategies", "tier_candidate": false}, "D": {"misconception": "Assumed risk-free strategy exists", "why_plausible": "Conservative minimizes risk but does not eliminate it", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "Working capital management literature"],
    "source_support_for_key": {"A": "Matching uses short-term for temporary assets", "B": "Conservative = long-term for all assets including some temporary", "C": "Aggressive uses short-term for permanent assets", "D": "No financing strategy eliminates all risk"},
    "question_state": "Unprocessed"
  },
  {
    "QuestionID": "P2-B-575", "Part": 2, "Section": "B", "Topic": "B.5 Disbursement optimization - zero-balance accounts",
    "LOSTag": "B.5", "Part2OnlyFlag": true,
    "Stem": "Summit Industrial maintains a master disbursement account and three regional zero-balance accounts at different banks. When a check drawn on a regional ZBA clears funds are automatically transferred from the master account to cover the payment. What is the primary cash management benefit of this ZBA arrangement?",
    "Choices": {"A": "It reduces the firm's total annual disbursement volume", "B": "It extends the collection float on customer payments", "C": "It concentrates idle balances into the master account for investment", "D": "It eliminates the need for bank reconciliation"},
    "CorrectChoice": "C",
    "ExplanationCorrect": "Zero-balance accounts keep regional balances at zero until checks clear. Funds remain in the master account where they earn interest.",
    "ExplanationWrongA": "ZBAs do not change total disbursement volume.",
    "ExplanationWrongB": "ZBAs address the disbursement side not collection float.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "ZBAs add complexity to bank reconciliation.",
    "QuestionType": "select", "Difficulty": "Difficult", "DifficultyScore": 4, "CognitiveLevel": "Evaluate", "CalculationRequired": false,
    "distractor_intent": {"A": {"misconception": "Assumed ZBAs reduce total payments", "why_plausible": "ZBAs optimize fund placement not payment amounts", "tier_candidate": false}, "B": {"misconception": "Confused disbursement ZBAs with collection float", "why_plausible": "Float management is a related concept", "tier_candidate": false}, "D": {"misconception": "Assumed automation eliminates reconciliation", "why_plausible": "Automated transfers might seem to reduce work", "tier_candidate": false}},
    "source_ids": ["IMA CMA Part 2 LOS B.5", "ZBA cash management literature"],
    "source_support_for_key": {"A": "ZBAs do not change payment volume", "B": "ZBAs address disbursements not collection float", "C": "ZBAs keep regional balances at zero concentrating idle funds", "D": "ZBAs add reconciliation complexity"},
    "question_state": "Unprocessed"
  }
]
