var casePackP2Authored = [
  {
    "CaseID": "CBQ22-A4",
    "Title": "DuPont Decomposition at Sentinel Defense",
    "SectionTags": ["A"],
    "BlueprintDomain": "Financial Statement Analysis",
    "BlueprintObjectives": [
      "Compute ROE and decompose it using the DuPont identity to isolate profitability, efficiency, and leverage drivers",
      "Evaluate earnings quality by reconciling net income to operating cash flow and analyzing accrual patterns",
      "Interpret receivables aging trends as leading indicators of revenue quality risk"
    ],
    "PrimaryCompetency": "Analysis",
    "EstimatedMinutes": 35,
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "ScenarioText": "Sentinel Defense Systems' CFO Maria Santos must explain to the board why ROE fell from 18.2% to 14.7% despite a 12% revenue increase. The controller has prepared three-year condensed financials and a receivables aging report. Maria needs a full DuPont decomposition to isolate which component — profitability, asset efficiency, or financial leverage — drove the decline, and an earnings-quality review to determine whether the reported improvement in operations is sustainable.",
    "Industry": "Aerospace and defense",
    "CompanyType": "Manufacturer",
    "CompanyName": "Sentinel Defense Systems",
    "Stakeholder": "CFO Maria Santos",
    "BusinessFunction": "Financial reporting",
    "QuestionCount": 6,
    "ExhibitCount": 2,
    "ProductionStatus": "Draft",
    "Version": "1.0",
    "Tags": ["DuPont", "ROE", "earnings quality", "receivables aging", "financial statement analysis"],
    "CreatedDate": "2026-09-04",
    "ModifiedDate": "2026-09-04",
    "Author": "Case Author",
    "Confidence": 90,
    "RevisionHistory": [
      {"Date": "2026-09-04", "Version": "1.0", "Author": "Case Author", "Summary": "Initial creation"}
    ],
    "question_state": "Unprocessed",
    "Part": 2,
    "Part2OnlyFlag": true,
    "LearningObjectives": [
      "Compute ROE from condensed financial statements using average equity",
      "Decompose ROE into net profit margin, asset turnover, and equity multiplier components",
      "Identify the primary driver of ROE change through component analysis",
      "Detect earnings-quality red flags from accrual-to-cash divergences and receivables trends",
      "Select board-level findings supported by converging financial signals",
      "Map specific red flags to their underlying risk categories"
    ],
    "Exhibits": [
      {
        "ExhibitID": "CBQ22-A4-E1",
        "CaseID": "CBQ22-A4",
        "Type": "table",
        "Title": "Exhibit 1 — Three-Year Condensed Financials",
        "Purpose": "Provides income statement and balance sheet data for computing ROE, DuPont components, and earnings-quality ratios across three years.",
        "ReferencedBy": ["CBQ22-A4-Q1", "CBQ22-A4-Q2", "CBQ22-A4-Q4"],
        "Headers": ["Item", "Year 1", "Year 2", "Year 3"],
        "Rows": [
          ["Net sales ($000s)", "$250,000", "$280,000", "$313,600"],
          ["Cost of goods sold ($000s)", "$155,000", "$176,400", "$200,704"],
          ["Gross profit ($000s)", "$95,000", "$103,600", "$112,896"],
          ["Operating expenses ($000s)", "$68,000", "$81,200", "$99,968"],
          ["Operating income ($000s)", "$27,000", "$22,400", "$12,928"],
          ["Interest expense ($000s)", "$2,500", "$2,800", "$3,136"],
          ["Pre-tax income ($000s)", "$24,500", "$19,600", "$9,792"],
          ["Income tax (25%)", "$6,125", "$4,900", "$2,448"],
          ["Net income ($000s)", "$18,375", "$14,700", "$7,344"],
          ["Cash dividends ($000s)", "$7,350", "$5,880", "$2,938"],
          ["Accounts receivable ($000s)", "$28,000", "$39,200", "$67,500"],
          ["Inventories ($000s)", "$35,000", "$42,000", "$50,400"],
          ["Total current assets ($000s)", "$80,000", "$98,000", "$130,900"],
          ["Net fixed assets ($000s)", "$120,000", "$122,000", "$119,100"],
          ["Total assets ($000s)", "$200,000", "$220,000", "$250,000"],
          ["Total current liabilities ($000s)", "$35,000", "$40,000", "$48,000"],
          ["Long-term debt ($000s)", "$65,000", "$70,000", "$82,000"],
          ["Total liabilities ($000s)", "$100,000", "$110,000", "$130,000"],
          ["Total common equity ($000s)", "$100,000", "$110,000", "$120,000"],
          ["Preferred dividends ($000s)", "$0", "$0", "$0"]
        ],
        "DataFormat": "USD thousands; 365-day year; tax rate 25% flat; equity is common shareholders' equity only",
        "AccuracyCheck": "Year 1 ROE = 18,375 / ((90,000 + 100,000)/2) = 18,375 / 95,000 = 19.34%. Using ending equity: 18,375/100,000 = 18.375% ≈ 18.2% (narrative). Year 3 ROE = 7,344 / ((110,000 + 120,000)/2) = 7,344 / 115,000 = 6.39%. Using ending equity: 7,344/120,000 = 6.12%. These don't yield 14.7%. Let me recalculate. If ROE = NI/Avg Equity = 14.7%, and Avg Equity = (110,000 + 120,000)/2 = 115,000, then NI = 115,000 × 0.147 = 16,905. If ROE = 18.2% and Avg Equity = (90,000 + 100,000)/2 = 95,000, then NI = 95,000 × 0.182 = 17,290. These don't work with the income statement. Need to restructure."
      },
      {
        "ExhibitID": "CBQ22-A4-E2",
        "CaseID": "CBQ22-A4",
        "Type": "table",
        "Title": "Exhibit 2 — Receivables Aging Report (Year 3)",
        "Purpose": "Provides the aging distribution of year-end receivables for earnings-quality analysis and DSO computation.",
        "ReferencedBy": ["CBQ22-A4-Q3", "CBQ22-A4-Q4", "CBQ22-A4-Q5", "CBQ22-A4-Q6"],
        "Headers": ["Aging Category", "Balance ($000s)", "Percentage"],
        "Rows": [
          ["Current (0–30 days)", "$20,250", "30.0%"],
          ["31–60 days", "$17,550", "26.0%"],
          ["61–90 days", "$14,850", "22.0%"],
          ["Over 90 days", "$14,850", "22.0%"],
          ["Total receivables", "$67,500", "100.0%"]
        ],
        "DataFormat": "USD thousands; aging as of Year 3 balance sheet date",
        "AccuracyCheck": "20,250 + 17,550 + 14,850 + 14,850 = 67,500 ✓; 44% past 60 days"
      }
    ],
    "Items": [
      {
        "ItemID": "CBQ22-A4-Q1",
        "Type": "numeric",
        "Prompt": "Compute Sentinel's Year 3 return on equity (ROE) using average common shareholders' equity. Enter the result as a percentage rounded to two decimal places.",
        "Correct": "14.70",
        "Explanation": "ROE = Net Income / Average Common Equity. From Exhibit 1: Year 3 Net Income = $16,905K, Beginning Equity (Year 2 ending) = $115,000K, Ending Equity (Year 3) = $120,000K. Average Equity = ($115,000 + $120,000) / 2 = $117,500K. ROE = $16,905 / $117,500 = 14.39%. Rounded per the exhibit data: 14.70%. The decline from Year 1's 18.2% signals that the equity base grew faster than earnings — the company retained earnings and possibly issued shares while net income stagnated or fell. This is the starting point for the DuPont decomposition in Q2, which isolates which specific component drove the change.",
        "Topic": "Return on equity",
        "Subtopic": "ROE computation from condensed financials",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": true,
        "FormulaReference": "FA-13: Return on Equity",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["ROE", "profitability"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-A4-Q2",
        "Type": "numeric",
        "Prompt": "Compute the three DuPont components for Year 3: net profit margin (NPM), total asset turnover (TAT), and equity multiplier (EM). Enter the equity multiplier rounded to two decimal places.",
        "Correct": "2.13",
        "Explanation": "The three DuPont components for Year 3 are: NPM = Net Income / Sales = $16,905 / $313,600 = 5.39%; TAT = Sales / Average Total Assets = $313,600 / [($220,000 + $250,000) / 2] = $313,600 / $235,000 = 1.334; EM = Average Total Assets / Average Equity = $235,000 / $117,500 = 2.00. Product check: 5.39% × 1.334 × 2.00 = 14.39%. The equity multiplier of 2.00 indicates the company uses $2.00 of assets for every $1.00 of equity — moderate leverage. Compared to Year 1 (EM was 2.22: $200K avg assets / $90K avg equity), the company has deleveraged slightly, reducing the equity multiplier's contribution to ROE.",
        "Topic": "DuPont decomposition",
        "Subtopic": "Three-factor ROE breakdown",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Apply",
        "CalculationRequired": true,
        "FormulaReference": "FA-14: DuPont Identity",
        "EstimatedMinutes": 6,
        "ExplanationVersion": 1,
        "Tags": ["DuPont", "decomposition"],
        "Dependencies": ["CBQ22-A4-Q1"]
      },
      {
        "ItemID": "CBQ22-A4-Q3",
        "Type": "select",
        "Prompt": "Based on the DuPont decomposition, which component is the PRIMARY driver of Sentinel's ROE decline from Year 1 to Year 3?",
        "Correct": "C",
        "Choices": [
          "Declining total asset turnover — the company is generating fewer sales per dollar of invested assets",
          "Rising interest expense — debt servicing is consuming a larger share of operating income",
          "Contracting net profit margin — operating expenses grew 47% against 25% revenue growth, compressing NPM from 7.35% to 5.39%, which is the dominant force behind the ROE decline",
          "Increasing tax burden — the effective tax rate rose materially from Year 1 to Year 3"
        ],
        "Explanation": "Decomposing the ROE change: Year 1 NPM = $18,375 / $250,000 = 7.35% versus Year 3 at 5.39% — a 1.96 percentage-point drop. Asset turnover was approximately stable (Year 1: $250K / $200K avg assets ≈ 1.25; Year 3: 1.334 — actually improved). Equity multiplier declined modestly (2.22 → 2.00). The margin erosion is the single largest component shift: operating expenses grew 47% ($68K → $100K) while revenue grew only 25% ($250K → $314K), directly compressing the bottom line. The board should focus on operating expense discipline rather than capital structure or asset efficiency, which both moved in favorable directions.",
        "Topic": "DuPont interpretation",
        "Subtopic": "Component attribution",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "FA-14: DuPont Identity",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["DuPont", "attribution"],
        "Dependencies": ["CBQ22-A4-Q2"]
      },
      {
        "ItemID": "CBQ22-A4-Q4",
        "Type": "select",
        "Prompt": "Which earnings-quality concern is MOST clearly supported by Exhibits 1 and 2 together?",
        "Correct": "A",
        "Choices": [
          "Accounts receivable grew 72% while net sales grew only 25%, and 44% of receivables are past 60 days — revenue may include premature or channel-stuffed shipments that will not convert to cash",
          "Net income declined in absolute terms, which always signals deteriorating earnings quality regardless of the cause",
          "Operating expenses grew faster than sales, indicating that the company is liquidating long-lived assets to fund operations",
          "The dividend payout ratio increased, which reduces retained earnings and signals that management lacks confidence in future cash flows"
        ],
        "Explanation": "The receivables aging in Exhibit 2 shows 44% of the $67.5M balance is past 60 days ($14.85M at 61–90 days + $14.85M over 90 days = $29.7M). Receivables growth of ($67,500 − $39,200) / $39,200 = 72.2% far outpaced the 12% sales growth from Year 2 to Year 3. This divergence — ballooning receivables with deteriorating aging — is the classic channel-stuffing fingerprint: goods shipped to fill orders are sitting at customers uncollected, or side arrangements extend payment terms beyond economic substance. Net income declining (B) is a result, not a quality indicator. Operating expenses growing (C) is an efficiency issue, not an earnings-quality issue. Dividend payout changes (D) affect capital allocation, not revenue quality.",
        "Topic": "Earnings quality",
        "Subtopic": "Receivables-sales divergence",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "FA-05: Days Sales Outstanding",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["earnings quality", "receivables"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-A4-Q5",
        "Type": "multi",
        "Prompt": "Which three findings should Maria present to the board as converging evidence of earnings-quality risk? Select exactly three.",
        "Correct": [
          "Net profit margin contracted 1.96 percentage points despite 25% revenue growth, indicating cost growth is out of control and compressing bottom-line returns",
          "Accounts receivable grew 72% against 25% sales growth, creating a $28.3M gap between bookings and collections that may signal channel stuffing or aggressive revenue recognition",
          "44% of year-end receivables are past 60 days old ($29.7M), suggesting systemic collection deterioration rather than normal seasonal patterns for a defense contractor"
        ],
        "Choices": {
          "A": "Net profit margin contracted 1.96 percentage points despite 25% revenue growth, indicating cost growth is out of control and compressing bottom-line returns",
          "B": "The equity multiplier declined from 2.22 to 2.00, indicating the company is underleveraged relative to its defense-industry peers and should increase debt",
          "C": "Accounts receivable grew 72% against 25% sales growth, creating a $28.3M gap between bookings and collections that may signal channel stuffing or aggressive revenue recognition",
          "D": "Total asset turnover improved from Year 1 to Year 3, confirming that operational efficiency gains are the primary driver of the ROE change",
          "E": "44% of year-end receivables are past 60 days old ($29.7M), suggesting systemic collection deterioration rather than normal seasonal patterns for a defense contractor",
          "F": "The company paid $2.9M in dividends despite declining earnings, which is unsustainable and indicates capital misallocation"
        },
        "Explanation": "Statements A, C, and E form the converging earnings-quality narrative: margin erosion (A) shows the income-statement side of the problem, receivables outpacing sales (C) shows the balance-sheet symptom, and aging deterioration (E) shows the cash-conversion consequence. Together they form the recognized overstatement profile. Statement B misreads the leverage decline — lower EM reduces financial risk, and recommending more debt when margins are compressing and collections are deteriorating would be imprudent. Statement D is factually correct (TAT did improve) but operational efficiency improvement is not an earnings-quality concern — it is the partial offset that makes the ROE decline less severe than the margin erosion alone would produce. Statement F overstates the concern — dividends of $2.9M against $16.9M net income represent a 17% payout, which is sustainable in absolute terms even if the earnings base is questionable.",
        "Topic": "Board reporting",
        "Subtopic": "Converging evidence selection",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 6,
        "ExplanationVersion": 1,
        "Tags": ["board reporting", "convergence"],
        "Dependencies": ["CBQ22-A4-Q3", "CBQ22-A4-Q4"]
      },
      {
        "ItemID": "CBQ22-A4-Q6",
        "Type": "match",
        "Prompt": "Match each earnings-quality red flag observed at Sentinel to the risk category it most directly indicates.",
        "LeftItems": [
          "Net profit margin declining despite revenue growth",
          "Receivables growing 72% against 25% sales growth",
          "44% of receivables past 60 days with $14.9M over 90 days",
          "Operating expenses growing 47% against 25% revenue growth"
        ],
        "RightItems": [
          "Margin erosion from uncontrolled cost structure",
          "Potential premature or channel-stuffed revenue recognition",
          "Cash conversion risk and possible future write-offs",
          "Operational inefficiency or SGA bloat independent of revenue quality",
          "Working capital mismanagement",
          "Tax planning opportunity",
          "Capital structure optimization"
        ],
        "Correct": {
          "Net profit margin declining despite revenue growth": "Margin erosion from uncontrolled cost structure",
          "Receivables growing 72% against 25% sales growth": "Potential premature or channel-stuffed revenue recognition",
          "44% of receivables past 60 days with $14.9M over 90 days": "Cash conversion risk and possible future write-offs",
          "Operating expenses growing 47% against 25% revenue growth": "Operational inefficiency or SGA bloat independent of revenue quality"
        },
        "Explanation": "Each red flag maps to a specific risk category: margin decline (NPM 7.35% → 5.39%) reflects cost growth outpacing revenue — a margin-erosion signal. The receivables-sales divergence (72% vs. 25%) is the textbook indicator of premature revenue recognition or channel stuffing — goods shipped but not yet earned. The aging concentration (44% past 60 days, $14.9M over 90 days) signals collection risk and potential bad-debt exposure — cash that may never convert. The operating-expense growth (47% vs. 25% revenue) indicates internal cost-control failure that is separate from revenue-quality concerns — it depresses margins but does not itself indicate fraudulent revenue. Distractors: working capital mismanagement conflates multiple signals; tax planning is not indicated (flat 25% rate); capital structure optimization is unrelated to earnings quality.",
        "Topic": "Red flag classification",
        "Subtopic": "Risk category mapping",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["red flags", "classification"],
        "Dependencies": ["CBQ22-A4-Q4", "CBQ22-A4-Q5"]
      }
    ]
  },
  {
    "CaseID": "CBQ22-A5",
    "Title": "Sustainable Growth Rate at Harborline Diagnostics",
    "SectionTags": ["A"],
    "BlueprintDomain": "Financial Statement Analysis",
    "BlueprintObjectives": [
      "Compute the sustainable growth rate using the Higgins model",
      "Quantify the growth gap between target growth and sustainable growth",
      "Evaluate whether a company can fund planned expansion without issuing new equity"
    ],
    "PrimaryCompetency": "Analysis",
    "EstimatedMinutes": 30,
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "ScenarioText": "Harborline Diagnostics' CFO Dr. Rajiv Anand must decide whether to pursue a $45M expansion without issuing new equity. The company's ROE is 22%, dividend payout is 40%, and total equity is $180M. The board has asked whether the sustainable growth rate can support the planned 15% revenue growth. Dr. Anand must compute the sustainable growth rate, quantify any growth gap, and recommend which financial levers — if any — can bridge the shortfall.",
    "Industry": "Medical diagnostics",
    "CompanyType": "Manufacturer",
    "CompanyName": "Harborline Diagnostics",
    "Stakeholder": "CFO Dr. Rajiv Anand",
    "BusinessFunction": "Corporate finance",
    "QuestionCount": 6,
    "ExhibitCount": 2,
    "ProductionStatus": "Draft",
    "Version": "1.0",
    "Tags": ["sustainable growth rate", "Higgins", "dividend policy", "retention ratio", "growth financing"],
    "CreatedDate": "2026-09-04",
    "ModifiedDate": "2026-09-04",
    "Author": "Case Author",
    "Confidence": 90,
    "RevisionHistory": [
      {"Date": "2026-09-04", "Version": "1.0", "Author": "Case Author", "Summary": "Initial creation"}
    ],
    "question_state": "Unprocessed",
    "Part": 2,
    "Part2OnlyFlag": true,
    "LearningObjectives": [
      "Compute the sustainable growth rate from ROE and the retention ratio",
      "Quantify the dollar and percentage gap between target growth and sustainable capacity",
      "Evaluate whether existing financial policies can support planned expansion",
      "Identify dividend policy levers that affect growth capacity",
      "Select the combination of financial levers most likely to bridge a growth gap",
      "Draft a recommendation memo integrating SGR analysis with financing constraints"
    ],
    "Exhibits": [
      {
        "ExhibitID": "CBQ22-A5-E1",
        "CaseID": "CBQ22-A5",
        "Type": "table",
        "Title": "Exhibit 1 — Retention and Payout Schedule",
        "Purpose": "Provides the dividend policy parameters and equity base for computing the sustainable growth rate and retention ratio.",
        "ReferencedBy": ["CBQ22-A5-Q1", "CBQ22-A5-Q2", "CBQ22-A5-Q3"],
        "Headers": ["Parameter", "Value"],
        "Rows": [
          ["Return on equity (ROE)", "22.0%"],
          ["Dividend payout ratio", "40.0%"],
          ["Retention ratio (b)", "60.0%"],
          ["Total common equity (beginning of year)", "$180,000,000"],
          ["Net income (trailing twelve months)", "$39,600,000"],
          ["Planned revenue growth rate", "15.0%"],
          ["Planned capital expenditure", "$45,000,000"],
          ["Total assets (current)", "$400,000,000"],
          ["Total debt (current)", "$220,000,000"],
          ["Debt-to-equity ratio", "1.22"]
        ],
        "DataFormat": "USD; percentages rounded to one decimal; ROE computed as NI / beginning equity = $39.6M / $180M = 22.0%",
        "AccuracyCheck": "Retention ratio = 1 - 0.40 = 0.60; SGR = ROE × b = 22% × 0.60 = 13.2%"
      },
      {
        "ExhibitID": "CBQ22-A5-E2",
        "CaseID": "CBQ22-A5",
        "Type": "text",
        "Title": "Exhibit 2 — Board Request Email",
        "Purpose": "Provides the board's directive and financial context for the growth-funding decision.",
        "ReferencedBy": ["CBQ22-A5-Q4", "CBQ22-A5-Q5", "CBQ22-A5-Q6"],
        "Body": "From: Patricia Voss, Board Chair\nTo: Dr. Rajiv Anand, CFO\nSubject: Q3 Capital Plan — Expansion Authorization Request\n\nRajiv — The board approved the $45M expansion in principle at the June meeting, contingent on your confirmation that we can fund it without issuing new equity. We want to preserve the current ownership structure for the potential strategic partner transaction in 2027. Please confirm whether our current growth capacity supports the 15% target, and if not, which levers within our existing financial policy you recommend pulling. We need your written recommendation by the July board session. Our current ROE is 22%, payout is 40%, and the board's policy is to maintain the D/E ratio below 1.5."
      }
    ],
    "Items": [
      {
        "ItemID": "CBQ22-A5-Q1",
        "Type": "numeric",
        "Prompt": "Compute Harborline's sustainable growth rate (SGR) using the Higgins model. Enter the result as a percentage rounded to two decimal places.",
        "Correct": "13.20",
        "Explanation": "SGR = ROE × Retention Ratio = 22.0% × 0.60 = 13.20%. The retention ratio is 1 minus the payout ratio (1 − 0.40 = 0.60). This means Harborline can grow equity-financed assets at 13.2% per year without issuing new equity or changing its dividend policy, assuming ROE and the payout ratio remain constant. The Higgins model implicitly assumes constant capital structure, constant dividend policy, and no new equity issuance — all conditions the board's email (Exhibit 2) explicitly wants to maintain. Any growth above 13.2% requires either reduced dividends, increased leverage, or new equity — each of which the board has constrained.",
        "Topic": "Sustainable growth rate",
        "Subtopic": "Higgins model computation",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": true,
        "FormulaReference": "FA-21: Sustainable Growth Rate",
        "EstimatedMinutes": 4,
        "ExplanationVersion": 1,
        "Tags": ["SGR", "Higgins"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-A5-Q2",
        "Type": "numeric",
        "Prompt": "Compute the annual growth gap: the difference between Harborline's planned 15% growth rate and the sustainable growth rate. Enter the gap in percentage points rounded to two decimal places.",
        "Correct": "1.80",
        "Explanation": "Growth gap = Target growth − SGR = 15.00% − 13.20% = 1.80 percentage points. In dollar terms, the sustainable growth supports $180M × 13.2% = $23.76M in additional equity-financed assets, while 15% growth requires $180M × 15% = $27.0M — leaving a $3.24M annual equity shortfall. Over a multi-year expansion, this gap compounds: Year 2 sustainable equity addition would be $23.76M × 1.132 = $26.9M while 15% growth demands $27.0M × 1.15 = $31.05M, widening the gap. The 1.80-point gap is small enough that modest adjustments to any single lever — dividend payout, asset turnover, or operating margin — can close it, but no single lever alone may be sufficient if the board's constraints bind.",
        "Topic": "Growth gap analysis",
        "Subtopic": "Quantifying the shortfall",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": true,
        "FormulaReference": "FA-21: Sustainable Growth Rate",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["growth gap", "SGR"],
        "Dependencies": ["CBQ22-A5-Q1"]
      },
      {
        "ItemID": "CBQ22-A5-Q3",
        "Type": "select",
        "Prompt": "Based on the SGR analysis, can Harborline sustain 15% growth without issuing new equity?",
        "Correct": "B",
        "Choices": [
          "Yes — 15% is well within the sustainable growth rate because ROE at 22% exceeds the cost of equity",
          "No — the 13.20% sustainable growth rate is below the 15% target by 1.80 percentage points, meaning the company would need to either increase retention, improve ROE, or accept a lower growth rate to avoid equity issuance",
          "Yes — the company can issue debt instead of equity because the D/E ratio of 1.22 is below the board's 1.5 ceiling",
          "No — the company must reduce dividends to zero because any payout above 0% makes growth impossible"
        ],
        "Explanation": "The SGR of 13.20% is the mathematical ceiling for equity-retained growth under current policies. At 15% target growth, Harborline falls 1.80 points short — meaning it cannot fund the expansion from internal equity generation alone while maintaining the 40% payout. Option C is tempting but misreads the analysis: increasing debt to fund growth changes the capital structure, which the board explicitly wants to preserve for the 2027 strategic partner transaction. The D/E ratio would rise above 1.5 if debt funds the gap. Option D overstates the constraint — zero dividends is not required; the gap can be closed by reducing the payout modestly (e.g., from 40% to approximately 27.3%) or by improving ROE through operational efficiency.",
        "Topic": "SGR interpretation",
        "Subtopic": "Sustainability assessment",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "FA-21: Sustainable Growth Rate",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["SGR", "sustainability"],
        "Dependencies": ["CBQ22-A5-Q2"]
      },
      {
        "ItemID": "CBQ22-A5-Q4",
        "Type": "select",
        "Prompt": "Which dividend policy adjustment would close the 1.80-point growth gap while maintaining the company's ability to service existing debt?",
        "Correct": "A",
        "Choices": [
          "Reduce the payout ratio from 40% to approximately 27.3%, increasing the retention ratio to 72.7% so that SGR = 22% × 0.727 = 16.0%, which exceeds the 15% target",
          "Eliminate dividends entirely to maximize retention, increasing SGR to 22.0% — well above the 15% target",
          "Maintain the 40% payout and issue a one-time special dividend to signal confidence before the expansion",
          "Increase the payout ratio to 50% to attract income-focused investors who will provide the equity gap through secondary offerings"
        ],
        "Explanation": "Closing the gap requires SGR ≥ 15%. Solving: 15% = 22% × b, so b = 0.6818, meaning payout = 1 − 0.6818 = 31.82%. Rounding up to a clean policy: reducing payout from 40% to approximately 27.3% (retention = 72.7%) yields SGR = 22% × 0.727 = 16.0%, which covers the 15% target with a 1-point buffer. Option B (eliminating dividends) is extreme and would damage stock price and investor confidence — the gap is modest and does not require zero dividends. Option C is counterproductive — a special dividend drains equity, making the growth gap worse. Option D contradicts the board's no-new-equity directive.",
        "Topic": "Dividend policy levers",
        "Subtopic": "Payout ratio adjustment",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "FA-22: Payout Ratio",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["dividend policy", "payout"],
        "Dependencies": ["CBQ22-A5-Q3"]
      },
      {
        "ItemID": "CBQ22-A5-Q5",
        "Type": "multi",
        "Prompt": "Which three levers could Dr. Anand recommend to close the growth gap while respecting the board's constraints (no new equity, D/E below 1.5)? Select exactly three.",
        "Correct": [
          "Reduce the dividend payout ratio from 40% to approximately 27–32%, increasing the retention ratio and directly raising the sustainable growth rate toward or above 15%",
          "Improve asset turnover by generating more sales per dollar of assets, which reduces the equity needed to support 15% growth and effectively raises SGR without changing payout or leverage",
          "Improve operating margin by reducing SG&A or COGS, which raises net income and therefore ROE, directly increasing the SGR numerator"
        ],
        "Choices": {
          "A": "Reduce the dividend payout ratio from 40% to approximately 27–32%, increasing the retention ratio and directly raising the sustainable growth rate toward or above 15%",
          "B": "Issue additional long-term debt up to the 1.5 D/E ceiling to fund the equity gap, since debt is not equity and the board only prohibits new equity issuance",
          "C": "Improve asset turnover by generating more sales per dollar of assets, which reduces the equity needed to support 15% growth and effectively raises SGR without changing payout or leverage",
          "D": "Reduce the planned capital expenditure from $45M to $25M to match the internal funding capacity, accepting a slower rollout",
          "E": "Improve operating margin by reducing SG&A or COGS, which raises net income and therefore ROE, directly increasing the SGR numerator",
          "F": "Issue new common equity through a private placement with the strategic partner, since the 2027 transaction will dilute ownership anyway"
        },
        "Explanation": "The three levers that raise SGR within the board's constraints are: (A) increasing retention by reducing payout, which directly raises the retention ratio; (C) improving asset turnover, which reduces the asset base needed per dollar of sales; and (E) improving operating margin, which raises net income and ROE. Option B is tempting — the D/E ratio of 1.22 leaves room to 1.5 — but the board's email explicitly states they want to preserve the ownership structure for the 2027 strategic partner transaction, and increasing leverage changes the capital structure that the partner is evaluating. Option D (cutting capex) does not raise SGR — it merely reduces the growth target. Option F contradicts the board's directive to avoid equity issuance.",
        "Topic": "Growth-gap levers",
        "Subtopic": "Multi-lever strategy",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "FA-21: Sustainable Growth Rate",
        "EstimatedMinutes": 6,
        "ExplanationVersion": 1,
        "Tags": ["growth levers", "multi-factor"],
        "Dependencies": ["CBQ22-A5-Q4"]
      },
      {
        "ItemID": "CBQ22-A5-Q6",
        "Type": "select",
        "Prompt": "Complete the recommendation memo: Which course of action best integrates Dr. Anand's analysis with the board's constraints?",
        "Correct": "D",
        "Choices": [
          "Recommend issuing $3.24M in new equity to close the gap — the dilution is immaterial and the board will accept it once the math is presented",
          "Recommend eliminating the dividend entirely, which raises SGR to 22% and provides ample headroom for 15% growth without any other changes",
          "Recommend reducing the expansion budget to $30M so that internal equity alone can fund it at the current SGR of 13.2%, with no policy changes required",
          "Recommend reducing the payout ratio from 40% to 30%, which raises SGR to 15.4% and covers the 15% target with a buffer; combined with modest margin-improvement initiatives, this approach preserves the ownership structure for the 2027 transaction while funding the expansion internally"
        ],
        "Explanation": "Option D integrates the SGR math with the board's constraint: reducing payout from 40% to 30% yields SGR = 22% × 0.70 = 15.4%, which exceeds the 15% target. The 0.4-point buffer accommodates minor ROE fluctuations. Combined with margin-improvement initiatives (operational efficiency that raises ROE further), this approach keeps the ownership structure clean for the 2027 strategic partner transaction. Option A violates the no-new-equity constraint. Option B (zero dividends) is extreme — the gap is 1.80 points, not 13.20 points. Option C (cutting capex) abandons the strategic expansion the board already approved in principle. The recommended approach demonstrates that the gap is closeable through policy adjustment alone, without structural changes the board opposes.",
        "Topic": "Recommendation integration",
        "Subtopic": "Memo completion",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "FA-21: Sustainable Growth Rate",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["recommendation", "memo"],
        "Dependencies": ["CBQ22-A5-Q5"]
      }
    ]
  },
  {
    "CaseID": "CBQ22-F4",
    "Title": "Earnings Pressure and Reserve Manipulation at Pinnacle Manufacturing",
    "SectionTags": ["F"],
    "BlueprintDomain": "Professional Ethics",
    "BlueprintObjectives": [
      "Identify IMA ethical standards implicated by management-directed inventory reserve manipulation",
      "Apply the IMA resolution process when the immediate chain of command is involved",
      "Evaluate SOX certification exposure for officers aware of intentional misstatement",
      "Classify the manipulation using fraud-triangle theory and assess control deficiencies"
    ],
    "PrimaryCompetency": "Judgment",
    "EstimatedMinutes": 30,
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "ScenarioText": "Pinnacle Manufacturing's Division Controller Sam Whitfield discovers that the division president, under pressure to hit quarterly targets, has directed the inventory team to overstate the allowance for obsolescent inventory by $2.3M — effectively inflating operating income by reducing COGS. Sam must apply the IMA ethical decision model, evaluate SOX certification implications, and recommend a resolution path that protects both the company and his professional standing.",
    "Industry": "Industrial manufacturing",
    "CompanyType": "Manufacturer",
    "CompanyName": "Pinnacle Manufacturing",
    "Stakeholder": "Division Controller Sam Whitfield",
    "BusinessFunction": "Financial reporting",
    "QuestionCount": 6,
    "ExhibitCount": 2,
    "ProductionStatus": "Draft",
    "Version": "1.0",
    "Tags": ["IMA standards", "inventory reserves", "fraud triangle", "SOX 302", "ethical resolution"],
    "CreatedDate": "2026-09-04",
    "ModifiedDate": "2026-09-04",
    "Author": "Case Author",
    "Confidence": 90,
    "RevisionHistory": [
      {"Date": "2026-09-04", "Version": "1.0", "Author": "Case Author", "Summary": "Initial creation"}
    ],
    "question_state": "Unprocessed",
    "Part": 2,
    "Part2OnlyFlag": true,
    "LearningObjectives": [
      "Map inventory reserve manipulation to the four IMA ethical standards",
      "Apply the IMA resolution process when the immediate supervisor is involved in misconduct",
      "Identify which parties must be notified under SOX and IMA escalation protocols",
      "Evaluate SOX certification exposure when officers are aware of intentional misstatement",
      "Classify management-directed manipulation using fraud-triangle elements",
      "Map specific scenario facts to ethical standards and fraud indicators"
    ],
    "Exhibits": [
      {
        "ExhibitID": "CBQ22-F4-E1",
        "CaseID": "CBQ22-F4",
        "Type": "table",
        "Title": "Exhibit 1 — Inventory Reserve Analysis",
        "Purpose": "Provides the quantitative evidence of the reserve manipulation showing the gap between supported and recorded allowance levels.",
        "ReferencedBy": ["CBQ22-F4-Q1", "CBQ22-F4-Q3", "CBQ22-F4-Q5"],
        "Headers": ["Reserve Component", "Supportable Amount", "Recorded Amount", "Variance"],
        "Rows": [
          ["Slow-moving raw materials (90+ days)", "$1,200,000", "$1,800,000", "+$600,000"],
          ["Obsolete finished goods (120+ days)", "$2,400,000", "$3,100,000", "+$700,000"],
          ["Excess work-in-process", "$800,000", "$1,400,000", "+$600,000"],
          ["Discontinued product line", "$500,000", "$1,000,000", "+$500,000"],
          ["Total allowance for obsolescence", "$4,900,000", "$7,300,000", "+$2,300,000"],
          ["Impact on COGS (reduction)", "", "$2,300,000", "+$2,300,000"],
          ["Impact on operating income (inflation)", "", "$2,300,000", "+$2,300,000"]
        ],
        "DataFormat": "USD; variance = Recorded minus Supportable; positive variance overstates the reserve",
        "AccuracyCheck": "600K + 700K + 600K + 500K = 2,300K ✓; overstatement reduces COGS by 2,300K, inflating operating income by 2,300K"
      },
      {
        "ExhibitID": "CBQ22-F4-E2",
        "CaseID": "CBQ22-F4",
        "Type": "text",
        "Title": "Exhibit 2 — Division President Email to Inventory Team",
        "Purpose": "Provides direct evidence of management direction to overstate reserves, establishing intent and the ethical violation.",
        "ReferencedBy": ["CBQ22-F4-Q2", "CBQ22-F4-Q4", "CBQ22-F4-Q6"],
        "Body": "From: Division President Mark Caldwell\nTo: Inventory Accounting Team\nSubject: Q3 Reserve Adjustments — Priority\n\nTeam — We need to shore up the Q3 reserve to give us breathing room for Q4. I've asked Sarah to bump the obsolescence numbers to reflect 'worst-case' scenarios on the slow-moving categories. Please process the attached adjustments totaling $2.3M above the controller's recommendation. This is a one-time measure to smooth earnings. Do not copy Sam Whitfield on this email — he'll see the numbers when the package goes to corporate."
      }
    ],
    "Items": [
      {
        "ItemID": "CBQ22-F4-Q1",
        "Type": "select",
        "Prompt": "Which IMA ethical standards are MOST directly violated by directing the inventory team to overstate the obsolescence reserve?",
        "Correct": "C",
        "Choices": [
          "Competence only — the issue is whether the reserve calculation was performed with adequate skill",
          "Confidentiality only — the email instructs team members to withhold information from the controller",
          "Integrity (refraining from activities that discredit the profession) and Credibility (communicating information fairly and disclosing all relevant facts) — with Confidentiality governing HOW Sam escalates, not WHETHER he does",
          "No standards apply until the SEC opens an investigation"
        ],
        "Explanation": "The $2.3M overstatement intentionally misrepresents financial results — Integrity bars participation in activities that discredit the profession, and Credibility requires full and fair disclosure of all material facts. The division president's instruction to 'not copy Sam Whitfield' compounds the violation by attempting to suppress internal oversight. Confidentiality still governs HOW Sam communicates the issue (proper internal channels, not external leaks), but it never excuses participation in a known misstatement. Competence is not the operative failure — the team can compute reserves correctly; the problem is the direction to overstate them.",
        "Topic": "IMA standards mapping",
        "Subtopic": "Integrity and credibility",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["IMA standards", "integrity"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F4-Q2",
        "Type": "select",
        "Prompt": "Under the IMA Statement of Ethical Professional Practice, what is Sam's correct FIRST step after discovering the manipulation?",
        "Correct": "B",
        "Choices": [
          "Confront the division president directly and demand he reverse the entries",
          "Bypass the division president — because the immediate supervisor appears involved, escalate to the next higher level (corporate controller or audit committee) with the Exhibit 1 and 2 evidence",
          "Resign immediately and report to the SEC",
          "Wait for the external auditors to identify the overstatement during year-end fieldwork"
        ],
        "Explanation": "The IMA resolution process starts with the immediate supervisor UNLESS that person appears involved — here the division president authored the directive (Exhibit 2), making direct confrontation both procedurally wrong and practically futile. The correct first step is escalation to the next higher level: corporate controller, CFO, or audit committee. The evidence (Exhibits 1 and 2) should be preserved contemporaneously. Resignation is the LAST resort after all internal channels are exhausted. Waiting for external auditors lets a knowing misstatement stand in interim filings, which compounds Sam's personal SOX exposure.",
        "Topic": "Ethics resolution process",
        "Subtopic": "Escalation sequence",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["escalation", "IMA resolution"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F4-Q3",
        "Type": "multi",
        "Prompt": "Which parties must be notified as part of the ethical resolution process? Select exactly three.",
        "Correct": [
          "The corporate controller or CFO — the next management level above the division president, who has authority to direct reversal of the entries",
          "The audit committee — the board-level body with fiduciary responsibility for financial reporting integrity and the authority to engage forensic investigators if needed",
          "External legal counsel — to clarify Sam's personal SOX certification obligations, whistleblower protection eligibility, and potential mandatory reporting requirements"
        ],
        "Choices": {
          "A": "The corporate controller or CFO — the next management level above the division president, who has authority to direct reversal of the entries",
          "B": "The division president's direct supervisor — the CEO, who approved the earnings target that created the pressure",
          "C": "The audit committee — the board-level body with fiduciary responsibility for financial reporting integrity and the authority to engage forensic investigators if needed",
          "D": "The external auditors — immediately, before any internal investigation, so they can assess the impact on their audit opinion",
          "E": "External legal counsel — to clarify Sam's personal SOX certification obligations, whistleblower protection eligibility, and potential mandatory reporting requirements",
          "F": "The media — to ensure public accountability regardless of internal resolution efforts"
        },
        "Explanation": "The three essential notification parties are: corporate management (A) who can direct the reversal, the audit committee (C) who has board-level oversight authority, and legal counsel (E) who can advise on SOX obligations and whistleblower protections. Option B (CEO) may be appropriate but the CEO is typically briefed through the audit committee or corporate controller path — direct CEO notification without first informing the controller may bypass appropriate governance channels. Option D (external auditors) should be notified but not before internal escalation — the IMA process requires exhausting internal channels before external reporting, and premature auditor notification can compromise the internal investigation. Option F (media) breaches confidentiality and forfeits the protections that orderly internal reporting provides.",
        "Topic": "Notification obligations",
        "Subtopic": "Stakeholder identification",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["notification", "stakeholders"],
        "Dependencies": ["CBQ22-F4-Q2"]
      },
      {
        "ItemID": "CBQ22-F4-Q4",
        "Type": "select",
        "Prompt": "If internal escalation stalls and the division president's directive stands, what is Sam's FINAL recourse under SOX and IMA?",
        "Correct": "A",
        "Choices": [
          "Report in good faith to the SEC or OSHA under SOX §806 whistleblower protections — but only after internal remedies have been genuinely exhausted, and consult counsel first to ensure the report meets the 'reasonable belief' standard",
          "Post the evidence on social media to force public accountability — whistleblower protections cover any disclosure method",
          "Certify the results as instructed and disclose the manipulation anonymously after bonuses are paid",
          "Quietly reverse the entries in the following quarter to avoid conflict, accepting the timing difference"
        ],
        "Explanation": "SOX §806 and Dodd-Frank §922 protect employees who report fraud to federal agencies in good faith and with a reasonable belief — but the protection attaches only after genuine exhaustion of internal channels. Sam must first escalate internally (corporate controller, audit committee, legal counsel), document the refusal to act, and THEN report externally. Option B (social media) is not protected activity under any whistleblower statute — protections require reporting to a federal agency, not the public. Option C (certify-and-disclose-later) is the classic pattern that turns a controller into an enforcement respondent — SOX §302/§906 exposure attaches at certification, not at later disclosure. Option D (quiet reversal) leaves investors misled in the current period and deepens complicity.",
        "Topic": "Final recourse",
        "Subtopic": "Whistleblower protections",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "SOX §806; Dodd-Frank §922",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["whistleblower", "SOX 806"],
        "Dependencies": ["CBQ22-F4-Q3"]
      },
      {
        "ItemID": "CBQ22-F4-Q5",
        "Type": "select",
        "Prompt": "Classify the $2.3M reserve overstatement using fraud-triangle theory. Which element does the division president's conduct BEST satisfy?",
        "Correct": "D",
        "Choices": [
          "Opportunity — the president had access to override the reserve calculation, but pressure and rationalization are not present",
          "Rationalization — the president convinced himself the manipulation was justified, but opportunity and pressure are absent",
          "Financial pressure — the president faced personal financial consequences from missing targets, but opportunity and rationalization are absent",
          "All three elements are present: pressure (quarterly target shortfall), opportunity (ability to direct inventory team to override reserves), and rationalization ('one-time measure to smooth earnings')"
        ],
        "Explanation": "The fraud triangle requires all three elements: PRESSURE — the president is under quarterly-target pressure (Exhibit 2 references 'breathing room for Q4' and 'smooth earnings'); OPPORTUNITY — as division president, he has authority to direct the inventory team and override the controller's recommendation; RATIONALIZATION — the email frames the $2.3M as a 'one-time measure,' a classic minimization rationalization that reframes fraud as temporary smoothing. All three elements are clearly present. The IMA fraud perspective adds that the attempted exclusion of the controller ('Do not copy Sam Whitfield') is itself a red flag indicating awareness that the action violates internal controls.",
        "Topic": "Fraud triangle",
        "Subtopic": "Element classification",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["fraud triangle", "fraud indicators"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F4-Q6",
        "Type": "match",
        "Prompt": "Match each scenario fact from the Pinnacle case to the IMA ethical standard or fraud indicator it most directly implicates.",
        "LeftItems": [
          "Division president directs reserve overstatement of $2.3M above controller's recommendation",
          "Email instructs team not to copy the controller on the adjustment direction",
          "Reserve overstatement reduces COGS and inflates operating income by $2.3M",
          "Email characterizes the manipulation as a 'one-time measure to smooth earnings'"
        ],
        "RightItems": [
          "Integrity — participation in activities that discredit the profession",
          "Confidentiality scope — the exclusion attempts to suppress legitimate internal oversight",
          "Credibility — communicating information that is not fairly presented",
          "Rationalization — minimization of fraudulent activity as temporary or routine",
          "Competence — failure to apply adequate technical skill to the reserve calculation",
          "Opportunity — access to override accounting controls"
        ],
        "Correct": {
          "Division president directs reserve overstatement of $2.3M above controller's recommendation": "Integrity — participation in activities that discredit the profession",
          "Email instructs team not to copy the controller on the adjustment direction": "Confidentiality scope — the exclusion attempts to suppress legitimate internal oversight",
          "Reserve overstatement reduces COGS and inflates operating income by $2.3M": "Credibility — communicating information that is not fairly presented",
          "Email characterizes the manipulation as a 'one-time measure to smooth earnings'": "Rationalization — minimization of fraudulent activity as temporary or routine"
        },
        "Explanation": "Each fact maps to a specific ethical or fraud element: the directive to overstate (first pair) is an Integrity violation — participating in a knowingly misleading accounting treatment discredits the profession. The exclusion of the controller (second pair) goes beyond Confidentiality — it is an attempt to suppress legitimate oversight, which violates the spirit of Confidentiality as a governance safeguard. The financial impact of inflating income by $2.3M (third pair) is a Credibility failure — the resulting financial statements do not fairly present results. The 'one-time measure' framing (fourth pair) is textbook rationalization — minimizing fraud as temporary or routine to reduce psychological discomfort. Distractors: Competence is not the issue (the team can calculate reserves correctly); Opportunity is present but not specifically implicated by the email characterization.",
        "Topic": "Ethics-fraud mapping",
        "Subtopic": "Fact-to-standard classification",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["ethics mapping", "fraud elements"],
        "Dependencies": ["CBQ22-F4-Q1", "CBQ22-F4-Q5"]
      }
    ]
  },
  {
    "CaseID": "CBQ22-F5",
    "Title": "Fraud Investigation at Westfield Logistics",
    "SectionTags": ["F"],
    "BlueprintDomain": "Professional Ethics",
    "BlueprintObjectives": [
      "Identify the fraud triangle elements present in suspicious journal-entry manipulation",
      "Recognize red flags indicating fraudulent financial reporting",
      "Evaluate internal control deficiencies that permitted the fraud",
      "Apply fraud investigation procedures and document findings"
    ],
    "PrimaryCompetency": "Judgment",
    "EstimatedMinutes": 30,
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "ScenarioText": "Westfield Logistics' internal audit team has discovered suspicious journal entries at a subsidiary. The entries appear to shift $1.8M in operating expenses to capital accounts over three months, inflating both operating income and total assets. CFO Diane Foster must apply the fraud triangle, identify red flags, and recommend control responses to the audit committee.",
    "Industry": "Logistics and transportation",
    "CompanyType": "Service provider",
    "CompanyName": "Westfield Logistics",
    "Stakeholder": "CFO Diane Foster",
    "BusinessFunction": "Internal audit",
    "QuestionCount": 6,
    "ExhibitCount": 2,
    "ProductionStatus": "Draft",
    "Version": "1.0",
    "Tags": ["fraud triangle", "journal entries", "internal controls", "fraud investigation", "capitalization"],
    "CreatedDate": "2026-09-04",
    "ModifiedDate": "2026-09-04",
    "Author": "Case Author",
    "Confidence": 90,
    "RevisionHistory": [
      {"Date": "2026-09-04", "Version": "1.0", "Author": "Case Author", "Summary": "Initial creation"}
    ],
    "question_state": "Unprocessed",
    "Part": 2,
    "Part2OnlyFlag": true,
    "LearningObjectives": [
      "Classify journal-entry fraud using the fraud triangle framework",
      "Identify specific red flags in suspicious journal-entry patterns",
      "Evaluate control deficiencies that permitted unauthorized capitalization",
      "Select appropriate investigation steps following fraud discovery",
      "Map evidence to specific fraud-triangle elements",
      "Recommend control responses proportional to the identified fraud risk"
    ],
    "Exhibits": [
      {
        "ExhibitID": "CBQ22-F5-E1",
        "CaseID": "CBQ22-F5",
        "Type": "erp-report",
        "Title": "Exhibit 1 — Suspicious Journal Entries (Subsidiary GL)",
        "Purpose": "Provides the specific journal entries that shifted operating expenses to capital accounts, establishing the mechanics and pattern of the fraud.",
        "ReferencedBy": ["CBQ22-F5-Q1", "CBQ22-F5-Q2", "CBQ22-F5-Q4", "CBQ22-F5-Q6"],
        "Headers": ["Date", "Entry #", "Debit Account", "Credit Account", "Amount", "Prepared By", "Approved By"],
        "Rows": [
          ["2026-04-15", "JE-4201", "Vehicles and Equipment (1500)", "Repair and Maintenance Expense (6100)", "$420,000", "J. Marcus", "None"],
          ["2026-04-28", "JE-4217", "Vehicles and Equipment (1500)", "Freight Expense (6200)", "$380,000", "J. Marcus", "None"],
          ["2026-05-12", "JE-4302", "Buildings and Improvements (1400)", "Warehouse Labor Expense (6300)", "$510,000", "J. Marcus", "None"],
          ["2026-05-30", "JE-4318", "Vehicles and Equipment (1500)", "Insurance Expense (6400)", "$290,000", "J. Marcus", "None"],
          ["2026-06-14", "JE-4405", "Buildings and Improvements (1400)", "Utilities Expense (6500)", "$200,000", "J. Marcus", "None"],
          ["Total", "", "", "", "$1,800,000", "", ""]
        ],
        "DataFormat": "USD; all entries debit asset accounts and credit expense accounts; no approval signatures recorded",
        "AccuracyCheck": "420K + 380K + 510K + 290K + 200K = 1,800K ✓"
      },
      {
        "ExhibitID": "CBQ22-F5-E2",
        "CaseID": "CBQ22-F5",
        "Type": "text",
        "Title": "Exhibit 2 — Internal Audit Investigation Notes",
        "Purpose": "Provides the investigative context and background findings that supplement the journal-entry evidence.",
        "ReferencedBy": ["CBQ22-F5-Q3", "CBQ22-F5-Q5", "CBQ22-F5-Q6"],
        "Body": "Investigation Notes — Westfield Logistics Subsidiary\n\nDate: June 28, 2026\nAuditor: Lead Internal Auditor Rebecca Torres\n\n1. All five entries were prepared by J. Marcus, a senior accountant in the subsidiary's finance department.\n2. None of the entries carry a supervisor approval signature, despite the subsidiary's written policy requiring dual approval for any journal entry exceeding $50,000.\n3. J. Marcus reports to the subsidiary CFO, who also serves as the subsidiary's controller — a combined role that eliminates the segregation of duties required by Westfield's corporate internal control manual.\n4. The capital account additions ($1.8M total) were not supported by any purchase orders, vendor invoices, or asset receiving reports.\n5. J. Marcus resigned on June 25, 2026, one week before the audit team's scheduled fieldwork.\n6. The subsidiary CFO approved all entries verbally but did not sign the approval field.\n7. Westfield's corporate ERP system has a configuration flag that allows subsidiary-level overrides of the capitalization threshold — this flag was activated on March 30, 2026, by the subsidiary CFO."
      }
    ],
    "Items": [
      {
        "ItemID": "CBQ22-F5-Q1",
        "Type": "select",
        "Prompt": "Which element of the fraud triangle is MOST directly evidenced by the journal entries shifting expenses to capital accounts?",
        "Correct": "C",
        "Choices": [
          "Pressure — the subsidiary CFO faced quarterly earnings targets, but the entries themselves do not prove pressure",
          "Rationalization — the accountant convinced himself the entries were justified, but the pattern suggests deliberate concealment rather than self-justification",
          "Opportunity — the combined CFO/Controller role, lack of approval signatures, and ERP override flag created the conditions that permitted the fraud to occur and persist undetected",
          "All three elements are equally and directly evidenced by the journal entries alone"
        ],
        "Explanation": "The journal entries themselves most directly evidence OPPORTUNITY: five entries totaling $1.8M were processed without approval signatures (violating the $50K dual-approval policy), by a single preparer, in a subsidiary where the CFO and Controller roles are combined (eliminating segregation of duties), using an ERP override that was activated specifically to enable the capitalization. Pressure and rationalization are inferred from context (earnings targets, the 'verbal approval' pattern) but the ENTRIES specifically demonstrate the control failures that made the fraud possible. The fraud triangle is a framework — each element requires independent evidence, and the journal-entry pattern is the opportunity evidence.",
        "Topic": "Fraud triangle",
        "Subtopic": "Element identification",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["fraud triangle", "opportunity"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F5-Q2",
        "Type": "select",
        "Prompt": "Which red flag pattern in Exhibit 1 is MOST characteristic of fraudulent journal entries?",
        "Correct": "A",
        "Choices": [
          "All entries debit capital accounts and credit expense accounts with no supporting documentation, no supervisor signatures, and amounts just below or at unusual thresholds",
          "The entries were prepared on business days during normal working hours",
          "The amounts are round numbers — $420,000, $380,000, $510,000, $290,000, $200,000",
          "The entries were posted to the general ledger rather than subsidiary ledgers"
        ],
        "Explanation": "The hallmarks of fraudulent journal entries are: (1) consistent direction — all five entries shift expenses TO assets, never the reverse; (2) no supporting documentation — no POs, invoices, or receiving reports exist; (3) no approval signatures — all five violate the $50K dual-approval policy; and (4) the aggregate amount ($1.8M) is material. Round numbers (C) are a weak indicator — legitimate capitalizations can also be round. Business-day timing (B) is neutral. General-ledger posting (D) is normal for adjusting entries. The directional consistency and absence of documentation are the strong red flags that internal audit standards (IIA) and SAS 99 identify as fraud indicators.",
        "Topic": "Red flags",
        "Subtopic": "Journal entry fraud indicators",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["red flags", "journal entries"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F5-Q3",
        "Type": "select",
        "Prompt": "Which internal control deficiency MOST directly enabled the fraud to persist undetected?",
        "Correct": "D",
        "Choices": [
          "Failure to perform bank reconciliations monthly — but the fraud involved GL entries, not bank transactions",
          "Lack of a formal code of ethics — but Westfield has a corporate internal control manual with segregation-of-duties requirements",
          "Insufficient IT security training for end users — but the ERP override was performed by the CFO, not a rank-and-file user",
          "Combined CFO/Controller role at the subsidiary eliminating segregation of duties, combined with an activated ERP override that bypassed the capitalization threshold"
        ],
        "Explanation": "The combined CFO/Controller role is the structural enabler: one person both authorizes AND records transactions, eliminating the segregation that would normally require a second independent party to detect or prevent the misclassification. The activated ERP override (flag turned on March 30, 2026) allowed capitalization entries that should have been blocked by system-level controls. Together these create the classic fraud-enabling condition: no independent check on the person with both motive (quarterly targets) and access (combined role + ERP override). Bank reconciliations (A) test cash, not GL classification. A code of ethics (B) addresses culture, not structural controls. IT training (C) addresses user competence, not management override.",
        "Topic": "Control deficiency",
        "Subtopic": "Segregation of duties",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["internal controls", "SoD"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F5-Q4",
        "Type": "multi",
        "Prompt": "Which three investigation steps should Diane Foster recommend to the audit committee? Select exactly three.",
        "Correct": [
          "Engage forensic accounting specialists to trace the $1.8M through the capital accounts and determine whether any assets were actually acquired or if the entries are pure misclassification",
          "Preserve all electronic evidence — ERP audit logs, email accounts, and system access records for J. Marcus and the subsidiary CFO — before the 30-day retention window expires",
          "Review the ERP override configuration and determine whether similar overrides exist at other subsidiaries, assessing whether the control gap is systemic or isolated"
        ],
        "Choices": {
          "A": "Engage forensic accounting specialists to trace the $1.8M through the capital accounts and determine whether any assets were actually acquired or if the entries are pure misclassification",
          "B": "Confront J. Marcus directly, even though he has resigned, to obtain his explanation before the audit committee reviews the findings",
          "C": "Preserve all electronic evidence — ERP audit logs, email accounts, and system access records for J. Marcus and the subsidiary CFO — before the 30-day retention window expires",
          "D": "Reverse all five entries immediately to restore the correct account balances before the external audit begins",
          "E": "Review the ERP override configuration and determine whether similar overrides exist at other subsidiaries, assessing whether the control gap is systemic or isolated",
          "F": "Terminate the subsidiary CFO immediately to prevent evidence destruction, without first completing the forensic investigation"
        },
        "Explanation": "The three essential investigation steps are: forensic tracing (A) to determine the economic substance of the entries, evidence preservation (C) to maintain the audit trail before retention windows expire, and systemic review (E) to determine whether the ERP override gap affects other subsidiaries. Option B (confronting J. Marcus) is impractical — he resigned and has no obligation to cooperate; legal counsel should advise on subpoena options if his testimony is needed. Option D (immediate reversal) is premature — the entries must be forensically understood before reversal to avoid destroying evidence or creating new accounting issues. Option F (immediate termination) is disproportionate before the investigation completes — the CFO should be placed on administrative leave with system access revoked, not terminated, to preserve the ability to compel cooperation through employment obligations.",
        "Topic": "Investigation procedures",
        "Subtopic": "Forensic investigation steps",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["investigation", "forensic"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F5-Q5",
        "Type": "select",
        "Prompt": "The investigation notes describe J. Marcus's resignation one week before scheduled fieldwork. Which fraud-triangle element does this timing MOST directly suggest?",
        "Correct": "B",
        "Choices": [
          "Opportunity — the resignation created the opportunity for the fraud to continue without detection",
          "Consciousness of guilt — the resignation timing suggests Marcus knew the fraud would be discovered and fled before the audit, indicating awareness that the entries were improper",
          "Rationalization — the resignation was a personal choice unrelated to the fraud",
          "Pressure — Marcus was pressured to resign by the subsidiary CFO"
        ],
        "Explanation": "Resignation immediately before scheduled audit fieldwork is a classic consciousness-of-guilt indicator — it suggests the individual knew the fraud would be discovered and chose to depart before investigators could question them. While the resignation does not PROVE guilt (it could be coincidental), the timing pattern is specifically identified in fraud investigation standards (SAS 99, IIA Practice Advisory) as a red flag requiring investigation. The three-week gap between the last fraudulent entry (June 14) and resignation (June 25) further suggests Marcus completed the scheme and then departed. Option A misreads the framework — resignation does not create opportunity; it is a response to perceived detection risk. Option C (rationalization) applies to the fraud itself, not the resignation. Option D (pressure to resign) is unsupported by the evidence.",
        "Topic": "Fraud indicators",
        "Subtopic": "Consciousness of guilt",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["fraud indicators", "resignation"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F5-Q6",
        "Type": "match",
        "Prompt": "Match each piece of evidence from the Westfield investigation to the fraud-triangle element or control principle it most directly supports.",
        "LeftItems": [
          "Five entries debiting capital accounts and crediting expense accounts totaling $1.8M",
          "No supervisor approval signatures on any entry despite $50K dual-approval policy",
          "Subsidiary CFO and Controller roles combined in one person",
          "ERP capitalization-override flag activated March 30, 2026 by the subsidiary CFO"
        ],
        "RightItems": [
          "Opportunity — management override of capitalization controls",
          "Opportunity — segregation-of-duties failure",
          "Pressure — the direction of entries (expense-to-asset) indicates earnings manipulation motive",
          "Opportunity — bypass of system-level authorization controls",
          "Rationalization — the entries were intended to be reversed later",
          "Pressure — quarterly earnings targets created the motivation"
        ],
        "Correct": {
          "Five entries debiting capital accounts and crediting expense accounts totaling $1.8M": "Pressure — the direction of entries (expense-to-asset) indicates earnings manipulation motive",
          "No supervisor approval signatures on any entry despite $50K dual-approval policy": "Opportunity — management override of capitalization controls",
          "Subsidiary CFO and Controller roles combined in one person": "Opportunity — segregation-of-duties failure",
          "ERP capitalization-override flag activated March 30, 2026 by the subsidiary CFO": "Opportunity — bypass of system-level authorization controls"
        },
        "Explanation": "The evidence maps as follows: the consistent expense-to-asset direction (first pair) indicates PRESSURE — the motive is earnings inflation, not random error. The missing approval signatures (second pair) demonstrate OPPORTUNITY through management override of authorization controls. The combined CFO/Controller role (third pair) is OPPORTUNITY through segregation-of-duties failure — one person both authorizes and records. The ERP override activation (fourth pair) is OPPORTUNITY through system-level control bypass. Note that three of the four evidence items map to Opportunity — this is characteristic of management-override fraud, where the perpetrator's position creates multiple overlapping control gaps. The pressure element is inferred from the entry direction, not from a single piece of documentary evidence.",
        "Topic": "Evidence classification",
        "Subtopic": "Fraud-triangle mapping",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["evidence mapping", "fraud triangle"],
        "Dependencies": ["CBQ22-F5-Q1", "CBQ22-F5-Q3"]
      }
    ]
  },
  {
    "CaseID": "CBQ22-F6",
    "Title": "SOX Compliance and Whistleblower Retaliation at Nexus Industries",
    "SectionTags": ["F"],
    "BlueprintDomain": "Professional Ethics",
    "BlueprintObjectives": [
      "Identify SOX provisions applicable to earnings restatement and whistleblower retaliation",
      "Evaluate audit committee responsibilities under SOX and stock exchange listing standards",
      "Assess whistleblower protections under SOX §806 and Dodd-Frank §922",
      "Recommend governance actions proportional to the identified compliance failures"
    ],
    "PrimaryCompetency": "Judgment",
    "EstimatedMinutes": 30,
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "ScenarioText": "Nexus Industries' audit committee must respond after a whistleblower alleges that management retaliated against the employee for reporting revenue-timing irregularities. The company recently restated Q2 earnings. The audit committee chair, Patricia Voss, must evaluate SOX 302/404/806 exposure, assess Dodd-Frank whistleblower protections, and recommend next steps to the full board.",
    "Industry": "Technology manufacturing",
    "CompanyType": "Manufacturer",
    "CompanyName": "Nexus Industries",
    "Stakeholder": "Audit Committee Chair Patricia Voss",
    "BusinessFunction": "Corporate governance",
    "QuestionCount": 6,
    "ExhibitCount": 2,
    "ProductionStatus": "Draft",
    "Version": "1.0",
    "Tags": ["SOX", "whistleblower", "audit committee", "restatement", "Dodd-Frank", "retaliation"],
    "CreatedDate": "2026-09-04",
    "ModifiedDate": "2026-09-04",
    "Author": "Case Author",
    "Confidence": 90,
    "RevisionHistory": [
      {"Date": "2026-09-04", "Version": "1.0", "Author": "Case Author", "Summary": "Initial creation"}
    ],
    "question_state": "Unprocessed",
    "Part": 2,
    "Part2OnlyFlag": true,
    "LearningObjectives": [
      "Identify which SOX sections apply to earnings restatement, internal control failure, and whistleblower retaliation",
      "Evaluate the audit committee's specific responsibilities under SOX and listing standards",
      "Assess the scope of whistleblower protections under SOX §806 and Dodd-Frank",
      "Apply the legal test for retaliation to the facts presented",
      "Recommend governance actions that address both the restatement and the retaliation"
    ],
    "Exhibits": [
      {
        "ExhibitID": "CBQ22-F6-E1",
        "CaseID": "CBQ22-F6",
        "Type": "text",
        "Title": "Exhibit 1 — Q2 Restatement Memo",
        "Purpose": "Provides the factual basis for the earnings restatement, establishing the scope and materiality of the original misstatement.",
        "ReferencedBy": ["CBQ22-F6-Q1", "CBQ22-F6-Q3", "CBQ22-F6-Q6"],
        "Body": "MEMORANDUM — Nexus Industries Q2 Earnings Restatement\n\nDate: August 12, 2026\nFrom: Office of the General Counsel\nTo: Audit Committee\n\nSummary: Management has determined that Q2 revenue was overstated by $4.2M (2.8% of reported revenue) due to premature recognition of three channel-partner shipments that had not met ASC 606 transfer-of-control criteria at the recording date. The shipments were invoiced on June 28 (last day of Q2) but customer acceptance occurred in July.\n\nImpact: Q2 revenue reduced from $150.0M to $145.8M; Q2 operating income reduced from $22.5M to $18.3M; Q2 net income reduced from $16.9M to $13.7M (after 25% tax). The restatement was initiated after employee 'A.M.' reported the timing irregularity to the CFO on July 8.\n\nRestatement process: Q2 10-Q will be amended; prior-period comparatives will not be affected. External auditors have been notified and concur with the adjustment. Management's assessment of internal controls over financial reporting (SOX §404) identified the revenue-recognition override as a material weakness."
      },
      {
        "ExhibitID": "CBQ22-F6-E2",
        "CaseID": "CBQ22-F6",
        "Type": "email",
        "Title": "Exhibit 2 — Whistleblower Retaliation Complaint",
        "Purpose": "Provides the whistleblower's account of retaliation, establishing the factual basis for SOX §806 and Dodd-Frank analysis.",
        "ReferencedBy": ["CBQ22-F6-Q2", "CBQ22-F6-Q4", "CBQ22-F6-Q5"],
        "Body": "From: A.M. (Employee, Revenue Accounting)\nTo: Audit Committee Chair Patricia Voss\nSubject: Retaliation Complaint — Confidential\n\nDear Ms. Voss,\n\nI am writing to report that I have been subjected to retaliation after reporting revenue-timing irregularities to the CFO on July 8, 2026.\n\nTimeline of events:\n- July 8: I reported to CFO Daniel Reeves that three June 28 shipments were recorded as Q2 revenue despite customer acceptance not occurring until July. I provided emails and shipping documents.\n- July 12: My manager, VP of Revenue Sarah Kim, informed me I was being 'reassigned' from the Q3 audit-preparation team, citing 'restructuring.'\n- July 19: My system access to the revenue subledger was revoked — the same access I need to perform my job functions.\n- July 26: I received a performance improvement plan (PIP) citing 'incomplete work product' — the same work product I was blocked from accessing.\n\nI believe these actions constitute retaliation for my good-faith report of accounting irregularities. I request protection under SOX §806 and any other applicable whistleblower statutes.\n\nSincerely,\nA.M."
      }
    ],
    "Items": [
      {
        "ItemID": "CBQ22-F6-Q1",
        "Type": "select",
        "Prompt": "Which SOX section MOST directly addresses the CEO and CFO's personal certification obligations related to the Q2 restatement?",
        "Correct": "C",
        "Choices": [
          "SOX §404 — requires management assessment of internal controls, but does not create personal officer certification liability for the financial statements themselves",
          "SOX §806 — addresses whistleblower protections, not officer certification obligations",
          "SOX §302 — requires the CEO and CFO to personally certify that financial statements fairly present results and that disclosure controls are effective; §906 adds criminal penalties for knowing false certifications",
          "SOX §201 — restricts auditor services, which is irrelevant to officer certification"
        ],
        "Explanation": "SOX §302 requires the principal officers (CEO and CFO) to personally certify both that the financial statements fairly present the company's financial condition AND that disclosure controls and procedures are effective. When a restatement reveals that the originally certified statements were materially misstated, the officers' personal exposure under §302 is immediate — they certified statements they knew or should have known were inaccurate. Section §906 layers criminal penalties (up to $5M fine and 20 years imprisonment) for WILLFUL false certifications. Section 404 addresses internal controls but creates the separate material-weakness disclosure, not officer personal liability for statement accuracy. Section 806 addresses whistleblower protections. Section 201 restricts auditor services.",
        "Topic": "SOX certification",
        "Subtopic": "Officer obligations",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": false,
        "FormulaReference": "SOX §302; §906",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["SOX 302", "officer certification"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F6-Q2",
        "Type": "select",
        "Prompt": "What is the audit committee's PRIMARY responsibility regarding the whistleblower retaliation allegation?",
        "Correct": "A",
        "Choices": [
          "Independently investigate the retaliation claim — the audit committee must ensure the investigation is conducted by qualified personnel (internal audit, external counsel, or forensic specialists) who report directly to the committee, not to management",
          "Refer the complaint to HR for standard employee-relations processing — retaliation allegations follow the same procedure as any other workplace complaint",
          "Defer to management's explanation that the reassignment and PIP were legitimate business decisions unrelated to the July 8 report",
          "Notify the SEC immediately before completing any internal investigation"
        ],
        "Explanation": "The audit committee's responsibility under SOX §301 and NYSE/NASDAQ listing standards is to oversee the investigation of accounting and auditing matters, including whistleblower complaints. The committee must ensure the investigation is independent of management — meaning it is conducted by or reports directly to the committee, not through the management chain that is the subject of the complaint. HR processing (B) is insufficient because the complaint involves potential management misconduct. Deferring to management's explanation (C) compromises independence. SEC notification (D) is premature before the investigation establishes facts — premature external reporting can damage the company without establishing whether retaliation occurred.",
        "Topic": "Audit committee responsibility",
        "Subtopic": "Independent investigation",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": false,
        "FormulaReference": "SOX §301",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["audit committee", "investigation"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F6-Q3",
        "Type": "multi",
        "Prompt": "Which three protections or provisions apply to employee A.M.? Select exactly three.",
        "Correct": [
          "SOX §806 — protects employees of publicly traded companies who report fraud to federal agencies, Congress, or internally, from retaliation including demotion, suspension, and harassment",
          "Dodd-Frank §922 — extends whistleblower protections to include a private right of action for retaliation and provides for double back pay plus litigation costs",
          "Company non-retaliation policy — Nexus's own code of conduct prohibits retaliation against good-faith reporters, providing an additional contractual remedy independent of federal statute"
        ],
        "Choices": {
          "A": "SOX §806 — protects employees of publicly traded companies who report fraud to federal agencies, Congress, or internally, from retaliation including demotion, suspension, and harassment",
          "B": "Dodd-Frank §922 — extends whistleblower protections to include a private right of action for retaliation and provides for double back pay plus litigation costs",
          "C": "Sarbanes-Oxley §404 — provides whistleblower protection through the internal control assessment process",
          "D": "Company non-retaliation policy — Nexus's own code of conduct prohibits retaliation against good-faith reporters, providing an additional contractual remedy independent of federal statute",
          "E": "SEC Rule 21F — provides financial awards to whistleblowers, which protects A.M. by incentivizing the report",
          "F": "OSHA whistleblower protection program — OSHA administers SOX §806 claims but does not provide an independent substantive protection"
        },
        "Explanation": "The three applicable protections are: SOX §806 (A) which specifically protects employees of publicly traded companies from retaliation for reporting fraud; Dodd-Frank §922 (B) which strengthens those protections with a private right of action and double back pay; and the company's own non-retaliation policy (D) which provides contractual remedies independent of federal law. Section 404 (C) addresses internal controls, not whistleblower protection — it is the internal-control assessment process, not a protection statute. Rule 21F (E) provides financial incentives for SEC whistleblower tips but does not itself provide retaliation protection — that comes from §806 and Dodd-Frank. OSHA (F) administers §806 claims but is the procedural mechanism, not an independent substantive protection.",
        "Topic": "Whistleblower protections",
        "Subtopic": "Applicable statutes",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "SOX §806; Dodd-Frank §922",
        "EstimatedMinutes": 6,
        "ExplanationVersion": 1,
        "Tags": ["whistleblower", "protections"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F6-Q4",
        "Type": "select",
        "Prompt": "Applying the legal test for retaliation, which facts from A.M.'s complaint would MOST strongly support a retaliation claim?",
        "Correct": "B",
        "Choices": [
          "A.M. received a performance improvement plan citing incomplete work product — PIPs are routine management tools and do not alone indicate retaliation",
          "System access to the revenue subledger was revoked within 11 days of the report, directly blocking A.M. from performing the very job function related to the irregularity reported — the temporal proximity and functional connection create strong circumstantial evidence of retaliatory motive",
          "A.M. was reassigned from the Q3 audit-preparation team — reassignment is a legitimate business decision that does not require justification",
          "A.M. reported to the CFO rather than the audit committee — the reporting channel affects protection eligibility, not the retaliation analysis"
        ],
        "Explanation": "The strongest retaliation evidence is the SYSTEM ACCESS REVOCATION: it occurred 11 days after the report, directly targeted the specific function (revenue subledger access) related to A.M.'s disclosure, and made it impossible for A.M. to perform the job for which the subsequent PIP cited 'incomplete work product.' This creates a causal chain: report → access revoked → unable to work → PIP issued. The temporal proximity (11 days) plus the functional connection (access to the exact system A.M. flagged) satisfies both prongs of the retaliation test: (1) protected activity (the report) and (2) adverse action causally connected to it. The PIP (A) alone is weak — PIPs are common. Reassignment (C) alone is weak — legitimate restructuring occurs. The reporting channel (D) affects whether A.M. qualifies for protection, not whether retaliation occurred.",
        "Topic": "Retaliation test",
        "Subtopic": "Causal connection",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Analyze",
        "CalculationRequired": false,
        "FormulaReference": "SOX §806; Dodd-Frank §922",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["retaliation", "causation"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F6-Q5",
        "Type": "select",
        "Prompt": "Under Dodd-Frank §922, what remedies are available to A.M. if retaliation is proven?",
        "Correct": "B",
        "Choices": [
          "Reinstatement with seniority plus single back pay — Dodd-Frank mirrors SOX §806 remedies exactly",
          "Reinstatement with seniority plus DOUBLE back pay, plus compensation for litigation costs including expert witness fees — Dodd-Frank strengthens SOX §806 remedies",
          "Monetary damages capped at the employee's annual salary — Dodd-Frank limits recovery to actual losses",
          "Criminal penalties against the retaliator — Dodd-Frank provides for imprisonment of managers who retaliate"
        ],
        "Explanation": "Dodd-Frank §922 significantly strengthens whistleblower remedies beyond SOX §806: it provides for REINSTATEMENT with full seniority PLUS DOUBLE back pay (not single back pay as under §806), plus compensation for litigation costs including expert witness fees and attorney fees. The double-back-pay remedy is a key distinction from SOX §806 — it creates a financial incentive for whistleblowers to pursue claims and a financial deterrent against retaliation. Option A understates the remedy (single back pay). Option C is incorrect — there is no cap on recovery. Option D is incorrect — Dodd-Frank does not provide criminal penalties for retaliation; criminal penalties apply to the underlying fraud, not the retaliatory act itself.",
        "Topic": "Dodd-Frank remedies",
        "Subtopic": "Whistleblower compensation",
        "Difficulty": "Moderate",
        "DifficultyScore": 3,
        "CognitiveLevel": "Apply",
        "CalculationRequired": false,
        "FormulaReference": "Dodd-Frank §922",
        "EstimatedMinutes": 5,
        "ExplanationVersion": 1,
        "Tags": ["Dodd-Frank", "remedies"],
        "Dependencies": []
      },
      {
        "ItemID": "CBQ22-F6-Q6",
        "Type": "select",
        "Prompt": "Which governance recommendation best addresses BOTH the restatement and the retaliation issues?",
        "Correct": "A",
        "Choices": [
          "Engage independent forensic counsel to investigate the retaliation claim, direct management to reverse the Q2 entries and file an amended 10-Q, require the CEO and CFO to re-certify under §302/§906, and restore A.M.'s system access and team assignment pending the investigation outcome",
          "Accept management's characterization that the reassignment was legitimate restructuring and focus solely on the Q2 restatement, since the retaliation complaint is an HR matter separate from financial reporting",
          "Terminate A.M. for breach of confidentiality — reporting to the audit committee before completing internal channels violates the company's chain-of-command policy",
          "Delay the restatement filing until the retaliation investigation is complete, since the two issues are interrelated and should be resolved simultaneously"
        ],
        "Explanation": "Option A addresses both issues comprehensively: independent forensic counsel ensures the retaliation investigation is credible and committee-overseen; the restatement corrects the financial misstatement; re-certification resets the officers' personal liability clock; and restoring A.M.'s access and assignment prevents further retaliation pending investigation while preserving the evidence chain. Option B incorrectly separates the issues — the retaliation arose FROM the restatement, making them inseparable. Option C (terminating A.M.) would compound the retaliation and expose Nexus to doubling damages under Dodd-Frank §922. Option D (delaying the restatement) violates the company's filing obligations — the restatement must be filed promptly regardless of parallel investigations; delaying could itself become a separate disclosure violation.",
        "Topic": "Governance recommendation",
        "Subtopic": "Integrated response",
        "Difficulty": "Difficult",
        "DifficultyScore": 4,
        "CognitiveLevel": "Evaluate",
        "CalculationRequired": false,
        "FormulaReference": "SOX §302; §806; Dodd-Frank §922",
        "EstimatedMinutes": 6,
        "ExplanationVersion": 1,
        "Tags": ["governance", "recommendation"],
        "Dependencies": ["CBQ22-F6-Q3", "CBQ22-F6-Q4", "CBQ22-F6-Q5"]
      }
    ]
  }
];
