var pack_p2_c_questions = [
  {
    "Part": 2,
    "Section": "C",
    "Topic": "C.001 CVP breakeven analysis in units",
    "QuestionID": "P2-C-001",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-001-cvp-breakeven-analysis-in-units",
    "Stem": "Atlas Manufacturing produces a single product line. The selling price is $200 per unit, variable manufacturing costs are $120 per unit, and variable selling costs are $5 per unit. Total annual fixed manufacturing and administrative costs are $450,000. The controller is preparing the annual operating plan and needs to determine the breakeven point.",
    "Choices": {
      "A": "2,250 units",
      "B": "6,000 units",
      "C": "3,600 units",
      "D": "3,000 units"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Under relevant costing principles and CVP analysis, the breakeven point in units is computed by dividing total fixed costs by the contribution margin per unit. The contribution margin per unit equals the selling price minus all variable costs: $200 − ($120 + $5) = $75 per unit. Breakeven units = Fixed Costs ÷ CM per Unit = $450,000 ÷ $75 = 6,000 units. This means Atlas Manufacturing must sell 6,000 units to cover all fixed and variable costs, after which every additional unit sold contributes $75 toward operating profit. A common error is treating revenue per unit or variable cost per unit as the contribution margin, which yields materially different breakeven calculations.",
    "ExplanationWrongA": "2,250 units results from dividing fixed costs by the selling price: $450,000 ÷ $200 = 2,250. This error treats the selling price as if it were the contribution margin, ignoring all variable costs. The selling price must first be reduced by variable costs to determine the true margin per unit available to cover fixed costs. A candidate making this error is confusing total revenue per unit with the incremental contribution each unit provides toward fixed costs and profit.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "3,600 units results from dividing fixed costs by the variable cost per unit: $450,000 ÷ $125 = 3,600. This error uses variable cost as the divisor instead of the contribution margin. A candidate making this error may be confusing the cost structure — variable cost represents the outflow per unit, not the margin available to cover fixed costs. The contribution margin ($75) is the correct measure because it represents what remains from each sale after covering all variable costs.",
    "ExplanationWrongD": "3,000 units results from dividing fixed costs by an overstated contribution margin. Using only variable manufacturing costs as the deduction ($200 − $120 = $80 per unit CM) and ignoring variable selling costs yields $450,000 ÷ $80 = 5,625, not 3,000. The result of 3,000 arises if a candidate divides fixed costs by $150 ($450,000 ÷ $150 = 3,000), which occurs when only variable selling costs are deducted ($200 − $5 = $195 = still not $150). More likely, a candidate using this approach has incorrectly computed CM as $200 − ($120 + $5) incorrectly or used an arbitrary CM value. The correct CM is $75 per unit.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-01: Breakeven (units) = Fixed Costs / CM per Unit",
    "CommonTrapReference": "T7: Using average instead of incremental cost — confusing selling price or variable cost per unit with the contribution margin",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: CM = $200−($120+$5)=$75; BE = $450,000/$75 = 6,000",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.002 CVP breakeven analysis in dollars",
    "QuestionID": "P2-C-002",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-002-cvp-breakeven-analysis-in-dollars",
    "Stem": "Pine Ridge Components sells industrial fasteners at an average selling price of $25 per unit. Variable costs are $15 per unit. Total annual fixed costs are $500,000. The CFO wants to know the breakeven point in sales dollars for the upcoming budget presentation.",
    "Choices": {
      "A": "$1,250,000",
      "B": "$833,333",
      "C": "$500,000",
      "D": "$2,000,000"
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Under CVP analysis, the breakeven point in sales dollars is computed by dividing total fixed costs by the contribution margin ratio. The CM ratio = CM per Unit ÷ Selling Price = ($25 − $15) ÷ $25 = $10 ÷ $25 = 0.40 (40%). Breakeven sales dollars = Fixed Costs ÷ CM Ratio = $500,000 ÷ 0.40 = $1,250,000. This means Pine Ridge Components must generate $1,250,000 in sales revenue to cover all costs. A common error is confusing the CM ratio with the gross margin ratio or the variable cost ratio — only the CM ratio reflects the portion of each sales dollar available to cover fixed costs and contribute to profit.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$833,333 results from using the variable cost ratio (60%) instead of the CM ratio: $500,000 ÷ 0.60 = $833,333. A candidate making this error is dividing fixed costs by the proportion of each sales dollar consumed by variable costs rather than by the proportion that contributes to covering fixed costs. The variable cost ratio measures costs, not margin — the CM ratio (40%) is the correct divisor.",
    "ExplanationWrongC": "$500,000 results from equating breakeven sales dollars to total fixed costs without applying any ratio. This error treats fixed costs as though they equal the required revenue, ignoring that variable costs must also be covered. Each sales dollar must cover its share of variable costs before contributing to fixed costs, requiring total revenue significantly above the fixed cost amount.",
    "ExplanationWrongD": "$2,000,000 results from computing the breakeven in units first (500,000 ÷ 10 = 50,000 units) and then multiplying by selling price incorrectly, or using a markup-based approach rather than the CM ratio. A candidate making this error may have used $25 × 80,000 units or an inverted ratio. The correct approach is $500,000 ÷ 0.40 = $1,250,000.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-02: Breakeven (dollars) = Fixed Costs / CM Ratio",
    "CommonTrapReference": "Confusing CM ratio with variable cost ratio — using 60% instead of 40%",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: CM = $10, CM Ratio = $10/$25 = 0.40, BE = $500,000/0.40 = $1,250,000",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.003 CVP target profit analysis in units",
    "QuestionID": "P2-C-003",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-003-cvp-target-profit-analysis-in-units",
    "Stem": "Meridian Equipment manufactures a specialized valve used in industrial pumps. The selling price is $350 per unit, variable costs are $210 per unit, and total annual fixed costs are $560,000. Management has set a target operating profit of $280,000 for the upcoming year. The controller needs to determine how many units must be sold to achieve this target.",
    "Choices": {
      "A": "4,000 units",
      "B": "2,400 units",
      "C": "2,000 units",
      "D": "6,000 units"
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Under CVP analysis, the unit sales required to achieve a target operating profit are computed by adding the target profit to fixed costs, then dividing by the contribution margin per unit. CM per unit = $350 − $210 = $140. Required units = (Fixed Costs + Target Profit) ÷ CM per Unit = ($560,000 + $280,000) ÷ $140 = $840,000 ÷ $140 = 6,000 units. Meridian Equipment must sell 6,000 valves to generate $280,000 in operating profit. A common error is forgetting to add target profit to fixed costs in the numerator, which yields only the breakeven quantity of 4,000 units rather than the target-profit quantity.",
    "ExplanationWrongA": "4,000 units is the breakeven quantity: $560,000 ÷ $140 = 4,000 units. This answer addresses the question of how many units must be sold to break even, not to achieve the target profit of $280,000. A candidate selecting this option has correctly identified the contribution margin but omitted the target profit from the numerator. The target profit must be added to fixed costs before dividing by the contribution margin per unit.",
    "ExplanationWrongB": "2,400 units results from dividing only the target profit by an overstated contribution margin, or from a computational error combining fixed costs and target profit incorrectly. If a candidate divides (Fixed Costs + Target Profit) by selling price: $840,000 ÷ $350 = 2,400, they are using revenue instead of the contribution margin per unit. This error fails to recognize that variable costs consume $210 of each $350 in sales revenue, leaving only $140 to contribute toward fixed costs and profit.",
    "ExplanationWrongC": "2,000 units is the result of dividing only the target profit by the CM per unit: $280,000 ÷ $140 = 2,000. This error treats the contribution margin as though it only needs to cover the target profit, completely ignoring the $560,000 in fixed costs that must also be recovered. Each unit's $140 contribution margin must first cover fixed costs before any profit is earned.",
    "ExplanationWrongD": "",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-03: Target Profit (units) = (Fixed Costs + Target Profit) / CM per Unit",
    "CommonTrapReference": "Omitting fixed costs from the numerator — computing only target profit ÷ CM per unit, or computing only breakeven",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: CM=$140; ($560K+$280K)/$140 = 6,000",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.004 CVP margin of safety analysis",
    "QuestionID": "P2-C-004",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-004-cvp-margin-of-safety-analysis",
    "Stem": "Harbor Food Processors budgeted sales of $3,600,000 for the current year. The company's breakeven sales are $2,700,000. The VP of Operations is concerned about a potential industry downturn and asks the controller to compute the margin of safety percentage to assess the company's risk exposure.",
    "Choices": {
      "A": "33.3%",
      "B": "75.0%",
      "C": "25.0%",
      "D": "20.0%"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "The margin of safety measures how much sales can decline before the company reaches its breakeven point. It is computed as (Actual Sales − Breakeven Sales) ÷ Actual Sales × 100. For Harbor Food Processors: ($3,600,000 − $2,700,000) ÷ $3,600,000 = $900,000 ÷ $3,600,000 = 0.25 = 25.0%. This means sales could decline by up to 25% before the company incurs a loss. A higher margin of safety indicates lower operating risk. A common error is reversing the numerator — using breakeven sales less actual sales — which would produce a meaningless negative percentage.",
    "ExplanationWrongA": "33.3% results from dividing the margin of safety in dollars ($900,000) by breakeven sales ($2,700,000) instead of actual sales: $900,000 ÷ $2,700,000 = 33.3%. A candidate making this error is using the wrong denominator. The margin of safety is always expressed as a percentage of actual (or budgeted) sales, not breakeven sales. The denominator must be actual sales because the question is 'how much can sales decline?' — the decline is relative to the current level, not the breakeven level.",
    "ExplanationWrongB": "75.0% results from dividing breakeven sales by actual sales: $2,700,000 ÷ $3,600,000 = 75.0%. This is the breakeven-to-actual ratio, not the margin of safety. A candidate making this error is computing what portion of current sales is needed just to break even, but the margin of safety measures the excess — the sales that can be lost before reaching breakeven. The two ratios are complements (25% + 75% = 100%).",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "20.0% results from an arithmetic error, possibly using breakeven sales of $2,880,000 instead of the correct $2,700,000: ($3,600,000 − $2,880,000) ÷ $3,600,000 = $720,000 ÷ $3,600,000 = 20%. Alternatively, a candidate may have subtracted incorrectly ($3,600,000 − $2,700,000 = $800,000 instead of $900,000) and then divided. The correct computation is ($3,600,000 − $2,700,000) ÷ $3,600,000 = 25.0%.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-04: Margin of Safety = (Actual Sales − BE Sales) / Actual Sales",
    "CommonTrapReference": "Using breakeven sales in the denominator instead of actual sales; computing the complement ratio",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: ($3,600K−$2,700K)/$3,600K = $900K/$3,600K = 25%",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.005 CVP degree of operating leverage concept",
    "QuestionID": "P2-C-005",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-005-cvp-degree-of-operating-leverage-concept",
    "Stem": "The CFO of Northstar Analytics is reviewing two possible cost structures for a new data analytics service. Structure X has high fixed costs and low variable costs per unit. Structure Y has low fixed costs and high variable costs per unit. Both structures produce the same operating income at the current sales volume. The CFO asks the controller which structure has the higher degree of operating leverage (DOL) and what this implies for the company's earnings risk.",
    "Choices": {
      "A": "Structure Y has the higher DOL because its variable costs are higher, meaning each additional sale contributes less margin and magnifies the effect of sales changes on operating income.",
      "B": "Both structures have the same DOL because they produce identical operating income at the current sales volume, and DOL is a function of operating income alone.",
      "C": "Structure Y has the higher DOL because the contribution margin ratio is lower when variable costs are higher, and DOL is negatively correlated with the CM ratio.",
      "D": "Structure X has the higher DOL because its higher fixed costs amplify the effect of a given percentage change in sales on operating income, resulting in greater earnings volatility."
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "The degree of operating leverage (DOL) equals contribution margin divided by operating income. Structure X, with higher fixed costs, has a higher contribution margin (because variable costs are lower) for the same level of operating income. Since DOL = CM ÷ OI, and CM is larger under Structure X while OI is identical, Structure X has the higher DOL. A higher DOL means that a given percentage change in sales will produce a larger percentage change in operating income — this is earnings volatility risk. Companies with high fixed costs and low variable costs (capital-intensive, automated operations) have higher operating leverage and greater earnings sensitivity to sales fluctuations. This is why airlines, manufacturers, and technology companies experience sharp profit swings when demand changes.",
    "ExplanationWrongA": "Structure Y actually has the lower DOL, not the higher. Higher variable costs reduce the contribution margin per unit, which reduces DOL (DOL = CM ÷ OI). Under Structure Y, each additional sale contributes less to covering fixed costs because most costs are already variable. Companies with high variable costs (labor-intensive, outsourced operations) have lower operating leverage and more stable earnings across sales volume changes. This candidate has the direction of the relationship reversed.",
    "ExplanationWrongB": "DOL is a function of both contribution margin and operating income, not operating income alone. While both structures have the same operating income at the current volume, their contribution margins differ substantially because of different cost structures. Structure X has a higher CM (lower variable costs), so CM ÷ OI yields a higher ratio. This candidate is treating DOL as if it were determined solely by the denominator, ignoring that the numerator (contribution margin) differs between the two cost structures. This is a common area of confusion between operating leverage and financial leverage.",
    "ExplanationWrongC": "Structure Y has the lower DOL, not the higher. While it is true that Structure Y has a lower CM ratio, DOL = CM ÷ OI, and with lower CM, the DOL is lower, not higher. DOL is positively correlated with the CM ratio, not negatively correlated. A candidate selecting this option has correctly identified that Structure Y has the lower CM ratio but then incorrectly concluded that this implies a higher DOL. The relationship is direct: higher fixed costs → higher CM per unit → higher DOL → greater earnings volatility.",
    "ExplanationWrongD": "",
    "Difficulty": "Moderate-Easy",
    "DifficultyScore": 2,
    "CognitiveLevel": "Understand",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-05: Degree of Operating Leverage = CM / Operating Income",
    "CommonTrapReference": "Confusing the direction of the relationship between cost structure and DOL; treating DOL as dependent on OI alone",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.006 CVP multi-product weighted average contribution margin",
    "QuestionID": "P2-C-006",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-006-cvp-multi-product-weighted-average-contribution-margin",
    "Stem": "Lakeside Medical Supply sells two product lines: a premium surgical kit (Model X) and a standard kit (Model Y). Model X accounts for 60% of total unit sales with a selling price of $120 and variable cost of $70 per kit. Model Y accounts for 40% of total unit sales with a selling price of $80 and variable cost of $50 per kit. Total annual fixed costs are $420,000. The controller needs to compute the company-wide breakeven point in total units.",
    "Choices": {
      "A": "10,000 units",
      "B": "8,400 units",
      "C": "14,000 units",
      "D": "10,500 units"
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Under multi-product CVP analysis, the weighted average contribution margin (WACM) is computed first, then used as the denominator for the company-wide breakeven calculation. Model X CM = $120 − $70 = $50. Model Y CM = $80 − $50 = $30. WACM = (0.60 × $50) + (0.40 × $30) = $30 + $12 = $42 per weighted-average unit. Company-wide breakeven units = Fixed Costs ÷ WACM = $420,000 ÷ $42 = 10,000 total units. After computing total breakeven units, individual product breakeven quantities are determined by applying the sales mix: Model X = 10,000 × 0.60 = 6,000 units; Model Y = 10,000 × 0.40 = 4,000 units. A critical exam trap is using the sales mix to compute a weighted average but then applying that total directly without disaggregating — or conversely, trying to compute breakeven per product independently without first computing the total.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "8,400 units results from dividing total fixed costs by Model X's contribution margin alone: $420,000 ÷ $50 = 8,400. This error treats the company as though it only sells the premium product, omitting Model Y entirely. A candidate making this error is applying single-product CVP logic to a multi-product environment. The sales mix is a structural feature of the business — Model Y accounts for 40% of units, and its lower contribution margin must be reflected in the weighted average.",
    "ExplanationWrongC": "14,000 units results from dividing total fixed costs by Model Y's contribution margin alone: $420,000 ÷ $30 = 14,000. This error treats all sales as if they consist only of the standard product with the lower contribution margin. A candidate selecting this option may be using the lowest CM as a conservative estimate, but this overstates the breakeven point. The correct approach weights both products' contribution margins by their respective sales mix percentages.",
    "ExplanationWrongD": "10,500 units results from computing a simple (unweighted) average of the two contribution margins and using that as the denominator: ($50 + $30) ÷ 2 = $40; $420,000 ÷ $40 = 10,500. A candidate making this error has recognized that both products must be considered but has treated them as equally weighted (50/50) rather than applying the actual sales mix (60/40). Sales mix weighting is fundamental to multi-product CVP — ignoring the actual proportions distorts the result.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-06: WACM = sum of (Sales Mix % × CM per Unit) per product",
    "CommonTrapReference": "T6: Omitting capacity/sales mix constraints in multi-product CVP — using single-product CM or unweighted average",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: WACM = (0.60×$50)+(0.40×$30)=$42; BE = $420K/$42 = 10,000",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.007 CVP breakeven concept definition",
    "QuestionID": "P2-C-007",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-007-cvp-breakeven-concept-definition",
    "Stem": "The controller of Northfield Manufacturing is preparing the annual operating plan and needs to identify the sales level at which the company neither earns a profit nor incurs a loss. In cost-volume-profit analysis, the breakeven point is:",
    "Choices": {
      "A": "The sales level at which total revenues equal total fixed costs, with variable costs covered by contribution margin from additional units.",
      "B": "The maximum sales volume achievable given existing production capacity and the current cost structure.",
      "C": "The sales level at which total contribution margin equals total fixed costs, resulting in operating income of zero.",
      "D": "The sales level at which the contribution margin ratio and the gross margin ratio are equal, indicating optimal cost structure."
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "The breakeven point is the sales level at which total revenues exactly equal total costs (both fixed and variable), resulting in zero operating income. Algebraically, this occurs when total contribution margin equals total fixed costs. At this point, the company has covered all costs but has not yet earned a profit. Every unit sold beyond the breakeven point adds its contribution margin directly to operating profit. The breakeven point is a foundational CVP concept used by managers to assess risk, set sales targets, and evaluate the viability of new products or business segments.",
    "ExplanationWrongA": "Total revenues equal to total fixed costs alone is insufficient to break even — variable costs must also be covered. At the breakeven point, total revenues must equal the sum of both fixed and variable costs. A candidate selecting this option has omitted variable costs from the break-even equation, treating fixed costs as the only cost requiring coverage. In practice, each unit sold consumes variable resources that must be recovered through the selling price before any contribution to fixed costs is possible.",
    "ExplanationWrongB": "Maximum sales volume describes production capacity, not the breakeven point. The breakeven point is a specific sales level where profit is zero, typically well below maximum capacity. A candidate selecting this option may be confusing the concepts of capacity utilization and breakeven analysis. Capacity represents the upper limit of production, while the breakeven point represents the minimum sales level needed to avoid a loss.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Equality of the CM ratio and gross margin ratio is not a CVP concept — these two ratios measure different things and would be equal only by coincidence (when variable SG&A equals zero). The breakeven point is defined by the relationship between total revenues and total costs, not by the equality of any two ratios. A candidate selecting this option is confusing ratio analysis with CVP analysis. This is a common area of confusion between financial statement analysis and managerial decision-making frameworks.",
    "Difficulty": "Easy",
    "DifficultyScore": 1,
    "CognitiveLevel": "Remember",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "",
    "CommonTrapReference": "Confusing breakeven with capacity, or omitting variable costs from the zero-profit condition",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified — definition recall at Remember level",
      "Independent answer derived",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.008 CVP assumptions and limitations",
    "QuestionID": "P2-C-008",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-008-cvp-assumptions-and-limitations",
    "Stem": "The controller of Ridgeview Electronics is preparing a CVP analysis to evaluate the launch of a new product line. Before presenting the analysis to management, the controller identifies several limitations of CVP analysis. Which of the following is a recognized limitation of CVP analysis?",
    "Choices": {
      "A": "CVP analysis assumes costs can be cleanly separated into fixed and variable components, which may be difficult in practice for semi-variable costs and step costs.",
      "B": "CVP analysis cannot accommodate multiple products — it is valid only for single-product companies.",
      "C": "CVP analysis assumes variable costs per unit increase proportionally with production volume, which overstates costs at higher output levels.",
      "D": "CVP analysis requires that inventory levels remain constant, making it inapplicable to companies that carry significant work-in-process inventory."
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "A fundamental limitation of CVP analysis is the assumption that costs can be classified as purely fixed or purely variable. In practice, many costs are semi-variable (mixed) or step-fixed, requiring judgment to separate into fixed and variable components. Misclassification distorts the contribution margin and breakeven calculations. For example, a utility bill with a fixed base charge plus a usage-based component must be split using the high-low method or regression analysis — and the chosen method affects the CVP results. Other recognized CVP limitations include the assumption of constant selling prices, constant sales mix (in multi-product settings), and the assumption that production volume equals sales volume (no inventory changes). Controllers must evaluate whether these simplifying assumptions are reasonable for the specific business context before relying on CVP outputs for decision-making.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "CVP analysis can accommodate multiple products through the use of a weighted average contribution margin (WACM) and a constant sales mix assumption. While the multi-product extension adds complexity, it does not invalidate CVP. A candidate selecting this option has confused the limitation of the basic single-product model with the capability of the extended multi-product framework.",
    "ExplanationWrongC": "CVP analysis assumes constant variable cost per unit — that is, variable costs do not change per unit with volume. Economies of scale (declining per-unit variable costs at higher volumes) or diseconomies (increasing per-unit costs) are not modeled in basic CVP. A candidate selecting this option has the direction of the assumption reversed. CVP assumes per-unit variable costs are constant, not increasing. The limitation is that real-world costs may not behave this way, not that CVP assumes they increase.",
    "ExplanationWrongD": "CVP analysis does assume production equals sales (no change in finished goods inventory), but this makes it less applicable when inventory levels change significantly — it does not make CVP 'inapplicable' nor does the limitation concern work-in-process inventory specifically. A candidate selecting this option has misidentified which inventory assumption is relevant (finished goods, not WIP). Additionally, absorption costing versus variable costing differences arise from inventory changes, which is a related but distinct concept from CVP analysis assumptions.",
    "Difficulty": "Moderate-Easy",
    "DifficultyScore": 2,
    "CognitiveLevel": "Understand",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "",
    "CommonTrapReference": "Confusing single-product vs multi-product CVP capability; misunderstanding constant variable cost per unit assumption",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.009 CVP sensitivity analysis — incremental profit impact",
    "QuestionID": "P2-C-009",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-009-cvp-sensitivity-analysis-incremental-profit-impact",
    "Stem": "Summit Packaging currently sells 25,000 units per year at $40 per unit. Variable costs are $24 per unit, and total annual fixed costs are $320,000. The VP of Sales proposes increasing the advertising budget by $60,000, which is expected to boost annual sales volume to 30,000 units. Assuming no other changes, what is the net effect of this proposal on annual operating income?",
    "Choices": {
      "A": "$80,000 increase",
      "B": "No change — the incremental contribution margin is entirely offset by the additional advertising expenditure.",
      "C": "$20,000 increase",
      "D": "$60,000 decrease"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "Under relevant costing, only incremental revenues and costs matter for decision analysis. Current CM per unit = $40 − $24 = $16. Current operating income = (25,000 × $16) − $320,000 = $400,000 − $320,000 = $80,000. Under the proposal: New contribution margin = 30,000 × $16 = $480,000. New operating income = $480,000 − ($320,000 + $60,000) = $480,000 − $380,000 = $100,000. The net effect = $100,000 − $80,000 = $20,000 increase. Alternatively, the incremental approach: Incremental CM = 5,000 additional units × $16 = $80,000. Incremental fixed costs = $60,000. Net change = $80,000 − $60,000 = $20,000 increase. The proposal is financially beneficial because the incremental contribution margin from the additional sales volume exceeds the incremental advertising cost.",
    "ExplanationWrongA": "$80,000 is the incremental contribution margin from the additional 5,000 units (5,000 × $16 = $80,000), but this figure ignores the $60,000 increase in advertising costs. A candidate selecting this option has correctly identified the incremental revenue impact but has not netted it against the incremental costs. Every business decision involves weighing both incremental benefits and incremental costs — focusing on only one side produces an incomplete analysis.",
    "ExplanationWrongB": "The incremental contribution margin of $80,000 exceeds the incremental advertising cost of $60,000 by $20,000, so the two do not offset. A candidate selecting this option may have incorrectly computed the incremental CM (for example, using a lower CM per unit) or may be applying a heuristic that any increase in fixed costs exactly consumes the benefit. In this case, the revenue increase more than justifies the additional spending. The breakeven point for the advertising increase would require only 3,750 additional units ($60,000 ÷ $16), and the proposal is expected to generate 5,000 additional units.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "A $60,000 decrease treats the advertising cost as the total effect on operating income, ignoring the additional contribution margin from the increased sales volume entirely. A candidate making this error is viewing the advertising expenditure in isolation — as a pure cost — without recognizing that advertising is expected to drive incremental sales. The correct analysis must consider both sides of the proposal: the cost of the advertising and the contribution margin from the additional units sold.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-03: Target Profit principles — incremental CM vs. incremental FC analysis",
    "CommonTrapReference": "Considering only incremental revenue or only incremental cost in isolation, rather than netting both for the decision",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: Incremental CM = 5,000×$16 = $80K; net = $80K−$60K = $20K increase",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.010 Marginal analysis — special order decision",
    "QuestionID": "P2-C-010",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-010-marginal-analysis-special-order-decision",
    "Stem": "Atlas Manufacturing normally sells its product for $45 per unit. Current production and sales are 20,000 units per year, well below the plant's capacity of 30,000 units. Variable costs are $30 per unit (direct materials $12, direct labor $8, variable overhead $5, variable selling costs $5). Total annual fixed costs are $400,000. A one-time special order from an international buyer offers to purchase 2,500 units at $29 per unit. The order would incur no variable selling costs and would have no effect on regular sales. The controller must recommend whether to accept or reject the order.",
    "Choices": {
      "A": "Accept, because the special order contributes $10,000 toward fixed costs and profit.",
      "B": "Reject, because the special order price of $29 is below the full absorption cost per unit of $50, resulting in a loss on each unit sold.",
      "C": "Reject, because the special order price of $29 is below the normal selling price of $45, and accepting special orders below market price damages the company's pricing power.",
      "D": "Accept, because the incremental revenue of $72,500 covers both the variable and allocated fixed costs, leaving a positive margin."
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Under relevant costing principles, only incremental costs and revenues matter for special-order decisions. The relevant variable cost is $25 per unit ($30 total variable cost minus $5 variable selling costs avoided on this order). Incremental revenue = 2,500 × $29 = $72,500. Incremental cost = 2,500 × $25 = $62,500. Net contribution = $72,500 − $62,500 = $10,000. Since the order generates positive contribution margin and there is idle capacity, it should be accepted. Fixed costs are irrelevant — they will be incurred whether or not the order is accepted. The $5 variable selling cost per unit is also irrelevant because the international buyer's order incurs no selling costs. A common error is using full absorption cost (which includes allocated fixed costs) as the decision criterion, which incorrectly suggests the order should be rejected.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Full absorption cost per unit = Variable cost + (Fixed costs ÷ Normal volume) = $30 + ($400,000 ÷ 20,000) = $30 + $20 = $50. While $29 is below $50, the $20 of allocated fixed costs per unit is irrelevant to the decision — fixed costs totaling $400,000 will be incurred regardless. Relevant-cost analysis compares only incremental revenue ($72,500) against incremental cost ($62,500), yielding a positive contribution of $10,000. A candidate selecting this option is applying absorption-costing logic to a marginal-analysis decision, a common confusion between external financial reporting and internal decision-making frameworks.",
    "ExplanationWrongC": "The normal selling price of $45 is irrelevant to this decision because the special order represents an independent market segment (international buyer) that would not otherwise purchase the product at any price. Accepting the order does not cannibalize regular sales and does not affect the regular market price. The existence of idle capacity means the company can serve both markets without trade-offs. A candidate selecting this option is treating pricing-strategy concerns as decision factors when the relevant question is simply whether incremental revenue exceeds incremental cost.",
    "ExplanationWrongD": "The incremental cost analysis does not include allocated fixed costs — only the incremental variable costs of $25 per unit matter. Total incremental costs = 2,500 × $25 = $62,500. Incremental revenue = $72,500. The net contribution is $10,000, not a 'positive margin after covering variable and allocated fixed costs.' Allocated fixed costs per unit are not incremental and should be excluded from the analysis. A candidate making this error has accepted the order for the right conclusion but using flawed reasoning — including sunk or unavoidable costs in the incremental calculation.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-07: Accept special order if incremental revenue > incremental cost",
    "CommonTrapReference": "T3: Using absorption unit cost for special-order pricing",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: (2,500 × $29) − (2,500 × $25) = $72,500 − $62,500 = $10,000",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.011 Marginal analysis — make-or-buy with opportunity cost",
    "QuestionID": "P2-C-011",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-011-marginal-analysis-make-or-buy-with-opportunity-cost",
    "Stem": "Pine Ridge Components currently manufactures 15,000 units of Part M-7 internally, incurring the following per-unit costs: direct materials $8.00, direct labor $11.00, variable overhead $4.00, and allocated fixed overhead $9.00 (of which only $3.00 per unit is avoidable if the part is purchased externally). An outside supplier has offered to supply all 15,000 units at $28.00 each. If Pine Ridge purchases from the outside supplier, the freed production space can be used to manufacture a new product that would generate $45,000 in incremental contribution margin. The VP of Manufacturing asks the controller to determine whether to make or buy Part M-7.",
    "Choices": {
      "A": "Make, because the total relevant cost to make ($435,000) exceeds the purchase cost ($420,000), yielding a $15,000 disadvantage to buying.",
      "B": "Make, because the full cost to make ($480,000) is less than the purchase cost plus avoided overhead ($420,000 + $90,000 = $510,000).",
      "C": "Buy, because the purchase price per unit ($28.00) is less than the full absorption cost per unit ($32.00).",
      "D": "Buy, because the total relevant cost to make ($435,000) exceeds the purchase cost ($420,000), yielding a $15,000 advantage to buying."
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Under relevant costing, the make-or-buy analysis compares only avoidable costs and opportunity costs. Avoidable costs to make = DM ($8) + DL ($11) + VOH ($4) + avoidable FOH ($3) = $26 per unit × 15,000 units = $390,000. Opportunity cost = $45,000 (incremental CM from the alternative use of the freed capacity). Total relevant cost to make = $390,000 + $45,000 = $435,000. Cost to buy = 15,000 × $28 = $420,000. Since the cost to buy ($420,000) is less than the relevant cost to make ($435,000), buying yields a $15,000 advantage. The $6.00 per unit of unavoidable fixed overhead ($9.00 − $3.00) is irrelevant — it will be incurred regardless of the decision. A critical exam trap is forgetting the opportunity cost when freed capacity has an alternative productive use.",
    "ExplanationWrongA": "The arithmetic is correct: relevant cost to make ($435,000) exceeds purchase cost ($420,000). However, the conclusion is reversed — when the cost to make exceeds the cost to buy, the company should buy, not make. A candidate selecting this option has correctly computed the relevant costs but drawn the wrong directional conclusion. When the relevant cost to make is higher than the purchase cost, external procurement is the economically superior choice.",
    "ExplanationWrongB": "The full cost to make is ($8 + $11 + $4 + $9) × 15,000 = $480,000, not a useful measure. The comparison with 'purchase cost plus avoided overhead' of $420,000 + $90,000 = $510,000 incorrectly adds unavoidable overhead to the purchase alternative. A candidate selecting this option is using full absorption costs and incorrectly including costs that do not differ between alternatives. The unavoidable $6 per unit of fixed overhead ($90,000 total) is irrelevant — it persists under either alternative and should be excluded from the analysis.",
    "ExplanationWrongC": "While the purchase price per unit ($28) is less than the full absorption cost per unit ($32), this comparison ignores the opportunity cost of $45,000 from the alternative use of the freed capacity. Even if the purchase price appears favorable against full cost, the make-or-buy analysis must also account for what is given up by buying — the $45,000 of contribution margin from the new product that can only be produced if the space is freed. Additionally, the $6 of unavoidable fixed overhead per unit ($9 − $3) is not a relevant cost. The correct analysis compares the total cost to buy ($420,000) against the total relevant cost to make ($435,000).",
    "ExplanationWrongD": "",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-08: Make-or-buy — relevant cost = avoidable costs + opportunity cost",
    "CommonTrapReference": "T4: Forgetting opportunity cost in make-or-buy; T1: Including sunk/unavoidable fixed costs",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: (15,000 × $26) + $45,000 = $435,000 make vs. $420,000 buy = $15,000 advantage to buy",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.012 Marginal analysis — sell-or-process-further decision",
    "QuestionID": "P2-C-012",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-012-marginal-analysis-sell-or-process-further-decision",
    "Stem": "Harbor Food Processors produces an intermediate food ingredient at a joint processing cost of $180,000 per batch. At the split-off point, 10,000 gallons of the product can be sold as-is for $12 per gallon, generating $120,000 in revenue. Alternatively, the product can be further processed at an additional cost of $3.50 per gallon into a premium ingredient that would sell for $17 per gallon. The controller is evaluating whether to sell at split-off or process further.",
    "Choices": {
      "A": "Process further, because incremental revenue of $170,000 exceeds incremental cost of $35,000, yielding a net benefit of $135,000 per batch.",
      "B": "Process further, because incremental revenue of $50,000 exceeds incremental cost of $35,000, yielding a net benefit of $15,000 per batch.",
      "C": "Sell at split-off, because after allocating joint costs of $180,000, selling as-is avoids additional processing costs and produces less overall loss.",
      "D": "Sell at split-off, because processing further adds only $5.00 per gallon in revenue ($17 − $12), which is less than the joint cost per gallon of $18.00."
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Under relevant costing, joint costs are sunk at the split-off point and are irrelevant to the sell-or-process-further decision. Only incremental revenues and incremental costs beyond the split-off point matter. Incremental revenue = 10,000 × ($17 − $12) = 10,000 × $5 = $50,000. Incremental cost = 10,000 × $3.50 = $35,000. Net benefit from further processing = $50,000 − $35,000 = $15,000. Since the net benefit is positive, Harbor Food Processors should process further. The $180,000 in joint costs would be incurred regardless of the decision — they are sunk at the split-off point and must be excluded from the analysis. A critical exam trap is allocating joint costs to the further-processing alternative and incorrectly concluding that the product is unprofitable.",
    "ExplanationWrongA": "$170,000 is the total revenue from further processing ($170,000 = 10,000 × $17), but this represents all revenue, not the incremental revenue. A candidate selecting this option is comparing total post-processing revenue against incremental costs, which is inconsistent — the comparison must use incremental revenue ($50,000, the difference between $170,000 and $120,000) against incremental costs ($35,000). Using total revenue incorrectly inflates the apparent benefit.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Joint costs of $180,000 are sunk — they are irrelevant to the sell-or-process-further decision and should not be allocated to either alternative. Both alternatives (sell at split-off for $120,000 or process further for a net benefit of $15,000 above split-off value) share the same joint costs. Allocating the $180,000 distorts the comparison by making both alternatives appear unprofitable when the relevant question is simply: does the incremental revenue from further processing exceed the incremental cost? The answer is yes ($50,000 > $35,000). A candidate selecting this option has incorrectly included sunk costs in a marginal analysis — this is the most common error on sell-or-process-further exam questions.",
    "ExplanationWrongD": "The comparison of incremental revenue per gallon ($5.00 = $17 − $12) against joint cost per gallon ($18.00 = $180,000 ÷ 10,000) mixes incremental and sunk costs. Joint costs per unit apply equally to both the sell-at-split-off and process-further alternatives and thus cancel out in the comparison. The relevant comparison is incremental revenue ($5.00/gallon) against incremental cost ($3.50/gallon), yielding a $1.50/gallon net benefit. A candidate making this error is failing to distinguish between costs that differ between alternatives (relevant) and costs that do not differ (irrelevant).",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-08: Process further if Incremental Revenue > Incremental Cost",
    "CommonTrapReference": "T5: Applying joint costs to sell-or-process-further decisions — joint costs are sunk at split-off",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: (10,000 × $5) − (10,000 × $3.50) = $50,000 − $35,000 = $15,000",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.013 Marginal analysis — sunk cost concept",
    "QuestionID": "P2-C-013",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-013-marginal-analysis-sunk-cost-concept",
    "Stem": "In the context of decision analysis, which of the following best describes a sunk cost?",
    "Choices": {
      "A": "A future cost that varies between decision alternatives and must be included in the incremental analysis.",
      "B": "A cost that represents the value of the next-best alternative forgone when a particular course of action is chosen.",
      "C": "A cost that has already been incurred and cannot be avoided or changed by any current or future decision.",
      "D": "A cost that remains constant in total within the relevant range regardless of changes in production volume."
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "A sunk cost is a cost that has already been incurred and cannot be recovered or changed by any current or future action. Because sunk costs are unavoidable and do not differ between decision alternatives, they are irrelevant for decision-making. Examples include the original cost of equipment already purchased, past research and development expenditures, and joint costs incurred before the split-off point. The most common exam error in decision analysis is including sunk costs in incremental comparisons — for example, allowing the book value of old equipment to influence a replacement decision when only future cash flows are relevant.",
    "ExplanationWrongA": "This describes a differential or incremental cost — a future cost that differs between alternatives and is relevant for decision-making. A candidate selecting this option is confusing two opposing concepts: differential costs (which are relevant and should be included) and sunk costs (which are irrelevant and should be excluded). The presence of the phrase 'future cost' is the key distinction — sunk costs are past costs.",
    "ExplanationWrongB": "This describes an opportunity cost — the benefit forgone by choosing one alternative over another. Opportunity costs are relevant for decision-making because they represent a real economic sacrifice, even though they do not involve a cash outlay. A candidate selecting this option is confusing opportunity costs with sunk costs. While both are conceptual costs, opportunity costs are relevant (they differ between alternatives), while sunk costs are irrelevant (they do not differ).",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "This describes a fixed cost within the relevant range — a cost that does not vary with production volume. While some fixed costs may also be sunk, the two concepts are distinct. A fixed cost can be avoidable (e.g., a lease that can be terminated) and thus relevant for decision-making. A candidate selecting this option is confusing the cost behavior classification (fixed vs. variable) with the decision-relevance classification (sunk vs. avoidable).",
    "Difficulty": "Easy",
    "DifficultyScore": 1,
    "CognitiveLevel": "Remember",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "",
    "CommonTrapReference": "T1: Including sunk costs in relevant-cost analysis — confusing sunk costs with differential or opportunity costs",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified — definition recall at Remember level",
      "Independent answer derived",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.014 Marginal analysis — opportunity cost concept",
    "QuestionID": "P2-C-014",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-014-marginal-analysis-opportunity-cost-concept",
    "Stem": "Meridian Equipment owns a specialized machine that is currently idle. A production manager proposes using the machine to manufacture a new component that would generate $90,000 in contribution margin. However, the controller notes that six months from now, the machine will be needed for a scheduled production run of the company's best-selling product, which will generate $75,000 in contribution margin. If the new component's production cannot be completed and the machine reconfigured in time for the scheduled run, what is the opportunity cost of using the machine now?",
    "Choices": {
      "A": "$0, because the machine is currently idle and has no alternative use in the present period.",
      "B": "$90,000, which is the contribution margin from the proposed new component.",
      "C": "$15,000, which is the net difference between the two potential contribution margins.",
      "D": "$75,000, which is the contribution margin from the scheduled production run that would be sacrificed."
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Opportunity cost is the benefit forgone when choosing one alternative over another — specifically, the value of the next-best alternative. If using the machine now prevents its availability for the scheduled production run, the company sacrifices $75,000 in contribution margin from the best-selling product. This $75,000 is the opportunity cost of the current proposal. The decision should compare the $90,000 benefit from the new component against the $75,000 opportunity cost, yielding a net advantage of $15,000 for the current proposal. If the opportunity cost exceeded $90,000, the company should reject the current proposal and preserve the machine's availability for the scheduled run. Opportunity costs are relevant for decision-making even though they do not involve a cash outlay — they represent real economic sacrifices.",
    "ExplanationWrongA": "An idle resource still carries an opportunity cost if its current use precludes a future use that has value. The $75,000 scheduled production run is a foregone benefit if the machine is committed now. A candidate selecting this option is treating the machine as though it has infinite capacity or assuming that its current availability means there is no future constraint. In capital budgeting and relevant costing, the timing of resource commitments matters — using capacity now can displace future profitable uses.",
    "ExplanationWrongB": "$90,000 is the benefit of the chosen alternative, not its opportunity cost. By definition, opportunity cost is the value of the next-best alternative forgone — the $75,000 from the scheduled run. A candidate selecting this option has the direction of the definition reversed, confusing the benefit obtained with the benefit sacrificed. In decision analysis, the chosen alternative's contribution margin is the benefit; the opportunity cost is what is given up by not choosing the next-best option.",
    "ExplanationWrongC": "$15,000 is the net advantage of the proposal ($90,000 − $75,000), not the opportunity cost. The opportunity cost is specifically the $75,000 sacrificed — the full value of the foregone alternative, not the net difference. A candidate selecting this option is computing the incremental benefit of the decision rather than identifying the opportunity cost. While the net advantage is relevant for the final decision, the question asks specifically for the opportunity cost, which is the full amount forgone.",
    "ExplanationWrongD": "",
    "Difficulty": "Moderate-Easy",
    "DifficultyScore": 2,
    "CognitiveLevel": "Understand",
    "CalculationItem": false,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "",
    "CommonTrapReference": "T4: Forgetting opportunity cost in resource-allocation decisions; confusing net advantage with opportunity cost",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.015 Relevant costing — add-or-drop segment decision",
    "QuestionID": "P2-C-015",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-015-relevant-costing-add-or-drop-segment-decision",
    "Stem": "Harbor Food Processors operates three product lines. Financial results for the Packaged Salads line are as follows: sales revenue $480,000, variable costs $336,000, direct fixed costs (avoidable if the line is dropped) $108,000, and allocated common fixed costs $72,000. The allocated common fixed costs are corporate overhead that would continue regardless of whether the Packaged Salads line is retained. The VP of Operations is considering dropping the line due to its reported loss. The controller is asked to evaluate the financial impact of dropping the Packaged Salads line.",
    "Choices": {
      "A": "Dropping the line would increase overall company profit by $36,000, because the segment currently reports a loss of $36,000.",
      "B": "Dropping the line would decrease overall company profit by $36,000, because the segment's contribution toward common fixed costs would be lost.",
      "C": "Dropping the line would decrease overall company profit by $108,000, because the direct fixed costs represent sunk costs that cannot be recovered.",
      "D": "Dropping the line would have no effect on overall company profit, because the loss is caused entirely by allocated common fixed costs, which would simply be reallocated to the remaining product lines."
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The segment margin = Sales − Variable Costs − Avoidable Fixed Costs = $480,000 − $336,000 − $108,000 = $36,000. This $36,000 is a positive contribution toward the $72,000 of allocated common fixed costs. The reported loss of $36,000 ($36,000 segment margin − $72,000 common fixed costs = −$36,000) reflects the allocation of common costs, not the segment's true economic contribution. If the line is dropped, the company loses the $36,000 segment margin but saves none of the $72,000 in common fixed costs (which are unavoidable). The net effect is a $36,000 decrease in overall company profit. A critical exam principle: allocated common fixed costs are irrelevant to segment retention decisions because they do not disappear when the segment is dropped — they persist and must be covered by the remaining segments.",
    "ExplanationWrongA": "While the segment reports an accounting loss of $36,000 ($480,000 − $336,000 − $108,000 − $72,000 = −$36,000), this loss includes $72,000 of allocated common fixed costs that will not disappear if the line is dropped. The relevant measure is the segment margin of $36,000 ($480,000 − $336,000 − $108,000), which is positive. Dropping the line would eliminate this positive contribution, decreasing total company profit. A candidate selecting this option is treating all costs as avoidable, a common error in add-or-drop analysis.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "The direct fixed costs of $108,000 are avoidable — they would be eliminated if the line is dropped. The segment margin calculation already accounts for this ($480,000 − $336,000 − $108,000 = $36,000). The $36,000 positive segment margin means the line contributes more in gross margin than the avoidable fixed costs it incurs. A candidate selecting this option has misclassified avoidable fixed costs as sunk, or has confused the sign of the impact. Dropping the line loses the $480,000 in revenue but also saves $336,000 in variable costs and $108,000 in avoidable fixed costs — the net is a loss of $36,000 in contribution toward common costs.",
    "ExplanationWrongD": "The line is not at breakeven — it generates a positive segment margin of $36,000. While the allocated common fixed costs of $72,000 would indeed be reallocated to the remaining product lines, the company would also lose the $36,000 segment margin from this line. The net effect is a $36,000 decrease in total company profit, because the common fixed costs persist but the contribution from this segment disappears. A candidate selecting this option has recognized that common costs are irrelevant but has failed to compute the segment margin correctly — or has incorrectly assumed the segment margin is zero.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.4",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-07: Segment margin = Revenue − Variable Costs − Avoidable Fixed Costs",
    "CommonTrapReference": "T1: Including allocated common fixed costs in segment retention decisions — only avoidable costs are relevant",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: Segment margin = $480K − $336K − $108K = $36K positive; dropping loses this contribution",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.016 multi-product-cvp-weighted-average-cm",
    "QuestionID": "P2-C-016",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-016-multi-product-cvp-wacm-breakeven",
    "Stem": "Kellerman Industries produces two products. Product X has a contribution margin of $24 per unit and Product Y has a contribution margin of $40 per unit. The expected sales mix is three units of X for every one unit of Y. Total fixed costs are $336,000. The controller is preparing the breakeven analysis for the annual operating plan.",
    "Choices": {
      "A": "8,400 units",
      "B": "10,500 units",
      "C": "12,000 units",
      "D": "14,000 units"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "In multi-product CVP analysis, the breakeven point uses the weighted average contribution margin (WACM) based on the sales mix. For a bundle of 4 units (3X + 1Y), total CM = (3 x $24) + (1 x $40) = $72 + $40 = $112. WACM per unit = $112 / 4 = $28. Breakeven in total units = $336,000 / $28 = 12,000 units. Kellerman must sell a combined 12,000 units: 9,000 units of X and 3,000 units of Y. Products with different CM must be weighted, not averaged; the simple arithmetic mean of the two CM values ($32) would understate the breakeven point because it overweights the higher-CM product relative to the actual mix.",
    "ExplanationWrongA": "8,400 units results from dividing fixed costs by Product Y's CM alone ($336,000 / $40), ignoring Product X entirely. A candidate making this error treats the lower-margin product as though its contribution data is irrelevant, analogous to trap T1: excluding a relevant component from the weighted analysis. T1: including sunk costs / excluding relevant costs",
    "ExplanationWrongB": "10,500 units results from computing a simple average CM of ($24 + $40) / 2 = $32 and dividing $336,000 / $32. The simple average assumes equal sales of both products, ignoring the 3:1 mix. Because Product Y has a higher CM and represents a smaller share of the mix, the simple average overstates WACM. T2: treating unit data as if uniformly distributed",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "14,000 units results from dividing fixed costs by Product X's CM alone ($336,000 / $24), ignoring Product Y's higher $40 contribution entirely. Each unit of Y in the bundle contributes $40 toward fixed costs; excluding Y inflates the breakeven quantity. T1: treating relevant contribution data as though it does not factor into the decision.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.1",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-01: Breakeven = Fixed Costs / Weighted Average CM per Unit",
    "CommonTrapReference": "T2: Using simple average CM instead of sales-mix-weighted WACM",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty (DL-008)",
      "Non-CC EW slots >=50 chars (DL-026)",
      "No boilerplate (DL-013)",
      "Difficulty justified",
      "Independent calculation: WACM=28, BE=12,000",
      "Authority citations match"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.017 shut-down-point-short-run",
    "QuestionID": "P2-C-017",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-017-shut-down-continue-if-price-covers-avc",
    "Stem": "Denton Manufacturing operates a single production line with monthly fixed costs of $180,000. The product sells for $48 per unit, variable manufacturing cost is $26 per unit, and variable selling cost is $4 per unit. Current monthly production and sales are 4,500 units, well below capacity of 10,000. Operating income is negative. The controller must recommend whether to continue operations or shut down in the short run.",
    "Choices": {
      "A": "Shut down immediately, because fixed costs are avoidable in the long run",
      "B": "Shut down, because operating income of $(99,000) is negative and the factory is below capacity",
      "C": "Continue operating, because the $48 selling price exceeds the $26 variable manufacturing cost per unit",
      "D": "Continue operating, because the $48 selling price exceeds the $30 average variable cost per unit, generating $18 contribution per unit toward fixed costs"
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "The short-run shut-down rule: continue if price covers AVC. Total variable cost = $26 + $4 = $30 per unit. Selling price of $48 exceeds $30 AVC, generating $18 CM per unit. Total CM = 4,500 x $18 = $81,000, which reduces the loss from $180,000 (shut-down) to $99,000 (operating). The $81,000 advantage of continuing makes the decision clear. Fixed costs of $180,000 are committed in the short run; they are irrelevant. This is grounded in marginal analysis and CVP framework.",
    "ExplanationWrongA": "Shutting down because fixed costs are avoidable in the long run confuses short-run and long-run analysis. In the short run, $180,000 in fixed costs are committed and unavoidable. The relevant question is whether $48 price exceeds $30 AVC -- it does, contributing $81,000 toward unavoidable fixed costs. T1: including committed fixed costs in short-run relevant-cost analysis when they are sunk and common to both alternatives.",
    "ExplanationWrongB": "Negative operating income of $(99,000) does not justify shut-down when the shut-down alternative produces a larger loss of $180,000. The $81,000 CM reduces the loss relative to ceasing operations. The correct comparison: operate and lose $99K vs. shut down and lose $180K -- an $81K advantage to continuing.",
    "ExplanationWrongC": "While the $48 price exceeds the $26 variable manufacturing cost, this analysis is incomplete -- it omits the $4 variable selling cost per unit. Total variable cost is $30, and correct CM is $18, not $22. Although the conclusion to continue happens to be correct here, the reasoning is flawed. In a scenario with higher selling costs, this partial analysis could produce the wrong recommendation. T2: narrowly defining variable cost without capturing all costs that vary with the decision.",
    "ExplanationWrongD": "",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-07: Shut-down -- Continue if Price >= Minimum AVC",
    "CommonTrapReference": "T1: Including sunk costs in relevant-cost analysis",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty (DL-008)",
      "Non-CC EW slots >=50 chars (DL-026)",
      "No boilerplate (DL-013)",
      "Difficulty justified",
      "Independent: AVC=$30, $48>$30, continue; loss vs shut-down: $99K vs $180K",
      "Authority citations match"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.018 Make-or-buy analysis with opportunity cost",
    "QuestionID": "P2-C-018",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-018-make-or-buy-analysis-with-opportunity-cost",
    "Stem": "Northfield Industries produces a motor bracket in-house at a variable cost of $25 per unit. The bracket absorbs $80,000 of annual fixed overhead, of which 50% is avoidable if production ceases. An external supplier offers the bracket for $22 per unit. If Northfield outsources, the idle factory space can be subleased for $50,000 annually. Annual demand is 20,000 units. The controller is evaluating the annual net financial impact of accepting the supplier’s offer.",
    "Choices": {
      "A": "$150,000 lower cost by outsourcing",
      "B": "$110,000 lower cost by outsourcing",
      "C": "$100,000 lower cost by outsourcing",
      "D": "$60,000 lower cost by outsourcing"
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Under relevant costing, the make-or-buy analysis compares the total relevant cost of each alternative. Relevant cost to make = variable cost + avoidable fixed overhead = ($25 × 20,000) + ($80,000 × 50%) = $500,000 + $40,000 = $540,000. Relevant cost to buy = purchase cost − opportunity benefits = ($22 × 20,000) − $50,000 sublease revenue = $440,000 − $50,000 = $390,000. Net advantage = $540,000 − $390,000 = $150,000 lower cost by outsourcing. The $40,000 of unavoidable fixed overhead (50% of $80,000) continues under both alternatives and is irrelevant. A critical exam principle: avoidable fixed costs increase the relevant cost of making; opportunity benefits reduce the relevant cost of buying. Both must be included for a complete analysis.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "$110,000 lower cost results from forgetting the $40,000 avoidable fixed overhead. The make cost is understated at variable cost only ($25 × 20,000 = $500,000) while the buy cost correctly includes the sublease benefit ($22 × 20,000 − $50,000 = $390,000). The difference of $110,000 understates the true $150,000 advantage. The $40,000 of avoidable fixed overhead represents a cost that will be incurred only if production continues in-house; it is a relevant cost of the make alternative. This error reflects trap T2 — treating all fixed costs as irrelevant to the decision, when in fact the avoidable portion is a differential cost.",
    "ExplanationWrongC": "$100,000 lower cost results from forgetting the $50,000 sublease revenue that becomes available only under the outsourced alternative. The make cost is correctly computed at $540,000 ($500,000 variable + $40,000 avoidable fixed), but the buy cost is compared at the purchase price alone ($22 × 20,000 = $440,000), yielding $540,000 − $440,000 = $100,000. The $50,000 lease income reduces the net cost of buying and must be subtracted to reflect the full economic impact. This error reflects trap T4 — forgetting the opportunity cost in the make-or-buy comparison. Sublease revenue is an opportunity benefit of outsourcing.",
    "ExplanationWrongD": "$60,000 lower cost results from forgetting both the $40,000 avoidable fixed overhead and the $50,000 sublease revenue. The make cost is understated at variable cost only ($25 × 20,000 = $500,000), and the buy cost is overstated at purchase price only ($22 × 20,000 = $440,000), yielding $500,000 − $440,000 = $60,000. This double omission captures neither the relevant cost of making nor the relevant cost of buying, producing a result that understates the true savings by $90,000. This error reflects traps T2 and T4 — excluding both avoidable fixed costs and opportunity benefits from the relevant-cost framework.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-08: Relevant costing — outsource if avoidable costs of making + opportunity cost > purchase cost − opportunity benefits",
    "CommonTrapReference": "T4: Forgetting opportunity cost in make-or-buy; T2: Treating unit fixed costs as if variable — failing to isolate avoidable fixed overhead",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: Make = $500K + $40K = $540K; Buy = $440K − $50K = $390K; advantage = $150K",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.019 Sell-or-process-further — joint products",
    "QuestionID": "P2-C-019",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-019-sell-or-process-further-joint-products",
    "Stem": "Pacific Foods processes a single agricultural input into three joint products. Joint processing costs total $240,000 per batch. After the split-off point, Product Alpha can be sold as-is for $80,000 or processed further at a cost of $45,000 and sold for $130,000. Product Beta can be sold as-is for $120,000 or processed further at a cost of $30,000 and sold for $145,000. Product Gamma can be sold as-is for $60,000 or processed further at a cost of $15,000 and sold for $72,000. The controller is evaluating which products, if any, should be processed further.",
    "Choices": {
      "A": "Alpha and Beta only",
      "B": "Alpha only",
      "C": "Alpha and Gamma only",
      "D": "All three products"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Under sell-or-process-further analysis, joint costs are sunk at the split-off point and irrelevant. For each product, compare incremental revenue (final selling price minus split-off selling price) to incremental processing cost. Alpha: incremental revenue = $130,000 − $80,000 = $50,000, incremental cost = $45,000, net gain = $5,000 — process further. Beta: incremental revenue = $145,000 − $120,000 = $25,000, incremental cost = $30,000, net loss = $(5,000) — sell at split-off. Gamma: incremental revenue = $72,000 − $60,000 = $12,000, incremental cost = $15,000, net loss = $(3,000) — sell at split-off. Only Alpha should be processed further. The $240,000 joint cost was intentionally included in the problem as a distractor — allocating it to individual products would distort every comparison. Joint costs are common costs incurred before the split-off point and are irrelevant to decisions beyond that point.",
    "ExplanationWrongA": "Selecting both Alpha and Beta for further processing includes Beta, which fails the incremental test. Beta’s incremental revenue of $25,000 ($145,000 − $120,000) is $5,000 less than its incremental processing cost of $30,000, producing a net loss. A candidate may select Beta for further processing after allocating a portion of the $240,000 joint cost to Beta and mistakenly concluding that further processing helps ‘recover’ the allocated cost. This error reflects trap T5 — applying joint costs, which are sunk at the split-off point, to the sell-or-process-further decision. Only incremental revenue and incremental cost are relevant.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Selecting Alpha and Gamma for further processing incorrectly includes Gamma. Gamma’s incremental revenue of $12,000 ($72,000 − $60,000) is $3,000 less than its incremental processing cost of $15,000, producing a net loss. The correct test is whether the incremental revenue exceeds the incremental processing cost, not whether the final selling price alone exceeds the processing cost. A candidate selecting Gamma may be comparing the final price of $72,000 against the $15,000 processing cost without subtracting the $60,000 split-off value — forgetting that the split-off sales value is forgone if the product is processed further. This error reflects trap T5 — focusing on absolute amounts rather than incremental differences.",
    "ExplanationWrongD": "Selecting all three products to process further includes both Beta and Gamma, each of which produces a net loss from further processing. Beta loses $5,000 ($25,000 − $30,000) and Gamma loses $3,000 ($12,000 − $15,000). Only Alpha’s incremental revenue of $50,000 exceeds its incremental cost of $45,000. A candidate selecting all three may be allocating the $240,000 joint cost across products and reasoning that further processing helps recover allocated joint costs across the full product line. This error reflects trap T5 — joint costs of $240,000 are sunk and must be excluded from the incremental analysis for each product.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.2",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-08: Process further — Process if Incremental Revenue > Incremental Cost",
    "CommonTrapReference": "T5: Applying joint costs to sell-or-process-further decisions — joint costs are sunk at the split-off point and irrelevant",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: Alpha $50K>$45K process; Beta $25K<$30K sell; Gamma $12K<$15K sell",
      "Authority citations match tested concept"
    ]
  },
    {
    "Part": 2,
    "Section": "C",
    "Topic": "C.020 Transfer pricing with capacity constraint — opportunity cost",
    "QuestionID": "P2-C-020",
    "question_state": "Unprocessed",
    "Part2OnlyFlag": true,
    "UniqueConceptKey": "C-020-transfer-pricing-with-capacity-constraint",
    "Stem": "Westlake Division manufactures a specialized component sold to outside customers for $85 per unit. Variable cost per unit is $50, and annual fixed costs are $420,000. The division operates at full capacity, producing and selling 20,000 units per year. Eastlake Division of the same company requests 3,000 units from Westlake. To fill this internal order, Westlake must reduce outside sales by 3,000 units. The controller is determining the minimum transfer price Westlake should accept for the internal order.",
    "Choices": {
      "A": "$50 per unit",
      "B": "$71 per unit",
      "C": "$85 per unit",
      "D": "$120 per unit"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "When the selling division operates at full capacity, the minimum transfer price equals variable cost plus the opportunity cost of lost external sales. Variable cost = $50 per unit. Opportunity cost per unit = lost contribution margin on outside sales = selling price minus variable cost = $85 − $50 = $35. Minimum transfer price = $50 + $35 = $85 per unit. At this price, the selling division is indifferent between selling internally and selling externally, because it recovers both its out-of-pocket cost and the $35 contribution margin it would have earned on each unit in the external market. The $420,000 of fixed costs is irrelevant to the transfer price — fixed costs are committed and do not vary with the internal transfer decision. When the selling division has idle capacity, the minimum transfer price is simply variable cost; at full capacity, the lost contribution margin on forgone sales becomes the binding constraint.",
    "ExplanationWrongA": "$50 per unit represents the variable cost alone, ignoring the $35 contribution margin forgone on each unit of external sales displaced by the internal order. Because Westlake is at full capacity, every unit transferred internally means one less unit sold externally, sacrificing $35 of contribution margin. The minimum transfer price must recover both the variable cost and this opportunity cost. At $50 per unit, the selling division would realize zero contribution margin on transferred units versus $35 per unit on external sales — an unacceptable outcome. This error reflects trap T4 — forgetting the opportunity cost in pricing decisions when capacity is constrained.",
    "ExplanationWrongB": "$71 per unit incorrectly computes the unit cost as variable cost plus average fixed cost ($50 + $420,000 ÷ 20,000 = $50 + $21 = $71). Fixed costs are committed and unavoidable within the relevant range; they are not relevant to the transfer pricing decision. The minimum transfer price formula requires variable cost and opportunity cost only — the $21 per unit of allocated fixed cost should be excluded. Using full absorption cost as the transfer price floor overstates the minimum when the selling division has idle capacity and understates it at full capacity because it ignores the opportunity cost. This error reflects trap T2 — treating fixed costs as if they are a relevant variable cost component of the transfer price.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "$120 per unit results from an incorrect formula that adds the contribution margin to the selling price ($85 + $35 = $120), double-counting the revenue forgone. The contribution margin of $35 already captures the net benefit lost per unit; adding it to the full $85 selling price essentially counts both the external revenue and the lost margin. The minimum transfer price is variable cost ($50) plus opportunity cost — the forgone contribution margin ($35) — yielding $85. When the selling division is at full capacity, the minimum transfer price equals the external market price, which is the economic result of the formula: $50 + ($85 − $50) = $85. This error reflects trap T4 — incorrectly measuring opportunity cost by adding rather than decomposing the external price.",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "CognitiveLevel": "Apply",
    "CalculationItem": true,
    "ItemStyle": "single-select",
    "LOSTag": "C.3",
    "BlueprintDomain": "Decision Analysis",
    "FormulaReference": "DA-09: Transfer pricing min = Variable Cost + Opportunity Cost",
    "CommonTrapReference": "T4: Forgetting opportunity cost in make-or-buy/transfer pricing — omitting the lost contribution margin when the selling division is at full capacity",
    "Authorities": [
      "IMA SMA on relevant costing"
    ],
    "VerifiedChecks": [
      "Part2OnlyFlag verified true",
      "EW[CC] empty",
      "Non-CC EW slots >= 75 chars",
      "No boilerplate text",
      "Difficulty justified",
      "Independent answer derived: Min transfer price = $50 VC + ($85 − $50) opportunity cost = $50 + $35 = $85",
      "Authority citations match tested concept"
    ]
  }
];
