// S063 Batch 1 — Section A Evaluate-Level Rewrites (inline version)
const fs = require('fs');
const src = fs.readFileSync('pack_a_corrected.js', 'utf8');
const varMatch = src.match(/^(var\s+\w+\s*=\s*)/);
const varDecl = varMatch ? varMatch[1] : 'var packA = ';
const arr = new Function(src.replace(/^var\s+\w+\s*=\s*/, 'return '))();

// Inline item definitions
const items = {};

items['P1-A-005'] = JSON.parse(JSON.stringify(arr[4]));
// Keep immutable fields, update changeable ones
items['P1-A-005'].Difficulty = "Difficult";
items['P1-A-005'].Stem = "CONTROLLER'S MEMORANDUM — Apex Industrial Controls\n\nTO: CFO Priya Mehta\nFROM: Elena Vasquez, Controller\nRE: Revenue Recognition for ApexGuard 9000 Customer Contracts\n\nApex sells the ApexGuard 9000, a programmable safety controller for chemical processing plants, under a standard customer contract with four components: (1) the hardware controller unit, delivered at contract signing for $180,000; (2) a three-year proprietary software license with quarterly security updates, bundled at $72,000; (3) on-site installation and calibration services performed over a two-week period following delivery, invoiced at $48,000; and (4) a two-year maintenance and technical support plan for $36,000. The controller and software license are sold separately to customers who already own ApexGuard hardware. Installation is performed by Apex-certified technicians and is also available as a standalone service. The software updates require Apex's proprietary encryption keys and cannot be performed by the customer or third parties. The maintenance plan includes 24/7 phone support and annual on-site inspections. Total contract price: $336,000. Ms. Mehta asks: 'How many performance obligations does this contract contain under ASC 606, and what is the basis for our determination?'";
items['P1-A-005'].Choices = {
    "A": "Four distinct performance obligations — hardware, software license, installation, and maintenance — because each is separately identifiable and the customer can benefit from each on its own or with readily available resources, and each is distinct within the context of the contract because the promises are not inputs to a combined output.",
    "B": "One combined performance obligation because all four components are part of a single integrated safety system solution. The customer purchased a complete chemical plant safety capability, and Apex should recognize revenue as a single performance obligation at the point when the system is fully operational.",
    "C": "Three performance obligations — hardware, bundled software-plus-installation, and maintenance — because installation and the software license are highly interdependent. The software cannot function without the hardware being properly installed and calibrated, so installation and the software license should be combined into a single performance obligation.",
    "D": "Two performance obligations — the hardware-plus-installation as one obligation (since the hardware must be installed to function) and the software-plus-maintenance as a second obligation (since the software updates and support are ongoing services). The bundled pricing makes individual separation impractical."
};
items['P1-A-005'].CorrectChoice = "A";
items['P1-A-005'].ExplanationCorrect = "Under ASC 606-10-25-14, a performance obligation is a promise to transfer a distinct good or service to the customer. A good or service is distinct if two criteria are met: (1) the customer can benefit from the good or service on its own or together with readily available resources (capable-of-being-distinct criterion), and (2) the entity's promise to transfer the good or service is separately identifiable from other promises in the contract (distinct-within-the-context-of-the-contract criterion). All four components meet both criteria. The hardware controller is a standalone product sold separately to existing ApexGuard customers — a customer who already owns the hardware could purchase just the hardware from Apex or a competitor, satisfying criterion 1. The proprietary software license with quarterly updates is also sold independently to customers who already have ApexGuard hardware, and customers can benefit from the license with the hardware they already own. The installation services are performed by Apex-certified technicians and are available as a standalone service — a customer could purchase hardware from Apex and hire an Apex-certified technician for installation under a separate arrangement. The maintenance plan is clearly distinct as an ongoing service that continues well after delivery and installation. Within the context of the contract, these four promises are not inputs to a combined output — the customer is purchasing discrete deliverables, not a single integrated item. The hardware can function without the software (a competitor's software could run on ApexGuard hardware), the software can run without Apex's maintenance plan, and installation is a one-time service that does not transform the other components. Therefore, the contract contains four distinct performance obligations, each requiring separate revenue recognition timing under the five-step model. A critical exam trap is concluding that multiple deliverables in a single contract automatically constitute one combined performance obligation — ASC 606 explicitly requires disaggregation when promises are distinct. Candidates should remember that 'separately sold' is strong evidence of distinctness, and bundled pricing does not, by itself, combine performance obligations.";
items['P1-A-005'].ExplanationWrongA = "";
items['P1-A-005'].ExplanationWrongB = "This recommendation incorrectly treats four separately identifiable deliverables as a single combined performance obligation because they relate to the same customer need. Under ASC 606-10-25-19 through 25-22, promises ARE distinct within the context of the contract unless they are inputs to a combined output the customer has contracted for. Apex is not delivering a single integrated safety system — the customer receives a hardware controller, a software license, installation services, and ongoing maintenance. Each can function without the others (the hardware can run third-party software; the software is sold standalone; installation is a one-time service; maintenance is ongoing support). The fact that a customer purchased all four components from Apex in one contract does not make them a single performance obligation. ASC 606 requires entities to identify all distinct goods and services — disaggregation, not aggregation, is the default. The controller should advise that four separate performance obligations exist, with revenue recognized as each is satisfied, not as a single combined deliverable.";
items['P1-A-005'].ExplanationWrongC = "This recommendation correctly identifies that performance obligations should be assessed for combination but incorrectly combines the software license and installation. Under ASC 606-10-25-21, promises are combined into a single performance obligation when (a) the goods or services in the bundle are inputs to a combined output, and (b) the bundle is significantly modified or customized. Installation does not significantly modify or customize the software license — the software is a pre-built proprietary product; installation is the physical setup and calibration of hardware. The software license is a right-to-use intellectual property that is distinct from the physical installation service. A customer could purchase the software license without installation (e.g., if they already have a configured ApexGuard 9000) or purchase installation without the software license (e.g., if they use third-party safety software). The controller should not combine these two promises — they are separately identifiable and should be accounted for as distinct performance obligations.";
items['P1-A-005'].ExplanationWrongD = "This recommendation undercounts performance obligations by assuming that bundled pricing merges goods and services into combined units. Under ASC 606-10-25-14, the distinctness analysis is based on the nature of the promise, not on pricing structure. The transaction price is allocated to performance obligations based on standalone selling prices (ASC 606-10-32-28 through 32-35), not used to determine whether obligations are distinct. Additionally, the hardware controller is sold separately and is capable of being distinct — it does not require installation to function (the customer could install it themselves or use a third-party installer). The software license is a separate right-to-use asset, not merely an adjunct to maintenance. The controller should identify four distinct performance obligations: hardware, software license, installation services, and maintenance plan. Bundled contract pricing allocates the total consideration — it does not collapse distinct promises into combined obligations.";
items['P1-A-005'].DifficultyScore = 4;
items['P1-A-005'].CognitiveLevel = "Evaluate";

// P1-A-008
items['P1-A-008'] = JSON.parse(JSON.stringify(arr[7]));
items['P1-A-008'].Difficulty = "Difficult";
items['P1-A-008'].Stem = "CFO BRIEFING NOTE — Ridgeview Manufacturing\n\nTO: CFO Alan Kettering\nFROM: Controller's Office\nRE: Year-End Inventory Valuation — Three Product Lines\n\nRidgeview manufactures industrial fasteners across three product lines. At year-end, the inventory balances and market conditions are: Line 1 (Standard Steel Bolts): Cost $420,000, NRV $485,000 — commodity product with stable demand; Line 2 (Alloy Fasteners): Cost $310,000, NRV $275,000 — customer canceled a major contract in November, leaving excess specialty inventory that can only be sold to a limited set of aerospace buyers; Line 3 (Engineered Components): Cost $185,000, NRV $168,000 — a new competitor entered the market in Q4, driving prices down, but Ridgeview expects a partial recovery within six months as the competitor's capacity is limited. All inventory is carried at FIFO cost. Ridgeview's external auditors have questioned whether the company should write down inventory on a product-line basis or assess impairment at a more aggregated level. Mr. Kettering asks: 'What is the appropriate write-down approach and total inventory value under ASC 330?'";
items['P1-A-008'].Choices = {
    "A": "Apply the lower of cost and NRV test on an item-by-item basis: Line 1 at cost ($420,000), Line 2 at NRV ($275,000), Line 3 at NRV ($168,000). Total inventory: $863,000. Write-down: $52,000. Item-by-item application is required under ASC 330-10-35-1B because it prevents offsetting declines in one product line against unrealized gains in another.",
    "B": "Apply lower of cost and NRV at the total inventory level: aggregate cost is $915,000 and aggregate NRV is $928,000, so no write-down is needed because the portfolio-level NRV exceeds cost. Total inventory: $915,000. Write-down: $0. Portfolio-level assessment is appropriate because Ridgeview manages inventory as a combined industrial fasteners business.",
    "C": "Write down only Line 2 by $35,000 because the contract cancellation is permanent, but carry Line 3 at cost because Ridgeview expects price recovery within six months. Under ASC 330, temporary market declines do not require write-downs. Total inventory: $880,000. Write-down: $35,000.",
    "D": "Write down all three lines to NRV even if NRV exceeds cost for Line 1, because conservatism demands that all inventory be stated at the lower valuation basis. Total inventory: $928,000. No write-down per se, but Line 1 is recorded at NRV of $485,000 which exceeds its cost basis."
};
items['P1-A-008'].CorrectChoice = "A";
items['P1-A-008'].ExplanationCorrect = "Under ASC 330-10-35-1B, inventory measured using FIFO or average cost must be stated at the lower of cost and net realizable value (NRV). Critically, ASC 330-10-35-1B requires this assessment to be applied on an item-by-item basis — not at the aggregate inventory level or product-category level — unless it is impracticable to do so. Each product line represents a separate item for LCM purposes because the fasteners have different cost structures, different markets, and different demand profiles. Line 1 (Standard Steel Bolts) has NRV of $485,000 exceeding cost of $420,000 — no write-down, inventory remains at $420,000 cost. Line 2 (Alloy Fasteners) has NRV of $275,000 below cost of $310,000 — a $35,000 write-down is required to state inventory at $275,000. Line 3 (Engineered Components) has NRV of $168,000 below cost of $185,000 — a $17,000 write-down to $168,000. Total inventory after write-downs: $420,000 + $275,000 + $168,000 = $863,000. Total write-down: $35,000 + $17,000 = $52,000. The item-by-item approach is essential because it prevents the offsetting of unrealized losses on one product line against unrealized holding gains on another — a core principle of LCM accounting. Offsetting would overstate inventory and understate cost of goods sold, misrepresenting Ridgeview's actual economic position. A critical exam trap is the temptation to aggregate across product lines when the NRV of Line 1's gain exceeds the combined losses on Lines 2 and 3 — this is explicitly prohibited. Candidates should also note that expected future price recovery (Line 3) does not excuse a write-down at the balance sheet date if NRV is below cost at that date. The assessment is made at each reporting date based on conditions existing at that date.";
items['P1-A-008'].ExplanationWrongA = "";
items['P1-A-008'].ExplanationWrongB = "This recommendation incorrectly applies the lower of cost and NRV test at the aggregate portfolio level. Under ASC 330-10-35-1B, the LCM test must be applied on an item-by-item basis — not at the total inventory level. While aggregate cost ($915,000) is below aggregate NRV ($928,000), this masks the fact that Line 2 and Line 3 individually have NRV below cost. A portfolio-level approach would allow the $65,000 unrealized gain on Line 1 ($485,000 NRV minus $420,000 cost) to offset $52,000 in required write-downs on Lines 2 and 3. This violates the fundamental LCM principle that losses must be recognized when they occur, while gains are not recognized until realized through sale. The controller should apply LCM separately to each product line, resulting in write-downs of $35,000 on Line 2 and $17,000 on Line 3. The fact that Ridgeview 'manages inventory as a combined business' does not determine the accounting unit of account — ASC 330 specifies item-by-item application.";
items['P1-A-008'].ExplanationWrongC = "This recommendation incorrectly distinguishes between a 'permanent' contract cancellation and an expected price recovery in determining whether a write-down is required. Under ASC 330-10-35-2, the LCM test is applied at each reporting date based on conditions existing at that date, without regard to expected future recoveries. The fact that Ridgeview expects Line 3 prices to recover within six months is a forecast, not a condition existing at the balance sheet date. There is no 'temporary decline' exception in ASC 330 for FIFO inventory — the standard requires write-down whenever NRV at the reporting date is below cost, regardless of expected future recovery. Both Line 2 ($35,000 write-down) and Line 3 ($17,000 write-down) require adjustment. If prices subsequently recover, Ridgeview may reverse the write-down up to the amount of the original write-down (not above original cost), but the reversal occurs in the future period, not at the current balance sheet date. The controller should recognize both write-downs at year-end.";
items['P1-A-008'].ExplanationWrongD = "This recommendation contains two fundamental errors. First, it proposes writing up Line 1 inventory above cost to NRV — this is not permitted under U.S. GAAP. The LCM rule states inventory at the lower of cost or NRV; when cost is below NRV, inventory remains at cost. Writing inventory up to NRV would recognize an unrealized holding gain, which ASC 330 does not permit. The correct treatment for Line 1 is to carry it at cost ($420,000). Second, the recommendation frames a write-up as 'conservatism,' but conservatism in accounting means not overstating assets or income — writing inventory above cost does exactly the opposite. The controller should apply LCM item-by-item: Line 1 at cost ($420,000), Line 2 written down to NRV ($275,000), and Line 3 written down to NRV ($168,000). Total inventory: $863,000. Total write-down: $52,000.";
items['P1-A-008'].DifficultyScore = 4;
items['P1-A-008'].CognitiveLevel = "Evaluate";

// P1-A-011
items['P1-A-011'] = JSON.parse(JSON.stringify(arr[10]));
items['P1-A-011'].Difficulty = "Difficult";
items['P1-A-011'].Stem = "INTERNAL MEMORANDUM — Keystone Industries\n\nTO: Controller David Chen\nFROM: Plant Manager Sarah Okonkwo, Keystone Toledo Facility\nRE: Production Line 4 — Performance Review\n\nProduction Line 4 is a dedicated automated stamping line (carrying amount: $6,200,000, remaining useful life: 9 years) that produces automotive body panels. Over the past 18 months, the line's output has declined from a peak of 92,000 units/month to 51,000 units/month due to mechanical wear and obsolescence of the control systems. Our primary customer (83% of Line 4 output) is transitioning to aluminum panels for their next-generation vehicle starting in 14 months, which Line 4 cannot produce without a $1.9 million retooling investment. The engineering assessment indicates that undiscounted future cash flows from continued use are projected at $5,400,000 through end of useful life (including retooling), while the fair value of Line 4 (based on a recent appraisal of comparable used equipment) is approximately $3,800,000. The line's current depreciation schedule assumes even output over 12 years. Mr. Chen asks: 'Under ASC 360, is an impairment test triggered, and which indicator carries the most weight in making this determination?'";
items['P1-A-011'].Choices = {
    "A": "Yes, an impairment test is triggered. The most significant indicator is the significant adverse change in the extent or manner in which the asset is used — the primary customer's transition to aluminum panels means 83% of Line 4's output will be eliminated unless a $1.9 million retooling investment is made. This constitutes a significant change in the asset's use under ASC 360-10-35-21(b). The output decline and obsolescence provide secondary corroboration.",
    "B": "No, an impairment test is not triggered because the undiscounted future cash flows of $5,400,000 are close to the carrying amount of $6,200,000, and indicators alone without a recoverability test failure do not trigger impairment recognition. The standard requires performing the test only when indicators are present, but the test itself must show a failure before impairment exists.",
    "C": "Yes, an impairment test is triggered, but the primary indicator is the mechanical output decline from 92,000 to 51,000 units/month — a 44.6% reduction that demonstrates the asset is physically deteriorating. The customer transition is a separate business risk that does not, by itself, affect the asset's carrying value under ASC 360.",
    "D": "No impairment test is required because the asset still has 9 years of remaining useful life and $5,400,000 in projected cash flows. An impairment test is only triggered when the carrying amount exceeds undiscounted future cash flows, and Keystone should continue with the current depreciation schedule until the customer actually transitions to aluminum panels in 14 months."
};
items['P1-A-011'].CorrectChoice = "A";
items['P1-A-011'].ExplanationCorrect = "Under ASC 360-10-35-21, a long-lived asset must be tested for recoverability whenever events or changes in circumstances indicate that its carrying amount may not be recoverable. The standard lists specific examples of impairment indicators, and the question presents several that collectively establish a clear triggering event. The single most significant indicator is the adverse change in the extent or manner in which Line 4 is used [ASC 360-10-35-21(b)]: the primary customer, representing 83% of Line 4's output, is transitioning to aluminum panels that Line 4 cannot produce without a $1.9 million retooling investment. This is not merely a sales forecast revision — it is a fundamental change in what the asset will be required to produce and whether its current configuration can meet future demand. The mechanical output decline (92,000 to 51,000 units/month, a 44.6% decline) provides secondary corroboration under ASC 360-10-35-21(c) — a significant decrease in the market value of the asset is implied by the fair value appraisal of $3,800,000, well below the carrying amount of $6,200,000. Once a triggering event is identified, Step 1 of the impairment test compares the carrying amount to the sum of undiscounted future cash flows. The projected $5,400,000 in undiscounted cash flows is below the $6,200,000 carrying amount — meaning the recoverability test IS failed, and Step 2 requires recognizing an impairment loss equal to the excess of carrying amount over fair value. A critical exam trap is confusing the triggering event (indicators that require testing) with the recoverability test itself (undiscounted cash flow comparison). Indicators trigger the test; the test determines whether impairment is recognized. The controller should not wait until the customer transition actually occurs — the indicator exists now because the circumstances have already changed. ASC 360 requires testing at the point when indicators arise, not when the adverse event fully materializes.";
items['P1-A-011'].ExplanationWrongA = "";
items['P1-A-011'].ExplanationWrongB = "This recommendation conflates two distinct steps in the ASC 360 impairment framework: (1) determining whether indicators exist that require a recoverability test, and (2) performing the recoverability test itself. The standard requires a test whenever indicators suggest the carrying amount may not be recoverable — it does NOT require that the undiscounted cash flows are already known to be below carrying amount before testing. The controller is asking whether a test is TRIGGERED (Step 1), not whether impairment should be RECOGNIZED (Step 2). Multiple indicators exist: the customer transition fundamentally changes how the asset will be used, the output decline is substantial, and the fair value appraisal of $3,800,000 is well below the carrying amount. These indicators require the controller to perform the recoverability test. The fact that undiscounted cash flows ($5,400,000) fall below the carrying amount ($6,200,000) confirms that the test should have been performed — and that impairment recognition is required. If the undiscounted cash flows had exceeded carrying amount, impairment would not be recognized, but the indicators still would have required performing the test. The controller must perform the test now; waiting until undiscounted cash flows clearly fail the test is circular reasoning.";
items['P1-A-011'].ExplanationWrongC = "This recommendation correctly identifies that impairment testing is triggered but misidentifies the primary indicator. While the mechanical output decline is a genuine concern, it is secondary to the customer-driven change in how the asset will be used. Under ASC 360-10-35-21(b), a significant adverse change in the extent or manner in which an asset is used is an explicit impairment indicator. The primary customer's transition to aluminum panels — which Line 4 cannot produce without $1.9 million in retooling — is precisely this type of change. The output decline corroborates the need for testing but is more properly classified under ASC 360-10-35-21(c) (significant decrease in market value) rather than as a physical deterioration indicator. Additionally, characterizing the customer transition as 'a separate business risk' that does not affect asset carrying value misunderstands impairment accounting. A change in customer demand that renders an asset's current configuration obsolete is a textbook ASC 360 triggering event. Both indicators independently support testing; collectively, they make the case overwhelming.";
items['P1-A-011'].ExplanationWrongD = "This recommendation makes two critical errors. First, it assumes an impairment test is triggered only when the carrying amount is known to exceed undiscounted cash flows — this reverses the ASC 360 framework. The standard requires testing when indicators exist; the test then compares carrying amount to undiscounted cash flows. The controller cannot conclude no test is required without first evaluating the indicators. Second, the recommendation suggests waiting until the customer actually transitions to aluminum panels in 14 months before testing. Under ASC 360-10-35-21, indicators are evaluated at each reporting date based on current circumstances. The customer's announced transition plan, the known incompatibility of Line 4 with aluminum production, and the required $1.9 million retooling investment are current indicators existing at the balance sheet date — they do not become indicators only when production actually stops. The controller should perform the impairment test now, and based on the undiscounted cash flows of $5,400,000 vs. carrying amount of $6,200,000, recognize an impairment loss.";
items['P1-A-011'].DifficultyScore = 4;
items['P1-A-011'].CognitiveLevel = "Evaluate";

console.log('Items 1-3 defined. Running replacements...');

const replacements = { 'P1-A-005': items['P1-A-005'], 'P1-A-008': items['P1-A-008'], 'P1-A-011': items['P1-A-011'], 'P1-A-012': items['P1-A-012'], 'P1-A-021': items['P1-A-021'], 'P1-A-025': items['P1-A-025'], 'P1-A-034': items['P1-A-034'] };
let changes = 0;
for (let i = 0; i < arr.length; i++) {
    const qid = arr[i].QuestionID;
    if (replacements[qid]) {
        console.log('Replacing ' + qid + ' old_CC=' + arr[i].CorrectChoice + ' new_CC=' + replacements[qid].CorrectChoice + ' old_Level=' + arr[i].CognitiveLevel + ' new_Level=' + replacements[qid].CognitiveLevel);
        arr[i] = replacements[qid];
        changes++;
    }
}
console.log('Total replacements: ' + changes);
const serialized = varDecl + JSON.stringify(arr, null, 8) + ';';
fs.writeFileSync('pack_a_corrected.js', serialized, 'utf8');
console.log('Done: ' + serialized.length + ' bytes');
