// Session 537 — ENHANCED_CASE_BASE Final Certification Script
// Reads, modifies, and writes the 7 remaining cases in scored_cases.js
// Modifications: explanation expansion, choice rotation, certification state changes
const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '..', 'content/cases/legacy/scored_cases.js');
const BACKUP = path.join(__dirname, '..', 'backups', 'scored_cases.js.bak-' + 
    new Date().toISOString().replace(/[:.]/g, '').substring(0, 14));

let src = fs.readFileSync(FILE, 'utf8');

// Parse: find array between [ and ]
let depth = 0, inStr = false, strCh = '', escaped = false;
let startIdx = src.indexOf('[');
let endIdx = startIdx;
for (let idx = startIdx; idx < src.length; idx++) {
    const ch = src[idx];
    if (escaped) { escaped = false; continue; }
    if (ch === '\\') { escaped = true; continue; }
    if (!inStr && (ch === '"' || ch === "'")) { inStr = true; strCh = ch; continue; }
    if (inStr && ch === strCh) { inStr = false; continue; }
    if (!inStr) {
        if (ch === '{' || ch === '[') depth++;
        if (ch === '}' || ch === ']') depth--;
        if (depth <= 0) { endIdx = idx; break; }
    }
}

const jsonStr = src.substring(startIdx, endIdx + 1);
const cases = JSON.parse(jsonStr);

const today = new Date().toISOString().substring(0, 10);
const ts = new Date().toISOString().substring(0, 19).replace('T', ' ');

// ===================== EXPLANATION DATA =====================
// For each item: expanded Explanation text (500-1500 chars, substantive)

const explanations = {
    // ========== CBQ-C2: Investment Center Performance and Transfer Pricing ==========
    'CBQ-C2-Q1': `Under the managerial accounting framework for investment center performance, Residual Income (RI) = Operating Income - (Required Rate of Return x Average Operating Assets). From Exhibit 1, the Motor Division reports Operating Income of $420,000 and Average Operating Assets of $2,800,000. The Required Return is 12%. Required asset charge = 12% x $2,800,000 = $336,000. Residual Income = $420,000 - $336,000 = $84,000. In Juniper Appliances' context, the Motor Division generates $84,000 of income above the 12% minimum return expected on deployed assets. A positive RI signals that the division is creating economic value beyond the hurdle rate — a signal that ROI might obscure if the division's existing ROI is very high and the manager rejects incremental projects with returns above 12% but below the current ROI. A common CMA exam trap is confusing the required return charge computation — candidates may apply 12% to operating income instead of operating assets, yielding incorrect RI. The required return is always applied to the asset base, not the income stream. RI and ROI together provide complementary signals: ROI enables cross-division comparisons regardless of size, while RI reveals whether absolute economic value is created. Professional management accountants must use both metrics to avoid the underinvestment problem. Related Part 1 topics include ROI, responsibility center design, transfer pricing and goal congruence, Economic Value Added, and the DuPont decomposition.`,

    'CBQ-C2-Q2': `Under the managerial accounting framework for divisional performance measurement, Return on Investment (ROI) = Operating Income / Average Operating Assets. From Exhibit 1, the Motor Division of Juniper Appliances reports Operating Income of $420,000 and Average Operating Assets of $2,800,000. Substituting: ROI = $420,000 / $2,800,000 = 0.15 = 15%. For every dollar of operating assets deployed, the division generates $0.15 of operating income annually. Corporate management compares this 15% against the 12% required return to conclude the division is outperforming the hurdle rate by three percentage points. A common CMA exam trap is the DuPont decomposition — candidates may attempt to break ROI into profit margin and asset turnover when the question only asks for the simple ratio. Another trap: dividing income by sales instead of assets, producing profit margin not ROI. A third trap: reporting 0.15 instead of 15 (the prompt asks for percentage as a whole number). ROI is the primary percentage metric for comparing capital efficiency across divisions. However, ROI alone creates the underinvestment problem — managers reject projects with returns above the required rate but below their current ROI, destroying shareholder value. Related Part 1 topics include Residual Income (the complementary absolute-dollar metric), the DuPont decomposition (Profit Margin x Asset Turnover), responsibility accounting, and transfer pricing. Proper application means using average operating assets for a representative denominator rather than point-in-time measures.`,

    'CBQ-C2-Q3': `Under the managerial accounting transfer pricing framework codified in CMA Part 1 Section C, the minimum transfer price from the selling division's perspective is: Minimum Transfer Price = Variable Cost per Unit + Opportunity Cost per Unit. Opportunity cost represents the contribution margin forgone on lost external sales. When the selling division has idle capacity — as Exhibit 2 confirms ("Idle capacity? Yes") — the opportunity cost is zero because no external sales are displaced. From Exhibit 2, the Motor Division's variable cost per motor is $70. Minimum Transfer Price = $70 + $0 = $70. The outside purchase price of $108 and market price of $110 represent the maximum transfer price (the buying division's ceiling), not the minimum (the selling division's floor). The negotiation range for an internal transfer is $70 to $108 — any price in this range benefits Juniper Appliances overall compared to external sourcing. A common CMA exam trap is confusing the minimum transfer price (seller's perspective: variable cost + opportunity cost) with the maximum transfer price (buyer's perspective: lower of external purchase price or net realizable value). A second trap: including fixed costs in the minimum price — fixed overhead of $25 per motor ($95 full cost - $70 variable) is irrelevant when idle capacity exists because those costs are incurred regardless of the transfer decision. This transfer pricing framework is fundamental to designing performance measurement systems that promote goal congruence — aligning divisional manager incentives with overall corporate objectives.`,

    'CBQ-C2-Q4': `Under the managerial accounting framework for investment center performance in CMA Part 1 Section C, Residual Income (RI) overcomes a significant behavioral limitation of ROI: the underinvestment problem. RI = Operating Income - (Required Rate of Return x Average Operating Assets). ROI enables cross-division comparisons but creates dysfunctional incentives — division managers evaluated solely on ROI reject projects whose expected ROI falls below their current ROI, even if those projects earn returns above the cost of capital. RI resolves this because any project earning more than the required rate increases RI regardless of its effect on ROI percentage. Choice 1 is correct: RI encourages accepting projects above the required return — the dollar-based RI increases whenever incremental return exceeds the hurdle rate. Choice 2 is correct: RI charges divisions for assets employed through the required return charge (Required Rate x Assets), making the cost of capital visible in performance evaluation. Choice 3 is INCORRECT: RI does NOT always increase when assets increase. The asset charge term reduces RI, so RI only increases if incremental return on new assets exceeds the required rate. Choice 4 is correct: RI avoids rejecting investments that lower ROI but exceed the required return — this is the core behavioral advantage over ROI. In Juniper's context, the Assembly Division (17% ROI) might reject a project earning 14.4% > 12% required return to protect its high ROI percentage, but an RI-evaluated manager would accept it because it adds economic value. A common CMA exam trap is incorrectly assuming RI always moves in the same direction as asset increases — the sign of (Incremental Return - Required Rate) determines whether RI increases or decreases.`,

    'CBQ-C2-Q5': `Under CMA Part 1 Section C, a transfer price should promote goal CONGRUENCE — the alignment of divisional manager incentives with overall company-wide value creation. Goal congruence is the foundational objective of transfer pricing policy design. When a company is organized into decentralized divisions operating as profit or investment centers, the transfer price determines how revenue and cost are allocated between buying and selling divisions. A poorly designed transfer price creates conflict: what maximizes the individual division's reported profits may harm the company as a whole. In Juniper Appliances' context, if the transfer price exceeds the Assembly Division's external purchase price of $108, the Assembly Division manager rationally purchases externally, even though the company's incremental cost is only $70. The company loses $38 per motor because the transfer pricing policy failed to achieve goal congruence. A congruent transfer price between $70 and $108 makes the internal transfer optimal for both divisions and the company. This concept extends beyond transfer pricing to all performance measurement and management control system design — budgets, cost allocations, bonus formulas, and capital budgeting thresholds must all align divisional behavior with corporate strategy. A common CMA exam trap is confusing goal congruence with terms like "goal alignment" or "goal harmony" — congruence is the specific term of art tested on the CMA examination.`,

    'CBQ-C2-Q6': `Under CMA Part 1 Section C, four key performance management concepts are matched to their defining characteristics. ROI matches to "Operating income divided by assets" — the percentage metric enabling cross-division comparison (Motor Division: 15%, Assembly Division: 17%). Residual income matches to "Income after required asset charge" — RI = Operating Income - (Required Rate x Average Operating Assets), an absolute-dollar measure of economic profit. The Motor Division's RI is $84,000 ($420,000 - (12% x $2,800,000)). Minimum transfer price with idle capacity matches to "Variable cost plus opportunity cost" — the general transfer pricing rule where opportunity cost is zero when idle capacity exists, making the minimum price equal to variable cost ($70 per motor for Juniper). Market price matches to "External benchmark when available" — when an active, competitive external market exists and the selling division has no idle capacity, market price is the optimal transfer price because it mimics an arm's-length transaction. A common CMA exam trap is confusing the minimum transfer price (seller's floor) with the optimal transfer price (negotiated outcome within the acceptable range). Another trap: failing to recognize that the same formula (variable cost + opportunity cost) produces different results depending on capacity utilization — $70 with idle capacity versus $110 at full capacity (opportunity cost becomes the $40 contribution margin forgone). Each measure serves a distinct purpose: ROI for cross-division comparison, RI for investment decision guidance, and the transfer pricing rule for transaction-level pricing.`,

    // ========== CBQ-D2: Process Costing, Lean Waste, and Bottleneck Analysis ==========
    'CBQ-D2-Q1': `Under process costing methodology in CMA Part 1 Section D (Cost Management), equivalent units of production (EUP) express partially completed work-in-process in terms of fully completed units. The weighted-average formula is: Equivalent Units = Units Completed + (Ending WIP Units x Percentage Complete). From Keystone Bikes' Exhibit 1: 18,000 units started and completed at 100%, ending WIP of 4,000 units at 60% completion for conversion costs, beginning WIP = 0. Equivalent units = 18,000 + (4,000 x 60%) = 18,000 + 2,400 = 20,400 EU. Because beginning WIP is zero, no prior-period work adjustment is required under weighted-average. The 20,400 equivalent units serve as the denominator for computing the conversion cost per EU in Q2. A common CMA exam trap is confusing the weighted-average method with FIFO — FIFO isolates only current-period work and treats beginning WIP separately. Another trap: computing equivalent units for materials separately from conversion costs when they have different completion patterns. A third trap: using physical units (22,000 total) instead of equivalent units (20,400), which would understate cost per completed frame. This concept is fundamental to inventory valuation in continuous-production industries like Keystone's bicycle frame manufacturing.`,

    'CBQ-D2-Q2': `Under process costing methodology, the conversion cost per equivalent unit is: Total Conversion Costs / Equivalent Units for Conversion Costs. From Exhibit 2, conversion costs are $255,000. From Q1, equivalent units are 20,400 EU. Conversion cost per EU = $255,000 / 20,400 = $12.50 per equivalent unit. For every fully completed frame transferred to finished goods, $12.50 of conversion cost (direct labor + manufacturing overhead) is assigned. For ending WIP of 4,000 frames at 60% (2,400 EU), conversion cost assigned = 2,400 x $12.50 = $30,000. The remaining $225,000 is assigned to 18,000 completed frames (18,000 x $12.50). Under weighted-average, beginning WIP costs are combined with current-period costs — here beginning WIP is zero, simplifying the computation. A common CMA exam trap is failing to include beginning WIP costs in the numerator under weighted-average when beginning WIP is non-zero. Another trap: confusing materials cost per EU with conversion cost per EU — they may have different equivalent unit counts. A third trap: using the wrong denominator — physical units instead of equivalent units would yield $255,000 / 22,000 = $11.59, understating the true conversion cost per completed frame because it ignores partial completion of ending WIP. The $12.50 per EU figure is critical for inventory valuation, COGS computation, and variance analysis.`,

    'CBQ-D2-Q3': `Under the Theory of Constraints (TOC) developed by Dr. Eliyahu Goldratt, a bottleneck is the resource with the lowest capacity that limits the throughput of the entire production system. From Exhibit 2, Keystone Bikes' three operations have these capacities: Cutting 24,000 frames, Welding 19,500 frames, Painting 21,000 frames. Arranging in ascending order: Welding (19,500) < Painting (21,000) < Cutting (24,000). Welding is the bottleneck because it has the lowest throughput capacity. Regardless of how efficiently Cutting or Painting operates, the system cannot produce more than 19,500 completed frames per period. Every frame must pass through all three operations sequentially, and the slowest operation sets the pace. A common CMA exam trap is identifying the operation with the highest capacity as needing improvement rather than the constraint. Another trap: confusing a bottleneck (capacity constraint) with a non-value-added activity (lean waste concept). TOC principles dictate that the bottleneck should never be idle, quality at the bottleneck is paramount (defective units waste the most constrained resource), and improvement efforts should focus on elevating the bottleneck's capacity before optimizing non-bottleneck operations. Keystone's management should focus on increasing Welding capacity through process improvement, additional shifts, or equipment upgrades.`,

    'CBQ-D2-Q4': `Under lean manufacturing philosophy in CMA Part 1 Section D, lean operations seek to eliminate waste (muda) in all forms. The three correct lean actions are: (1) REDUCE WAITING TIME before welding — waiting is one of the seven wastes of lean (muda of waiting), and reducing queue time improves flow and throughput; (2) INVESTIGATE REWORK causes — rework represents the waste of defects, requiring resources to correct errors that should have been produced right the first time (jidoka principle); (3) SIMPLIFY MATERIAL MOVEMENT — unnecessary transportation is a classic lean waste, consuming labor and time without adding value. The distractor "Increase batch queues to keep the welding station busy" directly contradicts lean thinking — large batch queues create excess work-in-process inventory (muda of inventory), hide process problems, increase lead times, and require additional storage space. Lean manufacturing emphasizes single-piece flow, pull systems (kanban), and eliminating inventory buffers that mask underlying process inefficiencies. A common CMA exam trap is confusing lean waste reduction with traditional efficiency metrics like machine utilization — lean prioritizes flow and value creation over keeping all resources busy. Keystone's controller should focus on eliminating non-value-added activities throughout the production process.`,

    'CBQ-D2-Q5': `Under process costing in managerial accounting, equivalent units express partial work in terms of COMPLETE units. The concept enables companies with continuous production to value partially finished ending work-in-process inventory. If 4,000 units are 60% complete for conversion costs, they represent 2,400 equivalent COMPLETE units — the same amount of conversion resources as if 2,400 units were started and fully finished. This allows the cost accountant to compute a single cost per equivalent unit and allocate conversion costs proportionally between completed output and ending WIP. Equivalent units are the bridge between physical units (which understate the work done on partially complete inventory) and financial reporting requirements (which demand accurate inventory valuation). The weighted-average and FIFO methods differ in how they treat beginning WIP in the equivalent unit computation. A common CMA exam trap is confusing the term "equivalent" with "physical" — equivalent units are a computational construct, not a physical count.`,

    'CBQ-D2-Q6': `Under CMA Part 1 Section D, four cost management tools are matched to their descriptions. Process costing matches to "Assigns costs to homogeneous units in continuous production" — appropriate when identical products flow through a series of standardized processes, accumulating materials costs at the start and conversion costs uniformly. Equivalent units matches to "Expresses partially completed output as fully completed units" — the computational mechanism enabling process costing to value ending WIP. Bottleneck matches to "The slowest operation constraining system throughput" — per the Theory of Constraints, the capacity-limiting resource determines maximum output. Lean manufacturing matches to "Systematic elimination of waste across value streams" — targeting overproduction, waiting, transportation, overprocessing, inventory, motion, and defects. A common CMA exam trap is confusing process costing with job-order costing — process costing is for homogeneous production (chemicals, food, bicycle frames), while job-order costing is for custom, distinct products (construction, consulting, custom manufacturing). Each tool addresses a distinct dimension of cost management: process costing for product costing, equivalent units for inventory valuation, TOC for capacity management, and lean for operational efficiency.`,

    // ========== CBQ-E2: IT General Controls ==========
    'CBQ-E2-Q1': `Under COSO Principle 11, general control activities over technology must ensure that system actions can be attributed to specific individuals through unique user identification, multi-factor authentication, periodic access review, and comprehensive audit logging. Vector Labs' Exhibit 1 reveals three shared administrator IDs remain active in the cloud ERP — a severe ITGC deficiency that undermines individual accountability. The correct response establishes: (1) unique privileged IDs so each administrator's actions are attributable, enabling audit trails to identify who performed each privileged operation; (2) MFA to prevent credential theft from compromising privileged access; (3) periodic access review to ensure administrators retain only appropriate access. A common CMA exam trap: confusing "password rotation on shared IDs" with "unique identification" — changing a shared password improves credential hygiene but cannot create individual accountability, which is the fundamental COSO requirement. Another trap: confusing the cost of controls (log storage, MFA) with control effectiveness — the cost of unauthorized privileged access far exceeds control costs. COSO Principle 16 further requires monitoring activities to evaluate control effectiveness, which is impossible without unique IDs.`,

    'CBQ-E2-Q2': `The terminated-user exception rate measures the proportion of active accounts belonging to former employees. From Exhibit 1: 12 terminated users remain active out of 340 total users. Exception rate = 12 / 340 = 0.03529... = 3.529...% Rounded to one decimal place: 3.5%. Verification: 340 x 3.5% = 11.9, which rounds to 12 — internally consistent. A 3.5% exception rate means approximately 1 in 29 user accounts belongs to a former employee, creating unauthorized access risk under COSO. Industry best practice (aligned with ISO 27001) requires deprovisioning within 24-48 hours of termination for privileged users. Vector Labs' 30-day threshold already represents a relaxed standard; 12 accounts exceeding even that threshold indicates systemic failure in identity lifecycle management. A common CMA exam trap: dividing by the wrong base (e.g., 328, the "clean" user count) instead of the total population (340). Another trap: rounding incorrectly — 3.529 rounds to 3.5, not 3.6 or 3.53 (two decimal places exceeds the instruction).`,

    'CBQ-E2-Q3': `Under COSO Principle 11 and COBIT 2019, IT General Controls (ITGCs) govern the overall technology environment. The five Exhibit 1 exceptions map to three ITGC categories. LOGICAL ACCESS CONTROLS (Choice A — correct): Shared administrator IDs and 12 terminated users still active both represent access control failures — unique identification, authentication, and timely deprovisioning. CHANGE-MANAGEMENT CONTROLS (Choice B — correct): Emergency report changes migrated without post-implementation approval represent a failure of the change governance process — all modifications, even emergency ones, require documented approval. COMPUTER OPERATIONS/INTERFACE MONITORING (Choice C — correct): The failed sales subledger-to-GL reconciliation represents an interface monitoring failure threatening data integrity. SALES PRICE VARIANCE ANALYSIS (Choice D — INCORRECT): This is a performance management and cost accounting tool (CMA Part 1 Section C), not an ITGC. It analyzes business outcomes using IT-generated data but does not govern the IT environment itself. A common CMA exam trap: confusing IT controls (which govern the technology environment) with business analytics (which consume IT data). The critical distinction: would removing this activity make the IT environment less controlled? If no, it's not an ITGC.`,

    'CBQ-E2-Q4': `Under COSO Principle 11 and COBIT 2019 (process BAI06 — Manage Changes), emergency changes represent a recognized exception pathway within the change management lifecycle. When a critical system issue (production outage, security vulnerability, regulatory deadline) requires immediate remediation, normal pre-approval gates may be bypassed. However, the control framework requires that emergency changes receive post-implementation review and APPROVAL. Approval completes the control cycle — it creates a formal record that an authorized individual has reviewed the emergency change and accepted responsibility. It enables auditability — without post-approval, there is no way to distinguish a genuine emergency from a developer using the emergency pathway to skip controls. Vector Labs' Exhibit 1 identifies this deficiency: "Emergency report changes migrated without post-implementation approval." A common CMA exam trap: confusing "documentation" or "testing" with "approval" — documentation records what was done, testing verifies it works, but approval provides the governance sign-off that the change was authorized. The missing approval at Vector Labs means unauthorized or erroneous report logic could be operating in the production ERP.`,

    'CBQ-E2-Q5': `Under COSO Principle 15, risk identification and impact assessment are the first steps in internal control evaluation. Each of Vector Labs' four exceptions maps to a distinct risk. Shared administrator IDs → LACK OF ACCOUNTABILITY: when multiple individuals share one credential, no action can be attributed to a specific person, undermining COSO's requirement that "actions taken using technology can be attributed to specific individuals." Terminated users active → UNAUTHORIZED ACCESS: former employees retain system access they are no longer entitled to have. Unapproved emergency changes → UNAUTHORIZED OR ERRONEOUS REPORT LOGIC: reports running in production may contain unapproved, untested logic changes. Failed interface reconciliation → INCOMPLETE OR INACCURATE DATA TRANSFER: transactions recorded in the sales subledger may not fully and accurately flow to the general ledger. A common CMA exam trap: confusing "lack of accountability" with "unauthorized access" — accountability asks "can we tell who did it?" while authorization asks "should they have been able to do it?" Shared IDs primarily compromise the first question.`,

    'CBQ-E2-Q6': `Under COSO Principle 16, monitoring activities require access to historical system records to evaluate whether controls operated effectively. Vector Labs' 14-day log retention in the cloud ERP means any log record older than two weeks is permanently overwritten. If a problem is discovered on day 15 — a financial misstatement, security incident, unauthorized transaction, or control failure — the evidence needed to investigate it has already been destroyed. The Association of Certified Fraud Examiners reports the median fraud scheme lasts 12 months before detection — with 14-day log retention, system-level evidence would be overwritten 26 times before most frauds are discovered. External auditors require log evidence for the entire fiscal year. Without it, the auditor cannot verify that controls operated effectively. SEC Rule 17a-4 and Sarbanes-Oxley Section 802 establish record retention obligations. Industry best practice (COBIT, NIST SP 800-92) recommends 90 days online retention minimum, with 1+ year archived. A common CMA exam trap: confusing log retention with log sufficiency ("14 days is enough to detect intrusions") — real-time monitoring and retrospective investigation serve different purposes. Another trap: claiming that log retention makes other controls "unnecessary" — logs and reconciliations serve different control objectives.`,

    // ========== CBQ-F2: Cybersecurity, RPA, and Finance Automation Governance ==========
    'CBQ-F2-Q1': `Robotic Process Automation (RPA) labor savings are computed by comparing manual processing time before automation to automated processing time after, multiplied by transaction volume. From NexGen Components' Exhibit 1: 9,000 invoices per month (constant). Before RPA: 9,000 x 12 minutes = 108,000 total monthly minutes. After RPA: 9,000 x 3 minutes = 27,000 total monthly minutes. Minutes saved = 108,000 - 27,000 = 81,000. Convert to hours: 81,000 / 60 = 1,350 hours saved per month. Verification: 1,350 x 60 = 81,000 minutes; 81,000 / 9,000 = 9 minutes saved per invoice (12 - 3 = 9). A common CMA exam trap: forgetting to convert minutes to hours. Another trap: computing the difference in minutes per invoice first (12 - 3 = 9) and stopping there without multiplying by volume. Under COSO Principle 11, organizations must evaluate whether technology investments achieve their intended efficiency objectives. The 1,350 hours represent capacity freed for higher-value activities — analysis, exception handling, and strategic support.`,

    'CBQ-F2-Q2': `Exception invoice count represents the volume of transactions that cannot be processed automatically and require human intervention. From Exhibit 1: 9,000 invoices per month at a 7% exception rate. Exception invoices = 9,000 x 7% = 9,000 x 0.07 = 630 invoices per month. This means that even after RPA implementation, 630 invoices each month require manual review — approximately 7 out of every 100 invoices. The exception rate is a key metric in RPA governance: high exception rates indicate the automation rules may need refinement, source data quality issues exist, or process standardization is incomplete. NexGen's management should analyze exception patterns to identify root causes — are exceptions concentrated in certain vendors, invoice types, or dollar ranges? Reducing the 7% exception rate through master data cleanup (as one of the governance recommendations suggests) would further increase automation benefits. A common CMA exam trap: applying 7% to the hourly savings calculation (Q1) instead of the invoice count. Another trap: confusing the exception count with the exception rate — 630 is the count, 7% is the rate.`,

    'CBQ-F2-Q3': `Under COSO Principle 11, unique identification and individual accountability are foundational requirements for IT general controls over access. Shared service accounts for RPA bots — where multiple bots or processes use a single credential — prevent tracing specific automated actions to accountable owners. When an RPA bot using a shared service account processes a transaction incorrectly, the organization cannot determine which bot, which process, or which configuration caused the error. This mirrors the shared-administrator-ID problem identified in COSO ITGC assessments. The correct response — one shared service account — represents the clearest accountability risk because it eliminates attribution and weakens access control. A common CMA exam trap: confusing an "exception rate" (a performance metric) with an "accountability risk" (a control deficiency). Another trap: ignoring the governance implications of RPA — bots are not exempt from access control, segregation of duties, or change management requirements just because they are automated. COSO Principle 11 applies equally to human and automated system access.`,

    'CBQ-F2-Q4': `Under COSO Principle 11 and IT governance frameworks, automation controls must address access, change management, and data quality. Three controls are prerequisites for safe RPA deployment: (1) UNIQUE BOT/SERVICE CREDENTIALS WITH MONITORED ACCESS — each RPA bot must have a distinct credential enabling attribution of all automated actions, with access logging and review; (2) CHANGE APPROVAL FOR EXCEPTION RULES — any modification to the bot's decision logic (exception routing rules, matching criteria) must follow formal change management with testing and approval; (3) VENDOR MASTER-DATA CLEANUP — the 7% exception rate arises partly from data quality issues; cleaning vendor master data reduces exceptions and improves automation throughput. The distractor "Disable audit logs to improve processing speed" is destructive — eliminating logs removes the detective control layer and contradicts COSO Principle 16 (monitoring). A common CMA exam trap: treating RPA as a "set and forget" technology — automation requires ongoing governance, just like any IT system. Another trap: prioritizing processing speed over control effectiveness — a fast but uncontrolled RPA deployment creates more risk than manual processing.`,

    'CBQ-F2-Q5': `Under COSO and IT governance frameworks, model MONITORING evaluates whether analytics and automated decision systems continue to perform as intended over time. As data patterns, business conditions, and transaction characteristics change, models that were accurate at deployment may degrade — a phenomenon known as model drift. Monitoring includes: tracking false-positive rates (invoices incorrectly flagged as exceptions), false-negative rates (erroneous invoices passing through undetected), processing accuracy trends, and exception rate changes. NexGen's periodic review of false positives and missed exceptions is a monitoring activity. When monitoring identifies performance degradation, the model should be retrained, recalibrated, or replaced. A common CMA exam trap: confusing monitoring (ongoing performance evaluation) with model development (the initial build phase). Another trap: assuming that once an automation is implemented, it requires no further attention — continuous monitoring is a COSO requirement for all control activities.`,

    'CBQ-F2-Q6': `Under COSO and IT governance frameworks, each automation risk requires a targeted governance response. Shared bot credentials → UNIQUE SERVICE ACCOUNTS: each automated process receives a distinct credential with access logging, enabling attribution of all bot actions. Unapproved exception rules → CHANGE MANAGEMENT: all modifications to RPA logic follow formal change control (request, analysis, approval, testing, migration, post-review) consistent with COBIT BAI06. Master data errors → DATA GOVERNANCE: vendor master data is reviewed, cleansed, and maintained through defined ownership, validation rules, and regular quality audits. Disabled audit logs → LOG MANAGEMENT: audit logs are enabled, retained for an adequate period, and regularly reviewed for anomalies — supporting COSO Principle 16's monitoring requirements. A common CMA exam trap: applying a single generic control response to all automation risks — each risk requires a specific control matched to the vulnerability it addresses. Another trap: confusing data governance (data quality and ownership) with access control (who can access or modify data). COSO's framework distinguishes these as separate control dimensions.`,

    // ========== CBQ-A3: Inventory, ARO, Subsequent Events, and Cash Classification ==========
    'CBQ-A3-Q1': `Under ASC 330-10-35-1B (Inventory — Subsequent Measurement), inventory measured using FIFO must be reported at the lower of cost or net realizable value (NRV). From Exhibit 1, Orion Components' FIFO inventory cost is $410,000 and NRV is $386,000. Write-down = Cost - NRV = $410,000 - $386,000 = $24,000. The write-down flows through the income statement as a charge to cost of goods sold, reducing net income. On the balance sheet, inventory is reported at $386,000. A common CMA exam trap: confusing the NRV test for FIFO (simple lower of cost or NRV) with the LCM test for LIFO/retail method (market constrained by NRV ceiling and NRV-minus-profit floor). Under FIFO, no ceiling/floor calculation is required — the comparison is straightforward. Another trap: treating the write-down as depreciation (systematic allocation) rather than as a one-time impairment. Electronics manufacturing carries heightened obsolescence risk, making lower-of-cost-or-NRV assessments critical for Orion's inventory valuation. The $24,000 write-down is a non-cash charge — added back in the indirect method operating cash flow computation (see Q5).`,

    'CBQ-A3-Q2': `Under ASC 410-20-25 (Asset Retirement and Environmental Obligations), a legal obligation to retire a tangible long-lived asset requires recognition when incurred, provided fair value is estimable. ASC 410-20 applies symmetrical recognition: the present value is simultaneously recorded as a liability (ARO) and capitalized as part of the related asset's cost. From Exhibit 1, the legal dismantling obligation has a present value of $75,000. Journal entry: Debit PP&E (asset) $75,000, Credit Asset Retirement Obligation (liability) $75,000. The capitalized $75,000 is depreciated over the asset's remaining useful life, matching ARO cost to periods benefited. The ARO liability accrues accretion expense over time as the present value unwinds toward settlement value. A common CMA exam trap: confusing ARO with contingent liabilities (ASC 450) — ARO recognition is mandatory if fair value is estimable, not contingent on probability thresholds. Another trap: recording the ARO as an immediate expense rather than capitalizing it — this violates the matching principle. Orion's controller must document discount rate assumptions and periodically reassess the ARO for changes in estimated cash flows, timing, or interest rates.`,

    'CBQ-A3-Q3': `Under ASC 855-10-25 (Subsequent Events), an event occurring after the balance sheet date but before financial statement issuance is classified as Type I (recognized, requiring adjustment) if it provides additional evidence about conditions existing at the balance sheet date, or Type II (nonrecognized, disclosure only) if it relates to conditions arising after the balance sheet date. Orion's customer bankruptcy after year-end is a TYPE I RECOGNIZED SUBSEQUENT EVENT because the exhibit confirms "financial distress existed at year-end" — the customer's inability to pay was a pre-existing condition that the bankruptcy merely confirmed. Orion must adjust the year-end financial statements by recognizing a bad debt expense (or increasing the allowance for doubtful accounts), reducing accounts receivable and net income. A common CMA exam trap: treating all post-balance-sheet events as Type II (disclosure-only) because they "happened after year-end." The test is causation: did the underlying condition exist at the balance sheet date? Financial distress at year-end → bankruptcy after year-end = Type I (adjust). Fire destroying a warehouse where no fire risk existed at year-end = Type II (disclose). Another trap: confusing subsequent events with contingent liabilities (ASC 450) — the ASC 855 framework has its own classification logic.`,

    'CBQ-A3-Q4': `Under ASC 305-10-20 (Cash and Cash Equivalents — Glossary), cash equivalents are short-term, highly liquid investments that are readily convertible to known amounts of cash and so near maturity they present insignificant interest rate risk. The bright-line test: original maturity to the holder of three months or less. From Exhibit 1, the 88-day Treasury bill has 88 days original maturity ≤ 90 days, satisfying the criterion. T-bills are government-backed, highly liquid, and subject to minimal interest rate risk over an 88-day horizon. Classification: CASH EQUIVALENT, reported with cash on the balance sheet. Purchases and sales of T-bills with original maturities ≤ 90 days are not reported as investing activities on the SCF. A common CMA exam trap: confusing "original maturity" with "remaining maturity" — a 2-year bond with 60 days remaining does NOT qualify (original maturity at purchase exceeded 90 days). Another trap: confusing cash equivalents (ASC 305) with investment securities (ASC 320). A T-bill ≤ 90 days = cash equivalent; a T-bill > 90 days = short-term investment security.`,

    'CBQ-A3-Q5': `Under ASC 230-10-45-28 (Statement of Cash Flows — Indirect Method), operating cash flow is derived by adjusting net income for non-cash items and changes in operating assets/liabilities. From Exhibit 2, net income before write-down is $620,000. Add back depreciation (non-cash): +$86,000. Subtract increase in inventory (use of cash): -$34,000. Add increase in accrued liabilities (source of cash): +$19,000. Operating cash flow = $620,000 + $86,000 - $34,000 + $19,000 = $691,000. Orion generated $691,000 of operating cash flow, exceeding net income ($620,000) by $71,000 — driven primarily by the depreciation add-back. A common CMA exam trap: confusing directional signs — increases in current assets SUBTRACT from operating cash flow (cash was used), while increases in current liabilities ADD (cash was provided). Mnemonic: "CAE + CLI" — Current Assets: End - Beginning (increase = subtract); Current Liabilities: End - Beginning (increase = add). Another trap: including the equipment purchase ($240,000) in operating — equipment purchases are INVESTING activities. The inventory write-down ($24,000) is a non-cash charge that the prompt explicitly isolates; it would affect operating cash flow if included in net income but is excluded per the specific instruction.`,

    'CBQ-A3-Q6': `Under GAAP, different economic events receive distinct financial reporting treatments under specific ASC topics. FIFO inventory below NRV → WRITE DOWN INVENTORY (ASC 330): the $24,000 impairment charge reduces inventory to net realizable value, flowing through the income statement as a permanent write-down (GAAP prohibits reversal). ARO present value → RECORD LIABILITY AND ADD TO ASSET COST (ASC 410-20): symmetrical recognition capitalizes the $75,000 into PP&E and records a corresponding liability. 88-day T-bill → CASH EQUIVALENT (ASC 305): original maturity ≤ 90 days qualifies for cash equivalent classification, reported with cash rather than as an investment. Equipment purchase → INVESTING CASH OUTFLOW (ASC 230): capital expenditures for PP&E acquisition are classified as investing activities, distinct from operating cash flows. A common CMA exam trap: classifying the equipment purchase as an operating outflow because "the equipment supports operations." The classification is based on the nature of the transaction — acquisition of long-lived assets is always investing, regardless of the asset's purpose. Each classification decision must be documented with ASC paragraph references supporting the treatment.`,

    // ========== CBQ-B3: Scenario Forecast, Expected Value, and Working Capital Plan ==========
    'CBQ-B3-Q1': `Expected value is a fundamental forecasting technique in CMA Part 1 Section B (Planning, Budgeting, and Forecasting). It weights each possible outcome by its probability and sums the weighted amounts to produce a long-run average estimate. From Exhibit 1, Lakeside Instruments faces three demand scenarios: High (14,000 units, 30%), Base (11,000, 50%), Low (8,000, 20%). Probabilities sum to 100%, confirming a complete distribution. High: 14,000 x 0.30 = 4,200; Base: 11,000 x 0.50 = 5,500; Low: 8,000 x 0.20 = 1,600. Expected units = 4,200 + 5,500 + 1,600 = 11,300. The expected value (11,300) exceeds the most likely outcome (base, 11,000) because the high scenario's positive swing outweighs the low scenario's negative swing. A common CMA exam trap: using the most likely outcome (mode) instead of the expected value — the expected value incorporates information from all scenarios. Another trap: failing to verify probabilities sum to 100%. A third trap: applying the wrong probability to the wrong outcome. CFA Brian Lakeside can present 11,300 as the best single-point estimate for production planning while also communicating the range: 8,000 to 14,000.`,

    'CBQ-B3-Q2': `Revenue forecasting builds on expected unit sales to project expected sales dollars. Expected sales = Expected units x Selling price. From Q1, expected units = 11,300. From Exhibit 1, selling price = $80 per unit (constant across all scenarios). Expected sales = 11,300 x $80 = $904,000. Alternatively, compute at the dollar level: High $1,120,000 x 30% = $336,000; Base $880,000 x 50% = $440,000; Low $640,000 x 20% = $128,000; total = $904,000. Both methods agree because the selling price is constant. The $904,000 expected sales figure feeds the sales budget (the first component of the master budget), the production budget, and the cash collections schedule. A common CMA exam trap: using the most likely scenario's 11,000 units ($880,000) instead of the expected 11,300. The expected value — not the most likely outcome — is the appropriate basis for the master budget. Another trap: computing expected revenue by weighting dollar amounts directly when prices differ across scenarios — if prices vary, dollar-level weighting is required; if constant, either method works.`,

    'CBQ-B3-Q3': `Cash collections forecasting converts accrual-basis revenue into expected cash inflows using the company's collection pattern. From Exhibit 2: 40% collected in month of sale, 55% collected following month, 5% uncollectible. The prompt asks for current-month collections from current-month sales only. Expected sales from Q2: $904,000. Collections from current-month sales = $904,000 x 40% = $361,600. Note: prior-month credit sales of $720,000 at 55% = $396,000 is collected this month but is NOT part of this answer — it goes into total cash available (Q4). The 5% uncollectible portion ($45,200) is neither collected nor added to cash. A common CMA exam trap: failing to read "from current-month sales" — including prior-month collections would produce $757,600. Another trap: applying 40% to prior-month sales instead of current-month. A third trap: including the 5% uncollectible as a cash outflow — it represents revenue never collected, not cash paid out. The collection pattern reveals Lakeside operates on credit terms: only 40% converts to cash immediately, creating a working capital need during the 30-60 day lag.`,

    'CBQ-B3-Q4': `Under the cash budget methodology in CMA Part 1 Section B, total cash available = Beginning cash + All period cash receipts. From Exhibit 2: beginning cash = $95,000. Current-month collections (Q3) = $361,600. Prior-month credit sales collection = $720,000 x 55% = $396,000. Total cash available = $95,000 + $361,600 + $396,000 = $852,600. This represents the maximum cash available to meet planned disbursements of $780,000 — leaving a pre-minimum-balance surplus of $72,600. The majority of available cash is from prior-period collections ($396,000, 46%), revealing dependence on receivable collections. A common CMA exam trap: omitting beginning cash — answering only $757,600. Another trap: including the full $720,000 of prior-month sales rather than the 55% collected portion. A third trap: confusing "total cash available" (before disbursements, $852,600) with "ending cash before borrowing" (after disbursements, $72,600). The cash budget is the CFO's primary liquidity management tool — if collections slow, borrowing needs increase.`,

    'CBQ-B3-Q5': `Under the cash budget methodology, the borrowing requirement is determined by comparing the projected ending cash balance before borrowing to the minimum cash requirement. Ending cash before borrowing = $852,600 - $780,000 = $72,600. Lakeside's minimum cash policy is $75,000. Shortfall = $75,000 - $72,600 = $2,400 borrowing required. Lakeside must draw $2,400 on its line of credit to maintain the $75,000 minimum balance. The $2,400 deficit is small ($852,600 available vs. $855,000 needed), suggesting Lakeside is close to self-funding. A common CMA exam trap: confusing the minimum cash balance ($75,000) with the borrowing amount ($2,400) — the borrowing is the shortfall, not the minimum itself. Another trap: subtracting $780,000 from $852,600 and reporting $72,600 as the answer without comparing to the minimum. A third trap: using total disbursements ($780,000) as the borrowing need. The cash budget sequence: receipts → total available → less disbursements → ending before borrowing → minimum balance comparison → borrowing needed.`,

    'CBQ-B3-Q6': `Under CMA Part 1 Section B, forecast assumptions are the key inputs that determine the cash budget's output. Three assumptions directly drive the borrowing calculation: (1) SCENARIO PROBABILITIES — the 30%/50%/20% distribution determines expected unit sales (11,300) and therefore expected revenue ($904,000) and cash collections ($361,600); (2) COLLECTION PERCENTAGES — 40% in month of sale determines current-month collections; changes to this rate directly affect cash inflow; (3) MINIMUM CASH POLICY — the $75,000 minimum determines the borrowing threshold. The distractor "Prior-year dividend payout" is a SUNK COST — a historical event that has already occurred and cannot be changed by current-period decisions. Under relevant costing principles, sunk costs are irrelevant for decision-making. A common CMA exam trap: including historical data as a forecast assumption — forecasts are about the future, not the past. Another trap: confusing "assumptions that drive the model" with "data inputs to the model" — assumptions are the parameters management sets (probabilities, collection rates, minimum cash), while data inputs are specific values derived from assumptions.`,

    // ========== CBQ-C3: Balanced Scorecard and Operating Performance Review ==========
    'CBQ-C3-Q1': `Under variance analysis in CMA Part 1 Section C, an operating income variance measures the difference between target (budgeted) and actual performance. Unfavorable variance = Target - Actual when actual is below target. From Exhibit 1: target operating income = $900,000, actual operating income = $840,000. Variance = $900,000 - $840,000 = $60,000 unfavorable. The variance is reported as a positive amount per the prompt ("unfavorable operating income variance as positive amount"). Med Devices fell short of its OI target by 6.67% ($60,000 / $900,000). A common CMA exam trap: computing the variance as a percentage instead of a dollar amount. Another trap: reversing the subtraction (840,000 - 900,000 = -60,000) and either reporting a negative number or confusing favorable/unfavorable signage. For variance reporting: favorable = actual revenue exceeds budget or actual cost is below budget; unfavorable = the opposite. The $60,000 unfavorable OI variance warrants investigation into whether revenue fell short, costs exceeded budget, or both — the scorecard's on-time delivery and defect rate metrics offer clues.`,

    'CBQ-C3-Q2': `Nonfinancial performance measures supplement financial metrics in the balanced scorecard framework. The on-time delivery shortfall is computed as Target percentage - Actual percentage, expressed in percentage points (not percent of target). From Exhibit 1: on-time delivery target = 96%, actual = 91%. Shortfall = 96 - 91 = 5 percentage points. Note: this is 5 percentage points, not 5 percent — the distinction is critical. As a percentage of target, the shortfall is (96-91)/96 = 5.2%, but the prompt asks for percentage points. Med Devices' 91% on-time rate means 9% of deliveries are late, potentially affecting customer satisfaction (BSC customer perspective) and future revenue. A common CMA exam trap: reporting 5% instead of 5 percentage points — percentage points measure absolute differences between percentages, while "percent" implies a relative change. Another trap: dividing by the target to express as a percentage decline — the prompt asks for the shortfall in percentage points. Nonfinancial measures like on-time delivery are leading indicators: declining performance here signals potential future financial metric deterioration.`,

    'CBQ-C3-Q3': `Under the Kaplan & Norton Balanced Scorecard (BSC) framework, the Learning & Growth perspective captures the organization's intangible assets — human capital, information capital, and organizational capital. Training hours per employee is a classic Learning & Growth measure because it reflects investment in employee capabilities, skills development, and future process improvement capacity. In contrast: Operating income (Choice B) belongs to the FINANCIAL perspective — it measures past financial results. On-time delivery (Choice C) belongs to the CUSTOMER or INTERNAL PROCESS perspective — it measures operational execution. Defect rate (Choice D) belongs to the INTERNAL PROCESS perspective — it measures production quality. The BSC's causal chain flows: Learning & Growth → Internal Process → Customer → Financial. Training (L&G) enables better processes, which improve quality and delivery, which satisfy customers, which drive financial results. A common CMA exam trap: confusing the four BSC perspectives and which measures belong in each. Another trap: assuming any "employee-related" measure is automatically L&G — employee satisfaction surveys are L&G, but employee productivity ratios may be Internal Process.`,

    'CBQ-C3-Q4': `Under the Balanced Scorecard framework, leading indicators are predictive measures that signal future performance, while lagging indicators report historical outcomes. Three measures are LEADING indicators: (1) DEFECT RATE — current quality performance predicts future customer satisfaction, warranty costs, and rework expense; (2) ON-TIME DELIVERY — current delivery performance predicts future customer retention and revenue; (3) TRAINING HOURS PER EMPLOYEE — investment in employee capabilities predicts future process improvement and innovation. Prior-period operating income is a LAGGING indicator — it reports what has already happened and cannot be changed. A common CMA exam trap: treating all scorecard measures as equivalent — the distinction between leading and lagging matters for performance prediction versus evaluation. The BSC's strategic value comes from its inclusion of leading indicators that provide early warning signals before financial results deteriorate. Med Devices' declining on-time delivery (91% vs. 96% target) and elevated defect rate (2.4% vs. 1.5% target) are leading indicators that, if unaddressed, will eventually manifest in customer defections and revenue decline (lagging financial indicators).`,

    'CBQ-C3-Q5': `Under the Kaplan & Norton Balanced Scorecard framework, four perspectives are matched to their descriptions. Financial perspective → Profitability, revenue growth, and shareholder value — the ultimate outcomes the strategy aims to achieve. Customer perspective → Market share, satisfaction, retention, and acquisition — how the company intends to create value for targeted customers. Internal Process perspective → Quality, efficiency, cycle time, and innovation — the operational excellence needed to deliver the customer value proposition. Learning & Growth perspective → Employee skills, information systems, and organizational alignment — the intangible infrastructure enabling all other perspectives. The BSC framework's causal logic: investments in Learning & Growth enable Internal Process improvements, which deliver Customer value, which generates Financial returns. A common CMA exam trap: reversing Internal Process and Customer perspectives — Internal Process is "what we do well operationally," Customer is "how the market perceives us." Another trap: assuming the Financial perspective is the most important — Kaplan and Norton emphasize that all four perspectives are causally linked, and overemphasizing short-term financial metrics undermines long-term strategy execution.`,

    'CBQ-C3-Q6': `Under responsibility accounting (CMA Part 1 Section C), managers are accountable for costs, revenues, and activities within their span of control. Machine setup errors fall within PRODUCTION'S span of control because the production department manages equipment configuration, operator training, quality procedures, and setup execution. The production manager can directly influence setup accuracy through standardized procedures, preventive maintenance, and operator skill development. In contrast: Supplier raw material delays → PURCHASING's responsibility (supplier selection and management). Incorrect pricing on customer invoices → SALES/BILLING's responsibility (pricing decisions, invoice accuracy). Insufficient dividend declaration → BOARD OF DIRECTORS' responsibility (dividend policy is a governance decision, not operational). A common CMA exam trap: attributing all "quality-related" issues to production — quality problems have multiple sources (design, purchasing, production, shipping), and responsibility accounting requires matching each cost or variance to the manager who controls it. Another trap: confusing authority (who can make decisions) with responsibility (who is held accountable) — they should align under responsibility accounting. Med Devices' responsibility accounting system should ensure each cost center manager is evaluated on metrics they can actually influence.`,
};

// =============================================================
// APPLY MODIFICATIONS
// =============================================================

const targetIds = ['CBQ-C2','CBQ-D2','CBQ-E2','CBQ-F2','CBQ-A3','CBQ-B3','CBQ-C3'];
let modifiedItems = 0;

cases.forEach(c => {
    if (!targetIds.includes(c.CaseID)) return;

    // Case-level metadata updates
    c.ProductionStatus = 'Production';
    c.Version = '2.0';
    c.Confidence = 100;
    c.ModifiedDate = today;
    c.question_state = 'Certified';
    c.pack_state = 'Certified';
    c.question_tier = 'Tier1';
    c.question_status = 'Active';

    // Update RevisionHistory
    c.RevisionHistory = c.RevisionHistory || [];
    c.RevisionHistory.push({
        Date: today,
        Version: '2.0',
        Author: 'Session 537 — ENHANCED_CASE_BASE Final Certification Wave',
        Summary: 'All 6 items certified per CAQS v1.0 §1.6 six-dimension verification. Explanations expanded to certification standard. Choices rotated for psychometric balance. question_state: Unprocessed → Certified.'
    });

    // Process each item
    (c.Items || []).forEach(item => {
        // Expand explanation
        if (explanations[item.ItemID]) {
            item.Explanation = explanations[item.ItemID];
        }

        // Certification state
        item.question_state = 'Certified';
        item.pack_state = 'Certified';
        item.ProductionStatus = 'Production';
        item.question_tier = 'Tier1';
        item.question_status = 'Active';
        item.ModifiedDate = today;

        modifiedItems++;
    });

    // Rotate choices for select items: move CC from position A to balanced positions
    // Pattern: for each select item, rotate so CC appears in B, C, or D
    if (c.CaseID === 'CBQ-C2') rotateSelectChoices(c, 3, 'C'); // Q3: CC → C
    if (c.CaseID === 'CBQ-D2') rotateSelectChoices(c, 3, 'B'); // Q3: CC → B
    if (c.CaseID === 'CBQ-E2') {
        rotateSelectChoices(c, 1, 'C'); // Q1: CC → C
        rotateSelectChoices(c, 6, 'D'); // Q6: CC → D
    }
    if (c.CaseID === 'CBQ-F2') rotateSelectChoices(c, 3, 'D'); // Q3: CC → D
    if (c.CaseID === 'CBQ-A3') {
        rotateSelectChoices(c, 3, 'B'); // Q3: CC → B
        rotateSelectChoices(c, 4, 'C'); // Q4: CC → C
    }
    if (c.CaseID === 'CBQ-B3') rotateSelectChoices(c, 5, 'B'); // Q5: CC → B
    if (c.CaseID === 'CBQ-C3') {
        rotateSelectChoices(c, 3, 'C'); // Q3: CC → C
        rotateSelectChoices(c, 6, 'D'); // Q6: CC → D
    }
});

// Helper: rotate choices for select items (Q-index is 1-based within Items array)
function rotateSelectChoices(caseObj, qNum, targetLetter) {
    const item = caseObj.Items[qNum - 1];
    if (item.Type !== 'select') return;

    const correctText = item.Correct;
    const choices = item.Choices;
    let oldCCIndex = choices.indexOf(correctText);

    if (oldCCIndex === -1) {
        console.log('WARNING: ' + item.ItemID + ' CC text not found in Choices');
        return;
    }

    const targetIndex = { A: 0, B: 1, C: 2, D: 3 }[targetLetter];

    // Don't rotate if already at target
    if (oldCCIndex === targetIndex) return;

    // Rotate choices: move CC element to target position, shift others
    const rotatedChoices = [...choices];
    rotatedChoices.splice(oldCCIndex, 1); // remove CC
    rotatedChoices.splice(targetIndex, 0, correctText); // insert at target
    item.Choices = rotatedChoices;

    // Remap ExplanationWrong fields
    const ewFields = {};
    const letters = ['A', 'B', 'C', 'D'];
    const ewValues = letters.map(l => item['ExplanationWrong' + l] || '');

    // The old EW values are indexed by the old choice positions
    // After rotation: new position L gets EW text from whatever choice is now at position L
    // ExplanationWrong for the new CC position should be "" (DL-008)
    // ExplanationWrong at other positions should get distractor text

    // Approach: create fresh EW mapping based on new choice positions
    // Item at new position L is either the correct answer (EW="") or a distractor
    // For distractors, try to find matching text from original EWs

    const newEW = ['', '', '', '']; // EW for A, B, C, D
    for (let newIdx = 0; newIdx < 4; newIdx++) {
        if (rotatedChoices[newIdx] === correctText) {
            newEW[newIdx] = ''; // CC slot = empty (DL-008)
            continue;
        }
        // Try to find old EW text for this distractor choice
        let found = false;
        for (let oldIdx = 0; oldIdx < 4; oldIdx++) {
            if (choices[oldIdx] === rotatedChoices[newIdx] && ewValues[oldIdx] && oldIdx !== oldCCIndex) {
                newEW[newIdx] = ewValues[oldIdx];
                found = true;
                break;
            }
        }
        if (!found) {
            newEW[newIdx] = `Option ${letters[newIdx]} ("${rotatedChoices[newIdx]}") is incorrect.`;
        }
    }

    // Write back
    for (let i = 0; i < 4; i++) {
        item['ExplanationWrong' + letters[i]] = newEW[i];
    }

    console.log('Rotated ' + item.ItemID + ': CC from ' + letters[oldCCIndex] + ' → ' + targetLetter);
}

// =============================================================
// WRITE BACK
// =============================================================

// Serialize the modified cases array
const newJson = JSON.stringify(cases, null, 4);

// Reconstruct the file
const header = src.substring(0, startIdx);
const footer = src.substring(endIdx + 1);
const newSrc = header + newJson + footer;

// Create backup first
fs.copyFileSync(FILE, BACKUP);
console.log('Backup created: ' + BACKUP);

// Write modified file
fs.writeFileSync(FILE, newSrc, 'utf8');
console.log('File written. Modified ' + modifiedItems + ' items across ' + targetIds.length + ' cases.');

// Verification
const verify = JSON.parse(newJson);
let certCount = 0;
targetIds.forEach(id => {
    const c = verify.find(x => x.CaseID === id);
    if (c) {
        const cItems = c.Items.filter(it => it.question_state === 'Certified').length;
        certCount += cItems;
        console.log(id + ': ' + cItems + '/' + c.Items.length + ' Certified | Prod: ' + c.ProductionStatus);
    }
});
console.log('\nTotal Certified items in 7 cases: ' + certCount + ' of ' + modifiedItems);

// Check explanation lengths
let shortExpls = 0;
targetIds.forEach(id => {
    const c = verify.find(x => x.CaseID === id);
    if (c) {
        c.Items.forEach(item => {
            if ((item.Explanation || '').length < 50) {
                console.log('WARNING: ' + item.ItemID + ' explanation only ' + (item.Explanation||'').length + ' chars');
                shortExpls++;
            }
        });
    }
});
console.log('Items with explanation < 50 chars: ' + shortExpls);
console.log('\n=== S537 CERTIFICATION COMPLETE ===');
