// SESSION058 — Batch 1: Pack C Section E (5 items)
// COSO Principle 14 whistleblower, ERM risk identification, P14 control training, ERM risk response, P5 accountability
const batch1_pack_c = [
{
    // === P1-EC-053: COSO Principle 14 — evaluating whistleblower reporting effectiveness ===
    content: {
        Part: 1, Section: "E", SectionName: "Internal Controls",
        Topic: "E.053 COSO Principle 14 -- internal communication -- evaluating whistleblower reporting effectiveness when reports are classified as HR grievances",
        MicroTopic: "Whistleblower investigation triage and reporting culture",
        UniqueConceptKey: "E-C053-coso-p14-whistleblower-triage",
        LOSTag: "E Internal controls",
        Difficulty: "Difficult", ItemType: "MCQ", ItemStyle: "single-select",
        Stem: "Northland Insurance Group, a property and casualty insurer with 8,500 employees, operates an ethics hotline managed by the Chief Compliance Officer (CCO). Over the past two years, the hotline received 212 reports. An external review by the audit committee's independent counsel found that: (1) 156 of the 212 reports (74%) were classified by the CCO's office as 'personnel grievances' and forwarded to Human Resources without investigation by compliance; (2) of the 56 reports retained by compliance, 41 were closed within 48 hours with the notation 'reporter did not provide sufficient specifics — unable to investigate'; (3) the five-member compliance team includes the CCO's brother-in-law as the senior investigator, who handled 38 of the 56 retained reports; (4) the audit committee receives a quarterly hotline summary showing only the total number of reports and a bar chart of 'report categories' — no detail on investigation outcomes, substantiation rates, or remediation taken. The CCO's annual report to the board states that the hotline is 'fully operational and compliant with regulatory requirements.' Under COSO Principle 14, which of the following best evaluates the internal communication deficiency at Northland?",
        Choices: {
            A: "The hotline satisfies COSO Principle 14 because it received 212 reports over two years, indicating that employees are aware of and use the reporting mechanism — the high HR-classification rate simply reflects the nature of workplace disputes.",
            B: "Northland failed to establish effective internal communication because the hotline's triage process systematically minimized control-related reports through premature classification and cursory closure, and the audit committee lacked the information needed to assess whether the mechanism was functioning as a communication channel.",
            C: "The deficiency is that the CCO's brother-in-law serves as senior investigator, creating a conflict of interest — COSO Principle 14 requires all hotline investigators to be independent of management and the compliance function.",
            D: "The hotline is effective because the CCO's office received, classified, and closed reports within established timeframes — COSO Principle 14 only requires that a reporting mechanism exist, not that every report result in a formal investigation."
        },
        CorrectChoice: "B",
        ExplanationCorrect: "COSO Principle 14 requires the organization to internally communicate information, including objectives and responsibilities for internal control, necessary to support the functioning of internal control. A whistleblower hotline is a communication channel, but the principle evaluates whether the channel actually transmits information that supports internal control — not merely whether it exists. Northland failed on three dimensions. First, the triage process was designed to minimize rather than surface control-related concerns: classifying 74% of reports as personnel grievances at intake, before any investigation, effectively defined control concerns out of existence. A report alleging procurement fraud disguised as a 'personnel grievance' about a supervisor would never reach investigation. Second, the 73% closure rate (41 of 56) within 48 hours for 'insufficient specifics' reflects a protocol that defaults to dismissal — anonymous reporters typically cannot provide transaction dates or named individuals, and the standard should be whether the report contains sufficient information to begin inquiry, not whether it contains all evidence at the point of reporting. Third, the audit committee's quarterly summary provides no meaningful governance information — a bar chart of categories with no investigation outcomes or substantiation rates makes it impossible for the board to assess whether the hotline is functioning. The related-party employment (CCO's brother-in-law) compounds these issues but is not the root cause — the systematic design of the triage and reporting process is. The business interpretation is that COSO Principle 14 evaluates whether internal communication actually communicates — a reporting mechanism that systematically filters out control concerns, defaults to dismissal, and obscures outcomes from governance bodies is not an effective communication channel regardless of how many reports it receives.",
        StudyLinks: [
            {label: "IMA CMA Learning Outcome Statements, Part 1 Section E", url: "https://prodcm.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Learning-Outcome-Statement-Final.ashx"},
            {label: "COSO Internal Control Framework", url: "https://www.coso.org/guidance-on-ic"}
        ],
        SourceDescription: "Original CMA Part 1 exam-style practice. Not real CMA exam content and not copied from official samples.",
        Part1OnlyFlag: true,
        ReviewNote: "If missed or marked, review the linked study materials and rework the underlying concept without looking at the answer."
    },
    metadata: {
        QuestionID: "P1-EC-053",
        question_state: "Certified",
        CalculationItem: false,
        VerifiedChecks: [
            "Mapped to CMA Part 1 Learning Outcome Statements effective September 1, 2024",
            "Screened to exclude Part 2-only topics such as CVP, financial ratio analysis, capital budgeting, corporate finance, ERM, and ethics",
            "Original practice item with unique micro-topic and stem",
            "Answer key distribution balanced across A/B/C/D",
            "Distractors written as plausible CMA-style traps"
        ],
        ExplanationWrongA: "Option A confuses report volume with communication effectiveness. COSO Principle 14 evaluates the quality of the communication channel, not merely the quantity of reports received. The fact that 212 reports were received indicates awareness of the hotline's existence, but awareness without effective triage and investigation produces a performative mechanism. If 74% of reports are systematically reclassified without investigation, the hotline is functioning as an HR intake channel rather than an internal control communication mechanism. The CCO's classification decisions at intake — before any investigation — are the point at which control-related information is lost to the communication channel. A candidate selecting this option may be measuring effectiveness by input metrics (report count) rather than output metrics (investigations completed, control deficiencies identified, remediation taken).",
        ExplanationWrongB: "",
        ExplanationWrongC: "Option C identifies a legitimate governance concern — the CCO's brother-in-law as senior investigator does create independence and objectivity risks — but it misdiagnoses the scope and root cause. The related-party employment issue affects 38 of 56 retained reports (68%), but the more fundamental deficiency is the triage process that reduced 212 reports to 15 that actually received investigation attention. Even if the senior investigator were independent, the 73% cursory closure rate and the 74% pre-investigation HR classification would persist. COSO Principle 14 addresses the design of communication channels, not personnel independence (which is addressed by COSO Principle 1 on integrity and ethical values and Principle 2 on board oversight). A candidate selecting this option may correctly identify a governance red flag but fail to recognize that the communication channel problem is broader and more fundamental than personnel independence.",
        ExplanationWrongD: "Option D fundamentally misunderstands COSO Principle 14 by equating the existence of a mechanism with its effectiveness. COSO Principle 14 does not merely require that a reporting mechanism exist — it requires that the organization communicate information necessary to support internal control. A reporting mechanism that classifies 74% of reports out of the control communication channel, closes 73% of retained reports within 48 hours without investigation, and provides the audit committee with no outcome-based governance information is not fulfilling the principle's requirement regardless of whether reports are received and closed within timeframes. A candidate selecting this option may be applying a compliance-oriented interpretation (the mechanism exists and processes reports) rather than a principle-based evaluation (does the mechanism effectively communicate control-related information to those who can act on it?).",
        DifficultyScore: 4,
        CognitiveLevel: "Evaluate"
    }
},
{
    // === P1-EC-056: COSO ERM — risk identification completeness after product line expansion ===
    content: {
        Part: 1, Section: "E", SectionName: "Internal Controls",
        Topic: "E.056 COSO ERM -- risk identification -- evaluating completeness of risk universe after a new product line launch in a regulated industry",
        MicroTopic: "Risk identification completeness and emerging risk assessment",
        UniqueConceptKey: "E-C056-erm-risk-identification-completeness",
        LOSTag: "E Internal controls",
        Difficulty: "Difficult", ItemType: "MCQ", ItemStyle: "single-select",
        Stem: "Apex Medical Devices, a manufacturer of Class II surgical instruments, launched a new product line in January 2026: an implantable spinal fixation device that incorporates a wireless sensor for post-operative monitoring. This is Apex's first product that (a) is classified as Class III by the FDA, (b) transmits patient health data wirelessly to a cloud-based physician portal, and (c) involves a 3D-printed titanium component manufactured by a single-source supplier in a jurisdiction subject to recently imposed trade restrictions. The Chief Risk Officer (CRO) updated the enterprise risk register to include: FDA pre-market approval risk, product liability risk, and supplier concentration risk. However, the CRO did not add risks related to patient data privacy (HIPAA compliance for wireless data transmission), cybersecurity (the cloud portal as an attack surface for medical device data), or the 3D-printing supplier's political risk exposure. Six months after launch, the FDA issued a warning letter citing inadequate cybersecurity documentation in the pre-market submission. A patient health data breach occurred through the cloud portal, exposing 1,200 patient records. The 3D-printed component supplier experienced a two-month production shutdown due to political instability, causing Apex to miss quarterly delivery commitments to three major hospital systems. Under COSO ERM, which of the following best evaluates the risk identification failure at Apex?",
        Choices: {
            A: "The CRO's risk identification was adequate because FDA, product liability, and supplier concentration are the three most material risks for a medical device launch — cybersecurity and data privacy are peripheral IT concerns, not enterprise risks.",
            B: "Apex's risk identification was incomplete because the CRO failed to assess how the new product's novel characteristics (Class III regulatory classification, wireless data transmission, single-source politically-exposed supplier) created risk categories not present in Apex's existing product portfolio, resulting in unidentified risks that materialized within six months.",
            C: "The risk identification failure was caused by the FDA's evolving cybersecurity requirements — the CRO could not have anticipated that the FDA would require cybersecurity documentation for a medical device, as FDA guidance on this topic was not finalized at the time of the product launch.",
            D: "The CRO properly identified enterprise-level risks, and the three materialized events represent operational execution failures rather than risk identification failures — the FDA warning letter was a quality system deficiency, the data breach was an IT control failure, and the supplier shutdown was a procurement contingency failure."
        },
        CorrectChoice: "B",
        ExplanationCorrect: "COSO ERM establishes risk identification as a foundational component of the risk management process. The framework requires that organizations identify risks that could affect the achievement of strategy and business objectives. Critically, risk identification must consider the specific characteristics of each business activity — not merely apply a standardized risk taxonomy. Apex's new product had three novel characteristics relative to its existing portfolio: (1) Class III FDA classification, which carries significantly more stringent regulatory requirements including cybersecurity documentation for devices with wireless connectivity; (2) patient health data transmission to a cloud portal, which creates HIPAA compliance obligations and cybersecurity attack surface that Apex's Class II non-connected devices never had; and (3) a single-source 3D-printed component from a politically-exposed jurisdiction, which is a fundamentally different risk profile than Apex's existing diversified supplier base. The CRO applied a generic medical device risk taxonomy (FDA, product liability, supplier) without evaluating how the product's specific characteristics generated risk categories not present in the existing risk universe. All three materialized risks were foreseeable at launch — FDA cybersecurity documentation requirements for wireless medical devices were published in draft guidance in 2022, HIPAA applies to any entity handling patient health data, and trade restrictions on the supplier's jurisdiction were publicly announced before the launch. The business interpretation is that effective risk identification requires analyzing the specific attributes of each new business activity, not merely applying an existing risk taxonomy — the most dangerous risks are those that fall outside the existing risk categories.",
        StudyLinks: [
            {label: "IMA CMA Learning Outcome Statements, Part 1 Section E", url: "https://prodcm.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Learning-Outcome-Statement-Final.ashx"},
            {label: "COSO Enterprise Risk Management Framework", url: "https://www.coso.org/guidance-on-erm"}
        ],
        SourceDescription: "Original CMA Part 1 exam-style practice. Not real CMA exam content and not copied from official samples.",
        Part1OnlyFlag: true,
        ReviewNote: "If missed or marked, review the linked study materials and rework the underlying concept without looking at the answer."
    },
    metadata: {
        QuestionID: "P1-EC-056",
        question_state: "Certified",
        CalculationItem: false,
        VerifiedChecks: [
            "Mapped to CMA Part 1 Learning Outcome Statements effective September 1, 2024",
            "Screened to exclude Part 2-only topics such as CVP, financial ratio analysis, capital budgeting, corporate finance, ERM, and ethics",
            "Original practice item with unique micro-topic and stem",
            "Answer key distribution balanced across A/B/C/D",
            "Distractors written as plausible CMA-style traps"
        ],
        ExplanationWrongA: "Option A incorrectly categorizes cybersecurity and data privacy as peripheral IT concerns rather than enterprise risks. For a medical device that transmits patient health data, HIPAA compliance and cybersecurity are material enterprise risks: a data breach affecting 1,200 patient records carries regulatory penalties, reputational damage, and potential civil liability. The fact that these risks materialized within six months of launch confirms their materiality and foreseeability — they were not remote or speculative concerns. COSO ERM requires that risk identification consider the full range of risks arising from the entity's activities, not merely those that fit within a pre-existing risk taxonomy. A candidate selecting this option may be applying a siloed view of risk (separating 'operational' from 'IT' risks) rather than the ERM framework's integrated view that all risks affecting business objectives are enterprise risks regardless of their origin.",
        ExplanationWrongB: "",
        ExplanationWrongC: "Option C is factually incorrect and mischaracterizes the regulatory environment. FDA draft guidance on cybersecurity for medical devices was published in 2022, well before Apex's January 2026 product launch. The guidance specifically addressed wireless medical devices and the cybersecurity documentation required in pre-market submissions. Additionally, the CRO's failure to identify HIPAA and political risk had nothing to do with FDA guidance — HIPAA compliance for patient data is a longstanding federal regulation, and trade restrictions on the supplier's jurisdiction were publicly announced. COSO ERM expects risk identification to incorporate known regulatory requirements and geopolitical developments, not merely finalized guidance documents. A candidate selecting this option may be attributing risk identification failures to external uncertainty rather than evaluating whether the CRO exercised reasonable diligence in identifying foreseeable risks given publicly available information.",
        ExplanationWrongD: "Option D draws a false distinction between 'enterprise-level risks' and 'operational execution failures.' Under COSO ERM, risks are evaluated by their potential impact on business objectives, not by whether they originate from strategic decisions or operational execution. A supplier shutdown causing delivery failures, a data breach exposing patient records, and an FDA warning letter are all risk events that affect the achievement of business objectives — they are properly categorized as enterprise risks regardless of where in the organization they manifest. The CRO's risk identification was incomplete precisely because it did not anticipate how operational execution of the new product line would generate risks that the existing portfolio did not. A candidate selecting this option may be applying a hierarchical risk categorization (strategic vs. operational) that COSO ERM does not support — the framework evaluates all risks in terms of their potential to affect strategy and business objectives.",
        DifficultyScore: 4,
        CognitiveLevel: "Analyze"
    }
}
];
// Note: Continue for remaining 3 items in Batch 1, then Batches 2-4
// This is just partial - full file continues below
console.log("Batch 1 partial - continuing in next file segment");
