// S892 Batch 4: P1-E-070, P1-E-071, P1-E-073, P1-E-074
// Information & Communication + Monitoring
exports.items = [
  {
    "Part": 1,
    "Section": "E",
    "SectionName": "Internal Controls",
    "Topic": "E.070 external communication third party control reporting",
    "MicroTopic": "COSO Principle 15 — external communication",
    "UniqueConceptKey": "E-070-external-communication-reporting",
    "LOSTag": "E.2 Information and communication",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Stem": "Greenway Medical outsources patient billing to a third-party service provider that processes $8.5M in annual receivables. Greenway receives a SOC 1 Type 2 report annually from the provider. The latest report identified a control exception: the provider's system did not enforce segregation of duties for billing adjustments and write-offs during a three-month period. The provider stated the issue was remediated but did not provide evidence. Greenway's CFO wants to accept the SOC report as sufficient and take no further action. Which of the following represents the most appropriate course of action for Greenway based on the SOC report findings?",
    "Choices": {
      "A": "Accept the provider's statement of remediation and rely on the SOC 1 Type 2 report for assurance, since it was issued by an independent service auditor.",
      "B": "Terminate the contract with the provider immediately because a single control exception indicates a pervasive control failure in the provider's environment.",
      "C": "Request that the external auditor adjust the financial statement audit approach to test 100% of Greenway's receivables, compensating for the provider's control weakness.",
      "D": "Request a bridge letter or updated SOC report covering the remediation period, evaluate the severity of the segregation-of-duties exception on Greenway's financial reporting, and implement compensating controls until verified remediation is confirmed."
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Under COSO Principle 15 (External Communication), an organization communicates with external parties regarding matters affecting the functioning of internal control. SOC 1 Type 2 reports provide assurance over a service provider's controls during a specified period — but when the report identifies an exception, management cannot simply accept the report and take no action. The SOC report is not a seal of approval when exceptions exist; rather, it is information that management must evaluate. Greenway has two responsibilities under COSO Principle 15: (1) obtain sufficient evidence that the exception has been remediated — this requires more than the provider's verbal assertion; a bridge letter covering the period from the SOC report date to the current date, an updated SOC report, or management's direct testing of the provider's controls are appropriate; and (2) evaluate the severity of the deficiency on Greenway's own financial reporting. A segregation-of-duties failure in billing adjustments and write-offs directly affects the completeness and accuracy of accounts receivable, a significant balance in Greenway's financial statements. Until verified remediation is confirmed, Greenway should implement compensating controls — such as reviewing billing adjustment reports, reconciling write-offs to supporting documentation, and performing trend analysis on receivables balances — to mitigate the risk that errors or irregularities go undetected. Business interpretation: reliance on a service organization's SOC report does not relieve user entity management of its responsibility to evaluate identified exceptions and protect the integrity of its own financial reporting. Exam trap: candidates sometimes treat a SOC report as a binary pass/fail instrument; in practice, the report is an input to management's assessment of control risk, and management retains the obligation to respond to exceptions.",
    "StudyLinks": [
      { "label": "COSO Internal Control — Integrated Framework (2013)", "url": "https://www.coso.org" },
      { "label": "IMA CMA Learning Outcome Statements, Part 1 Section E", "url": "https://prodcm.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Learning-Outcome-Statement-Final.ashx" }
    ],
    "SourceDescription": "Original CMA Part 1 exam-style practice. Not real CMA exam content and not copied from official samples.",
    "Part1OnlyFlag": true,
    "ReviewNote": "If missed or marked, review the linked study materials and rework the underlying concept without looking at the answer.",
    "QuestionID": "P1-E-070",
    "CalculationItem": false,
    "VerifiedChecks": [
      "Mapped to CMA Part 1 Learning Outcome Statements effective September 1, 2024",
      "Screened to exclude Part 2-only topics such as CVP, financial ratio analysis, capital budgeting, corporate finance, ERM, and ethics",
      "Original practice item with unique micro-topic and stem",
      "Answer key distribution balanced across A/B/C/D",
      "Distractors written as plausible CMA-style traps"
    ],
    "ExplanationWrongA": "Accepting the provider's statement at face value violates COSO Principle 15's requirement that external communication be evaluated for sufficiency. A SOC 1 Type 2 report with an identified exception is not a clean opinion — it is a qualified or adverse conclusion on the control for the affected period. The provider's unverified assertion, without evidence, does not satisfy management's responsibility to obtain sufficient information about whether the deficiency was actually corrected. Furthermore, COSO Principle 10 requires control activities that mitigate identified risks; accepting an unverified claim of remediation leaves Greenway exposed to the same control weakness for any billing adjustments and write-offs processed since the exception period. The independence of the service auditor does not excuse management from its own obligation to evaluate the impact on Greenway's financial reporting and to ensure that risks to the integrity of accounts receivable are addressed through evidence-based follow-up rather than reliance on an unsupported statement from the service provider.",
    "ExplanationWrongB": "Immediate contract termination is disproportionate to a single quarterly exception and is not what COSO Principle 15 contemplates. Service organization relationships involve multi-year contracts with significant transition costs, data migration requirements, and operational disruption risks. A single control exception covering a three-month period, while requiring investigation, does not necessarily indicate a pervasive control failure — the SOC report itself would describe the exception's severity and whether it represented a material weakness or a less severe deficiency. Furthermore, termination does not resolve the outstanding question of whether billing adjustments and write-offs during the affected period were processed correctly; those receivables remain on Greenway's books regardless of the provider relationship. The appropriate response under COSO is to evaluate the severity, obtain remediation evidence, and implement compensating controls — not to abandon the relationship without assessment. Termination without analysis substitutes an operational decision for a control evaluation, addressing neither the root cause nor the financial reporting impact.",
    "ExplanationWrongC": "Expanding the financial statement audit to test 100% of receivables conflates management's responsibility for internal control with the external auditor's independent attest role. Under COSO Principle 15, management — not the external auditor — is responsible for evaluating exceptions identified in service organization reports and determining whether compensating controls are needed. External auditors are not a substitute for management's internal control responsibilities; they provide independent assurance, not ongoing management oversight. Furthermore, auditing 100% of $8.5M in receivables is neither cost-effective nor a permanent solution — it addresses the symptom (potential receivable misstatement) rather than the cause (unremediated segregation-of-duties failure at the service provider). Every subsequent period would require the same expanded audit testing unless the underlying control issue is resolved, making this approach an indefinite, unsustainable use of audit resources. The correct response is for management to obtain remediation evidence from the provider and implement compensating controls at Greenway.",
    "ExplanationWrongD": "",
    "question_state": "Certified",
    "certification_date": "2026-07-28",
    "certification_batch": "Pack A Final Closure — S892",
    "upgrade_note": "Pack A Final Closure - S892 Evaluate replacement for archived P1-E-070",
    "CognitiveLevel": "Evaluate"
  },
  {
    "Part": 1,
    "Section": "E",
    "SectionName": "Internal Controls",
    "Topic": "E.071 ongoing separate evaluations monitoring frequency",
    "MicroTopic": "COSO Principle 16 — ongoing and separate evaluations",
    "UniqueConceptKey": "E-071-monitoring-frequency-determination",
    "LOSTag": "E.2 Monitoring activities",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Stem": "Dalton Corp uses continuous monitoring for high-risk areas (daily reconciliation of cash, weekly review of wire transfers) and separate evaluations for moderate-risk areas (quarterly inventory cycle counts, semi-annual access reviews). The internal audit director proposes shifting all monitoring to continuous automated monitoring, arguing it provides real-time assurance. The CFO counters that continuous monitoring is expensive and separate evaluations on a defined schedule are adequate for most areas. Which of the following most accurately identifies the factors that determine whether ongoing monitoring, separate evaluations, or a combination is appropriate for a given control area?",
    "Choices": {
      "A": "The decision depends on the risk level of the area, the nature of the control (automated vs. manual), the rate of change in the business environment, and the cost-benefit trade-off — with continuous monitoring warranted for high-risk, rapidly changing areas and separate evaluations sufficient for stable, moderate-risk areas where manual observation is effective.",
      "B": "All monitoring should be continuous and automated because technology provides superior assurance at lower cost over time, and separate evaluations introduce unacceptable gaps between review periods during which control failures can go undetected.",
      "C": "Separate evaluations alone are sufficient for all control areas because internal audit's periodic reviews provide independent, objective evidence of control effectiveness, and continuous monitoring merely duplicates this work at higher cost.",
      "D": "Monitoring approach should be determined solely by regulatory requirements — if no regulation mandates continuous monitoring, separate evaluations are the default — because compliance with laws and regulations is the primary purpose of internal control monitoring."
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Under COSO Principle 16 (Ongoing and Separate Evaluations), the organization selects, develops, and performs ongoing and/or separate evaluations to ascertain whether the components of internal control are present and functioning. COSO Principle 16 does not prescribe a single monitoring method; it explicitly contemplates a mix tailored to circumstances. The key factors in determining the appropriate monitoring approach are: (1) Risk level — high-risk areas such as Dalton's cash reconciliation and wire transfers warrant more frequent, near-real-time monitoring because the consequences of failure are severe and immediate. (2) Nature of the control — automated controls embedded in systems are naturally suited to continuous monitoring, while manual controls requiring human judgment (e.g., physical inventory cycle counts where an observer must identify damaged or obsolete stock) are better suited to separate evaluations at defined intervals. (3) Rate of change — areas experiencing rapid change (new product lines, system implementations, regulatory shifts) require more frequent monitoring than stable, mature processes. (4) Cost-benefit trade-off — the cost of implementing continuous automated monitoring (software, integration, maintenance) must be weighed against the benefit of earlier detection; for Dalton's semi-annual access reviews in a stable organizational structure, the incremental benefit of continuous monitoring may not justify its cost. Business interpretation: monitoring is not one-size-fits-all; effective internal control allocates monitoring resources to areas where the risk-adjusted benefit of timely detection is highest.",
    "StudyLinks": [
      { "label": "COSO Internal Control — Integrated Framework (2013)", "url": "https://www.coso.org" },
      { "label": "IMA CMA Learning Outcome Statements, Part 1 Section E", "url": "https://prodcm.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Learning-Outcome-Statement-Final.ashx" }
    ],
    "SourceDescription": "Original CMA Part 1 exam-style practice. Not real CMA exam content and not copied from official samples.",
    "Part1OnlyFlag": true,
    "ReviewNote": "If missed or marked, review the linked study materials and rework the underlying concept without looking at the answer.",
    "QuestionID": "P1-E-071",
    "CalculationItem": false,
    "VerifiedChecks": [
      "Mapped to CMA Part 1 Learning Outcome Statements effective September 1, 2024",
      "Screened to exclude Part 2-only topics such as CVP, financial ratio analysis, capital budgeting, corporate finance, ERM, and ethics",
      "Original practice item with unique micro-topic and stem",
      "Answer key distribution balanced across A/B/C/D",
      "Distractors written as plausible CMA-style traps"
    ],
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Claiming that all monitoring should be continuous and automated ignores the cost-benefit dimension required by COSO Principle 16. While continuous monitoring provides near-real-time assurance, it requires significant investment in technology infrastructure, automated exception reporting, and ongoing maintenance — costs that may exceed the benefit for moderate-risk, stable control areas. Dalton's inventory cycle counts, for example, involve physical observation of inventory that automated systems cannot fully replace: cycle counting requires human judgment to identify damaged goods, obsolescence, mislabeled stock, or quantities that do not match system records because of theft rather than recording error. COSO Principle 16 explicitly contemplates a mix of ongoing evaluations and separate evaluations calibrated to risk, stating that a combination is typically used. A blanket mandate for continuous monitoring across all areas would waste resources on low-risk controls while potentially diverting attention from areas that genuinely require real-time detection. Furthermore, separate evaluations provide an independent assessment of whether ongoing monitoring itself is functioning — something that continuous monitoring alone cannot self-assess.",
    "ExplanationWrongC": "Relying exclusively on separate evaluations for all control areas disregards COSO Principle 16's recognition that ongoing monitoring built into business operations provides timely detection of control failures. Separate evaluations conducted quarterly, semi-annually, or annually create observation gaps: for Dalton's daily cash reconciliation control, deferring verification to a quarterly review would mean three months during which a cash misappropriation could escalate without detection. COSO Principle 16 explicitly states that ongoing evaluations provide more timely feedback on the effectiveness of internal control than separate evaluations, and that the frequency of separate evaluations is a matter of management judgment informed by the nature and degree of change and associated risks. Ongoing monitoring and separate evaluations serve complementary purposes: ongoing monitoring detects deviations as they occur, while separate evaluations provide a periodic independent assessment of whether the ongoing monitoring itself is designed and operating effectively. Neither alone is sufficient across all control areas; the Principle requires organizations to use both approaches in proportion to risk.",
    "ExplanationWrongD": "Restricting the monitoring approach determination to regulatory requirements only mischaracterizes the purpose of internal control monitoring under COSO Principle 16. While compliance with laws and regulations is one objective of internal control, COSO recognizes three categories of objectives: operations, reporting, and compliance. Monitoring must be designed to provide reasonable assurance across all relevant objectives, not just compliance. For Dalton Corp, the inventory cycle count control serves operational objectives (accurate inventory records for production planning and order fulfillment) and financial reporting objectives (proper inventory valuation affecting cost of goods sold and balance sheet presentation), regardless of whether any regulation mandates continuous monitoring. COSO Principle 16 requires the organization to evaluate and communicate deficiencies — the monitoring approach should be driven by the risk of control failure and its potential impact on objectives, not solely by the existence of a regulatory mandate. An approach that ignores operational and reporting risks because no regulation compels monitoring would leave significant control gaps that could result in inventory misstatements, production disruptions, or financial reporting errors.",
    "question_state": "Certified",
    "certification_date": "2026-07-28",
    "certification_batch": "Pack A Final Closure — S892",
    "upgrade_note": "Pack A Final Closure - S892 Evaluate replacement for archived P1-E-071",
    "CognitiveLevel": "Evaluate"
  },
  {
    "Part": 1,
    "Section": "E",
    "SectionName": "Internal Controls",
    "Topic": "E.073 control deficiency classification material weakness",
    "MicroTopic": "COSO Principle 17 — deficiency assessment",
    "UniqueConceptKey": "E-073-deficiency-classification",
    "LOSTag": "E.3 Monitoring activities",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Stem": "An external auditor identified the following at Meridian Corp: (1) The company does not reconcile intercompany accounts across its six subsidiaries — unreconciled differences total $2.3M against total assets of $85M. (2) The accounting manager who records journal entries also reviews and approves them — no misstatements have been found. (3) Bank reconciliations for three of twelve accounts were not performed for the last two months. Which of the following most appropriately classifies each finding and identifies the most severe classification?",
    "Choices": {
      "A": "(1) Significant deficiency, (2) Deficiency, (3) Deficiency — and finding (2) is the most severe because it involves segregation of duties.",
      "B": "(1) Material weakness, (2) Significant deficiency, (3) Deficiency — and finding (1) is the most severe because the unreconciled $2.3M represents a material potential misstatement.",
      "C": "(1) Deficiency, (2) Material weakness, (3) Significant deficiency — and finding (2) is the most severe because any segregation-of-duties failure is automatically a material weakness.",
      "D": "(1) Material weakness, (2) Material weakness, (3) Material weakness — all three are material weaknesses because any control failure must be classified at the highest severity level per PCAOB standards."
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Under COSO Principle 17 (Evaluation and Communication of Deficiencies), the organization evaluates and communicates internal control deficiencies to parties responsible for taking corrective action. Deficiencies are classified along a severity spectrum: (a) Deficiency — a control is not operating as designed; (b) Significant Deficiency — a deficiency or combination of deficiencies less severe than a material weakness yet important enough to merit attention; (c) Material Weakness — a deficiency or combination of deficiencies such that there is a reasonable possibility that a material misstatement of the financial statements would not be prevented or detected on a timely basis. Applying these definitions: Finding 1 is a material weakness. Unreconciled intercompany differences of $2.3M on $85M in total assets (2.7%) are quantitatively material, and the failure spans all six subsidiaries, indicating a pervasive systematic breakdown. Finding 2 is a significant deficiency. The accounting manager's ability to both record and approve journal entries is a segregation-of-duties failure — a key control weakness because journal entries can affect any account. However, the absence of identified misstatements, coupled with the possibility of compensating controls, means the deficiency does not rise to material weakness. Finding 3 is a deficiency. Bank reconciliations for 3 of 12 accounts not performed for two months — a control not operating as designed for a limited period affecting a minority of accounts. Finding 1 is the most severe classification (material weakness vs. significant deficiency for finding 2 and deficiency for finding 3). Deficiency classification requires professional judgment weighing both quantitative materiality and qualitative factors such as pervasiveness.",
    "StudyLinks": [
      { "label": "COSO Internal Control — Integrated Framework (2013)", "url": "https://www.coso.org" },
      { "label": "IMA CMA Learning Outcome Statements, Part 1 Section E", "url": "https://prodcm.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Learning-Outcome-Statement-Final.ashx" }
    ],
    "SourceDescription": "Original CMA Part 1 exam-style practice. Not real CMA exam content and not copied from official samples.",
    "Part1OnlyFlag": true,
    "ReviewNote": "If missed or marked, review the linked study materials and rework the underlying concept without looking at the answer.",
    "QuestionID": "P1-E-073",
    "CalculationItem": false,
    "VerifiedChecks": [
      "Mapped to CMA Part 1 Learning Outcome Statements effective September 1, 2024",
      "Screened to exclude Part 2-only topics such as CVP, financial ratio analysis, capital budgeting, corporate finance, ERM, and ethics",
      "Original practice item with unique micro-topic and stem",
      "Answer key distribution balanced across A/B/C/D",
      "Distractors written as plausible CMA-style traps"
    ],
    "ExplanationWrongA": "This classification understates two of the three findings. Under COSO Principle 17, an unreconciled intercompany difference of $2.3M against $85M in total assets (2.7%) represents a material weakness — not a significant deficiency — because there is a reasonable possibility that a material misstatement in Meridian's consolidated financial statements would not be prevented or detected. Intercompany accounts must eliminate upon consolidation; unreconciled differences flowing into the consolidated financial statements could distort assets, liabilities, revenues, or expenses by a material amount across all six subsidiaries. Additionally, ranking the segregation-of-duties failure (finding 2) as the most severe is incorrect: while significant, finding 2 lacks a quantified financial statement impact, whereas finding 1 has a known $2.3M quantification. Severity is determined by both reasonable possibility (likelihood) and magnitude (potential misstatement); finding 1 has both — the $2.3M difference already exists, and the absence of reconciliation means the company does not know whether additional misstatements are embedded. Finding 2 has a potential for future misstatement but no identified current misstatement, making it less severe than finding 1.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "This classification contains two errors. First, classifying finding 1 as a deficiency understates its severity — a $2.3M unreconciled intercompany difference representing 2.7% of total assets meets the material weakness threshold under COSO Principle 17 because there is a reasonable possibility that a material misstatement in Meridian's consolidated financial statements would not be prevented or detected on a timely basis. The failure spans all six subsidiaries and affects the integrity of the consolidation process, which is fundamental to financial reporting. Second, the assertion that any segregation-of-duties failure is automatically a material weakness is incorrect. Under COSO's deficiency assessment framework, a segregation-of-duties failure is evaluated using the same factors as any other deficiency: magnitude of potential misstatement, likelihood of occurrence, pervasiveness, and the existence of compensating controls. Finding 2 involves journal entry review and could affect multiple accounts, but no misstatements have been found, and management may have compensating controls that mitigate the risk. Absent evidence of a reasonable possibility of material misstatement, a segregation-of-duties deficiency may be classified as a significant deficiency rather than a material weakness.",
    "ExplanationWrongD": "Classifying all three findings as material weaknesses reflects an all-or-nothing approach that is inconsistent with COSO Principle 17's graduated classification framework. Deficiencies, significant deficiencies, and material weaknesses represent distinct levels of severity based on the reasonable possibility and magnitude of potential misstatement. Finding 3 — three bank accounts out of twelve not reconciled for two months — is a deficiency (a control not operating as designed for a limited period affecting a minority of accounts) but is unlikely to rise to material weakness because: the scope is limited (25% of accounts), the duration is short (two months), and management can promptly remediate by performing the outstanding reconciliations. No evidence indicates that the unreconciled accounts contain material misstatements. Classifying every control failure at the highest severity level dilutes the meaning of the material weakness designation and deprives management and the board of the ability to prioritize remediation resources based on genuine severity. COSO requires a reasoned, evidence-based assessment of each finding, not a blanket escalation.",
    "question_state": "Certified",
    "certification_date": "2026-07-28",
    "certification_batch": "Pack A Final Closure — S892",
    "upgrade_note": "Pack A Final Closure - S892 Evaluate replacement for archived P1-E-073",
    "CognitiveLevel": "Evaluate"
  },
  {
    "Part": 1,
    "Section": "E",
    "SectionName": "Internal Controls",
    "Topic": "E.074 remediation monitoring tracking verification",
    "MicroTopic": "COSO Principle 17 — deficiency remediation",
    "UniqueConceptKey": "E-074-remediation-monitoring",
    "LOSTag": "E.3 Monitoring activities",
    "Difficulty": "Moderate",
    "DifficultyScore": 3,
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Stem": "Ridgeway Corp's prior year audit identified 14 control deficiencies, of which management reported 11 as remediated and 3 as in progress. The current year's internal audit found that: (1) 5 of the 11 reported as remediated still have the same control weakness, (2) the 3 in progress have had no status updates in 8 months, and (3) management self-certified all remediations without independent verification. The CEO states that management's self-assessment is sufficient because management knows the operations best. Which COSO monitoring principle and sub-principle is most clearly violated, and what specific remediation tracking process should be implemented to prevent recurrence?",
    "Choices": {
      "A": "COSO Principle 14 (internal communication) is violated because management failed to communicate the remediation status to employees; the fix is to issue a company-wide memo on control compliance.",
      "B": "COSO Principle 10 (control activities) is violated because the original controls were defective; the fix is to redesign all 14 controls from scratch with stronger preventive features.",
      "C": "COSO Principle 17 (evaluation and communication of deficiencies) is violated — specifically the requirement for timely remediation tracking with independent verification; the fix is to establish a remediation register with assigned owners, target dates, independent validation procedures, and regular status reporting to the audit committee.",
      "D": "COSO Principle 5 (accountability) is violated because the CEO is not personally performing the remediation verification; the fix is to require the CEO to review and sign off on every individual remediation item."
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "Under COSO Principle 17 (Evaluation and Communication of Deficiencies), the organization evaluates internal control deficiencies and communicates them to parties responsible for taking corrective action, including senior management and the board of directors as appropriate. COSO Principle 17 further requires that management track whether deficiencies are remediated on a timely basis. Ridgeway Corp's situation violates multiple dimensions of this principle: (1) Management self-certified all 11 remediations without independent verification — COSO Principle 17 requires that remediation be objectively verified, not self-assessed, because the entity that identified the deficiency or performed the remediation cannot impartially determine whether it was effective. (2) Of the 11 self-certified remediations, 5 still had the identical control weakness, demonstrating that self-certification without independent verification is unreliable. (3) Three in-progress items had no status updates in 8 months, indicating that management had no functioning tracking mechanism — COSO Principle 17 requires timely remediation, and eight months without progress monitoring is not timely. The appropriate remediation tracking process should include: a formal remediation register documenting each deficiency, its severity classification, the assigned remediation owner, target completion date, current status, and the date and result of independent validation testing; regular (at least quarterly) status reporting to the audit committee; independent verification by internal audit before any deficiency is closed; and escalation procedures if target dates are missed. Business interpretation: remediation self-certification is not remediation — organizations that rely on management self-assessment without independent verification will repeatedly report deficiencies as remediated when they are not, eroding stakeholder confidence and increasing the risk of uncorrected control failures.",
    "StudyLinks": [
      { "label": "COSO Internal Control — Integrated Framework (2013)", "url": "https://www.coso.org" },
      { "label": "IMA CMA Learning Outcome Statements, Part 1 Section E", "url": "https://prodcm.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Learning-Outcome-Statement-Final.ashx" }
    ],
    "SourceDescription": "Original CMA Part 1 exam-style practice. Not real CMA exam content and not copied from official samples.",
    "Part1OnlyFlag": true,
    "ReviewNote": "If missed or marked, review the linked study materials and rework the underlying concept without looking at the answer.",
    "QuestionID": "P1-E-074",
    "CalculationItem": false,
    "VerifiedChecks": [
      "Mapped to CMA Part 1 Learning Outcome Statements effective September 1, 2024",
      "Screened to exclude Part 2-only topics such as CVP, financial ratio analysis, capital budgeting, corporate finance, ERM, and ethics",
      "Original practice item with unique micro-topic and stem",
      "Answer key distribution balanced across A/B/C/D",
      "Distractors written as plausible CMA-style traps"
    ],
    "ExplanationWrongA": "Attributing the failure to COSO Principle 14 (internal communication) misidentifies the root cause. While communication is a component of effective internal control — management should communicate remediation status to relevant parties — the deficiency at Ridgeway is not primarily a communication failure. The core issues are: (1) management self-certified remediation without independent verification (5 of 11 remediations were ineffective), (2) no tracking mechanism existed for in-progress items (3 items with no updates in 8 months), and (3) the CEO believes self-assessment is sufficient. This is a deficiency assessment, tracking, and verification failure under COSO Principle 17, not a communication failure under Principle 14. Issuing a company-wide memo on control compliance — the proposed fix — would not establish independent verification of remediation effectiveness, create a formal tracking system with assigned owners and target dates, or provide the audit committee with reliable information about whether control weaknesses have been resolved. A memo communicates; it does not verify, track, or remediate. Principle 17 specifically requires that the organization track whether deficiencies are remediated on a timely basis — a tracking system, not a memo.",
    "ExplanationWrongB": "Blaming COSO Principle 10 (control activities) and recommending a full redesign of all 14 controls misunderstands the nature of the deficiency. The original controls may have been appropriately designed but failed due to operating errors (e.g., personnel not following prescribed procedures, inadequate training, workload pressures) that do not require wholesale redesign. More fundamentally, the finding described by internal audit is a monitoring and remediation tracking failure, not a control design failure. COSO Principle 17 requires the organization to evaluate deficiencies and track whether corrective actions are completed on a timely basis. Ridgeway's problem is not that the controls were poorly designed — it is that management declared controls remediated without verifying the remediation's effectiveness (5 of 11 still defective) and had no process for monitoring the progress of in-progress items (3 items with no updates in 8 months). Even the best-designed controls require a functioning remediation tracking and independent verification process to ensure that identified weaknesses are actually corrected — which is precisely what Ridgeway lacks.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Invoking COSO Principle 5 (accountability) and requiring the CEO to personally verify each remediation is both a misdiagnosis of the principle violated and an impractical, non-scalable solution. COSO Principle 5 addresses the board's oversight role and the organization's establishment of structures, reporting lines, and appropriate authorities and responsibilities in pursuit of objectives. While accountability for internal control is important, Principle 5 does not specifically address deficiency remediation tracking or independent verification — those are squarely within COSO Principle 17's scope. Furthermore, requiring the CEO to personally review and sign off on every remediation at a granular level is neither practical for an organization the size of Ridgeway Corp nor an effective control: the CEO relies on a system of internal control — including internal audit, the remediation tracking process, and the audit committee's oversight — rather than performing verification personally. The core deficiency is that Ridgeway's monitoring system lacked independent verification (management self-certified without objective testing). The appropriate fix is to build independent verification into the remediation tracking process — through internal audit validation, not CEO sign-off — which is the structural solution that COSO Principle 17 envisions.",
    "question_state": "Certified",
    "certification_date": "2026-07-28",
    "certification_batch": "Pack A Final Closure — S892",
    "upgrade_note": "Pack A Final Closure - S892 Analyze replacement for archived P1-E-074",
    "CognitiveLevel": "Analyze"
  }
];
