// SESSION 72 — Section B Cognitive Upgrade Campaign, Wave 2
// Applies 15 Pack D Section B rewrites: 8 Evaluate + 7 Analyze
// T0: 2026-07-29T21:10:00Z
const fs = require('fs');
const path = require('path');

const PACK_FILE = path.join(__dirname, '..', 'pack_d_corrected.js');
const T0 = Date.now();
console.log('SESSION072 — Starting rewrite application at', new Date(T0).toISOString());

const rewrites = {

  // ========== BATCH 1 ==========

  // 1: BD-006 — Flexible Budget Variance → Evaluate
  'P1-BD-006': {
    "Stem": "Fernhollow Manufacturing's controller, Rebecca Walsh, reviews a concerning pattern in the quarterly flexible budget reports. For four consecutive quarters, the production department has reported favorable flexible budget variances totaling $87,000. The production VP attributes this to lean manufacturing initiatives implemented last year. However, Rebecca notices that the flexible budget cost assumptions — $42,000 monthly fixed cost plus $6.50 per direct labor hour — were set 18 months ago when the plant was operating at 65% capacity with significant overtime. The plant now runs at 88% capacity with standardized shifts and no overtime. The CFO asks Rebecca whether the board should recognize the production VP for cost leadership or investigate the budget assumptions. Which recommendation is most appropriate?",
    "Choices": {
      "A": "Recognize the production VP for cost leadership — four consecutive quarters of favorable variances totaling $87,000 clearly demonstrate sustained operational improvement, and lean manufacturing ROI studies show 5-8% cost reduction is typical in year one",
      "B": "Recommend the board defer recognition until the flexible budget cost assumptions are independently re-benchmarked against current input prices and normal operating conditions — the 18-month-old assumptions were set under materially different operating conditions (65% capacity with overtime vs. 88% capacity without overtime), making it impossible to determine whether the $87,000 reflects genuine efficiency or an obsolete benchmark",
      "C": "Advise the board to recognize half the $87,000 as efficiency gains and attribute the remainder to outdated cost assumptions — this acknowledges the production VP's efforts while maintaining skepticism about the budget baseline",
      "D": "Recommend immediately lowering the flexible budget cost per hour from $6.50 to $5.80 to eliminate the 'artificial' favorable variances and challenge the production team with a tighter benchmark going forward"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The most appropriate recommendation is to defer recognition until the flexible budget assumptions are independently re-benchmarked. Under CMA Part 1 variance analysis, a flexible budget variance is only meaningful if the underlying cost standards are valid. The 18-month-old assumptions were set under fundamentally different operating conditions — 65% capacity with overtime premium costs versus today's 88% capacity with standardized shifts. The overtime premium embedded in the old baseline alone would create a structural favorable bias. Rebecca cannot determine whether the $87,000 represents lean manufacturing gains (which would warrant recognition) or simply reflects comparing current efficient operations against an inflated baseline (which would not). The professional controller's responsibility is to ensure performance evaluation rests on valid benchmarks, not to split differences (Option C) or mechanically tighten standards (Option D) without analysis. A common CMA exam trap is to assume that sustained favorable variances indicate good performance — candidates must evaluate whether the benchmark is still relevant to current operating conditions before drawing conclusions.",
    "ExplanationWrongA": "Option A prematurely credits lean manufacturing without verifying the benchmark's validity. The flexible budget assumptions were set when the plant operated at 65% capacity with overtime — the overtime premium ($48/hour vs. $32/hour regular rate) means the original $6.50/hour assumption embeds costs that no longer exist at 88% capacity with standardized shifts. The favorable variances may partially or entirely reflect this structural cost baseline change rather than continuous improvement. A candidate selecting this option may have assumed that any sustained favorable variance pattern indicates management performance, without applying the evaluate-level skill of questioning whether the measurement tool is still calibrated correctly.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C proposes an arbitrary 50/50 split with no analytical basis. While the controller suspects both factors are present (some genuine efficiency gain, some baseline obsolescence), apportioning percentages without analysis is speculative — not professional. The board would be making a recognition decision based on a guess. CMA Part 1 standards require evidence-based performance evaluation. The correct approach is to establish the factual baseline first (re-benchmark), then attribute the variance to its causes. A candidate selecting this option may have been attracted to the appearance of balance, but splitting the difference without evidence is not a professional accounting judgment.",
    "ExplanationWrongD": "Option D proposes mechanically tightening the flexible budget standard from $6.50 to $5.80. This is an arbitrary adjustment — there is no analysis suggesting $5.80 is the correct rate for current operations. More importantly, lowering the benchmark creates a new, possibly unrealistic target against which future performance will be measured. If $5.80 is too low, future periods will show unfavorable variances that penalize managers for factors beyond their control. The standard-setting process should be based on industrial engineering studies and current cost data, not an attempt to 'eliminate' favorable variances. A candidate selecting this option may have confused standard-setting rigor with budget manipulation — tightening standards to make variances disappear defeats the purpose of variance analysis as a diagnostic tool.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // 2: BD-021 — Capital Expenditure Budget → Evaluate
  'P1-BD-021': {
    "Stem": "Underhill Manufacturing's CFO, Marcus Chen, must present the three-year capital expenditure plan to the board of directors. The company currently operates with equipment averaging 14 years old — maintenance costs have increased 22% over the past two years and unplanned downtime caused $340,000 in lost production last year. Marcus's team prepared three scenarios: (1) replace all production equipment immediately at $4.2 million, financed through a term loan at 7.2%, projected to reduce maintenance costs by $280,000/year and eliminate 80% of downtime losses; (2) phase replacement over four years at $1.1 million/year, maintaining some older equipment through the transition but spreading the financing burden; or (3) continue with the current equipment and increase the maintenance budget by $95,000/year while adding a second maintenance shift. The board is divided — two directors argue that $4.2 million in new debt will pressure the debt-to-equity covenant (currently 1.8:1, covenant limit 2.0:1). Which recommendation should Marcus present?",
    "Choices": {
      "A": "Recommend the immediate replacement (Scenario 1) — the $280,000 annual maintenance savings plus $272,000 in avoided downtime losses ($340,000 x 80%) total $552,000 in annual benefits, yielding a 13.1% annual return on the $4.2 million investment, which exceeds the 7.2% borrowing cost and justifies the covenant risk",
      "B": "Recommend the four-year phase (Scenario 2) — it captures most of the equipment modernization benefit while limiting annual financing to $1.1 million, preserving debt covenant headroom (estimated 0.15:1 impact vs. 0.42:1 for Scenario 1), and allowing the company to adjust if demand conditions change",
      "C": "Recommend maintaining current equipment with increased maintenance (Scenario 3) — the $95,000 annual cost is significantly less than either capital scenario, and the company can defer major capital decisions until interest rates decline or equipment prices soften",
      "D": "Recommend Scenario 1 for the two oldest production lines (60% of downtime) at $2.5 million, keeping the remaining equipment under Scenario 3 maintenance — this targets the highest-ROI replacement while limiting debt issuance"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The phased approach (Scenario 2) best balances competing objectives: equipment modernization, debt covenant preservation, and operational flexibility. While Scenario 1 offers the highest theoretical return ($552K annual benefit on $4.2M = 13.1%), it adds substantial debt that would push the debt-to-equity ratio to approximately 2.22:1 based on the current capital structure — violating the 2.0:1 covenant. Lenders could call the loan or impose penalty rates. Scenario 2 limits annual financing to $1.1M (impacting the ratio by only ~0.15:1, well within covenant headroom) while still capturing modernization benefits incrementally. Under CMA Part 1 capital budgeting, the optimal capital expenditure decision is not always the one with the highest NPV — financing feasibility and covenant compliance are binding constraints that the CFO must evaluate. Additionally, the phased approach preserves the option to adjust the replacement schedule if demand or technology changes, while Scenario 1 commits the full $4.2M immediately. A common exam trap is to default to the highest-return option without evaluating financing constraints.",
    "ExplanationWrongA": "Scenario 1 delivers the highest annual benefit ($552,000) but ignores the debt covenant constraint. The $4.2 million term loan would increase total debt sufficiently to push the debt-to-equity ratio above the 2.0:1 covenant limit — a covenant violation that could trigger accelerated repayment, penalty interest rates, or lender intervention. Under CMA Part 1, capital budgeting decisions must be evaluated within the organization's financing constraints, not just on project-level returns. The board directors raising the covenant concern have identified a legitimate binding constraint. A candidate selecting this option may have calculated the return correctly but failed to apply the evaluate-level skill of considering whether the organization can actually finance the project without violating existing agreements.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Scenario 3 defers capital investment entirely, treating the maintenance cost escalation as an operating expense rather than a capital problem. However, the root cause is systematic: 14-year-old equipment with accelerating maintenance costs and significant downtime losses ($340,000 last year). Adding a second maintenance shift treats the symptom (more maintenance capacity) rather than the cause (aging, unreliable equipment). The $95,000/year increase in maintenance spending will likely continue to escalate as equipment ages further. Deferring the decision also risks a catastrophic failure that could halt production entirely — a risk the capital expenditure budget exists to mitigate. A candidate selecting this option may have prioritized near-term cost minimization over long-term asset reliability planning.",
    "ExplanationWrongD": "Option D proposes a partial replacement — targeting only the two oldest lines. While creative, this approach creates an operational mismatch: new equipment on two lines operating alongside aging equipment on others creates inconsistent production speeds, quality standards, and maintenance schedules. More importantly, the analysis substitutes the CFO's judgment about which lines to replace for a systematic evaluation of total cost of ownership across all equipment. The phased approach (Scenario 2) addresses this more systematically by replacing equipment on a planned schedule with consistent financing, rather than cherry-picking lines based on a single metric (downtime percentage). A candidate selecting this option may have attempted to compromise between Scenarios 1 and 3 without recognizing that partial, unplanned replacement creates its own operational problems.",
    "Difficulty": "Very Difficult",
    "DifficultyScore": 5,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // 3: BD-023 — Direct Labor Budget → Evaluate
  'P1-BD-023': {
    "Stem": "Whitmore Industries' production director, James Okonkwo, is finalizing the Q2 direct labor budget for presentation to the finance committee. The production schedule calls for 8,000 units, each requiring 2.0 direct labor hours. James's permanent workforce of 42 employees provides 8,400 hours per quarter at $18.00/hour (fully loaded). To meet the 16,000 total hours required, three options are available: (A) hire 15 temporary workers at $22.50/hour (25% premium) with $1,200 onboarding cost each — they reach full productivity in week 3; (B) authorize overtime for permanent employees at time-and-a-half ($27.00/hour) up to the contractual cap of 80 hours per employee per quarter; or (C) subcontract the overflow production to a certified partner at $24.00/unit equivalent labor cost. The VP of Operations prefers overtime to retain quality control. The CFO is concerned about the overtime premium eroding Q2 margins. Which recommendation should James present to the finance committee?",
    "Choices": {
      "A": "Staff entirely with permanent workers — lay off excess in Q3. This minimizes the hourly rate ($18.00) and avoids temporary-worker quality risks, though severance costs and rehiring expenses in future quarters would apply",
      "B": "Use a combination of capped overtime for all 42 permanent employees (3,360 hours at $27.00 = $90,720 premium) plus 6 temporary workers (2,520 hours at $22.50 = $56,700 plus $7,200 onboarding) to cover the remaining 4,240 hours — this balances cost, quality, and flexibility while respecting the contractual overtime cap",
      "C": "Authorize overtime for the full 7,600-hour gap — 42 employees working an additional 181 hours each, well above the 80-hour contractual cap, at a total overtime cost of $205,200. This retains all production in-house with the trained permanent workforce",
      "D": "Subcontract all overflow production to the certified partner at $24.00/unit equivalent — this eliminates overtime entirely, avoids temporary-worker onboarding costs, and transfers production risk to the subcontractor"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The combination approach best balances the three competing objectives: cost minimization, quality control, and contractual/regulatory compliance. Permanent workers provide the base 8,400 hours at the lowest rate ($18.00/hour). Capped overtime (80 hours x 42 employees = 3,360 hours) adds production capacity from the trained workforce at $27.00/hour — within the contractual limit. The remaining gap (16,000 - 8,400 - 3,360 = 4,240 hours) is filled by 6 temporary workers, whose $22.50/hour rate plus onboarding ($7,200) is lower than extended overtime at $27.00. Total labor cost: $151,200 (base) + $90,720 (overtime) + $56,700 (temps) + $7,200 (onboarding) = $305,820. Under CMA Part 1 budgeting, the direct labor budget must balance cost efficiency with operational constraints — the overtime cap is a binding constraint, and exceeding it (Option C) creates legal and employee-relations risk. A common exam trap is to minimize the hourly rate without considering capacity constraints or contractual limits.",
    "ExplanationWrongA": "Option A (permanent-only staffing) ignores the quarterly demand fluctuation. Hiring permanent workers for Q2 peak demand and laying them off in Q3 creates severance costs, unemployment insurance premium increases, and significant morale damage. The apparent $18.00/hour savings versus temporary workers at $22.50 is offset by (1) severance of approximately 2 weeks' pay per laid-off worker (~$21,600), (2) rehiring and retraining costs in future peak quarters, and (3) reputational damage that makes future hiring more difficult and expensive. Under CMA Part 1, labor budget decisions must consider the full cost of workforce management, not just the hourly wage rate. A candidate selecting this option may have minimized the visible hourly cost without accounting for the hidden costs of workforce instability.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C proposes 181 overtime hours per employee — more than double the contractual cap of 80 hours. This creates a direct labor-law compliance violation and potential grievance exposure. Even if employees voluntarily accept the hours, the company violates the negotiated contract and potentially applicable labor regulations. The overtime premium ($205,200) also exceeds the combined cost of Option B ($305,820 total vs. $357,120 total for pure overtime). More critically, worker fatigue from 7,600 overtime hours concentrated across 42 people substantially increases the risk of quality defects and workplace injuries — costs not captured in the labor rate alone. A candidate selecting this option may have prioritized in-house production control at any cost, ignoring contractual constraints and hidden quality/safety costs.",
    "ExplanationWrongD": "Option D subcontracts all overflow production at $24.00/unit equivalent. For 4,240 hours / 2.0 hours per unit = 2,120 units, the subcontracting cost is $50,880 — lower than temporary workers ($56,700 + $7,200 = $63,900). However, this option cedes all production flexibility: if the subcontractor delivers late or below quality standards, Whitmore has no internal capacity to absorb the shortfall (permanent workers are fully utilized, and no overtime or temporary workers are authorized). The subcontractor's $24.00/unit rate may also increase if demand exceeds expectations. Additionally, transferring proprietary production processes to an external partner creates intellectual property and quality control risks. Under CMA Part 1, make-vs-buy decisions in the direct labor budget must consider not just unit cost but also quality control, schedule reliability, and strategic capability retention. A candidate selecting this option may have minimized the visible labor cost without evaluating the operational risks of depending entirely on an external partner for peak production.",
    "Difficulty": "Very Difficult",
    "DifficultyScore": 5,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // 4: BD-028 — Direct Labor Budget Calculation → Analyze
  'P1-BD-028': {
    "Stem": "Crownridge Manufacturing's budget analyst, Priya Anand, is reviewing the direct labor budget for Q3. The production plan calls for 8,000 units at 2.0 direct labor hours each. The standard labor rate is $18.00/hour for permanent employees. However, the HR director reports that recent market wage pressure will push the actual rate to $19.50/hour starting in August (Q3 months: July, August, September — production is evenly distributed across months). Priya must determine the total budgeted direct labor cost and analyze the labor rate variance impact. The plant manager argues the budget should use the old $18.00 rate since the increase was not approved when the original annual budget was set. The CFO wants to know the budgeted cost and whether the labor rate increase constitutes a budget revision trigger. Which analysis is correct?",
    "Choices": {
      "A": "Budgeted cost = $288,000 (8,000 x 2 x $18.00). The labor rate increase is an external market event that should be disclosed in variance analysis footnotes but does not warrant a budget revision — managers should be held to the original approved budget",
      "B": "Budgeted cost = $312,000 (8,000 x 2 x $19.50). The labor rate increase is a known, structural change in the cost baseline that should be reflected in the Q3 budget — holding the Q3 budget at $18.00 when the company knows it will pay $19.50 would produce a meaningless $24,000 unfavorable variance",
      "C": "Budgeted cost = $296,000 — using the blended rate: July at $18.00 (one-third of production) and August-September at $19.50 (two-thirds). The budget should reflect the actual expected cash outflow, recognizing the timing of the wage change within the quarter",
      "D": "Budgeted cost = $300,000 — split the difference between the old and new rates at $18.75. This avoids taking a position on whether the increase is permanent while providing a reasonable planning estimate"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "The correct budgeted cost uses a blended rate reflecting the timing of the wage change: July production (one-third of 16,000 hours = 5,333.3 hours) at $18.00, plus August-September production (two-thirds = 10,666.7 hours) at $19.50. Calculation: (5,333.3 x $18) + (10,666.7 x $19.50) = $96,000 + $208,000 = $304,000 (rounded). More precisely: 8,000 units / 3 months = 2,666.7 units/month. July: 2,666.7 x 2 x $18 = $96,000. Aug-Sep: 5,333.3 x 2 x $19.50 = $208,000. Total = $304,000. Under CMA Part 1 budgeting, a budget revision is warranted when a known, structural change in the cost baseline will persist. The wage increase to $19.50 is effective August 1 — it is not a proposal or estimate, it is an implemented change. The budget should reflect expected costs, not aspirational ones. The analyze-level skill tests the candidate's ability to decompose a rate change by its timing within the budget period and apply a blended rate rather than treating the quarter monolithically.",
    "ExplanationWrongA": "Option A uses the old $18.00 rate for the entire quarter ($288,000). While the original annual budget was approved at this rate, the wage increase has already been implemented (effective August 1) — this is not a proposal awaiting approval. Holding the Q3 budget at an outdated rate produces a guaranteed $24,000 unfavorable variance that provides zero diagnostic value — the company knows exactly why actual costs exceed budget. The purpose of the flexible budget is to provide a meaningful benchmark for performance evaluation; a benchmark known to be wrong fails this purpose. A candidate selecting this option may have confused budget rigidity with budget discipline — the CMA exam distinguishes between holding managers accountable (appropriate for controllable factors) and using known-wrong assumptions (inappropriate for planning).",
    "ExplanationWrongB": "Option B uses the $19.50 rate for the entire quarter ($312,000). While this correctly recognizes that the wage increase is structural and should be reflected, it ignores the timing of the change within the quarter. July production (2,666.7 units) will be produced at the old $18.00 rate because the increase takes effect August 1. Applying $19.50 to July production overstates Q3 expected labor cost by approximately $8,000, creating a budget cushion that masks Q4's true labor cost run-rate. Under CMA Part 1, the budget should reflect the actual expected cash outflow — a blended rate that accounts for the within-quarter timing of rate changes is more precise and useful for cash planning. A candidate selecting this option correctly identified the need to update the budget but applied an overly simplistic quarterly-average approach.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Option D uses an arbitrary blended rate of $18.75 — the simple average of $18.00 and $19.50. This approach ignores the unequal weighting of production across months: two-thirds of Q3 production occurs after the rate increase, so the effective rate is closer to $19.50 than to $18.00. The $18.75 rate is not supported by any factual basis — it is a compromise figure, not an analytically derived one. While the resulting $300,000 might appear 'reasonable,' it is approximately $4,000 below the actual expected cost, creating a small but unnecessary planning error. Under CMA Part 1, budget assumptions must be grounded in factual analysis, not convenient averages. A candidate selecting this option may have defaulted to splitting the difference rather than performing the weighted calculation.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": true
  },

  // 5: BD-029 — Standard Cost Setting Basis → Evaluate
  'P1-BD-029': {
    "Stem": "Dellwood Industries' controller, Sarah Kessler, is reviewing the standard cost system before the annual budget cycle. The company sets standard costs for direct materials based on expected efficient usage and negotiated purchase prices. This year, the purchasing director, Raj Mehta, proposes two changes: (1) tighten the material usage standard from 3.2 lbs/unit to 3.0 lbs/unit, citing a new cutting technology expected to reduce waste by 6%, and (2) lower the standard price from $12.50/lb to $11.80/lb, reflecting a new long-term supplier contract. The production VP, Mark Delgado, objects strongly to both changes. He argues that tighter standards will produce unfavorable variances in the first two quarters while the cutting technology is calibrated, making his department look bad and potentially affecting his bonus. He proposes keeping the old standards for one more year and attributing any actual cost improvements to 'favorable efficiency variances.' The CEO asks Sarah to evaluate both positions and recommend a standard-setting approach. Which recommendation is most appropriate?",
    "Choices": {
      "A": "Adopt the purchasing director's tighter standards immediately — standard costs should reflect currently attainable efficient performance, and the new cutting technology and supplier contract represent the best available information about expected costs",
      "B": "Retain the existing standards (3.2 lbs at $12.50) for one more year as the production VP requests — changing standards during the year undermines performance evaluation continuity, and the department should earn the benefit of any cost improvements through favorable variances before standards are tightened",
      "C": "Adopt the price standard change to $11.80/lb immediately (reflecting the executed supplier contract) but phase the usage standard from 3.2 to 3.0 lbs over two quarters — this distinguishes between a known, implemented cost change (the contract) and a technology-driven estimate that requires validation",
      "D": "Create two sets of standards — one for budgeting (tighter, forward-looking) and one for performance evaluation (existing, historical) — so the budget accurately forecasts costs while managers are evaluated against a stable, achievable baseline"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "The phased approach best applies the CMA Part 1 principle that standard costs should reflect currently attainable performance while recognizing the distinction between known and estimated changes. The price standard change to $11.80/lb is based on an executed supplier contract — it is a known, implemented change, not a forecast. Delaying its adoption would mean the purchasing department's material price variance incorporates a known-wrong baseline. The usage standard change from 3.2 to 3.0 lbs is based on an estimate of technology-driven waste reduction — the 6% improvement has not yet been demonstrated in production. Phasing the usage standard over two quarters (e.g., 3.1 in Q1, 3.0 in Q2) provides a gradual target that acknowledges the learning curve while moving toward the expected efficient level. This approach distinguishes between a price change that has already occurred (contract signed) and an efficiency estimate that requires operational validation, which is the evaluate-level skill of determining which standards are fact-based versus forecast-based.",
    "ExplanationWrongA": "Option A adopts both tighter standards immediately. While both changes may ultimately prove correct, the usage standard reduction from 3.2 to 3.0 lbs is based on an estimate of technology-driven improvement — the cutting technology has not yet been calibrated or validated in production. Imposing the full 0.2 lb reduction immediately creates a high probability of unfavorable variances in Q1-Q2 that reflect learning-curve effects rather than poor performance. Under CMA Part 1, standards should be attainable but challenging — a standard that is unattainable in the first quarter (before the technology is proven) is demotivating, not motivating. The production VP's concern about his bonus is self-interested but identifies a legitimate standard-setting issue: standards imposed without operational validation undermine the performance evaluation system. A candidate selecting this option may have assumed that more aggressive standards are always better, without evaluating whether the standard is currently achievable.",
    "ExplanationWrongB": "Option B retains the old standards for another full year. This ignores that the supplier contract has already been executed — the company WILL pay $11.80/lb, not $12.50/lb. Using the old price standard for a full year means the material price variance will show a persistent 'favorable' variance of $0.70/lb that reflects nothing more than comparing actual costs against an obsolete standard. This 'phantom favorable variance' provides zero diagnostic value and may mask unfavorable usage variances that require management attention. Under CMA Part 1, standard costs should be updated when conditions change materially — an executed supplier contract at a different price is a material condition change. A candidate selecting this option may have prioritized stability over accuracy, not recognizing that a standard known to be wrong undermines variance analysis as a control tool.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Option D proposes dual standards — one for budgeting and one for performance evaluation. While this may appear to solve both problems, it creates a fundamental inconsistency in the control system. If managers know they are evaluated against a 'softer' standard than the one used for planning, they have no incentive to achieve the budget target. Dual standards also double the administrative burden of the standard cost system (two sets of variance reports, two reconciliation processes) and create confusion about which numbers represent 'real' performance. Under CMA Part 1, the standard cost system should serve both planning and control functions with a single, well-calibrated set of standards. A candidate selecting this option may have attempted to satisfy all stakeholders simultaneously without recognizing that dual standards undermine the integrity of the management control system.",
    "Difficulty": "Very Difficult",
    "DifficultyScore": 5,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // ========== BATCH 2 ==========

  // 6: BD-036 — Operating vs Financial Budget → Analyze
  'P1-BD-036': {
    "Stem": "Kirkwood Manufacturing's controller, David Okonkwo, is reconciling the Q2 master budget package before the audit committee meeting. The operating budget projects Q2 net income of $420,000 on sales of $1.8 million. The cash budget — built from the same sales forecast and production assumptions — projects a $65,000 cash deficit for the quarter. The audit committee chair, noting the $485,000 gap between profit and cash, questions whether the budget contains an arithmetic error. David must explain which items in the master budget architecture create the divergence between accrual-basis profitability and cash-basis liquidity. He isolates four items: depreciation of $72,000, credit sales of $1.26 million (70% of total sales, with 40% collected in the month of sale and 60% in the following month), a planned $140,000 equipment purchase, and a $45,000 inventory build for Q3 seasonal demand. Which analysis correctly explains the profit-to-cash divergence?",
    "Choices": {
      "A": "The $485,000 gap is primarily caused by the $140,000 equipment purchase — capital expenditures are recorded in the cash budget (financial budget) but excluded from the operating budget. The remaining $345,000 gap represents normal working capital timing differences that do not require separate explanation",
      "B": "The divergence is explained by four items: (1) $72,000 depreciation reduces operating income but not cash, (2) delayed credit sales collection — of Q2's $1.26M credit sales, only $504,000 is collected in Q2 (40%), leaving $756,000 uncollected, (3) the $140,000 equipment purchase consumes cash but appears only in the capital budget, and (4) the $45,000 inventory build consumes cash for materials/labor that are expensed in COGS but paid before the goods are sold",
      "C": "The $485,000 gap indicates a data linkage error — the operating and cash budgets must be mechanically connected because they share the same sales forecast and production assumptions, so the two budgets should reconcile within a small rounding tolerance",
      "D": "The $485,000 divergence is almost entirely explained by credit sales timing — Q2 recognizes $1.8M in revenue but collects only $504,000 from Q2 credit sales plus collections from Q1 receivables, and the $72,000 depreciation deduction widens the accrual-to-cash gap"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The $485,000 gap between $420K operating income and -$65K cash deficit is explained by four distinct reconciling items: (1) Depreciation ($72K) is a non-cash expense that reduces operating income but does not affect cash — it widens the gap because operating income is lower than it would be if depreciation were excluded. (2) Credit sales timing: of Q2's $1.26M credit sales, only 40% ($504K) is collected in Q2 — the remaining $756K becomes accounts receivable and will be collected in Q3. This means the operating budget recognizes $1.26M in revenue while the cash budget captures only $504K + cash sales of $540K (30% of $1.8M) = $1.044M. (3) The $140K equipment purchase is a capital budget item — it consumes cash but does not appear in the operating budget at all (it will be depreciated over future periods). (4) The $45K inventory build consumes cash for materials and labor that are capitalized into inventory — these costs are incurred and paid in Q2 but expensed through COGS only when the inventory is sold. Under CMA Part 1 master budget construction, the operating and financial budgets serve different purposes and use different accounting bases — reconciling them requires identifying each item that affects only one budget. The analyze-level skill is decomposing the aggregate gap into its component causes.",
    "ExplanationWrongA": "Option A identifies the capital expenditure ($140K) but dismisses the remaining $345K as 'normal working capital.' Under CMA Part 1, 'normal working capital' is not an explanation — it is an acknowledgment that the candidate cannot identify the specific reconciling items. The $345K gap is fully explainable through depreciation ($72K), credit sales timing (the difference between revenue recognized and cash collected), and the inventory build ($45K). Professional controllers must be able to trace each component of the operating-income-to-cash-flow reconciliation, not attribute unexplained gaps to generic categories. A candidate selecting this option recognized the capital budget item but failed to analyze the remaining drivers.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C assumes that shared assumptions mean the budgets should produce identical bottom lines. This reflects a fundamental misunderstanding of master budget architecture. The operating budget and financial budget serve different purposes: the operating budget uses accrual accounting (revenue when earned, expenses when incurred), while the cash budget uses cash-basis accounting (cash when received, cash when paid). They should diverge whenever depreciation, credit sales, prepaid expenses, inventory changes, or capital expenditures exist — all normal features of a manufacturing business. Under CMA Part 1, 'mechanically connected' means the budgets share input assumptions (sales forecast, production plan), not that they produce identical outputs. A candidate selecting this option may have confused budget integration (shared assumptions) with budget identity (identical results), which is a common exam trap.",
    "ExplanationWrongD": "Option D identifies credit sales timing and depreciation as drivers but omits the capital expenditure ($140K) and inventory build ($45K) — two material items that together account for $185K of the $485K gap. More importantly, this analysis has the depreciation effect directionally wrong: depreciation REDUCES operating income without affecting cash, which means operating income is LOWER than it would be without depreciation — this narrows, not widens, the profit-to-cash gap (operating income without depreciation would be $492K, not $420K). The candidate must correctly identify the directional effect of each reconciling item. A candidate selecting this option recognized some drivers correctly but omitted material items and mischaracterized depreciation's directional effect.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": false
  },

  // 7: BD-037 — Operating vs Financial Budget → Analyze
  'P1-BD-037': {
    "Stem": "Ledgemont Corporation's finance director, Amara Osei, is training new budget analysts on master budget construction. She presents a scenario: the company manufactures industrial valves and is preparing its annual master budget. The sales budget projects 50,000 units at $85 each. The production budget calls for 52,000 units (including ending inventory requirements). The direct materials budget requires 156,000 lbs of brass at $4.20/lb. The capital expenditure budget includes a $380,000 CNC machine replacement. Amara asks the analysts: 'If we identify a line item in the budget package, how do we determine whether it belongs to the operating budget or the financial budget?' She provides four classification principles. Which principle correctly distinguishes the two budget categories?",
    "Choices": {
      "A": "The operating budget includes all items that require cash disbursement within the budget year, while the financial budget includes only non-cash items such as depreciation and accruals",
      "B": "The operating budget encompasses revenue-generating and cost-incurring activities reported on the income statement (sales, production, materials, labor, overhead, S&A), while the financial budget encompasses the balance sheet, cash flows, and capital expenditures that affect the company's financial position",
      "C": "The operating budget covers only variable costs that change with production volume, while the financial budget covers all fixed costs and long-term commitments",
      "D": "The operating budget is prepared by department managers, while the financial budget is prepared exclusively by the treasury department — the classification depends on who prepares the budget, not what it contains"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The correct classification principle is based on the financial statement each budget component maps to. The operating budget encompasses all activities that generate revenue and incur costs in the normal course of business — sales, production, direct materials, direct labor, manufacturing overhead, and selling/administrative expenses. These items ultimately flow to the income statement. The financial budget encompasses items that affect the company's financial position: the capital expenditure budget (affecting long-term assets on the balance sheet), the cash budget (tracking liquidity), and the budgeted balance sheet and statement of cash flows. Under CMA Part 1 budgeting, this income-statement-vs-balance-sheet distinction is the foundational organizing principle of the master budget — the operating budget answers 'how will we perform operationally,' while the financial budget answers 'what resources do we need and how will we finance them.' The analyze-level skill is applying this classification framework to specific budget line items rather than memorizing a list.",
    "ExplanationWrongA": "Option A incorrectly ties the classification to cash disbursement. Both the operating budget AND the financial budget include items that require cash disbursement — paying for direct materials (operating) and purchasing equipment (financial/financial) both consume cash. Conversely, the operating budget includes non-cash items such as depreciation when allocated to overhead rates in a standard cost system. The cash budget (part of the financial budget) is specifically designed to track ALL cash inflows and outflows regardless of budget category. The classification is based on the financial statement destination (income statement vs. balance sheet/cash flow), not on whether cash changes hands. A candidate selecting this option may have confused the cash budget (which belongs to the financial budget) with the principle for classifying all budget items.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C incorrectly ties the classification to cost behavior (variable vs. fixed). Both budget categories contain variable and fixed components: the operating budget includes fixed costs (straight-line depreciation on factory equipment, salaried production supervisors, facility leases) alongside variable costs (direct materials, sales commissions). The financial budget includes both variable items (cash balances that fluctuate with operations) and fixed items (scheduled loan repayments). Cost behavior (variable vs. fixed) is a cost accounting concept used for CVP analysis and flexible budgeting — it is not the organizing principle of the master budget structure. A candidate selecting this option may have conflated cost behavior classification with budget architecture classification, which are distinct concepts tested under different CMA Part 1 learning outcomes.",
    "ExplanationWrongD": "Option D incorrectly ties the classification to the department that prepares the budget. In practice, the operating budget is a collaborative effort involving sales, production, purchasing, HR, and finance departments — not just 'department managers.' The financial budget, while coordinated by the finance/treasury function, draws input from capital project sponsors, department heads requesting equipment, and the CFO's office. More importantly, classification should be based on the nature and purpose of the budget item, not its preparer. Under CMA Part 1, budgets are classified by their role in the master budget architecture, not by organizational responsibility. A candidate selecting this option may have confused responsibility accounting (who is accountable for a budget) with budget classification (what type of plan the budget represents).",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": false
  },

  // 8: BD-044 — Time Series Forecasting → Evaluate
  'P1-BD-044': {
    "Stem": "Sandpiper Industries' demand planning manager, Naomi Singh, is presenting the Q4 sales forecast methodology to the S&OP committee. The company's quarterly sales data over three years shows a clear seasonal pattern — Q2 sales are consistently 35-40% above the annual quarterly average, while Q4 sales run 15-20% below average. Naomi's team evaluated two forecasting approaches: Model A uses a simple four-quarter moving average that smooths the seasonal peaks ($127,500 average quarterly forecast). Model B decomposes the time series into trend, seasonal, and cyclical components, applying seasonal indices derived from the three-year history — producing a Q4 forecast of $98,800 (reflecting the Q4 seasonal low). The VP of Sales, whose bonus is tied to forecast accuracy, argues that Model A is 'safer' because the higher $127,500 forecast gives the sales team a more ambitious target. The CFO is concerned that over-forecasting Q4 will lead to excess inventory and cash tied up in unsold goods. Which recommendation should Naomi present?",
    "Choices": {
      "A": "Recommend Model A (moving average) — the $127,500 forecast sets an ambitious target that will motivate the sales team to outperform, and the higher forecast ensures adequate inventory to capture any upside demand surprise",
      "B": "Recommend Model B (time series decomposition) because it incorporates the known seasonal pattern — Q4 has been 15-20% below average for three consecutive years, and ignoring this structural pattern would produce a forecast known to be biased high, leading to excess inventory carrying costs and potential obsolescence",
      "C": "Recommend taking the average of both models ($113,150) as a compromise forecast — this captures the directional signal from both approaches and hedges against model error in either direction",
      "D": "Recommend Model B for production planning (to avoid excess inventory) but communicate Model A's $127,500 figure to the sales team as a stretch target — this separates operational planning from sales motivation"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Model B (time series decomposition) is the appropriate forecasting methodology because it accounts for the documented seasonal pattern — Q4 sales that run 15-20% below the annual quarterly average. Over three years, this pattern has been consistent, making it a structural feature of the demand pattern, not random variation. Using Model A's moving average ($127,500) would produce a Q4 forecast known to be biased high by approximately $28,700 — and this bias is systematic (predictable), not random. Under CMA Part 1 forecasting, the objective is accuracy — forecasts that systematically miss in a known direction undermine the entire planning chain (production over-schedules, purchasing over-orders, and the cash budget overestimates collections). The VP of Sales's preference for an 'ambitious target' conflates forecasting (predicting what will happen) with goal-setting (aspiring to what could happen). These are distinct activities — the forecast should be the best estimate of actual demand, while stretch targets can be layered on top as motivational tools. The evaluate-level skill is distinguishing between forecast methodology selection (which should minimize bias) and performance target setting (which may incorporate aspiration).",
    "ExplanationWrongA": "Model A ignores the structural seasonal pattern that has persisted for three years. The moving average treats Q4 the same as Q2, despite Q4 consistently running 15-20% below average and Q2 35-40% above. The resulting $127,500 forecast is systematically biased high for Q4 — this is not a 'motivational target,' it is a forecast error. The consequences cascade through the planning chain: production will schedule for 127,500 units of demand, builds excess inventory, ties up cash in working capital, and potentially creates obsolescence if the goods are seasonal or perishable. Under CMA Part 1, the forecast is the input to the production, purchasing, and cash budgets — errors in the forecast propagate through the entire master budget. A candidate selecting this option may have confused forecasting accuracy with sales motivation, which are separate management functions.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Averaging two forecasts with different methodologies does not produce a better forecast — it produces an average of a good forecast and a biased one. Since Model B correctly accounts for seasonality and Model A does not, averaging them introduces a known directional bias into the final number. The resulting $113,150 forecast would still overstate Q4 demand by approximately $14,350, leading to excess inventory — just less of it. Under CMA Part 1, forecast combination methods (e.g., weighted averaging of multiple models) should only be applied to models that are each independently valid and unbiased — combining a valid model with a biased one contaminates the result. A candidate selecting this option may have defaulted to compromise rather than evaluating which model is methodologically sound.",
    "ExplanationWrongD": "Option D proposes using different numbers for different audiences — Model B for operations and Model A for sales. This creates a fundamental disconnect in the planning system: if production plans for 98,800 units of demand but sales is targeting 127,500, the production schedule will be insufficient to support the sales target (leading to stockouts if sales achieves the target) OR production will be pressured to override the operations forecast (creating confusion about which number drives the supply chain). Under CMA Part 1, the sales forecast is the single starting point for the entire master budget — maintaining two different forecasts for different purposes undermines the integrated nature of the budget. A candidate selecting this option may have attempted to satisfy both stakeholders without recognizing that forecast integrity requires a single, best-estimate number that all functions align behind.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // 9: BD-058 — Budget Committee Role → Evaluate
  'P1-BD-058': {
    "Stem": "Ivorycrest Corporation's CEO, Patricia Owens, must restructure the annual budget process after last year's cycle took 14 weeks and produced budgets that three department heads publicly disputed at the board presentation. The current structure: each department submits its budget to the CFO, who consolidates and presents to the board without cross-departmental review. Patricia is evaluating three governance models: (1) Create a formal budget committee of senior managers from sales, production, finance, HR, and R&D that meets weekly during budget season to review and align departmental submissions — estimated to add 3 weeks to the process but improve cross-functional coordination; (2) Centralize all budget preparation in the finance department with department heads providing input data only — estimated to reduce the process to 8 weeks; (3) Implement a bottom-up participative process where each department prepares its own budget with finance providing templates and consolidating — keeping the 14-week timeline but giving departments full ownership. The board wants Patricia's recommendation. Which governance model should she adopt?",
    "Choices": {
      "A": "Adopt Model 1 (budget committee) — cross-functional review by senior managers from all major functions ensures departmental budgets align with overall company strategy, prevents individual departments from optimizing locally at the expense of corporate goals, and the 3 additional weeks are an acceptable investment in budget quality given last year's disputes",
      "B": "Adopt Model 2 (finance-centralized) — the finance department has the technical expertise to build internally consistent budgets, the 8-week timeline represents a 43% process efficiency gain, and removing departmental negotiation eliminates the disputes that embarrassed the company at last year's board presentation",
      "C": "Adopt Model 3 (bottom-up participative) — giving departments full budget ownership increases managerial buy-in and accountability, the 14-week timeline is the cost of participation, and last year's disputes indicate the departments care about their budgets, which is a positive engagement signal",
      "D": "Adopt a hybrid: finance prepares the initial budget draft (Model 2 approach), the budget committee reviews and adjusts for cross-functional alignment (Model 1), and department heads have final sign-off authority on their sections — combining technical accuracy, coordination, and ownership"
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Model 1 (budget committee) directly addresses the root cause of last year's failure: the absence of cross-departmental review. When department heads publicly dispute budgets at the board presentation, the problem is not that finance lacked technical expertise — it is that departments never saw or agreed to each other's numbers before the board saw them. A budget committee composed of senior managers from all major functions provides the forum for departments to reconcile competing resource claims (e.g., sales wants more inventory than production can build, R&D wants funding that reduces short-term profits) BEFORE the budget reaches the board. Under CMA Part 1 budgeting, the budget committee serves as the coordination mechanism that aligns functional plans into a coherent organizational plan. The 3 additional weeks are an investment in budget quality — the alternative (repeating last year's board presentation with disputed numbers) has higher organizational cost. The evaluate-level skill is identifying that the governance model must solve the specific problem (lack of cross-functional coordination) rather than optimizing a secondary metric (process speed).",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Model 2 (finance-centralized) solves for process speed (14 weeks to 8 weeks) but exacerbates the root problem. Last year's disputes occurred precisely because departments felt excluded from a finance-driven process — centralizing budget preparation further removes departments from decision-making, likely increasing resistance rather than reducing it. The budget is not merely a financial document — it is the operational plan for the entire organization, and line managers possess knowledge about their functions (production constraints, market conditions, staffing challenges) that finance cannot replicate. Under CMA Part 1, the budget serves as both a planning tool and a coordination mechanism — centralizing all preparation in finance transforms it from a collaborative plan to a finance-department mandate. A candidate selecting this option may have prioritized efficiency over effectiveness and assumed that technical accuracy alone produces budget quality.",
    "ExplanationWrongC": "Model 3 (bottom-up participative) retains the 14-week timeline and does not add any cross-functional coordination mechanism beyond what already failed last year. Participative budgeting has documented benefits (managerial buy-in, information sharing from those closest to operations), but without a coordinating body to reconcile competing departmental requests, the process produces budgets that reflect departmental aspirations rather than organizational constraints. The three department heads who disputed the budget at last year's board presentation were fully 'participating' in the process — their dispute demonstrated that participation without coordination does not produce alignment. A candidate selecting this option may have over-weighted the benefits of participation without recognizing that coordination is the missing element.",
    "ExplanationWrongD": "Option D combines elements of all three models into a hybrid. While superficially appealing, this approach creates governance ambiguity: who has final authority if the budget committee adjusts finance's draft and the department head refuses to sign? The multiple approval layers add process steps without clarifying decision rights. Under CMA Part 1, budget governance structures should have clear roles and responsibilities — a hybrid that gives three different bodies overlapping authority over the same numbers creates confusion rather than accountability. The budget committee structure (Model 1) already incorporates finance expertise (finance sits on the committee) and departmental input (department heads are committee members), achieving the benefits of the hybrid without the governance ambiguity. A candidate selecting this option may have been attracted to combining 'the best of all models' without recognizing that governance structures require clear, not distributed, authority.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // 10: BD-065 — S&A Expense Budget → Analyze
  'P1-BD-065': {
    "Stem": "Prescott Industries' controller, Raj Mehta, is finalizing the annual selling and administrative expense budget. The sales forecast projects $4.8 million in revenue across three product lines. The S&A cost structure includes: sales commissions at 6% of revenue, shipping costs at 2% of revenue, five regional sales managers each earning $85,000 fixed salary, office lease at $9,500/month, and depreciation on headquarters equipment at $24,000/year. The VP of Sales has requested two additional regional managers for a new territory (adding $170,000 in fixed costs) and argues that the incremental managers will generate at least $600,000 in new revenue at the existing commission rate. Raj must classify each S&A cost component as fixed or variable and evaluate whether the VP's expansion proposal makes financial sense. The CEO wants the S&A budget completed before the board meeting. Which analysis correctly classifies the costs and evaluates the expansion?",
    "Choices": {
      "A": "Variable costs: commissions ($288,000 at 6% of $4.8M) and shipping ($96,000 at 2%). Fixed costs: sales manager salaries ($425,000), office lease ($114,000), and depreciation ($24,000). The VP's proposal adds $170,000 in fixed costs against $36,000 in incremental variable commissions (6% of $600K), plus $12,000 in shipping — requiring $218,000 in contribution margin from $600,000 revenue (36.3% CM ratio) just to cover the S&A cost increase, which is unlikely if COGS averages 60-65% of revenue",
      "B": "All S&A costs are variable because they support selling activity — the sales managers could be reassigned if revenue declines, the lease has a 30-day cancellation clause, and depreciation continues regardless of volume but is allocated per unit",
      "C": "Variable costs: commissions and shipping. Fixed costs: salaries, lease, depreciation. The VP's proposal adds $170,000 fixed against $600,000 incremental revenue — at a typical 35% contribution margin ($210,000), the incremental managers would contribute $40,000 after covering S&A costs, so the expansion should be approved",
      "D": "Variable costs: commissions only. Shipping is a step-variable cost that changes in blocks, not continuously. Fixed costs: salaries, lease, depreciation. The VP's proposal should be evaluated on strategic grounds (market entry), not cost analysis alone — the $170,000 investment in a new territory is a long-term strategic decision"
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Option A correctly classifies costs and evaluates the proposal. Commissions (6% of revenue) and shipping (2% of revenue) are variable costs — they change in direct proportion to sales volume. Sales manager salaries ($85K x 5 = $425K), office lease ($9,500 x 12 = $114K), and depreciation ($24K) are fixed costs — they remain constant regardless of sales volume within the relevant range. The VP's proposal requires analysis: the $600,000 incremental revenue would generate incremental variable S&A costs of $36,000 (commissions) + $12,000 (shipping) = $48,000, plus $170,000 in new fixed costs (two managers' salaries) = $218,000 total incremental S&A costs. To cover just the S&A layer, the $600,000 revenue needs a contribution margin of $218,000 / $600,000 = 36.3%. If COGS averages 65% of revenue (typical for manufacturing), the contribution margin is only 35% - 8% (S&A variable) = 27% after variable S&A. With $162,000 in contribution margin from $600K revenue at 27%, the VP's expansion loses approximately $56,000. The analyze-level skill is decomposing S&A costs into their fixed-variable components and using contribution margin analysis to evaluate a spending proposal rather than accepting it at face value.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Option B incorrectly classifies all S&A costs as variable. Manager salaries are committed fixed costs — they do not change if one territory's sales increase or decrease. The lease is a contractual obligation with fixed monthly payments, not a variable cost triggered by sales activity. Depreciation is a fixed cost based on asset life, not sales volume. Under CMA Part 1 cost behavior, variable costs must change in total in direct proportion to changes in activity — none of these three items meet that criterion. The assertion that managers 'could be reassigned' confuses cost behavior classification with cost avoidability — a cost is classified as fixed or variable based on its relationship to activity volume, not on whether the company could theoretically eliminate it. A candidate selecting this option may have confused cost behavior (fixed vs. variable) with cost management (whether a cost can be changed), which are distinct concepts.",
    "ExplanationWrongC": "Option C correctly classifies costs but incorrectly evaluates the expansion. The assumption of a 35% contribution margin ($210,000 on $600K revenue) appears reasonable until we factor in the variable S&A costs. The $600,000 revenue generates $48,000 in variable S&A (commissions + shipping), so the net contribution after variable S&A is $210,000 - $48,000 = $162,000 — less than the $170,000 in incremental fixed costs. The expansion would lose $8,000 at a minimum, and could lose more if the contribution margin is lower or the new territory's shipping costs are higher (greater distances). Under CMA Part 1, spending proposals must be evaluated on their incremental effect on operating income, not on gross contribution before incremental costs. A candidate selecting this option performed the cost classification correctly but failed to apply the full incremental analysis.",
    "ExplanationWrongD": "Option D partially misclassifies shipping as a 'step-variable' cost. Shipping at 2% of revenue is a purely variable cost — it changes in direct proportion to sales (each additional unit shipped incurs shipping cost). While the per-unit shipping rate may change if volume passes a carrier discount threshold, this is rate variability, not step-cost behavior. More critically, the option dismisses the cost analysis in favor of 'strategic grounds.' Under CMA Part 1, strategic decisions must be informed by cost analysis — entering a new territory without evaluating the financial impact substitutes hope for planning. The VP's proposal should be evaluated on both strategic AND financial grounds, and the financial analysis suggests it does not break even. A candidate selecting this option may have deferred to 'strategic importance' to avoid performing the quantitative analysis.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": true
  },

  // ========== BATCH 3 ==========

  // 11: BD-072 — Forecast Accuracy Measurement → Evaluate
  'P1-BD-072': {
    "Stem": "Whitfield Corporation's demand planning team is evaluating two forecasting models for the annual sales budget. Model X (exponential smoothing with trend adjustment) produced a Mean Absolute Percentage Error (MAPE) of 12.8% over the past 24 months, with forecast errors evenly distributed above and below actuals (unbiased). License cost: $4,800/year, requires 4 hours/month of analyst time for parameter tuning. Model Y (machine learning ensemble combining regression, neural network, and seasonal decomposition) produced a MAPE of 8.3% over the same period, with a slight optimistic bias (forecasts averaged 2.1% above actuals). License cost: $18,500/year, requires 18 hours/month of analyst time plus quarterly external consultant review at $3,200/quarter. The VP of Supply Chain argues that Model Y's lower MAPE justifies the investment. The CFO is concerned that the 2.1% optimistic bias in Model Y will systematically over-forecast demand, leading to excess inventory. Which recommendation should the forecasting manager present?",
    "Choices": {
      "A": "Recommend Model Y — its 8.3% MAPE represents a 35% improvement in forecast accuracy (12.8% to 8.3%), and the enhanced accuracy will reduce inventory carrying costs and stockout costs by more than the incremental $26,500 annual cost ($13,700 license delta + analyst time + consultant fees)",
      "B": "Recommend Model X — while its MAPE is higher (12.8%), it is unbiased (errors are symmetric), its total cost of ownership is substantially lower (~$12,000/year vs. ~$45,500/year for Model Y), and the 2.1% systematic over-forecast bias in Model Y would generate approximately $100,800 in excess inventory at Whitfield's average $800,000 monthly cost of goods sold",
      "C": "Recommend running both models in parallel for six months (Model X as the official forecast, Model Y as a shadow) at a cost of $23,300 — this validates Model Y's claimed accuracy improvement with live data before committing to a long-term contract",
      "D": "Recommend Model Y for long-lead-time items (raw materials ordered 8+ weeks in advance, where forecast accuracy matters most) and retain Model X for short-lead-time replenishment — segmenting the forecast by supply chain tier targets investment where accuracy has the highest operational impact"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Model X is the appropriate recommendation. The core issue is not just MAPE — it is that Model Y's lower MAPE comes with a systematic bias (2.1% optimistic) that would directly increase inventory costs. For Whitfield's $800,000 monthly COGS, a 2.1% over-forecast means approximately $16,800 in excess production each month that becomes inventory, tying up cash and risking obsolescence. Annualized, this bias alone costs approximately $100,800-$200,000 in inventory carrying costs (at 15-25% annual carrying cost) — far exceeding any savings from the lower MAPE. Additionally, Model Y's total cost of ownership (~$45,500/year) is nearly 4x Model X (~$12,000/year). Under CMA Part 1 forecasting, accuracy metrics must be evaluated alongside bias: an unbiased model with higher MAPE may produce better operational outcomes than a biased model with lower MAPE because systematic bias propagates through the entire planning chain (production, purchasing, cash). The evaluate-level skill is recognizing that forecast accuracy is a multi-dimensional concept — MAPE alone does not tell the full story, and the candidate must weigh accuracy against bias and cost.",
    "ExplanationWrongA": "Model Y's lower MAPE is achieved at significant cost and with a systematic bias. The candidate must consider the operational cost of the 2.1% optimistic bias — approximately $100,800+ in excess inventory annually. The total cost of Model Y (~$45,500/year) plus the bias cost (~$100,800) exceeds $146,300 in total forecasting-related costs, compared to ~$12,000 for Model X. Even if Model X's less accurate forecast results in some stockout or overstock costs, the delta in model cost plus bias impact almost certainly favors Model X. A candidate selecting this option focused narrowly on MAPE improvement without evaluating the cost of systematic bias, which is a common CMA exam trap — the lowest-MAPE model is not always the best model for operational planning.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C proposes a parallel run at a cost of $23,300 for six months. While validation before commitment is generally prudent, Model Y has already been tested on 24 months of historical data — the parallel run would not generate new information about forecast accuracy or bias beyond what the historical test already revealed (8.3% MAPE, 2.1% optimistic bias). The $23,300 spent on the parallel run could instead fund other process improvements. More importantly, the organization needs a forecast now for the annual budget — running two models in parallel for six months means the budget will be based on one model while the organization spends money evaluating another, creating confusion about which forecast drives planning decisions. A candidate selecting this option may have defaulted to 'test more' without recognizing that sufficient evidence already exists to make the decision.",
    "ExplanationWrongD": "Option D proposes segmenting the forecast by supply chain tier — Model Y for long-lead-time items and Model X for short-lead-time items. While supply-chain segmentation is a legitimate operations strategy, it introduces operational complexity: the company now maintains two forecasting systems, two sets of parameters, and two reconciliation processes. The incremental benefit of Model Y's lower MAPE (4.5 percentage points) on a subset of items is unlikely to justify running and maintaining two separate forecasting systems. Additionally, Model Y's 2.1% optimistic bias on long-lead-time items would cause the company to order too much material far in advance — precisely the items where over-ordering is most costly because the material cannot be returned or re-purposed quickly. A candidate selecting this option may have attempted to capture the 'best' of both models without recognizing that forecast system complexity has its own costs.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // 12: BD-073 — Forecast Accuracy → Analyze
  'P1-BD-073': {
    "Stem": "Ashvale Manufacturing's S&OP manager, Marcus Delgado, is comparing two forecasting models using historical data. Model P (three-month moving average) produced the following results for the past four months: Forecast: [1,200, 1,250, 1,180, 1,300] vs. Actual: [1,150, 1,310, 1,140, 1,340]. Model Q (exponential smoothing with α=0.3) produced: Forecast: [1,160, 1,220, 1,200, 1,260] vs. same actuals. Marcus calculates the Mean Absolute Deviation (MAD) for each model to recommend which should drive the Q3 production budget. The production VP prefers Model P because it 'responds faster to recent demand shifts.' The CFO wants the model that minimizes production schedule instability. Which analysis correctly evaluates the two models?",
    "Choices": {
      "A": "Model P MAD = (|1,200-1,150| + |1,250-1,310| + |1,180-1,140| + |1,300-1,340|) / 4 = (50 + 60 + 40 + 40) / 4 = 47.5. Model Q MAD = (|1,160-1,150| + |1,220-1,310| + |1,200-1,140| + |1,260-1,340|) / 4 = (10 + 90 + 60 + 80) / 4 = 60.0. Model P has lower MAD (47.5) and should be selected — it tracks actual demand more closely on average",
      "B": "Model Q should be selected despite a higher MAD because exponential smoothing produces more stable forecasts (less month-to-month forecast revision), which reduces production schedule instability — the production VP's preference for 'responding faster' is actually a disadvantage when it increases schedule changes",
      "C": "Model P MAD = (|50| + |60| + |40| + |40|) / 4 = 47.5. Model Q MAD = (|10| + |90| + |60| + |80|) / 4 = 60.0. The choice depends on the cost of forecast error structure: Model P's errors are smaller on average but Model Q's are asymmetric — it was much more accurate in month 1 (error of 10 vs. 50) but much worse in months 2-4. If large forecast errors cause disproportionate costs (e.g., stockouts or expedited production), Model P's more consistent error profile is preferable despite higher average accuracy in some months",
      "D": "Neither model is adequate — the MAD values of 47.5 and 60.0 on a base of approximately 1,200-1,300 units represent 3.7-4.6% error rates, which exceed the typical 2% accuracy threshold for production planning. Marcus should recommend developing a new forecasting approach"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "Option C correctly calculates the MAD for both models and evaluates them on error structure, not just the average. Model P: MAD = 47.5. Model Q: MAD = 60.0. Model P is more accurate on average. However, the analysis correctly adds a crucial dimension: the error profile matters as much as the average. Model Q's errors are uneven — it was very accurate in month 1 (error = 10) but had large errors in months 2-4 (errors of 90, 60, 80). Model P's errors are more consistent (50, 60, 40, 40). The choice depends on the operational cost structure: if large single-month errors trigger stockouts, expedited shipping, or production line stoppages, the more consistent model (P) is preferable even if its average error is higher than months where Q performs well. Under CMA Part 1 forecasting, accuracy metrics should be evaluated alongside the business cost of different error patterns — the analyze-level skill is recognizing that the decision cannot be made from the MAD alone and requires understanding the operational context.",
    "ExplanationWrongA": "Option A correctly calculates MAD but selects Model P based solely on the lower average error. While Model P's MAD of 47.5 is lower than Model Q's 60.0, the analysis ignores the error structure — Model Q had the smallest error of any single month (10 in month 1), suggesting it may capture certain demand patterns better. More importantly, the production VP's preference for 'responding faster' is not inherently wrong — in industries with volatile demand, a model that responds quickly to recent shifts may prevent stockouts even if its average error is higher. The candidate should recognize that MAD is a summary statistic that can hide important error structure details. A candidate selecting this option calculated correctly but stopped at the summary statistic without evaluating the full decision context.",
    "ExplanationWrongB": "Option B asserts that Model Q produces 'more stable forecasts' without quantitative support. Exponential smoothing with α=0.3 does produce smoother forecasts than a moving average when the data has high variance, but the actual forecasts show Model Q's month-to-month changes (|1,160→1,220| = 60, |1,220→1,200| = 20, |1,200→1,260| = 60) are comparable to Model P's (|1,200→1,250| = 50, |1,250→1,180| = 70, |1,180→1,300| = 120). Model P actually appears less stable by this measure. The claim that 'responding faster is a disadvantage' also requires qualification — in some industries, slow-responding forecasts cause more problems (stockouts) than fast-responding ones (schedule changes). A candidate selecting this option may have applied a generic preference for 'stability' without examining the actual data or operational context.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Option D applies an arbitrary 2% accuracy threshold. The 3.7-4.6% error rates (MAD / average demand of approximately 1,250) are actually quite good for manufacturing demand forecasting — typical MAPE targets for production planning range from 5-15% depending on industry and product characteristics. Declaring both models 'inadequate' based on an unstated benchmark ignores the practical assessment that both models produce forecasts within a reasonable error range. Under CMA Part 1, forecast accuracy should be evaluated against benchmarks appropriate to the industry and application, not an arbitrary standard. A candidate selecting this option may have applied a textbook accuracy threshold without considering whether it is realistic for the specific business context.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": true
  },

  // 13: BD-085 — Budget Revision Mid-Year → Evaluate
  'P1-BD-085': {
    "Stem": "Kelso Industries' controller, Lisa Tran, is preparing the Q2 variance analysis package for the audit committee. In April, a key supplier declared force majeure after a natural disaster, causing raw material prices for Kelso's primary input to increase from $14.50/unit to $19.80/unit — a 36.6% increase. The purchasing director estimates the new price will persist for at least 9-12 months while alternative suppliers are qualified. The Q1-Q2 budget was based on the $14.50 price. Kelso consumes 12,000 units of this material per quarter. Lisa calculates that maintaining the original price standard for Q3-Q4 would produce a guaranteed $127,200 unfavorable material price variance ($5.30/unit x 12,000 units x 2 quarters) that is entirely attributable to the external supply shock. The VP of Operations argues the budget should not be revised — 'we need to show the board the real impact of this supply disruption.' The CFO wants the budget to reflect expected costs accurately for Q3-Q4 planning. Which recommendation should Lisa make?",
    "Choices": {
      "A": "Do not revise the budget — hold managers accountable to the original $14.50/unit standard. The $127,200 unfavorable variance will communicate the supply shock's impact to the board more effectively than a revised budget that hides the cost increase. Budget revisions undermine the discipline of comparing actual to original plan",
      "B": "Revise the budget for Q3-Q4 to reflect the $19.80/unit price — the $14.50 standard is no longer achievable, and continuing to use it will produce variances that provide zero diagnostic value (everyone knows why costs are higher). The original budget can still be preserved for year-over-year comparison, but the operating budget for the remainder of the year should reflect the best available cost information",
      "C": "Revise the budget to a blended rate of $17.15 — the midpoint between the old and new prices. This partially acknowledges the cost increase while preserving some of the original budget's cost discipline message",
      "D": "Create two variance reports: one against the original $14.50 budget (to show the board the $127,200 supply shock impact) and one against a revised $19.80 budget (to evaluate operational performance excluding the supply shock). Present both to the audit committee for a complete picture"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The budget should be revised for Q3-Q4 to reflect the $19.80/unit price. Under CMA Part 1 budgeting, a budget revision is appropriate when a significant, persistent change in underlying assumptions makes the original budget unreliable as a planning and performance evaluation tool. The key facts: the price increase is large (36.6%), it will persist for 9-12 months (not a one-month spike), and it is external (the purchasing department did not cause it). Continuing with the $14.50 standard for two more quarters serves no purpose: the $127,200 unfavorable variance is 100% explained by the supply shock — it provides zero information about purchasing performance, production efficiency, or cost control. The budget's purpose is to provide a meaningful benchmark — a benchmark known to be wrong fails this purpose. The evaluate-level skill is distinguishing between events that warrant budget revision (persistent, structural changes to the cost baseline) and events that should be explained through variance analysis (one-time or controllable deviations).",
    "ExplanationWrongA": "Option A argues against revision on the grounds of 'budget discipline.' Under CMA Part 1, budget discipline means holding managers accountable for controllable factors — it does not mean refusing to update assumptions when conditions have demonstrably changed. Running two quarters of variance reports showing a mechanical $127,200 unfavorable variance teaches the organization nothing and may actually undermine the credibility of the budget process — if managers see that the budget is deliberately maintained at an unachievable standard, they will discount all budget variances as 'just the supply shock' and miss real operational issues. The board can be informed of the supply shock's impact through a one-time disclosure without embedding it in two quarters of meaningless variance reports. A candidate selecting this option may have confused budget rigidity with accountability.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C proposes an arbitrary blended rate of $17.15 — the simple average of $14.50 and $19.80. This rate has no basis in reality: the company will pay $19.80/unit, not $17.15. Using a fictional rate of $17.15 means the variance report will show an unfavorable variance of $2.65/unit on every purchase — creating a persistent, predictable variance that, like the unrevised budget, provides no diagnostic value. Budget standards should reflect expected actual costs, not aspirational compromises between old and new rates. A candidate selecting this option may have attempted to 'split the difference' without recognizing that budget assumptions must be grounded in reality, not negotiation.",
    "ExplanationWrongD": "Option D proposes dual variance reports — one against each standard. While this seems comprehensive, it doubles the reporting burden and creates confusion about which numbers represent 'the budget.' More importantly, running two parallel sets of variance reports signals that the organization cannot commit to a single plan — it undermines the budget as the authoritative financial benchmark. A single set of reports against a revised, realistic budget, supplemented by a clear disclosure of the supply shock's impact and the revision rationale, provides the same information more clearly and with less administrative overhead. A candidate selecting this option may have attempted to satisfy all audiences without recognizing that multiple 'official' budgets create ambiguity about which targets managers are accountable for.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": false
  },

  // 14: BD-091 — Cash Collection Pattern → Evaluate
  'P1-BD-091': {
    "Stem": "Quintwood Distribution's treasurer, Teresa Ortiz, is preparing the Q3 cash budget. The company sells to wholesale customers on terms of net 30. Historical collection patterns: 55% collected in the month of sale, 35% in the following month, 8% in the second month, and 2% uncollectible. Q3 forecasted credit sales: July $280,000, August $320,000, September $350,000. Actual Q2 sales: May $240,000, June $260,000. Quintwood's bank requires a minimum month-end cash balance of $40,000 under its revolving credit agreement. The VP of Sales proposes offering a 2% discount for payment within 10 days to accelerate collections — she estimates that 30% of customers would take the discount (reducing the month-of-sale collection from 55% to a split of 30% discounted + 25% regular), decreasing uncollectible accounts from 2% to 1%, and pulling 5% of the following-month collections into the current month. The CFO asks Teresa to evaluate whether the discount program improves Q3's cash position enough to justify the revenue reduction. Which recommendation is most appropriate?",
    "Choices": {
      "A": "Recommend the discount program — it accelerates cash inflows, reduces bad debt expense from 2% to 1% of credit sales ($19,000 annual savings on $950,000 Q3 sales), and the 2% discount cost on 30% of collections is offset by lower borrowing needs under the credit line",
      "B": "Do not adopt the discount — the program would reduce Q3 revenue by $5,700 (2% x 30% x $950,000) with uncertain collection acceleration benefits. The current collection pattern already provides adequate cash flow, and the $40,000 minimum balance is maintained in all months under the existing pattern",
      "C": "Calculate the net cash flow impact: the discount program accelerates approximately $14,250 from following-month into current-month collections (5% of $285,000 avg monthly sales), reduces uncollectible accounts by $9,500 over Q3 (1% of $950,000), but costs $5,700 in discounts. The net cash benefit is approximately $18,050 over Q3. The discount improves the cash position — recommend adoption",
      "D": "Recommend a limited pilot — offer the discount to the 10 largest customers (representing ~40% of sales) for Q3 only, then evaluate the collection acceleration before rolling out to all customers. This limits the revenue reduction to approximately $2,280 while testing the behavioral response"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "The discount program should be adopted because the net cash flow benefit is positive. The quantification: (1) Accelerated collections — approximately 5% of monthly sales shift from the following month to the current month. At an average of $285,000/month, this accelerates $14,250 in cash per month, or approximately $14,250-$28,500 over Q3 depending on timing. (2) Bad debt reduction — 1% of $950,000 Q3 sales = $9,500 in avoided uncollectible accounts. (3) Discount cost — 2% on 30% of customers on $950,000 = $5,700. Net cash benefit: $14,250 (acceleration) + $9,500 (bad debt savings) - $5,700 (discounts) = $18,050. Even conservatively, the program is cash-positive. Under CMA Part 1 cash management, collection acceleration programs should be evaluated on net cash flow impact, not just the cost of the discount — the time value of money and bad debt reduction are real benefits. The evaluate-level skill is quantifying the trade-off between revenue reduction and cash flow improvement rather than judging the discount program on a single dimension.",
    "ExplanationWrongA": "Option A recommends the program but with imprecise reasoning. It claims the discount cost is 'offset by lower borrowing needs' without quantifying either the cost or the borrowing reduction. It also estimates bad debt savings at $19,000 based on Q3 sales — but the correct calculation is 1% of $950,000 = $9,500, not $19,000. Under CMA Part 1, financial recommendations must be supported by quantified analysis, not directional assertions. A candidate selecting this option reached the correct conclusion but through unsupported reasoning, which would not satisfy the standard of evidence expected in professional management accounting.",
    "ExplanationWrongB": "Option B rejects the program without quantifying the cash flow benefit. The claim that 'the current collection pattern already provides adequate cash flow' assumes the $40,000 minimum balance is the only objective — but the treasurer's goal is to optimize the cash position, not merely meet the minimum. The $18,050 net cash benefit improves Quintwood's liquidity, reduces interest expense on the credit line, and lowers credit risk. Rejecting a cash-positive program because the current position is 'adequate' leaves value on the table. Under CMA Part 1, treasury decisions should maximize the cash position within acceptable risk parameters, not merely avoid covenant violations. A candidate selecting this option may have confused meeting minimum requirements with optimizing financial performance.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Option D proposes a limited pilot with 10 customers. While pilot programs are generally prudent for major process changes, the discount is a standard commercial term (2/10 net 30 is one of the most common trade credit terms in business). The behavioral response to early-payment discounts is well-understood — approximately 30-50% of customers take 2% discounts when offered, consistent with the VP of Sales's estimate. The cost of a pilot ($2,280 in foregone revenue on 40% of sales) and the delay in full implementation (one quarter of suboptimal cash flow) likely exceed the value of the 'test.' A pilot is appropriate for novel programs with uncertain customer response, not for standard trade credit terms with predictable take rates. A candidate selecting this option may have defaulted to 'test first' without recognizing that the program is a standard, well-understood financial instrument.",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "CalculationItem": true
  },

  // 15: BD-096 — Strategic vs Operational Planning → Analyze
  'P1-BD-096': {
    "Stem": "Valemont Corporation's board of directors approved a five-year strategic plan in January that set a target of $85 million in annual revenue by year five, driven by expansion into two new geographic markets (Southeast Asia and Eastern Europe). The plan calls for $12 million in capital investment over years 1-3 to establish distribution centers and local sales offices. In August, the controller, James Wu, is preparing the annual operating budget for the upcoming fiscal year. The VP of International Expansion submits a budget request for $4.2 million to open the Bangkok distribution center — consistent with the strategic plan's year-1 milestone. Simultaneously, the VP of Domestic Operations requests $2.8 million to upgrade the flagship US facility, arguing that domestic margins are under pressure and the upgrade is needed to maintain competitiveness. James can fund only one of the two requests within the operating budget's capital constraint of $4.5 million. The CEO asks James to reconcile the tension between the board-approved strategic plan and the domestic margin pressure. Which analysis correctly frames this planning conflict?",
    "Choices": {
      "A": "Fund the Bangkok expansion ($4.2M) — the board-approved strategic plan is the highest-level organizational commitment, and deviating from year-1 milestones would signal to the board that management cannot execute the approved strategy. The domestic upgrade can be deferred to next year",
      "B": "Fund the domestic upgrade ($2.8M) — protecting existing margins in the core business preserves the cash flow needed to fund future international expansion. The strategic plan's year-1 milestone can shift by 6-12 months without abandoning the overall five-year target",
      "C": "The conflict reveals that the strategic plan was approved without adequate resource feasibility analysis. James should present both requests to the board with a recommendation to fund the Bangkok expansion now, approve the domestic upgrade as a supplemental capital request (increasing the total capital budget to $7.0M), and ask the board to resolve the resource conflict they created when approving an ambitious strategic plan without confirming capital availability",
      "D": "The tension is inherent in the relationship between strategic and operational planning — the strategic plan sets direction and priorities (international expansion), while the operating budget must reconcile those priorities with current operational realities (margin pressure). James should fund Bangkok at $4.2M per the strategic plan while presenting a phased domestic upgrade over two budget cycles ($1.4M each year) to address the margin issue without fully deferring it"
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Option D correctly frames the strategic-vs-operational planning tension and provides a practical resolution. Under CMA Part 1 budgeting, the strategic plan sets long-term direction and priorities — the board's approval of international expansion establishes it as an organizational priority. The operating budget translates the first year of the strategic plan into specific resource allocations — the Bangkok distribution center is the year-1 milestone that advances the strategy. However, the operating budget must also address current operational realities — the domestic margin pressure is not a strategic choice, it is a current business condition that the budget must respond to. By funding Bangkok at the full $4.2M (executing the strategic commitment) while phasing the domestic upgrade over two budget cycles ($1.4M each), the controller respects both the strategic priority AND the operational need. The analyze-level skill is diagnosing the nature of the planning conflict (strategic commitment vs. operational necessity) and designing a solution that partially addresses both rather than fully resolving one at the expense of the other.",
    "ExplanationWrongA": "Option A treats the strategic plan as immutable — once approved, every milestone must be executed on the original timeline regardless of changing conditions. Under CMA Part 1, strategic plans provide direction but are not operational budgets — they are revised periodically as conditions change. The domestic margin pressure is new information that was not available when the board approved the strategic plan in January. Good governance requires incorporating new information into resource allocation decisions, not blindly executing a plan that predates the information. More importantly, if domestic margins deteriorate, the cash flow needed to fund years 2-3 of international expansion may not materialize — preserving the core business is a prerequisite for strategic execution. A candidate selecting this option may have over-weighted the strategic plan's authority without recognizing that strategic plans assume a stable core business.",
    "ExplanationWrongB": "Option B treats the strategic plan as easily deferrable — '6-12 months delay' is not trivial when the plan specifies year-1 milestones that cascade into years 2-3. Delaying Bangkok by a year delays the revenue ramp-up from Southeast Asia by a year, potentially missing the year-5 $85M revenue target. More importantly, if domestic upgrades are prioritized over strategic initiatives every time margin pressure appears, the company will perpetually defer strategy execution in favor of short-term operational fixes. The controller's role is to ensure strategic initiatives receive resource allocation, not just to respond to the loudest operational demand. A candidate selecting this option may have prioritized the immediate operational problem without evaluating the strategic cost of deferral.",
    "ExplanationWrongC": "Option C deflects the decision to the board rather than providing management analysis. While it is true that the strategic plan may have been approved without detailed resource feasibility, the controller's job is to provide analysis and recommendations, not to return conflicts to the board for resolution. Increasing the total capital budget to $7.0M may violate debt covenants, exceed borrowing capacity, or dilute returns — the option does not analyze whether additional funding is feasible. Presenting a conflict to the board without a recommended resolution is a staff-level response, not a management accounting leadership response. A candidate selecting this option may have identified a legitimate process issue (resource feasibility) but responded by escalating rather than analyzing.",
    "ExplanationWrongD": "",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "CalculationItem": false
  }
};

// ===================== MAIN =====================

const src = fs.readFileSync(PACK_FILE, 'utf8');
const match = src.match(/const\s+(\w+)\s*=\s*\[([\s\S]*)\];\s*\n/);
if (!match) { console.error('FATAL: Could not parse pack file'); process.exit(1); }

const varName = match[1];
const arrayBody = match[2];
const fn = new Function('return [' + arrayBody + ']');
const items = fn();

console.log('Parsed', items.length, 'items from', PACK_FILE);

let replaced = 0;
const evalCount = Object.values(rewrites).filter(r => r.CognitiveLevel === 'Evaluate').length;
const analyzeCount = Object.values(rewrites).filter(r => r.CognitiveLevel === 'Analyze').length;
console.log('Target: ' + evalCount + ' Evaluate + ' + analyzeCount + ' Analyze = ' + Object.keys(rewrites).length + ' total');

for (const qid of Object.keys(rewrites)) {
  const idx = items.findIndex(i => i.QuestionID === qid);
  if (idx === -1) {
    console.error('FATAL: QID not found:', qid);
    process.exit(1);
  }
  const newFields = rewrites[qid];
  const item = items[idx];

  for (const [key, value] of Object.entries(newFields)) {
    item[key] = value;
  }

  if (item.VerifiedChecks) {
    item.VerifiedChecks = [
      "Mapped to CMA Part 1 Learning Outcome Statements effective September 1, 2024",
      "Screened to exclude Part 2-only topics such as CVP, financial ratio analysis, capital budgeting, corporate finance, ERM, and ethics",
      "Original practice item with business-scenario stem, named stakeholder, and decision context",
      "Answer key distribution balanced across A/B/C/D",
      "Distractors written as choice-specific explanations targeting documented CMA exam traps"
    ];
  }

  item.ReviewNote = "If missed or marked, review the linked study materials. This item tests higher-order reasoning — focus on understanding the decision criteria, not just the correct answer.";
  item.certification_batch = (item.certification_batch || '') + '; S72 cognitive upgrade wave 2';

  replaced++;
  console.log('  [' + replaced + '/' + Object.keys(rewrites).length + '] Rewrote ' + qid + ' → ' + newFields.CognitiveLevel + ' CC=' + newFields.CorrectChoice + ' Diff=' + newFields.Difficulty);
}

if (replaced !== Object.keys(rewrites).length) {
  console.error('FATAL: Expected ' + Object.keys(rewrites).length + ' replacements, got', replaced);
  process.exit(1);
}

const newItemsJson = JSON.stringify(items, null, 2);
const newSrc = 'const ' + varName + ' = ' + newItemsJson + ';\n\nif (typeof module !== "undefined" && module.exports) {\n  module.exports = ' + varName + ';\n}\n';

fs.writeFileSync(PACK_FILE, newSrc, 'utf8');

const packCheck = newSrc.match(/const\s+(\w+)\s*=\s*\[([\s\S]*)\];\s*\n/);
if (!packCheck) { console.error('FATAL: Output file failed re-parse'); process.exit(1); }

const fn2 = new Function('return [' + packCheck[2] + ']');
const items2 = fn2();
console.log('Re-parsed ' + items2.length + ' items — QID count stable:', items2.length === 500 ? 'PASS' : 'FAIL');

let dl008 = 0;
for (const q of items2) {
  const cc = q.CorrectChoice;
  if (q['ExplanationWrong' + cc] && q['ExplanationWrong' + cc] !== '') {
    dl008++;
  }
}
console.log('DL-008 violations:', dl008, dl008 === 0 ? 'PASS' : 'FAIL');

let dl026 = 0;
for (const q of items2) {
  const cc = q.CorrectChoice;
  for (const l of ['A','B','C','D']) {
    if (l !== cc) {
      const ew = q['ExplanationWrong' + l];
      if (ew === '' || ew === undefined || ew === null) {
        dl026++;
      }
    }
  }
}
console.log('DL-026 violations:', dl026, dl026 === 0 ? 'PASS' : 'FAIL');

const qids = new Set(items2.map(i => i.QuestionID));
console.log('Unique QIDs:', qids.size, qids.size === 500 ? 'PASS' : 'FAIL');

const elapsed = ((Date.now() - T0) / 1000).toFixed(1);
const rewrittenEval = Object.values(rewrites).filter(r => r.CognitiveLevel === 'Evaluate').length;
const rewrittenAnalyze = Object.values(rewrites).filter(r => r.CognitiveLevel === 'Analyze').length;
console.log('\n=== SESSION072 Rewrite Complete ===');
console.log('  Duration:', elapsed, 'seconds');
console.log('  Items rewritten:', Object.keys(rewrites).length);
console.log('  Evaluate:', rewrittenEval);
console.log('  Analyze:', rewrittenAnalyze);
console.log('  Parse: PASS');
console.log('  DL-008:', dl008);
console.log('  DL-026:', dl026);
console.log('  QID count:', items2.length, '(stable)');
