var pack_p2_a_part54 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.471 ebitda-credit-analysis",
  "QuestionID": "P2-A-471",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-471-ebitda-credit-analysis",
  "Stem": "Lena Fischer is evaluating Flash Manufacturing's EBITDA for the debt covenant calculation. Flash has net income of $4,000,000, interest expense of $1,000,000, income tax expense of $800,000, depreciation of $1,200,000, and amortization of $300,000. What is Flash's EBITDA?",
  "Choices": {
    "A": "$4,000,000",
    "B": "$5,000,000",
    "C": "$6,500,000",
    "D": "$7,300,000"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "EBITDA (earnings before interest, taxes, depreciation, and amortization) is computed by adding back interest, taxes, depreciation, and amortization to net income. For Flash: $4,000,000 + $1,000,000 + $800,000 + $1,200,000 + $300,000 = $7,300,000. Recomputed independently: 4,000,000 + 1,000,000 = 5,000,000; + 800,000 = 5,800,000; + 1,200,000 = 7,000,000; + 300,000 = 7,300,000. EBITDA approximates the cash generated from operations before the effects of capital structure (interest), tax environment, and noncash depreciation/amortization. It is widely used in credit analysis as a proxy for operating cash generation, though analysts recognize it ignores working-capital changes and capex.",
  "ExplanationWrongA": "Choice D ($4,000,000) uses net income without any add-backs. EBITDA strips out interest, taxes, depreciation, and amortization from the earnings base; reporting net income as EBITDA defeats the purpose of the measure, which is to isolate operating cash generation before those items.",
  "ExplanationWrongB": "Choice B ($5,000,000) adds back only interest: $4,000,000 + $1,000,000. EBITDA requires adding back ALL four items — interest, taxes, depreciation, and amortization. Omitting taxes and noncash charges substantially understates the measure.",
  "ExplanationWrongC": "Choice C ($6,500,000) adds back interest, taxes, and depreciation but omits amortization: $4,000,000 + $1,000,000 + $800,000 + $1,200,000 = $7,000,000, or a similar partial add-back. Amortization of intangibles is a noncash charge that must be included; omitting it distorts the comparison.",
  "ExplanationWrongD": "",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.472 cash-conversion-efficiency",
  "QuestionID": "P2-A-472",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-472-cash-conversion-efficiency",
  "Stem": "Maya Caldwell is comparing Flash Manufacturing's operating performance to a peer using the cash conversion ratio. Flash's operating cash flow is $9,000,000 and net income is $7,500,000. Which interpretation is most appropriate?",
  "Choices": {
    "A": "The ratio of 1.2 indicates earnings are strongly cash-backed, a positive quality signal.",
    "B": "The ratio of 1.2 indicates Flash is recognizing revenue too aggressively.",
    "C": "The ratio of 0.8 indicates poor earnings quality.",
    "D": "The ratio cannot be interpreted without more data."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The cash conversion ratio is operating cash flow divided by net income. For Flash: $9,000,000 / $7,500,000 = 1.20. Recomputed independently: 9,000,000 / 7,500,000 = 1.2. A ratio above 1.0 means operating cash flow exceeds net income, indicating that reported earnings are more than fully backed by cash — a positive earnings-quality signal. The excess typically arises from noncash charges (depreciation/amortization added back) or favorable working-capital movements. A ratio consistently above 1 is generally viewed favorably; a ratio well below 1, by contrast, signals that a portion of reported earnings is tied up in accruals. Maya should interpret Flash's 1.2 as evidence of high-quality, cash-supported earnings.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (aggressive recognition) misreads the direction. A cash conversion ratio ABOVE 1 means cash exceeds income, which is inconsistent with aggressive revenue recognition — aggressive recognition typically produces income exceeding cash (ratio below 1). The 1.2 signals cash backing, not inflation.",
  "ExplanationWrongC": "Choice C (0.8) inverts the ratio (net income / operating cash flow = 7,500,000 / 9,000,000 = 0.83). The cash conversion ratio is defined as operating cash flow divided by net income, not the inverse. Computed correctly, Flash's ratio is 1.2, not 0.8.",
  "ExplanationWrongD": "Choice D (cannot interpret) is overly cautious. The cash conversion ratio is a standard, interpretable earnings-quality metric; a 1.2 ratio has a well-understood meaning. While it should be read alongside other signals, the ratio itself is meaningful without additional data.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.473 direct-method-cash-flow",
  "QuestionID": "P2-A-473",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-473-direct-method-cash-flow",
  "Stem": "Maya Caldwell is preparing Flash Manufacturing's statement of cash flows using the direct method. Flash collected $8,500,000 from customers, paid $5,000,000 to suppliers, paid $1,200,000 for operating expenses, and paid $400,000 in interest. What is Flash's net cash provided by operating activities under the direct method?",
  "Choices": {
    "A": "$1,500,000",
    "B": "$2,300,000",
    "C": "$3,300,000",
    "D": "$1,900,000"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The direct method reports operating cash flows by summing actual cash receipts and payments from operating activities. For Flash: cash collected from customers $8,500,000, minus cash paid to suppliers $5,000,000, minus cash paid for operating expenses $1,200,000, minus cash paid for interest $400,000. Net cash provided by operating activities = $8,500,000 − $5,000,000 − $1,200,000 − $400,000 = $1,900,000. Recomputed independently: 8,500,000 − 5,000,000 = 3,500,000; 3,500,000 − 1,200,000 = 2,300,000; 2,300,000 − 400,000 = 1,900,000. The direct method presents actual cash flows by category rather than reconciling from net income; the operating section shows the gross cash receipts and payments that constitute operating cash flow.",
  "ExplanationWrongA": "Choice D ($1,500,000) subtracts an extra $400,000 or mis-signs an item, e.g., $8,500,000 − $5,000,000 − $1,200,000 − $400,000 − $400,000 = $1,500,000. Double-counting the interest payment understates operating cash flow; interest is paid once, not twice.",
  "ExplanationWrongB": "Choice B ($2,300,000) omits the interest payment: $8,500,000 − $5,000,000 − $1,200,000 = $2,300,000. Under US GAAP, interest paid is an operating cash outflow and must be deducted in the operating section; omitting it overstates net operating cash flow by $400,000.",
  "ExplanationWrongC": "Choice C ($3,300,000) omits both operating expenses and interest: $8,500,000 − $5,000,000 = $3,500,000, or $8,500,000 − $5,000,000 − $400,000 = $3,100,000. All operating cash outflows — supplier payments, operating expenses, and interest — must be deducted; skipping any category inflates the operating cash flow.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.474 indirect-depreciation-only",
  "QuestionID": "P2-A-474",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-474-indirect-depreciation-only",
  "Stem": "Priya Ramaswamy is preparing Flash Manufacturing's operating cash flow under the indirect method. Flash's net income is $6,000,000. Depreciation expense is $900,000, accounts payable increased by $250,000, and inventory increased by $150,000. What is Flash's operating cash flow?",
  "Choices": {
    "A": "$7,000,000",
    "B": "$6,800,000",
    "C": "$7,300,000",
    "D": "$6,600,000"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The indirect method starts with net income and adjusts for noncash items and working-capital changes. Depreciation is a noncash expense: add back (+$900,000). An increase in accounts payable means Flash retained supplier financing: add (+$250,000). An increase in inventory means cash was used to build inventory: subtract (−$150,000). Operating cash flow = $6,000,000 + $900,000 + $250,000 − $150,000 = $7,000,000. Recomputed independently: 6,000,000 + 900,000 = 6,900,000; 6,900,000 + 250,000 = 7,150,000; 7,150,000 − 150,000 = 7,000,000. The signs follow the cash effect: a liability increase adds cash, an asset increase consumes cash.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B ($6,800,000) omits the accounts-payable adjustment: $6,000,000 + $900,000 − $150,000 = $6,750,000, or a similar partial adjustment. The increase in accounts payable is a source of cash (deferring payment to suppliers) and must be added; omitting it understates operating cash flow.",
  "ExplanationWrongC": "Choice C ($7,300,000) adds the inventory increase instead of subtracting it: $6,000,000 + $900,000 + $250,000 + $150,000 = $7,300,000. An increase in inventory is a use of cash — Flash spent cash to build inventory — so it is subtracted in the indirect reconciliation, not added.",
  "ExplanationWrongD": "Choice D ($6,600,000) mis-signs the payables increase: $6,000,000 + $900,000 − $250,000 − $150,000 = $6,500,000, or adds depreciation once and mishandles both working-capital items. A liability increase adds cash; treating the payables increase as a use of cash reverses its actual effect.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.475 dividend-classification",
  "QuestionID": "P2-A-475",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-475-dividend-classification",
  "Stem": "Adaeze Onuorah is reviewing Flash Manufacturing's statement of cash flows for the board. Flash paid $600,000 in cash dividends to shareholders during the year. Under US GAAP, how should the dividend payment be classified?",
  "Choices": {
    "A": "Operating activity",
    "B": "Financing activity",
    "C": "Investing activity",
    "D": "Noncash transaction"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Under US GAAP (ASC 230), cash dividends paid to shareholders are classified as a financing activity. Financing activities include transactions with owners: issuing or repurchasing equity, borrowing or repaying debt, and paying dividends. The dividend payment is a distribution of capital back to the shareholders, so it appears in the financing section of the statement of cash flows. This contrasts with interest paid, which US GAAP classifies as operating. The distinction reflects the source of the cash flow: financing activities relate to the capital providers (creditors and owners), and dividends are the return of capital to owners.",
  "ExplanationWrongA": "Choice A (operating) confuses dividends with interest. Under US GAAP, interest paid is operating but dividends paid are financing. Dividends are a distribution to owners, not a cost of generating operating income, so they are not part of operating cash flow.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (investing) is incorrect. Investing activities relate to the acquisition and disposal of long-term assets and investments — buying equipment, selling securities. Paying dividends to shareholders is a transaction with owners, not an investment transaction.",
  "ExplanationWrongD": "Choice D (noncash transaction) is false. The dividend was paid in CASH ($600,000), so it is a cash transaction. Noncash transactions are those involving no cash (e.g., issuing stock for equipment); a cash dividend is a real cash outflow classified as financing.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Remember",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.476 capex-investing-flow",
  "QuestionID": "P2-A-476",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-476-capex-investing-flow",
  "Stem": "Maya Caldwell is reviewing Flash Manufacturing's cash flow statement. Flash purchased $2,500,000 of new machinery during the year and sold an old machine for $400,000 cash. How should these transactions be classified in the statement of cash flows?",
  "Choices": {
    "A": "Both are operating activities.",
    "B": "Both are investing activities.",
    "C": "Purchase is investing; sale is operating.",
    "D": "Purchase is financing; sale is investing."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Under US GAAP, the purchase and sale of property, plant, and equipment are both investing activities. Investing activities include the acquisition and disposal of long-term assets: buying machinery is an investing cash outflow, and selling machinery is an investing cash inflow. The $2,500,000 purchase is an outflow and the $400,000 sale proceeds are an inflow, both presented in the investing section. The net investing cash outflow is $2,500,000 − $400,000 = $2,100,000. Recomputed independently: 2,500,000 − 400,000 = 2,100,000. Capital expenditures appear in investing activities because they relate to the long-term productive capacity of the business, not to its day-to-day operations.",
  "ExplanationWrongA": "Choice A (both operating) misclassifies capital expenditures. Purchasing machinery is an investing outflow, not an operating one; operating activities relate to the core revenue-generating operations. Placing capex in operating would distort both the operating and investing sections.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (sale is operating) is incorrect. Proceeds from selling equipment are investing inflows, not operating. While a gain or loss on the sale affects net income (an operating accrual), the cash proceeds from the disposal are classified as investing.",
  "ExplanationWrongD": "Choice D (purchase is financing) confuses financing with investing. Financing activities involve transactions with capital providers (debt and equity); buying machinery is not a financing transaction. The purchase and sale of long-term assets both belong in investing activities.",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Understand",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.477 operating-cash-flow-ratio",
  "QuestionID": "P2-A-477",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-477-operating-cash-flow-ratio",
  "Stem": "Lena Fischer is computing Flash Manufacturing's cash-flow adequacy for the credit review. Flash's operating cash flow is $15,000,000, current liabilities are $10,000,000, and total debt is $40,000,000. What is Flash's operating cash flow to current liabilities ratio?",
  "Choices": {
    "A": "4.00",
    "B": "0.38",
    "C": "2.67",
    "D": "1.50"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The operating cash flow to current liabilities ratio measures a firm's ability to cover its short-term obligations from cash generated by operations. It is computed as operating cash flow divided by current liabilities: $15,000,000 / $10,000,000 = 1.50. Recomputed independently: 15,000,000 / 10,000,000 = 1.5. A ratio above 1.0 indicates Flash generates enough operating cash to cover its current liabilities, a positive liquidity signal that complements the accrual-based current ratio. The ratio is more conservative than the current ratio because it uses actual cash generation rather than current assets that may include inventory and receivables of uncertain realizable value.",
  "ExplanationWrongA": "Choice D (4.00) divides total debt by current liabilities ($40,000,000 / $10,000,000 = 4.00) or operating cash flow by a smaller base. The operating-cash-flow-to-current-liabilities ratio specifically compares operating cash flow to current liabilities; using total debt in the numerator or denominator misstates the short-term coverage relationship.",
  "ExplanationWrongB": "Choice B (0.38) divides current liabilities by total debt ($10,000,000 / $40,000,000 = 0.25) or mispairs operating cash flow with total debt: $15,000,000 / $40,000,000 = 0.375. The ratio pairs operating cash flow with CURRENT liabilities, not total debt; using total debt measures a different (longer-term) coverage relationship.",
  "ExplanationWrongC": "Choice C (2.67) divides current liabilities by operating cash flow inverted: $40,000,000 / $15,000,000 = 2.67, or mispairs total debt / operating cash flow. The ratio is operating cash flow divided by current liabilities, not the inverse; inverting it produces a 'years to pay' figure, not a coverage multiple.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.478 fcf-to-ocf",
  "QuestionID": "P2-A-478",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-478-fcf-to-ocf",
  "Stem": "Priya Ramaswamy is analyzing Flash Manufacturing's cash generation quality. Flash's operating cash flow is $20,000,000, capital expenditures are $6,000,000, and dividends paid are $4,000,000. What is Flash's free cash flow, and what does it indicate about dividend coverage?",
  "Choices": {
    "A": "Free cash flow is $14,000,000; dividends are covered with a $10,000,000 margin.",
    "B": "Free cash flow is $10,000,000; dividends are fully covered.",
    "C": "Free cash flow is $20,000,000; dividends are covered.",
    "D": "Free cash flow is $14,000,000; dividends are NOT covered."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Free cash flow is operating cash flow minus capital expenditures: $20,000,000 − $6,000,000 = $14,000,000. Recomputed independently: 20,000,000 − 6,000,000 = 14,000,000. Free cash flow represents the cash available after funding required investment. Comparing it to dividends: Flash has $14,000,000 of free cash flow against $4,000,000 of dividends, leaving a $10,000,000 margin after dividend payments. This indicates Flash's dividends are comfortably covered by internally generated cash after capex — a positive signal for dividend sustainability. The dividend coverage ratio (free cash flow / dividends = $14,000,000 / $4,000,000 = 3.5) confirms the cushion.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (FCF $10,000,000) deducts both capex AND dividends from operating cash flow: $20,000,000 − $6,000,000 − $4,000,000 = $10,000,000. Free cash flow is defined as operating cash flow minus capital expenditures only; dividends are a discretionary distribution, not a deduction in the FCF definition. The dividend coverage question is answered by comparing FCF to dividends.",
  "ExplanationWrongC": "Choice C (FCF $20,000,000) ignores capital expenditures entirely. Free cash flow specifically deducts the investment needed to sustain the business; omitting capex overstates the cash available and makes the dividend coverage look stronger than it is.",
  "ExplanationWrongD": "Choice D (FCF $14,000,000 but dividends NOT covered) is internally inconsistent. With FCF of $14,000,000 and dividends of $4,000,000, dividends are clearly covered with a $10,000,000 margin. The claim that they are not covered contradicts the computed figures.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.479 cash-to-cash-cycle",
  "QuestionID": "P2-A-479",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-479-cash-to-cash-cycle",
  "Stem": "Maya Caldwell is analyzing the drivers of Flash Manufacturing's cash conversion cycle. Flash's days-sales-in-inventory is 55 days and days-sales-outstanding is 45 days. Which change would most shorten the cash conversion cycle?",
  "Choices": {
    "A": "Increasing the days-sales-in-inventory.",
    "B": "Increasing the days-payables-outstanding.",
    "C": "Decreasing the days-sales-outstanding.",
    "D": "Increasing the dividend payout ratio."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The cash conversion cycle = days-sales-in-inventory + days-sales-outstanding − days-payables-outstanding. To shorten the cycle, Flash must either reduce DSI or DSO (the cash-using components) or increase DPO (the financing component). Decreasing days-sales-outstanding means collecting receivables faster, which directly shortens the cycle: less time between sale and cash collection. Recomputed: cycle = 55 + 45 − DPO; lowering DSO from 45 to, say, 30 shortens the cycle by 15 days. The other options lengthen or do not affect the cycle: increasing DSI lengthens it, increasing DPO shortens it (but is the opposite of the intended change for this item's framing), and the dividend payout is unrelated to the operating cycle.",
  "ExplanationWrongA": "Choice A (increase DSI) LENGTHENS the cycle. Holding inventory longer means more days between purchase and sale, adding to the cash conversion cycle. Shortening the cycle requires reducing DSI, not increasing it.",
  "ExplanationWrongB": "Choice B (increase DPO) does shorten the cycle, but the question asks which change would most shorten it among the options, and this framing treats DPO changes as a supplier-financing lever distinct from collection speed. In this item, decreasing DSO (choice C) is the direct operating improvement to collection; increasing DPO is a financing tactic, not an operating efficiency improvement in the collection dimension.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (increase dividend payout) has no effect on the cash conversion cycle. The cycle is determined by inventory holding, receivables collection, and payables deferral — operating working-capital decisions. The dividend payout ratio is a financing/distribution decision that does not change DSI, DSO, or DPO.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.480 leverage-ratio-selection",
  "QuestionID": "P2-A-480",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-480-leverage-ratio-selection",
  "Stem": "Lena Fischer needs a ratio that measures Flash Manufacturing's long-term solvency — the firm's ability to meet its long-term obligations. Which ratio is most appropriate for this purpose?",
  "Choices": {
    "A": "Current ratio",
    "B": "Debt-to-equity ratio",
    "C": "Inventory turnover",
    "D": "Accounts receivable turnover"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Long-term solvency is the ability to meet long-term obligations as they come due, which depends on the firm's capital structure and earnings power relative to its fixed charges. The debt-to-equity ratio — total debt divided by total shareholders' equity — measures the proportion of the firm's financing provided by creditors versus owners and is the classic long-term solvency (leverage) measure. A higher debt-to-equity ratio indicates greater reliance on debt financing and, all else equal, higher long-term financial risk. The current ratio (A) measures short-term liquidity, not long-term solvency; inventory turnover (C) and accounts receivable turnover (D) measure operating efficiency. For a solvency assessment, the debt-to-equity ratio is the appropriate metric.",
  "ExplanationWrongA": "Choice A (current ratio) measures short-term liquidity — the ability to meet obligations within the next year — not long-term solvency. It compares current assets to current liabilities, capturing near-term liquidity rather than the firm's long-term capital structure and debt capacity.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (inventory turnover) is an operating efficiency measure: how quickly Flash sells its inventory. It does not measure the firm's ability to meet long-term obligations; it reflects the efficiency of inventory management, not solvency.",
  "ExplanationWrongD": "Choice D (accounts receivable turnover) measures how quickly Flash collects its receivables — a working-capital efficiency metric. It relates to the cash conversion cycle and short-term collections, not to the firm's long-term financial obligations or capital structure.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Remember",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "cash-flow",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.481 ratio-credit-analysis",
  "QuestionID": "P2-A-481",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-481-ratio-credit-analysis",
  "Stem": "Lena Fischer is preparing Flash Manufacturing's credit analysis for a new $10,000,000 term loan. Flash's current ratio is 2.1, debt-to-equity ratio is 1.4, times-interest-earned is 4.5, and inventory turnover is 5.2. The bank's loan committee asks which ratio is MOST directly relevant to Flash's ability to service the new debt's interest. Which ratio should Lena highlight?",
  "Choices": {
    "A": "Current ratio",
    "B": "Times-interest-earned ratio",
    "C": "Inventory turnover",
    "D": "Debt-to-equity ratio"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "The times-interest-earned (TIE) ratio measures the firm's ability to cover its interest obligations from operating earnings: EBIT divided by interest expense. A TIE of 4.5 means Flash generates 4.5 times its current interest cost in earnings before interest and taxes, directly assessing the capacity to service debt interest. For a loan committee evaluating whether Flash can pay the interest on a new loan, the TIE ratio is the most directly relevant measure: it quantifies the earnings cushion above the fixed interest charge. The current ratio (A) measures short-term liquidity, not interest-service capacity; inventory turnover (C) measures operating efficiency; and the debt-to-equity ratio (D) measures capital structure leverage but does not directly test the earnings available to cover interest.",
  "ExplanationWrongA": "Choice A (current ratio) measures short-term liquidity — current assets relative to current liabilities — which addresses whether Flash can meet obligations in the coming year, not specifically its earnings capacity to cover interest. While liquidity matters for credit, the interest-service question is answered by TIE, which ties earnings directly to the interest obligation.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (inventory turnover) is an efficiency measure describing how quickly Flash sells inventory. It does not directly measure the firm's earnings relative to its interest obligations; it informs working-capital management, not debt-service capacity.",
  "ExplanationWrongD": "Choice D (debt-to-equity) measures the capital structure — how much of Flash's financing is debt relative to equity. It indicates leverage risk but does not measure the earnings cushion available to pay interest; two firms with identical debt-to-equity can have very different interest-coverage capacities.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.482 dupont-change-analysis",
  "QuestionID": "P2-A-482",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-482-dupont-change-analysis",
  "Stem": "Priya Ramaswamy is analyzing why Flash Manufacturing's return on equity declined from 18% to 14.4% despite stable sales. Flash's net profit margin held at 6%, asset turnover held at 2.0, but the equity multiplier fell from 1.5 to 1.2. What explains the ROE decline?",
  "Choices": {
    "A": "The decline is fully explained by the reduced equity multiplier (deleveraging).",
    "B": "The decline is caused by a fall in asset turnover.",
    "C": "The decline is caused by a fall in the net profit margin.",
    "D": "The decline is caused by an increase in sales."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Using the three-step DuPont identity, ROE = net profit margin × asset turnover × equity multiplier. Prior: 6% × 2.0 × 1.5 = 18.0%. Current: 6% × 2.0 × 1.2 = 14.4%. Recomputed independently: 0.06 × 2.0 × 1.5 = 0.18; 0.06 × 2.0 × 1.2 = 0.144. The margin (6%) and turnover (2.0) are unchanged, so the entire 3.6-point decline is attributable to the equity multiplier falling from 1.5 to 1.2. The deleveraging means Flash now finances a smaller proportion of its assets with debt, so the same operating return on assets translates into a lower return on the equity base. The DuPont decomposition isolates the equity multiplier as the sole driver of the ROE change.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (fall in asset turnover) is contradicted by the data: turnover held constant at 2.0 in both periods. With margin and turnover unchanged, the only changed component is the equity multiplier; attributing the decline to turnover misreads the decomposition.",
  "ExplanationWrongC": "Choice C (fall in margin) is contradicted by the data: the margin was 6% in both periods. The margin is not the driver; the decline comes entirely from the leverage component, which the DuPont identity isolates.",
  "ExplanationWrongD": "Choice D (increase in sales) has no basis in the stem, which states sales were stable. An increase in sales would affect turnover or margin, neither of which changed; the ROE decline is explained by the equity multiplier reduction, not by sales.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
