var pack_p2_a_part47 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.402 quick-ratio-inventory-exclusion",
  "QuestionID": "P2-A-402",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-402-quick-ratio-inventory-exclusion",
  "Stem": "Mariela Hoffmann is preparing a memo for Adaeze Onuorah, Flash Manufacturing's CFO, explaining the company's liquidity dashboard. Under U.S. GAAP, which of the following statements accurately explains why inventory is excluded from the numerator of the quick (acid-test) ratio?",
  "Choices": {
    "A": "Inventory is excluded because ASC 210-10-45 treats inventory as a noncurrent asset, so it does not belong with the liquid current assets.",
    "B": "Inventory is excluded because the quick ratio is designed to measure operating profitability rather than liquidity.",
    "C": "Inventory is excluded because it is the current asset least likely to be converted into cash quickly without a significant price concession, making the quick ratio a more stringent test of near-term liquidity than the current ratio.",
    "D": "Inventory is excluded because it is always matched dollar-for-dollar by the accounts payable used to purchase it, so including both would cancel out."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Under ASC 210-10-45-1, inventory is a current asset because it is expected to be realized through sale within the normal operating cycle, so the exclusion is not a matter of balance-sheet classification. The quick (acid-test) ratio intentionally includes only the most liquid current assets — cash, short-term marketable securities, and net accounts receivable — because those are convertible to cash within a short period. Inventory requires a sale and collection cycle before producing cash, and a forced or rapid disposal may require price concessions. Excluding inventory therefore makes the quick ratio a more stringent, conservative test of whether Flash can settle maturing obligations from its most readily available resources, complementing the broader current-ratio measurement described in ASC 210-10-45-9.",
  "ExplanationWrongA": "Under ASC 210-10-45-1, inventory is a current asset because it is expected to be realized through sale within the normal operating cycle of a manufacturing business. Inventory is excluded from the quick ratio not because of its balance-sheet classification, but because it is the slowest of the current assets to convert into cash and may require a price concession to sell quickly. A noncurrent classification premise misstates the standard's classification guidance.",
  "ExplanationWrongB": "The quick ratio is a liquidity measure, not a profitability measure; profitability is assessed through margins and returns such as gross margin or return on assets. Inventory is excluded from the quick ratio because it takes longer to convert into cash than cash, marketable securities, or receivables, and its conversion may require a price concession — not because the ratio targets a different performance dimension than liquidity.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Inventory is rarely financed dollar-for-dollar by the payables used to acquire it: purchases may be made for cash, and accounts payable reflect the credit terms of specific suppliers rather than the inventory balance as a whole. The quick ratio excludes inventory because of its relatively slow conversion to cash, and the broader current ratio would still include both inventory and accounts payable as separately measured current items.",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-02: Quick (Acid-Test) Ratio",
  "CommonTrapReference": "Attributing inventory's exclusion from the quick ratio to noncurrent classification or to a profitability focus.",
  "Authorities": [
    "ASC 210-10-45-1 (current assets)",
    "ASC 210-10-45-9 (working capital)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true (CMA Part 2 Financial Statement Analysis item).",
    "EW[CorrectChoice] is exactly the empty string (DL-008 compliant).",
    "All non-correct ExplanationWrong slots are >=75 characters and choice-specific (DL-026 compliant).",
    "No boilerplate text; explanations are item-specific (DL-013 prevention).",
    "Difficulty justified: one-concept explanation in familiar context with straightforward distractors — Moderate-Easy (DS 2).",
    "Correct answer independently derived from ASC 210-10-45-1 current-asset classification logic and the acid-test definition.",
    "Authority citations (ASC 210-10-45) match the tested liquidity concept (quick ratio numerator composition).",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: Understand level; 'Under U.S. GAAP' with no weighing language satisfies AF-3; no AF-4 trigger in stem."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.403 current-ratio-computation",
  "QuestionID": "P2-A-403",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-403-current-ratio-computation",
  "Stem": "Flash Manufacturing's December 31, 20X5 balance sheet, prepared by Mariela Hoffmann's staff, reports cash of $48,000; short-term marketable securities of $72,000; accounts receivable (net) of $156,000; inventory of $204,000; prepaid expenses of $24,000; accounts payable of $140,000; accrued liabilities of $60,000; and a current portion of long-term debt of $40,000. Under U.S. GAAP, what is Flash Manufacturing's current ratio at December 31, 20X5?",
  "Choices": {
    "A": "2.52",
    "B": "0.50",
    "C": "0.48",
    "D": "2.10"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Current ratio = Current assets ÷ Current liabilities. Under ASC 210-10-45, all five asset balances are current assets: $48,000 + $72,000 + $156,000 + $204,000 + $24,000 = $504,000. Current liabilities include the current portion of long-term debt together with accounts payable and accruals: $140,000 + $60,000 + $40,000 = $240,000. Current ratio = $504,000 ÷ $240,000 = 2.10. Recomputed: 504,000 ÷ 240,000 = 2.10. Flash holds $2.10 of current assets for every $1.00 of current liabilities, a level above the conventional 2.0 benchmark; however, because inventory dominates the numerator, the quality of those current assets should be reviewed before relying on the ratio as evidence of strong liquidity.",
  "ExplanationWrongA": "This result omits the $40,000 current portion of long-term debt from the denominator, dividing $504,000 by $140,000 + $60,000 = $200,000 to obtain 2.52. Under ASC 210-10-45, the current portion of long-term debt is a current liability because it will be repaid within the operating cycle using current assets. Excluding it overstates the current ratio and understates Flash's near-term obligations.",
  "ExplanationWrongB": "This result uses only cash and short-term marketable securities in the numerator: $48,000 + $72,000 = $120,000, divided by $240,000 = 0.50. That is the cash ratio, a much more conservative measure than the current ratio. The current ratio includes all current assets — receivables, inventory, and prepaid expenses as well — so this answer understates Flash's full current-asset coverage of current liabilities.",
  "ExplanationWrongC": "This answer inverts the ratio, dividing current liabilities by current assets: $240,000 ÷ $504,000 = 0.48. The current ratio is defined as current assets divided by current liabilities, expressing how many dollars of current assets back each dollar of current liabilities. Inverting the fraction understates Flash's liquidity coverage and reverses the meaning of the measure.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-01: Current Ratio",
  "CommonTrapReference": "Omitting the current portion of long-term debt from current liabilities; inverting the ratio; substituting the cash ratio for the current ratio.",
  "Authorities": [
    "ASC 210-10-45-1 (current assets)",
    "ASC 210-10-45-3 (current liabilities)",
    "ASC 210-10-45-9 (working capital)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true (CMA Part 2 Financial Statement Analysis item).",
    "EW[CorrectChoice] is exactly the empty string (DL-008 compliant).",
    "All non-correct ExplanationWrong slots are >=75 characters and choice-specific (DL-026 compliant).",
    "No boilerplate text; explanations are item-specific (DL-013 prevention).",
    "Difficulty justified: direct computation with one classification trap (current portion of long-term debt) — Moderate (DS 3).",
    "Correct answer independently derived by recomputation: 504,000 ÷ 240,000 = 2.10; result cross-checked against the CorrectChoice text.",
    "Authority citations (ASC 210-10-45) match the tested concept (current ratio and current-liability classification).",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: Apply level; 'Under U.S. GAAP' with a compute instruction satisfies AF-3; no AF-4 trigger.",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.404 quick-ratio-computation",
  "QuestionID": "P2-A-404",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-404-quick-ratio-computation",
  "Stem": "At December 31, 20X5, Flash Manufacturing reports cash of $40,000; short-term marketable securities of $35,000; accounts receivable (net) of $95,000; inventory of $160,000; and prepaid expenses of $20,000. Current liabilities total $190,000, including a $30,000 current portion of long-term debt. Under U.S. GAAP, what is Flash Manufacturing's quick (acid-test) ratio?",
  "Choices": {
    "A": "1.74",
    "B": "1.00",
    "C": "1.12",
    "D": "0.89"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Quick ratio = (Cash + short-term marketable securities + net accounts receivable) ÷ Current liabilities. Numerator: $40,000 + $35,000 + $95,000 = $170,000. Denominator: all current liabilities, including the current portion of long-term debt, total $190,000. Quick ratio = $170,000 ÷ $190,000 = 0.89. Recomputed: 170,000 ÷ 190,000 = 0.8947 ≈ 0.89. Under ASC 210-10-45, inventory and prepaid expenses are current assets, but they are excluded from the acid-test numerator because they are not as readily convertible to cash. A quick ratio below 1.0 means Flash's near-cash assets alone do not fully cover current liabilities, so collections and cash generation from operations are important for meeting near-term obligations.",
  "ExplanationWrongA": "This result incorrectly includes inventory in the numerator: $40,000 + $35,000 + $95,000 + $160,000 = $330,000, divided by $190,000 = 1.74. Inventory is excluded from the acid-test ratio because it must be sold and collected before producing cash, and disposal may require price concessions. Including inventory converts the measure into a broader liquidity test and overstates Flash's ability to cover current liabilities from near-cash assets.",
  "ExplanationWrongB": "This result includes prepaid expenses in the numerator: $170,000 + $20,000 = $190,000, divided by $190,000 = 1.00. Prepaids represent payments for future benefits, such as insurance or rent, that will be consumed rather than converted into cash, so they are excluded from the quick ratio. They belong in the current-ratio numerator under ASC 210-10-45, but not in the acid-test numerator, which is limited to near-cash assets.",
  "ExplanationWrongC": "This answer inverts the relationship, dividing current liabilities by the liquid-asset numerator: $190,000 ÷ $170,000 = 1.12. The quick ratio is defined as liquid current assets divided by current liabilities. Inverting the fraction makes Flash appear more liquid than the acid-test measure indicates, since a quick ratio of 0.89 means liquid assets cover less than the full amount of current liabilities.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-02: Quick (Acid-Test) Ratio",
  "CommonTrapReference": "Adding inventory or prepaid expenses to the quick-ratio numerator; inverting the acid-test ratio.",
  "Authorities": [
    "ASC 210-10-45-1 (current assets)",
    "ASC 210-10-45-3 (current liabilities)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true (CMA Part 2 Financial Statement Analysis item).",
    "EW[CorrectChoice] is exactly the empty string (DL-008 compliant).",
    "All non-correct ExplanationWrong slots are >=75 characters and choice-specific (DL-026 compliant).",
    "No boilerplate text; explanations are item-specific (DL-013 prevention).",
    "Difficulty justified: direct computation with multiple classification traps — Moderate (DS 3).",
    "Correct answer independently derived by recomputation: 170,000 ÷ 190,000 = 0.8947 ≈ 0.89; result cross-checked against the CorrectChoice text.",
    "Authority citations (ASC 210-10-45) match the tested concept (quick ratio and current-asset classification).",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: Apply level; 'Under U.S. GAAP' with a compute instruction satisfies AF-3; no AF-4 trigger."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.405 liquidity-composition-analysis",
  "QuestionID": "P2-A-405",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-405-liquidity-composition-analysis",
  "Stem": "Adaeze Onuorah has asked Mariela Hoffmann to analyze Flash Manufacturing's year-end liquidity. Flash reports cash of $45,000; accounts receivable (net) of $165,000; inventory of $330,000; prepaid expenses of $60,000; and total current liabilities of $300,000. Compute Flash's current ratio and quick (acid-test) ratio, and select the statement that best analyzes what the relationship between the two measures reveals about Flash's liquidity.",
  "Choices": {
    "A": "Current ratio 0.50 and quick ratio 0.70; Flash's current assets cover only half of its current liabilities, indicating a severe liquidity shortfall.",
    "B": "Current ratio 2.00 and quick ratio 1.80; including inventory in the numerator shows that Flash's liquid assets comfortably exceed current liabilities.",
    "C": "Current ratio 2.00 and quick ratio 0.90; prepaid expenses are as liquid as receivables and should be included in the acid-test numerator.",
    "D": "Current ratio 2.00 and quick ratio 0.70; inventory and prepaid expenses make up 65% of current assets, so the current ratio overstates Flash's near-term cash availability."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Current ratio = $600,000 ÷ $300,000 = 2.00; quick ratio = ($45,000 + $165,000) ÷ $300,000 = $210,000 ÷ $300,000 = 0.70. Inventory plus prepaid expenses is $390,000, or 65% ($390,000 ÷ $600,000) of current assets. Recomputed: current assets 45,000 + 165,000 + 330,000 + 60,000 = 600,000; 600,000 ÷ 300,000 = 2.00; liquid assets 45,000 + 165,000 = 210,000; 210,000 ÷ 300,000 = 0.70; (330,000 + 60,000) ÷ 600,000 = 65%. The wide gap between the current ratio of 2.00 and the quick ratio of 0.70 shows that Flash's headline coverage is driven by inventory and prepaid expenses — assets that are not near-cash — so the current ratio overstates the company's ability to pay maturing obligations from immediately available resources.",
  "ExplanationWrongA": "This answer inverts the current ratio: $300,000 ÷ $600,000 = 0.50. Flash's current assets of $600,000 are twice its current liabilities of $300,000, so the current ratio is 2.00, not 0.50. The quick ratio is correctly 0.70, but concluding that current assets cover only half of current liabilities misreads the relationship and overstates the severity of Flash's liquidity position.",
  "ExplanationWrongB": "This pair of ratios adds inventory to the acid-test numerator: $45,000 + $165,000 + $330,000 = $540,000, divided by $300,000 = 1.80. Inventory is excluded from the quick ratio because it must be sold and collected before producing cash, and disposal may require price concessions. Treating inventory as a near-cash asset masks the true gap between Flash's broad current-asset coverage and its immediately liquid resources, so it cannot support a conclusion of comfortable liquidity.",
  "ExplanationWrongC": "This answer includes prepaid expenses in the acid-test numerator: $45,000 + $165,000 + $60,000 = $270,000, divided by $300,000 = 0.90. Prepaids are payments for future benefits, such as insurance or rent, that will be consumed rather than converted into cash, so they are excluded from the quick ratio. Their 20% share of current assets ($60,000 ÷ $600,000) helps explain why the current ratio exceeds the quick ratio; it does not justify treating them as liquid assets.",
  "ExplanationWrongD": "",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-01: Current Ratio; FA-02: Quick (Acid-Test) Ratio",
  "CommonTrapReference": "Reading the current ratio as evidence of near-cash liquidity; adding inventory or prepaids to the quick ratio; inverting the current ratio.",
  "Authorities": [
    "ASC 210-10-45-1 (current assets)",
    "ASC 210-10-45-3 (current liabilities)",
    "ASC 210-10-45-9 (working capital)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true (CMA Part 2 Financial Statement Analysis item).",
    "EW[CorrectChoice] is exactly the empty string (DL-008 compliant).",
    "All non-correct ExplanationWrong slots are >=75 characters and choice-specific (DL-026 compliant).",
    "No boilerplate text; explanations are item-specific (DL-013 prevention).",
    "Difficulty justified: requires computing two ratios and analyzing the composition gap between them — Difficult (DS 4).",
    "Correct answer independently derived by recomputation: 600,000 ÷ 300,000 = 2.00; 210,000 ÷ 300,000 = 0.70; (330,000 + 60,000) ÷ 600,000 = 65%.",
    "Authority citations (ASC 210-10-45) match the tested concept (current vs quick ratio composition analysis).",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: Analyze level with DS 4 >= 2 (AF-5); stem avoids 'Under GAAP' phrasing and uses the analysis verb 'analyzes', passing AF-3."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.406 liquidity-trend-evaluation",
  "QuestionID": "P2-A-406",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-406-liquidity-trend-evaluation",
  "Stem": "Adaeze Onuorah must evaluate whether Flash Manufacturing's liquidity improved or deteriorated between December 31, 20X4 and December 31, 20X5. Balance-sheet data are: 20X5 — cash $60,000; accounts receivable (net) $180,000; inventory $240,000; prepaid expenses $20,000; current liabilities $250,000. 20X4 — cash $90,000; accounts receivable (net) $150,000; inventory $150,000; prepaid expenses $10,000; current liabilities $200,000. Which evaluation of Flash's liquidity is best supported by the data?",
  "Choices": {
    "A": "Liquidity improved: the quick ratio of 0.96 in 20X5 still covers 96% of current liabilities, and a quick ratio above 0.90 is strong for a manufacturer.",
    "B": "Liquidity was unchanged: the current ratio of 2.00 in both years proves that Flash's ability to meet short-term obligations did not change.",
    "C": "Liquidity deteriorated: the current ratio held at 2.00 in both years, but the quick ratio fell from 1.20 to 0.96 and the cash ratio fell from 0.45 to 0.24 as liquidity shifted from cash into slower-moving inventory and receivables.",
    "D": "Liquidity improved: total current assets grew from $400,000 to $500,000, a 25% increase, and the current ratio remained at 2.00, showing Flash can more comfortably cover its obligations."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Evaluating Flash's liquidity requires examining both the level and the composition of current assets. Current ratio: 20X4 = $400,000 ÷ $200,000 = 2.00; 20X5 = $500,000 ÷ $250,000 = 2.00. Quick ratio: 20X4 = ($90,000 + $150,000) ÷ $200,000 = 1.20; 20X5 = ($60,000 + $180,000) ÷ $250,000 = 0.96. Cash ratio: 20X4 = $90,000 ÷ $200,000 = 0.45; 20X5 = $60,000 ÷ $250,000 = 0.24. Recomputed: 240,000 ÷ 200,000 = 1.20 and 240,000 ÷ 250,000 = 0.96. Although the current ratio was stable, the quality of current assets weakened: cash fell while inventory rose from $150,000 to $240,000, so Flash's ability to settle maturing obligations from near-cash assets deteriorated. A stable current ratio that masks a shift toward less liquid assets is a weaker liquidity signal, so an evaluation resting only on the current ratio is incomplete.",
  "ExplanationWrongA": "This evaluation treats the 20X5 quick ratio of 0.96 in isolation and applies an unsupported rule of thumb. The comparison that matters is the change over time: the quick ratio fell from 1.20 in 20X4 to 0.96 in 20X5, and the cash ratio fell from 0.45 to 0.24, while the current ratio was flat at 2.00. Citing an arbitrary benchmark does not offset the demonstrated deterioration in the quality of Flash's current assets.",
  "ExplanationWrongB": "This evaluation assumes the current ratio is a complete measure of liquidity. It was 2.00 in both years, but the composition changed materially: cash fell from $90,000 to $60,000, inventory rose from $150,000 to $240,000, and the quick ratio fell from 1.20 to 0.96. A stable current ratio with a worsening quick ratio indicates the mix of current assets became less liquid, so concluding liquidity was unchanged is not supported by the data.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "This evaluation focuses on the growth in total current assets and the stable current ratio but ignores the composition of that growth. Current assets grew mainly because inventory rose from $150,000 to $240,000 while cash fell from $90,000 to $60,000. The quick ratio declined from 1.20 to 0.96 and the cash ratio from 0.45 to 0.24, so the additional coverage came from slower-moving assets, weakening rather than strengthening Flash's near-term liquidity.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-01: Current Ratio; FA-02: Quick (Acid-Test) Ratio; FA-03: Cash Ratio",
  "CommonTrapReference": "Judging liquidity from the current ratio alone; ignoring the deteriorating mix of current assets; relying on rule-of-thumb benchmarks.",
  "Authorities": [
    "ASC 210-10-45-1 (current assets)",
    "ASC 210-10-45-9 (working capital)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true (CMA Part 2 Financial Statement Analysis item).",
    "EW[CorrectChoice] is exactly the empty string (DL-008 compliant).",
    "All non-correct ExplanationWrong slots are >=75 characters and choice-specific (DL-026 compliant).",
    "No boilerplate text; explanations are item-specific (DL-013 prevention).",
    "Difficulty justified: multi-period evaluation requiring ratio computation plus a judgment on liquidity quality — Difficult (DS 4).",
    "Correct answer independently derived by recomputation: current 2.00/2.00; quick 1.20 vs 0.96; cash 0.45 vs 0.24; all cross-checked against the CorrectChoice text.",
    "Authority citations (ASC 210-10-45) match the tested concept (liquidity ratio trend and current-asset composition).",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: Evaluate level with DS 4 >= 3 (AF-5); stem uses 'evaluate'/'best supported' and avoids 'Under GAAP', passing AF-3."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.407 quick-ratio-covenant-computation",
  "QuestionID": "P2-A-407",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-407-quick-ratio-covenant-computation",
  "Stem": "Mariela Hoffmann must compute Flash Manufacturing's quick (acid-test) ratio for a lender covenant compliance report. At December 31, 20X5, Flash has cash of $32,000; short-term marketable securities of $58,000; accounts receivable (net) of $120,000; inventory of $150,000; prepaid expenses of $18,000; accounts payable of $96,000; accrued liabilities of $44,000; and a current portion of long-term debt of $60,000. Flash's accounts receivable at January 1, 20X5 were $100,000. Under U.S. GAAP, what is Flash Manufacturing's quick ratio at December 31, 20X5?",
  "Choices": {
    "A": "1.00",
    "B": "1.50",
    "C": "1.80",
    "D": "1.05"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Quick ratio = (Cash + short-term marketable securities + net accounts receivable) ÷ Current liabilities. Numerator: $32,000 + $58,000 + $120,000 = $210,000. Denominator — all obligations due within the operating cycle, including the current portion of long-term debt: $96,000 + $44,000 + $60,000 = $200,000. Quick ratio = $210,000 ÷ $200,000 = 1.05. Recomputed: 210,000 ÷ 200,000 = 1.05. A balance-sheet ratio uses ending balances under ASC 210-10-45, so the January 1 receivable balance is not averaged into this point-in-time measure. A quick ratio of 1.05 means Flash's near-cash assets marginally exceed current liabilities, so the covenant remains met, though the margin is thin and sensitive to receivable collectibility.",
  "ExplanationWrongA": "This answer averages the receivable balance: ($100,000 + $120,000) ÷ 2 = $110,000, giving a numerator of $32,000 + $58,000 + $110,000 = $200,000 and a ratio of $200,000 ÷ $200,000 = 1.00. The quick ratio is a point-in-time balance-sheet measure; under ASC 210-10-45 it uses the ending receivable balance of $120,000. Averaging is appropriate when a flow measure is paired with a balance measure, not for a ratio of two balance-sheet amounts.",
  "ExplanationWrongB": "This answer omits the $60,000 current portion of long-term debt from the denominator: $96,000 + $44,000 = $140,000, giving $210,000 ÷ $140,000 = 1.50. Under ASC 210-10-45, the current portion of long-term debt is a current liability because it will be repaid within the operating cycle using current assets. Excluding it inflates the quick ratio and could cause Flash's covenant compliance to be overstated.",
  "ExplanationWrongC": "This answer includes inventory in the numerator: $32,000 + $58,000 + $120,000 + $150,000 = $360,000, divided by $200,000 = 1.80. Inventory is excluded from the quick ratio because it must be sold and collected before generating cash, and disposal may require price concessions. Including it converts the measure into a broader liquidity test and materially overstates Flash's near-cash coverage of its current obligations.",
  "ExplanationWrongD": "",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-02: Quick (Acid-Test) Ratio",
  "CommonTrapReference": "Averaging balance-sheet amounts for a point-in-time ratio; omitting the current portion of long-term debt; adding inventory to the quick ratio.",
  "Authorities": [
    "ASC 210-10-45-1 (current assets)",
    "ASC 210-10-45-3 (current liabilities)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true (CMA Part 2 Financial Statement Analysis item).",
    "EW[CorrectChoice] is exactly the empty string (DL-008 compliant).",
    "All non-correct ExplanationWrong slots are >=75 characters and choice-specific (DL-026 compliant).",
    "No boilerplate text; explanations are item-specific (DL-013 prevention).",
    "Difficulty justified: multi-trap computation (ending vs average balances, current portion of LTD, inventory) — Very Difficult (DS 5).",
    "Correct answer independently derived by recomputation: 210,000 ÷ 200,000 = 1.05; result cross-checked against the CorrectChoice text.",
    "Authority citations (ASC 210-10-45) match the tested concept (quick ratio, point-in-time balances, current-liability classification).",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: Apply level; 'Under U.S. GAAP' with a compute instruction satisfies AF-3; no AF-4 trigger."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.408 operating-vs-financial-leverage",
  "QuestionID": "P2-A-408",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-408-operating-vs-financial-leverage",
  "Stem": "Mariela Hoffmann is drafting a memo for Adaeze Onuorah, Flash Manufacturing's CFO, explaining the difference between operating leverage and financial leverage. Which of the following statements most accurately describes that difference?",
  "Choices": {
    "A": "Operating leverage is the ratio of total debt to total assets, while financial leverage is the ratio of fixed operating costs to variable operating costs.",
    "B": "Operating leverage arises from the proportion of fixed operating costs in Flash's cost structure and magnifies the effect of sales changes on operating income; financial leverage arises from the use of debt financing and magnifies the effect of operating income changes on earnings available to shareholders.",
    "C": "Operating leverage measures Flash's ability to pay short-term obligations, while financial leverage measures the company's long-term profitability.",
    "D": "Operating leverage and financial leverage describe the same phenomenon, measured at different points in the operating cycle."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Operating leverage reflects the mix of fixed and variable operating costs in the cost structure: with higher fixed costs, a given percentage change in sales produces a larger percentage change in operating income, because fixed costs do not vary with volume. Financial leverage reflects the capital structure — the use of debt — where fixed interest charges magnify the effect of changes in operating income on earnings available to common shareholders. The two interact through combined leverage, which links sales changes to earnings per share. In the balance-sheet context of ASC 205-10-45 and the current-liability classification of ASC 210-10-45, financial leverage is evaluated alongside liquidity and solvency measures, whereas operating leverage is a cost-structure risk assessed through the income statement.",
  "ExplanationWrongA": "This statement swaps the two definitions: the ratio of total debt to total assets is a financial-leverage (solvency) measure such as the debt-to-assets ratio, while the fixed-versus-variable operating cost relationship is the basis of operating leverage. Confusing the two leads management to misattribute risk: cost-structure risk would be blamed on the capital structure, and debt-related risk would be assessed against the wrong cost driver.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "This statement confuses leverage with liquidity and profitability concepts. Operating leverage is about the sensitivity of operating income to sales changes caused by fixed operating costs, not about paying short-term obligations, which is the domain of the current and quick ratios. Financial leverage concerns the magnification of returns and risk from debt financing, not a direct measure of long-term profitability.",
  "ExplanationWrongD": "Operating leverage and financial leverage are distinct concepts operating at different stages of the income statement: operating leverage links sales changes to operating income through fixed operating costs, while financial leverage links operating income changes to earnings per share through fixed financing charges. They are separate risk-and-return amplifiers that combine into total (combined) leverage; they are not the same phenomenon measured at different times.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-05: Operating vs. Financial Leverage",
  "CommonTrapReference": "Swapping the definitions of operating and financial leverage; confusing leverage with liquidity or profitability measures.",
  "Authorities": [
    "ASC 205-10-45 (balance-sheet presentation)",
    "ASC 210-10-45-3 (debt and current-liability classification)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true (CMA Part 2 Financial Statement Analysis item).",
    "EW[CorrectChoice] is exactly the empty string (DL-008 compliant).",
    "All non-correct ExplanationWrong slots are >=75 characters and choice-specific (DL-026 compliant).",
    "No boilerplate text; explanations are item-specific (DL-013 prevention).",
    "Difficulty justified: conceptual distinction between leverage types with a swapped-definition trap; Moderate/Difficult slot taken at Moderate (DS 3).",
    "Correct answer independently derived from the standard definitions of operating and financial leverage and their income-statement mechanics.",
    "Authority citations (ASC 205-10-45 / ASC 210-10-45) match the tested concept (leverage, solvency, and debt classification context).",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: Understand level; no 'Under GAAP' phrasing and no AF-4 trigger in stem, so AF-3/AF-4 gates are not implicated."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.409 debt-to-equity",
  "QuestionID": "P2-A-409",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-409-debt-to-equity",
  "Stem": "Adaeze Onuorah, CFO of Flash Manufacturing, is preparing the capital structure section of the board deck and asks her staff to pull the company's debt-to-equity ratio. Which of the following formulas defines the debt-to-equity ratio?",
  "Choices": {
    "A": "Total liabilities / Total assets",
    "B": "Long-term debt / Total stockholders' equity",
    "C": "Total liabilities / Total stockholders' equity",
    "D": "Total assets / Total stockholders' equity"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Under U.S. GAAP, the balance sheet classifies obligations as liabilities and residual claims as stockholders' equity (ASC 470 and ASC 505), and the debt-to-equity ratio divides total liabilities by total stockholders' equity. Total liabilities capture all creditor claims, including current obligations such as accounts payable and the current portion of long-term debt as well as noncurrent debt, while equity represents the owners' residual claim on Flash Manufacturing's assets. Higher values of the ratio signal heavier reliance on creditor financing, and because interest and principal must be paid before owners receive anything, they indicate greater credit risk for lenders and greater earnings volatility risk for shareholders.",
  "ExplanationWrongA": "Total liabilities divided by total assets is the liabilities-to-assets (debt) ratio, which expresses the proportion of Flash's assets financed by creditors rather than the relationship between creditor claims and owners' equity; it answers a different question about asset financing and is not the debt-to-equity ratio used in capital structure analysis.",
  "ExplanationWrongB": "Long-term debt divided by stockholders' equity captures only noncurrent borrowings and omits current liabilities such as accounts payable and the current portion of debt, which understates Flash's true creditor claims; the standard debt-to-equity ratio uses total liabilities, not just long-term debt, because all liabilities rank ahead of equity in liquidation.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Total assets divided by total stockholders' equity is the equity multiplier, a leverage measure used in DuPont analysis that shows how many dollars of assets each dollar of equity supports; it is related to leverage but is not the debt-to-equity ratio, which compares creditor claims directly with owners' claims.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Remember",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-06: Debt-to-Equity",
  "CommonTrapReference": "Using only long-term debt (or market values) instead of total book liabilities; confusing debt-to-equity with the equity multiplier",
  "Authorities": [
    "ASC 470",
    "ASC 505"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
