var pack_p2_a_part26 = [
{
  "Authorities": [
    "Market-based valuation convention; financial ratio analysis theory",
    "FASB ASC 260 (Earnings Per Share)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "5.56 times, calculated as diluted EPS divided by the market price per share.",
    "B": "20.00 times, calculated using next year's projected EPS of $2.43 together with the year-end market price.",
    "C": "13.50 times, calculated using basic EPS of $3.60 per share.",
    "D": "18.00 times, calculated as the $48.60 market price divided by diluted EPS of $2.70."
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Inverting P/E into earnings yield; pairing trailing price with forward EPS",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The correct answer is D. Diluted EPS = $54.0M net income available to common / 20.0M diluted weighted-average shares = $2.70. Trailing P/E = $48.60 market price / $2.70 diluted EPS = 18.00 times. Multiples convention pairs the current price with the most conservative trailing earnings figure (diluted, per ASC 260) so investors see earnings per existing share after all potential claims. Interpretation for Sofia's annual-report note: buyers paid $18.00 for each trailing diluted dollar Flash earned — meaningful mainly against peer multiples and Flash's own history, since a high multiple can reflect expected growth or temporarily depressed earnings alike.",
  "ExplanationWrongA": "Choice A inverts the ratio, dividing EPS by price ($2.70 / $48.60 = 5.56%). That computation produces the earnings yield, a different metric expressed in percent; quoting it as 'times' mislabels the instrument and reverses the magnitude relationship investors expect between price and earnings.",
  "ExplanationWrongB": "Choice B pairs the current price with forward EPS ($48.60 / $2.43 = 20.00), producing a forward multiple while labeling it trailing. Mixing bases overstates the multiple by two full turns and breaks comparability with peers reporting trailing figures; next year's projection belongs in guidance commentary, not inside the trailing statistic.",
  "ExplanationWrongC": "Choice C uses basic EPS ($48.60 / $3.60 = 13.50), ignoring the 5.0 million dilutive shares from convertible preferred. ASC 260 requires the diluted figure when potential common shares exist; the basic-based multiple understates P/E by 4.50 turns and presents Flash as materially cheaper than its fully diluted economics warrant.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-16",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-226",
  "Section": "A",
  "Stem": "Flash closed the year with net income available to common shareholders of $54.0 million, basic weighted-average shares of 15.0 million, and diluted weighted-average shares of 20.0 million after convertible preferred dilution; the stock traded at $48.60 at year-end. Investor relations director Sofia Marchetti must quote a trailing P/E ratio in the annual report. What should she report, and on what basis?",
  "Topic": "A.226 Price To Earnings Trailing Diluted",
  "UniqueConceptKey": "A-226-trailing-pe-earnings-yield-inversion",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Apply DS3: EPS basis selection plus P/E mechanics with three numeric traps)",
    "Recomputed: diluted EPS = 54.0/20.0 = 2.70; P/E = 48.60/2.70 = 18.00",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Financial statement analysis theory - limitations of ratio analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Year-end snapshots taken at a seasonal trough misstate normal liquidity, so the deck should footnote the pattern and supplement the ratio with monthly or quarterly average balances.",
    "B": "Ratios self-correct for seasonality because the income statement aggregates a full year of activity, smoothing the balance sheet beneath them.",
    "C": "Seasonality distorts profitability measures such as margins, but liquidity ratios are insensitive to shipment timing.",
    "D": "Benchmarking the December ratio against a steady-demand competitor cancels the seasonal distortion out of the comparison."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Treating a trough-date balance sheet as representative of normal liquidity",
  "CorrectChoice": "A",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "The correct answer is A. Balance-sheet ratios divide point-in-time amounts by point-in-time amounts, so a December 31 close lands wherever the seasonal cycle puts it — for Flash, a trough with lean inventories and cleared payables that prints a 3.1 current ratio against typical mid-year readings near 1.9. Sound practice discloses the seasonal pattern and supplements the snapshot with intra-year averages, giving users a representative liquidity picture. Ravi's caution protects the board from reading cyclical slack as structural strength, a distinction credit analysts rely on when setting terms through the cycle.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B assumes full-year flow statements sanitize point-in-time ratios. Smoothing appears only in turnover-style measures whose numerators aggregate activity; the current ratio's numerator and denominator remain single-day balances at December 31, untouched by how activity averaged across the rest of the year.",
  "ExplanationWrongC": "Choice C confines seasonal distortion to margins. Liquidity positions swing hardest with cycle timing — inventory builds ahead of peak shipments and unwinds afterward — so Flash's current and quick readings move with the calendar even when quarterly margins hold steady, exactly the 3.1-versus-1.9 spread Ravi documented.",
  "ExplanationWrongD": "Choice D selects a benchmark that worsens the problem: a non-seasonal peer's December reflects ordinary-course conditions, so the comparison mixes cycle phase with business-model differences and manufactures a false strength signal instead of canceling anything.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-227",
  "Section": "A",
  "Stem": "Flash's lawn-and-garden product line concentrates shipments in the spring and early summer, leaving inventories lean and payables settled by the December 31 close. Internal auditor Ravi Patel notices the year-end current ratio of 3.1 far exceeds mid-year readings near 1.9 that he samples monthly, and drafts a caution for the board deck. Which statement captures the measurement issue and the proper response?",
  "Topic": "A.227 Seasonality Year End Ratio Distortion",
  "UniqueConceptKey": "A-227-seasonal-balance-snapshot-limitation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Understand DS2: recognizes snapshot-vs-cycle distortion and remedy, no computation)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB ASC 205-10 (Presentation of Financial Statements)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Operating margin compressed because SG&A consumed a growing share of each sales dollar between the two years.",
    "B": "Cost of sales absorbed 3.0 additional points of every sales dollar; the 2.5-point SG&A reduction recouped only part of that drift, leaving operating margin 0.5 points lower despite 12% sales growth.",
    "C": "Because both years posted healthy positive operating income, common-size percentages cannot attribute the compression to any particular cost block.",
    "D": "A 12% sales increase should scale operating margin upward proportionally, so the 0.5-point decline indicates an arithmetic error in the schedules."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Reading common-size shifts as proportional sales effects instead of mix points",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The correct answer is B. Common-size framing isolates composition: cost of sales climbed from 62.0% to 65.0% of sales (+3.0 points), while SG&A discipline recovered 2.5 points (22.0% down to 19.5%), netting to a 0.5-point operating-margin slide (16.0% down to 15.5%). That attribution — input-cost or pricing pressure inside the production block, partly offset by overhead restraint — is precisely what vertical analysis exists to surface. Priya's schedules direct management attention to sourcing and price realization rather than to discretionary spending, and quantify how much SG&A improvement would be needed to neutralize another year of COGS drift.",
  "ExplanationWrongA": "Choice A reads the schedule backwards: SG&A fell from 22.0% to 19.5% of sales. Assigning the compression to the shrinking block mistakes the improving line for the deteriorating one and would send corrective effort at the very cost pool already contributing the offset that limited the margin decline.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C declares the exercise impotent while both margins are positive. The sign of the level is irrelevant to attribution: the purpose of common-size columns is decomposing the change — here +3.0 and −2.5 points — into block-level contributors, which is exactly what identifies where the 0.5-point leak arose.",
  "ExplanationWrongD": "Choice D imposes a mechanical expectation that margin scales with revenue growth. Mix shifts, input inflation, and price concessions routinely decouple the two; a falling margin alongside rising sales is a common internally consistent result, not evidence of defective arithmetic in Priya's schedules.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-228",
  "Section": "A",
  "Stem": "At Flash’s quarterly operating review, controller Priya Chen distributes common-size income statements, expressing each line as a percentage of net sales: cost of sales was 62.0% in 2024 and 65.0% in 2025, SG&A was 22.0% and 19.5%, and operating income was 16.0% and 15.5%; net sales grew 12% nominally over the year. Asked to pinpoint the margin story, which diagnosis is supported by her schedules?",
  "Topic": "A.228 Common Size Margin Squeeze Diagnosis",
  "UniqueConceptKey": "A-228-commonsize-cost-block-attribution",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Analyze DS4: attributes margin change across common-size blocks with offsetting shifts)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB ASC 205-10 (Presentation of Financial Statements)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$5.83 per share.",
    "B": "$6.25 per share.",
    "C": "$5.00 per share.",
    "D": "$4.50 per share."
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Skipping the preferred-equity deduction or using issued/average shares",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The correct answer is C. Book value per common share = (total equity − preferred equity) / common shares outstanding = ($210.0M − $30.0M) / 36.0M = $180.0M / 36.0M = $5.00. Preferred claims rank ahead of common, so the $30.0 million carrying value is deducted before dividing; the denominator uses period-end shares outstanding (40.0M issued less 4.0M treasury). Marcus's published figure tells common holders their residual book claim per share — a historical-cost anchor for the FAQ, not an estimate of market value, which reflects future earnings power rather than recorded equity.",
  "ExplanationWrongA": "Choice A divides undeducted total equity by shares outstanding ($210.0M / 36.0M = $5.83), folding the preferred stock's $30.0 million into the common pool. Preferred ranks senior; leaving it in overstates each common share's residual book claim by $0.83 and defeats the metric's purpose of measuring what remains for common holders specifically.",
  "ExplanationWrongB": "Choice B uses an average share count ($180.0M / 28.8M = $6.25). Book value is a point-in-time stock measure paired by convention with period-end outstanding shares; substituting an average denominator imports flow-measure logic and inflates the result whenever shares were repurchased or retired during the year, as Flash's treasury activity did here.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D divides by shares issued (40.0M, giving $180.0M / 40.0M = $4.50). Treasury shares carry no outstanding claim, so issued-count division spreads common equity across 4.0 million phantom shares and understates book value per actual share by $0.50 — the mirror image of the outstanding-share requirement.",
  "FormulaReference": "FA-18",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-229",
  "Section": "A",
  "Stem": "For the investor-relations FAQ, treasurer Marcus Webb computes book value per common share from Flash's year-end equity section: total shareholders' equity $210.0 million, including preferred stock carried at $30.0 million; 40.0 million common shares issued less 4.0 million treasury shares, leaving 36.0 million outstanding. What figure should Marcus publish?",
  "Topic": "A.229 Book Value Per Share Preferred Deduction",
  "UniqueConceptKey": "A-229-bvps-preferred-and-sharecount-basis",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Apply DS3: preferred deduction plus share-count basis traps around a clean division)",
    "Recomputed: (210.0 - 30.0)/36.0 = 180.0/36.0 = 5.00",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB ASC 830 (Foreign Currency Matters)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The weighted-average exchange rate for the fiscal period.",
    "B": "The historical rate in effect when each sale or cost was originally recorded.",
    "C": "The closing spot rate on the final day of the fiscal year.",
    "D": "The rate embedded in the parent's intercompany funding agreement."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Translating income items at closing spot instead of weighted-average rate",
  "CorrectChoice": "A",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The correct answer is A. Under the current-rate method, ASC 830 translates income-statement amounts at the weighted-average rate for the period — a practical convention matching a year of franc flows to the year's average dollar value — while assets and liabilities translate at the closing rate and the residual translation adjustment accumulates in other comprehensive income rather than net income. Omar's revenue and expense lines therefore take the average rate, keeping translated margin relationships intact and separating currency movement from operating performance in Flash's consolidated trend analysis.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B applies historical transaction rates, the signature of the temporal remeasurement method tied to historical-cost amounts. Zurich's self-contained franc operations call for translation, not remeasurement; dating every translation to original transaction rates would rebuild a mosaic of stale conversions and blur the year's average economics into unrecognizable form.",
  "ExplanationWrongC": "Choice C stretches the closing spot rate across twelve months of flows. The year-end rate belongs to balance-sheet translation under this method; applying one day's price to the whole income statement would import the final-day franc movement into every revenue line and distort comparisons against prior-year averages.",
  "ExplanationWrongD": "Choice D sources a contractual rate from intercompany funding documents. Loan-agreement rates govern settlement of those specific obligations; they hold no GAAP standing for translating third-party operating results and would couple Flash's consolidated income statement to the outcome of a financing negotiation.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-230",
  "Section": "A",
  "Stem": "Flash's Zurich instruments subsidiary keeps books in Swiss francs, and its franc operations are relatively self-contained, so its functional currency is the franc and ASC 830's current-rate translation method applies. Staff accountant Omar Haddad prepares the year-end consolidation and asks which rate translates the subsidiary's revenue and expense lines into U.S. dollars.",
  "Topic": "A.230 Current Rate Method Income Translation",
  "UniqueConceptKey": "A-230-currentrate-income-average-rate",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Remember DS1: single current-rate-method income-translation rule)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Sarbanes-Oxley Section 401 / Regulation S-K Item 303 (off-balance-sheet arrangement disclosure)",
    "FASB ASC 440 (Commitments)",
    "IMA Statement of Ethical Professional Practice"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Sign as drafted and omit quantitative disclosure of the purchase minima, since GAAP recognizes no liability for an executory contract and undisclosed terms bind nobody outside the contract parties.",
    "B": "Restructure with a capitalized prepayment because any long-term purchase commitment is functionally debt that GAAP requires on the face of the balance sheet.",
    "C": "Negotiate the guaranteed minimum down to $9.9 million so the commitment slips below disclosure thresholds and the covenant file stays clean.",
    "D": "Sign the executory agreement, disclose the $14.0 million annual minimums among off-balance-sheet arrangements in the notes and MD&A, and present covenant sensitivity analysis — acknowledging that the economic burden survives even though no liability is booked."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Equating unrecognized liability with no disclosure duty for committed minimums",
  "CorrectChoice": "D",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "The correct answer is D. Executory contracts for future purchases create no GAAP asset or liability until performance occurs, so signing as drafted is permissible accounting — but material off-balance-sheet arrangements demand prominent quantified disclosure under Sarbanes-Oxley Section 401 and Regulation S-K Item 303. Elena and Dana should also show lenders the modeled sensitivity: the $9.0 million prepay route drives D/E from $219.6M/$180.0M = 1.22 to $228.6M/$180.0M = 1.27, breaching the 1.25 covenant, whereas the executory structure preserves headroom honestly. Disclosure does not shrink the $14.0-million-a-year obligation; it makes the commitment visible to users who price Flash's risk, which is the substance-over-form standard the securities rules enforce.",
  "ExplanationWrongA": "Choice A leaps from 'no recognized liability' to 'no disclosure duty,' the opacity error Sarbanes-Oxley Section 401 was enacted to end. Material committed purchase minima shape creditors' expectations regardless of balance-sheet placement; suppressing the numbers invites exactly the credibility collapse the off-balance-sheet disclosure regime was built to prevent.",
  "ExplanationWrongB": "Choice B overcorrects, asserting GAAP forces recognition of every long-term purchase promise. Executory contracts remain off balance sheet unless an asset or liability exists at inception, as with financed arrangements or ASC 460-type guarantees; forced capitalization here would misstate the accounting model even as it flatters a substance-over-form instinct.",
  "ExplanationWrongC": "Choice C engineers the commitment underneath a perceived disclosure floor. Materiality carries qualitative as well as quantitative dimensions — a decade-long take-or-pay deliberately trimmed to dodge thresholds is itself a disclosure-triggering fact, and shaping terms to defeat user information rights conflicts with IMA integrity and credibility standards.",
  "ExplanationWrongD": "",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-231",
  "Section": "A",
  "Stem": "To secure dedicated alloy capacity, Flash negotiates a ten-year take-or-pay agreement with Kestrel Alloys guaranteeing $14.0 million of minimum annual purchases; no asset title passes and the executory contract creates no recognized obligation at signing. Flash's debt-to-equity stands at 1.22 against a 1.25 covenant (liabilities $219.6 million, equity $180.0 million); modeling a debt-funded $9.0 million prepayment alternative lifts the ratio to 1.27, breaching the covenant. CFO Elena Vasquez and general counsel Dana Whitfield weigh signing as drafted versus restructuring to bring the commitment onto the balance sheet. Which course is best supported?",
  "Topic": "A.231 Take Or Pay Off Balance Sheet Disclosure",
  "UniqueConceptKey": "A-231-executory-commitment-disclosure-duty",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Evaluate DS5: named executives trade covenant optics against disclosure duties)",
    "Recomputed: current D/E = 219.6/180.0 = 1.22; prepay route = (219.6+9.0)/180.0 = 228.6/180.0 = 1.27 vs 1.25 covenant",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB Statement No. 33 (Financial Reporting and Changing Prices) - historical constant-dollar model"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$52.0 million, because historical cost is the only supportable measurement basis for the memo.",
    "B": "$91.5 million.",
    "C": "$83.2 million.",
    "D": "$32.5 million."
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Restating with 100 base instead of acquisition-year index; inverting the factor",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The correct answer is C. Constant-dollar restatement scales historical cost by the movement in the general price level from acquisition to present: $52.0M × (176 / 110) = $52.0M × 1.60 = $83.2M. The ratio runs between indexes (176/110, not 176/100) because inflation is measured from Flash's own purchase date. Interpretation for Priya's memo: in today's purchasing power the plant represents $83.2 million of resources, so historical-cost depreciation and asset bases understate replacement economics by $31.2 million — flattering reported ROA and understating the real cost of standing still on capacity investment.",
  "ExplanationWrongA": "Choice A declines the restatement on nominalist grounds. Historical cost is indeed the GAAP carrying basis, but the memo's stated purpose is purchasing-power analysis; refusing the index conversion answers a question the memo did not ask and leaves the $31.2 million measurement gap invisible to the capacity debate Priya is informing.",
  "ExplanationWrongB": "Choice B divides by the index base of 100 ($52.0M × 176/100 = $91.52M), restating as if the plant had been bought at the index's origin year. Skipping the acquisition-date index of 110 overstates the inflation factor by 60% and exaggerates the understatement the memo exists to quantify precisely.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D inverts the conversion factor ($52.0M × 110/176 = $32.5M), deflating a past cost toward a smaller present figure. Inflation raises the current purchasing-power equivalent of old spending; reversing the ratio implies yesterday's dollars were worth less than today's, backwards from what the index data say.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-232",
  "Section": "A",
  "Stem": "Flash acquired its Riverside stamping plant for $52.0 million in a year when the consumer price index stood at 110; the index now reads 176. Controller Priya Chen restates the plant to current general purchasing power for a strategy memo on capacity investment. What restated figure should she show?",
  "Topic": "A.232 Constant Dollar Restatement Acquisition Index",
  "UniqueConceptKey": "A-232-general-price-level-restatement",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Apply DS3: index-base selection and factor orientation around one multiplication)",
    "Recomputed: 52.0 x (176/110) = 52.0 x 1.60 = 83.2",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB ASC 280 (Segment Reporting)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Industrial Automation powered the consolidated improvement — revenue up 38% with segment margins expanding 3.0 points — while Consumer Appliances shrank on both dimensions, so rising mix weight toward Automation explains consolidated margin lift.",
    "B": "Consumer Appliances remains Flash's larger segment in 2025, so consolidated performance still follows the Consumer trajectory.",
    "C": "One segment's gains and the other's losses offset, leaving consolidated margin essentially unchanged over the three-year window.",
    "D": "Extrapolating Industrial Automation's trajectory proves the segment margin will reach 25% in 2026."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Extrapolating segment trends as certainties; anchoring on stale size rankings",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The correct answer is A. Industrial Automation grew revenue 38% (from $80.0M to $110.4M) while expanding segment margin 3.0 points (16.0% to 19.0%); Consumer Appliances contracted revenue 10% (to $86.4M) and shed 3.0 margin points (14.0% to 11.0%). Both vectors push the same direction: the improving, faster-growing segment gains mix weight in consolidation, lifting consolidated margin beyond either standalone trend. Renata's portfolio takeaway — reinvest behind Automation while deciding Consumer's turnaround-or-divest path — follows from the cross-segment comparison under ASC 280 disclosures rather than from either column alone.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B anchors on the historical size ranking. By 2025 Automation ($110.4M) has overtaken Consumer ($86.4M); clinging to the stale larger-segment frame weights the deteriorating business more heavily than current reality supports and misdirects the consolidated narrative Renata will present.",
  "ExplanationWrongC": "Choice C assumes symmetric offset. The segments moved in opposite directions on both measures, which reinforces rather than cancels: gains concentrate in the growing segment while deterioration concentrates in the shrinking one, so consolidated margin migrates toward Automation's profile instead of holding flat.",
  "ExplanationWrongD": "Choice D converts a trend into a certainty. Three data points establish direction, not destiny — extrapolating to a precise 25% margin ignores competitive response, capacity limits, and cyclicality, and dresses projection up as proof in front of a live portfolio decision.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-233",
  "Section": "A",
  "Stem": "Flash reports two segments under ASC 280. Industrial Automation revenue ran $80.0M, $94.0M, and $110.4M over 2023-2025 with segment operating margins of 16.0%, 17.5%, and 19.0%; Consumer Appliances ran $96.0M, $91.2M, and $86.4M with margins of 14.0%, 12.5%, and 11.0%. Chief strategy officer Renata Kovacs asks which conclusion the three-year trend comparison supports for the portfolio review.",
  "Topic": "A.233 Segment Trend Mix Shift Analysis",
  "UniqueConceptKey": "A-233-segment-mix-shift-diagnosis",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Analyze DS4: cross-segment trend synthesis with mix-weight reasoning)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Financial statement analysis theory - benchmarking methodology"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "A net margin under 10 percent marks weak operational execution irrespective of the industry or business model involved.",
    "B": "Figures drawn from audited statements carry standardized meaning, so the 6.8% reading speaks for itself without further framing.",
    "C": "A ratio acquires meaning only against a benchmark — Flash's own multi-year trend, its industry norms, or matched peers — because healthy levels differ sharply across business models.",
    "D": "Benchmarking replaces statement analysis, so Jordan should substitute peer averages for reading Flash's underlying financial statements."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Judging a ratio good or bad without trend, industry, or peer context",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "The correct answer is C. Ratios are relative instruments: 6.8% may signal excellence in distribution-heavy hardware retailing and distress in branded pharmaceuticals, so the number means little until compared with Flash's own trajectory, sector norms, or closely matched competitors. Amara's correction teaches the core limitation of ratio analysis — a computed figure describes, and only context evaluates. Jordan's revision should place 6.8% beside Flash's prior years and the appropriate peer set before attaching any quality label, turning an isolated reading into an interpretable benchmark comparison for the draft summary.",
  "ExplanationWrongA": "Choice A hard-codes a universal threshold. Margin adequacy varies with asset intensity, pricing power, and channel economics; a fixed 10% bar would condemn structurally thinner industries wholesale and excuse fragile high-margin niches, substituting folklore for the analysis Amara is training Jordan to perform.",
  "ExplanationWrongB": "Choice B mistakes audit assurance for interpretive sufficiency. Auditors verify fair presentation, not the strategic meaning of a percentage; 'audited' addresses the reliability of inputs and leaves the evaluative step — against what, compared with whom — completely unanswered in Jordan's draft.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D elevates benchmarking into a substitute for reading the statements themselves. Peer averages summarize outcomes; they cannot reveal why Flash earns its margin or which line items drive gaps with comparables, and leaning on them alone trades genuine understanding for a table lookup.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-234",
  "Section": "A",
  "Stem": "New FP&A analyst Jordan Lee computes Flash's net margin at 6.8% and labels it weak in a draft summary. Finance director Amara Diallo returns the draft, asking Jordan to reconsider what a lone ratio can support. Which principle should guide the revision?",
  "Topic": "A.234 Ratio Benchmark Context Principle",
  "UniqueConceptKey": "A-234-benchmark-relative-meaning",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Understand DS2: states the benchmark-dependence principle, no computation)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "SEC Regulation G / Regulation S-K Item 10(e) (non-GAAP presentation)",
    "FASB ASC 360-10 (Property, Plant, and Equipment - disposal gains)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "17.00%, because the disposal gain is a legitimate component of GAAP net income and requires no adjustment for planning purposes.",
    "B": "14.75%, removing the $6.3 million after-tax gain so the metric reflects recurring earning power of the ongoing asset base.",
    "C": "14.00%, stripping the full $8.4 million pre-tax gain from reported net income.",
    "D": "19.25%, adding the after-tax gain to reported net income to capture total resource productivity."
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Leaving nonrecurring gains inside core-return metrics; ignoring tax on the gain",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The correct answer is B. Reported ROA = $47.6M / $280.0M average total assets = 17.00%. The packaging-line sale is nonrecurring: removing its after-tax effect ($8.4M × (1 − 0.25) = $6.3M) yields core net income of $41.3M and core ROA = $41.3M / $280.0M = 14.75%. Victor's earnings-quality point stands: 2.25 points of the headline return came from a one-time disposal rather than operating assets, and planning on 17.00% overstates sustainable profitability. Presenting the adjustment with reconciliation follows non-GAAP discipline (Regulation G / Item 10(e)) and keeps the core figure auditable rather than promotional.",
  "ExplanationWrongA": "Choice A defends the headline on GAAP-compliance grounds. The gain is properly included in net income — but earnings quality asks whether the level repeats; a planning ROA riding a one-time disposal overstates the return the surviving asset base can generate, which is precisely the overstatement Victor flagged to management.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C deducts the gain pre-tax, computing $47.6M − $8.4M = $39.2M and 14.00%. Disposal gains are taxed, so only $6.3 million of the $8.4 million enriched net income; stripping the full amount overstates the adjustment and understates core ROA by 0.75 points below the correctly tax-effected figure.",
  "ExplanationWrongD": "Choice D moves the gain the wrong way, adding $6.3 million on top of income that already contains it ($53.9M / $280.0M = 19.25%). Double counting inflates the very distortion Victor challenged and would compound, not cure, the planning error the audit committee asked him to quantify.",
  "FormulaReference": "FA-12",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-235",
  "Section": "A",
  "Stem": "Flash's 2025 net income of $47.6 million includes an $8.4 million pre-tax gain on the sale of a packaging line; the marginal tax rate is 25%, making the after-tax contribution $6.3 million. Chief audit executive Victor Nakamura challenges the headline return on assets of 17.0% (net income divided by average total assets of $280.0 million) as overstated for planning purposes. What core ROA should Victor present, and why?",
  "Topic": "A.235 Adjusted Roa Nonrecurring Gain",
  "UniqueConceptKey": "A-235-core-roa-disposal-gain-exclusion",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified (Apply DS3: tax-effected exclusion arithmetic inside an earnings-quality frame)",
    "Recomputed: reported ROA = 47.6/280.0 = 17.00%; core NI = 47.6 - 8.4x0.75 = 41.3; core ROA = 41.3/280.0 = 14.75%",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
}
];
