var pack_p2_a_part10 = [
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "MedCore's ROE is more sustainable because its higher net profit margin of 8.4% indicates superior pricing power and cost control that will persist across economic cycles, regardless of the lower asset turnover.",
    "B": "Both ROEs are equally sustainable because the identical 18.2% outcome and identical equity multiplier mean the two companies face identical risk profiles for credit assessment purposes.",
    "C": "MedCore's ROE is more sustainable because a higher net profit margin is less susceptible to deterioration than asset turnover, making MedCore's earnings quality superior for long-term credit evaluation.",
    "D": "Harbor Drug Supply's ROE is more sustainable because its high asset turnover of 2.2x indicates efficient operations that generate revenue from a smaller asset base, while its lower margin reflects a volume-driven strategy that is more defensible in a competitive market."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Interpreting ROE as a self-contained quality measure without decomposing into DuPont drivers",
  "CorrectChoice": "D",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The correct answer is D. Under ASC 205-10, financial statement analysis for credit evaluation must assess the quality and sustainability of returns, not merely their level. Harbor Drug Supply generates its 18.2% ROE through asset efficiency (turnover of 2.2x) on a thin but stable margin of 4.2%. This DuPont profile is characteristic of a high-volume distribution business model — the company turns inventory rapidly, manages receivables tightly, and generates revenue from modestly priced goods, making it resilient to margin compression because competitors cannot easily replicate the operational efficiency. MedCore's 8.4% margin on 1.1x turnover suggests a premium-pricing strategy with lower volume throughput. In pharmaceutical distribution, a high-margin strategy is vulnerable to price competition from generic entrants, consolidation among hospital purchasing groups, and regulatory pressure on drug pricing.",
  "ExplanationWrongA": "Option A restates that MedCore's higher net profit margin indicates superior sustainability. This is incorrect because in the pharmaceutical distribution industry, high-margin strategies are vulnerable to price competition and regulatory pressure that can rapidly compress margins. Asset turnover reflects operational efficiency embedded in infrastructure, which competitors cannot replicate quickly.",
  "ExplanationWrongB": "Option B restates that identical ROE and equity multiplier mean identical risk profiles. This is incorrect because the DuPont decomposition reveals that identical top-line ROE can be produced by fundamentally different business strategies — MedCore's margin-driven model and Harbor's turnover-driven model carry different sensitivity to competitive pressures and regulatory changes.",
  "ExplanationWrongC": "Option C restates that higher net profit margin is less susceptible to deterioration than asset turnover. This is incorrect for distribution businesses: margins are more exposed to competitive and regulatory threats than turnover, which reflects core operating efficiency. In pharmaceutical distribution specifically, high-margin strategies face greater disruption risk than high-volume strategies.",
  "ExplanationWrongD": "",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-058",
  "Section": "A",
  "Stem": "Two pharmaceutical distributors, MedCore Inc. and Harbor Drug Supply, reported identical return on equity of 18.2% for the fiscal year. However, the credit analyst, James Okonkwo, notes significant differences in their DuPont decomposition. MedCore's net profit margin is 8.4%, asset turnover is 1.1x, and equity multiplier is 1.97x. Harbor Drug Supply's net profit margin is 4.2%, asset turnover is 2.2x, and equity multiplier is 1.97x. Both companies operate with identical equity multipliers because they target the same debt-to-capital ratio of 49%. Okonkwo must determine which company's ROE is more sustainable for a 7-year credit facility.",
  "Topic": "A.058 DuPont ROE component performance differential",
  "UniqueConceptKey": "A-058-dupont-roe-component-performance-differential",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Net income of $34.2 million is the better predictor because GAAP accrual accounting smooths timing differences, and the revenue recognized from the new chain contracts represents genuine economic value that will eventually convert to cash.",
    "B": "Neither metric alone is sufficient, and the bank must require audited cash flow forecasts for all 5 years, because any divergence between reported income and operating cash flow invalidates both measures for credit analysis.",
    "C": "Operating cash flow of $6.1 million is the better predictor because cash actually generated from operations measures the liquidity available to service debt, whereas net income includes non-cash accruals that may not materialize if the new chain customers delay or default on payment.",
    "D": "The average of net income and operating cash flow, $20.15 million, is the appropriate measure because it balances the accrual perspective with the cash perspective and represents the most unbiased estimate of debt service capacity."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Treating net income as interchangeable with operating cash flow for credit analysis purposes",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The correct answer is C. Under ASC 230-10, the statement of cash flows provides information about an entity's cash receipts and cash payments during a period, which is essential for assessing liquidity, financial flexibility, and ability to service obligations. For credit analysis, operating cash flow is a superior predictor of creditworthiness because debt service requires actual cash, not accrual income. Trelawny's $34.2 million in net income includes $15.8 million of revenue recognized on extended payment terms — income that has been earned under ASC 606 but has not been collected. If the home-improvement chains delay payment or experience financial difficulty, those receivables may never convert to cash. Operating cash flow of $6.1 million reflects the actual cash generated that is available to pay interest and principal. Accrual income signals economic performance; operating cash flow signals debt service capacity.",
  "ExplanationWrongA": "Option A restates that net income is the better predictor because accrual accounting smooths timing differences and revenue will eventually convert to cash. This is incorrect because credit analysis must evaluate whether receivables will actually be collected, not assume conversion. Extended payment terms to large, concentrated customers introduce collection risk that accrual income does not capture.",
  "ExplanationWrongB": "Option B restates that neither metric is sufficient and audited 5-year cash flow forecasts must be required. This is incorrect because requiring audited multi-year forecasts is impractical for most borrowers and is not a standard credit underwriting requirement. Historical operating cash flow trends are routinely used in credit analysis as the primary predictor.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D restates that averaging net income and operating cash flow at $20.15 million is the appropriate measure. This is incorrect because simple averaging has no theoretical or empirical basis in credit analysis. It combines a cash measure ($6.1M of actual inflows) with an accrual measure ($34.2M of recognized but partially uncollected revenue), producing a synthetic figure that masks the true cash constraint on debt service.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-059",
  "Section": "A",
  "Stem": "Grandview Bank is reviewing a $50 million credit facility for Trelawny Building Products, a manufacturer of commercial roofing systems. Trelawny reported net income of $34.2 million for the year, a 22% increase from the prior year. However, operating cash flow was $6.1 million, down from $18.4 million in the prior year. The divergence stems from a $15.8 million increase in accounts receivable tied to extended payment terms offered to two large home-improvement chains, $8.2 million in inventory buildup for a new product line, and $4.1 million in capitalized software development costs. The credit officer, David Chen, must determine which metric better predicts Trelawny's creditworthiness over a 5-year term.",
  "Topic": "A.059 cash flow accrual divergence creditworthiness",
  "UniqueConceptKey": "A-059-cash-flow-accrual-divergence-creditworthiness",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 470-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The waiver request should be denied because the division sale simultaneously depressed tangible net worth and inflated EBITDA, meaning two of three covenants would be breached on an adjusted basis, and the transaction reveals a pattern of managing covenant compliance rather than addressing underlying credit deterioration.",
    "B": "The waiver should be granted because the $2 million tangible net worth shortfall represents only 4.4% of the covenant threshold and is clearly immaterial, while the other two covenants demonstrate ample cushion and confirm the borrower's fundamental credit strength.",
    "C": "The waiver should be granted for the tangible net worth covenant only, but the debt-to-EBITDA covenant should be recalculated excluding the division sale gain, and if the adjusted ratio exceeds 4.0x, an additional principal payment must be required.",
    "D": "The waiver should be granted because all three covenants serve the same purpose of measuring financial health, and Blackburn's compliance with two of three indicates that the tangible net worth breach is a temporary anomaly caused by an otherwise value-enhancing asset sale."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Evaluating each covenant in isolation without examining interconnected effects of a single transaction",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The correct answer is A. Under ASC 470-10, creditors must evaluate covenant compliance holistically, examining whether reported metrics reflect genuine financial condition. Blackburn's situation reveals interconnected covenant manipulation: the $5.8 million division sale gain inflates EBITDA to $26 million, but adjusting EBITDA to exclude this non-recurring gain reduces it to $20.2 million. This pushes the debt-to-EBITDA ratio to $112M / $20.2M = 5.54x, far exceeding the 4.0x covenant. Simultaneously, the same transaction removed $9.2 million of fixed assets from tangible net worth, creating the $2 million shortfall. On an adjusted basis, two of three covenants are meaningfully breached, not just one marginally. The CFO's portrayal of a single immaterial shortfall misrepresents the economic reality.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B restates that the $2 million shortfall is immaterial and the waiver should be granted. This is incorrect because the shortfall originated from the same division sale that also generated a $5.8 million EBITDA gain. On an adjusted basis excluding the gain, the debt-to-EBITDA ratio would breach the 4.0x covenant at 5.54x, and the $2 million tangible net worth deficiency is a symptom of broader asset erosion.",
  "ExplanationWrongC": "Option C restates that only the EBITDA covenant should be recalculated while the tangible net worth waiver is granted. This is incorrect because treating the two covenant effects as separable ignores their common origin in a single transaction. The division sale's dual impact — EBITDA inflation and tangible net worth depletion — must be evaluated as a unified credit event.",
  "ExplanationWrongD": "Option D restates that compliance with two of three covenants indicates the breach is a temporary anomaly. This is incorrect because the breached covenant — tangible net worth — measures the equity cushion that protects the lender against loss, a fundamentally different dimension than the coverage and leverage covenants. A breach on any covenant signals credit deterioration; compliance on other dimensions does not offset it.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-060",
  "Section": "A",
  "Stem": "TriState Commercial Bank holds a $30 million term loan with Blackburn Steel, a specialty alloy manufacturer. The credit agreement contains three financial covenants: (1) debt-to-EBITDA not exceeding 4.0x, (2) interest coverage ratio of at least 2.5x, and (3) minimum tangible net worth of $45 million. At fiscal year-end, Blackburn reports debt of $112 million, EBITDA of $26 million, interest expense of $12 million, and tangible net worth of $43 million. The CFO, Angela Torres, requests a one-year covenant waiver, arguing that the tangible net worth shortfall of $2 million is immaterial and that the other covenants are comfortably satisfied. The credit analyst, Marcus Webb, notes that $5.8 million of the reported EBITDA comes from a gain on the sale of Blackburn's galvanizing division — a transaction that also removed $9.2 million of fixed assets from tangible net worth.",
  "Topic": "A.060 multi-covenant credit assessment",
  "UniqueConceptKey": "A-060-multi-covenant-credit-assessment",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Current assets divided by total assets, measuring the proportion of short-term resources.",
    "B": "Current assets divided by current liabilities, measuring the ability to meet short-term obligations.",
    "C": "Cash plus receivables divided by current liabilities, measuring immediate liquidity.",
    "D": "Current liabilities divided by current assets, measuring short-term solvency pressure."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing the current ratio with the quick ratio — the current ratio includes inventory and prepaids; the quick ratio excludes them.",
  "CorrectChoice": "B",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Under ASC 205-10, the current ratio is defined as Current Assets divided by Current Liabilities. It measures a company's ability to pay its short-term obligations with its short-term resources. A ratio above 1.0 indicates that current assets exceed current liabilities. The formula is one of the most fundamental liquidity metrics in financial statement analysis and serves as the starting point for assessing working capital adequacy.",
  "ExplanationWrongA": "Option A incorrectly describes the current ratio as current assets divided by total assets. That calculation measures the proportion of current assets in the total asset base, which is a composition metric, not a liquidity ratio.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C describes the quick ratio (acid-test ratio), which excludes inventory and prepaid expenses from the numerator. The current ratio includes all current assets — cash, receivables, inventory, and prepaids — not just cash and receivables.",
  "ExplanationWrongD": "Option D inverts the ratio. Current liabilities divided by current assets would measure the proportion of short-term debt financed by current assets, which is not a standard liquidity metric under ASC 205-10.",
  "FormulaReference": "Current Ratio = Current Assets / Current Liabilities",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-061",
  "Section": "A",
  "Stem": "CFO Rachel Tan of Pacific Retail Group is reviewing the company's liquidity position before a bank meeting. She asks her analyst to compute the ratio that compares all current assets to all current liabilities. Which ratio correctly captures this relationship?",
  "Topic": "A.061 Current Ratio — basic definition and formula components",
  "UniqueConceptKey": "A-061-current-ratio-basic-definition-and-formula-components",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level definition question",
    "Independent answer derived: B correctly defines current ratio per ASC 205-10"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Accounts receivable",
    "B": "Cash and cash equivalents",
    "C": "Inventory",
    "D": "Marketable securities"
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Including inventory in the quick ratio numerator — the quick ratio deliberately excludes inventory because it is the least liquid current asset.",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Inventory is excluded from the quick ratio numerator because it is the least liquid current asset. Converting inventory to cash requires two steps — selling the product and collecting the receivable — making it unreliable for meeting immediate obligations. The quick ratio numerator includes only cash, marketable securities, and accounts receivable, which are more readily convertible to cash. The current ratio numerator includes all current assets, including inventory and prepaid expenses.",
  "ExplanationWrongA": "Accounts receivable are included in both the current ratio and the quick ratio numerator. Receivables are generally considered liquid assets because they are expected to convert to cash within the normal collection cycle.",
  "ExplanationWrongB": "Cash is the most liquid asset and is included in both the current ratio and the quick ratio numerator. It is not excluded from either ratio.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Marketable securities (short-term investments) are included in both the current ratio and the quick ratio numerator because they can be readily sold for cash in public markets.",
  "FormulaReference": "Quick Ratio = (Cash + Marketable Securities + Accounts Receivable) / Current Liabilities",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-062",
  "Section": "A",
  "Stem": "Which asset is excluded from the numerator of the quick ratio but included in the numerator of the current ratio?",
  "Topic": "A.062 Quick Ratio — formula components and what it excludes",
  "UniqueConceptKey": "A-062-quick-ratio-formula-components-and-what-it-excludes",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level identification question",
    "Independent answer derived: C correctly identifies inventory as excluded from quick ratio"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Gross margin, asset turnover, and financial leverage.",
    "B": "Net profit margin, total asset turnover, and equity multiplier.",
    "C": "Operating margin, inventory turnover, and debt-to-equity ratio.",
    "D": "EBITDA margin, fixed asset turnover, and times interest earned."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing the three DuPont components with other common financial ratios — candidates often substitute gross margin for net profit margin or inventory turnover for total asset turnover.",
  "CorrectChoice": "B",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The DuPont identity decomposes ROE into three multiplicative components: Net Profit Margin (Net Income / Sales), Total Asset Turnover (Sales / Average Total Assets), and Equity Multiplier (Average Total Assets / Average Equity). The formula is ROE = Net Profit Margin × Total Asset Turnover × Equity Multiplier. This decomposition reveals whether ROE is driven by operational efficiency (margin), asset productivity (turnover), or financial leverage (equity multiplier). The three-component DuPont model is a foundational tool for financial statement analysis.",
  "ExplanationWrongA": "Option A substitutes gross margin for net profit margin. While gross margin is a component of profitability, the DuPont model uses net profit margin to capture all expenses including operating, interest, and tax costs. Gross margin alone does not represent total operational efficiency.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C substitutes operating margin, inventory turnover, and debt-to-equity. While these are all valid financial metrics, they do not multiply to produce ROE. Inventory turnover is an activity ratio, not an asset productivity measure, and debt-to-equity differs from the equity multiplier.",
  "ExplanationWrongD": "Option D substitutes EBITDA margin, fixed asset turnover, and times interest earned. EBITDA margin excludes depreciation and amortization, making it a different construct from net profit margin. Fixed asset turnover measures only fixed asset efficiency, not total asset efficiency.",
  "FormulaReference": "ROE = Net Profit Margin × Total Asset Turnover × Equity Multiplier",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-063",
  "Section": "A",
  "Stem": "The DuPont identity decomposes return on equity (ROE) into which three components?",
  "Topic": "A.063 DuPont Analysis — three-component decomposition",
  "UniqueConceptKey": "A-063-dupont-analysis-three-component-decomposition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level formula identification",
    "Independent answer derived: B correctly identifies DuPont components"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Net income divided by total assets.",
    "B": "Operating income divided by total equity.",
    "C": "Net income divided by average total equity.",
    "D": "Net income divided by total revenue."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing ROE with ROA — ROE uses equity in the denominator; ROA uses total assets.",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Return on Equity (ROE) is defined as Net Income divided by Average Total Equity. Under ASC 205-10, ROE measures the return generated on shareholders' invested capital. Using average equity (rather than beginning or ending) accounts for equity changes during the period and provides a more representative measure of the equity base that generated the earnings. ROE is one of the most widely used profitability metrics because it directly measures how efficiently management uses equity capital.",
  "ExplanationWrongA": "Option A describes return on assets (ROA), not return on equity. ROA uses total assets in the denominator and measures how efficiently the company uses all its resources, both debt-financed and equity-financed.",
  "ExplanationWrongB": "Option B uses operating income rather than net income. Operating income excludes interest expense and taxes, which are costs borne by equity holders. ROE uses net income available to common shareholders after all expenses.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D describes net profit margin, which measures the percentage of each sales dollar that becomes profit. Net profit margin uses revenue in the denominator, not equity.",
  "FormulaReference": "ROE = Net Income / Average Total Equity",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-064",
  "Section": "A",
  "Stem": "Which of the following formulas correctly expresses return on equity (ROE)?",
  "Topic": "A.064 Return on Equity — basic formula and interpretation",
  "UniqueConceptKey": "A-064-return-on-equity-basic-formula-and-interpretation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level formula identification",
    "Independent answer derived: C correctly defines ROE"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Horizontal analysis expresses each line item as a percentage of a base year; vertical analysis expresses each line item as a percentage of total assets.",
    "B": "Horizontal analysis compares financial data across time periods; vertical analysis expresses each line item as a percentage of a base amount within the same period.",
    "C": "Horizontal analysis is used only for balance sheets; vertical analysis is used only for income statements.",
    "D": "Horizontal analysis requires industry benchmarks; vertical analysis requires only internal data."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Reversing the definitions of horizontal and vertical analysis — horizontal = across time (left to right); vertical = within period (top to bottom).",
  "CorrectChoice": "B",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Horizontal analysis (trend analysis) compares financial data across two or more time periods to identify growth patterns, trends, and anomalies. It typically computes period-over-period changes in both absolute dollar amounts and percentage terms. Vertical analysis (common-size analysis) expresses each line item within a single period's financial statement as a percentage of a base amount — typically total assets for the balance sheet and net sales for the income statement. Both are fundamental tools for comparative financial statement analysis under ASC 205-10.",
  "ExplanationWrongA": "Option A reverses the definitions. Horizontal analysis compares across time periods (not expressing as percentage of base year, though that is one implementation). Vertical analysis expresses as a percentage of a base amount within the same period. The base amount for vertical analysis of the income statement is typically net sales, not total assets.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C incorrectly limits each method to one statement. Both horizontal and vertical analysis can be applied to balance sheets, income statements, and cash flow statements. There is no statement restriction for either technique.",
  "ExplanationWrongD": "Option D claims horizontal analysis requires industry benchmarks. While industry comparisons enhance both types of analysis, neither method requires external benchmarks. Horizontal analysis primarily uses the company's own historical data.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-065",
  "Section": "A",
  "Stem": "Which statement correctly distinguishes horizontal analysis from vertical analysis?",
  "Topic": "A.065 Horizontal vs Vertical Analysis — definitions",
  "UniqueConceptKey": "A-065-horizontal-vs-vertical-analysis-definitions",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level definition question",
    "Independent answer derived: B correctly distinguishes horizontal from vertical analysis"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Total assets.",
    "B": "Gross profit.",
    "C": "Net sales (revenue).",
    "D": "Operating income."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Using total assets as the base for common-size income statements — total assets is the base for balance sheets; net sales is the base for income statements.",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "In a common-size income statement, every line item is expressed as a percentage of net sales (revenue). For example, if cost of goods sold is $600,000 and net sales are $1,000,000, COGS is expressed as 60%. This standardization allows comparison across companies of different sizes and across time periods, as it removes the scale effect of absolute dollar amounts. For the balance sheet, the common-size base is total assets. This technique is central to vertical analysis.",
  "ExplanationWrongA": "Total assets is the base for a common-size balance sheet, not the income statement. Using total assets as the base for income statement items would mix stock and flow measures, producing percentages that are not analytically meaningful.",
  "ExplanationWrongB": "Gross profit would be an unusual base for a common-size income statement. Starting from gross profit excludes cost of goods sold, which is itself an important line item that analysts examine as a percentage of sales.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Operating income would exclude several important income statement line items above it (COGS, SG&A). Using operating income as the base would prevent analysis of how cost structure affects profitability from the top line through to operating income.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-066",
  "Section": "A",
  "Stem": "In a common-size income statement prepared using vertical analysis, each line item is expressed as a percentage of:",
  "Topic": "A.066 Common-Size Financial Statements — purpose and base amounts",
  "UniqueConceptKey": "A-066-common-size-financial-statements-purpose-and-base-amounts",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level definition question",
    "Independent answer derived: C correctly identifies net sales as common-size income statement base"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The sensitivity of net income to changes in interest rates.",
    "B": "The sensitivity of operating income to changes in sales volume.",
    "C": "The proportion of debt in the capital structure.",
    "D": "The ratio of fixed costs to variable costs."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing operating leverage (DOL) with financial leverage (DFL) — DOL reflects cost structure risk; DFL reflects financing risk.",
  "CorrectChoice": "B",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The degree of operating leverage (DOL) measures how sensitive operating income (EBIT) is to changes in sales volume. It is calculated as Contribution Margin divided by Operating Income. A higher DOL indicates that a given percentage change in sales will produce a larger percentage change in operating income, because fixed operating costs magnify the effect of sales changes on profitability. DOL reflects operating risk — the risk inherent in the company's cost structure independent of how the company is financed.",
  "ExplanationWrongA": "Option A describes interest rate sensitivity, which relates to financial risk and the degree of financial leverage (DFL), not operating leverage. DOL is independent of how the company is financed.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C describes financial leverage or the debt-to-equity ratio, which relates to capital structure decisions. DOL concerns the operating cost structure (fixed vs. variable costs), not the financing mix.",
  "ExplanationWrongD": "Option D describes a cost structure ratio. While the ratio of fixed to variable costs influences DOL, DOL itself is a specific elasticity measure (percentage change in EBIT divided by percentage change in sales), not simply the ratio of fixed to variable costs.",
  "FormulaReference": "Degree of Operating Leverage = Contribution Margin / Operating Income",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-067",
  "Section": "A",
  "Stem": "An analyst at Meridian Capital is evaluating how sensitive a manufacturing company's operating income is to changes in sales volume. The degree of operating leverage (DOL) measures:",
  "Topic": "A.067 Degree of Operating Leverage — definition",
  "UniqueConceptKey": "A-067-degree-of-operating-leverage-definition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level definition question",
    "Independent answer derived: B correctly defines DOL"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Gross profit",
    "B": "Earnings before interest and taxes (EBIT)",
    "C": "Net income (or earnings per share)",
    "D": "Operating cash flow"
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing DFL with DOL — DFL measures the sensitivity of net income to EBIT changes; DOL measures the sensitivity of EBIT to sales changes.",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The degree of financial leverage (DFL) measures the sensitivity of net income (or earnings per share) to changes in operating income (EBIT). DFL is calculated as EBIT divided by (EBIT − Interest Expense), or equivalently as the percentage change in EPS divided by the percentage change in EBIT. A higher DFL means that a given change in EBIT produces a larger change in EPS because fixed financing costs (interest) magnify the effect. DFL reflects financial risk — the additional variability in returns to equity holders introduced by the use of debt financing.",
  "ExplanationWrongA": "Gross profit is above the operating income line and is not affected by financing costs. DFL operates below the EBIT line, measuring how fixed financing charges amplify the effect of EBIT changes on earnings available to shareholders.",
  "ExplanationWrongB": "EBIT is the input to DFL, not the output. DFL measures how changes in EBIT affect net income or EPS. The relationship is directional: EBIT is the independent variable and net income is the dependent variable.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Operating cash flow is a cash-basis measure that may differ from accrual-basis earnings. DFL is defined in terms of accrual-basis income measures (EBIT and net income), not cash flows.",
  "FormulaReference": "Degree of Financial Leverage = EBIT / (EBIT − Interest Expense)",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-068",
  "Section": "A",
  "Stem": "The degree of financial leverage (DFL) measures the sensitivity of which income measure to changes in operating income?",
  "Topic": "A.068 Degree of Financial Leverage — definition",
  "UniqueConceptKey": "A-068-degree-of-financial-leverage-definition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level definition question",
    "Independent answer derived: C correctly identifies net income/EPS as DFL output"
  ],
  "question_state": "Certified"
}
];
