var pack_p2_a_part21 = [
{
  "Authorities": [
    "ASC 505-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "6% — using the payout ratio; the target requires a payout cut alone",
    "B": "7.5% — using ROE computed on ending equity; the target is achievable with modest efficiency gains",
    "C": "9% — using the 60% retention ratio; Flash cannot self-fund 12% growth at current ROE and payout, so a lever must move",
    "D": "12% — the board's target is achievable because ROE of 15% exceeds the target"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Using payout instead of retention, or quoting the target as the result",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Sustainable growth rate = ROE x Retention Ratio = 15% x (1 - 40%) = 15% x 60% = 9%. Flash can grow at 9% per year from internally generated funds; the board's 12% target exceeds that, so CFO Priya Sharma must identify which lever to move: raise ROE above 15% through margin or turnover gains, cut the payout below 40%, or fund the gap with new equity. The retention ratio is the complement of the payout ratio — earnings kept rather than distributed — which is why multiplying by the payout (6%) or reading the 12% target as a result are both errors. Average equity underpins the ROE input; using ending equity (7.5%) understates the sustainable rate by distorting the leverage component of ROE.",
  "ExplanationWrongA": "6% multiplies ROE by the payout ratio (15% x 40%) instead of the retention ratio. Sustainable growth uses the earnings Flash retains — 60% here — so the correct result is 9%. Using the dividend payout answers how fast dividends can grow, not how fast Flash can grow its operations.",
  "ExplanationWrongB": "7.5% computes ROE on ending equity ($54M / $432M = 12.5%) and applies the 60% retention ratio. Sustainable growth is built on average equity: ROE of 15% x 0.60 = 9%. The year-end equity base, reduced by this year's dividends, understates Flash's internally funded growth capacity.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "12% is the board's growth target, not a derived result. Sustainable growth from internal funds is ROE x retention = 15% x 60% = 9%. The target only becomes achievable if Flash raises ROE, cuts the payout, or issues equity — which is exactly the gap Sharma must present to the board.",
  "FormulaReference": "Sustainable Growth = ROE x Retention Ratio (1 - Payout) (FA-21)",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-172",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, must present a growth plan to the board, which has set a 12% annual growth target. Flash's return on equity is 15% and its dividend payout ratio is 40% (net income was $54M on average equity of $360M; ending equity was $432M). What sustainable growth rate can Flash fund from retained earnings, and what does that imply for the board's target?",
  "Topic": "A.172 Sustainable growth rate — retention and ROE",
  "UniqueConceptKey": "A-172-sustainable-growth-rate",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 15% x 0.6 = 9%; payout 6%; ending-equity 54/432 = 12.5% x 0.6 = 7.5%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 230-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$56M — the buyback must be scaled back or partially debt-financed",
    "B": "$112M — the buyback is comfortably covered even with the capital program",
    "C": "$32M — the buyback cannot proceed without new borrowing",
    "D": "$80M — the buyback is covered with $20M to spare"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Subtracting dividends or double-counting depreciation in free cash flow",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 230-10, free cash flow = Operating Cash Flow - Capital Expenditures = $128M - $48M = $80M. The $80M is the cash Flash can deploy for buybacks, dividends, or debt reduction after funding the capital program that keeps the plants competitive — the amount CFO Priya Sharma can commit to the $60M buyback without touching the borrowing facility. Dividends ($24M) are a financing distribution and are not deducted: FCF is measured before discretionary uses, so comparing it with the buyback shows Flash generates $80M against a $60M commitment. Depreciation is already embedded in operating cash flow under the indirect method, so adding it back double-counts the non-cash charge. A common exam trap is subtracting dividends ($56M), re-adding depreciation ($112M), or substituting depreciation for cash flow ($32M).",
  "ExplanationWrongA": "$56M subtracts dividends paid ($24M) from operating cash flow after capital expenditures. Free cash flow is the cash available before discretionary distributions — 128 - 48 = $80M — and dividend policy is a financing decision that belongs downstream of FCF, not inside it; folding it in understates the buyback capacity.",
  "ExplanationWrongB": "$112M adds depreciation ($32M) back to operating cash flow before subtracting capital expenditures. Depreciation is already reflected in operating cash flow under the indirect method — adding it again double-counts the non-cash charge and inflates Flash's true free cash flow by $32M.",
  "ExplanationWrongC": "$32M treats depreciation as free cash flow. Depreciation is a non-cash allocation of historical cost, not a cash source; Flash generated $128M of operating cash flow, and after $48M of capital expenditures its free cash flow is $80M, which comfortably covers the proposed buyback.",
  "ExplanationWrongD": "",
  "FormulaReference": "FCF = Operating Cash Flow - Capital Expenditures (FA-23)",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-173",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, is assessing whether Flash can fund a $60M share buyback without new borrowing. Flash's statement of cash flows shows operating cash flow of $128M, capital expenditures of $48M, dividends paid of $24M, and depreciation of $32M. What free cash flow is available for the buyback?",
  "Topic": "A.173 Free cash flow computation",
  "UniqueConceptKey": "A-173-free-cash-flow",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 128 - 48 = $80M; minus dividends 56; plus depreciation 112; dep-only 32",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Vertical analysis — restating each line item as a percentage of net sales (and total assets for the balance sheet) — for the size-free comparison, and horizontal analysis for the base-year trend review",
    "B": "Vertical analysis for both tasks: it measures year-over-year changes in each line item since the base year",
    "C": "Horizontal analysis for both tasks: it restates items as a percentage of net sales within the same year",
    "D": "Vertical analysis for the income statement only, since common-size treatment cannot be applied to the balance sheet"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Swapping vertical and horizontal analysis definitions",
  "CorrectChoice": "A",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Vertical analysis restates each line item as a percentage of a base amount within the same period's statement — typically net sales for the income statement and total assets for the balance sheet — producing common-size statements that let analyst Tom Reyes compare Flash's cost structure with a competitor five times Flash's size without the scale problem. Horizontal (trend) analysis instead measures dollar and percentage changes across periods from a base year, which is exactly the review the board requested for movements since the base year. The two techniques answer different questions: structure versus direction. A common exam trap is swapping the two definitions or claiming vertical analysis cannot apply to the balance sheet.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Year-over-year changes from a base year are horizontal (trend) analysis, not vertical analysis. Vertical analysis restates each line item as a percentage of a base within the same statement — cost of goods sold as a percentage of Flash's net sales — so using it for the trend review answers the wrong question.",
  "ExplanationWrongC": "Restating items as a percentage of net sales within the same year is vertical analysis, not horizontal analysis. Horizontal analysis measures dollar and percentage changes across periods from a base year — the trend view the board requested — so the two techniques cannot both be served by a single method.",
  "ExplanationWrongD": "Vertical analysis applies to the balance sheet as well: line items are expressed as a percentage of total assets, with liabilities and equity each restated against the same base. Restricting it to the income statement discards the common-size capital-structure view the board package needs.",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-174",
  "Section": "A",
  "Stem": "Flash Manufacturing's financial analyst, Tom Reyes, is building the annual board package. The board wants to compare Flash's cost structure with a competitor five times Flash's size and also review how each line item has moved since the base year. Which technique set should Reyes use?",
  "Topic": "A.174 Vertical and horizontal (trend) analysis",
  "UniqueConceptKey": "A-174-vertical-horizontal-analysis",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: conceptual — vertical = common-size, horizontal = trend vs base year",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 606-10",
    "ASC 230-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Earnings include a one-time gain on the sale of a warehouse",
    "B": "The target's EPS has consistently met analyst estimates within 1% for three years, a precision the target credits to disciplined forecasting",
    "C": "Revenue rose 12% while operating cash flow fell 8%, with receivables growing faster than sales and inventory rising at twice the rate of sales",
    "D": "The target has reported higher earnings than in the prior year for eight consecutive quarters"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Reading cash-flow-insensitive revenue growth as high earnings quality",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The strongest earnings-quality red flag is a divergence between the income statement and the cash flow statement: revenue up 12% while operating cash flow falls 8%, with receivables growing faster than sales and inventory rising at twice the sales rate. That combination signals channel stuffing or weak collection — revenue recognized under ASC 606 that is not converting into cash — which means the target's current earnings overstate sustainable earning power and the acquisition price must be discounted. Judgment is required because no single signal is decisive: one-time gains are adjustable, and precisely meeting estimates can itself indicate earnings management. The composite cash-conversion test is the most reliable screen, and it is the pattern ASC 230-10's cash flow statement exists to reveal.",
  "ExplanationWrongA": "A one-time gain on an asset sale is a transient earnings boost, but standing alone it is a single-period item the analyst can adjust out of the earnings base. Revenue growth that fails to convert into cash — the signal in the correct answer — is a recurring, structural earnings-quality problem that adjustment cannot cure.",
  "ExplanationWrongB": "Consistently meeting analyst estimates is not proof of high earnings quality — sustained precision near expectations can itself indicate earnings management, but without cash-flow corroboration it is a weak signal. The decisive test is cash conversion: revenue growth with falling operating cash flow and swelling receivables signals lower quality.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Eight consecutive quarters of year-over-year earnings growth is a trend, not a red flag: growth is expected and, absent supporting detail, tells Sharma nothing about the reliability of the earnings. The warning pattern is growth without cash — revenue rising while operating cash flow falls and receivables build.",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-175",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, is evaluating a $400M acquisition of a supplier. The target reports revenue up 12% and a strong EPS trend. Before pricing the deal, Sharma reviews the target's cash flow statement and balance sheet. Which pattern would most strongly reduce Sharma's confidence in the target's earnings quality?",
  "Topic": "A.175 Earnings quality — red flags assessment",
  "UniqueConceptKey": "A-175-earnings-quality-red-flags",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: conceptual — revenue/CFO divergence is the strongest composite red flag",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "Market-based ratio",
    "Corporate finance theory"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "12.5% — free cash flow divided by market capitalization ($150M ÷ $1,200M)",
    "B": "10.0% — net income divided by market capitalization ($120M ÷ $1,200M)",
    "C": "16.67% — free cash flow divided by invested capital ($150M ÷ $900M)",
    "D": "8.0% — the price-to-FCF multiple itself (8.0x) misread as a percentage yield"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Substituting earnings for cash flow, or scaling by invested capital instead of market value",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Free cash flow yield = Free Cash Flow ÷ Market Capitalization = $150M ÷ $1,200M = 12.5%. The metric expresses how much distributable cash the market pays for each dollar of equity value — Nuvora generates 12.5 cents of free cash flow per dollar of market value. FCF yield serves as both a valuation screen and a quality check: a high yield suggests cheapness or strong cash conversion, while a low yield versus peers can signal overvaluation or heavy reinvestment. Earnings-based substitutes distort the measure because accrual income embeds non-cash charges and working-capital timing that free cash flow strips out.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "10.0% divides NET INCOME by market capitalization — that is an earnings yield (the reciprocal of the P/E), not a free-cash-flow yield. Accrual income includes non-cash charges and collection timing that FCF removes; substituting NI understates Nuvora's cash-generating performance.",
  "ExplanationWrongC": "16.67% divides by invested capital ($900M), producing an internal return measure rather than a market-based yield. FCF yield must be scaled by MARKET CAPITALIZATION to express what investors pay for the cash stream.",
  "ExplanationWrongD": "8.0% misreads the multiple as a yield. The reciprocal relationship runs the other way: $1,200M ÷ $150M is a price-to-FCF multiple of 8.0×, whose yield equivalent is 1/8.0 = 12.5%. Reporting the multiple itself as a percentage inverts the metric.",
  "FormulaReference": "FCF Yield = Free Cash Flow ÷ Market Capitalization",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-176",
  "Section": "A",
  "Stem": "Equity analyst Priya Sharma screens Nuvora Industries: free cash flow of $150M, market capitalization of $1,200M, net income of $120M, and invested capital of $900M. What is Nuvora's free cash flow yield?",
  "Topic": "A.176 Free cash flow yield — cash return on market value",
  "UniqueConceptKey": "A-176-free-cash-flow-yield",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 150/1,200=12.5%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-059"
},
{
  "Authorities": [
    "DuPont framework",
    "Financial ratio analysis theory"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The boutique model is superior because higher margins always indicate a stronger competitive position regardless of asset efficiency",
    "B": "Both earn the same ROA through opposite structures — margin-led differentiation versus turnover-led volume — and each strategy carries distinct risk exposures and sustainability conditions",
    "C": "Turnover is irrelevant to ROA quality because profitability alone drives returns on assets",
    "D": "The warehouse club model cannot be sustainable because low margins signal a failure of pricing power"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Judging business models by margin alone without examining the turnover leg of ROA",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "ROA decomposes into margin × turnover, and the two retailers reach the same 12% destination by opposite routes: the boutique earns 12% margins once per unit of assets, while the club earns 3% four times over. Margin-led models depend on differentiation, brand pricing power, and loyalty — exposed to demand shocks and imitation. Turnover-led models depend on scale economics, cost discipline, and inventory velocity — exposed to price wars and fixed-cost absorption risk. Neither structure dominates universally; the analytical question is whether each firm's competitive position sustains ITS chosen lever across cycles.",
  "ExplanationWrongA": "Higher margins do not universally indicate strength — they must be judged against the turnover that funds returns. The club converts its thin margin into superior ROA through velocity; dismissing it on margin alone misreads the DuPont arithmetic.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Turnover is half of ROA (ROA = NPM × TAT). Ignoring it hides whether returns come from pricing power or from asset productivity — two models with identical ROA can carry entirely different risk profiles.",
  "ExplanationWrongD": "Low margins paired with high turnover describe most successful volume retailers; sustainability depends on cost discipline and inventory velocity, not on achieving boutique-level margins.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-177",
  "Stem": "Portfolio analyst Ethan Brooks compares two retailers earning identical 12% ROA: Meridian Boutique (net margin 12%, asset turnover 1.0) and Brixton Club (net margin 3%, turnover 4.0). Which interpretation of the two business models is correct?",
  "Topic": "A.177 Margin-versus-turnover ROA strategy contrast",
  "UniqueConceptKey": "A-177-margin-versus-turnover-roa-strategy-contrast",
  "LOSTag": "A.2",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Both reach ROA 12% via different NPM x TAT mixes; strategy risk differs",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "ASC 850",
    "ASC 210"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Legally disclosed related-party transactions never affect analytical conclusions because they comply with GAAP",
    "B": "Auditor sign-off on related-party disclosures cures any pricing concerns embedded in those transactions",
    "C": "Demand full disclosure of the affiliation, reprice the transactions at arm's-length terms, and assess whether reported revenue and margin are overstated relative to independent-market economics",
    "D": "Related parties matter only when cash is misappropriated; above-market pricing between affiliates requires no analytical response"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Treating GAAP-compliant disclosure of related-party dealings as proof the transactions are economically arm's-length",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "ASC 850 requires DISCLOSURE of related-party transactions, not arm's-length measurement — a transaction can satisfy GAAP and still be priced at terms no independent party would accept. Revenue booked at above-market prices to a CFO-affiliated entity overstates both revenue quality and margin, may mask deteriorating demand from independent customers, and signals governance weakness. The analyst should quantify the affiliated volume, estimate market-equivalent pricing, restate the affected ratios, and treat unexplained affiliate dependence as a governance red flag feeding the overall risk assessment.",
  "ExplanationWrongA": "GAAP compliance governs recognition and disclosure mechanics, not economic pricing. ASC 850 asks companies to disclose related-party transactions; it contains no requirement that the terms be arm's-length, so compliance coexists with economically distorted revenue.",
  "ExplanationWrongB": "The audit opinion addresses whether disclosures are COMPLETE, not whether affiliated pricing is economically fair. Sign-off confirms the footnote exists; it does not validate that an insider-controlled buyer paid what an independent party would have paid.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Above-market sales to affiliates transfer value without any cash leaving the company — accrual distortions are exactly where related-party abuse hides. Restricting the analysis to cash misappropriation misses the margin and revenue-quality damage entirely.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-178",
  "Stem": "Credit officer Dana Walsh discovers that Harbor Industrial booked $40M of sales to an entity controlled by its CFO at prices roughly 15% above independent-market levels; the transactions were disclosed in the related-party footnote. What analytical response is appropriate?",
  "Topic": "A.178 Related-party transactions — pricing red flags",
  "UniqueConceptKey": "A-178-related-party-transactions-pricing-red-flags",
  "LOSTag": "A.3",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: ASC 850 disclosure does not equal arm-length pricing; reprice and restate ratios",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "Auditor independence literature",
    "Earnings quality analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Auditor changes are always routine engagement rotations and carry no analytical information content",
    "B": "New management automatically resolves the conditions that produced accounting controversy, so history can be disregarded",
    "C": "Personnel and auditor changes affect only internal operations, never external reporting reliability",
    "D": "An involuntary auditor resignation or dismissal combined with a CFO exit inside twelve months is a classic deterioration-and-manipulation warning that warrants deeper scrutiny of past filings"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Dismissing auditor changes as routine without distinguishing voluntary rotation from dismissal or resignation",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Research and SEC enforcement experience both show that auditor DISAGREEMENTS — resignations, dismissals, disputes over accounting treatment — cluster around deteriorating or manipulating firms, while planned rotations follow predictable cycles. The Form 8-K disclosing an auditor change must state whether the disagreement was reportable; a reportable disagreement plus a CFO departure inside a year is one of the strongest composite red flags available to an analyst. It does not prove manipulation; it shifts the burden of proof, justifying deeper scrutiny of revenue recognition, reserves, and prior-period estimates before relying on the reported trend.",
  "ExplanationWrongA": "Rotation programs ARE routine when pre-scheduled after maximum partner tenure — but involuntary changes mid-engagement are categorically different and are disclosed with reasons under Form 8-K Item 4.01. Treating all changes alike discards the signal.",
  "ExplanationWrongB": "New leadership does not erase the historical record: prior-period estimates, reserves, and cutoff decisions remain embedded in reported trends, and remediation takes quarters to evidence. The analyst's baseline of trust must be rebuilt, not assumed.",
  "ExplanationWrongC": "External reporting reliability is exactly what auditor disputes and finance-leadership turnover put at issue: estimates, reserves, and cutoffs depend on judgment that departing personnel may have shaped. Operations and reporting cannot be separated here.",
  "ExplanationWrongD": "",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-179",
  "Stem": "Analyst Jordan Reyes reviews Crestline Steel: the auditor resigned mid-engagement citing a reportable disagreement over revenue recognition, and the CFO departed within six months. How should these events shape reliance on reported results?",
  "Topic": "A.179 Auditor change and CFO turnover signals",
  "UniqueConceptKey": "A-179-auditor-change-and-cfo-turnover-signals",
  "LOSTag": "A.3",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Reportable disagreement plus CFO exit inside 12 months = composite red flag",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "ASC 740",
    "Earnings quality analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "A persistently low effective tax rate driven by unexplained permanent differences signals aggressive positioning that flatters pretax earnings — normalize the rate and probe the differences before trusting the margin",
    "B": "A low effective tax rate reflects superior tax planning efficiency and should raise the analyst's view of management quality",
    "C": "The statutory rate applies uniformly, so reported tax expense never affects earnings comparability across firms",
    "D": "Tax items sit below operating income and therefore never influence assessments of earnings quality"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Reading a persistently favorable book-tax gap as efficiency rather than as an earnings-quality flag",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Under ASC 740, temporary differences reverse, but PERMANENT differences (non-deductible compensation, disputed positions, aggressive credits) do not — they permanently wedge book income away from taxable income. An effective tax rate stuck near 18% against a 25% statutory rate, growing alongside pretax income and unexplained by disclosed credits, suggests earnings are being booked in entities or channels that tax authorities never see. Analysts normalize the ETR toward a sustainable level when comparing margins, because part of the reported advantage may unwind through IRS settlement, repatriation costs, or reputational exposure. The tax line IS an earnings-quality signal, not housekeeping below the fold.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Efficiency explains modest, well-documented advantages — R&D credits, municipal-bond income. A persistent unexplained 7-point gap invites the opposite inference: that reported pretax earnings themselves may be overstated relative to the economics actually being taxed.",
  "ExplanationWrongC": "Statutory rates are starting points; permanent differences, jurisdictional mix, and valuation allowances produce wide dispersion in effective rates. Ignoring the tax line forfeits one of the cleaner tests of earnings quality.",
  "ExplanationWrongD": "Net margin, ROA, and ROE all sit BELOW the tax line — tax distortions flow directly into every return metric the analyst uses. Position in the income statement does not immunize any ratio.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-180",
  "Stem": "Analyst Grace Liu compares two firms with identical pretax income. Firm R reports a stable 25% effective tax rate; Firm S reports 18%, driven by permanent differences management cannot fully explain. Which assessment of Firm S earnings quality is correct?",
  "Topic": "A.180 Effective tax rate anomaly — earnings quality",
  "UniqueConceptKey": "A-180-effective-tax-rate-anomaly-earnings-quality",
  "LOSTag": "A.3",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: ETR 18% vs 25% statutory with unexplained permanents = earnings-quality flag",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "Depreciation method analysis",
    "Comparability adjustments"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "DDB always produces lower depreciation than straight-line, so its year-1 margin overstates the comparison",
    "B": "Year 1: the SL firm expenses $20K and reports EBIT of $30K (37.5% margin); the DDB firm expenses $40K and reports EBIT of $10K (12.5%) — yet both expense the full $100K over five years, so the difference is timing, not economics",
    "C": "Double-declining balance spreads the $100K cost evenly but deducts salvage first, producing permanently lower asset values",
    "D": "Because GAAP permits both methods, the two firms' margins are directly comparable without adjustment"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Comparing margins across depreciation methods without restating to a common basis",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Straight-line charges $100K ÷ 5 = $20K per year; double-declining-balance applies twice the SL rate (40%) to the declining book value: year 1 = $100K × 40% = $40K, year 2 = $60K × 40% = $24K, continuing until fully depreciated. With identical revenue ($80K) and cash operating costs ($30K), year-1 EBIT diverges sharply: SL reports $30K versus DDB's $10K — a 25-point margin gap created purely by method choice. Over the full five years BOTH methods expense exactly $100K, so lifetime earnings converge. Comparing an accelerated depreciator to a straight-line peer requires restating depreciation to a common schedule or evaluating margins over complete asset cycles.",
  "ExplanationWrongA": "DDB front-loads expense: year 1 charges $40K — DOUBLE the straight-line $20K — and only falls below SL in later years as the book value shrinks. Lifetime totals are identical at $100K, so claiming DDB permanently lowers depreciation inverts the method's entire logic.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Neither method deducts salvage here: both depreciate the full $100K cost to zero under the facts given. DDB is an accelerated rate applied to declining book value — the salvage misconception confuses tax conventions and residual-value guarantees with GAAP schedules.",
  "ExplanationWrongD": "Permitted methods differ in TIMING, and timing dominates single-year comparisons: unadjusted cross-method margins flatter straight-line filers by up to 25 points early in an asset's life. Comparability requires restatement to a common schedule or full-cycle evaluation.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-181",
  "Stem": "Twin distributors each bought a $100K truck with a five-year life and zero salvage. Firm SL uses straight-line; Firm DDB uses double-declining balance. Year 1 for both: revenue $80K, cash operating costs $30K. Which statement about year-1 comparability is correct?",
  "Topic": "A.181 Depreciation method comparability — SL versus DDB",
  "UniqueConceptKey": "A-181-depreciation-method-comparability-sl-versus-ddb",
  "LOSTag": "A.4",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: SL EBIT=80-30-20=30 (37.5%); DDB EBIT=80-30-40=10 (12.5%); lifetime totals equal",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "ASC 606",
    "ASC 606-10-25"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Completed-contract accounting would eliminate the manipulation risk because no revenue is recognized until the contract concludes",
    "B": "Engineers' cost-to-cost completion estimates are objective measurements that auditors can verify precisely",
    "C": "Late-year upward revisions to completion percentages accelerate revenue ahead of underlying performance — compare estimate revisions against billing patterns, cash conversion, and contract modifications, and treat divergence as an overstatement flag",
    "D": "Progress billings from customers verify revenue, so recognition timing on long-term contracts cannot be manipulated"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Trusting management-controlled completion estimates without reconciling them to billings and cash",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Under ASC 606's over-time model, revenue tracks the measure of progress — frequently cost-to-cost — which management controls through estimates of costs to complete, change orders, and rework. A contractor that needs a stronger quarter simply reassesses its 'percent complete' upward, booking revenue for work whose economics have not changed. The analyst's discipline is triangulation: if reported revenue accelerates while billings stay flat and receivables balloon, the completion estimates — not demand — are driving results. Estimate revisions, unapproved change orders sitting in contract assets, and implausibly stable gross margins across dissimilar job types are the telltales worth pursuing.",
  "ExplanationWrongA": "Deferral is not a cure: completed-contract recognition produces lumpy, back-loaded revenue that can hide losses on troubled jobs until completion, and cash collection was never the recognition criterion — control transfer drives ASC 606 regardless of method choice.",
  "ExplanationWrongB": "Cost-to-cost inputs look mechanical but rest on judgments about forecasted costs to complete, unpriced change orders, and anticipated inefficiencies. Auditors test the REASONABLENESS of those judgments; they cannot certify an inherently subjective estimate as fact.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Billing schedules are negotiated commercial terms that routinely diverge from performance — front-loaded mobilization bills, retention holdbacks, and unapproved claims all break the billings-equal-revenue link that this argument assumes.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-182",
  "Stem": "Analyst Marcus Lee reviews Crestline Construction: Q4 revenue accelerated while billings stayed flat, receivables jumped 35%, and management revised percent-complete estimates upward on three major contracts. Which conclusion is best supported?",
  "Topic": "A.182 Percentage-of-completion estimate manipulation",
  "UniqueConceptKey": "A-182-percentage-of-completion-estimate-manipulation",
  "LOSTag": "A.3",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Revenue acceleration with flat billings and rising AR points to estimate-driven recognition",
    "Authority citations match tested concept"
  ]
}
];
