var pack_p2_a_part24 = [
{
  "Authorities": [
    "FASB ASC 860 (Transfers and Servicing)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Treat the transaction as a true sale: remove the $8.5 million of receivables, record a $340,000 factoring loss, and show no new liability",
    "B": "Treat the transaction as a sale for presentation purposes while disclosing the recourse obligation entirely in the footnotes",
    "C": "Treat the transaction as a secured borrowing: record the $8.16 million of proceeds as a liability to Meridian and leave the receivables on Flash's balance sheet",
    "D": "Treat the transferred receivables as hedged derivative positions and remeasure the portfolio at fair value each period"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Assuming receipt of cash equals a true sale when credit risk is retained",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "ASC 860 permits sale (derecognition) treatment only when the transferor surrenders control of the transferred assets, and Flash's retention of full recourse means it keeps the credit risk, so the sale conditions fail. The arrangement is therefore a collateralized borrowing: debit cash $8.16 million and credit a liability to Meridian for $8.16 million, while the $8.5 million of receivables remain on the balance sheet and the $340,000 difference is accounted for as financing cost over the collection period. For ratio purposes, debt-to-equity and reported current liabilities are effectively unchanged, so the leverage metrics Marcus Webb gives lenders are not improved by the transfer. Business interpretation: analysts add recourse arrangements like this back when screening for off-balance-sheet financing, so treating the cash receipt as a sale would overstate Flash's apparent de-leveraging.",
  "ExplanationWrongA": "Choice A applies true-sale accounting, removing $8.5 million of receivables and booking a $340,000 loss, but Flash retained full recourse and therefore the credit risk, so ASC 860's surrender-of-control condition fails and derecognition is unavailable. The error assumes that receiving cash converts a transfer into a sale; because risk was retained, the correct characterization is a secured borrowing with both sides staying on the books.",
  "ExplanationWrongB": "Choice B records a sale and pushes the recourse exposure to footnote disclosure, but ASC 860 does not permit disclosure to substitute for recognition when sale accounting fails; the entire arrangement remains on the balance sheet. The underlying mistake is believing presentation can be engineered around recognition rules; the controlling question is whether control of the receivables passed, not how the commitment is described.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D imports hedge-accounting mechanics, which have no application here because no hedged item or hedging instrument exists in the fact pattern; the transfer is a financing with recourse. The confusion blends ASC 815 fair-value remeasurement with ASC 860 transfer analysis, whereas the correct treatment leaves carrying amounts untouched until the receivables are collected or the borrowing repaid.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-206",
  "Section": "A",
  "Stem": "Flash Industries, a diversified manufacturer, sold $8.5 million of trade receivables to Meridian Capital Factors for cash proceeds of $8.16 million, with Flash retaining full recourse for customer nonpayment; Meridian may return uncollectible accounts to Flash. Treasurer Marcus Webb tells CFO Elena Vasquez that lenders will recompute Flash's debt-to-equity ratio at year end using the reported statements. How should this transaction affect the leverage ratios Flash reports?",
  "Topic": "A.206 factoring-with-recourse-derecognition",
  "UniqueConceptKey": "A-206-recourse-factoring-derecognition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Analyze of derecognition conditions under retained recourse requires multi-step control-risk reasoning (DS 4)",
    "Conceptual item; embedded arithmetic verified: 8.50M - 8.16M = 0.34M fee",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (degree of financial leverage)",
    "IRC Sec. 163 (corporate interest deductibility context)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "1.64",
    "B": "1.51",
    "C": "1.29",
    "D": "0.61"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Subtracting preferred dividends without the (1 - t) gross-up",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "DFL = EBIT / [EBIT - Interest - Preferred dividends / (1 - t)]. Preferred dividends are paid from after-tax income while EBIT is pre-tax, so they must be grossed up to a pre-tax equivalent: $1.05M / 0.70 = $1.50M. The denominator becomes $9.0M - $2.0M - $1.5M = $5.5M, giving DFL = $9.0M / $5.5M = 1.64. Elena can tell the audit committee that each 1 percent change in EBIT should move earnings per share by about 1.64 percent, a moderate amplification from fixed financing charges. Business interpretation: the gross-up matters because comparing an after-tax dividend stream directly against pre-tax operating income would understate Flash's fixed financial burden and understate the leverage embedded in its capital structure.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B, 1.51, comes from dividing $9.0M by ($9.0M - $2.0M - $1.05M) = $5.95M, subtracting the preferred dividend without converting it to its pre-tax equivalent. Because preferred dividends come out of after-tax income while the numerator is pre-tax, the unadjusted figure mixes tax bases; restoring the dividend to $1.05M / 0.70 = $1.50M yields the correct denominator of $5.5M.",
  "ExplanationWrongC": "Choice C, 1.29, ignores the preferred issue entirely and computes $9.0M / ($9.0M - $2.0M) = 1.29. That treats preferred dividends as discretionary rather than a fixed charge akin to interest, understating leverage; the correct computation must absorb the $1.50M grossed-up preferred burden alongside the $2.0M of interest.",
  "ExplanationWrongD": "Choice D, 0.61, inverts the formula and computes $5.5M / $9.0M. DFL relates a percentage change in EPS to a percentage change in EBIT, so EBIT belongs in the numerator; an inverted figure below 1.0 would imply financing dampens earnings swings, contradicting the fixed-charge mechanics that magnify them.",
  "FormulaReference": "FA-20",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-207",
  "Section": "A",
  "Stem": "At fiscal year-end, CFO Elena Vasquez prepares Flash Industries' leverage briefing for the audit committee. Next year's budget shows expected operating income (EBIT) of $9.0 million, interest expense of $2.0 million on term debt, and cumulative preferred dividends of $1.05 million; the marginal tax rate is 30 percent. What is Flash's degree of financial leverage (DFL)?",
  "Topic": "A.207 dfl-preferred-dividend-gross-up",
  "UniqueConceptKey": "A-207-dfl-preferred-gross-up",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: multi-component fixed-charge computation with tax gross-up (DS 3)",
    "DFL recomputed twice: 1.05/0.70 = 1.50; 9.00 - 2.00 - 1.50 = 5.50; 9.00/5.50 = 1.6364 -> 1.64; distractors 9/5.95 = 1.51, 9/7 = 1.29, 5.5/9 = 0.61 verified",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB ASC 460 (Guarantees)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Disclose the guarantee in the footnotes only, recognizing a liability if and when Halstead's default becomes probable",
    "B": "Record nothing at inception because Flash has neither paid nor received consideration for issuing the guarantee yet",
    "C": "Expense the full $6.0 million covered amount immediately as a loss contingency",
    "D": "Recognize a liability equal to the fair value of the obligation to stand ready, with an offsetting premium recorded and amortized over the guarantee term"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Deferring recognition until default becomes probable (legacy practice)",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "ASC 460 requires a guarantor to recognize, on the day the guarantee is issued, a liability measured at the fair value of the stand-ready obligation rather than waiting for a probable default. In practice the initial amount often approximates the market-based fee Flash would charge an unrelated party to issue the same guarantee; the offsetting entry is a premium carried as a deferred credit and amortized into income over the coverage period, with later measurement following contingency guidance. Priya's point for the analyst is that signing the commitment itself creates a measurable balance-sheet obligation, which is why rating agencies and credit analysts add guarantee exposures to Flash's effective leverage when assessing support commitments to related suppliers.",
  "ExplanationWrongA": "Choice A applies the pre-ASC 460 habit of footnote-only treatment until default becomes probable; the standard moved initial recognition forward to inception at fair value, reserving probability thresholds for subsequent measurement. Waiting for a probable default omits a liability that exists from the day the commitment is signed.",
  "ExplanationWrongB": "Choice B assumes no entry follows from an unbilled, unpaid promise, but the guarantor's obligation is precisely what ASC 460 brings onto the books; consideration normally exists explicitly or implicitly as a guarantee premium, and recording nothing leaves the stand-ready duty unrecognized at inception.",
  "ExplanationWrongC": "Choice C expenses the maximum covered amount, $6.0 million, confusing the guarantee's face limit with the fair value of the obligation. The initial liability reflects what the promise to stand ready is worth, generally far below the covered amount, and it is matched by a deferred premium rather than charged straight to loss.",
  "ExplanationWrongD": "",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-208",
  "Section": "A",
  "Stem": "Flash guarantees a $6.0 million working-capital line for Halstead Components, its sole source of a proprietary bearing assembly. At signing, controller Priya Chen walks a newly hired staff analyst through the journal entries Flash must make. Under FASB ASC 460, how must Flash account for the guarantee at inception?",
  "Topic": "A.208 guarantee-inception-recognition",
  "UniqueConceptKey": "A-208-guarantee-fair-value-recognition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: single-standard comprehension of recognition timing (Moderate-Easy, DS 2)",
    "Conceptual item; no recomputation required",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Quality-of-earnings doctrine (CFO-to-net-income ratio)",
    "FASB ASC 230 (Statement of Cash Flows)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Proceed at $95 million because a 10x multiple of reported earnings already embeds conservatism appropriate for a manufacturing target",
    "B": "Renegotiate toward a price supported by recurring, cash-backed earnings, since weak cash conversion, receivables divergence, and the reserve release indicate reported income overstates sustainable earning power",
    "C": "Reject the transaction categorically because any target whose cash flow trails net income is unsuitable for acquisition",
    "D": "Proceed at $95 million relying on customary representations and warranties alone, because earnings-quality screens are unreliable for industrial targets"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Paying the headline multiple without normalizing nonrecurring accruals",
  "CorrectChoice": "B",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Earnings-quality doctrine asks how faithfully reported income represents sustainable, cash-generating performance before it is capitalized into price. Kestrel's five-year quality-of-income ratio of CFO/net income at 0.55 means only about $0.55 of each reported dollar was backed by operating cash; receivables growing 35 percent against 8 percent sales growth suggests revenue may be pulled forward or recognized aggressively; and the $1.8 million warranty-reserve release is nonrecurring, so core income approximates $9.5M - $1.8M = $7.7M and the effective multiple is $95M / $7.7M = roughly 12.3x rather than the advertised 10x. Against convergent evidence of low earnings quality, anchoring the offer to recurring, cash-supported earnings through renegotiation preserves a strategically sound deal while refusing to pay for accrual-inflated income; proceeding at the ask overpays for earnings that may never convert to cash, and categorical rejection discards a negotiable opportunity without proportionate cause.",
  "ExplanationWrongA": "Choice A trusts the headline multiple, but a multiple inherits every weakness in the earnings beneath it; with 45 percent of reported dollars lacking cash backing and a reserve release inflating the base, the effective multiple on durable earnings approaches 12.3x, so the asking price embeds optimism rather than conservatism.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C converts one red flag into an absolute veto; weak cash conversion warrants scrutiny and repricing, not automatic rejection, because causes range from aggressive recognition to temporary working-capital investment. The evidence supports the proportional response of renegotiation, which addresses the findings while keeping optionality alive.",
  "ExplanationWrongD": "Choice D dismisses earnings-quality analysis as unreliable, yet persistent CFO-to-income divergence and receivables outgrowing sales are among the most documented precursors of restatement and earnings disappointment; relying solely on representations leaves Elena paying today for income that may never arrive as cash.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-209",
  "Section": "A",
  "Stem": "Flash is considering acquiring Kestrel Tooling for $95 million, a 10x multiple of Kestrel's reported net income of $9.5 million. Before the board vote, CFO Elena Vasquez reviews five years of Kestrel data: operating cash flow averaged only 55 percent of net income; receivables grew 35 percent last year against 8 percent sales growth; and current-year income includes a one-time release of warranty reserves worth $1.8 million. Elena must recommend whether to proceed at $95 million or renegotiate the price. Which recommendation is best supported by the evidence?",
  "Topic": "A.209 earnings-quality-acquisition-pricing",
  "UniqueConceptKey": "A-209-earnings-quality-renegotiation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: evaluation weighing competing acquisition responses against convergent red-flag evidence (Very Difficult, DS 5); named decision-maker with competing defensible alternatives",
    "Embedded arithmetic verified: 9.5 - 1.8 = 7.7; 95 / 7.7 = ~12.34",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB ASC 830 (Foreign Currency Matters)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The euro, because the subsidiary's sales prices, costs, and operating cash flows are overwhelmingly denominated in and settled with the local currency",
    "B": "The U.S. dollar, because the reporting currency of the consolidated group governs every subsidiary's functional currency",
    "C": "The U.S. dollar, because the parent's dollar-denominated financing is the decisive indicator whenever intercompany funding exists",
    "D": "Neither currency can be selected until the subsidiary's individual statements are restated to a common measurement basis"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Letting parent-loan currency outweigh local cash-flow indicators",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "ASC 830 weighs indicators across cash-flow, sales-price, expense, financing, and intercompany dimensions. Dresden Precision Tools' economics point squarely to the euro: selling prices respond to eurozone competition, materials and labor are locally incurred, and collections arrive in euros, while the dollar loan and limited intercompany activity are secondary financing-side signals that do not dominate. Concluding the euro means the unit is a foreign operation translated under the current-rate method, with translation adjustments accumulated in other comprehensive income instead of flowing through net income. Marcus's determination matters operationally because functional currency dictates which exchange rate translates each statement line and where currency effects land, directly shaping the volatility Flash reports to investors.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B elevates group reporting convenience over economic substance; ASC 830 assigns functional currency from the subsidiary's own cash flows, prices, and costs, and designating dollars for a euro-based operation would misstate its economics simply to match the parent's reporting orientation.",
  "ExplanationWrongC": "Choice C lets a single financing indicator override the cash-flow, pricing, and expense indicators that clearly dominate; a parent loan denominated in dollars is a relevant signal, but the standard directs a weighing of all factors, and here the operational evidence uniformly favors the euro.",
  "ExplanationWrongD": "Choice D invents a restatement prerequisite; functional currency is determined from the indicators themselves, and the designation then drives translation mechanics rather than depending on any prior common-basis restatement of the local accounts.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-210",
  "Section": "A",
  "Stem": "Flash's newly acquired Dresden Precision Tools subsidiary manufactures and sells almost exclusively within the eurozone: sales prices are set and billed in euros, materials and labor costs are incurred in euros, and cash collections arrive in euros. Parent-level financing included a $12 million dollar-denominated intercompany loan, and routine transactions with the U.S. parent are limited. Under FASB ASC 830's functional-currency indicators, what functional currency should treasurer Marcus Webb conclude applies to the subsidiary?",
  "Topic": "A.210 functional-currency-indicator-analysis",
  "UniqueConceptKey": "A-210-euro-functional-currency-indicators",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: application of a multi-factor standard to a fact pattern (Moderate, DS 3)",
    "Conceptual item; no recomputation required",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Managerial accounting theory (cost behavior and operating leverage)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The percentage change in earnings per share produced by a 1 percent change in earnings before interest and taxes",
    "B": "The ratio of total fixed costs to total variable costs at the current sales level",
    "C": "The percentage change in operating income that accompanies a 1 percent change in sales at a given sales level",
    "D": "Operating income divided by interest expense, measuring the cushion available to service debt"
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing DOL with DFL or coverage-ratio definitions",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Degree of operating leverage is defined as the percentage change in operating income divided by the percentage change in sales, equivalently the operating-income response to a 1 percent sales change at a specified volume; mechanically it equals contribution margin divided by operating income. Priya stresses the qualifier 'at a given sales level' because DOL is a point elasticity that grows toward its maximum as volume approaches breakeven and declines as volume rises above it. In Flash's planning decks the figure signals how sharply divisional operating income would swing if volumes deviate from plan, isolating cost-structure risk from the financing risk captured separately by the degree of financial leverage.",
  "ExplanationWrongA": "Choice A defines degree of financial leverage, the EPS response to an EBIT change, capturing financing amplification rather than the cost-structure amplification DOL isolates; swapping the two muddles which management lever, plant capacity and fixed costs versus capital structure, is under discussion.",
  "ExplanationWrongB": "Choice B offers a raw cost-mix ratio, which influences DOL but is not itself the elasticity measure; two divisions with identical fixed-to-variable mixes operating at different volumes report different DOL values, so the mix ratio cannot substitute for the percentage-response definition.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D states times interest earned, a solvency-coverage metric containing no sales sensitivity at all; it answers a creditor-protection question rather than the operating-risk elasticity Priya asked about, and citing it reveals category confusion between leverage measures and coverage ratios.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-211",
  "Section": "A",
  "Stem": "During onboarding, Flash controller Priya Chen quizzes a new FP&A analyst on the leverage vocabulary used throughout Flash's planning decks. She asks for the precise definition of the degree of operating leverage (DOL). Which response is correct?",
  "Topic": "A.211 dol-definition-recall",
  "UniqueConceptKey": "A-211-degree-operating-leverage-definition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: single-definition recall with familiar distractor boundaries (Easy, DS 1)",
    "Conceptual item; no recomputation required",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "IAS 29 (Financial Reporting in Hyperinflationary Economies)",
    "Legacy constant-dollar doctrine (SFAS 33 lineage)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The affiliate's current ratio is materially overstated because its payables are recorded at stale exchange values",
    "B": "The affiliate's return on assets and fixed-asset turnover are overstated because revenues reflect current prices while the asset base is carried at outdated, understated historical costs",
    "C": "The affiliate's gross margin is understated because cost of goods sold absorbs current replacement costs",
    "D": "The affiliate's debt-to-equity ratio is overstated because liabilities are indexed upward while equity remains at historical amounts"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Comparing inflationary affiliates to home-country divisions without restatement",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Inflation splits historical-cost statements onto mismatched measurement bases. Revenues price at current levels while COGS draws older, cheaper inventory layers, flattering gross margin, and the denominator effect compounds the distortion: plant carried at roughly 20 percent of replacement cost shrinks total assets, so ROA and fixed-asset turnover inflate mechanically even with zero operational improvement. Priya's cross-division review therefore shows the Buenos Aires affiliate beating U.S. divisions on efficiency and returns largely as an accounting artifact, and any conclusion feeding capital allocation should require inflation-adjusted restatement or an explicit comparability caveat before the ratios are treated as performance.",
  "ExplanationWrongA": "Choice A ties the distortion to payables at stale exchange values, but monetary items such as payables carry nominal amounts whose measurement is not the source of the classic inflation bias; the misstatement sits in understated non-monetary assets, so the current-ratio claim misidentifies both cause and effect.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C reverses the direction of the distortion: older, cheaper inventory layers mean COGS understates replacement cost, so gross margin is flattered rather than compressed; the conclusion mistakes the direction in which the historical-cost lag operates under rising prices.",
  "ExplanationWrongD": "Choice D asserts liabilities are indexed upward under historical-cost reporting; absent formal restatement they remain at nominal amounts, and equity is likewise not indexed, so there is no mechanism producing the claimed overstatement of leverage.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-212",
  "Section": "A",
  "Stem": "Flash's Buenos Aires assembly affiliate operates amid 45 percent annual inflation yet reports on a historical-cost basis. Its principal plant was purchased eight years ago and is carried at heavily depreciated original cost, roughly 20 percent of current replacement cost, while inventory layers date from earlier, cheaper periods. Controller Priya Chen is preparing the annual comparison of the affiliate's ratios against Flash's U.S. divisions. Which analytical conclusion is best supported?",
  "Topic": "A.212 inflation-distorted-ratio-analysis",
  "UniqueConceptKey": "A-212-historical-cost-ratio-overstatement",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: multi-statement decomposition of inflation-induced ratio bias (Difficult, DS 4)",
    "Conceptual item; no recomputation required",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Managerial accounting theory (operating leverage elasticity)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "1.20",
    "B": "0.40",
    "C": "0.31",
    "D": "2.50"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Dividing dollar changes instead of percentage changes",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Measured from observed results, DOL = percentage change in operating income / percentage change in sales = 20.0% / 8.0% = 2.50. Rosa can tell division leadership that if next quarter's sales move 1 percent from the current base, operating income should move about 2.5 percent in the same direction, with symmetric force on the downside. The percentage-on-percentage construction matches the elasticity definition and avoids mixing dollar deltas with percentage bases; over a linear cost-behavior range it reproduces the contribution-margin-divided-by-operating-income formulation, which is why history-based and budget-based estimates should agree when volumes stay near plan.",
  "ExplanationWrongA": "Choice A, 1.20, divides ending operating income by beginning operating income ($7.44M / $6.2M); that growth factor confirms income rose 20 percent but contains no sales information whatsoever, so it cannot express the elasticity of income to sales that Rosa intends to measure.",
  "ExplanationWrongB": "Choice B, 0.40, inverts the inputs, dividing the 8.0 percent sales change by the 20.0 percent income change; the result describes sales movement per unit of income movement, the reverse of the leverage question, and would wrongly suggest income swings less than sales.",
  "ExplanationWrongC": "Choice C, 0.31, divides dollar changes ($1.24M / $4.0M); pairing raw dollar deltas yields a ratio with no elasticity meaning and contradicts the percentage-based definition, since the dollar changes must each be expressed relative to their own bases before division.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-19",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-213",
  "Section": "A",
  "Stem": "Last quarter Flash's appliance division grew sales from $50.0 million to $54.0 million, an 8.0 percent increase, while operating income climbed from $6.2 million to $7.44 million, a 20.0 percent increase. Budget analyst Rosa Delgado computes the division's degree of operating leverage from this observed history to frame next quarter's sensitivity briefing. What DOL figure should she report?",
  "Topic": "A.213 dol-from-observed-changes",
  "UniqueConceptKey": "A-213-dol-percent-change-method",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: direct elasticity computation with three plausible mechanical slips (Moderate-Easy, DS 2)",
    "DOL recomputed twice: 20.0%/8.0% = 2.50; distractors 7.44/6.20 = 1.20, 8/20 = 0.40, 1.24/4.00 = 0.31 verified",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB ASC 830 (Foreign Currency Matters - remeasurement)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "A $1.0 million remeasurement loss in net income, because the franc's strength reduces the dollar value of the unit's obligations",
    "B": "No remeasurement effect, because monetary items continue to be carried at their historical exchange rates between closings",
    "C": "A $1.0 million remeasurement gain in net income, reflecting the higher dollar value of the unit's net monetary asset position",
    "D": "A $1.0 million gain presented in other comprehensive income as a currency translation adjustment"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Routing remeasurement gains to OCI instead of net income",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "When the functional currency is the U.S. dollar, foreign-currency monetary items are remeasured at the current rate at each close, and the net monetary position determines the result. The Zurich unit's CHF 20.0 million of net monetary assets gains $0.05 per franc as the rate moves from $0.90 to $0.95: CHF 20.0M x $0.05 = a $1.0 million remeasurement gain, which ASC 830 routes through net income within other income (expense). Priya's reporting distinction matters to readers: had the franc been the functional currency instead, currency effects would surface as a translation adjustment in other comprehensive income, leaving the earnings line insulated from the rate move that here flows directly through it.",
  "ExplanationWrongA": "Choice A gets the direction backwards: appreciation of the currency in which the unit holds net monetary assets increases, not decreases, their dollar value; a remeasurement loss would arise from depreciation of that currency or from a net monetary liability position, neither of which fits these facts.",
  "ExplanationWrongB": "Choice B freezes monetary items at historical rates, inverting the core rule of remeasurement: monetary assets and liabilities are exactly the categories carried at the current rate, while non-monetary items retain historical rates, so the stated treatment reverses the standard's classification logic.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D parks a remeasurement gain in other comprehensive income, geography reserved for the current-rate translation method; under a U.S.-dollar functional currency the remeasurement runs through net income by design, so the proposed presentation hides the effect where analysts expect earnings impact.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-214",
  "Section": "A",
  "Stem": "Flash's Zurich distribution unit keeps its books in Swiss francs although the U.S. dollar is its functional currency, because financing and most sales contracts are dollar-denominated. The unit carries net monetary assets of CHF 20.0 million. During the quarter the franc strengthens from $0.90 to $0.95 per franc. Following ASC 830 remeasurement procedures, what amount and statement location should controller Priya Chen report?",
  "Topic": "A.214 remeasurement-net-monetary-position",
  "UniqueConceptKey": "A-214-franc-remeasurement-gain-location",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: rate-direction plus income-statement-versus-OCI classification application (Moderate, DS 3)",
    "Embedded arithmetic recomputed twice: 20.0M x (0.95 - 0.90) = 1.0M gain; direction check vs net monetary asset position confirmed",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "DuPont analysis (three-component ROE decomposition)",
    "Corporate finance theory (financial risk and leverage)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Fund Electronics Enclosures: its ROE rests on margin and turnover, whereas Industrial Pumps reaches the same ROE through a 2.25 equity multiplier implying debt-heavy financing near the covenant ceiling and greater downside amplification",
    "B": "Fund Industrial Pumps: its turnover of 2.0 demonstrates superior asset efficiency, and efficiency-driven returns carry less risk than margin-driven returns in cyclical equipment markets",
    "C": "Treat the divisions as equivalent for funding purposes because identical ROE signifies identical value creation and identical shareholder risk",
    "D": "Fund Industrial Pumps because its higher equity multiplier evidences stronger lender confidence and cheaper incremental debt for the expansion"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Reading identical ROE as identical risk across capital structures",
  "CorrectChoice": "A",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "DuPont decomposes ROE = margin x turnover x leverage, exposing how each division assembles its 18 percent. Electronics Enclosures earns it with a 10.0 percent margin on 1.2 turns at modest 1.5 leverage; Industrial Pumps manages only a 4.0 percent margin and compensates with 2.0 turns and a 2.25 equity multiplier, implying total liabilities near 55.6 percent of assets (1 - 1/2.25), uncomfortably close to the 0.60 covenant cap in Flash's revolver. Identical headline ROE therefore conceals materially different risk: Pumps' return is amplified by fixed charges and would compress faster in a downturn, and its thin covenant headroom constrains the very expansion being funded. Elena's recommendation directs the $30 million toward the structurally safer compounding engine and conditions any Pumps support on deleveraging, illustrating why attribution precedes allocation when ROEs tie.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B equates turnover with safety, but turnover ignores that Pumps' 4 percent margin provides little buffer against cost shocks and that its 2.25 multiplier, not its efficiency, completes the ROE; praising asset productivity does not neutralize fixed-charge fragility beside a live covenant limit.",
  "ExplanationWrongC": "Choice C reads identical ROE as identical risk; decomposition exists precisely because the same return can be assembled from different combinations of margin, turnover, and leverage, and the leverage component changes earnings volatility and covenant exposure even when the arithmetic product matches exactly.",
  "ExplanationWrongD": "Choice D interprets a high equity multiplier as lender endorsement; it actually measures the fraction of assets financed by creditors, and a multiplier pushing implied debt-to-assets toward the contractual ceiling signals constrained, costlier future borrowing rather than cheap expansion funding.",
  "FormulaReference": "FA-14",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-215",
  "Section": "A",
  "Stem": "Two Flash divisions report identical 18.0 percent return on equity. Industrial Pumps posts a 4.0 percent net profit margin, total asset turnover of 2.0, and an equity multiplier of 2.25; Electronics Enclosures posts a 10.0 percent margin, turnover of 1.2, and an equity multiplier of 1.5. Flash's revolving credit agreement caps debt-to-total-assets at 0.60, and CFO Elena Vasquez must recommend which division receives next year's $30 million expansion budget. Which recommendation is best supported by the DuPont decomposition?",
  "Topic": "A.215 dupont-return-quality-allocation",
  "UniqueConceptKey": "A-215-dupont-roe-driver-decomposition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: trade-off adjudication across equal-return unequal-risk structures with a live covenant constraint (Very Difficult, DS 5); named decision-maker facing competing defensible alternatives",
    "ROE recomputed twice: 0.04 x 2.0 x 2.25 = 0.180; 0.10 x 1.2 x 1.5 = 0.180; Pumps implied D/A = 1 - 1/2.25 = 0.556",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
}
];
