var pack_p2_a_part11 = [
{
  "Authorities": [
    "ASC 230-10",
    "ASC 606"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Earnings that exceed analyst consensus estimates by the largest margin.",
    "B": "Earnings that are derived primarily from recurring operating activities and closely correlate with operating cash flows.",
    "C": "Earnings that show consistent growth every quarter without any decline.",
    "D": "Earnings that are maximized through aggressive revenue recognition policies."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Equating earnings growth or consistency with earnings quality — quality relates to sustainability and cash backing, not growth rate or smoothness.",
  "CorrectChoice": "B",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "High-quality earnings are sustainable, derived from core recurring operating activities, and supported by operating cash flows. Under ASC 230-10, when net income closely tracks operating cash flow, earnings quality is considered high because the reported profits are backed by actual cash generation. Conversely, when net income grows while operating cash flow stagnates or declines, earnings quality may be low — the profits may reflect aggressive accrual estimates, one-time gains, or revenue recognition timing differences rather than sustainable economic performance.",
  "ExplanationWrongA": "Option A confuses earnings quality with earnings surprise. Beating analyst estimates says nothing about whether the earnings are sustainable, cash-backed, or derived from core operations. A company can beat estimates through one-time gains or aggressive accounting while having low-quality earnings.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C describes earnings smoothness, not quality. Consistent growth may indicate earnings management (smoothing) rather than genuine economic performance. High-quality earnings may be volatile if the underlying business is cyclical — volatility alone does not indicate low quality.",
  "ExplanationWrongD": "Option D describes the opposite of high-quality earnings. Aggressive revenue recognition typically produces low-quality earnings because it inflates reported profits through accounting choices rather than economic substance. Under ASC 606, revenue should be recognized only when performance obligations are satisfied.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-069",
  "Section": "A",
  "Stem": "Which of the following best describes high-quality earnings?",
  "Topic": "A.069 Earnings Quality — definition and indicators",
  "UniqueConceptKey": "A-069-earnings-quality-definition-and-indicators",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level definition question",
    "Independent answer derived: B correctly defines high-quality earnings"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "ROE multiplied by the dividend payout ratio.",
    "B": "ROE multiplied by (1 − dividend payout ratio).",
    "C": "ROA multiplied by the retention ratio.",
    "D": "Net profit margin multiplied by asset turnover."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Using the dividend payout ratio instead of the retention ratio in the sustainable growth rate formula.",
  "CorrectChoice": "B",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The sustainable growth rate (SGR) equals ROE × (1 − Dividend Payout Ratio), or equivalently ROE × Retention Ratio. It represents the maximum rate at which a company can grow its sales and assets without issuing new equity or increasing its debt-to-equity ratio. The retention ratio (1 − payout ratio) captures the portion of earnings reinvested in the business. A company with ROE of 15% that retains 60% of earnings can sustainably grow at 9% (15% × 0.60) while maintaining its current capital structure. This is a critical concept for financial planning and valuation.",
  "ExplanationWrongA": "Option A multiplies ROE by the dividend payout ratio, which would give the dividend yield contribution rather than the growth rate. The sustainable growth rate uses the retention ratio (1 − payout), not the payout ratio itself.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C uses ROA instead of ROE. The sustainable growth rate is equity-based because it measures how fast equity can grow through retained earnings. ROA measures return on all assets and does not account for leverage effects on equity growth.",
  "ExplanationWrongD": "Option D describes the DuPont components of ROA (net profit margin × asset turnover), not the sustainable growth rate. While these feed into ROE through the DuPont identity, the sustainable growth rate formula explicitly includes the retention ratio.",
  "FormulaReference": "Sustainable Growth Rate = ROE × (1 − Dividend Payout Ratio)",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-070",
  "Section": "A",
  "Stem": "CEO Elena Vasquez of Pacifica Apparel is planning the company's long-term expansion without issuing new equity. Her CFO reminds her that the sustainable growth rate is correctly expressed as:",
  "Topic": "A.070 Sustainable Growth Rate — formula and meaning",
  "UniqueConceptKey": "A-070-sustainable-growth-rate-formula-and-meaning",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Remember-level formula identification",
    "Independent answer derived: B correctly identifies SGR formula"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The declining current ratio confirms deteriorating liquidity; Crestline should immediately reduce its dividend and negotiate extended payment terms with suppliers.",
    "B": "The declining current ratio is a reporting artifact caused by the sales growth rate exceeding the asset growth rate; the ratios should be recalculated using inflation-adjusted values before any conclusion is reached.",
    "C": "A current ratio above 1.0 at all times indicates adequate liquidity; the declining trend is irrelevant because the company consistently maintains more current assets than current liabilities.",
    "D": "The declining current ratio is a natural consequence of rapid sales growth — working capital requirements increase with sales, and the company may be using efficient working capital management rather than experiencing liquidity stress."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Treating a declining ratio in isolation without considering the business context — growth often drives working capital expansion that naturally reduces the current ratio.",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "A declining current ratio during a period of rapid sales growth does not necessarily indicate deteriorating liquidity. Under ASC 205-10, ratio analysis requires understanding the business context. Rapidly growing companies often experience declining current ratios as they invest in receivables and inventory to support higher sales volumes. The key analytical question is whether the company is managing working capital efficiently (collecting receivables, turning inventory) or struggling to meet obligations. Additional metrics — days sales outstanding, inventory turnover, operating cash flow trends, and access to credit facilities — are needed before concluding whether the trend signals stress or reflects growth-driven working capital expansion.",
  "ExplanationWrongA": "Option A jumps to a remedial conclusion without further investigation. A declining current ratio during growth may be efficient — the company may be collecting receivables faster, turning inventory more frequently, or negotiating better supplier terms. Immediate remedial action without diagnostic analysis would be premature.",
  "ExplanationWrongB": "Option D invokes inflation adjustment as an explanation. While inflation can affect financial statement comparability, a declining current ratio during growth is more likely explained by working capital dynamics than by inflation effects, which typically affect both current assets and current liabilities.",
  "ExplanationWrongC": "Option C dismisses trend analysis entirely. While a ratio above 1.0 suggests technical solvency, a persistent declining trend may signal emerging liquidity pressure even before the ratio falls below 1.0. Trend analysis provides early warning signals that a single-point ratio cannot capture.",
  "ExplanationWrongD": "",
  "FormulaReference": "Current Ratio = Current Assets / Current Liabilities",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-071",
  "Section": "A",
  "Stem": "Crestline Industries' current ratio has declined from 2.5 to 1.8 to 1.3 over the past three years. The company's sales grew 40% over the same period. Which interpretation of this trend is most appropriate before reaching a conclusion about liquidity deterioration?",
  "Topic": "A.071 Interpretation of declining current ratio trend",
  "UniqueConceptKey": "A-071-interpretation-of-declining-current-ratio-trend",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level interpretation question",
    "Independent answer derived: B correctly interprets declining current ratio in growth context",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10",
    "ASC 330-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "The divergence is mathematically impossible — a current ratio of 2.0 must produce a quick ratio above 1.0. The financial statements likely contain an error.",
    "B": "The divergence indicates that inventory represents a very large portion of current assets. The company's apparent liquidity largely depends on selling inventory, which may be problematic if inventory is slow-moving, obsolete, or subject to significant markdown risk.",
    "C": "The quick ratio is less useful than the current ratio for most analytical purposes. A current ratio of 2.0 is sufficient evidence of strong liquidity regardless of the quick ratio value.",
    "D": "The divergence indicates that the company has excessive cash and receivables relative to inventory. Management should invest more heavily in inventory to improve sales growth."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Treating the current ratio and quick ratio as providing redundant information — they capture different dimensions of liquidity risk.",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "When the current ratio is 2.0 but the quick ratio is 0.5, inventory must constitute approximately 75% of current assets. For example: Current Assets = $200, Current Liabilities = $100. Current Ratio = 2.0. If Quick Assets = $50, then Quick Ratio = 0.5 and Inventory = $150. The divergence signals that the company's reported liquidity depends heavily on converting inventory to cash — a process that requires both selling and collecting. If the inventory is slow-moving, technologically obsolete, or perishable, the apparent liquidity cushion may be illusory. Under ASC 330-10, inventory is reported at lower of cost or NRV, but book value may exceed realizable value in a liquidity stress scenario.",
  "ExplanationWrongA": "Option A incorrectly claims the divergence is mathematically impossible. There is no required relationship between the current ratio and quick ratio values. A company with very high inventory relative to quick assets can simultaneously have a current ratio of 2.0 and a quick ratio well below 1.0.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C dismisses the quick ratio as merely less useful. The quick ratio provides information the current ratio cannot — specifically, whether the company can meet its obligations without relying on inventory liquidation. Both ratios should be analyzed together for a complete liquidity picture.",
  "ExplanationWrongD": "Option D misinterprets the divergence. A very low quick ratio relative to the current ratio indicates excessive inventory reliance, not excessive cash. The company likely needs better inventory management, not more inventory investment.",
  "FormulaReference": "Quick Ratio = (Cash + Marketable Securities + Accounts Receivable) / Current Liabilities",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-072",
  "Section": "A",
  "Stem": "A financial analyst notes that Company X's current ratio is a healthy 2.0, but its quick ratio is only 0.5. Which of the following best explains the divergence and its implications?",
  "Topic": "A.072 Quick Ratio — why inventory is excluded",
  "UniqueConceptKey": "A-072-quick-ratio-why-inventory-is-excluded",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level interpretation question",
    "Independent answer derived: B correctly explains current vs quick ratio divergence"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Underperforming — the high turnover indicates the company is overworking its assets, which will lead to equipment failure and maintenance problems.",
    "B": "Generating more revenue per dollar of assets than its peers, which may indicate superior asset efficiency or a capital-light business model.",
    "C": "Experiencing revenue inflation due to aggressive recognition policies — asset turnover cannot meaningfully exceed the industry average.",
    "D": "Underinvested in assets and will need to make significant capital expenditures to sustain operations."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Assuming that any deviation from industry averages is automatically negative — high asset turnover can reflect genuine competitive advantage.",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Total asset turnover measures revenue generated per dollar of total assets. A ratio of 3.2 means the company generates $3.20 in revenue for every $1.00 of assets, versus the industry average of $1.50. This indicates the company is more capital-efficient — it may employ a capital-light business model (e.g., outsourcing production, leasing assets, maintaining low inventory) or simply manage its asset base more productively. However, the analyst should investigate whether the high turnover reflects genuine efficiency or asset underinvestment that could constrain future growth. The ratio must be interpreted alongside profitability metrics — high turnover with low margins may indicate a different competitive strategy than low turnover with high margins.",
  "ExplanationWrongA": "Option A incorrectly associates high asset turnover with overwork and equipment risk. In many industries, high asset turnover is desirable — it means the company is generating more sales from its asset base. Whether maintenance is adequate is a separate operational question.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C claims asset turnover cannot exceed industry averages. Asset turnover can vary significantly within an industry based on business model, asset age (older depreciated assets produce higher turnover), outsourcing decisions, and operational efficiency.",
  "ExplanationWrongD": "Option D jumps to a conclusion about underinvestment. While very high turnover could indicate underinvestment, this is not the most likely interpretation without additional evidence. Many successful companies deliberately operate with high asset turnover as a strategic choice.",
  "FormulaReference": "Total Asset Turnover = Net Sales / Average Total Assets",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-073",
  "Section": "A",
  "Stem": "A company with a total asset turnover of 3.2 compared to an industry average of 1.5 is most likely:",
  "Topic": "A.073 Total Asset Turnover — interpretation of high vs low values",
  "UniqueConceptKey": "A-073-total-asset-turnover-interpretation-of-high-vs-low-values",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level interpretation question",
    "Independent answer derived: B correctly interprets high asset turnover"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "When the company has no debt in its capital structure.",
    "B": "When the company's return on assets exceeds its after-tax cost of debt.",
    "C": "When the company's net profit margin exceeds its asset turnover.",
    "D": "When the company issues new equity to retire existing debt."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Assuming ROE always exceeds ROA — when the after-tax cost of debt exceeds ROA, financial leverage is unfavorable and ROE is less than ROA.",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "ROE will exceed ROA when the return earned on borrowed funds (ROA) exceeds the after-tax cost of borrowing. Through financial leverage, the company earns ROA on both equity-financed and debt-financed assets but pays only the after-tax interest cost on the debt portion. The excess return (ROA − after-tax cost of debt) accrues to equity holders, magnifying their return. For example, if ROA = 12%, after-tax cost of debt = 6%, and the company is 50% debt-financed, the 6% spread on each dollar of debt-financed assets boosts equity returns above the 12% ROA. This is the fundamental mechanism of favorable financial leverage.",
  "ExplanationWrongA": "Option A is incorrect. When a company has no debt, ROE equals ROA (assuming no preferred stock). Financial leverage creates the wedge between ROE and ROA — without debt, the two measures produce identical results because all assets are equity-financed.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C is incorrect. Net profit margin and asset turnover are components of ROA through the DuPont identity, but their relationship to each other does not determine whether ROE exceeds ROA. The ROE-ROA spread is determined by the cost of debt relative to ROA.",
  "ExplanationWrongD": "Option D is incorrect. Issuing equity to retire debt reduces financial leverage, which narrows or eliminates the ROE-ROA spread. This action moves ROE closer to ROA, not further above it.",
  "FormulaReference": "ROE = ROA + (ROA − After-tax Cost of Debt) × (Debt / Equity)",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-074",
  "Section": "A",
  "Stem": "Under what condition will a company's return on equity (ROE) exceed its return on assets (ROA)?",
  "Topic": "A.074 ROE vs ROA — the effect of financial leverage",
  "UniqueConceptKey": "A-074-roe-vs-roa-the-effect-of-financial-leverage",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level conceptual question",
    "Independent answer derived: B correctly identifies when ROE exceeds ROA"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Revenue growth is accelerating, indicating strong and improving market demand for the company's products.",
    "B": "Revenue growth is decelerating because the most recent growth rate of 11% is below the compound annual growth rate.",
    "C": "Revenue has grown in each period, but trend analysis alone cannot determine whether the growth pattern is accelerating, decelerating, or stable without considering the base effect and external benchmarks.",
    "D": "Revenue growth is stable at approximately 8-9% because the four-year average growth rate is 8.75% and individual year variations are immaterial."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Drawing strong conclusions from short time-series data — four data points are insufficient to establish acceleration or deceleration trends without statistical testing.",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Trend analysis using year-over-year growth rates requires careful interpretation. The raw growth rates (8%, 9%, 7%, 11%) show year-to-year variation but do not clearly establish acceleration or deceleration. The base effect means that as revenue grows larger in absolute terms, the same percentage growth represents more absolute dollars — 11% growth on a larger base may represent substantially more revenue than 8% growth on a smaller base. Additionally, without industry benchmarks or economic context, the analyst cannot determine whether these growth rates represent strong or weak performance. Trend analysis is a starting point for investigation, not a conclusion.",
  "ExplanationWrongA": "Option A sees acceleration where the data is ambiguous. While 11% is the highest single-year rate, 7% immediately preceded it — a one-year uptick does not establish a trend. The analyst needs more data points and external context.",
  "ExplanationWrongB": "Option B incorrectly claims the 11% rate is below the CAGR. The compound annual growth rate from the beginning to the end of the four-year period can be calculated, but 11% being above or below the CAGR depends on the starting and ending values, not the simple average of growth rates.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D treats the average as representing stability while ignoring that variation from 7% to 11% represents a range of 4 percentage points on a base of roughly 8-9%, which is substantial relative variation. The analyst should investigate what drove the 7% year and the 11% year.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-075",
  "Section": "A",
  "Stem": "A company's revenue has grown 8%, 9%, 7%, and 11% over the past four years. Based solely on trend analysis, which statement is most accurate?",
  "Topic": "A.075 Trend Analysis — purpose and limitations",
  "UniqueConceptKey": "A-075-trend-analysis-purpose-and-limitations",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level interpretation question",
    "Independent answer derived: C correctly identifies limitations of trend analysis"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Comparing a company's financial performance against its own historical results across multiple periods.",
    "B": "Comparing companies of significantly different sizes within the same industry.",
    "C": "Projecting future financial performance using regression analysis.",
    "D": "Assessing whether a company has sufficient cash to meet its near-term obligations."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Confusing vertical analysis (cross-sectional comparison) with horizontal analysis (time-series comparison). Vertical = same period, different companies; Horizontal = same company, different periods.",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Vertical analysis expresses each financial statement line item as a percentage of a base (typically total assets for the balance sheet, net sales for the income statement). This standardization is most powerful for comparing companies of different sizes, because it removes the scale effect. For example, a company with $50 million in sales and another with $5 billion in sales cannot be meaningfully compared in absolute dollars, but common-size statements reveal whether the smaller company spends a similar percentage of revenue on R&D, carries a similar proportion of debt, or generates a comparable gross margin. Industry benchmarking relies heavily on vertical analysis for this reason.",
  "ExplanationWrongA": "Option A describes horizontal (trend) analysis, which compares the same company across time periods. While vertical analysis can be used over time, its primary strength is cross-sectional comparison across companies of different sizes.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C describes forecasting or predictive analytics, which may incorporate common-size data but is not the primary purpose of vertical analysis. Vertical analysis is descriptive, showing composition; forecasting is predictive.",
  "ExplanationWrongD": "Option D describes liquidity analysis using ratios such as the current ratio and quick ratio. While vertical analysis of the balance sheet can inform liquidity assessment, it is not the primary tool for evaluating near-term cash sufficiency.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-076",
  "Section": "A",
  "Stem": "An equity analyst at Bridgeway Capital is comparing three retailers of dramatically different sizes — a $2B national chain, a $450M regional competitor, and a $30M local operator. Vertical (common-size) analysis is most useful for:",
  "Topic": "A.076 Vertical Analysis — when most useful",
  "UniqueConceptKey": "A-076-vertical-analysis-when-most-useful",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level interpretation question",
    "Independent answer derived: B correctly identifies vertical analysis strength"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "It has more debt in its capital structure, increasing the probability of default.",
    "B": "A given percentage decline in sales will produce a larger percentage decline in operating income.",
    "C": "Its variable costs are too high relative to fixed costs, making it difficult to cut expenses during downturns.",
    "D": "Its operating cash flows are more volatile than its accrual earnings."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Confusing operating leverage (business risk from cost structure) with financial leverage (financial risk from debt financing).",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "A high DOL means that fixed operating costs constitute a large portion of the company's total cost structure. Because fixed costs do not decline when sales fall, a given percentage decrease in sales produces a magnified percentage decrease in operating income. For example, with a DOL of 4.0, a 10% sales decline results in a 40% decline in EBIT. This magnification works in both directions — high DOL also amplifies the benefit of sales increases. Companies with high fixed costs (airlines, manufacturers with heavy depreciation, software companies with large R&D) exhibit higher operating leverage and greater earnings variability over the business cycle.",
  "ExplanationWrongA": "Option A confuses operating leverage with financial leverage. High debt increases financial risk (measured by DFL), not operating risk (measured by DOL). A company can have high DOL with zero debt if its cost structure is predominantly fixed.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C reverses the cost structure. High DOL implies high fixed costs and low variable costs, not the reverse. Companies with high variable costs (low fixed costs) have low DOL because costs adjust proportionally with sales.",
  "ExplanationWrongD": "Option D describes cash flow versus accrual divergence, which relates to earnings quality, not operating leverage. High DOL increases earnings variability irrespective of whether earnings are measured on a cash or accrual basis.",
  "FormulaReference": "Degree of Operating Leverage = Contribution Margin / Operating Income",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-077",
  "Section": "A",
  "Stem": "A company with a high degree of operating leverage (DOL) faces greater risk because:",
  "Topic": "A.077 High DOL — business risk implications",
  "UniqueConceptKey": "A-077-high-dol-business-risk-implications",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level conceptual question",
    "Independent answer derived: B correctly explains risk from high DOL"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "EPS will increase by 4.8% (12% divided by 2.5).",
    "B": "EPS will increase by 12%, the same as the EBIT increase, because EPS is calculated after interest.",
    "C": "EPS will increase by 30% (12% multiplied by 2.5).",
    "D": "EPS will increase by 2.5%, reflecting the fixed charge coverage."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Dividing by DFL instead of multiplying — DFL magnifies EBIT changes into EPS changes, so the multiplier is applied, not divided.",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "The degree of financial leverage measures the percentage change in EPS for a given percentage change in EBIT: DFL = %ΔEPS / %ΔEBIT. With DFL = 2.5 and EBIT increasing by 12%, EPS will increase by 12% × 2.5 = 30%. The magnification occurs because interest expense is fixed — when EBIT rises, interest remains constant, so the entire EBIT increase flows to pre-tax income, producing a proportionally larger increase in net income and EPS. DFL captures this amplification effect.",
  "ExplanationWrongA": "Option A divides EBIT growth by DFL instead of multiplying. The correct relationship is %ΔEPS = %ΔEBIT × DFL. Dividing by DFL would imply that financial leverage dampens EPS changes, which is the opposite of how leverage works.",
  "ExplanationWrongB": "Option B ignores financial leverage entirely. Because interest is a fixed charge, EPS changes are magnified relative to EBIT changes when DFL exceeds 1.0. EPS changes equal EBIT changes only when DFL = 1.0 (no debt or preferred stock).",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D confuses DFL (a multiplier) with an additive adjustment. DFL of 2.5 means the percentage change in EPS is 2.5 times the percentage change in EBIT, not that EPS adds 2.5 percentage points.",
  "FormulaReference": "DFL = EBIT / (EBIT − Interest Expense); %ΔEPS = %ΔEBIT × DFL",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-078",
  "Section": "A",
  "Stem": "A company has a degree of financial leverage (DFL) of 2.5. If EBIT increases by 12%, what is the expected impact on earnings per share?",
  "Topic": "A.078 DFL — relationship between EBIT and EPS volatility",
  "UniqueConceptKey": "A-078-dfl-relationship-between-ebit-and-eps-volatility",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level application question",
    "Independent answer derived: 12% × 2.5 = 30% — C is correct"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 606",
    "ASC 230-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Revenue growing at 8% annually while operating cash flow grows at 9% annually.",
    "B": "Accounts receivable growing at 25% annually while revenue grows at 10% annually.",
    "C": "Gross margin remaining stable at 42% for five consecutive years.",
    "D": "Capital expenditures consistently exceeding depreciation expense."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Focusing on revenue growth in isolation without examining the relationship between revenue, receivables, and cash collections.",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Accounts receivable growing significantly faster than revenue (25% vs. 10%) is a classic earnings quality red flag. It may indicate that the company is extending more generous credit terms to boost sales, recognizing revenue before collection is reasonably assured, or experiencing collection problems. Under ASC 606, revenue should be recognized only when collectibility is probable. When receivables outpace revenue growth, the analyst should investigate whether: (1) the company changed its credit policy, (2) customers are delaying payment (suggesting dissatisfaction or financial distress), or (3) revenue recognition is aggressive. The divergence between revenue growth and cash collection is a leading indicator of potential earnings quality issues.",
  "ExplanationWrongA": "Option A describes a healthy pattern — operating cash flow growing slightly faster than revenue suggests that earnings are cash-backed. This is a positive earnings quality indicator, not a concern.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C describes stable gross margins, which is generally a positive indicator. While artificially stable margins could signal earnings management, stable margins are more commonly associated with consistent pricing power and cost control.",
  "ExplanationWrongD": "Option D describes capital expenditures exceeding depreciation, which suggests the company is investing in growth and maintaining its asset base. This is generally viewed positively, as underinvestment in capex is a more common earnings quality concern (inflating earnings by deferring necessary maintenance).",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-079",
  "Section": "A",
  "Stem": "Which of the following patterns would most concern an analyst evaluating earnings quality?",
  "Topic": "A.079 Earnings quality — red flags in financial reporting",
  "UniqueConceptKey": "A-079-earnings-quality-red-flags-in-financial-reporting",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level red-flag identification",
    "Independent answer derived: B correctly identifies A/R outpacing revenue as red flag"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The company's profit margins will automatically increase to bring growth into alignment.",
    "B": "The company's debt-to-equity ratio will increase over time as it relies on additional borrowing to finance the growth gap.",
    "C": "The company's sustainable growth rate will automatically adjust upward through improved asset turnover.",
    "D": "The company will accumulate excess cash, improving its liquidity position."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Ignoring sustainable growth constraints — companies cannot grow faster than their SGR indefinitely without altering capital structure, dividend policy, or equity base.",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "When actual growth exceeds the sustainable growth rate, the company is growing faster than retained earnings can support while maintaining a constant debt-to-equity ratio. To finance the gap, the company must either: (1) issue new equity, (2) increase its debt ratio (borrowing more relative to equity), (3) reduce the dividend payout ratio to retain more earnings, or (4) improve operational efficiency (higher margin or turnover). If the company maintains its dividend policy and does not issue equity, it must increase borrowing, which raises the debt-to-equity ratio. This increases financial leverage and financial risk. Over time, the higher interest burden may reduce ROE, further constraining the sustainable growth rate.",
  "ExplanationWrongA": "Option A assumes profit margins automatically adjust, which is incorrect. Profit margins are determined by competitive dynamics, cost structure, and pricing power — they do not automatically increase because the company is growing faster than its sustainable rate.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C assumes the sustainable growth rate auto-adjusts, which is incorrect. The sustainable growth rate is determined by ROE and the retention ratio; it does not automatically change simply because actual growth differs from it. The gap must be financed through one of the four channels.",
  "ExplanationWrongD": "Option D describes the opposite of what happens. Growth that exceeds the sustainable rate consumes cash (investment in working capital and fixed assets), it does not generate excess cash. The company will face funding pressure, not liquidity abundance.",
  "FormulaReference": "Sustainable Growth Rate = ROE × (1 − Dividend Payout Ratio)",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-080",
  "Section": "A",
  "Stem": "A company's actual sales growth consistently exceeds its sustainable growth rate. Which of the following is the most likely consequence if the company maintains its current dividend policy and does not issue new equity?",
  "Topic": "A.080 Sustainable Growth Rate — constraints and implications",
  "UniqueConceptKey": "A-080-sustainable-growth-rate-constraints-and-implications",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty appropriate for Understand-level consequence analysis",
    "Independent answer derived: B correctly identifies increased leverage as consequence"
  ],
  "question_state": "Certified"
}
];
