var pack_p2_a_part29 = [
{
  "Authorities": [
    "ASC 842 Leases (analytical capitalization perspective)",
    "Credit covenant analysis convention"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Present the reported debt-to-equity ratio of 0.75 unchanged, because lease obligations sit outside the debt caption of the balance sheet and therefore do not belong in a leverage discussion with the committee",
    "B": "Add the undiscounted $3,000,000 payment schedule to debt, producing debt-to-equity of 1.125, because contractual totals capture the full obligation regardless of payment timing",
    "C": "Reduce shareholders' equity by the $2,400,000 present value to reflect the committed fleet spending, showing debt-to-equity of 6,000,000 / 5,600,000 = 1.07",
    "D": "Capitalize the $2,400,000 present value into debt-like claims, presenting adjusted debt of $8,400,000 and adjusted debt-to-equity of 1.05, with the undiscounted schedule disclosed separately"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Omitting lease PV from debt or adding undiscounted payments",
  "CorrectChoice": "D",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Sound credit analysis treats economically debt-like financing arrangements as debt regardless of balance-sheet classification, and discounting - not undiscounted summation - measures the obligation's economic weight. Adjusted debt = 6,000,000 + 2,400,000 = $8,400,000; adjusted debt-to-equity = 8,400,000 / 8,000,000 = 1.05 versus the unadjusted 0.75, a material escalation in measured fixed-claim intensity. Business interpretation: credit manager Samuel Ortiz gives the committee a faithful view of Flash's committed obligations while preserving transparency about the $3,000,000 contractual total, letting the bank price covenant headroom realistically. The traps are ignoring the obligation behind its presentation form, overstating it with undiscounted future dollars, or distorting equity, which corrupts every return metric computed off the same denominator.",
  "ExplanationWrongA": "Choice A hides committed financing behind presentation form; the misconception equates balance-sheet captions with economic substance. Fixed lease payments compete with debt service for the same cash flows and belong in any leverage view presented to lenders.",
  "ExplanationWrongB": "Choice B discounts nothing, adding $3,000,000 of future dollars to today's debt stock; the misconception confuses contractual gross outflows with present-value obligation. Discounting at the embedded borrowing rate yields $2,400,000, the economically comparable figure.",
  "ExplanationWrongC": "Choice C nets the obligation against equity, shrinking the denominator from $8,000,000 to $5,600,000 and manufacturing 1.07; the misconception misclassifies a debt-like claim as an equity adjustment, corrupting ROE and other equity-based metrics built on the same base.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-07",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-255",
  "Section": "A",
  "Stem": "Credit manager Samuel Ortiz is renewing Flash's $10,000,000 revolving facility and must present a leverage view to the bank's credit committee. Flash reports total debt of $6,000,000 and shareholders' equity of $8,000,000, a 0.75 ratio. Off balance sheet, Flash operates its delivery fleets under long-term leases with remaining undiscounted payments totaling $3,000,000; discounted at the incremental borrowing rates embedded in the contracts, the present value of those payments is $2,400,000. The committee asks Samuel which leverage presentation best supports a defensible lending decision. Which recommendation should he make?",
  "Topic": "A.255 lease-adjusted-leverage",
  "UniqueConceptKey": "A-255-pv-lease-capitalization",
  "VerifiedChecks": [
    "Verification: 6,000,000 + 2,400,000 = 8,400,000; 8,400,000/8,000,000 = 1.05; unadjusted 6,000,000/8,000,000 = 0.75",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Difficult/Evaluate named decision-maker choosing among defensible presentations"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Substance-over-form doctrine (SEC off-balance-sheet disclosure principles)",
    "Higgins off-balance-sheet financing analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Endorse the reported debt-to-equity of 0.56 unchanged, because neither arrangement appears in the debt caption and off-balance-sheet items are governed by separate disclosure rules outside any leverage metric",
    "B": "Aggregate the $4,160,610 take-or-pay present value with the $3,500,000 guaranteed entity debt for $7,660,610 of debt-like claims, lifting adjusted debt-to-equity to approximately 0.85, and disclose the aggregation basis in the committee materials",
    "C": "Count only the $3,500,000 guarantee alongside reported debt for $8,500,000 and debt-to-equity of 0.94, treating the take-or-pay contract as an ordinary purchase commitment outside any leverage lens",
    "D": "Add the undiscounted $5,400,000 of scheduled take-or-pay payments to the guarantee and reported debt for $13,900,000, presenting debt-to-equity above 1.5 as the conservative planning figure"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Excluding PV of take-or-pay or SPE debt from capacity analysis",
  "CorrectChoice": "B",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Off-balance-sheet financing analysis rests on substance over form: fixed, unavoidable commitments function as debt-like claims and belong in capacity assessment at present value, and guarantees of sponsored entities consolidate into the analysis. Take-or-pay PV = $900,000 x 4.6229 = $4,160,610; combined with the $3,500,000 guarantee, debt-like claims total $7,660,610, and adjusted debt-to-equity = 7,660,610 / 9,000,000 = 0.85 versus the reported 5,000,000 / 9,000,000 = 0.56 - an understatement of more than 50%. Business interpretation: board member Jonathan Hale's audit committee gains a truthful picture of Flash's fixed-claim burden for governance decisions, provided staff disclose exactly which commitments were aggregated and why. The traps are exclusion based on caption placement and undiscounted padding, which substitutes conservatism for measurement.",
  "ExplanationWrongA": "Choice A accepts the balance-sheet surface; the misconception is that absence from the debt caption equals absence of economic obligation. Guaranteed debt and take-or-pay commitments are fixed claims ranking ahead of equity in any stress scenario the committee should contemplate.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C draws an arbitrary boundary at the guarantee; the misconception treats take-or-pay as ordinary trade purchasing even though its fixed-payment character regardless of deliveries makes it financing in substance worth $4,160,610 in present value. Half the hidden claim disappears from the analysis.",
  "ExplanationWrongD": "Choice D abandons discounting and stacks $5,400,000 of future nominal dollars onto today's obligations; the misconception conflates contractual totals with obligation value. Undiscounted padding overstates leverage as dramatically as exclusion understates it, and neither extreme measures anything.",
  "FormulaReference": "FA-07",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-256",
  "Section": "A",
  "Stem": "Board member Jonathan Hale chairs Flash's audit committee and is probing whether reported leverage understates Flash's committed obligations. Reported long-term debt is $5,000,000 against shareholders' equity of $9,000,000. Outside the balance sheet sit two arrangements: a six-year take-or-pay supply contract obligating Flash to pay $900,000 annually regardless of deliveries received, whose present value at Flash's 8% discount rate is $4,160,610 using the stated 4.6229 six-year annuity factor; and a legally separate equipment entity sponsored by Flash whose $3,500,000 of bank debt Flash guarantees. Jonathan asks staff which debt-capacity presentation the committee should endorse. Which presentation is most defensible?",
  "Topic": "A.256 take-or-pay-debt-capacity",
  "UniqueConceptKey": "A-256-spe-commitment-aggregation",
  "VerifiedChecks": [
    "Verification: 900,000 x 4.6229 = 4,160,610; 4,160,610 + 3,500,000 = 7,660,610; 7,660,610/9,000,000 = 0.85; reported 5,000,000/9,000,000 = 0.56; undiscounted 900,000 x 6 = 5,400,000",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: VD/Evaluate multi-instrument aggregation judgment by named board decision-maker"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Cost-volume-profit framework",
    "Financial leverage theory (DOL-DFL-DCL chain)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "2.67",
    "B": "1.50",
    "C": "4.00",
    "D": "5.00"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Reporting DOL or DFL alone, or deducting interest twice",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Combined leverage chains the operating and financial layers: DCL = DOL x DFL, equivalently contribution margin divided by earnings before interest and taxes less interest. Contribution margin = 1,000,000 x 40% = $400,000. EBIT = 400,000 - 250,000 = $150,000. DOL = 400,000 / 150,000 = 2.67. DFL = 150,000 / (150,000 - 50,000) = 150,000 / 100,000 = 1.50. DCL = 2.67 x 1.50 = 4.00, confirmed directly as 400,000 / 100,000 = 4.00. Business interpretation: finance director Elena Vasquez can tell the board that a 10% swing in sales moves EPS roughly 40% in either direction, so thin-cushion quarters will amplify volatility dramatically. The traps are stopping at one layer of the chain or deducting interest twice in the denominator.",
  "ExplanationWrongA": "Choice A reports DOL alone (400,000 / 150,000 = 2.67); the misconception presents operating leverage as the combined measure and drops the financing layer entirely, understating EPS sensitivity to sales by half.",
  "ExplanationWrongB": "Choice B reports DFL alone (150,000 / 100,000 = 1.50); the misconception isolates the interest wedge from the operating chain. Combined leverage multiplies the two elasticities rather than selecting whichever layer was computed last.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D divides contribution margin by $80,000, double-counting the interest deduction beneath EBIT; the misconception produces an inflated elasticity of 5.00. Interest is deducted once from the $150,000 EBIT, leaving $100,000 in the denominator and a correct answer of 4.00.",
  "FormulaReference": "FA-19",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-257",
  "Section": "A",
  "Stem": "Finance director Elena Vasquez is stress-testing Flash's earnings sensitivity ahead of a volatile selling season. Flash projects sales of $1,000,000 with a 40% contribution margin ratio, fixed operating costs of $250,000, and interest expense of $50,000. Elena wants the degree of combined leverage to show the board how proportionally EPS responds to sales swings. What degree of combined leverage should she report?",
  "Topic": "A.257 dcl-computation",
  "UniqueConceptKey": "A-257-dol-dfl-chain",
  "VerifiedChecks": [
    "Verification: CM 400,000; EBIT 400,000 - 250,000 = 150,000; DOL 400,000/150,000 = 2.67; DFL 150,000/100,000 = 1.50; DCL 2.67 x 1.50 = 4.00 = 400,000/100,000",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Moderate/Apply chained leverage computation"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (degree of financial leverage)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The percentage change in operating income that accompanies a given percentage change in sales revenue",
    "B": "The percentage change in earnings per share that accompanies a given percentage change in operating income, computed as EBIT divided by EBIT minus interest expense",
    "C": "The ratio of total liabilities to shareholders' equity that gauges the balance-sheet weight of borrowed funds",
    "D": "The percentage change in sales required to offset a given percentage change in fixed financing costs"
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing DFL elasticity with debt-to-equity ratio",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "The degree of financial leverage measures earnings-per-share elasticity with respect to operating income: DFL = EBIT / (EBIT - interest expense). Illustrating with Flash's own figures, EBIT of $150,000 against interest of $50,000 gives DFL = 150,000 / 100,000 = 1.50, meaning each 1% movement in EBIT shifts EPS by 1.5% in the same direction. Business interpretation: FP&A director Grace Liu emphasizes to associates that DFL isolates the financing layer only - operating leverage handles the sales-to-EBIT linkage, and the two chain multiplicatively into combined leverage for planning purposes. The common trap is confusing this elasticity with the debt-to-equity ratio, a static capital-structure stock measure rather than a sensitivity coefficient.",
  "ExplanationWrongA": "Choice A defines the operating-leverage linkage (sales-driven EBIT elasticity); the misconception attaches the sales variable to the financing measure. DFL begins from EBIT, not revenue, because interest enters the income statement below operating income.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C describes the debt-to-equity ratio, a point-in-time capital-structure gauge; the misconception equates the amount of leverage with the sensitivity to leverage. DFL is an elasticity computed from income-statement flows, not a stock measure from the balance sheet.",
  "ExplanationWrongD": "Choice D invents a breakeven-style sales requirement that matches no definition in leverage theory; the misconception pattern-matches financing vocabulary onto cost-volume-profit mechanics. No standard ratio expresses sales change needed to offset financing-cost changes.",
  "FormulaReference": "FA-20",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-258",
  "Section": "A",
  "Stem": "During Flash's management development program, FP&A director Grace Liu quizzes associates on leverage terminology before opening the budgeting module. She puts a single definition question to the group: which statement correctly defines the degree of financial leverage? Which definition is correct?",
  "Topic": "A.258 dfl-definition",
  "UniqueConceptKey": "A-258-eps-elasticity-definition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: ME/Remember definitional recall with worked illustration in explanation"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Working-capital liquidity analysis convention",
    "Commercial lending credit-memo practice"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "The current ratio improved from 1.50 to 1.60 while the quick ratio collapsed from 1.13 to 0.70; the divergence shows the improvement came from an inventory build financed by added current liabilities, so headline liquidity strengthened while immediately available liquidity deteriorated",
    "B": "Both liquidity measures improved in tandem across the year, confirming that larger current assets alongside moderate liability growth leave Flash better positioned to absorb short-term cash shocks",
    "C": "The quick ratio held essentially steady near 1.13 through the fourth quarter, so the inventory movement is immaterial and the current-ratio gain stands as a reliable approval basis",
    "D": "The deterioration traces to surging receivables, which roughly doubled inside the year and drained operating cash, warranting tighter collection covenants before any increase in the facility"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Approving on current ratio while quick ratio diverges",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Decomposing liquidity requires pairing the current ratio with the acid-test to locate where composition shifted. Q1: current ratio = 1,200,000 / 800,000 = 1.50; quick ratio = (400,000 + 500,000) / 800,000 = 1.13. Q4: current ratio = 1,600,000 / 1,000,000 = 1.60; quick ratio = (180,000 + 520,000) / 1,000,000 = 0.70. The 0.43-point quick-ratio collapse beside a rising current ratio isolates the $600,000 inventory build as the driver, compounded by cash falling $220,000 while receivables moved only $20,000 - slower-converting assets absorbed the new funding. Business interpretation: senior credit analyst Naomi Brooks should condition any line increase on inventory-turn evidence, because the cited improvement masks reduced immediate-payment capacity. The trap is approving on the current ratio alone when the pair diverges.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B reads both gauges upward together; recomputation shows the quick ratio fell 39% (1.13 to 0.70). The misconception averages asset composition into the headline, missing that the pair's divergence - improvement in one, collapse in the other - is itself the finding.",
  "ExplanationWrongC": "Choice C freezes the quick ratio at its first-quarter value; applying fourth-quarter balances gives (180,000 + 520,000) / 1,000,000 = 0.70, a 0.43-point slide. The misconception carries stale subtotals forward instead of recalculating each period from raw components.",
  "ExplanationWrongD": "Choice D pins the cause on receivables, which moved just $20,000 between quarters; the misconception skips the component bridge. Inventory absorbed $600,000 of the shift - thirty times the receivables movement - making the inventory account the sole plausible driver.",
  "FormulaReference": "FA-02",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-259",
  "Section": "A",
  "Stem": "Senior credit analyst Naomi Brooks reviews Flash's year-end borrowing-base request and extracts these working-capital positions. Q1: cash $400,000, receivables $500,000, inventory $300,000, current liabilities $800,000. Q4: cash $180,000, receivables $520,000, inventory $900,000, current liabilities $1,000,000. In its request, Flash cites a stronger current ratio as evidence of improved short-term health. Naomi must determine what the ratio pair actually reveals before recommending approval. Which analysis is supported?",
  "Topic": "A.259 liquidity-decomposition",
  "UniqueConceptKey": "A-259-quick-ratio-divergence",
  "VerifiedChecks": [
    "Verification: Q1 CR 1,200,000/800,000 = 1.50; Q1 QR (400,000+500,000)/800,000 = 1.125 = 1.13; Q4 CR 1,600,000/1,000,000 = 1.60; Q4 QR (180,000+520,000)/1,000,000 = 0.70; inventory delta 900,000 - 300,000 = 600,000",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Difficult/Analyze two-ratio decomposition over quarterly data table"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Income statement presentation conventions",
    "GAAP operating income construction"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "36.00%",
    "B": "64.00%",
    "C": "18.00%",
    "D": "50.00%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Quoting gross margin or cost ratio where operating margin is asked",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Operating margin equals operating income divided by net sales, capturing core profitability before financing and taxes. Gross profit = 5,000,000 - 3,200,000 = $1,800,000. Operating income = 1,800,000 - 900,000 = $900,000. Operating margin = 900,000 / 5,000,000 = 18.00%. Business interpretation: investor relations director Maya Patel can quote 18.00% as a clean peer-comparison figure free of capital-structure noise; a limitation worth footnoting is that the ratio says nothing about how operating assets were financed, and classification choices such as moving depreciation into cost of sales shift the split between gross and operating margins without changing operating income. The traps are quoting the gross margin, the cost-of-sales percentage, or scaling operating income against the wrong base.",
  "ExplanationWrongA": "Choice A quotes the gross margin (1,800,000 / 5,000,000 = 36.00%); the misconception stops the income statement before operating expenses. SG&A of $900,000, depreciation included, belongs inside the operating measure being requested.",
  "ExplanationWrongB": "Choice B reports the cost-of-goods-sold percentage (3,200,000 / 5,000,000 = 64.00%) rather than any margin; the misconception inverts a profitability question into a cost-share statistic and labels the remainder a margin.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D scales operating income by gross profit (900,000 / 1,800,000 = 50.00%); the misconception mismatches numerator and denominator bases. Margins divide income by net sales, the full revenue base that generated the profit, not by the intermediate subtotal.",
  "FormulaReference": "FA-10",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-260",
  "Section": "A",
  "Stem": "Investor relations director Maya Patel is drafting Flash's annual-results commentary and must quote the operating margin for the just-closed fiscal year. The income statement shows net sales of $5,000,000, cost of goods sold of $3,200,000, and selling, general, and administrative expense (including depreciation) of $900,000, with no other operating items. What operating margin should Maya report?",
  "Topic": "A.260 operating-margin-computation",
  "UniqueConceptKey": "A-260-margin-waterfall-distinction",
  "VerifiedChecks": [
    "Verification: GP 5,000,000 - 3,200,000 = 1,800,000; OI 1,800,000 - 900,000 = 900,000; OM 900,000/5,000,000 = 18.00%",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Moderate/Apply margin waterfall with limitation note per A.2"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Earnings quality framework (sustainable versus transitory earnings)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The climb from 12% to 17% demonstrates durable operating improvement and merits leading the prepared remarks without qualification",
    "B": "One-time gains should be averaged into several future periods' ROE so the benefit of asset monetization is spread evenly across the reported trend line",
    "C": "Because the sale generated cash proceeds, the gain represents a permanent step-up in earning assets and the 17% level becomes the new baseline for guidance",
    "D": "The warehouse gain is nonrecurring; analysts will exclude it, and on a core basis ROE is little changed, so the script should attribute the headline to portfolio monetization rather than operating strength"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Booking one-time gains into recurring ROE trends",
  "CorrectChoice": "D",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Earnings-quality analysis separates sustainable recurring earnings from transitory items before drawing performance conclusions. A $1,400,000 pre-tax gain on selling a decade-held warehouse - disposed only because an unsolicited offer arrived - does not recur, and folding it mechanically into return on equity overstates the earning power of Flash's ongoing asset base. Excluding it leaves the underlying return close to the prior 12%, so honest framing attributes the headline jump to a discrete monetization event. Business interpretation: board member Robert Ellison protects credibility with the analyst community, who will normalize the figure themselves within minutes of the release. The traps are crediting operations for a portfolio event, artificially smoothing the windfall forward, or assuming cash proceeds instantly replicate the sold asset's returns.",
  "ExplanationWrongA": "Choice A credits operations for a portfolio transaction; the misconception reads headline ROE without normalizing transitory items - precisely the first adjustment sophisticated investors run. Leading with the unqualified figure invites an awkward analyst correction on the call.",
  "ExplanationWrongB": "Choice B averages a nonrecurring item forward across future periods; the misconception borrows later denominators to dilute a one-off instead of excluding it now. Normalization removes transitory gains from the current period; it does not amortize them into the trend.",
  "ExplanationWrongC": "Choice C equates cash proceeds with permanent earning power; the misconception assumes redeployed sale proceeds instantly reproduce a 17% return. Until reinvested, idle cash depresses rather than extends elevated returns, and no reinvestment plan of equivalent yield is evidenced.",
  "ExplanationWrongD": "",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-261",
  "Section": "A",
  "Stem": "Ahead of Flash's investor call, board member Robert Ellison reviews draft talking points touting return on equity that climbed from 12% to 17% year over year. Internal schedules show the jump was driven principally by a $1,400,000 pre-tax gain on the sale of a distribution warehouse - a property Flash had owned for ten years and did not intend to sell until an unsolicited offer arrived. Robert asks which framing of the ROE trend is sound for the call script. Which interpretation should guide the prepared remarks?",
  "Topic": "A.261 nonrecurring-gain-quality",
  "UniqueConceptKey": "A-261-sustainable-earnings-screen",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Easy/Understand conceptual earnings-quality screening"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Common-size and mix-variance decomposition convention"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "The reported blend is internally inconsistent; a two-point decline in the highest-margin line must pull the companywide margin below 21.00%, so the supplement requires correction before any analysis is attempted",
    "B": "The blended gain came from Standard fixtures, whose absolute direct-margin dollars rose enough to outweigh Premium's per-dollar erosion during the year",
    "C": "Revenue mix shifted toward Premium from 50% to 60% of sales; holding the FY2025 mix constant, the Premium rate cut alone would have dropped the blend to 20.00%, so the rate effect is about -1.00 point while the favorable mix effect contributes roughly +1.60 points, netting the observed +0.60",
    "D": "Blended margins across periods with different product mixes are not comparable statistics, so the 21.00%-to-21.60% movement carries no information and no decomposition is possible"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Judging blended margin change without separating mix from rate",
  "CorrectChoice": "C",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Mix-versus-rate decomposition separates what each driver contributed to the blended margin. FY2025 blend: (3,000,000 x 30% + 3,000,000 x 12%) / 6,000,000 = 1,260,000 / 6,000,000 = 21.00%. FY2026 blend: (3,600,000 x 28% + 2,400,000 x 12%) / 6,000,000 = (1,008,000 + 288,000) / 6,000,000 = 1,296,000 / 6,000,000 = 21.60%. Rate effect at constant FY2025 mix: 50% x 28% + 50% x 12% = 20.00%, a 1.00-point drag; migrating to the FY2026 mix lifts the blend the remaining 1.60 points to 21.60%. Business interpretation: portfolio manager Alicia Grant can show her associate that volume migrated toward the structurally richer line fast enough to overwhelm its per-dollar erosion - a mix story, not a pricing victory. The trap is judging blended ratios without decomposing composition from price.",
  "ExplanationWrongA": "Choice A declares the outcome impossible and demands correction; the misconception treats the flagship's rate decline as destiny while ignoring that its revenue share grew from 50% to 60%, multiplying the weight the weakened 28% margin carries in the blend.",
  "ExplanationWrongB": "Choice B credits the wrong line; Standard held a flat 12% margin on shrinking revenue, contributing $288,000 versus $360,000 the prior year. Its absolute margin dollars fell, ruling it out arithmetically as the source of the blended improvement.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D discards the comparison wholesale; common-size analysis exists precisely to compare blends across differing compositions. The misconception mistakes mix contamination for incomparability rather than recognizing a decomposable structure with quantifiable effects.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-262",
  "Section": "A",
  "Stem": "Portfolio manager Alicia Grant covers Flash and receives the company's product-line supplement. Premium fixtures: FY2025 revenue $3,000,000 at a 30% direct margin; FY2026 revenue $3,600,000 at a 28% direct margin. Standard fixtures: FY2025 revenue $3,000,000 at a 12% direct margin; FY2026 revenue $2,400,000 at a 12% direct margin. Companywide blended direct margin moved from 21.00% to 21.60% even though pricing pressure cut the flagship Premium line's margin by two points. Her associate insists the blend cannot rise while the highest-margin line weakens. Which decomposition resolves the puzzle?",
  "Topic": "A.262 mix-rate-decomposition",
  "UniqueConceptKey": "A-262-common-size-mix-effect",
  "VerifiedChecks": [
    "Verification: FY2025 blend (900,000 + 360,000)/6,000,000 = 21.00%; FY2026 blend (1,008,000 + 288,000)/6,000,000 = 21.60%; rate-only blend 0.5 x 28% + 0.5 x 12% = 20.00%; residual mix effect 21.60% - 20.00% = +1.60 pts; net +0.60 pts",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: VD/Analyze two-factor decomposition over product-line data table"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Higgins sustainable growth model"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "10.80%",
    "B": "7.20%",
    "C": "18.00%",
    "D": "12.11%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Applying payout instead of retention in the SGR formula",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The Higgins sustainable growth model caps sales expansion at the pace retained earnings can fund without changing profitability, payout, or leverage: SGR = ROE x retention ratio. Retention = 1 - payout = 1 - 0.40 = 0.60. SGR = 0.18 x 0.60 = 10.80%. Business interpretation: treasurer Hana Suzuki can commit Flash's strategic plan to roughly 10.8% annual internal funding capacity; pushing beyond that ceiling forces one of the model's four levers - new debt, new equity, margin improvement, or a dividend cut - since retained earnings alone cannot carry faster growth. The traps are multiplying ROE by the payout ratio instead of retention (7.20%), quoting unadjusted ROE (18.00%), or invoking the beginning-equity variant 0.108 / (1 - 0.108) = 12.11% when steady-state ROE is already specified.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B multiplies ROE by the 40% payout (0.18 x 0.40 = 7.20%); the misconception rewards distribution rather than retention. Growth is financed by earnings kept inside the firm, not by earnings paid away to shareholders.",
  "ExplanationWrongC": "Choice C presents ROE unadjusted (18.00%); the misconception assumes all earnings remain available for expansion. After the 40% dividend leaves the company, only 60% of the return compounds internally, cutting the fundable pace by nearly half.",
  "ExplanationWrongD": "Choice D applies the beginning-of-period equity formulation, 0.108 / (1 - 0.108) = 12.11%; the mismatch is using that variant when the question already specifies ROE on the steady-state base the standard SGR expression assumes. Mixing formulations inflates the ceiling by 131 basis points.",
  "FormulaReference": "FA-21",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-263",
  "Section": "A",
  "Stem": "Treasurer Hana Suzuki is setting the self-funding envelope for Flash's three-year strategic plan. Flash generates a return on equity of 18% and pays out 40% of earnings as dividends, and management intends to hold both policies constant along with current leverage. Using the sustainable growth rate relationship, what maximum annual sales growth can Flash finance internally?",
  "Topic": "A.263 sgr-computation",
  "UniqueConceptKey": "A-263-retention-multiplier",
  "VerifiedChecks": [
    "Verification: retention 1 - 0.40 = 0.60; SGR 0.18 x 0.60 = 10.80%; distractor check 0.18 x 0.40 = 7.20%; variant 0.108/(1-0.108) = 12.11%",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Difficult/Apply formula selection plus variant discrimination",
    "Slot conformance: CC=A, DS=3, Apply per P2-064 slot table"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Credit covenant analysis convention",
    "Coverage ratio construction standards"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "4.00x",
    "B": "3.54x",
    "C": "3.97x",
    "D": "4.48x"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Ignoring incremental interest or switching to EBITDA numerator",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Times Interest Earned divides EBIT by total interest expense, and covenant testing requires layering incremental interest into the denominator before comparing against the floor. Pro forma interest = 310,000 + (500,000 x 8%) = 310,000 + 40,000 = $350,000. Pro forma TIE = 1,240,000 / 350,000 = 3.54x, breaching the 4.00x floor by 0.46 turns. Depreciation of $150,000 is irrelevant here because TIE is an accrual-EBIT measure; adding it back constructs EBITDA coverage, a different covenant family. Business interpretation: division controller Owen Gallagher must flag the breach to the lender and negotiate a lower initial drawdown, an EBITDA-based test, or explicit headroom, since automation savings arrive later than the interest charge begins accruing. The traps are freezing the ratio at 4.00x or switching numerators mid-test.",
  "ExplanationWrongA": "Choice A carries the current-year ratio forward untouched; the misconception omits the $40,000 incremental interest the covenant test explicitly requires once the term loan closes. The floor is breached, not met, on a pro forma basis.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C builds an EBITDA coverage figure ((1,240,000 + 150,000) / 350,000 = 3.97x) yet still fails to clear 4.00x; the misconception swaps the covenant numerator mid-calculation, converting a TIE test into an EBITDA test the agreement never authorized.",
  "ExplanationWrongD": "Choice D pairs the EBITDA numerator with the old interest base ((1,240,000 + 150,000) / 310,000 = 4.48x); the misconception compounds two independent errors - upgrading the numerator and forgetting the new loan - to manufacture false compliance headroom.",
  "FormulaReference": "FA-08",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-264",
  "Section": "A",
  "Stem": "Credit manager Victor Amadi monitors Flash's Times Interest Earned covenant, which requires a minimum of 4.00x. This year Flash produced EBIT of $1,240,000 against interest expense of $310,000 - exactly at threshold. Flash now proposes a $500,000 term loan priced at 8% to fund factory automation, adding $40,000 of annual interest once fully drawn; depreciation currently runs $150,000 per year. What pro forma Times Interest Earned should Victor report to the lender after giving full-year effect to the new loan?",
  "Topic": "A.264 pro-forma-tie-covenant",
  "UniqueConceptKey": "A-264-incremental-interest-proforma",
  "VerifiedChecks": [
    "Verification: pro forma interest 310,000 + 40,000 = 350,000; TIE 1,240,000/350,000 = 3.54; variants reproduced (1,390,000/350,000 = 3.97; 1,390,000/310,000 = 4.48)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Difficult/Apply pro forma covenant layering with numerator-confusion distractors"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
}
];
