var pack_p2_a_part16 = [
{
  "Authorities": [
    "Corporate finance theory — EVA",
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$6.1M — NOPAT of $15.6M minus the WACC percentage of 9.5, treating the rate as a dollar charge",
    "B": "$11.4M — the capital charge (9.5% × $120M), which is the return required by investors",
    "C": "$4.2M — NOPAT of $15.6M minus the capital charge of $11.4M (9.5% × $120M)",
    "D": "−$4.2M — computed as the capital charge of $11.4M minus NOPAT of $15.6M, reversing the subtraction"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Confusing the capital charge (a dollar benchmark) with EVA (the excess over that benchmark)",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "EVA measures whether operating profit covers the dollar return required by capital providers. EVA = NOPAT − (WACC × Invested Capital) = $15.6M − (9.5% × $120M) = $15.6M − $11.4M = $4.2M. Positive EVA means Meridian generated $4.2M more than investors could earn elsewhere at equivalent risk — genuine value creation, not merely accounting profit. A company can report positive net income yet destroy value whenever NOPAT fails to cover the full capital charge, which is why EVA is used in bonus plans and value-based management.",
  "ExplanationWrongA": "$6.1M subtracts the WACC percentage (9.5) directly from NOPAT in millions, mixing a rate with a dollar amount. The capital charge must be computed as a dollar figure first: 9.5% × $120M = $11.4M. Subtracting a bare percentage from dollar NOPAT is dimensionally meaningless.",
  "ExplanationWrongB": "$11.4M is the capital charge itself, not EVA. The charge is the minimum dollar return owed to capital providers — the benchmark, not the result. EVA requires subtracting the charge from NOPAT to determine whether operating profit exceeded it.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "The sign is reversed. EVA subtracts the capital charge from NOPAT ($15.6M − $11.4M = +$4.2M). Subtracting NOPAT from the charge inverts the comparison and misreports value creation as value destruction.",
  "FormulaReference": "EVA = NOPAT − (WACC × Invested Capital)",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-117",
  "Section": "A",
  "Stem": "Controller David Kim prepares Meridian Manufacturing's annual value-creation analysis. After-tax operating profit (NOPAT) is $15.6M, invested capital is $120M, and the weighted average cost of capital is 9.5%. The CEO has asked whether Meridian created economic value this year. What economic value added (EVA) should the controller report?",
  "Topic": "A.117 Economic value added — NOPAT versus capital charge",
  "UniqueConceptKey": "A-117-economic-value-added-nopat-vs-capital-charge",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Charge=9.5%×120=11.4; EVA=15.6−11.4=+4.2M",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 330",
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "No adjustment is needed — both companies apply GAAP, so Corona's 35.0% gross margin and the peer's 38.0% are directly comparable and the gap reflects real differences in cost efficiency",
    "B": "Add the full $45M ending LIFO reserve to Corona's gross profit, producing a gross margin of 40.6% ($325M ÷ $800M) that exceeds the peer's 38.0%",
    "C": "Reduce Corona's gross profit by the $10M increase in the LIFO reserve, yielding a conservative restated margin of 33.75% for comparison with the peer",
    "D": "Restate Corona's COGS by subtracting the $10M increase in the LIFO reserve, yielding FIFO-equivalent COGS of $510M and a restated gross margin of 36.25% — narrowing but not eliminating the gap to the peer's 38.0%"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Using the LIFO reserve balance instead of its change, or adjusting the wrong direction, when comparing LIFO and FIFO firms",
  "CorrectChoice": "D",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Under LIFO, rising input prices flow into COGS at current cost, depressing reported gross profit relative to FIFO peers. The LIFO reserve reconciles inventory to FIFO cost; its CHANGE measures the current-year COGS distortion. FIFO-equivalent COGS = LIFO COGS − increase in LIFO reserve = $520M − ($45M − $35M) = $510M. Restated gross margin = ($800M − $510M) ÷ $800M = 36.25%. The gap to the peer narrows from 3.0 points to 1.75 points — a far more informative comparison of underlying cost efficiency. Using the reserve balance instead of its change double-counts all prior years' price distortion.",
  "ExplanationWrongA": "LIFO and FIFO COGS are not comparable when input prices are rising: LIFO charges current, higher prices to COGS while FIFO charges older, lower prices. Corona's 35.0% margin understates the economics of its inventory. Restating COGS by the $10M reserve increase raises the margin to 36.25%, narrowing the peer gap.",
  "ExplanationWrongB": "Adding the full $45M ending reserve double-counts every prior year's price increases. Only this year's change ($10M) distorted this year's COGS. The correct adjustment converts the margin to 36.25%, not 40.6% — the $45M balance belongs to prior years' cost of sales.",
  "ExplanationWrongC": "The adjustment direction is reversed. LIFO COGS is HIGHER than FIFO COGS in a period of rising prices, so the FIFO-equivalent gross profit is HIGHER, not lower. Subtracting the reserve increase penalizes Corona twice and misstates the comparison.",
  "ExplanationWrongD": "",
  "FormulaReference": "FIFO COGS = LIFO COGS − ΔLIFO Reserve",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-118",
  "Section": "A",
  "Stem": "Equity analyst Jordan Reyes compares two steel distributors. Corona Steel uses LIFO and reports sales of $800M, LIFO COGS of $520M, and a LIFO reserve that increased from $35M to $45M during the year. Its peer uses FIFO and reports a gross margin of 38.0%. Corona's controller notes that rising steel prices during the year inflated LIFO COGS. Which adjustment gives the most comparable gross margin comparison?",
  "Topic": "A.118 LIFO reserve adjustment — comparability with FIFO peers",
  "UniqueConceptKey": "A-118-lifo-reserve-adjustment-fifo-comparability",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: ΔReserve=10; FIFO COGS=520−10=510; GM=(800−510)/800=36.25%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 280-10-50-12"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Three — A, B, and D. Combined revenue of $142M is 94.7% of total, satisfying the 75% threshold",
    "B": "Four — every operating segment must be reported separately regardless of size",
    "C": "Two — A and D. Segment B fails the profit test because its profit is below 10% of total segment profit",
    "D": "Four — the 75% threshold requires adding Segment C because A, B, and D combined fall short of 75% of revenue"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Failing to apply the 10% tests independently, or assuming the 75% test is failed when combined reportable revenue already exceeds it",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "ASC 280-10-50-12 requires separate reporting for a segment meeting ANY 10% test: revenue ≥ 10% of combined revenue, profit ≥ 10% of combined profit of profitable segments, or assets ≥ 10% of combined assets. Revenue test: 10% × $150M = $15M — A ($60M), B ($18M), and D ($64M) pass; C ($8M) fails. Profit test: 10% × $21.5M = $2.15M — A, B, and D pass; C fails. Combined revenue of reportable segments ($142M) is 94.7%, which meets the 75% sufficiency threshold, so no additional segments must be added. Three segments are reported.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "ASC 280 does not require reporting every operating segment. Small segments that fail all 10% tests may be aggregated into an 'all other' category, and the standard's purpose is to limit disclosure to economically significant segments. Segment C ($8M revenue, $0.5M profit) fails both tests and is not reportable.",
  "ExplanationWrongC": "Segment B passes BOTH tests: revenue of $18M exceeds the $15M threshold, and profit of $4M exceeds the $2.15M threshold. A segment needs to pass only ONE 10% test to be reportable; B passes two.",
  "ExplanationWrongD": "A, B, and D combined have $142M of revenue — 94.7% of the $150M total, comfortably above the 75% threshold. The threshold exists to force disclosure of more segments when reportable ones cover too little of the entity; here no shortfall exists, so C is not required.",
  "FormulaReference": "ASC 280 10% tests: revenue, profit (of profitable segments), or assets",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-119",
  "Section": "A",
  "Stem": "Controller Amelia Ruiz prepares Brynn Corporation's segment disclosures. Brynn has four operating segments with revenue of $60M (A), $18M (B), $8M (C), and $64M (D), totaling $150M. Segment operating profits are $9M, $4M, $0.5M, and $8M respectively, and no segment had an operating loss. Under ASC 280's quantitative thresholds, how many segments must Brynn report separately?",
  "Topic": "A.119 Segment reporting — ASC 280 quantitative thresholds",
  "UniqueConceptKey": "A-119-segment-reporting-asc-280-thresholds",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 10% revenue=$15M→A,B,D pass; 10% profit=$2.15M→A,B,D pass; 75% test=142/150=94.7% OK",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "DuPont Corporation (1914)",
    "Financial ratio analysis theory"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "12.5% — the return on assets (net income ÷ total assets), which omits the equity multiplier",
    "B": "25.0% — the product of tax burden, interest burden, operating margin, asset turnover, and equity multiplier",
    "C": "33.3% — earnings before tax divided by equity, ignoring the tax charge",
    "D": "20.0% — operating income divided by assets, ignoring interest and taxes"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Computing partial decompositions (ROA, pre-tax ROE) and treating them as ROE",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The five-factor DuPont splits ROE into tax burden (NI ÷ EBT), interest burden (EBT ÷ EBIT), operating margin (EBIT ÷ sales), asset turnover (sales ÷ assets), and equity multiplier (assets ÷ equity). Net income = $150M × (1 − 0.25) = $112.5M. Factors: (112.5 ÷ 150) × (150 ÷ 180) × (180 ÷ 1,200) × (1,200 ÷ 900) × (900 ÷ 450) = 0.75 × 0.8333 × 0.15 × 1.3333 × 2.0 = 25.0%. Check: NI ÷ equity = $112.5M ÷ $450M = 25%. The five-factor version separates how taxes, financing costs, margins, efficiency, and leverage each contribute to the return earned for shareholders.",
  "ExplanationWrongA": "12.5% is ROA (net income ÷ total assets = $112.5M ÷ $900M), which stops before applying the equity multiplier. ROE multiplies ROA by the equity multiplier (900 ÷ 450 = 2.0) to reflect the return to common shareholders on their actual investment.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "33.3% divides pre-tax income by equity ($150M ÷ $450M). ROE is computed on net income after tax, because taxes are a real cost to shareholders. Applying the tax burden factor of 0.75 converts $150M to $112.5M.",
  "ExplanationWrongD": "20.0% is the pre-tax return on assets (EBIT ÷ assets = $180M ÷ $900M). It ignores both the interest burden and the tax burden; the return to common shareholders is earned only after debt service and taxes.",
  "FormulaReference": "FA-14: Five-Factor DuPont = (NI/EBT) × (EBT/EBIT) × (EBIT/Sales) × (Sales/Assets) × (Assets/Equity)",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-120",
  "Section": "A",
  "Stem": "Analyst Sofia Nguyen applies the five-factor DuPont decomposition to Willow Textiles: sales $1,200M; operating income (EBIT) $180M; interest expense $30M; pre-tax income $150M; tax rate 25%; total assets $900M; shareholders' equity $450M. What ROE does the five-factor decomposition produce?",
  "Topic": "A.120 Five-factor DuPont decomposition — tax and interest burden factors",
  "UniqueConceptKey": "A-120-five-factor-dupont-decomposition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 0.75×0.8333×0.15×1.3333×2.0=25.0%; check 112.5/450=25%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "Market-based ratio",
    "SEC Regulation G"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Meridian is overvalued relative to the peer because its P/E of 28 exceeds the peer's 18",
    "B": "Meridian is undervalued relative to the peer because its growth rate of 14% exceeds the peer's 9%",
    "C": "The two stocks are similarly valued on a growth-adjusted basis — both carry PEG ratios of 2.0",
    "D": "Meridian is overvalued because its PEG of 2.0 exceeds the peer's PEG of 1.5"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Judging value on P/E alone, or on growth alone, without computing the price paid per unit of growth",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The PEG ratio divides P/E by expected growth to express the price paid per unit of growth: Meridian 28 ÷ 14 = 2.0; peer 18 ÷ 9 = 2.0. Identical PEGs indicate the market pays the same price for each percentage point of growth — Meridian's premium multiple is fully explained by its higher growth. PEG guards against the classic error of calling a high-P/E stock expensive or a low-P/E stock cheap without considering growth. A PEG near 1.0 is often cited as fair value; both stocks at 2.0 are priced for their growth, and neither is obviously mispriced relative to the other.",
  "ExplanationWrongA": "P/E alone cannot judge value when growth rates differ. Meridian's higher multiple is explained by growth: both stocks trade at the same PEG of 2.0. Rejecting Meridian on P/E alone ignores the very reason the market pays the premium.",
  "ExplanationWrongB": "Higher growth alone does not make a stock cheap — the price paid for that growth matters. Meridian's 14% growth costs 28 times earnings; the peer's 9% growth costs 18 times. Both equal 2.0 times earnings per point of growth.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "The peer's PEG is 18 ÷ 9 = 2.0, not 1.5. Both stocks carry PEG ratios of 2.0. The premise that the peer is cheaper on a growth-adjusted basis rests on a division error.",
  "FormulaReference": "PEG = P/E ÷ Expected EPS Growth Rate",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-121",
  "Section": "A",
  "Stem": "Portfolio manager Ethan Brooks compares Meridian Manufacturing (P/E 28, expected EPS growth 14%) with a peer trading at 18 times earnings with 9% expected growth. Which conclusion correctly applies the PEG ratio?",
  "Topic": "A.121 PEG ratio — growth-adjusted valuation comparison",
  "UniqueConceptKey": "A-121-peg-ratio-growth-adjusted-valuation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: PEG Meridian=28/14=2.0; peer=18/9=2.0 — similarly valued",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "3.2 — net sales divided by average current assets ($900M ÷ $280M)",
    "B": "5.6 — net sales divided by average current liabilities ($900M ÷ $160M)",
    "C": "2.3 — average current assets divided by average working capital ($280M ÷ $120M)",
    "D": "7.5 — net sales divided by average working capital ($900M ÷ $120M)"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using gross current assets as the denominator instead of NET working capital",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Working capital turnover = Net Sales ÷ Average Working Capital. Average working capital = current assets − current liabilities = $280M − $160M = $120M. Turnover = $900M ÷ $120M = 7.5 times. Each dollar of net working capital generated $7.50 of sales. A rising turnover suggests more efficient use of net operating assets; a falling trend can signal that receivables or inventory are building up and consuming cash.",
  "ExplanationWrongA": "3.2 divides sales by GROSS current assets. Working capital is the NET of current assets over current liabilities — the incremental funding tied up in operations. The $160M of spontaneous financing (payables, accruals) must be netted out before measuring the asset base that sales must cover.",
  "ExplanationWrongB": "5.6 divides sales by current liabilities alone. Liabilities are financing sources, not the operating asset base; dividing sales by payables measures how often the financing turns over, not how efficiently net working capital is deployed.",
  "ExplanationWrongC": "2.3 divides current assets by working capital, inverting the ratio and mixing two balance sheet items with no sales figure. A turnover ratio must place the flow (sales) in the numerator and the stock (net working capital) in the denominator.",
  "ExplanationWrongD": "",
  "FormulaReference": "Working Capital Turnover = Net Sales ÷ Average Working Capital",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-122",
  "Section": "A",
  "Stem": "Analyst Priya Sharma reviews Nuvora Industries' operating efficiency. Net sales were $900M; average current assets $280M; average current liabilities $160M. What is the working capital turnover?",
  "Topic": "A.122 Working capital turnover — net working capital efficiency",
  "UniqueConceptKey": "A-122-working-capital-turnover-computation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: WC=280−160=120; turnover=900/120=7.5",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 350",
    "ASC 350-20"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Exclude goodwill from the asset base when computing asset-based ratios such as ROA and asset turnover, then test whether returns on the remaining net operating assets support the goodwill carrying value",
    "B": "Deduct goodwill from shareholders' equity, because goodwill is an intangible that belongs on the liability side of the balance sheet",
    "C": "No adjustment is needed — U.S. GAAP amortizes goodwill each year, so the carrying amount is already reduced to fair value",
    "D": "No adjustment is needed — annual impairment testing guarantees that the carrying value is supported by the acquired business's economics"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Believing goodwill amortization exists under U.S. GAAP, or treating impairment testing as a guarantee of carrying-value accuracy",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Goodwill is an unidentifiable intangible arising from an acquisition; it generates no separable cash flows of its own. For asset-quality analysis, ratios should be computed both with and without goodwill. Excluding it: the asset base falls to $270M, asset turnover rises from 1.4 ($630M ÷ $450M) to 2.33 ($630M ÷ $270M), and ROA rises from 9.0% to 15.0% ($40.5M ÷ $270M). The analytical question is whether the acquired business's economics — reflected in the ex-goodwill returns — justify the $180M carrying value. Under ASC 350, goodwill is not amortized; it is tested annually for impairment, and those tests depend on management's assumptions, which can lag economic deterioration and are not independently verified by the auditor's default procedures.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Goodwill sits on the asset side of the balance sheet and represents a portion of the price paid for the acquisition. Subtracting it from equity confuses the direction of the entry and double-counts: goodwill is already embedded in assets, and equity is unaffected by the analyst's ratio choice.",
  "ExplanationWrongC": "U.S. GAAP prohibits goodwill amortization. ASC 350 requires annual impairment testing instead, so the carrying amount is NOT reduced to fair value each year — it stays at historical acquisition cost until an impairment charge is recorded.",
  "ExplanationWrongD": "Impairment testing relies on management's cash-flow projections and discount rates, which can lag economic deterioration and are subject to managerial discretion. The absence of a recorded impairment does not prove the goodwill is supported; an analyst tests the underlying economics independently.",
  "FormulaReference": "Asset quality adjustment: ratios computed with and without goodwill",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-123",
  "Section": "A",
  "Stem": "Credit analyst Marcus Lee evaluates a distributor whose balance sheet shows goodwill of $180M against total assets of $450M — from a $120M acquisition completed three years ago. Sales are $630M and net income is $40.5M, giving reported ROA of 9.0% and asset turnover of 1.4. The company has not disclosed its impairment test assumptions. How should the analyst treat goodwill when assessing asset quality?",
  "Topic": "A.123 Goodwill and asset quality — ex-goodwill ratio analysis",
  "UniqueConceptKey": "A-123-goodwill-asset-quality-ratio-analysis",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Ex-goodwill assets=270M; turnover=630/270=2.33; ROA=40.5/270=15.0%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "Earnings quality analysis",
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$38.0M — reported net income is the appropriate base because all components are audited and equally persistent",
    "B": "$30.5M — net income adjusted only for the after-tax gain on the sale of the division",
    "C": "$35.0M — core earnings excluding both the after-tax gain and the after-tax restructuring charge",
    "D": "$42.5M — net income adjusted only for the after-tax restructuring charge"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Treating transitory items asymmetrically — excluding gains but keeping charges, or vice versa",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Sustainable earnings exclude transitory items that are unlikely to recur. After-tax gain = $10M × (1 − 0.25) = $7.5M; after-tax restructuring charge = $6M × (1 − 0.25) = $4.5M. Core earnings = $38M − $7.5M + $4.5M = $35.0M. The gain is a one-time liquidation of value that will not repeat; the restructuring charge reflects this period's repositioning costs, not ongoing operations. Projecting from $38M overstates persistence (gains do not recur); projecting from $30.5M understates it (the charge is not expected annually). The analyst should also verify that core earnings are backed by operating cash flow.",
  "ExplanationWrongA": "Reported net income mixes recurring and transitory components. A gain on divestiture will not repeat next year, and the restructuring charge is a period-specific cost. Anchoring a projection on reported income overstates future earnings power by including the $7.5M after-tax gain.",
  "ExplanationWrongB": "$30.5M removes the gain but leaves the restructuring charge in. Because restructuring is a transitory cost, core earnings add it back after tax (+$4.5M), giving $35.0M. Excluding gains but not charges treats transitory items asymmetrically and biases the projection downward.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "$42.5M adds back the charge but keeps the gain. The gain inflated this year's income and must be excluded from recurring earnings (−$7.5M). Symmetric treatment of both transitory items yields $35.0M.",
  "FormulaReference": "Core earnings = NI − after-tax transitory gains + after-tax transitory charges",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-124",
  "Section": "A",
  "Stem": "Analyst Grace Liu projects Rafter Industries' sustainable earnings. Reported net income was $38M, including a pre-tax gain of $10M on the sale of a division and a pre-tax restructuring charge of $6M. The tax rate is 25%. Which earnings measure should anchor the projection of recurring earnings power?",
  "Topic": "A.124 Earnings persistence — core versus transitory components",
  "UniqueConceptKey": "A-124-earnings-persistence-core-vs-transitory",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Gain AT=7.5; Charge AT=4.5; Core=38−7.5+4.5=35.0",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 606",
    "ASC 606-10-32"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Recognize the Q4 results and proceed with the bonus cycle. The extended terms were approved as a documented holiday program, and goods shipped under standard revenue contracts qualify as revenue under ASC 606",
    "B": "Freeze Q4 performance-based pay and investigate before the earnings release. The combination of a 28% revenue surge, 90-day terms, a 45% jump in receivables, and January return requests at 18% versus a 3% norm suggests shipments were pushed to distributors to manufacture the quarter — revenue may be overstated if substantial payment is not probable or if side agreements exist",
    "C": "Recognize revenue but exclude the extended-terms shipments from the bonus calculation, since returns and collectability are operating problems that do not affect revenue recognition",
    "D": "Reverse all Q4 revenue to January and reissue the quarter as a restatement, because any product that can be returned cannot be recognized in Q4"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Treating collectability and return evidence as an operating problem separate from revenue recognition",
  "CorrectChoice": "B",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "The pattern — quarter-end shipment surge, dramatic terms relaxation, receivables growth far outpacing revenue, and abnormal returns — is the classic channel-stuffing profile. Under ASC 606, revenue is recognized when control transfers and collectability is probable; extended payment terms and side understandings can call collectability into question, and expected returns reduce the transaction price. The CFO's duty is to investigate whether the holiday program created enforceable rights, whether substantial payment is probable, and whether return estimates need adjusting before certifying results or paying bonuses tied to them. Freezing bonuses and investigating preserves both accounting integrity and management credibility — recognizing first and correcting later would expose the company to restatement risk.",
  "ExplanationWrongA": "Approving a program does not establish that the underlying revenue meets ASC 606. Extended terms without evidence of customers' intention and ability to pay, plus an 18% return rate against a 3% norm, are red flags that the transaction price may be overstated. Documented terms alone do not cure a channel-stuffing arrangement.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "The returns and collectability evidence directly affects the amount and timing of revenue under ASC 606 through the transaction price (variable consideration and expected returns). Treating them as a separate operating problem while recognizing full revenue double-counts the economics — the revenue base the bonus plan is computed on is precisely the number in question.",
  "ExplanationWrongD": "Reversing the entire quarter before investigating overcorrects. Some Q4 shipments are legitimate. The correct sequence is investigation, estimation of returns and collectability adjustments, then recognition at the properly measured amount. Automatic full reversal is as unsupportable as automatic full recognition.",
  "FormulaReference": "ASC 606 transaction price — variable consideration and returns adjustments",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-125",
  "Section": "A",
  "Stem": "CFO Elena Torres reviews Vantage Optics' Q4 results before the earnings release: revenue rose 28% versus Q3, with 60% of the quarter's shipments made in the final two weeks under a newly approved 'holiday program' extending distributor terms from net 30 to net 90 days. Accounts receivable rose 45%, and January return requests are running at 18% of Q4 shipments versus a historical 3%. The CEO wants to close the quarter and process bonuses. What should the CFO do?",
  "Topic": "A.125 Channel stuffing — revenue timing red flags and earnings quality",
  "UniqueConceptKey": "A-125-channel-stuffing-revenue-timing-red-flags",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Channel-stuffing profile — freeze bonuses, investigate under ASC 606 before recognizing",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230",
    "Cash flow adequacy analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "0.67 — capital expenditures divided by operating cash flow ($30M ÷ $45M)",
    "B": "1.50 — operating cash flow divided by capital expenditures ($45M ÷ $30M)",
    "C": "2.50 — (operating cash flow + capital expenditures) ÷ capital expenditures",
    "D": "3.00 — operating cash flow divided by maintenance-only capital expenditures of $15M"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Inverting the ratio, or netting capital expenditures against a maintenance estimate not given in the data",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Cash flow to capital expenditures = Operating Cash Flow ÷ Capital Expenditures = $45M ÷ $30M = 1.50. The ratio measures how many times operating cash flow covers capital spending — Meridian generates $1.50 of cash from operations for every $1.00 invested in fixed assets. A ratio below 1.0 signals that operations cannot internally fund asset replacement or growth, forcing external financing or deferred spending. Sustained coverage above 1.0 is a hallmark of financial flexibility.",
  "ExplanationWrongA": "0.67 inverts the ratio. Capital expenditures must be the DENOMINATOR — the question is how much operating cash flow covers each dollar of investment, not how large capital spending is relative to cash flow.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Adding capital expenditures to the numerator double-counts the investment. Operating cash flow is the coverage measure; capital spending is the obligation being covered. The correct comparison is $45M against $30M, not $75M against $30M.",
  "ExplanationWrongD": "Splitting capital spending into maintenance and growth requires information about the split, which the data does not provide. With no maintenance estimate given, the analyst must use total capital expenditures — $45M ÷ $30M = 1.50, not 3.00.",
  "FormulaReference": "Cash Flow to Capital Expenditures = Operating Cash Flow ÷ Capital Expenditures",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-126",
  "Section": "A",
  "Stem": "Meridian Manufacturing reports operating cash flow of $45M and capital expenditures of $30M. The CFO wants a single measure of whether operations can fund asset replacement internally. What is the cash flow to capital expenditures ratio?",
  "Topic": "A.126 Cash flow to capital expenditures — internal funding capacity",
  "UniqueConceptKey": "A-126-cash-flow-to-capital-expenditures",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 45/30=1.50",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "Market-based ratio",
    "SEC Regulation G"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "0.67 — book value per share divided by market price ($8 ÷ $12)",
    "B": "2.4 — market price divided by book value excluding retained earnings ($250M ÷ 50M = $5; $12 ÷ $5)",
    "C": "1.5 — market price divided by book value per share ($12 ÷ $8, where BVPS = $400M ÷ 50M)",
    "D": "1.2 — market price divided by total assets per share ($500M ÷ 50M = $10; $12 ÷ $10)"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Computing the ratio against assets or against only contributed capital, or inverting market over book",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Price-to-book = Market Price per Share ÷ Book Value per Share. Book value per share = total shareholders' equity ÷ shares outstanding = $400M ÷ 50M = $8. P/B = $12 ÷ $8 = 1.5 — the market values Meridian at 1.5 times the accounting book value of its net assets. A P/B above 1.0 indicates the market expects the company to earn returns above its cost of capital; a P/B below 1.0 can signal distress, asset impairment, or a value opportunity.",
  "ExplanationWrongA": "0.67 inverts the ratio, placing book value over market price. The P/B ratio is market over book; inverting it converts the multiple into a book-to-market yield and changes the interpretation.",
  "ExplanationWrongB": "Excluding retained earnings from book value is wrong — retained earnings are a core component of shareholders' equity under ASC 505. Total equity is $400M (common stock $100M + APIC $150M + retained earnings $150M), giving BVPS of $8 and P/B of 1.5.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Using total assets instead of equity confuses the denominator. P/B compares market value to the shareholders' claim — net assets, not gross assets. With $500M of assets (implying $100M of liabilities), the correct per-share book value is $8, not $10.",
  "FormulaReference": "P/B = Market Price per Share ÷ Book Value per Share",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-127",
  "Section": "A",
  "Stem": "Meridian Manufacturing trades at $12 per share with 50M shares outstanding. Shareholders' equity totals $400M (common stock $100M, additional paid-in capital $150M, retained earnings $150M), and total assets are $500M. What is the price-to-book ratio?",
  "Topic": "A.127 Price-to-book ratio — market versus accounting value",
  "UniqueConceptKey": "A-127-price-to-book-ratio",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: BVPS=400/50=8; P/B=12/8=1.5",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
}
];
