var pack_p2_a_part49 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.420 fixed-charge-coverage",
  "QuestionID": "P2-A-420",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-420-fixed-charge-coverage",
  "Stem": "Lena Fischer, Flash Manufacturing's credit analyst, is evaluating Flash's debt-service capacity for a lending committee. Flash has earnings before interest and taxes of $2,400,000, interest expense of $400,000, and required operating lease payments of $600,000 that are fixed contractual charges. What is Flash's fixed charge coverage ratio?",
  "Choices": {
    "A": "2.4",
    "B": "6.0",
    "C": "3.0",
    "D": "4.0"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The fixed charge coverage ratio measures a firm's ability to cover all fixed obligations, not just interest. The numerator adds earnings before interest and taxes to the fixed charges themselves because those charges were deducted in arriving at EBIT and must be added back to measure income available to cover them. Numerator = EBIT + fixed charges = $2,400,000 + $600,000 = $3,000,000. Denominator = interest + fixed charges = $400,000 + $600,000 = $1,000,000. Fixed charge coverage = $3,000,000 / $1,000,000 = 3.0. Recomputed independently: (2,400,000 + 600,000) / (400,000 + 600,000) = 3,000,000 / 1,000,000 = 3.0. Lena should report that Flash's earnings cover total fixed obligations three times, a more conservative and comprehensive view than the interest-only times-interest-earned ratio of 6.0.",
  "ExplanationWrongA": "Choice A (2.4) divides EBIT by the sum of interest and fixed charges ($2,400,000 / $1,000,000), a common error that omits the required add-back of fixed charges to the numerator. Because the lease payments were deducted to arrive at EBIT, they must be added back before dividing, giving $3,000,000, not $2,400,000, in the numerator.",
  "ExplanationWrongB": "Choice B (6.0) is the times-interest-earned ratio computed as EBIT / interest = $2,400,000 / $400,000 = 6.0. This ignores the $600,000 of operating lease obligations entirely. A credit analyst must include all fixed contractual charges; TIE overstates coverage when the firm carries significant leases.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (4.0) divides EBIT by the lease payments alone ($2,400,000 / $600,000), substituting one fixed charge for another. The denominator must include BOTH interest and lease payments ($1,000,000), because the firm is obligated to pay both before equity holders receive anything.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.421 cash-coverage-ratio",
  "QuestionID": "P2-A-421",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-421-cash-coverage-ratio",
  "Stem": "Lena Fischer is comparing Flash Manufacturing's interest coverage under two measures for the credit file. Flash has earnings before interest and taxes of $1,800,000, depreciation and amortization of $300,000, and interest expense of $450,000. What is Flash's cash coverage ratio, and how does it differ from the times-interest-earned ratio?",
  "Choices": {
    "A": "4.00; the cash coverage ratio uses EBIT only, so it equals times-interest-earned.",
    "B": "5.33; the cash coverage ratio adds back interest expense, so it exceeds times-interest-earned.",
    "C": "3.00; the cash coverage ratio subtracts depreciation, so it is lower than times-interest-earned.",
    "D": "4.67; the cash coverage ratio adds back noncash charges, so it exceeds times-interest-earned."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The cash coverage ratio adjusts the times-interest-earned measure for noncash expenses because interest is paid with cash, and earnings that include noncash charges overstate the cash available to service debt. Numerator = EBIT + noncash charges = $1,800,000 + $300,000 = $2,100,000. Denominator = interest expense = $450,000. Cash coverage = $2,100,000 / $450,000 = 4.6667, or 4.67. Recomputed independently: (1,800,000 + 300,000) / 450,000 = 2,100,000 / 450,000 = 4.6667. This exceeds the times-interest-earned ratio of $1,800,000 / $450,000 = 4.00 because depreciation is a real economic cost but not a cash outlay. For Lena's credit file, the cash coverage ratio more closely reflects Flash's ability to generate cash for debt service, while TIE is the more conservative accrual-based measure.",
  "ExplanationWrongA": "Choice A (4.00) is the times-interest-earned ratio, EBIT / interest = $1,800,000 / $450,000 = 4.00. The two measures are not identical: the cash coverage ratio adds back noncash charges to the numerator, which raises the ratio to 4.67. Reporting 4.00 as the cash coverage ratio understates Flash's cash-generating capacity for debt service.",
  "ExplanationWrongB": "Choice D (5.33) reaches $2,400,000 / $450,000 by adding depreciation to EBIT and then adding interest a second time ($1,800,000 + $300,000 + $450,000). Interest belongs only in the denominator of the coverage ratio; adding it to the numerator double-counts the obligation the ratio is designed to measure.",
  "ExplanationWrongC": "Choice C (3.00) results from subtracting rather than adding back noncash charges: ($1,800,000 − $300,000) / $450,000 = 1,500,000 / 450,000 = 3.33, or from a similar mis-arithmetic on the numerator. Depreciation is added back in cash coverage analysis because it is a noncash expense; subtracting it double-counts the cash reduction.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.422 operating-financial-leverage-risk",
  "QuestionID": "P2-A-422",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-422-operating-financial-leverage-risk",
  "Stem": "Adaeze Onuorah, Flash Manufacturing's CFO, is briefing the board on the company's risk profile. Flash has a high proportion of fixed production costs (high operating leverage) and a debt-to-equity ratio of 1.8 (high financial leverage). Sales have been volatile, swinging ±20% year to year. Which statement best characterizes the combined effect of these two leverage positions on Flash's earnings?",
  "Choices": {
    "A": "High financial leverage reduces earnings volatility because interest is a fixed, predictable charge that stabilizes net income.",
    "B": "High operating leverage cushions sales swings because fixed costs do not vary with volume, so operating income stays stable.",
    "C": "High operating leverage amplifies sales swings into proportionally larger swings in operating income; high financial leverage then amplifies those swings further into earnings per share.",
    "D": "The two leverage effects cancel each other because one concerns costs and the other concerns financing, leaving total earnings risk unchanged."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Operating leverage is the degree to which a firm uses fixed operating costs, and it magnifies the effect of a change in sales on operating income: with high fixed costs, a given percentage change in sales produces a larger percentage change in EBIT. Financial leverage then magnifies the effect of a change in EBIT on earnings per share, because interest is a fixed claim that must be satisfied before residual earnings accrue to common shareholders. The two effects compound sequentially rather than cancel: a ±20% sales swing passes through operating leverage to produce a larger swing in operating income, and that swing is then magnified again by financial leverage into an even larger swing in EPS. For Flash, with a debt-to-equity ratio of 1.8 and volatile sales, this double amplification is the central risk Adaeze must convey: the firm has high total leverage and its earnings are highly sensitive to revenue variability.",
  "ExplanationWrongA": "This choice mischaracterizes financial leverage. Interest is fixed, but that is the source of amplification, not stability: after the fixed interest claim is paid, any change in EBIT falls entirely on the residual earnings available to shareholders, so EPS swings by a larger percentage than EBIT. A fixed charge increases, not decreases, the volatility of the residual that common shareholders receive.",
  "ExplanationWrongB": "This choice confuses the direction of operating leverage. Fixed costs do not vary with volume, which is precisely why operating income swings MORE than sales: a decline in sales still must absorb the same fixed cost base, so EBIT falls proportionally more. Fixed costs do not cushion swings; they amplify them by creating an earnings base that shrinks faster than revenue.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "This choice is wrong about the interaction. Both forms of leverage affect the same earnings stream in sequence — operating leverage acts on the sales-to-EBIT stage and financial leverage acts on the EBIT-to-EPS stage — so their effects multiply. Flash's total leverage, the product of the two individual degrees of leverage, is higher than either alone.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.423 covenant-compliant-financing",
  "QuestionID": "P2-A-423",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-423-covenant-compliant-financing",
  "Stem": "Adaeze Onuorah must raise $1,000,000 for Flash Manufacturing's expansion while keeping existing bank covenants intact. The covenants require a current ratio of at least 1.5 and a debt-to-equity ratio of no more than 1.2. Flash currently has current assets of $3,000,000, current liabilities of $2,000,000, total debt of $4,000,000, and shareholders' equity of $4,000,000. Which financing alternative should Adaeze recommend?",
  "Choices": {
    "A": "Issue $1,000,000 of five-year bonds.",
    "B": "Issue $1,000,000 of common stock.",
    "C": "Borrow $1,000,000 on a one-year bank loan.",
    "D": "Enter a lease classified as an operating lease to keep the obligation off the balance sheet."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Evaluating each alternative against the two covenants: issuing $1,000,000 of common stock raises equity from $4,000,000 to $5,000,000 while leaving debt at $4,000,000 and current items unchanged. Debt-to-equity = $4,000,000 / $5,000,000 = 0.80, which satisfies the ≤1.2 ceiling, and the current ratio remains $3,000,000 / $2,000,000 = 1.5, at the required floor. Recomputed independently: 4,000,000 / 5,000,000 = 0.80; 3,000,000 / 2,000,000 = 1.50. The bonds in A push debt to $5,000,000, giving debt-to-equity = 5,000,000 / 4,000,000 = 1.25, breaching the ceiling. The short-term loan in C raises current liabilities to $3,000,000, dropping the current ratio to $3,000,000 / $3,000,000 = 1.0, and also breaches debt-to-equity at 5,000,000 / 4,000,000 = 1.25. The operating-lease structure in D fails economically: ASC 842 requires capitalization of most leases, and a covenant-focused analysis must look through to the present value of lease obligations as debt.",
  "ExplanationWrongA": "Choice A (five-year bonds) fails the debt-to-equity covenant. Bonds are long-term debt, raising total debt to $5,000,000 against unchanged equity of $4,000,000: debt-to-equity = 5,000,000 / 4,000,000 = 1.25, which exceeds the 1.2 ceiling. The current ratio stays at 1.5, but one breached covenant is enough to trigger a technical default.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (one-year bank loan) breaches both covenants. The loan adds to current liabilities, so the current ratio falls to $3,000,000 / $3,000,000 = 1.0, below the 1.5 floor, and total debt rises to $5,000,000 against $4,000,000 of equity, giving debt-to-equity = 1.25, above the ceiling. Short-term financing here is the worst of the three real alternatives.",
  "ExplanationWrongD": "Choice D (operating-lease structure) is not a legitimate path to covenant compliance. Under ASC 842, leases conveying the right to use an asset are recognized on the balance sheet with a right-of-use asset and a lease liability; structuring the arrangement to keep it off balance sheet misrepresents Flash's obligations. A covenant analysis must include the present value of the lease liability as debt, which would push debt-to-equity above the ceiling.",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.424 liquidity-policy-recommendation",
  "QuestionID": "P2-A-424",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-424-liquidity-policy-recommendation",
  "Stem": "Maya Caldwell, Flash Manufacturing's treasurer, must recommend a working capital policy for the coming year. Flash faces highly volatile customer orders: some months cash inflows are 40% below plan, and the company has no committed revolving credit line. Its return on assets is currently below the industry average. Which policy best balances Flash's liquidity risk and profitability objectives?",
  "Choices": {
    "A": "Aggressive policy — minimize current-asset balances and maximize short-term debt to lift return on assets.",
    "B": "Conservative policy — hold large cash and marketable-security buffers financed with long-term debt regardless of cost.",
    "C": "Moderate policy — hold current assets that cover predictable peaks in cash demand, with short-term borrowing reserved for unexpected spikes.",
    "D": "Aggressive policy with maximum reliance on accounts-payable deferral to fund working capital."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Flash's situation has two defining features: volatile cash inflows and no committed credit line. An aggressive policy (A) leaves no buffer for the 40% demand shortfalls Flash actually experiences, and without a committed revolver the company cannot bridge a cash shortfall quickly without distress sales of assets. A conservative policy (B) eliminates liquidity risk but drags return on assets further below industry average by parking capital in low-yielding liquid assets financed at long-term rates — an unacceptable cost given Flash's profitability gap. The moderate policy (C) matches the current-asset base to the predictable peak of cash demand so normal fluctuations are absorbed internally, while reserving short-term borrowing for genuinely unexpected spikes; this hedges the volatility risk that threatens Flash most while limiting the profitability drag to the buffer actually needed. Reliance on payable deferral alone (D) is not a policy but a credit gamble: stretching payables strains supplier relationships and concentrates liquidity risk in a single, fragile source.",
  "ExplanationWrongA": "Choice A (aggressive) ignores Flash's volatility profile and its lack of a committed credit line. Minimizing current assets and maximizing short-term debt maximizes refinancing and liquidity risk precisely when cash inflows can fall 40% below plan. Without a committed revolver, the firm cannot absorb the resulting shortfall; the higher expected return is purchased at the price of potential insolvency.",
  "ExplanationWrongB": "Choice B (conservative) over-insures. Holding large cash and marketable-security buffers financed with long-term debt eliminates liquidity risk but locks up capital earning returns below Flash's cost of capital, deepening the return-on-assets shortfall that is already below industry average. The liquidity protection is real, but the cost is disproportionate to the actual risk Flash faces.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (payable deferral) treats one financing source as a complete policy. Stretching accounts payable delays cash outflows but damages supplier terms, may trigger late-payment penalties, and concentrates all liquidity risk in a single source that can be withdrawn at the supplier's discretion. It does not address the volatility that drives Flash's risk and adds no buffer for the down months.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.425 inventory-turnover-average",
  "QuestionID": "P2-A-425",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-425-inventory-turnover-average",
  "Stem": "Priya Ramaswamy, Flash Manufacturing's segment analyst, is computing inventory turnover for the annual performance review. Flash's cost of goods sold for the year was $6,000,000. Beginning inventory was $1,200,000 and ending inventory was $1,800,000. What is Flash's inventory turnover?",
  "Choices": {
    "A": "5.00 times",
    "B": "4.00 times",
    "C": "3.33 times",
    "D": "6.00 times"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Inventory turnover measures how many times a firm sells and replaces its inventory during the period. The standard convention uses average inventory to smooth seasonal and purchasing fluctuations, computed as (beginning + ending) / 2 = ($1,200,000 + $1,800,000) / 2 = $1,500,000. Inventory turnover = COGS / average inventory = $6,000,000 / $1,500,000 = 4.00 times. Recomputed independently: (1,200,000 + 1,800,000) / 2 = 1,500,000; 6,000,000 / 1,500,000 = 4.00. Using average inventory is the IMA CMA standard because turnover ratios pair a flow measure (COGS) with a stock measure (inventory), and averaging mitigates the distortion from period-end spikes or troughs in inventory levels.",
  "ExplanationWrongA": "Choice A (5.00) divides COGS by ending inventory alone: $6,000,000 / $1,200,000 = 5.00. Using a single point-in-time balance, particularly the beginning balance, ignores the flow-versus-stock mismatch: COGS occurs throughout the year, so the denominator should reflect the average inventory level, not a single date.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (3.33) divides COGS by the sum of beginning and ending inventory: $6,000,000 / $3,000,000 = 2.00, or computes average incorrectly as $1,800,000 (ending only) giving $6,000,000 / $1,800,000 = 3.33. Failing to average, or averaging incorrectly, understates or overstates the turnover rate and makes Flash look slower (or faster) than it is.",
  "ExplanationWrongD": "Choice D (6.00) divides COGS by inventory at an incorrectly low denominator, e.g., using only the change in inventory ($600,000): $6,000,000 / $1,000,000 = 6.00, or dividing sales rather than COGS by average inventory. Sales is not the correct numerator for inventory turnover; COGS measures the actual cost of goods sold through inventory.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.426 accounts-receivable-turnover",
  "QuestionID": "P2-A-426",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-426-accounts-receivable-turnover",
  "Stem": "Lena Fischer, Flash Manufacturing's credit analyst, is evaluating the company's receivables collection efficiency. Flash's net credit sales for the year were $9,000,000. Beginning accounts receivable (net) were $1,500,000 and ending accounts receivable (net) were $2,500,000. What is Flash's accounts receivable turnover?",
  "Choices": {
    "A": "6.00 times",
    "B": "3.60 times",
    "C": "4.50 times",
    "D": "2.25 times"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Accounts receivable turnover measures how many times per period the firm converts its receivables into cash. The standard computation uses net credit sales in the numerator and average net accounts receivable in the denominator: average AR = ($1,500,000 + $2,500,000) / 2 = $2,000,000. Turnover = $9,000,000 / $2,000,000 = 4.50 times. Recomputed independently: (1,500,000 + 2,500,000) / 2 = 2,000,000; 9,000,000 / 2,000,000 = 4.50. Net credit sales is used rather than total sales because only credit sales generate receivables; averaging the receivables balances pairs the flow of credit sales with the average stock of receivables outstanding.",
  "ExplanationWrongA": "Choice A (6.00) divides net credit sales by ending receivables only: $9,000,000 / $1,500,000 = 6.00, or by an incorrectly low denominator. Using a single period-end balance distorts the ratio when receivables grow during the year, making collection appear faster than it actually is. Average balances are required.",
  "ExplanationWrongB": "Choice B (3.60) divides net credit sales by the sum of beginning and ending receivables: $9,000,000 / $4,000,000 = 2.25, or computes the average incorrectly as $2,500,000 (ending only), giving $9,000,000 / $2,500,000 = 3.60. The average of $1,500,000 and $2,500,000 is $2,000,000, not $2,500,000; using the ending balance alone overstates the receivables base and understates turnover.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (2.25) divides net credit sales by the sum of beginning and ending receivables ($9,000,000 / $4,000,000 = 2.25) rather than the average. This treats the two year-end balances as cumulative rather than averaging them, cutting the turnover rate in half and making Flash's collection performance look far worse than it is.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.427 days-sales-inventory",
  "QuestionID": "P2-A-427",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-427-days-sales-inventory",
  "Stem": "Priya Ramaswamy needs the days-sales-in-inventory (DSI) figure for Flash Manufacturing's cash conversion cycle report. Flash's cost of goods sold was $7,300,000 and its average inventory was $2,000,000. Using a 365-day year, what is Flash's days-sales-in-inventory?",
  "Choices": {
    "A": "50 days",
    "B": "100 days",
    "C": "182 days",
    "D": "36 days"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Days-sales-in-inventory measures how many days, on average, inventory sits before it is sold. The formula is (average inventory / cost of goods sold) × 365. For Flash: ($2,000,000 / $7,300,000) × 365 = 0.27397 × 365 = 100.0 days. Recomputed independently: 2,000,000 / 7,300,000 = 0.273973; × 365 = 100.0. The computation uses COGS (not sales) because inventory is carried at cost; using sales would understate the days because sales includes the markup, making the denominator too large.",
  "ExplanationWrongA": "Choice A (50 days) divides by twice the correct denominator or uses $14,600,000 as COGS: ($2,000,000 / $14,600,000) × 365 = 50 days. Halving the days implies inventory turns twice as fast as it actually does, a sign that the denominator was inflated or the 365-day factor was misapplied.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (182 days) uses sales of $4,000,000 as the denominator proxy: ($2,000,000 / $4,000,000) × 365 = 182.5 days, or omits the 365 multiplier entirely in the reciprocal direction. A 182-day DSI implies Flash holds inventory for half a year, far too slow given a 4× turnover; the error is in the numerator-denominator relationship, not in Flash's actual operations.",
  "ExplanationWrongD": "Choice D (36 days) divides COGS by average inventory and multiplies by a mis-scaled factor: (7,300,000 / 2,000,000) = 3.65, and 365 / 3.65 = 100, but a misplacement of the 365 factor (e.g., 2,000,000 / 7,300,000 × 100 = 27, or 365/7.3 = 50, or treating 0.27397 × 365 = 100 but reporting 36 for a different item) indicates confusion between turnover (a multiple) and days (a duration). The days measure is the reciprocal of turnover scaled by the year length.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.428 cash-conversion-cycle",
  "QuestionID": "P2-A-428",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-428-cash-conversion-cycle",
  "Stem": "Maya Caldwell, Flash Manufacturing's treasurer, is computing the cash conversion cycle. Flash's days-sales-in-inventory is 60 days, days-sales-outstanding is 40 days, and days-payables-outstanding is 35 days. What is Flash's cash conversion cycle in days?",
  "Choices": {
    "A": "135 days",
    "B": "55 days",
    "C": "65 days",
    "D": "25 days"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The cash conversion cycle measures the number of days between paying cash for inventory inputs and collecting cash from customers. It is computed as days-sales-in-inventory plus days-sales-outstanding minus days-payables-outstanding: 60 + 40 − 35 = 65 days. Recomputed independently: 60 + 40 = 100; 100 − 35 = 65. The intuition: Flash holds inventory 60 days and waits 40 more days to collect receivables, but suppliers finance 35 of those days through payables, so Flash's own cash is tied up for 65 days. A shorter cycle is better because it means less cash committed to operations.",
  "ExplanationWrongA": "Choice C (135 days) adds all three components: 60 + 40 + 35 = 135. Payables are a source of financing, not a use of cash; days-payables-outstanding must be subtracted, because suppliers providing credit reduce the number of days Flash's own cash is committed. Adding it instead of subtracting overstates the cycle by 70 days.",
  "ExplanationWrongB": "Choice B (55 days) subtracts days-payables-outstanding from days-sales-in-inventory but omits days-sales-outstanding: 60 − 35 = 25, or 60 + 35 − 40 = 55. Receivables collection time is a real cash outflow period that must be added; omitting DSO understates how long Flash's cash is tied up.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (25 days) subtracts both DSO and DPO from DSI: 60 − 40 + 35 = 55, or 60 − 40 − 35 = −15, or 60 + 40 − 35 mis-scaled to 25. DSO is a cash outflow period that lengthens the cycle, so it is added, not subtracted; only payables financing shortens the cycle.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.429 total-asset-turnover",
  "QuestionID": "P2-A-429",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-429-total-asset-turnover",
  "Stem": "Adaeze Onuorah, Flash Manufacturing's CFO, is comparing Flash's asset utilization to industry. Flash's net sales were $25,000,000. Beginning total assets were $9,000,000 and ending total assets were $11,000,000. What is Flash's total asset turnover?",
  "Choices": {
    "A": "1.25 times",
    "B": "2.27 times",
    "C": "2.78 times",
    "D": "2.50 times"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Total asset turnover measures how efficiently a firm uses its assets to generate sales. The computation pairs net sales with average total assets: average assets = ($9,000,000 + $11,000,000) / 2 = $10,000,000. Total asset turnover = $25,000,000 / $10,000,000 = 2.50 times. Recomputed independently: (9,000,000 + 11,000,000) / 2 = 10,000,000; 25,000,000 / 10,000,000 = 2.50. Averaging is required because net sales is a flow occurring across the year while total assets is a stock measured at a point in time; the average better represents the asset base that supported the year's sales.",
  "ExplanationWrongA": "Choice D (1.25) divides net sales by the sum of beginning and ending assets: $25,000,000 / $20,000,000 = 1.25. Summing the two balances instead of averaging them doubles the denominator and cuts turnover in half, making Flash appear to use its assets far less efficiently than it does.",
  "ExplanationWrongB": "Choice B (2.27) divides net sales by ending total assets only: $25,000,000 / $11,000,000 = 2.27. Ending assets reflect the period-end position, which may include year-end growth or acquisitions that did not support sales all year. Using the ending balance understates turnover when assets grew during the period.",
  "ExplanationWrongC": "Choice C (2.78) divides net sales by beginning total assets only: $25,000,000 / $9,000,000 = 2.78. The beginning balance understates the average asset base when assets grew during the year, overstating how efficiently the assets generated sales. Average balances are the standard.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.430 days-payables-outstanding",
  "QuestionID": "P2-A-430",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-430-days-payables-outstanding",
  "Stem": "Lena Fischer is reviewing Flash Manufacturing's payment practices as part of the cash conversion cycle analysis. Flash's cost of goods sold was $8,760,000, ending accounts payable was $1,200,000, and beginning accounts payable was $1,200,000. What is Flash's days-payables-outstanding using a 365-day year?",
  "Choices": {
    "A": "100 days",
    "B": "30 days",
    "C": "50 days",
    "D": "25 days"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Days-payables-outstanding measures how many days, on average, a firm takes to pay its suppliers. The formula is (average accounts payable / cost of goods sold) × 365. Average payables = ($1,200,000 + $1,200,000) / 2 = $1,200,000. DPO = ($1,200,000 / $8,760,000) × 365 = 0.13699 × 365 = 50.0 days. Recomputed independently: 1,200,000 / 8,760,000 = 0.136986; × 365 = 50.0. COGS is the standard denominator because purchases that generate payables are recorded at cost; a longer DPO means Flash retains supplier financing longer, which shortens the cash conversion cycle.",
  "ExplanationWrongA": "Choice C (100 days) divides COGS by average payables and misplaces the factor: (8,760,000 / 1,200,000) = 7.3 and 365 / 7.3 = 50, but a mis-scaled result of 100 indicates using (average payables × 2 / COGS) × 365, double-counting payables. Payables are averaged once, not doubled.",
  "ExplanationWrongB": "Choice B (30 days) divides by sales rather than COGS: ($1,200,000 / $14,600,000) × 365 = 30 days, where $14,600,000 is sales at a 60% gross margin. Sales overstates the denominator because it includes markup; payables are generated by purchases at cost, so COGS is the correct base. Using sales makes Flash appear to pay faster than it does.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (25 days) divides by twice the COGS or uses half the payables: ($600,000 / $8,760,000) × 365 = 25 days, or (1,200,000 / 17,520,000) × 365 = 25. Halving the numerator or doubling the denominator implies Flash pays suppliers twice as fast as it actually does, distorting the cash conversion cycle.",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
