var pack_p2_a_part53 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.460 special-purpose-entity",
  "QuestionID": "P2-A-460",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-460-special-purpose-entity",
  "Stem": "Adaeze Onuorah is evaluating a structured financing arrangement Flash Manufacturing entered with a variable interest entity (VIE) that holds $30,000,000 of Flash's receivables. Under ASC 810, when must Flash consolidate the VIE?",
  "Choices": {
    "A": "Flash must consolidate if the VIE holds any of Flash's assets.",
    "B": "Flash must never consolidate a VIE because VIEs are separate legal entities.",
    "C": "Flash must consolidate only if it owns more than 50% of the VIE's equity.",
    "D": "Flash must consolidate if it is the primary beneficiary with the power to direct the VIE's activities and the obligation to absorb its losses."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Under ASC 810, a reporting entity must consolidate a variable interest entity when it is the primary beneficiary of that VIE. The primary-beneficiary determination requires BOTH (1) the power to direct the activities of the VIE that most significantly affect its economic performance, AND (2) the obligation to absorb losses or the right to receive benefits that could potentially be significant to the VIE. The analysis is based on control and risk exposure, not merely on equity ownership percentage. If Flash directs how the VIE manages the receivables and absorbs the credit losses, Flash is the primary beneficiary and must consolidate the VIE's assets, liabilities, and results — putting the $30,000,000 of receivables and the related financing back on Flash's balance sheet.",
  "ExplanationWrongA": "Choice D (holds any of Flash's assets) is overbroad. Merely holding Flash's receivables does not trigger consolidation; the test is whether Flash is the primary beneficiary with power over and exposure to the VIE. The arrangement must be analyzed under the ASC 810 two-part test, not by the mere existence of transferred assets.",
  "ExplanationWrongB": "Choice B (never consolidate VIEs) is false. Legal separateness does not prevent consolidation; ASC 810 requires consolidation of VIEs by their primary beneficiary regardless of legal form. The entire purpose of VIE consolidation guidance is to look through legal structure to economic substance.",
  "ExplanationWrongC": "Choice C (majority equity ownership) applies the voting-interest model, not the VIE model. VIEs are consolidated based on primary-beneficiary analysis — power and loss exposure — not on an equity percentage threshold. A VIE can be consolidated with far less than 50% equity if the primary-beneficiary test is met.",
  "ExplanationWrongD": "",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.461 cash-flow-earnings-quality",
  "QuestionID": "P2-A-461",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-461-cash-flow-earnings-quality",
  "Stem": "Priya Ramaswamy is comparing two companies for Flash Manufacturing's investor report. Company A reports net income of $5,000,000 and operating cash flow of $5,400,000. Company B reports net income of $5,000,000 and operating cash flow of $3,000,000. Which company has higher earnings quality, and why?",
  "Choices": {
    "A": "Company A, because its operating cash flow exceeds net income, indicating earnings are cash-backed.",
    "B": "Company B, because lower cash flow means more conservative accounting.",
    "C": "Company A, because higher cash flow always means higher net income.",
    "D": "They have identical earnings quality because net income is the same."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Earnings quality is often gauged by the relationship between net income and operating cash flow. When operating cash flow exceeds net income, the earnings are more than fully backed by cash — a sign of high quality, since the reported profit has been converted to cash. Company A's operating cash flow of $5,400,000 exceeds its $5,000,000 net income, indicating that accruals added rather than consumed cash and the earnings are cash-supported. Company B's operating cash flow of $3,000,000 against $5,000,000 of net income means $2,000,000 of reported earnings is tied up in accruals (e.g., uncollected receivables) that have not converted to cash, lowering the quality of its earnings. The comparison is a standard earnings-quality screen.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (Company B more conservative) misinterprets the signal. Lower cash flow relative to income does not indicate conservatism; it indicates that a portion of reported earnings is supported by accruals rather than cash, which is a quality concern. Conservatism would be evidenced by reserving practices, not by a cash-flow gap.",
  "ExplanationWrongC": "Choice C (higher cash flow means higher net income) confuses the direction of causation. Cash flow and net income are related but distinct measures; a firm can have high operating cash flow with moderate income (e.g., large depreciation add-backs) or vice versa. Company A's quality advantage comes from cash backing earnings, not from cash flow mechanically raising income.",
  "ExplanationWrongD": "Choice D (identical because net income is the same) ignores the cash-flow dimension. Identical net income with materially different operating cash flow is precisely the situation where earnings quality differs: the same reported profit can be backed by very different amounts of cash, and the cash-backed version is higher quality.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.462 restructuring-charge-analysis",
  "QuestionID": "P2-A-462",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-462-restructuring-charge-analysis",
  "Stem": "Maya Caldwell is evaluating whether Flash Manufacturing's $6,000,000 restructuring charge should affect the company's credit assessment. Flash plans to close two plants and consolidate operations. Which analytical treatment is most appropriate?",
  "Choices": {
    "A": "Add the charge back to operating income when evaluating ongoing earning power.",
    "B": "Treat the charge as a recurring operating expense.",
    "C": "Ignore the charge entirely because it is noncash.",
    "D": "Subtract the charge twice to be conservative."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "A restructuring charge is a non-recurring, discrete expense associated with a one-time reorganization. For evaluating ongoing earning power — the level of earnings the firm can sustain — the charge should be added back to operating income, treating it as a non-recurring item. This gives a cleaner measure of Flash's recurring profitability. However, the charge is NOT ignored for all purposes: it represents a real cash outflow (severance, plant closure costs) that reduces current-year cash flow, and it may signal future efficiencies. The analytical treatment is to separate the one-time charge from core earnings for forecasting while recognizing its cash effect in liquidity analysis. Maya should present both the reported figure (with the charge) and the adjusted figure (excluding it).",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (recurring operating expense) misclassifies the charge. Restructuring is a one-time reorganization event; if Flash restructures every year, the pattern would warrant scrutiny, but a discrete plant-closure charge is not part of recurring operating cost structure. Including it as recurring distorts the earnings base.",
  "ExplanationWrongC": "Choice C (ignore entirely because noncash) is inaccurate on two counts. The charge is not entirely noncash — severance and plant closure involve cash outlays — and 'ignoring' a charge that reduces reported income misleads the analysis. The correct treatment is to adjust for the one-time nature while acknowledging the cash effect.",
  "ExplanationWrongD": "Choice D (subtract twice) has no analytical basis. Double-counting the charge would overstate its impact on earnings and produce a distorted measure. The charge is counted once: included in reported income and excluded (added back) from the adjusted recurring-earnings base.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.463 vat-joint-venture",
  "QuestionID": "P2-A-463",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-463-vat-joint-venture",
  "Stem": "Adaeze Onuorah is evaluating Flash Manufacturing's 40% ownership of a joint venture for the balance-sheet presentation. Flash has significant influence over the joint venture's operating and financial policies. Under ASC 323, how should Flash account for the investment?",
  "Choices": {
    "A": "Consolidate the joint venture's full assets and liabilities.",
    "B": "Use the equity method, recognizing Flash's share of the venture's income.",
    "C": "Carry the investment at fair value with no income recognition.",
    "D": "Record only dividends received as income."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Under ASC 323, an investor with significant influence over an investee — generally presumed at ownership of 20% to 50% — accounts for the investment using the equity method. The investment is initially recorded at cost and subsequently adjusted for the investor's share of the investee's income or loss and reduced by dividends received. Flash's 40% ownership with significant influence qualifies for the equity method: Flash recognizes its 40% share of the joint venture's net income as investment income, increasing the carrying amount of the investment, and dividends received reduce the carrying amount. The equity method reflects economic substance: Flash shares in the venture's results rather than merely recording distributions.",
  "ExplanationWrongA": "Choice A (full consolidation) applies only when the investor has control, generally ownership of more than 50% of voting stock. A 40% interest with significant influence but no control is not consolidated; consolidation would inappropriately combine the venture's full results with Flash's.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (fair value, no income recognition) applies to investments without significant influence (generally under 20%), which are accounted for at fair value with unrealized gains/losses in other comprehensive income for available-for-sale securities. Significant influence at 40% requires the equity method, not fair-value-only accounting.",
  "ExplanationWrongD": "Choice D (dividends only as income) is the cost-method approach used when the investor lacks significant influence. Under the equity method, Flash recognizes its share of the venture's earnings, not just dividends; recording only dividends would understate investment income and the carrying value.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "confusing equity method with consolidation",
  "Authorities": [
    "ASC 323"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "earnings-quality-obs",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.464 substance-over-form",
  "QuestionID": "P2-A-464",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-464-substance-over-form",
  "Stem": "Lena Fischer is analyzing a 'sale' of Flash Manufacturing's receivables to a bank with full recourse. Under the arrangement, Flash receives cash now but remains liable if the receivables are not collected. Which statement best describes the appropriate analytical treatment?",
  "Choices": {
    "A": "The transaction is a genuine sale; the receivables and related risk are removed from Flash's balance sheet.",
    "B": "The transaction is economically a secured borrowing; the receivables and related liability should remain on Flash's balance sheet.",
    "C": "The transaction is a sale for legal purposes, so it is a sale for financial reporting purposes.",
    "D": "The transaction has no effect on Flash's financial position."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Under the substance-over-form principle and ASC 860, a transfer of receivables with full recourse does not qualify as a true sale for financial reporting purposes if Flash retains substantially all of the risks and rewards of ownership. With full recourse, Flash remains liable for uncollected receivables, meaning it retains the credit risk. The transaction is economically a secured borrowing: Flash received cash and pledged the receivables as collateral. The receivables remain on Flash's balance sheet, and a liability is recorded for the cash received. For credit analysis, Lena should treat the arrangement as debt, not as a removal of assets — the 'sale' does not improve Flash's true leverage or liquidity position.",
  "ExplanationWrongA": "Choice A (genuine sale) ignores the recourse provision. A true sale requires the transferor to surrender control and substantially all risks and rewards. Full recourse means Flash keeps the credit risk, defeating the sale treatment; the arrangement is a secured borrowing in substance.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (legal sale = accounting sale) conflates legal form with economic substance. Financial reporting looks through legal form to substance: even if the documents call it a sale, the retention of risk through recourse means the accounting treatment must reflect a borrowing.",
  "ExplanationWrongD": "Choice D (no effect) is incorrect. Flash received cash and incurred an obligation to repay if collections fall short; the transaction changes Flash's financial position by converting receivables into cash plus a liability, which affects leverage and liquidity measures.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.465 operating-leverage-dupont",
  "QuestionID": "P2-A-465",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-465-operating-leverage-dupont",
  "Stem": "Adaeze Onuorah is briefing the board on the interaction between Flash Manufacturing's operating leverage and its DuPont decomposition. Flash has high fixed production costs and a low net profit margin. Which statement correctly characterizes the interaction?",
  "Choices": {
    "A": "High operating leverage has no effect on the DuPont components.",
    "B": "High operating leverage amplifies the sensitivity of the net profit margin to sales changes, making margin a volatile DuPont component.",
    "C": "High operating leverage increases the equity multiplier.",
    "D": "High operating leverage permanently raises the asset turnover."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Operating leverage — the proportion of fixed costs in the cost structure — determines how sensitive operating income is to changes in sales. In the DuPont framework, the net profit margin (net income / sales) is the component most directly affected: with high fixed costs, a given percentage change in sales produces a larger percentage change in net income, so the margin swings more widely across the business cycle. This makes the margin a volatile component of Flash's ROE decomposition, which is material for forecasting and risk analysis. The other DuPont components are affected differently: asset turnover reflects capital intensity, and the equity multiplier reflects financing structure — neither is driven by operating leverage. Adaeze's briefing should note that Flash's ROE variability is concentrated in the margin component due to operating leverage.",
  "ExplanationWrongA": "Choice A (no effect) is false. The net profit margin component embeds the cost structure; operating leverage directly governs how the margin responds to volume changes. Operating leverage is a primary driver of margin volatility within the DuPont identity.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (increases equity multiplier) confuses operating with financial leverage. The equity multiplier is determined by the financing structure (assets relative to equity, i.e., debt usage), not by the fixed-vs-variable cost structure. Operating leverage affects the income statement; the equity multiplier reflects the balance sheet.",
  "ExplanationWrongD": "Choice D (permanently raises asset turnover) confuses cost structure with asset efficiency. Asset turnover measures sales per dollar of assets, a function of capital intensity and efficiency. High fixed costs do not mechanically change the relationship between sales and assets.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.466 comprehensive-ratio-decision",
  "QuestionID": "P2-A-466",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-466-comprehensive-ratio-decision",
  "Stem": "Lena Fischer must recommend whether Flash Manufacturing's debt covenant — a minimum current ratio of 1.5 — is likely to be met next quarter. Flash currently has a current ratio of 1.9. Management plans to use short-term debt to fund a $2,000,000 increase in inventory. What is the effect on the current ratio, and will the covenant be met?",
  "Choices": {
    "A": "Ratio rises to 2.4; covenant met.",
    "B": "Ratio falls to approximately 1.6; covenant met.",
    "C": "Ratio falls to 1.0; covenant breached.",
    "D": "Ratio is unchanged; covenant met."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Funding inventory with short-term debt increases both current assets (inventory) and current liabilities (short-term debt) by $2,000,000. Since the current ratio exceeds 1.0, equal absolute increases in numerator and denominator pull the ratio toward 1.0. Start: CA = 1.9 × CL, so with CL = X, CA = 1.9X. After the transaction: CA = 1.9X + 2,000,000, CL = X + 2,000,000. If current liabilities were $4,000,000 (CA = $7,600,000, ratio 1.9), after: CA = $9,600,000, CL = $6,000,000, ratio = 1.6. Recomputed independently: 9,600,000 / 6,000,000 = 1.60. The ratio falls toward 1.0 but remains above the 1.5 covenant floor, so the covenant is met. The decline from 1.9 to 1.6 reflects the standard dilution effect of equal-dollar increases to both sides of a ratio above 1.",
  "ExplanationWrongA": "Choice A (rises to 2.4) reverses the direction. Equal increases to both sides of a ratio above 1.0 compress the ratio; the current ratio falls, not rises. Adding $2,000,000 to both numerator and denominator cannot raise a 1.9 ratio.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (falls to 1.0, breached) overstates the decline. The ratio falls toward 1.0 but does not reach it unless the increase is enormous relative to the base. With the given figures, the ratio settles near 1.6, above the covenant floor, so the covenant is not breached.",
  "ExplanationWrongD": "Choice D (unchanged) is false. The current ratio is a ratio, not a difference: equal absolute additions change the quotient whenever the starting ratio differs from 1.0. Working capital (the difference) is unchanged, but the ratio itself falls.",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.467 operating-cash-flow-reconcil",
  "QuestionID": "P2-A-467",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-467-operating-cash-flow-reconcil",
  "Stem": "Priya Ramaswamy is reconciling Flash Manufacturing's net income to operating cash flow for the cash-flow analysis. Flash's net income is $5,000,000, depreciation is $800,000, accounts receivable increased by $300,000, and inventory decreased by $200,000. What is Flash's operating cash flow under the indirect method?",
  "Choices": {
    "A": "$6,300,000",
    "B": "$4,700,000",
    "C": "$5,100,000",
    "D": "$5,700,000"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The indirect method reconciles net income to operating cash flow by adjusting for noncash items and changes in working capital. Depreciation is a noncash expense: add it back (+$800,000). An increase in accounts receivable means cash collections lagged sales: subtract (+$300,000 decrease in cash flow, so −$300,000). A decrease in inventory means more inventory was sold than purchased: add (+$200,000). Operating cash flow = $5,000,000 + $800,000 − $300,000 + $200,000 = $5,700,000. Recomputed independently: 5,000,000 + 800,000 = 5,800,000; 5,800,000 − 300,000 = 5,500,000; 5,500,000 + 200,000 = 5,700,000. The reconciliation shows how accrual-based income converts to cash.",
  "ExplanationWrongA": "Choice D ($6,300,000) adds the receivables increase instead of subtracting it: $5,000,000 + $800,000 + $300,000 + $200,000 = $6,300,000. An increase in accounts receivable consumes cash (sales on credit not yet collected); it must be subtracted, not added, in the indirect reconciliation.",
  "ExplanationWrongB": "Choice B ($4,700,000) subtracts the depreciation add-back: $5,000,000 − $800,000 − $300,000 + $200,000 = $4,100,000, or mis-signs the inventory change. Depreciation is added back because it is noncash; subtracting it double-counts the expense reduction in cash.",
  "ExplanationWrongC": "Choice C ($5,100,000) ignores the working-capital adjustments: $5,000,000 + $800,000 = $5,800,000 with only a partial adjustment. Both the receivables increase (subtract) and inventory decrease (add) affect cash; omitting or mis-signing either misstates the cash flow.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.468 free-cash-flow",
  "QuestionID": "P2-A-468",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-468-free-cash-flow",
  "Stem": "Maya Caldwell is computing Flash Manufacturing's free cash flow for the capital-allocation review. Flash's operating cash flow is $12,000,000 and capital expenditures are $3,500,000. What is Flash's free cash flow?",
  "Choices": {
    "A": "$12,000,000",
    "B": "$15,500,000",
    "C": "$3,500,000",
    "D": "$8,500,000"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Free cash flow measures the cash a firm generates after funding the capital expenditures required to maintain and grow its asset base. It is computed as operating cash flow minus capital expenditures: $12,000,000 − $3,500,000 = $8,500,000. Recomputed independently: 12,000,000 − 3,500,000 = 8,500,000. Free cash flow is the cash available for discretionary purposes — dividends, debt reduction, acquisitions, or share repurchases. For Maya's capital-allocation review, the $8,500,000 represents the cash Flash can distribute or reinvest after sustaining its operations. A persistent negative free cash flow would signal that operating cash flow is insufficient to fund required investment.",
  "ExplanationWrongA": "Choice D ($12,000,000) ignores capital expenditures entirely, equating free cash flow with operating cash flow. Free cash flow specifically deducts the investment required to sustain the business; without the deduction, the measure overstates the cash available for discretionary distribution.",
  "ExplanationWrongB": "Choice B ($15,500,000) adds capital expenditures to operating cash flow instead of subtracting them. Capital expenditures are cash OUTFLOWS for investment; adding them treats investment spending as cash generation, which is the opposite of the actual cash effect.",
  "ExplanationWrongC": "Choice C ($3,500,000) reports capital expenditures alone, confusing the investment outflow with the free-cash-flow measure. Free cash flow is the residual after capex, not the capex amount itself.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.469 cash-flow-classification",
  "QuestionID": "P2-A-469",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-469-cash-flow-classification",
  "Stem": "Priya Ramaswamy is preparing Flash Manufacturing's statement of cash flows. Flash received $400,000 in interest on its investments and paid $600,000 in interest on its debt. Under US GAAP, how should these cash flows be classified?",
  "Choices": {
    "A": "Both interest received and interest paid are classified as operating activities.",
    "B": "Interest received is investing; interest paid is financing.",
    "C": "Interest received is operating; interest paid is financing.",
    "D": "Both are classified as financing activities."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Under US GAAP (ASC 230), interest received and interest paid are both classified as operating activities, because they relate to the normal operating activities of borrowing and lending. This is a distinctive US GAAP rule: interest is treated as an operating cash flow, consistent with its treatment in computing net income. By contrast, under IFRS, interest paid may be classified as operating or financing and interest received as operating or investing, at the entity's election. For a US GAAP preparer like Flash, both the $400,000 interest received and the $600,000 interest paid are presented within cash flows from operating activities, and the $200,000 net interest cost is embedded in the operating section.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (received=investing, paid=financing) reflects the IFRS flexibility, not the US GAAP default. US GAAP classifies BOTH as operating; the split treatment is permissible under IFRS but is not the required US GAAP presentation.",
  "ExplanationWrongC": "Choice C (received=operating, paid=financing) is a common misconception. Under US GAAP, interest PAID is also operating, not financing. (Dividends paid, by contrast, may be classified as financing under US GAAP.) Interest paid is not moved to financing simply because it relates to debt.",
  "ExplanationWrongD": "Choice D (both financing) is incorrect. Interest relates to income-generating activities and is classified as operating under US GAAP. Financing activities are reserved for principal amounts — borrowing proceeds and debt repayments — not the interest cost on the debt.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.470 accrual-cash-mismatch",
  "QuestionID": "P2-A-470",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-470-accrual-cash-mismatch",
  "Stem": "Lena Fischer is explaining to a junior analyst why Flash Manufacturing's net income and operating cash flow differ. Which statement best explains the fundamental reason for the difference?",
  "Choices": {
    "A": "Net income is measured on a cash basis while operating cash flow is on an accrual basis.",
    "B": "Net income uses accrual accounting, which recognizes revenues and expenses when earned or incurred, while operating cash flow records only actual cash receipts and payments.",
    "C": "The difference is always caused by accounting errors.",
    "D": "The two measures are identical by definition and should never differ."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Net income is prepared on the accrual basis: revenues are recognized when earned (ASC 606) and expenses when incurred (matching principle), regardless of when cash changes hands. Operating cash flow, by contrast, records only actual cash receipts and payments from operating activities. The differences arise from timing and noncash items: sales on credit create revenue (and income) before cash is collected; depreciation and amortization reduce income but involve no cash outflow; prepaid expenses and deferred revenue shift the timing of cash relative to expense or revenue recognition. These accrual mechanics are the legitimate, expected source of the difference between net income and operating cash flow. Understanding the reconciliation (the indirect method) is central to earnings-quality analysis.",
  "ExplanationWrongA": "Choice A (net income is cash-based) inverts the definitions. Net income is the accrual-basis measure; operating cash flow is the cash-basis measure. The statement has the two reversed.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (always accounting errors) is false. Timing differences between accrual income and cash flow are normal and expected — revenue on credit, depreciation, working-capital changes. A difference is not evidence of error; persistent unexplained or extreme gaps warrant investigation, but the gap itself is standard.",
  "ExplanationWrongD": "Choice D (identical by definition) is false. Accrual accounting and cash accounting measure different things and will generally differ. The statement of cash flows exists precisely to reconcile the two and explain the difference.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "batch3-mixed",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
