var pack_p2_a_part7 = [
{
  "Authorities": [
    "ASC 842 — Leases",
    "ASC 606 — Revenue from Contracts with Customers"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Recommend declining the loan. The year-end inventory manipulation, customer concentration risk with an expiring contract, off-balance-sheet lease obligations, aggressive revenue recognition, and industry-relative over-leverage collectively indicate that the reported covenant ratios overstate Northwind's credit quality and create an unacceptable risk of default.",
    "B": "Recommend approving the loan at standard terms. All covenant ratios are objectively satisfied, and qualitative concerns are inherently subjective — a sound credit decision must be based on verifiable quantitative data rather than speculative assessments of management behavior or future events.",
    "C": "Recommend approving the loan with a covenant amendment requiring monthly ratio reporting. More frequent monitoring will detect any deterioration in Northwind's financial condition before it becomes material to the bank's exposure, addressing the qualitative concerns without denying credit to a covenant-compliant borrower.",
    "D": "Recommend approving the loan at a 200-basis-point rate premium to compensate for customer concentration risk. The other qualitative factors fall within the normal range of business judgment and do not warrant declining a borrower that meets all quantitative covenant thresholds."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Trap: Relying on covenant ratio compliance when multiple qualitative factors indicate the ratios overstate credit quality",
  "CorrectChoice": "A",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "The loan should be declined despite technical covenant compliance. Professional lending standards require analysts to evaluate both the quantitative ratios and the quality of the underlying financial data. Five qualitative factors collectively indicate that Northwind's reported ratios overstate its economic credit quality: (1) year-end inventory manipulation (window dressing) reduces the true current ratio; (2) 40% customer concentration with a six-month contract creates material revenue continuity risk; (3) $3.8 million in off-balance-sheet lease obligations would increase the true debt-to-equity ratio substantially; (4) $900,000 in accelerated revenue recognition reduces earnings quality; and (5) Northwind's 1.8 debt-to-equity ratio exceeds the 1.0 industry median by 80%. Taken individually, no single factor definitively warrants declining the loan, but the convergence of five distinct qualitative red flags creates an unacceptable risk profile. The credit analyst's professional obligation is to assess credit risk based on the substance of the borrower's financial condition, not merely its form.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Treating quantitative covenant compliance as dispositive ignores the fundamental limitations of ratio analysis. Financial ratios can be manipulated through year-end transactions, are calculated using historical data that may not reflect future conditions, do not capture off-balance-sheet obligations, and are sensitive to accounting policy choices. Professional lending standards require evaluating the quality of reported financial data — not merely whether ratios exceed thresholds. Approving a loan based solely on covenant compliance when multiple qualitative indicators suggest the ratios overstate credit quality violates the principle that credit decisions must assess the borrower's capacity to repay.",
  "ExplanationWrongC": "Monthly ratio reporting does not address the structural nature of the qualitative concerns. Year-end window dressing will recur at each reporting date; off-balance-sheet lease obligations will remain invisible in covenant calculations regardless of reporting frequency; and customer concentration risk with a six-month contract horizon cannot be mitigated by more frequent monitoring — the loss event, if it occurs, will be sudden and binary. More frequent reporting increases detection speed after deterioration occurs but does nothing to address the root causes that make the ratios unreliable indicators of credit quality.",
  "ExplanationWrongD": "Adjusting the interest rate to compensate for customer concentration risk addresses only one of five identified qualitative concerns. A 200-basis-point premium compensates for incremental expected loss but does not eliminate the fundamental credit quality issues. Risk-based pricing is appropriate for borrowers with genuine but quantifiable incremental risk — not for borrowers where multiple qualitative red flags collectively indicate that reported financial data may not faithfully represent the borrower's economic condition. Prudent underwriting requires declining credit when the information quality itself is in question.",
  "FormulaReference": null,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-030",
  "Section": "A",
  "Stem": "Northwind Logistics, a regional freight carrier, has applied for a $5 million term loan from First Commercial Bank. Credit analyst Michael Torres reviews the application. Northwind's financial ratios all satisfy the bank's loan covenants: current ratio 2.1 (covenant ≥1.5), debt-to-equity 1.8 (covenant ≤2.5), and fixed charge coverage 1.6 (covenant ≥1.25). However, Michael's investigation reveals several qualitative concerns: Northwind liquidated $1.2 million of inventory in the final week of the fiscal year and repurchased it the following week; 40% of revenue derives from a single customer whose contract expires in six months; $3.8 million in equipment leases are structured as service agreements to avoid balance sheet recognition; the company accelerated $900,000 of revenue recognition under percentage-of-completion accounting in the most recent year; and industry peers maintain an average debt-to-equity ratio of 1.0. What recommendation should Michael make to the credit committee?",
  "Topic": "A.030 integrating multiple ratio limitations in a lending decision with qualitative risk factors",
  "UniqueConceptKey": "A-030-integrating-multiple-ratio-limitations-in-a-lending-decision-wit",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots ≥75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified by multi-factor evaluative judgment integrating ratio limitations, qualitative risks, and professional lending standards",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230-10-45-25"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "0.67",
    "B": "0.30",
    "C": "0.80",
    "D": "1.50"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using total liabilities instead of current liabilities as the denominator, which confuses the operating cash flow ratio (a liquidity measure) with the cash flow to debt ratio (a solvency measure)",
  "CorrectChoice": "D",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The correct answer is 1.50. Operating cash flow ratio = Cash flow from operations / Current liabilities = $480,000 / $320,000 = 1.50. Under ASC 230-10-45-25, operating cash flows include all transactions not classified as investing or financing activities. A ratio above 1.0 indicates Crestview generated sufficient operating cash to cover its current obligations for the year. A common error is dividing by total liabilities rather than current liabilities, which would understate the company's short-term cash coverage.",
  "ExplanationWrongA": "Option A (0.67) inverts the ratio by dividing current liabilities by operating cash flow ($320,000 / $480,000). This error treats the ratio as a coverage measure in reverse, but the operating cash flow ratio measures cash generated per dollar of current liability, placing CFO in the numerator.",
  "ExplanationWrongB": "Option B (0.30) divides operating cash flow by total liabilities ($480,000 / $1,600,000) rather than current liabilities. The operating cash flow ratio specifically uses current liabilities as the denominator because it assesses short-term liquidity — not long-term solvency, which is measured by the cash flow to debt ratio.",
  "ExplanationWrongC": "Option C (0.80) substitutes net income ($256,000) for operating cash flow in the numerator ($256,000 / $320,000). Operating cash flow differs from accrual-basis net income because it excludes non-cash items such as depreciation and changes in working capital accounts, making CFO the proper numerator for this liquidity ratio.",
  "ExplanationWrongD": "",
  "FormulaReference": "Operating Cash Flow Ratio",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-031",
  "Section": "A",
  "Stem": "Crestview Manufacturing Inc. reported net cash provided by operating activities of $480,000 for the year ended December 31, 2025. Crestview's current liabilities at year-end totaled $320,000, and total liabilities were $1,600,000. Net income for the year was $256,000. Calculate Crestview's operating cash flow ratio.",
  "Topic": "A.031 operating cash flow ratio computation",
  "UniqueConceptKey": "A-031-operating-cash-flow-ratio-computation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots ≥50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230-10-45-24"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$500,000",
    "B": "$1,200,000",
    "C": "$370,000",
    "D": "$850,000"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Adding capital expenditures to operating cash flow instead of subtracting them, treating capex as a source rather than a use of cash",
  "CorrectChoice": "A",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The correct answer is $500,000. Free cash flow = Operating cash flow - Capital expenditures = $850,000 - $350,000 = $500,000. Under ASC 230-10-45-24, capital expenditures are reported as cash outflows from investing activities. Free cash flow represents the cash available to the company after maintaining its productive capacity. Baxter's $500,000 in free cash flow is available for debt reduction, dividend payments, share repurchases, or strategic acquisitions. A common error is adding capital expenditures rather than subtracting them.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B ($1,200,000) results from adding capital expenditures to operating cash flow ($850,000 + $350,000) rather than subtracting them. This error treats capex as a cash inflow rather than recognizing that capital expenditures are cash outflows used to acquire or upgrade long-term assets and must be deducted to arrive at free cash flow.",
  "ExplanationWrongC": "Option C ($370,000) substitutes net income for operating cash flow in the formula ($720,000 - $350,000). Net income includes non-cash expenses such as depreciation and excludes changes in working capital, making it an unreliable starting point for measuring the cash actually available for discretionary purposes after capital investment.",
  "ExplanationWrongD": "Option D ($850,000) omits the capital expenditure subtraction entirely, treating operating cash flow itself as free cash flow. This approach overstates available cash because it fails to account for the reinvestment required to maintain productive capacity, which is a fundamental component of the free cash flow calculation.",
  "FormulaReference": "Free Cash Flow",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-032",
  "Section": "A",
  "Stem": "Baxter Industries reported net cash provided by operating activities of $850,000 for fiscal year 2025. The company invested $350,000 in new manufacturing equipment during the year, which was classified as capital expenditures in the investing activities section of the statement of cash flows. Net income for the year was $720,000. Calculate Baxter's free cash flow.",
  "Topic": "A.032 free cash flow calculation",
  "UniqueConceptKey": "A-032-free-cash-flow-calculation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots ≥50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230-10-45-25"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "1.25",
    "B": "4.00",
    "C": "0.25",
    "D": "0.19"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using current liabilities instead of total debt as the denominator, confusing a liquidity ratio with a solvency ratio",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The correct answer is 0.25. Cash flow to debt ratio = Operating cash flow / Total debt = $600,000 / $2,400,000 = 0.25. Under ASC 230-10-45-25, operating cash flow is the numerator for this solvency ratio because it reflects the company's ability to generate cash from core operations. A ratio of 0.25 indicates Sanderson generates $0.25 in operating cash for each dollar of total debt, suggesting moderate capacity to service debt obligations from internally generated cash flows. A common error is dividing by current liabilities rather than total debt.",
  "ExplanationWrongA": "Option A (1.25) divides operating cash flow by current liabilities ($600,000 / $480,000) rather than total debt. While this calculation yields a liquidity measure similar to the operating cash flow ratio, the cash flow to debt ratio specifically uses total debt as the denominator to assess long-term solvency, not short-term liquidity.",
  "ExplanationWrongB": "Option B (4.00) inverts the ratio by dividing total debt by operating cash flow ($2,400,000 / $600,000). This error reverses the relationship and produces a figure that represents how many years of current operating cash flow would be needed to repay total debt, rather than the standard cash flow to debt ratio.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D (0.19) substitutes net income for operating cash flow in the numerator ($450,000 / $2,400,000). Net income includes non-cash accruals and does not fully reflect cash available to service debt. Operating cash flow is the appropriate measure for this ratio because it captures actual cash generated during the period.",
  "FormulaReference": "Cash Flow to Debt",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-033",
  "Section": "A",
  "Stem": "Sanderson Energy Partners reported net cash provided by operating activities of $600,000 for the year ended December 31, 2025. The company's balance sheet showed total debt of $2,400,000, consisting of long-term notes payable and the current portion of long-term debt. Current liabilities at year-end were $480,000, and net income was $450,000. Calculate Sanderson's cash flow to debt ratio.",
  "Topic": "A.033 cash flow to debt ratio",
  "UniqueConceptKey": "A-033-cash-flow-to-debt-ratio",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots ≥50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10-45"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "100 days",
    "B": "5 days",
    "C": "15 days",
    "D": "50 days"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Adding days payable outstanding instead of subtracting it, which treats supplier financing as an extension of the cycle rather than a reduction",
  "CorrectChoice": "D",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The correct answer is 50 days. Cash conversion cycle = DIO + DSO - DPO = 45 + 30 - 25 = 50 days. Under ASC 205-10-45, financial statements should be presented to facilitate analysis of a company's operating cycle. The cash conversion cycle measures the time between cash outlay for inventory purchases and cash collection from customer sales. Northpoint's 50-day cycle means the company must finance its operations for approximately seven weeks from inventory purchase through customer payment. A common error is adding DPO rather than subtracting it.",
  "ExplanationWrongA": "Option A (100 days) adds all three components together (45 + 30 + 25 = 100) rather than subtracting DPO. Days payable outstanding represents the period the company takes to pay its suppliers, which is a source of financing that reduces — not increases — the cash conversion cycle. Adding DPO treats supplier credit as if it extends rather than shortens the cycle.",
  "ExplanationWrongB": "Option B (5 days) calculates DSO minus DPO only (30 - 25 = 5), ignoring the inventory holding period entirely. A complete cash conversion cycle must include DIO because the cycle begins when cash is used to acquire inventory. Omitting inventory holding days understates the true time required to convert cash outflows into cash inflows.",
  "ExplanationWrongC": "Option C (15 days) subtracts DSO from DIO (45 - 30 = 15) without accounting for DPO. This error reverses the sign on DSO, treating customer receivables as if they shorten the cycle when in fact days sales outstanding represents the waiting period for customer payments and extends the cash conversion cycle.",
  "ExplanationWrongD": "",
  "FormulaReference": "Cash Conversion Cycle",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-034",
  "Section": "A",
  "Stem": "Northpoint Retail Inc. operates a chain of specialty apparel stores. For the fiscal year 2025, the company reported days inventory outstanding (DIO) of 45 days, days sales outstanding (DSO) of 30 days, and days payable outstanding (DPO) of 25 days. Calculate Northpoint's cash conversion cycle.",
  "Topic": "A.034 cash conversion cycle",
  "UniqueConceptKey": "A-034-cash-conversion-cycle",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots ≥50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230-10-45-28"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "0.83",
    "B": "1.32",
    "C": "1.20",
    "D": "1.08"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Inverting the ratio by dividing net income by operating cash flow, or double-counting the depreciation add-back that is already included in CFO",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The correct answer is 1.20. Cash flow to net income ratio = Operating cash flow / Net income = $420,000 / $350,000 = 1.20. Under ASC 230-10-45-28, the reconciliation of net income to operating cash flow highlights differences between accrual and cash earnings. A ratio above 1.0 indicates Mercer's earnings quality is strong — operating cash flows exceed reported net income, suggesting accrual estimates are conservative and net income is fully supported by actual cash generation. A common error is inverting the ratio by placing net income in the numerator.",
  "ExplanationWrongA": "Option A (0.83) inverts the ratio by dividing net income by operating cash flow ($350,000 / $420,000). The correct ratio places operating cash flow in the numerator because it measures how many dollars of cash earnings support each dollar of accrual-basis net income, not the reverse.",
  "ExplanationWrongB": "Option B (1.32) results from adding the depreciation add-back to operating cash flow a second time [($420,000 + $42,000) / $350,000]. Operating cash flow already includes the depreciation add-back as part of the indirect method reconciliation from net income. Adding it again double-counts this non-cash item and overstates the numerator, inflating the ratio.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D (1.08) subtracts depreciation from operating cash flow [($420,000 - $42,000) / $350,000]. This error treats depreciation as a cash outflow that reduces operating cash flow, when in fact depreciation is a non-cash expense that has already been added back to net income to arrive at the reported CFO under the indirect method.",
  "FormulaReference": "Cash Flow to Net Income",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-035",
  "Section": "A",
  "Stem": "Mercer Consulting Group reported net income of $350,000 for the year ended December 31, 2025. The statement of cash flows showed net cash provided by operating activities of $420,000, which included $42,000 of depreciation add-back within the reconciliation of net income to operating cash flow. Calculate Mercer's cash flow to net income ratio as a measure of earnings quality.",
  "Topic": "A.035 quality of earnings cash flow vs. accrual income",
  "UniqueConceptKey": "A-035-quality-of-earnings-cash-flow-vs-accrual-income",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots ≥50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230-10-45-25",
    "ASC 260-10-45-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$6.25",
    "B": "$5.75",
    "C": "$5.80",
    "D": "$6.00"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Failing to deduct preferred dividends from operating cash flow, or incorrectly deducting total dividends (including common) instead of only preferred dividends",
  "CorrectChoice": "D",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The correct answer is $6.00. Operating cash flow per share = (CFO - Preferred dividends) / Weighted average common shares outstanding = ($750,000 - $30,000) / 120,000 = $720,000 / 120,000 = $6.00. Under ASC 230-10-45-25, operating cash flows are the numerator for cash-flow-based per-share measures, and per ASC 260-10-45-10, preferred dividends are deducted because those payments are not available to common shareholders. Pennbrook generates $6.00 in operating cash flow for each common share outstanding. A common error is failing to deduct preferred dividends from the numerator.",
  "ExplanationWrongA": "Option A ($6.25) divides the full operating cash flow by shares outstanding without deducting preferred dividends ($750,000 / 120,000). Operating cash flow per share must subtract preferred dividends from CFO because these payments are not available to common shareholders, following the same principle as the basic earnings per share calculation.",
  "ExplanationWrongB": "Option B ($5.75) substitutes net income for operating cash flow in the numerator, then deducts preferred dividends [($720,000 - $30,000) / 120,000]. This ratio specifically uses cash from operations rather than accrual-basis net income because it measures cash-generating capacity on a per-share basis, not accrual earnings.",
  "ExplanationWrongC": "Option C ($5.80) deducts total dividends rather than only preferred dividends [($750,000 - $54,000) / 120,000]. Under ASC 260-10-45-10, only preferred dividends are subtracted from the numerator because common dividends are a discretionary distribution of available earnings, not a prior claim that reduces the amount attributable to common shareholders.",
  "ExplanationWrongD": "",
  "FormulaReference": "Operating Cash Flow per Share",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-036",
  "Section": "A",
  "Stem": "Pennbrook Industries reported net cash provided by operating activities of $750,000 for the year ended December 31, 2025. The company paid preferred dividends of $30,000 and common dividends of $24,000 during the year. Net income was $720,000, and Pennbrook had 120,000 weighted average common shares outstanding. Calculate operating cash flow per share.",
  "Topic": "A.036 operating cash flow per share",
  "UniqueConceptKey": "A-036-operating-cash-flow-per-share",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots ≥50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 225-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "60.0%",
    "B": "66.7%",
    "C": "40.0%",
    "D": "25.0%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Confusing gross margin (profit / revenue) with markup (profit / cost) — candidates divide gross profit by COGS rather than by revenue, producing an inflated percentage.",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Gross margin = (Revenue - COGS) / Revenue = ($600,000 - $360,000) / $600,000 = $240,000 / $600,000 = 40.0%. Under ASC 225-10, gross margin measures the percentage of revenue retained after covering direct production costs. Landmark retains $0.40 of every revenue dollar after paying for the goods it sold. A common error is to divide gross profit by COGS instead of revenue, which produces a markup percentage rather than a margin.",
  "ExplanationWrongA": "Option A is incorrect because it computes COGS / Revenue ($360,000 / $600,000 = 60.0%), which is the cost-of-goods-sold percentage, not the gross margin. A candidate reaching this result has inverted the margin concept — the margin is what remains after covering COGS, not the proportion consumed by COGS. The correct approach subtracts COGS from revenue and divides the result by revenue.",
  "ExplanationWrongB": "Option B is incorrect because it divides gross profit by COGS ($240,000 / $360,000 = 66.7%), computing the markup percentage on cost rather than the margin on revenue. Markup and margin are distinct concepts — markup expresses profit relative to cost, while margin expresses profit relative to the selling price. The correct gross margin formula divides gross profit by revenue.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D is incorrect because it divides gross profit by the sum of revenue and COGS ($240,000 / $960,000 = 25.0%). This error treats the total cost base (revenue + COGS) as the denominator, which has no basis in GAAP margin computation. The denominator in gross margin is revenue only, representing the top-line figure against which profitability is measured.",
  "FormulaReference": "Gross Margin = (Revenue - COGS) / Revenue",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-037",
  "Section": "A",
  "Stem": "Landmark Industries reported revenue of $600,000 and cost of goods sold of $360,000 for the fiscal year. Compute Landmark's gross margin percentage.",
  "Topic": "A.037 Gross margin trend analysis",
  "UniqueConceptKey": "A-037-gross-margin-trend-analysis",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 225-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "20.0%",
    "B": "25.0%",
    "C": "40.0%",
    "D": "13.3%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Omitting depreciation from operating expenses — candidates treat depreciation as a non-operating charge, but under ASC 225-10 depreciation of productive assets is a core operating cost.",
  "CorrectChoice": "A",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Operating income = Revenue - COGS - Selling & Admin - Depreciation = $1,200,000 - $720,000 - $180,000 - $60,000 = $240,000. Operating margin = Operating income / Revenue = $240,000 / $1,200,000 = 20.0%. Under ASC 225-10, operating margin isolates the profitability of core business operations by excluding financing and tax effects. Novus generates $0.20 of operating profit per revenue dollar. A common error is to omit depreciation from operating expenses, overstating operating income.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B is incorrect because it omits depreciation expense from the computation: ($1,200,000 - $720,000 - $180,000) / $1,200,000 = $300,000 / $1,200,000 = 25.0%. Depreciation is an operating expense under ASC 225-10 because it reflects the systematic allocation of productive asset costs. Excluding depreciation inflates the apparent profitability of operations by 5 percentage points.",
  "ExplanationWrongC": "Option C is incorrect because it computes gross margin instead of operating margin: ($1,200,000 - $720,000) / $1,200,000 = $480,000 / $1,200,000 = 40.0%. Gross margin stops at COGS and ignores selling, administrative, and depreciation expenses. The correct operating margin subtracts all operating costs — including indirect costs — from revenue before dividing.",
  "ExplanationWrongD": "Option D is incorrect because it deducts income tax expense from operating income before computing the margin. The candidate likely subtracted an estimated tax provision of $80,000 from $240,000 operating income and then divided: $160,000 / $1,200,000 = 13.3%. Under ASC 225-10, operating margin is computed above the tax line — taxes are a financing/government cost, not an operating expense.",
  "FormulaReference": "Operating Margin = (Revenue - COGS - Operating Expenses) / Revenue",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-038",
  "Section": "A",
  "Stem": "Novus Technologies reports the following for 2026: Revenue $1,200,000, Cost of Goods Sold $720,000, Selling and Administrative Expenses $180,000, and Depreciation Expense $60,000. Compute Novus's operating margin.",
  "Topic": "A.038 Operating margin computation",
  "UniqueConceptKey": "A-038-operating-margin-computation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 225-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "45.0%",
    "B": "22.5%",
    "C": "20.0%",
    "D": "14.0%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Selecting a margin computed at the wrong income statement level — candidates may use gross margin, operating margin, or pretax margin when net profit margin is requested, because all four percentages look plausible.",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Net income = Revenue - COGS - S&A - Interest - Tax = $2,000,000 - $1,100,000 - $450,000 - $50,000 - $120,000 = $280,000. Net profit margin = Net income / Revenue = $280,000 / $2,000,000 = 14.0%. Under ASC 225-10, net profit margin is the most comprehensive profitability measure on the income statement, reflecting all costs including financing and taxes. Sterling retains $0.14 of profit per revenue dollar after all expenses. A common error is to use operating income or pretax income instead of net income in the numerator.",
  "ExplanationWrongA": "Option A is incorrect because it computes gross margin: ($2,000,000 - $1,100,000) / $2,000,000 = $900,000 / $2,000,000 = 45.0%. Gross margin reflects only the direct cost of goods sold and ignores operating expenses, interest, and taxes. Net profit margin requires the bottom-line net income figure, which incorporates all costs.",
  "ExplanationWrongB": "Option B is incorrect because it computes operating margin: ($2,000,000 - $1,100,000 - $450,000) / $2,000,000 = $450,000 / $2,000,000 = 22.5%. Operating margin stops at operating income and excludes interest and taxes. The candidate likely reached the correct operating income figure but failed to account for below-the-line financing and tax costs when computing the net margin.",
  "ExplanationWrongC": "Option C is incorrect because it computes pretax margin: ($2,000,000 - $1,100,000 - $450,000 - $50,000) / $2,000,000 = $400,000 / $2,000,000 = 20.0%. The candidate correctly deducted interest but stopped before income taxes. Net profit margin must reflect the final net income after all expenses, including the tax provision.",
  "ExplanationWrongD": "",
  "FormulaReference": "Net Profit Margin = Net Income / Revenue",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-039",
  "Section": "A",
  "Stem": "Sterling Manufacturing reported the following for 2026: Net Revenue $2,000,000, Cost of Goods Sold $1,100,000, Selling and Administrative Expenses $450,000, Interest Expense $50,000, and Income Tax Expense $120,000. Compute Sterling's net profit margin.",
  "Topic": "A.039 Net profit margin computation",
  "UniqueConceptKey": "A-039-net-profit-margin-computation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "4.6%",
    "B": "9.75%",
    "C": "14.0%",
    "D": "21.9%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Performing the wrong arithmetic operation on DuPont components — candidates add or divide margin and turnover when the formula requires multiplication. The two drivers are multiplicative, not additive.",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "ROA (DuPont) = Net profit margin x Asset turnover = 8.0% x 1.75 = 14.0%. Under the DuPont framework, ROA decomposes into profitability (how much the company earns per dollar of sales) and efficiency (how many sales dollars are generated per dollar of assets). Ashford's 14.0% ROA means each dollar of assets generates $0.14 of net income, driven by an 8.0% margin and 1.75x turnover. A common error is to divide margin by turnover instead of multiplying.",
  "ExplanationWrongA": "Option A is incorrect because it divides net profit margin by asset turnover: 8.0% / 1.75 = 4.6%. The DuPont formula requires multiplication, not division. A candidate who divides the two components is effectively computing the margin per unit of turnover — a metric with no economic interpretation. The correct ROA is the product of the two DuPont drivers.",
  "ExplanationWrongB": "Option B is incorrect because it adds net profit margin and asset turnover as though turnover were a percentage: 8.0% + 1.75% = 9.75%. Asset turnover is a ratio, not a percentage — adding it to a margin produces a dimensionally meaningless result. The DuPont decomposition requires multiplication because margin and turnover interact multiplicatively to produce ROA.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D is incorrect because it divides asset turnover by net profit margin: 1.75 / 0.08 = 21.875 rounded to 21.9%. This inverts the DuPont relationship entirely, treating turnover as the primary driver and margin as the divisor. The correct DuPont ROA is margin multiplied by turnover — the business earns the margin on every turnover of assets.",
  "FormulaReference": "ROA (DuPont) = Net Profit Margin x Total Asset Turnover",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-040",
  "Section": "A",
  "Stem": "Ashford Corporation's most recent financial statements show a net profit margin of 8.0% and a total asset turnover of 1.75. The DuPont formula for return on assets is net profit margin multiplied by asset turnover. Compute Ashford's return on assets.",
  "Topic": "A.040 Return on assets — DuPont decomposition",
  "UniqueConceptKey": "A-040-return-on-assets-dupont-decomposition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
}
];
