var pack_p2_a_part50 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.431 asset-turnover-margin-interaction",
  "QuestionID": "P2-A-431",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-431-asset-turnover-margin-interaction",
  "Stem": "Priya Ramaswamy is analyzing why Flash Manufacturing's return on assets rose from 8% to 10% even though its net profit margin fell from 6% to 5%. Which explanation is most consistent with the data?",
  "Choices": {
    "A": "The equity multiplier increased while assets stayed constant.",
    "B": "Total asset turnover decreased from 2.00 to 1.25 times.",
    "C": "Total asset turnover increased from 1.33 to 2.00 times.",
    "D": "Sales declined while net income remained constant."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Return on assets equals net profit margin × total asset turnover (ROA = net income / sales × sales / total assets). If ROA rose from 8% to 10% while the margin fell from 6% to 5%, the asset turnover must have risen to compensate. Check: with a 6% margin and 1.33 turnover, ROA = 6% × 1.33 = 8%; with a 5% margin and 2.00 turnover, ROA = 5% × 2.00 = 10%. Recomputed independently: 0.06 × 1.333 = 0.08; 0.05 × 2.0 = 0.10. The DuPont decomposition isolates the driver: Flash is generating more sales per dollar of assets, which more than offsets the thinner margin. This is the correct analytical reading of the interaction between the two components.",
  "ExplanationWrongA": "Choice C (equity multiplier increased) affects return on equity, not return on assets. ROA deliberately excludes financing structure — it uses total assets, not equity — so a change in leverage cannot explain a change in ROA. Confusing ROA with ROE is the classic DuPont error here.",
  "ExplanationWrongB": "Choice B (turnover decreased from 2.00 to 1.25) produces the wrong direction: 5% × 1.25 = 6.25%, below the prior 8%. A falling turnover compounds with a falling margin to push ROA down, not up. The data require the turnover to rise enough to offset the margin decline.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (sales declined while net income stayed constant) would raise the net margin, not lower it: if sales fall and net income is unchanged, net income / sales increases. The stem states the margin fell, so this explanation contradicts the given data.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.432 turnover-ratio-selection",
  "QuestionID": "P2-A-432",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-432-turnover-ratio-selection",
  "Stem": "Maya Caldwell, Flash Manufacturing's treasurer, must choose the ratio that best indicates how efficiently Flash is collecting cash from its credit customers. Which ratio should Maya use?",
  "Choices": {
    "A": "Inventory turnover",
    "B": "Accounts receivable turnover",
    "C": "Accounts payable turnover",
    "D": "Total asset turnover"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Accounts receivable turnover measures how many times per period a firm converts its credit sales into cash: net credit sales divided by average accounts receivable. It directly answers the treasurer's question about collection efficiency from credit customers. The higher the turnover, the shorter the collection period, which reduces the cash conversion cycle and the amount of capital tied up in receivables. Inventory turnover (A) measures how quickly goods are sold, not collected; accounts payable turnover (C) measures how quickly the firm pays its suppliers, not how quickly it collects; and total asset turnover (D) measures overall sales generation per dollar of assets, too broad to isolate customer collection behavior.",
  "ExplanationWrongA": "Choice A (inventory turnover) measures the speed at which inventory is sold and replaced, using COGS and average inventory. Selling inventory does not create cash inflow — collecting the resulting receivable does. A fast inventory turnover with slow collections still leaves cash tied up in receivables, so this ratio does not answer the collection-efficiency question.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (accounts payable turnover) measures how quickly Flash pays its suppliers, using purchases (or COGS) and average accounts payable. This is a financing decision, not a collection decision; it reflects Flash's payment behavior toward vendors, not the collection behavior of its credit customers.",
  "ExplanationWrongD": "Choice D (total asset turnover) measures net sales relative to average total assets, capturing how efficiently all assets generate sales. It aggregates inventory, receivables, and fixed assets into one measure, so it cannot isolate how efficiently Flash collects from credit customers specifically.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Remember",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "activity-efficiency",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.433 Gross Profit Margin Analysis",
  "QuestionID": "P2-A-433",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-433-gross-profit-margin-analysis",
  "Stem": "Flash Manufacturing's most recent annual report shows operating income of $24.0 million, net income of $15.0 million, average interest-bearing debt of $75.0 million, average stockholders' equity of $75.0 million, and average total assets of $150.0 million. Lena Fischer, a credit analyst, wants a measure of the return Flash earns on all capital contributed by both its debt holders and its equity holders. Which ratio should Lena compute?",
  "Choices": {
    "A": "Net profit margin — net income divided by net sales",
    "B": "Return on assets — net income divided by average total assets",
    "C": "Return on invested capital — net operating profit after tax divided by invested capital (interest-bearing debt plus stockholders' equity)",
    "D": "Return on equity — net income divided by average stockholders' equity"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Return on invested capital (ROIC), as defined in the IMA CMA Part 2 Content Specification Outline for profitability analysis, measures the return earned on all capital provided to the firm — debt and equity combined. ROIC = net operating profit after tax (NOPAT) ÷ invested capital, where NOPAT = operating income × (1 − tax rate) and invested capital = interest-bearing debt + stockholders' equity. For Flash: NOPAT = $24.0M × 0.75 = $18.0M and invested capital = $75.0M + $75.0M = $150.0M, giving ROIC = 12.0%. For Lena, a credit analyst, ROIC is the cleanest operating-return measure because it is unaffected by how the assets are financed, unlike ROE, which is amplified by leverage, and unlike ROA, which does not add back the after-tax interest paid to lenders.",
  "ExplanationWrongA": "Net profit margin (net income ÷ net sales) measures how much of each sales dollar ends up as profit; it has no capital or asset base in its denominator. Because it ignores the funds invested, it cannot tell Lena what return Flash earns on the capital that debt holders and equity holders have contributed to the firm.",
  "ExplanationWrongB": "Return on assets divides net income by average total assets. Although total assets are financed by both debt and equity, the net income numerator is only the residual return to common shareholders after interest has been paid to lenders. ROA therefore does not measure the combined return to all capital providers that ROIC captures with NOPAT in the numerator.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Return on equity divides net income by average stockholders' equity only. Because the denominator excludes the debt capital in Flash's capital structure, ROE measures the leveraged return on the shareholders' residual claim, not the return earned on all of the capital — debt plus equity — provided to the firm.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Remember",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-19: Return on invested capital (ROIC) = NOPAT ÷ invested capital",
  "CommonTrapReference": "Confusing the all-capital-provider return (ROIC) with equity-only (ROE) or asset-only (ROA) returns",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (profitability ratios)",
    "Wild, J. J., Subramanyam, K. R., & Halsey, R. F., Financial Statement Analysis (return on invested capital)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Easy — single-concept identification of the ROIC formula with no computation required, appropriate for a Remember-level opener.",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; Wild/Subramanyam/Halsey) match the tested profitability-ratio concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.434 Operating Margin Trend Evaluation",
  "QuestionID": "P2-A-434",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-434-operating-margin-trend-evaluation",
  "Stem": "Flash Manufacturing reports a return on assets (ROA) of 10% and a return on equity (ROE) of 20% for fiscal 2025. Average total assets were $150.0 million and average stockholders' equity was $75.0 million. Lena Fischer, a credit analyst, is puzzled by the size of the gap between the two ratios. Which statement best explains why Flash's ROE is twice its ROA?",
  "Choices": {
    "A": "ROE exceeds ROA because ROE is computed with net income in the numerator whereas ROA is computed with operating income.",
    "B": "ROE exceeds ROA because ROE adds back dividends paid to common shareholders before dividing by stockholders' equity.",
    "C": "ROE exceeds ROA because Flash's stockholders' equity is smaller than its total assets, so the same amount of net income is spread over a smaller base and financial leverage amplifies the return to shareholders.",
    "D": "ROE exceeds ROA because ROA is reduced by interest expense while ROE is computed before interest expense."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The gap reflects the denominators, not the numerators. Both ROA and ROE, as defined in the IMA CMA Part 2 Content Specification Outline, use net income in the numerator: ROA = net income ÷ average total assets = $15.0M ÷ $150.0M = 10%, and ROE = net income ÷ average stockholders' equity = $15.0M ÷ $75.0M = 20%. Because Flash's equity base ($75.0M) is only half of its asset base ($150.0M), the same $15.0M of earnings is divided by a smaller base, so debt financing concentrates the return on the shareholders' capital. For Lena, the gap is a leverage signal: ROE well above ROA indicates that borrowed funds are magnifying the shareholders' return, which is precisely the risk dimension a credit analyst must monitor when assessing Flash's financial structure.",
  "ExplanationWrongA": "This explanation misidentifies the numerator. ROA is not computed with operating income; both ROA and ROE conventionally use net income. The after-tax operating-income return is return on invested capital (ROIC). The difference between ROA and ROE arises from the denominators (total assets versus stockholders' equity), not from a change in the numerator.",
  "ExplanationWrongB": "Dividends are a distribution of earnings, not an addition to them. ROE divides net income by average equity, and dividends are paid out of that net income. Adding dividends back to the numerator would create a hypothetical pre-distribution return that does not reflect the earnings actually retained for and available to shareholders.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Neither ratio is pre-interest: net income is measured after interest expense in both ROA and ROE. ROE is not an earnings-before-interest measure. The two ratios differ because equity is smaller than total assets, so dividing the same after-interest net income by the smaller equity base produces the higher ROE.",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-17: Return on assets (ROA) = net income ÷ average total assets; FA-18: Return on equity (ROE) = net income ÷ average stockholders' equity",
  "CommonTrapReference": "ROA vs ROE confusion — attributing the gap to numerators instead of to financial leverage and the differing denominators",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (ROA vs. ROE)",
    "Wild, J. J., Subramanyam, K. R., & Halsey, R. F., Financial Statement Analysis (financial leverage and the DuPont framework)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Moderate-Easy — one conceptual relationship (the leverage gap between ROA and ROE) with all data supplied and no computation demanded.",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; Wild/Subramanyam/Halsey) match the tested ROA/ROE leverage concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3.",
    "Rule4 recomputed: CorrectChoice B->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.435 Net Profit Margin Benchmarking",
  "QuestionID": "P2-A-435",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-435-net-profit-margin-benchmarking",
  "Stem": "Flash Manufacturing's income statement for the year ended December 31, 2025 reports net sales of $100.0 million, cost of goods sold of $60.0 million, selling, general, and administrative expenses of $16.0 million, interest expense of $4.0 million, and income tax expense of $5.0 million. Priya Ramaswamy, Flash's segment and investor relations analyst, wants Flash's operating profit margin. What is Flash's operating profit margin?",
  "Choices": {
    "A": "40%",
    "B": "20%",
    "C": "24%",
    "D": "15%"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Operating profit margin, per FA-16 as defined in the IMA CMA Part 2 Content Specification Outline, = operating income ÷ net sales, where operating income excludes interest and income taxes. Operating income = gross profit − operating expenses = ($100.0M − $60.0M) − $16.0M = $24.0M. Operating margin = $24.0M ÷ $100.0M = 24.0%. Recomputed: $24.0M ÷ $100.0M = 0.24 = 24.0%. Because interest and taxes are excluded, the operating margin measures the profitability of Flash's core manufacturing operations before the effects of capital structure and tax strategy. For Priya, who analyzes segments and communicates with investors, the operating margin is the most comparable operating-performance measure across business segments and against industry peers.",
  "ExplanationWrongA": "40% is Flash's gross profit margin: gross profit of $40.0M ($100.0M sales − $60.0M cost of goods sold) ÷ $100.0M sales. This margin stops above the $16.0M of selling, general, and administrative expenses, so it overstates operating profitability because it has not yet covered the company's operating costs beyond cost of goods sold.",
  "ExplanationWrongB": "20% is the pretax margin: income before income taxes of $20.0M ($24.0M operating income − $4.0M interest expense) ÷ $100.0M sales. Because pretax income is reduced by interest expense — a financing cost, not an operating cost — the pretax margin is not a pure measure of operating profitability and sits below the operating margin.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "15% is the net profit margin: net income of $15.0M ÷ $100.0M sales. Net income is measured after both interest expense and income tax expense, so the net margin reflects financing costs and the tax rate in addition to operating performance, making it the narrowest of the three margin measures rather than the operating margin.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-16: Operating profit margin = operating income ÷ net sales (with gross and net margin variants)",
  "CommonTrapReference": "Using net income (or pretax income) instead of operating income when computing the operating margin",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (profit margins)",
    "Subramanyam, K. R., Financial Statement Analysis (margin measures at successive income-statement levels)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Moderate — a two-step computation (gross profit, then operating income) with three plausible margin distractors drawn from other income-statement levels.",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; Subramanyam) match the tested margin-measure concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3.",
    "Rule4 recomputed: CorrectChoice B->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.436 Return On Assets Du Pont",
  "QuestionID": "P2-A-436",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-436-return-on-assets-du-pont",
  "Stem": "Flash Manufacturing's income statement for fiscal 2025 reports net sales of $100.0 million and net income of $15.0 million. Total assets were $140.0 million at the start of the year and $160.0 million at year-end; stockholders' equity was $70.0 million at the start of the year and $80.0 million at year-end. Lena Fischer, a credit analyst, wants Flash's return on assets (ROA). What is Flash's ROA?",
  "Choices": {
    "A": "9.4%",
    "B": "10.0%",
    "C": "20.0%",
    "D": "15.0%"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Return on assets, per FA-17 as defined in the IMA CMA Part 2 Content Specification Outline, = net income ÷ average total assets. Flash's average total assets = ($140.0M + $160.0M) ÷ 2 = $150.0M, so ROA = $15.0M ÷ $150.0M = 10.0%. Recomputed: $15.0M ÷ $150.0M = 0.10 = 10.0%. ROA tells Lena how efficiently Flash generates earnings from its entire asset base, before considering how those assets are financed. A point-in-time asset balance would distort the ratio because assets purchased or disposed of during the year change the base available to generate income, so the average balance over the period is the appropriate denominator.",
  "ExplanationWrongA": "9.4% divides net income by year-end total assets of $160.0M rather than by the average asset balance of $150.0M. Because assets can change materially during the year through additions, disposals, and seasonality, a single point-in-time balance does not reflect the asset base actually available to generate income across the period.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "20.0% is Flash's return on equity: net income of $15.0M ÷ average stockholders' equity of $75.0M. ROE measures the leveraged return earned for shareholders, not the return on Flash's total asset base, so it is the wrong ratio when the question asks for return on assets.",
  "ExplanationWrongD": "15.0% is the net profit margin: net income of $15.0M ÷ net sales of $100.0M. The net margin measures earnings per dollar of sales revenue, whereas ROA measures earnings per dollar of assets invested in the business; the two ratios answer different questions about profitability.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-17: Return on assets (ROA) = net income ÷ average total assets",
  "CommonTrapReference": "ROA vs ROE confusion (debt amplification) and using ending instead of average total assets",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (return on assets)",
    "Robinson, T. R., et al., International Financial Statement Analysis (average balances in ratio denominators)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Moderate — a single formula but requires averaging assets and resisting the ROE and net-margin distractors.",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; Robinson et al.) match the tested ROA concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.437 Return On Equity Leverage Effect",
  "QuestionID": "P2-A-437",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-437-return-on-equity-leverage-effect",
  "Stem": "Flash Manufacturing earned net income of $15.0 million in fiscal 2025 and reported operating income of $24.0 million. Total assets were $140.0 million at the start of the year and $160.0 million at year-end. Stockholders' equity was $70.0 million at the start of the year and $80.0 million at year-end. Flash's effective income tax rate is 25%. Priya Ramaswamy, Flash's segment and investor relations analyst, wants Flash's return on equity (ROE) for 2025. What is Flash's ROE?",
  "Choices": {
    "A": "18.8%",
    "B": "20.0%",
    "C": "10.0%",
    "D": "32.0%"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Return on equity, per FA-18 as defined in the IMA CMA Part 2 Content Specification Outline, = net income ÷ average stockholders' equity. Average equity = ($70.0M + $80.0M) ÷ 2 = $75.0M. ROE = $15.0M ÷ $75.0M = 20.0%. Recomputed: $15.0M ÷ $75.0M = 0.20 = 20.0%. ROE uses net income — earnings after interest and taxes — because it measures the return to common shareholders; operating income and the tax rate do not enter the computation. The average equity balance smooths intra-year changes from earnings retention, dividends, and share transactions. For Priya, ROE is the headline return for investor communications, but she should read it alongside ROA and ROIC to separate operating performance from the effects of financial leverage.",
  "ExplanationWrongA": "18.8% divides net income by year-end equity of $80.0M instead of average equity of $75.0M. Using a point-in-time balance ignores the equity that was actually invested throughout the year, so the ratio is distorted by intra-year growth in retained earnings and any share issuances or repurchases.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "10.0% is Flash's return on assets: net income of $15.0M ÷ average total assets of $150.0M. ROA measures the return on the entire asset base, while ROE measures the return on the equity base only; using assets in the denominator misses the amplifying effect that debt financing has on the shareholders' return.",
  "ExplanationWrongD": "32.0% substitutes operating income of $24.0M for net income in the numerator. ROE is a return to shareholders, so it must be measured on the earnings actually available to them — net income after interest and taxes — not on operating income, which is earned before financing and tax costs are deducted.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-18: Return on equity (ROE) = net income ÷ average stockholders' equity",
  "CommonTrapReference": "Ending vs average equity; using operating income instead of net income in the ROE numerator",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (return on equity)",
    "Wild, J. J., Subramanyam, K. R., & Halsey, R. F., Financial Statement Analysis (return on equity and financial leverage)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Difficult — requires computing average equity and navigating a numerator trap (operating income) and a ratio trap (ROA).",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; Wild/Subramanyam/Halsey) match the tested ROE concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.438 Price Earnings Multiple Interpretation",
  "QuestionID": "P2-A-438",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-438-price-earnings-multiple-interpretation",
  "Stem": "Flash Manufacturing reports 2025 net income of $16.5 million, which includes $1.5 million of dividends declared on its preferred shares. Flash had 7.5 million weighted-average common shares outstanding during the year; if all potentially dilutive securities were converted, 8.0 million common shares would be outstanding. Flash's common shares trade at $30.00 per share. Priya Ramaswamy, Flash's segment and investor relations analyst, is preparing the P/E ratio for Flash's investor presentation. Based on the data, determine the P/E ratio that should be reported.",
  "Choices": {
    "A": "13.6",
    "B": "15.0",
    "C": "16.0",
    "D": "0.07"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "The price-earnings ratio, per FA-20 as defined in the IMA CMA Part 2 Content Specification Outline, = market price per share ÷ EPS, where EPS = (net income − preferred dividends) ÷ weighted-average common shares outstanding. Flash's EPS = ($16.5M − $1.5M) ÷ 7.5M shares = $2.00, so P/E = $30.00 ÷ $2.00 = 15.0. Recomputed: $30.00 ÷ $2.00 = 15.0. Preferred dividends must be subtracted because preferred shareholders hold a prior claim on earnings; only the residual is available to common shareholders. The quoted P/E multiple is conventionally based on basic EPS — the 7.5M weighted-average shares — rather than the 8.0M fully diluted count, which reflects potential future conversion. For Priya, a P/E of 15.0 means investors pay $15 for each $1 of Flash's current EPS, a standard valuation benchmark she can compare with peer companies.",
  "ExplanationWrongA": "13.6 computes EPS as $16.5M ÷ 7.5M shares = $2.20, failing to subtract the $1.5M of preferred dividends, and then divides $30.00 by that overstated EPS. Preferred claims reduce the earnings available to common shareholders, so net income must be reduced before computing the common-share EPS used in the P/E ratio.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "16.0 computes EPS on the fully diluted share count: $15.0M ÷ 8.0M shares = $1.875, giving P/E = $30.00 ÷ $1.875 = 16.0. Diluted EPS reflects potential conversion of dilutive securities; the standard quoted P/E multiple is based on basic weighted-average common shares outstanding, so potential dilution should not be layered into the headline multiple.",
  "ExplanationWrongD": "0.07 inverts the ratio by dividing EPS by market price ($2.00 ÷ $30.00 = 0.067), which computes the earnings yield, not the price-earnings multiple. The P/E ratio is price per share divided by EPS, so the correct multiple is the larger number, 15.0, not the small earnings-yield fraction.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-20: EPS = (net income − preferred dividends) ÷ weighted-average common shares; P/E = market price per share ÷ EPS",
  "CommonTrapReference": "EPS numerator error (ignoring preferred dividends), diluted vs basic EPS denominators, and P/E inversion (E/P vs P/E)",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (EPS and P/E)",
    "ASC 260 — Earnings Per Share (preferred dividend subtraction; basic vs. diluted EPS)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Difficult — a four-step computation (subtract preferred dividends, derive EPS, form the multiple) against four distinct traps including P/E inversion.",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; ASC 260) match the tested EPS/P/E concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
