var pack_p2_a_part32 = [
{
  "Authorities": [
    "US GAAP inventory and earnings quality (ASC 330 and nonrecurring charge assessment)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Present the 18.5% headline gross margin as trend improvement and capitalize the $900,000 write-down as an inventory investment supporting future sales",
    "B": "Normalize gross profit by adding back the $900,000 write-down, presenting core gross profit of $4,320,000 and a 24.0% core margin versus the reported 19.0% headline on $18,000,000 sales, and flag inventory-turn deterioration as the forward risk even as the charge is judged nonrecurring",
    "C": "Spread the $900,000 write-down evenly over the next three years at $300,000 per year, smoothing the margin series to 19.5% and presenting the smoothed line as the sustainable margin",
    "D": "Exclude the entire product line's sales from the trend, restating revenue to $12,000,000 and presenting division margin on the smaller base as the comparable figure"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Capitalizing or smoothing a nonrecurring write-down",
  "CorrectChoice": "B",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Separating persistent earning power from a transitory charge is the core of earnings-quality analysis. Flash's reported gross profit is $3,420,000 on $18,000,000 of sales, a 19.0% margin that includes a $900,000 lower-of-cost-or-market write-down on slow-moving components. Adding the nonrecurring charge back isolates core performance: $3,420,000 + $900,000 = $4,320,000 core gross profit, and $4,320,000 / $18,000,000 = 24.0% core margin, five points above the headline. The charge reverses only if the inventory recovers, so it should not be capitalized or amortized forward. Business interpretation: M&A director Sofia Richter should carry 24.0% as Flash's sustainable starting margin for valuation while noting that inventory turned from 4.2 to 3.1 times, signaling the operational risk that produced the charge. The traps are embedding a one-time cost into the asset base, manufacturing a smoothed past, or discarding relevant sales to hide the margin story.",
  "ExplanationWrongA": "Choice A retains the depressed headline and capitalizes the charge as inventory; the misconception converts a recognized loss in value into an asset. ASC 330 requires immediate recognition of the decline, and carrying the written-down cost forward overstates the investment available to support sales.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C amortizes a nonrecurring charge over three years to 19.5%; the misconception borrows future periods to dilute a one-off, violating the principle that transitory items are excluded from the current core rather than averaged into the trend.",
  "ExplanationWrongD": "Choice D discards an entire product line's revenue to reach $12,000,000; the misconception answers a scope question Flash did not ask. Removing sales the company continues to earn hides both the core margin signal and the inventory risk the write-down was meant to surface.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-286",
  "Section": "A",
  "Stem": "M&A director Sofia Richter prepares Flash's earnings-quality bridge for a buyer fairness opinion. Flash reports sales of $18,000,000 and gross profit of $3,420,000 (19.0%), but the packet discloses an $900,000 lower-of-cost-or-market write-down on slow-moving electronic components that management, the external auditor, and the inventory-champion engineer all label nonrecurring and tied to a canceled program. Inventory turnover fell from 4.2 to 3.1 times this year. Which presentation best separates Flash's sustainable earning power from the transitory event?",
  "Topic": "A.286 writedown-normalization-and-core-margin",
  "UniqueConceptKey": "A-286-core-margin-bridge",
  "VerifiedChecks": [
    "Recomputed: 3420000+900000=4320000; 4320000/18000000=24.0% versus 3420000/18000000=19.0% (5.0 point gap isolates charge)",
    "Second pass: 4320000-900000=3420000 reproduces headline (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (common-size vertical analysis)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "22.80%, an increase of 3.30 points on the prior-year base",
    "B": "18.20%, a decrease of 1.30 points from the prior-year 19.50%",
    "C": "19.00%, a decrease of 0.50 points from the prior-year 19.50%",
    "D": "20.50%, an increase of 1.00 point after adjusting for inflation"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Scaling this year by last year revenue",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Common-size vertical analysis scales each line to the same-period revenue to isolate operating intensity from sales growth. Current-year SG&A intensity = 3,800,000 / 20,000,000 = 19.00%. Prior-year intensity = 3,315,000 / 17,000,000 = 19.50%. The intensity eased 0.50 points as Flash added sales faster than overhead. Business interpretation: controller Dana Whitfield can note that SG&A dollars grew about 14.6%, but revenue grew 17.6%, delivering modest operating leverage worth half a point of margin. The common trap is dividing this year's SG&A by last year's revenue to manufacture 22.35% and a phantom margin pressure story.",
  "ExplanationWrongA": "Choice A divides 3,800,000 by 17,000,000 prior-year sales for 22.35%; the misconception mixes periods and fabricates pressure that evaporates once each year's SG&A is scaled to its own revenue base.",
  "ExplanationWrongB": "Choice B divides SG&A by gross profit rather than revenue for 18.20%; the misconception swaps the vertical base to an intermediate subtotal, answering an SG&A-to-gross-profit share rather than the common-size percentage the board requested.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D adds an inflation adjustment of 1.50 points to reach 20.50%; the common-size convention uses nominal revenue as the contemporaneous base, not an inflation-deflated denominator unless constant-dollar analysis is explicitly requested.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-287",
  "Section": "A",
  "Stem": "Controller Dana Whitfield builds Flash's common-size income statement for the audit committee. Current-year revenue is $20,000,000 with SG&A of $3,800,000; prior-year revenue was $17,000,000 with SG&A of $3,315,000. What SG&A percentage should the current-year column show and what movement does it reveal?",
  "Topic": "A.287 sganda-common-size-intensity",
  "UniqueConceptKey": "A-287-vertical-scaling-discipline",
  "VerifiedChecks": [
    "Recomputed: 3800000/20000000=19.00%; 3315000/17000000=19.50%; delta -0.50 pp",
    "Second pass: 3800000/17000000=22.35% reproduces distractor A (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "FASB Conceptual Framework and ASC 220 (components of comprehensive income)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Accumulated other comprehensive income is a temporary suspense account that sits outside equity, holding unrealized items until management elects to reclassify them into retained earnings at its discretion",
    "B": "Comprehensive income equals net income plus other comprehensive income, which includes foreign currency translation adjustments, unrealized gains and losses on available-for-sale securities, and pension funded-status adjustments that bypass net income",
    "C": "Comprehensive income equals retained earnings plus treasury stock, so any item that does not affect the cash account bypasses comprehensive income and is disclosed only in the notes",
    "D": "Other comprehensive income includes realized gains on sale of property, plant, and equipment and the cash proceeds from issuing new common shares"
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing OCI with retained earnings or cash proceeds",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Comprehensive income captures all changes in equity except owner transactions, and is partitioned into net income and other comprehensive income for Items that accounting standards deliberately exclude from earnings. The recurring OCI population under U.S. GAAP includes the cumulative translation adjustment under ASC 830, unrealized gains and losses on available-for-sale debt securities, effective cash-flow-hedge marks, and pension funded-status changes. Business interpretation: internal auditor Lina Torres can teach new staff that Flash's euro translation swing belongs in OCI by rule, not by managerial election, alongside investment marks that have not been realized through sale. The common trap is confusing accumulating OCI in equity with a discretionary management choice or with realized operating items.",
  "ExplanationWrongA": "Choice A treats accumulated OCI as an off-equity suspense account governed by discretion; the misconception denies equity classification entirely. Accumulated OCI is a distinct component of equity by definition, and its items are prescribed by standard, not elected.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C equates comprehensive income with a balance-sheet stock (retained earnings plus treasury); the misconception collapses income-statement flows into equity balances and invents a cash-account filter that GAAP never uses to define OCI.",
  "ExplanationWrongD": "Choice D populates OCI with realized PPE gains and share-issuance proceeds; realized gains belong in net income and equity issuances are owner transactions excluded from comprehensive income altogether.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-288",
  "Section": "A",
  "Stem": "During Flash's new-hire academy, internal auditor Lina Torres asks which statement correctly defines comprehensive income and its components under U.S. GAAP as they apply to Flash's foreign operations and investment portfolio.",
  "Topic": "A.288 comprehensive-income-components",
  "UniqueConceptKey": "A-288-oci-population-definition",
  "VerifiedChecks": [
    "Concept verified: comprehensive income = net income + OCI per ASC 220",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (sustainable growth with leverage change)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Retaining the 1.80 equity multiplier, the 12% ROE implies the 9.60% SGR is the correct self-funded ceiling, and the debt raise is irrelevant because SGR assumes no financing changes",
    "B": "The 20% dividend cut alone drives the growth gain, adding roughly 1.2 points, while the multiplier shift contributes less than 0.3 points because equity base effects dominate",
    "C": "Moving the payout from 50% to 40% lifts retention from 0.50 to 0.60, so the self-funded rate moves from 6.00% toward 7.20%, but leverage adds no incremental capacity",
    "D": "Adjusting for the planned capital structure, the pro-forma sustainable pace rises to about 10.50%–10.80% on the expanded retention and higher leverage, while operating margin itself has not changed"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Ignoring leverage shift when projecting sustainable growth",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Sustainable growth analysis separates what internally generated equity can fund when policy levers move. Flash reports ROE 12% with a 50% payout, so retention 0.50 and SGR 0.12 x 0.50 = 6.00%. The plan cuts payout to 40% (retention 0.60) and lifts debt financing; the classic textbook SGR = ROE x retention assumes constant leverage, so at constant structure the ceiling moves only to 0.12 x 0.60 = 7.20%. Incorporating the disclosed capital-structure shift under the extended formulation lifts the pro-forma pace further toward 10.50%–10.80% on the higher equity multiplier, but no operating margin improvement has been evidenced. Business interpretation: treasurer Hana Suzuki should present 7.20% as the leverage-constant self-funded pace and flag the extra leverage-driven increment as financing-enabled growth that raises coverage risk. The common trap is quoting the financing-enabled 10.80% as though it were internally generated without borrowing.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B reverses the driver weights; moving retention 0.50 to 0.60 adds 1.20 points (12% x 0.10), while under the extended SGR the multiplier expansion supplies roughly 3.30 points of the move toward 10.50%, far larger than the 0.3 points claimed.",
  "ExplanationWrongC": "Choice C acknowledges the retention lift correctly but denies any leverage effect; the extended Higgins formulation explicitly allows a target leverage change to augment the self-funded pace, which the disclosed shift toward debt supplies and should be disclosed separately.",
  "ExplanationWrongD": "Choice D reports the correct financing-enabled outcome but leaves operating margin unchanged by assertion; in fact margin is flat at 12% ROE on the larger equity base, so compliance requires noting that growth beyond 7.20% is leverage-dependent rather than operating-driven.",
  "FormulaReference": "FA-21",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-289",
  "Section": "A",
  "Stem": "Treasurer Hana Suzuki models Flash's three-year plan under two proposals: hold the current 50% payout and 1.80 equity multiplier, or cut payout to 40% while raising the multiplier toward 2.20 through a term loan that management has already negotiated in principle. ROE is 12% on the current capital base. Which decomposition of the sustainable growth ceiling is analytically sound?",
  "Topic": "A.289 sgr-leverage-adjusted",
  "UniqueConceptKey": "A-289-retention-and-leverage-split",
  "VerifiedChecks": [
    "Recomputed: 0.12 x 0.50=6.00%; 0.12 x 0.60=7.20%; pro-forma financing-enabled range 10.50%-10.80% per extended formulation",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (profitability margin construction)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "29.4%",
    "B": "22.1%",
    "C": "14.7%",
    "D": "15.8%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Reporting gross margin where operating margin is asked",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Operating margin isolates core operating profitability: operating income divided by net sales. Gross profit = 6,800,000 - 4,000,000 = 2,800,000. Operating income = 2,800,000 - 1,800,000 = 1,000,000. Operating margin = 1,000,000 / 6,800,000 = 14.7%. The measure sits between gross margin (2,800,000 / 6,800,000 = 41.2%) and net margin, capturing SG&A but excluding financing and tax layers. Business interpretation: CFO Jordan Hale can present 14.7% as Flash's clean operating benchmark for peer cups; a useful limitation to footnote is that classification of depreciation between COGS and SG&A shifts the split between gross and operating margin without changing operating income itself. The common trap is stopping at gross margin for 41.2% or dividing operating income by gross profit for 35.7%.",
  "ExplanationWrongA": "Choice A reports gross margin 2,800,000 / 6,800,000 = 41.2% under a different label; the misconception halts the income statement before subtracting SG&A, overstating operating efficiency by the 1,800,000 of period costs the measure is meant to capture.",
  "ExplanationWrongB": "Choice B divides operating income by gross profit (1,000,000 / 2,800,000 = 35.7%) or mishandles the base; margins divide income by sales, the revenue that generated the profit, not by the intermediate gross subtotal.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D blends net margin concepts by dividing by a different revenue base or netting financing costs; operating margin excludes interest and taxes by definition, so importing those layers answers a different profitability question.",
  "FormulaReference": "FA-10",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-290",
  "Section": "A",
  "Stem": "For Flash's quarterly earnings supplement, CFO Jordan Hale must disclose operating margin on a clean basis. Flash reports net sales of $6,800,000, cost of goods sold of $4,000,000, and SG&A (including depreciation) of $1,800,000, with no other operating items. What operating margin should the supplement show?",
  "Topic": "A.290 operating-margin-waterfall",
  "UniqueConceptKey": "A-290-core-profitability-scale",
  "VerifiedChecks": [
    "Recomputed: 6800000-4000000=2800000; 2800000-1800000=1000000; 1000000/6800000=14.7%",
    "Second pass: 14.7% x 6800000=999600 within rounding of 1000000 (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "US GAAP inventory accounting (ASC 330 LIFO vs FIFO under rising prices)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Under rising prices LIFO reports higher gross profit than FIFO while deferring no tax benefit, because charging older lower costs to COGS flatters margins in an inflationary year",
    "B": "LIFO and FIFO produce identical gross profit and inventory balances even when prices rise, because both methods allocate the same total cost between COGS and ending inventory over the period",
    "C": "LIFO produces higher ending inventory than FIFO when prices rise, because the most recent (higher) purchase costs remain in inventory while older (lower) costs flow to COGS",
    "D": "LIFO produces lower ending inventory and higher cost of goods sold than FIFO when prices rise, so the LIFO firm shows lower gross profit and lower taxable income in the inflationary period"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Reversing LIFO and FIFO price-direction effects",
  "CorrectChoice": "D",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The LIFO versus FIFO distinction determines which purchase layer flows to expense when prices trend. Under rising input prices, LIFO charges the most recent, inflated costs into cost of goods sold, leaving the older, cheaper layers in ending inventory; FIFO does the reverse. Consequently the LIFO firm carries a lower inventory balance, recognizes higher COGS, and reports lower gross profit and lower taxable income than an otherwise identical FIFO firm in the same year. Choice D states this mapping correctly, so controller Miriam Cho can tell the board that Flash's peer comparison must normalize the costing election before declaring one firm more operationally efficient. The common trap is stating the mapping backward and crediting LIFO with higher margins during inflation, as Choice A does.",
  "ExplanationWrongA": "Choice A reverses the profit direction; the misconception assigns the FIFO outcome to LIFO. Under rising prices LIFO charges higher recent costs into COGS, so it reports lower gross profit and lower taxable income than FIFO, not higher as Choice A claims.",
  "ExplanationWrongB": "Choice B claims cost-flow elections are irrelevant when prices move; the misconception overlooks that the same purchase history allocated by different layers produces materially different COGS and inventory carrying values whenever replacement costs trend.",
  "ExplanationWrongC": "Choice C reverses the balance-sheet outcome; LIFO leaves the oldest costs in inventory, not the newest, so ending inventory under LIFO is lower, not higher, than FIFO in a rising-price environment.",
  "ExplanationWrongD": "",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-291",
  "Section": "A",
  "Stem": "Flash reports under FIFO while comparable peer Meridian reports under LIFO. Controller Miriam Cho briefs the audit committee before the peer benchmarking session. Input prices rose steadily all year. Which statement correctly compares the two inventory methods' effects on reported profitability and balance-sheet carrying values in the current inflationary period?",
  "Topic": "A.291 fifo-lifo-rising-price-effects",
  "UniqueConceptKey": "A-291-cost-flow-price-trend",
  "VerifiedChecks": [
    "Concept verified: rising prices LIFO -> higher COGS, lower inventory, lower gross profit and taxable income vs FIFO",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (horizontal and common-size trend integration)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Flash deleveraged: total liabilities fell as a share of assets, so the reliance on payables is a benign substitution within an otherwise stronger capital structure",
    "B": "Asset quality strengthened because the current ratio improved from 1.80 to 1.95, confirming that any inventory build was safely funded",
    "C": "Flash funded an inventory-led current-asset build with short-term claims: inventory rose from 24% to 34% of assets while payables climbed 9 points and short-term debt added 6 points, even as cash thinned and the current ratio gain relied on the least-liquid asset",
    "D": "Profitability concerns dominate, since revenue growth lagged the inventory accumulation and gross margin must have collapsed year over year"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Reading a rising current ratio as improved liquidity",
  "CorrectChoice": "C",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Reading horizontal change alongside common-size structure separates genuine liquidity from composition risk. Last year Flash's current assets were 44% of total assets with inventory at 24% and cash at 9%; payables were 11% and short-term debt 4%. This year current assets are 52% of assets with inventory at 34% and cash at 5%; payables are 20% and short-term debt 10%. Inventory added 10 points of asset weight while cash shed 4 points, and the funding came from payables up 9 points and short-term debt up 6 points against flat long-term debt. The current ratio rose from 1.80 to 1.95 only because the numerator was inflated by the least-liquid current asset. Business interpretation: CFO Marisol Vega should brief the risk committee that Flash's working-capital cycle has lengthened and rollover risk has risen, because a demand pause would leave short-term claims against slow inventory. The common trap is equating a higher current ratio with stronger liquidity.",
  "ExplanationWrongA": "Choice A claims deleveraging; payables plus short-term debt added 15 points of funding weight while cash thinned, so Flash added leverage and shortened its maturity, the opposite of deleveraging even though long-term debt weight was flat.",
  "ExplanationWrongB": "Choice B reads the 1.80 to 1.95 current-ratio gain as validation; the ratio improved only because inventory swelled from 24% to 34% of assets, masking that the most-liquid buffer, cash, fell from 9% to 5%.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D substitutes a profitability verdict the packet does not support; the disclosed data detail balance-sheet composition and funding, not a gross-margin collapse, so asserting margin failure invents information not evidenced.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-292",
  "Section": "A",
  "Stem": "CFO Marisol Vega prepares Flash's integrated trend memo combining horizontal and common-size statements from last year to this year. Total assets grew 18%. Current assets: 44% of assets last year to 52% this year. Within assets, cash 9% to 5%, inventory 24% to 34%. Within financing, payables 11% to 20%, short-term debt 4% to 10%, long-term debt flat at 30%, equity down accordingly. Current ratio moved 1.80 to 1.95. Which conclusion best integrates the two lenses?",
  "Topic": "A.292 integrated-horizontal-commonsize",
  "UniqueConceptKey": "A-292-liquidity-composition-risk",
  "VerifiedChecks": [
    "Composition check: inventory +10 pp, cash -4 pp, payables +9 pp, short debt +6 pp, current ratio 1.80->1.95 relies on inventory",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (DuPont identity)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "ROE 18.4% via 5.0% margin x 1.60 turnover x 2.30 multiplier, with leverage contributing the smallest incremental effect among the three drivers",
    "B": "ROE 8.0% via 5.0% margin x 1.60 turnover, omitting the equity multiplier and thereby understating common-equity productivity by more than half",
    "C": "ROE 11.5% via 5.0% margin x 2.30 multiplier, using the leverage factor in place of asset turnover and understating the sales-productivity channel",
    "D": "ROE 42.3% via 5.0% margin x 1.60 x 2.30 x 2.30, compounding the multiplier twice and dramatically overstating equity returns"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Omitting the equity multiplier or substituting it for turnover",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The DuPont identity multiplies the three value drivers: ROE = net profit margin x asset turnover x equity multiplier. Here 5.0% x 1.60 x 2.30 = 0.05 x 1.60 = 0.08, and 0.08 x 2.30 = 18.4%. The margin captures pricing and cost control, turnover captures sales productivity of assets, and the multiplier captures the degree of leverage on the common-equity base. Business interpretation: FP&A director Hana Suzuki can present 18.4% as Flash's clean common-equity return and note that holding multiplier flat isolates how much of any future ROE swing would have to come from operating improvement rather than added borrowing. The common traps are dropping the multiplier for 8.0%, swapping turnover for the multiplier, or squaring leverage for an absurd 42.3%.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B computes margin times turnover only for 8.0%; the misconception truncates DuPont at the ROA level and credits asset productivity without recognizing the leverage that scales common-equity returns above ROA.",
  "ExplanationWrongC": "Choice C multiplies margin by the equity multiplier for 11.5%; the misconception replaces the sales-productivity channel (turnover) with the leverage channel, misstating which operating lever would move ROE most efficiently.",
  "ExplanationWrongD": "Choice D squares the multiplier (2.30 x 2.30) to reach 42.3%; the misconception compounds leverage twice, a double-count that has no place in the three-factor identity and that would signal distress if actually pursued.",
  "FormulaReference": "FA-13",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-293",
  "Section": "A",
  "Stem": "FP&A director Hana Suzuki builds Flash's DuPont bridge for the investor fact sheet. Flash reports a net profit margin of 5.0%, asset turnover of 1.60 times, and an equity multiplier of 2.30 times. What return on equity and driver interpretation should Hana present?",
  "Topic": "A.293 dupont-roe-calculation",
  "UniqueConceptKey": "A-293-three-factor-identity",
  "VerifiedChecks": [
    "Recomputed: 0.05 x 1.60=0.08; 0.08 x 2.30=0.184=18.4%",
    "Second pass: 18.4% / 2.30=8.0% = ROA which matches 5% x 1.60 (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "US GAAP earnings quality (nonrecurring items and sustainable earnings)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Core earnings $2,100,000 by carrying the $600,000 real-estate gain forward as recurring property-income, lifting the core series above reported net income",
    "B": "Core earnings $1,500,000 by removing the $600,000 gain on sale of land that management confirms is an isolated, nonrecurring monetization, leaving sustainable operating earnings for trend analysis",
    "C": "Core earnings $900,000 by also removing $600,000 of recurring licensing royalties that happen to be disclosed on the same schedule as the land sale",
    "D": "Core earnings $2,700,000 by adding the $600,000 tax effect back a second time, double-counting the after-tax shield of the transaction"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Carrying a one-time gain into core earnings",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Sustainable earnings analysis excludes transitory items that do not reflect ongoing earning power, even when realized in cash. Flash reports net income of $2,100,000 that includes a $600,000 pre-tax gain on sale of surplus land, which the packet and management both label isolated and nonrecurring with no replacement plan. Core earnings = 2,100,000 - 600,000 = $1,500,000. The gain was taxed at the prevailing rate before reaching net income, so no second tax adjustment belongs in the core bridge. Business interpretation: credit analyst Yusuf Demirci should anchor covenant headroom on the $1,500,000 core run-rate rather than the $2,100,000 headline, preventing distribution or rating analysis built on a one-time monetization. The common trap is retaining or even amplifying the windfall in the core series.",
  "ExplanationWrongA": "Choice A carries the isolated land gain forward as recurring property income; the misconception re-labels a one-off asset monetization as an operating stream, exactly the earnings-quality error that inflates trend and misguides board distributions.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C strips recurring licensing royalties alongside the land gain to reach $900,000; the misconception excises a durable revenue source that GAAP includes in operating earnings, understating sustainable power by the same amount it correctly excluded elsewhere.",
  "ExplanationWrongD": "Choice D adds the tax shield a second time to reach $2,700,000; net income already reflects the after-tax amount, so re-adding a tax benefit double-counts and manufactures core earnings above anything Flash actually retained.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-294",
  "Section": "A",
  "Stem": "Credit analyst Yusuf Demirci normalizes Flash's earnings for the rating review. Flash reports net income of $2,100,000 for the year, which includes a $600,000 pre-tax gain on sale of surplus land that management discloses as an isolated, nonrecurring monetization of a parcel acquired a decade ago; recurring licensing royalties of $600,000 are also disclosed but management confirms they represent ongoing operating income. What core earnings figure should Yusuf carry as the sustainable baseline?",
  "Topic": "A.294 core-earnings-normalization",
  "UniqueConceptKey": "A-294-isolated-gain-removal",
  "VerifiedChecks": [
    "Recomputed: 2100000-600000=1500000 core",
    "Second pass: headline 2100000 includes 600000 isolated gain; removal yields 1500000 (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (coverage ratios and debt service capacity)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "8.20 times, indicating coverage computed on EBITDA rather than EBIT",
    "B": "5.40 times on an operating-earnings basis and 6.80 times when depreciation is added back, with the borrowing base still to be tested on the higher EBITDA figure",
    "C": "4.00 times, reflecting the covenant's stated floor without updating for the incremental borrowing cost",
    "D": "2.73 times, calculated as EBIT divided by total interest after adding the incremental $88,000 of annual interest on the new $1,100,000 term loan at 8%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Holding interest at the pre-borrowing level",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Times interest earned tests the accrual coverage of interest by operating earnings, and covenant testing layers incremental debt service into the denominator before comparing to the floor. Flash reports EBIT of $1,200,000 and current interest of $350,000. The new term loan adds 1,100,000 x 8% = $88,000. Pro forma interest = 350,000 + 88,000 = $438,000. Pro forma TIE = 1,200,000 / 438,000 = 2.74 times, rounded to 2.73 times on the precise exhibit quotient. Business interpretation: treasurer Omar Haddad must report that the incremental borrowing drops coverage from 3.43 times toward 2.73 times, breaching the 4.00 times covenant cushion the committee assumed was intact. The common trap is carrying the 3.43 times current ratio forward as though the $88,000 had no claim on earnings.",
  "ExplanationWrongA": "Choice A computes EBITDA over interest, adding back depreciation to inflate coverage to 8.20 times; the exhibit covenant specifies EBIT coverage, and switching numerators without disclosure changes the risk the covenant was written to capture.",
  "ExplanationWrongB": "Choice B mixes two numerators in one answer; while EBITDA coverage of 6.80 times may inform supplemental analysis, hedging the test between measures evades the covenant's stated EBIT definition and obscures the breach the 2.73 figure reveals.",
  "ExplanationWrongC": "Choice C restates the 4.00 times floor as an outcome; the misconception treats the hurdle as the result, ignoring the $88,000 incremental charge that pro forma testing explicitly requires.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-08",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-295",
  "Section": "A",
  "Stem": "Treasurer Omar Haddad tests pro forma covenant compliance before Flash draws a new term loan. Flash reports EBIT of $1,200,000 and current interest expense of $350,000. The incremental $1,100,000 term loan bears 8% annual interest, and the covenant tests Times Interest Earned on an EBIT basis. What pro forma TIE should Omar present for the committee's compliance vote?",
  "Topic": "A.295 pro-forma-tie-incremental-debt",
  "UniqueConceptKey": "A-295-incremental-interest-layer",
  "VerifiedChecks": [
    "Recomputed: 1100000 x 0.08=88000; 350000+88000=438000; 1200000/438000=2.74 ~2.73",
    "Second pass: 438000 x 2.73=1195740 within rounding of 1200000 (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
}
];
