var pack_p2_a_part22 = [
{
  "Authorities": [
    "ASC 350",
    "ASC 350-20"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Future return on assets improves permanently because the impaired asset base is now smaller",
    "B": "The write-down is recorded directly against equity with no income-statement effect",
    "C": "Operating cash flow falls by the $80M impairment in the year charged",
    "D": "Net income swings to −$35M, equity falls to $220M lifting debt-to-equity from 0.67 to 0.91, and operating cash flow is unchanged because the charge is non-cash"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Treating a non-cash impairment as a cash event, or missing its leverage-ratio consequences",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "An ASC 350 impairment charge of $80M (goodwill written from $120M to $40M) flows through OPERATING INCOME: net income falls from $45M to −$35M (tax effects ignored per the facts). Equity absorbs the loss, dropping from $300M to $220M, so debt-to-equity deteriorates from $200M ÷ $300M = 0.67 to $200M ÷ $220M = 0.91 — leverage ratios worsen even though nothing was borrowed. Because the charge involves no cash, operating cash flow is unaffected; under the indirect method it is added back within the reconciliation. The analyst reads the impairment as new information about acquisition economics, then evaluates whether the REMAINING goodwill of $40M is supported by the acquired business's current performance.",
  "ExplanationWrongA": "The smaller denominator lifts future ROA only if earnings recover: in the impairment year ROA is deeply negative (−$35M against $420M of remaining assets), and a one-time reset is not durable improvement — it is evidence that past acquisition capital destroyed value.",
  "ExplanationWrongB": "Goodwill impairments run through the income statement under ASC 350 — they reduce operating income and net income in the period assessed. Direct charges to equity that bypass the income statement are not U.S. GAAP treatment for goodwill.",
  "ExplanationWrongC": "The impairment is a bookkeeping entry with no invoice attached: no cash leaves the company when goodwill is written down. Only continued deterioration of the acquired business would show up in later operating cash flows.",
  "ExplanationWrongD": "",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-183",
  "Stem": "Nuvora Industries writes down goodwill from $120M to $40M ($80M charge; ignore tax). Immediately before the charge: net income $45M, total assets $500M, debt $200M, equity $300M. Which statement describes the effects correctly?",
  "Topic": "A.183 Goodwill impairment — ratio effects",
  "UniqueConceptKey": "A-183-goodwill-impairment-ratio-effects",
  "LOSTag": "A.3",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: NI=45-80=-35; equity 300->220; D/E=200/220=0.91; charge is non-cash",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "ASC 280",
    "Portfolio risk analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Concentration in one volatile region amplifies currency, political, and demand-cycle exposure — the analyst should stress-test growth durability and consider a higher risk premium before capitalizing reported earnings",
    "B": "Geographic mix is irrelevant as long as consolidated margins remain strong",
    "C": "Revenue diversifies automatically as companies scale, so today's concentration will self-correct",
    "D": "Reportable-segment data is too unreliable to support any geographic risk conclusion"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Capitalizing concentrated-region earnings at the same multiple as diversified peers",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "ASC 280 segment disclosures exist precisely to expose concentration. Seventy percent of revenue from one emerging region means the earnings stream carries that region's currency volatility, political risk, and demand cycle — risks a diversified competitor does not bear. The analytical consequences are concrete: decompose growth into region-driven versus core components, apply scenario haircuts to the concentrated stream, and recognize that identical reported margins do NOT imply identical risk. Valuation and credit conclusions should reflect whether the earnings base could survive a single-region shock.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Margin strength says nothing about revenue DURABILITY. A regional crisis hits the top line directly; high-margin firms with concentrated revenue lose more absolute profit per point of regional decline than diversified low-margin firms.",
  "ExplanationWrongC": "Scale does not diversify geography by itself — expansion follows opportunity, which often deepens regional concentration. Absent deliberate strategy, the mix persists or worsens.",
  "ExplanationWrongD": "Audited segment footnotes are among the more reliable disclosures available; imperfect cost allocation hardly justifies ignoring where three-quarters of the revenue originates. Imperfect information still dominates no information.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-184",
  "Stem": "Analyst Sofia Nguyen evaluates a distributor deriving 70% of revenue from one emerging-market region with high currency volatility. Which treatment of the geographic concentration is analytically correct?",
  "Topic": "A.184 Geographic concentration risk",
  "UniqueConceptKey": "A-184-geographic-concentration-risk",
  "LOSTag": "A.4",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 70% single-region revenue carries FX/political/demand concentration deserving premium",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "Gross margin analysis",
    "Variance decomposition"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The margin decline proves internal control failure or inventory shrinkage and warrants a fraud investigation before any other analysis",
    "B": "COGS grew faster than sales — the analyst should decompose whether price realization lagged unit-cost inflation, or whether mix shifted toward lower-margin products, before drawing conclusions about causes or remedies",
    "C": "Sales growth of 10% automatically restores margins over time as fixed costs spread across higher volume",
    "D": "A single aggregate driver explains margin moves, so no further decomposition is useful"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Jumping from an aggregate margin change to a single-cause conclusion without price-cost-mix decomposition",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Gross margin fell from 40% to 38% because COGS grew 13.7% against 10% sales growth — the arithmetic is unambiguous, but the CAUSES are not. Three candidate mechanisms dominate: input-cost inflation passed through more slowly than realized (price/cost timing), negative mix shift toward lower-margin products or channels, and volume driven by discounting that surrendered margin for share. Each implies different durability and different management responses. The disciplined analyst separates price, cost, and mix effects — using unit data where available — before attributing the compression to cost-control failure, competitive pressure, or deliberate strategy.",
  "ExplanationWrongA": "Margin compression has many ordinary drivers — input inflation, mix shifts, promotional discounting. Fraud conclusions need corroboration such as inventory counts and supplier-invoice testing; jumping straight to shrinkage biases every subsequent analytical test.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Volume spreads FIXED costs; gross margin is a per-unit concept largely indifferent to fixed-cost absorption. Discount-driven growth typically DEEPENS gross-margin erosion rather than repairing it.",
  "ExplanationWrongD": "Price, cost, and mix effects net into one ratio; treating the net change as a single cause makes remediation guesswork — a pricing problem demands pricing action, a sourcing problem demands procurement action, and they call for opposite responses.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-185",
  "Stem": "Rafter Industries gross margin fell from 40% to 38% while sales grew 10% and COGS grew 13.7%. Which analytical approach to the margin compression is correct?",
  "Topic": "A.185 Gross margin driver decomposition",
  "UniqueConceptKey": "A-185-gross-margin-driver-decomposition",
  "LOSTag": "A.2",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: COGS +13.7% outgrew sales +10%; decompose price/cost/mix before attributing cause",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "ASC 260",
    "ASC 260-10-30"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "All outstanding options and convertible securities are always included in diluted EPS regardless of their incremental effect",
    "B": "Antidilutive securities are ignored by GAAP entirely and never enter any part of the EPS computation",
    "C": "Securities whose inclusion would INCREASE earnings per share are antidilutive and are excluded from diluted EPS; the dilution test is re-run every reporting period",
    "D": "Basic EPS must be restated to include hypothetical option shares outstanding"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Assuming all potentially dilutive instruments automatically enter diluted EPS",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 260, diluted EPS includes potentially dilutive securities ONLY when their inclusion DECREASES EPS — the conservative direction. A convertible whose assumed conversion would RAISE EPS (interest add-back outweighing the added shares) is antidilutive and drops out for that period; out-of-the-money options fail the test trivially. The classification can flip between periods as share prices move, which is why the test is re-performed each quarter. Basic EPS never changes for options or converts; diluted EPS is where the inclusion test operates, and its purpose is to show the WORST-CASE claim on earnings, not an average case.",
  "ExplanationWrongA": "Inclusion is conditional on the DIRECTION of dilution: a convertible whose assumed conversion would raise EPS fails the test for that period. Blanket inclusion would overstate shareholders' claim on earnings instead of presenting its worst case.",
  "ExplanationWrongB": "Antidilutive securities are excluded from diluted EPS for that period, but they remain subject to the test every period and can become dilutive when prices or assumptions shift. 'Ignored by GAAP entirely' overstates the treatment.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Basic EPS uses weighted-average shares actually outstanding during the period. Hypothetical option shares appear only in the diluted computation, and even there only when dilutive.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-186",
  "Stem": "Controller David Kim computes Willow Textiles diluted EPS. Willow's convertible bonds would ADD to diluted EPS: the after-tax interest add-back to the numerator would outweigh the additional shares from assumed conversion. How should the bonds be treated?",
  "Topic": "A.186 Antidilutive securities exclusion",
  "UniqueConceptKey": "A-186-antidilutive-securities-exclusion",
  "LOSTag": "A.1",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Inclusion raising EPS = antidilutive -> excluded from diluted EPS this period",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "ASC 230",
    "Cash flow statement analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The $30M depreciation add-back demonstrates that depreciation generated operating cash during the period",
    "B": "Rising accounts receivable improved operating cash flow because more sales were booked",
    "C": "Choosing the indirect method changes the total operating cash flow reported versus the direct method",
    "D": "The $18M payables increase ADDS to cash because suppliers are financing operations — but the benefit reverses when stretched payments normalize; add-backs reconcile accrual income to cash rather than create it"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Reading indirect-method adjustments as cash drivers instead of reconciling items",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The indirect method starts with accrual net income and adjusts toward cash reality. Depreciation is added back because it reduced income without consuming cash — the add-back UNDOES an expense, it does not manufacture money. Receivables growth is subtracted because those sales produced no collections yet. Payables growth is ADDED because suppliers effectively extended financing: goods received, cash unpaid. That payables boost is real this period and transient by nature — next period's payments will reverse it. Analysts therefore separate structural OCF improvement from timing benefits like payable stretching before concluding that cash generation genuinely improved.",
  "ExplanationWrongA": "Depreciation reduced INCOME without consuming any cash; the add-back merely reverses that non-cash expense inside the reconciliation. Cash generation comes from collections net of payments — never from an accounting charge itself.",
  "ExplanationWrongB": "Receivables growth appears as a NEGATIVE adjustment: revenue was recognized but not collected, so accrual income outran cash. Growing AR drains operating cash in the period it occurs.",
  "ExplanationWrongC": "Both methods report IDENTICAL total operating cash flow; they differ only in presentation — direct lists gross receipts and payments by category, while indirect reconciles from net income.",
  "ExplanationWrongD": "",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-187",
  "Stem": "Analyst Priya Sharma reads Nuvora Industries operating cash flow reconciliation: net income $90M; depreciation add-back +$30M; receivables increase -$12M; payables increase +$18M. Which interpretation of these adjustments is correct?",
  "Topic": "A.187 Indirect method adjustments interpretation",
  "UniqueConceptKey": "A-187-indirect-method-adjustments-interpretation",
  "LOSTag": "A.3",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Dep add-back reverses non-cash expense; AR subtracts; AP add reverses next period",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "Working capital analysis",
    "Business model analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "For fast-turn retailers that collect from customers before paying suppliers, negative working capital is a low-cost funding source; the same figure signals distress in slow-turn industries — interpretation depends on the operating cycle",
    "B": "Negative working capital always indicates imminent insolvency risk regardless of business model",
    "C": "Negative working capital is universally a strength because liabilities exceed liquid assets",
    "D": "Liquidity ratios become meaningless whenever working capital turns negative"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Applying one working-capital sign interpretation across all business models",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Working capital's meaning depends on the operating cycle. A grocer sells inventory for cash within days while paying suppliers in 30-60 days: customers fund the business, so negative working capital reflects NEGATIVE net funding needs — a competitive advantage lowering capital intensity. A shipbuilder with the same negative balance may be stretching payables against slow-turning contracts — a distress marker. The analytical sequence: map the cash conversion cycle, check trend and composition (payables stretch versus genuine velocity), and benchmark against industry peers before labeling the sign good or bad.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Subscription-style firms (annual-billed software, cash-scanning grocers) run negative working capital for years while thriving. Insolvency depends on the TIMING of obligations, not the sign of one balance-sheet net.",
  "ExplanationWrongC": "The same negative figure at a contractor with milestone billings may be payables stretched against stalled projects — a distress marker. Context and trend decide whether the sign is strength or symptom.",
  "ExplanationWrongD": "A current ratio below 1.0 simply reflects the funding model. Pair it with the cash conversion cycle and covenant headroom to judge whether the position is structural by design or newly deteriorating.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-188",
  "Stem": "Brixton Club runs negative working capital while turning inventory every 12 days and collecting sales in cash. A shipbuilder shows the same negative balance while stretching payables on stalled contracts. Which framework interprets these positions correctly?",
  "Topic": "A.188 Negative working capital business models",
  "UniqueConceptKey": "A-188-negative-working-capital-business-models",
  "LOSTag": "A.1",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Sign interpretation depends on operating cycle: velocity strength vs payable stretch",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "SEC Regulation S-K Item 4.02",
    "Financial reporting reliability"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "A restatement proves management committed fraud and warrants immediate disqualification of the company's disclosures",
    "B": "A restatement signals control weakness that discounts reliance on historical metrics until remediation is evidenced through control testing and sustained clean reporting",
    "C": "Markets fully absorb restatements without consequence once corrected filings are made",
    "D": "The originally filed statements remain the more reliable record compared with later restated versions"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Equating restatement with proven fraud — or assuming zero consequences after correction",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Item 4.02 restatements correct material errors whose causes range from innocent oversight to deliberate manipulation — the filing itself establishes unreliability, not intent. The rational response recalibrates trust: internal-control weaknesses that permitted the error take time and evidence to remediate, prior-period estimates deserve extra skepticism, and cost-of-capital and litigation consequences typically persist. Analysts should use RESTATED figures for trend work, track the remediation timeline, and watch whether subsequent quarters validate the corrections before restoring full confidence in management's estimates.",
  "ExplanationWrongA": "Restatements correct errors spanning innocent oversight to deliberate manipulation; fraud requires evidence of INTENT that the filing itself does not establish. Disqualifying every disclosure on the basis of one restatement overreaches the signal.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Event studies consistently show negative abnormal returns, elevated spreads, and heightened litigation activity around restatements. Correction removes the error, not the credibility damage.",
  "ExplanationWrongD": "Inverted logic: the restatement exists precisely because the original figures contained material errors. Restated statements supersede the originals for every analytical purpose.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-189",
  "Stem": "Flash Manufacturing files an Item 4.02 restatement correcting revenue-cutoff errors and disclosing a related material weakness. Which stance toward historical metrics and forward estimates is analytically sound?",
  "Topic": "A.189 Restatement as reliability signal",
  "UniqueConceptKey": "A-189-restatement-as-reliability-signal",
  "LOSTag": "A.3",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Item 4.02 establishes unreliability, not intent; use restated data pending remediation",
    "Authority citations match tested concept"
  ]
},
{
  "Authorities": [
    "Compound growth analysis",
    "Comparative analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "11.6% — total growth of 46.41 points divided evenly across the four years",
    "B": "46.4% — the cumulative four-year growth rate treated as the annual pace",
    "C": "10.0% — (146.41 ÷ 100)^(1/4) − 1, compounding growth on growth",
    "D": "7.9% — applying a five-period exponent to the four-year span"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using simple-average or total growth instead of the geometric compound rate",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Compound annual growth rate = (Ending ÷ Beginning)^(1/n) − 1 = ($146.41M ÷ $100M)^(1/4) − 1 = 1.4641^0.25 − 1 = 10.0%. CAGR captures growth-on-growth: each year's expansion compounds on the enlarged base, which is why the constant rate linking $100M to $146.41M across four years is 10%, not the 11.6% simple average. Trend analysis should anchor on CAGR whenever the base grows materially, because simple averages systematically overstate multi-year growth trajectories.",
  "ExplanationWrongA": "Dividing the 46.41-point total by four ignores compounding: year two's growth builds on year one's larger base. Simple averaging overstates the sustainable annual pace.",
  "ExplanationWrongB": "46.4% is the ENTIRE four-year change, not an annual rate. Presenting cumulative growth as annual overstates the trajectory nearly five-fold.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Four years of growth means FOUR compounding intervals: (1.4641)^(1/4). Dividing by five periods shrinks the implied rate toward 7.9%.",
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-190",
  "Stem": "Willow Textiles grew revenue from $100M to $146.41M over four fiscal years. What compound annual growth rate should the analyst report?",
  "Topic": "A.190 Compound annual growth rate",
  "UniqueConceptKey": "A-190-compound-annual-growth-rate",
  "LOSTag": "A.4",
  "ItemStyle": "single-select",
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "certification_session": "P2-059",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: (146.41/100)^(1/4)-1 = 10.0%",
    "Authority citations match tested concept"
  ]
},
{
  "QuestionID": "P2-A-191",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.8",
  "Topic": "A.191 operating-leverage-dol",
  "UniqueConceptKey": "A-191-operating-leverage-point-elasticity",
  "Authorities": [
    "Managerial accounting leverage theory (contribution margin framework)"
  ],
  "FormulaReference": "FA-19",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Apply",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CommonTrapReference": "Computing DOL with gross margin instead of contribution margin",
  "Stem": "Flash is a diversified manufacturer. Controller Priya Chen is preparing a risk briefing on the industrial automation division for CFO Elena Vasquez. For the most recent fiscal year the division reported net sales of $84.0 million, total variable costs of $58.8 million, and total fixed costs of $18.0 million. What is the division's degree of operating leverage (DOL) at this sales level?",
  "Choices": {
    "A": "0.29",
    "B": "3.50",
    "C": "4.67",
    "D": "2.33"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Degree of operating leverage is defined in managerial accounting leverage theory as contribution margin divided by operating income at a specific sales level. Contribution margin = $84.0M - $58.8M = $25.2M; operating income = $25.2M - $18.0M = $7.2M; DOL = $25.2M / $7.2M = 3.50. For Priya Chen's briefing this means each 1% movement in divisional sales swings operating income by roughly 3.5%, because the $18.0M fixed-cost block does not flex with volume. DOL is a point elasticity, so its value rises as the division operates closer to breakeven and falls as volume grows.",
  "ExplanationWrongA": "Option A (0.29) flips the ratio, dividing operating income by contribution margin ($7.2M / $25.2M). Reading the elasticity backwards would tell Priya Chen that sales swings barely matter, when the correct reading is the reciprocal, 3.50, meaning profits amplify demand changes.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C (4.67) divides sales by fixed costs ($84.0M / $18.0M), pairing the wrong inputs entirely. Revenue over a fixed-cost block ignores variable-cost absorption and is not an elasticity; DOL must pit contribution margin against operating income.",
  "ExplanationWrongD": "Option D (2.33) drops the $3.6M of fixed selling and administrative cost from the fixed base, inflating operating income to $10.8M and depressing the quotient. Fixed SG&A still magnifies volume swings, so omitting it understates true leverage.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate - single-formula DOL computation with clean extraction of CM and OI",
    "Independent recompute: DOL = (84.0-58.8)/(84.0-58.8-18.0) = 25.2/7.2 = 3.50",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-192",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.5",
  "Topic": "A.192 translation-vs-transaction-exposure",
  "UniqueConceptKey": "A-192-exposure-type-discrimination",
  "Authorities": [
    "FASB ASC 830 (Foreign Currency Matters)"
  ],
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "CalculationItem": false,
  "CognitiveLevel": "Understand",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CommonTrapReference": "Treating translation adjustments as cash-flow losses, or vice versa",
  "Stem": "Flash is a diversified manufacturer. Treasurer Marcus Webb is briefing Flash's audit committee on currency risks arising from the Munich manufacturing subsidiary, whose books are kept in euros and whose results consolidate into Flash's U.S. dollar statements. Which statement best distinguishes transaction exposure from translation exposure for this subsidiary?",
  "Choices": {
    "A": "Transaction exposure arises only when the subsidiary's statements are consolidated into Flash's reporting currency.",
    "B": "Both exposures arise solely at the moment a foreign-currency amount is settled in cash.",
    "C": "Transaction exposure affects cash flows of specific euro-denominated transactions, such as a parts payable balance, as rates move before settlement; translation exposure affects only reported consolidated results when the subsidiary's statements are translated into U.S. dollars, with no immediate cash flow effect.",
    "D": "Translation exposure requires remeasuring nonmonetary items at historical rates with gains and losses recognized in net income."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Under FASB ASC 830, transaction exposure concerns exchange gains or losses on individual foreign-currency transactions, such as Flash's euro-denominated parts payable, as spot rates move before settlement, and those effects reach net income when recognized. Translation exposure arises only when Marcus Webb consolidates the Munich subsidiary: assets, liabilities, and results are restated into U.S. dollars, producing a translation adjustment reported in other comprehensive income with no immediate cash effect. Keeping the two categories distinct ensures hedging effort targets exposures that actually move cash rather than consolidation mechanics.",
  "ExplanationWrongA": "Option A relocates translation exposure onto individual deals: consolidation restatements produce no cash settlement, so calling the translation adjustment a transaction gain or loss reverses the two ASC 830 categories and would misdirect Webb's hedging toward non-cash items.",
  "ExplanationWrongB": "Option B asserts both exposures crystallize only at cash settlement. Transaction exposure builds continuously as spot rates drift before settlement, and translation exposure arises at each reporting-date consolidation, so neither category waits for a cash event to exist.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D assigns historical-rate remeasurement of nonmonetary items with net-income recognition to translation. Under current-rate translation the adjustment bypasses net income into OCI; historical-rate remeasurement belongs to the temporal method used when the dollar is functional.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate-Easy - single-concept discrimination between two ASC 830 exposure types",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-193",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.1",
  "Topic": "A.193 quick-ratio-components",
  "UniqueConceptKey": "A-193-quick-ratio-numerator",
  "Authorities": [
    "FASB ASC 205-10 (Presentation of Financial Statements)"
  ],
  "FormulaReference": "FA-02",
  "ItemStyle": "single-select",
  "CalculationItem": false,
  "CognitiveLevel": "Remember",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CommonTrapReference": "Including inventory in the quick ratio numerator",
  "Stem": "During an analyst onboarding session at Flash, a diversified manufacturer, assistant controller Derek Malone asks the new hires which current assets belong in the numerator of the quick (acid-test) ratio.",
  "Choices": {
    "A": "Cash and cash equivalents, marketable securities, and accounts receivable",
    "B": "Cash and cash equivalents, marketable securities, and inventory",
    "C": "Cash and cash equivalents, inventory, and prepaid expenses",
    "D": "Cash and cash equivalents plus marketable securities only"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The acid-test construction referenced in ASC 205-10-based analysis includes only the most liquid current assets in the numerator: cash and cash equivalents, marketable securities, and net accounts receivable. Quick ratio = (Cash + Marketable securities + Accounts receivable) / Current liabilities. Inventory is excluded because converting it to cash requires a full sales-and-collection cycle, and prepaid expenses are excluded because they are consumed rather than converted to cash. Derek Malone's contrast point: the cash ratio is narrower still, containing only cash plus marketable securities, so the three liquidity ratios form a conservative-to-aggressive spectrum.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B pulls inventory into the numerator, effectively rebuilding the current ratio's coverage. Inventory needs a sales-and-collection cycle before becoming spendable cash, which is precisely why the acid-test strips it out to give Derek Malone's trainees a stress view of liquidity.",
  "ExplanationWrongC": "Option C swaps in inventory and prepaid expenses, two of the least liquid current assets. Prepaids are consumed rather than collected, so including them overstates Flash's capacity to satisfy near-term obligations and defeats the ratio's conservative purpose.",
  "ExplanationWrongD": "Option D describes the cash ratio, not the quick ratio: only cash plus marketable securities. Dropping trade receivables is overly severe for most manufacturers like Flash, whose receivables convert quickly and belong in an acid-test measure.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Easy - direct recall of quick-ratio numerator components",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-194",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.1",
  "Topic": "A.194 inventory-turnover-calculation",
  "UniqueConceptKey": "A-194-average-inventory-turnover",
  "Authorities": [
    "FASB ASC 330 (Inventory)"
  ],
  "FormulaReference": "FA-04",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Apply",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CommonTrapReference": "Using ending inventory or sales instead of average inventory and COGS",
  "Stem": "Flash is a diversified manufacturer. FP&A director Tomas Reyes is compiling fiscal 2025 working-capital metrics for CFO Elena Vasquez. Cost of goods sold was $96.0 million for the year, and inventories were $14.0 million at January 1 and $18.0 million at December 31. What was Flash's inventory turnover for fiscal 2025?",
  "Choices": {
    "A": "5.33 times",
    "B": "6.86 times",
    "C": "8.25 times",
    "D": "6.00 times"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Inventory turnover under ASC 330-based analysis equals cost of goods sold divided by average inventory. Average inventory = ($14.0M + $18.0M) / 2 = $16.0M. Turnover = $96.0M / $16.0M = 6.00 times. For Tomas Reyes this indicates Flash converts its inventory investment into cost of sales about six times per year, roughly every 61 days using 365 / 6. Using ending inventory alone ($96.0M / $18.0M = 5.33) or beginning inventory ($96.0M / $14.0M = 6.86) misstates efficiency whenever balances shifted during the year, and substituting the $132.0M of sales for COGS would inflate the figure by importing pricing margin unrelated to inventory cost.",
  "ExplanationWrongA": "Option A (5.33) divides COGS by ending inventory of $18.0M. The year-end date embeds any seasonal build-up, so a single-date denominator understates velocity; averaging $14.0M and $18.0M into $16.0M aligns the denominator with the whole period of activity.",
  "ExplanationWrongB": "Option B (6.86) divides by beginning inventory of $14.0M, overstating turns after inventory grew through the year. Either single-date endpoint distorts the measure; the $16.0M mean matches cost of goods sold earned across all twelve months.",
  "ExplanationWrongC": "Option C (8.25) substitutes sales of $132.0M for COGS. Revenue carries margin that inventory never cost, inflating turnover and mixing pricing effects into an operating-efficiency metric; the numerator must be the cost flow matched to the inventory investment.",
  "ExplanationWrongD": "",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate - two-step average-inventory computation plus correct numerator choice",
    "Independent recompute: avg inv = (14.0+18.0)/2 = 16.0; turnover = 96.0/16.0 = 6.00",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
}
];
