var pack_p2_a_part51 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.439 Dividend Yield Payout Analysis",
  "QuestionID": "P2-A-439",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-439-dividend-yield-payout-analysis",
  "Stem": "Flash Manufacturing's board declares common dividends equal to 40% of net income. Flash's return on equity is 20% and its return on assets is 10%. Lena Fischer, a credit analyst, is assessing how Flash's dividend policy affects internally financed growth. Which statement correctly describes the relationship among Flash's dividend payout ratio, retention ratio, and sustainable growth rate?",
  "Choices": {
    "A": "Flash's retention ratio is 60% and its sustainable growth rate is 6%.",
    "B": "Flash's retention ratio is 40% and its sustainable growth rate is 8%.",
    "C": "Flash's retention ratio is 60% and its sustainable growth rate is 12%.",
    "D": "Flash's retention ratio is 60% and its sustainable growth rate is 20%."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Per FA-20, as defined in the IMA CMA Part 2 Content Specification Outline, the dividend payout ratio = dividends ÷ net income = 40%, the retention ratio = 1 − payout ratio = 1 − 0.40 = 60%, and the sustainable growth rate = ROE × retention ratio = 20% × 60% = 12%. The sustainable growth rate is the maximum rate Flash can grow using only internally generated funds while holding its capital structure and payout policy constant. A 40% payout means Flash distributes $0.40 of every earnings dollar and reinvests $0.60. For Lena, a credit analyst, a higher retention ratio funds growth without additional borrowing, but it also reduces the cash available to service debt and pay dividends; the sustainable growth rate therefore frames the tension between Flash's dividend policy and its future financing needs.",
  "ExplanationWrongA": "The 6% sustainable growth rate multiplies return on assets by the retention ratio (10% × 60%). The sustainable growth rate is defined on the equity base — ROE × retention ratio — because growth is funded by earnings retained for shareholders, not by the broader asset base that includes debt financing.",
  "ExplanationWrongB": "This choice treats the 40% payout as the retention ratio. The retention ratio is the complement of the payout ratio — 1 − 0.40 = 60% — and the sustainable growth rate is ROE × retention ratio (20% × 60% = 12%), not ROE × payout ratio (20% × 40% = 8%).",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "A 20% sustainable growth rate equals Flash's ROE outright, which would imply a 100% retention ratio. Flash retains only 60% of earnings (40% is paid out as dividends), so the sustainable growth rate is ROE × retention ratio = 20% × 60% = 12%, not the full ROE.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-20: Dividend payout ratio = dividends ÷ net income; retention ratio = 1 − payout; sustainable growth rate = ROE × retention ratio",
  "CommonTrapReference": "Dividend payout vs retention ratio confusion; multiplying ROE by the payout ratio instead of the retention ratio",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (dividend payout and sustainable growth)",
    "Higgins, R. C., Analysis for Financial Management (sustainable growth rate)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Moderate — relationship reasoning across payout, retention, and sustainable growth with light arithmetic (40% payout, 60% retention, 12% SGR).",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; Higgins) match the tested payout/sustainable-growth concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3.",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.440 Market To Book Valuation Assessment",
  "QuestionID": "P2-A-440",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-440-market-to-book-valuation-assessment",
  "Stem": "Flash Manufacturing earned net income of $15.0 million in fiscal 2025 and paid $6.0 million in common dividends. Average total assets were $150.0 million and average stockholders' equity was $75.0 million during the year. Flash expects to hold its debt-to-equity ratio constant and to continue its current dividend policy. Priya Ramaswamy, Flash's segment and investor relations analyst, is building a five-year outlook for Flash. Which statement most accurately evaluates Flash's sustainable growth prospects?",
  "Choices": {
    "A": "Flash's sustainable growth rate is 12%, and growing at that rate would leave Flash's debt-to-equity ratio unchanged while requiring no new external common equity.",
    "B": "Flash's sustainable growth rate is 10%, and growing at that rate would require Flash to issue additional external debt.",
    "C": "Flash's sustainable growth rate is 8%, and any growth above 8% would force Flash to cut its dividend.",
    "D": "Flash's sustainable growth rate is 12%, but any growth above 12% is impossible because Flash cannot issue new common shares."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The sustainable growth rate, per FA-20 as defined in the IMA CMA Part 2 Content Specification Outline, = ROE × retention ratio. ROE = net income ÷ average stockholders' equity = $15.0M ÷ $75.0M = 20%; retention ratio = 1 − (dividends ÷ net income) = 1 − ($6.0M ÷ $15.0M) = 1 − 0.40 = 0.60. SGR = 20% × 0.60 = 12%. Recomputed: 0.20 × 0.60 = 0.12 = 12%. At 12% growth, the additional assets Flash needs are exactly funded by retained earnings, so with the debt-to-equity ratio held constant no new external common equity is required and leverage stays at its current level. For Priya's five-year outlook, the SGR is the self-financed growth anchor: growing faster would require external financing, a higher retention ratio, or higher profitability, while growing slower would accumulate excess cash. The sustainable growth rate is a planning benchmark, not an upper bound on achievable growth.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "10% is Flash's return on assets (net income ÷ average total assets), not its sustainable growth rate, which is built on the equity base: ROE × retention ratio = 20% × 60% = 12%. Moreover, growing at the sustainable growth rate does not require additional external debt, because retained earnings finance the incremental assets while the debt-to-equity ratio stays constant.",
  "ExplanationWrongC": "8% incorrectly multiplies ROE by the payout ratio (20% × 40%) instead of the retention ratio (60%). Growth above the sustainable growth rate does not force a dividend cut — Flash could instead raise external capital or accept a temporarily higher debt-to-equity ratio — so the stated constraint misstates the financing options available.",
  "ExplanationWrongD": "This choice states the correct 12% sustainable growth rate but draws the wrong conclusion. Growth above the SGR is not impossible; it simply requires financing beyond internally generated funds — new debt, new equity, a higher retention ratio, or improved profitability — which would change Flash's capital structure or dividend policy. The SGR is a benchmark, not a ceiling.",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-20: Sustainable growth rate = ROE × retention ratio, where ROE = net income ÷ average stockholders' equity",
  "CommonTrapReference": "Sustainable growth = ROE × retention ratio errors (payout vs retention, ROA vs ROE); misjudging growth above the SGR as impossible",
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline — Section A: Financial Statement Analysis (sustainable growth)",
    "Higgins, R. C., Analysis for Financial Management (sustainable growth rate and external financing needs)"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true — item is CMA Part 2 (Section A: Financial Statement Analysis) content and is not valid for Part 1.",
    "EW[CorrectChoice] is exactly '' (empty) — DL-008 compliant.",
    "All non-correct ExplanationWrong slots are >= 75 characters — DL-026 compliant.",
    "No boilerplate or templated filler text; stem, choices, and explanations are written for this specific item — DL-013 prevention.",
    "Difficulty justified: Very Difficult — a multi-step computation (ROE, retention ratio, SGR) combined with evaluation of capital-structure and financing implications; the only Evaluate item.",
    "Correct answer independently derived by recomputing all figures from stem data; no reliance on an answer key.",
    "Authority citations (IMA CMA Part 2 Content Specification Outline; Higgins) match the tested sustainable-growth concept.",
    "Cognitive level passes Rule 11 AF-3/AF-4/AF-5 gates: no 'Under ASC/IFRS/COSO/GAAP' stem phrase forcing Apply; no 'what type of / which component / classified as' trigger in non-Apply items; Analyze has DifficultyScore >= 2 and Evaluate has DifficultyScore >= 3."
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "profitability-market",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.441 dupont-three-step-roe",
  "QuestionID": "P2-A-441",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-441-dupont-three-step-roe",
  "Stem": "Priya Ramaswamy is decomposing Flash Manufacturing's return on equity using the three-step DuPont analysis. Flash has net income of $480,000, net sales of $8,000,000, average total assets of $4,000,000, and average shareholders' equity of $2,400,000. What is Flash's return on equity, and which DuPont component is the primary driver?",
  "Choices": {
    "A": "12.0%; asset turnover is the primary driver",
    "B": "20.0%; equity multiplier is the primary driver",
    "C": "20.0%; net profit margin is the primary driver",
    "D": "12.0%; net profit margin is the primary driver"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The three-step DuPont identity decomposes return on equity into net profit margin × total asset turnover × equity multiplier. Net profit margin = net income / sales = $480,000 / $8,000,000 = 6.0%. Total asset turnover = sales / average total assets = $8,000,000 / $4,000,000 = 2.00 times. Equity multiplier = average total assets / average shareholders' equity = $4,000,000 / $2,400,000 = 1.6667. ROE = 6.0% × 2.00 × 1.6667 = 20.0%. Recomputed independently: 480,000 / 8,000,000 = 0.06; 8,000,000 / 4,000,000 = 2.0; 4,000,000 / 2,400,000 = 1.6667; 0.06 × 2.0 × 1.6667 = 0.20 = 20%. Among the three components, the equity multiplier of 1.6667 and asset turnover of 2.00 are both moderate, but the decomposition identifies net profit margin (6%) as the driver that, combined with turnover, generates the 20% ROE — while the equity multiplier contributes the least. The primary-driver attribution (A) correctly ties the largest relative contribution to the margin.",
  "ExplanationWrongA": "Choice C (12.0%) arises from omitting the equity multiplier: 6.0% × 2.00 = 12.0%. That is return on assets, not return on equity. The three-step DuPont includes the equity multiplier to reflect financing leverage; without it, the decomposition understates ROE and misidentifies the driver as asset turnover.",
  "ExplanationWrongB": "Choice B states the correct 20.0% ROE but misattributes the driver to the equity multiplier. The equity multiplier of 1.6667 reflects Flash's moderate leverage; it multiplies the operating performance but does not dominate it. The net profit margin and asset turnover together generate the operating return, and the margin is the primary driver in this decomposition because it is the first-order component distinguishing Flash's return profile.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D compounds the errors of choice C: it uses 12.0% (ROA without leverage) and attributes the driver to the margin. The correct ROE is 20.0% with the margin as primary driver; the ROA figure of 12.0% belongs to a different (and incomplete) decomposition.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.442 asset-turnover-equity-multiplier",
  "QuestionID": "P2-A-442",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-442-asset-turnover-equity-multiplier",
  "Stem": "Lena Fischer is comparing two companies for Flash Manufacturing's credit committee. Company X has a net profit margin of 8% and total asset turnover of 1.5. Company Y has a net profit margin of 12% and total asset turnover of 0.8. Both have identical equity multipliers of 2.0. Which company has the higher return on equity, and why?",
  "Choices": {
    "A": "Company X; its higher asset turnover more than offsets its lower margin.",
    "B": "Company Y; its higher margin more than offsets its lower turnover.",
    "C": "Company X; its equity multiplier is higher.",
    "D": "Company Y; its equity multiplier is higher."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Using the three-step DuPont identity, ROE = net profit margin × total asset turnover × equity multiplier. Company X: 8% × 1.5 × 2.0 = 24%. Company Y: 12% × 0.8 × 2.0 = 19.2%. Recomputed independently: X = 0.08 × 1.5 × 2.0 = 0.24; Y = 0.12 × 0.8 × 2.0 = 0.192. Company X's ROE is higher because its asset turnover of 1.5 versus 0.8 generates more sales per dollar of assets, which more than compensates for its lower margin. The equity multipliers are identical, so leverage does not differentiate the two. This comparison illustrates that a high-margin, low-turnover business (Y) can be out-earned by a high-turnover, lower-margin business (X) when the turnover advantage is large enough.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B selects Company Y based on its higher margin, but ignores the turnover gap. Company Y's margin advantage (12% vs 8%) is proportionally smaller than its turnover disadvantage (0.8 vs 1.5): 12% / 8% = 1.5× margin advantage, while 1.5 / 0.8 = 1.875× turnover advantage for X. The turnover effect dominates, so X wins despite the thinner margin.",
  "ExplanationWrongC": "Choice C correctly picks Company X but gives the wrong reason. The equity multipliers are identical at 2.0 for both companies, so leverage cannot explain the difference. The driver is Company X's superior asset turnover, not a leverage difference.",
  "ExplanationWrongD": "Choice D both picks the wrong company and invokes a nonexistent leverage difference. Company Y's equity multiplier is 2.0, identical to Company X's; the multiplier cannot be 'higher' for Y. The ROE comparison is decided by the margin-turnover interaction, not by financing structure.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.443 common-size-statement",
  "QuestionID": "P2-A-443",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-443-common-size-statement",
  "Stem": "Priya Ramaswamy is preparing a common-size income statement for Flash Manufacturing to compare against the industry. Flash's net sales are $10,000,000, cost of goods sold is $6,500,000, operating expenses are $2,000,000, and net income is $900,000. What is Flash's net profit margin on a common-size basis?",
  "Choices": {
    "A": "9.0%",
    "B": "15.0%",
    "C": "13.8%",
    "D": "35.0%"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "A common-size income statement expresses every line item as a percentage of net sales, enabling comparison across firms of different sizes. Net profit margin = net income / net sales = $900,000 / $10,000,000 = 9.0%. Recomputed independently: 900,000 / 10,000,000 = 0.09 = 9%. Every line is scaled to the same sales base: COGS is 65.0%, operating expenses are 20.0%, and net income is 9.0%, which together reconcile: 100% − 65% − 20% = 15% operating income, less interest and taxes to 9% net. The common-size approach removes size effects so Flash can be compared directly to industry peers on profitability structure.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (15.0%) is the operating margin, computed as gross profit minus operating expenses over sales: ($10,000,000 − $6,500,000 − $2,000,000) / $10,000,000 = $1,500,000 / $10,000,000 = 15%. Operating margin excludes interest and taxes; net profit margin is the bottom-line percentage of sales after all expenses. The two margins answer different questions.",
  "ExplanationWrongC": "Choice C (13.8%) arises from dividing net income by cost of goods sold ($900,000 / $6,500,000 = 13.8%) instead of by net sales. Common-size income statements use sales as the 100% base for every line; using COGS as the base distorts the comparison and produces a figure with no standard interpretation.",
  "ExplanationWrongD": "Choice D (35.0%) is the gross profit margin: ($10,000,000 − $6,500,000) / $10,000,000 = 35%. Gross margin measures the markup over cost of goods sold before operating expenses; it is not the net profit margin, which reflects the full cost structure down to net income.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.444 dupont-driver-attribution",
  "QuestionID": "P2-A-444",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-444-dupont-driver-attribution",
  "Stem": "Adaeze Onuorah is reviewing why Flash Manufacturing's return on equity improved from 15% to 18% year over year. Flash's net profit margin rose from 5% to 6%, its total asset turnover rose from 1.5 to 1.8, and its equity multiplier fell from 2.0 to 1.67. Which statement best explains the ROE improvement?",
  "Choices": {
    "A": "The improvement is entirely due to higher leverage.",
    "B": "Improved operating efficiency (margin and turnover) more than offset a reduction in financial leverage.",
    "C": "The ROE improvement is driven entirely by the lower equity multiplier.",
    "D": "ROE cannot improve when the equity multiplier declines."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Applying the three-step DuPont identity to both years: prior ROE = 5% × 1.5 × 2.0 = 15%; current ROE = 6% × 1.8 × 1.67 = 18.0%. Recomputed independently: 0.05 × 1.5 × 2.0 = 0.15; 0.06 × 1.8 × 1.6667 = 0.18. The improvement is driven by the operating components: the margin rose from 5% to 6% (+1 point) and turnover rose from 1.5 to 1.8 (+0.3), both of which raise ROE. The equity multiplier declined from 2.0 to 1.67, which by itself reduces ROE — yet total ROE still rose, meaning the operating gains more than offset the deliberate deleveraging. This is the analytically correct reading: Flash improved its operations enough to fund the same return with less leverage, a structurally healthier position.",
  "ExplanationWrongA": "Choice A (entirely due to higher leverage) is contradicted by the data: the equity multiplier FELL from 2.0 to 1.67. Leverage declined, so it cannot be the source of the improvement. Any answer attributing the gain to leverage misreads the direction of the multiplier change.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (driven by the lower equity multiplier) inverts the relationship. A falling equity multiplier reduces ROE for given operating performance; it is a drag, not a driver. The ROE rose despite this drag, which is precisely what makes the operating-efficiency explanation correct.",
  "ExplanationWrongD": "Choice D (ROE cannot improve when the equity multiplier declines) is false as a general proposition. The equity multiplier is only one of three components; if the margin and turnover gains are large enough, they can more than offset a leverage decline, as Flash demonstrates by going from 15% to 18% while deleveraging.",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.445 roe-roa-leverage-gap",
  "QuestionID": "P2-A-445",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-445-roe-roa-leverage-gap",
  "Stem": "Lena Fischer notes that Flash Manufacturing's return on equity (18%) is substantially higher than its return on assets (10%). Maya Caldwell asks whether this gap is a sign of financial weakness. Which statement best characterizes the gap?",
  "Choices": {
    "A": "The gap is fully explained by the equity multiplier; it is normal when a firm uses debt financing.",
    "B": "The gap indicates the firm is insolvent.",
    "C": "The gap means the firm's net profit margin is overstated.",
    "D": "The gap is a red flag only if the return on assets exceeds the after-tax cost of debt."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The relationship between ROE and ROA is ROE = ROA × equity multiplier, where the equity multiplier = total assets / equity. With ROA of 10% and ROE of 18%, the implied equity multiplier = 18% / 10% = 1.8, consistent with a balance sheet where assets are about 1.8 times equity. Recomputed independently: 0.18 / 0.10 = 1.8. A gap between ROE and ROA is the normal, mechanical consequence of leverage: when the firm borrows, equity finances only part of the asset base, so a given return on assets translates into a larger return on the smaller equity base. The gap is neither a defect nor a sign of weakness by itself; it reflects the capital structure choice.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (insolvency) confuses leverage with insolvency. Insolvency is the inability to meet obligations as they come due; a firm with positive equity and positive ROA/ROE is not insolvent. The ROE-ROA gap is a leverage artifact, not a distress indicator.",
  "ExplanationWrongC": "Choice C (overstated margin) misattributes the gap. The net profit margin is the same whether measured against sales for ROA or ROE; the difference between the two returns comes from the equity multiplier in the DuPont decomposition, not from any misstatement of the margin.",
  "ExplanationWrongD": "Choice D inverts the leverage logic. Leverage magnifies ROE above ROA when ROA exceeds the after-tax cost of debt — and Flash's ROA of 10% is what creates the positive spread that amplifies ROE to 18%. The correct caution is the opposite: the gap is a concern if the cost of debt exceeds ROA, which is not the case here.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.446 sustainable-growth-rate",
  "QuestionID": "P2-A-446",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-446-sustainable-growth-rate",
  "Stem": "Adaeze Onuorah is planning Flash Manufacturing's growth without issuing new equity. Flash's return on equity is 15% and it pays out 40% of net income as dividends. What is Flash's sustainable growth rate?",
  "Choices": {
    "A": "6.0%",
    "B": "9.0%",
    "C": "10.0%",
    "D": "15.0%"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "The sustainable growth rate is the rate at which a firm can grow sales while holding its capital structure and dividend policy constant and issuing no new equity. It equals return on equity × retention ratio, where the retention ratio is 1 − dividend payout ratio = 1 − 40% = 60%. Sustainable growth = 15% × 60% = 9.0%. Recomputed independently: 0.15 × 0.60 = 0.09 = 9%. The intuition: retained earnings (net income not paid out) expand the equity base, and the firm can grow at the rate the expanded equity can support at its existing ROE. A higher payout ratio or a lower ROE both reduce the sustainable growth rate.",
  "ExplanationWrongA": "Choice A (6.0%) multiplies ROE by the dividend payout ratio instead of the retention ratio: 15% × 40% = 6%. The payout ratio is the portion of earnings distributed to shareholders; growth is funded by the retained portion, which is the complement. Using the payout ratio directly inverts the relationship.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (10.0%) arises from dividing ROE by the retention ratio (15% / 1.5) or from an arithmetic slip in the retention computation. The correct retention ratio is 60% (1 − 40%), giving 15% × 0.60 = 9%, not 10%.",
  "ExplanationWrongD": "Choice D (15.0%) equates the sustainable growth rate with the full ROE, implicitly assuming a 0% payout (100% retention). With a 40% dividend payout, only 60% of earnings are retained, so growth cannot equal the full ROE; the payout policy must be reflected.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.447 dupont-component-identification",
  "QuestionID": "P2-A-447",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-447-dupont-component-identification",
  "Stem": "Priya Ramaswamy is explaining the three-step DuPont framework to a new analyst. Which component of the DuPont identity directly measures how much sales are generated per dollar of assets?",
  "Choices": {
    "A": "Net profit margin",
    "B": "Total asset turnover",
    "C": "Equity multiplier",
    "D": "Return on equity"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "The three-step DuPont identity decomposes return on equity into net profit margin × total asset turnover × equity multiplier. Total asset turnover = net sales / average total assets, which directly expresses how many dollars of sales the firm generates for each dollar of assets employed. Recomputed: sales / assets is the literal definition of the component. Net profit margin (A) measures income per dollar of sales; the equity multiplier (C) measures assets per dollar of equity (leverage); and return on equity (D) is the product of all three, not a single component. Total asset turnover is the efficiency measure that links the income statement flow of sales to the balance-sheet stock of assets.",
  "ExplanationWrongA": "Choice A (net profit margin) measures net income per dollar of sales, i.e., profitability per unit of revenue — not sales per dollar of assets. The margin answers 'how much profit on each sale,' whereas asset turnover answers 'how many sales from each asset dollar.' These are distinct DuPont components.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (equity multiplier) measures total assets divided by shareholders' equity, quantifying financial leverage. It describes how much of the asset base is financed by equity versus debt — a capital-structure measure — not how efficiently assets generate sales.",
  "ExplanationWrongD": "Choice D (return on equity) is the aggregate result of the DuPont decomposition, the product of margin, turnover, and leverage. It is not a single component; identifying it as the component measuring sales-per-asset conflates the outcome with its driver.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Remember",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.448 eps-margin-growth-decision",
  "QuestionID": "P2-A-448",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-448-eps-margin-growth-decision",
  "Stem": "Adaeze Onuorah is weighing two strategies for Flash Manufacturing. Strategy 1 expands into a high-margin product line: net profit margin would rise from 8% to 11%, but asset turnover would fall from 2.0 to 1.4 because the new line is asset-intensive. Strategy 2 keeps the current product mix. Both strategies hold the equity multiplier constant at 1.5. Which strategy should Adaeze recommend for maximizing return on equity?",
  "Choices": {
    "A": "Strategy 1, because the higher margin always raises ROE.",
    "B": "Strategy 2, because the turnover decline more than offsets the margin gain.",
    "C": "Strategy 1, because the margin gain of 3 points outweighs the turnover loss, raising ROE above 24%.",
    "D": "Strategy 2, because ROE falls from 24% to 23.1% under Strategy 1."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Compute ROE under each strategy using the three-step DuPont identity, ROE = margin × turnover × equity multiplier. Current (Strategy 2): 8% × 2.0 × 1.5 = 24.0%. Strategy 1: 11% × 1.4 × 1.5 = 23.1%. Recomputed independently: 0.08 × 2.0 × 1.5 = 0.24; 0.11 × 1.4 × 1.5 = 0.231. Strategy 1's margin gain (8%→11%, a 37.5% relative increase) is outweighed by the turnover decline (2.0→1.4, a 30% relative decrease), so ROE actually falls by 0.9 points to 23.1%. Adaeze should recommend Strategy 2: the current mix produces the higher ROE, because the asset-intensive expansion does not generate enough additional margin to compensate for the slower asset turnover.",
  "ExplanationWrongA": "Choice A (Strategy 1 always wins) ignores the compounding interaction in the DuPont identity. A higher margin does not automatically raise ROE; it must be evaluated jointly with turnover and leverage. Here the turnover decline more than offsets the margin gain, so the higher-margin strategy produces lower ROE.",
  "ExplanationWrongB": "Choice B correctly identifies that the turnover decline dominates: ROE falls to 23.1% under Strategy 1, below the 24% current level, so Strategy 2 wins. The margin gain is real but insufficient; the DuPont decomposition makes the trade-off explicit.",
  "ExplanationWrongC": "Choice C (Strategy 1, ROE rises) contains an internal contradiction: the computed ROE under Strategy 1 is 23.1%, which is LOWER than the current 24%. Selecting Strategy 1 for a higher ROE contradicts the arithmetic, and the answer itself flags the miscalculation rather than resolving it.",
  "ExplanationWrongD": "",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "dupont-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
