var pack_p2_a_part56 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.496 market-value-ratios",
  "QuestionID": "P2-A-496",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-496-market-value-ratios",
  "Stem": "Priya Ramaswamy is evaluating Flash Manufacturing's market performance for the investor report. Flash's market price per share is $45, book value per share is $30, and earnings per share is $3.00. Which pair correctly states Flash's price-to-book ratio and P/E ratio?",
  "Choices": {
    "A": "0.67 and 0.067",
    "B": "0.67 and 15.0",
    "C": "1.50 and 0.067",
    "D": "1.50 and 15.0"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The price-to-book ratio is market price per share divided by book value per share: $45 / $30 = 1.50. Recomputed independently: 45 / 30 = 1.5. The P/E ratio is market price per share divided by earnings per share: $45 / $3.00 = 15.0. Recomputed independently: 45 / 3 = 15. A price-to-book of 1.50 means the market values Flash at 1.5 times its accounting equity, and a P/E of 15 means investors pay $15 per dollar of earnings. Together these market-value ratios indicate the market's assessment of Flash's growth prospects and earnings quality relative to its accounting book value.",
  "ExplanationWrongA": "Choice D (0.67 and 0.067) contains both errors: the inverted price-to-book (book/market = 0.67) and the earnings yield instead of P/E (E/P = 0.067). Neither ratio is stated correctly; the correct pair is 1.50 and 15.0.",
  "ExplanationWrongB": "Choice B (0.67 and 15.0) inverts the price-to-book ratio: $30 / $45 = 0.67. Price-to-book is market price divided by book value (45/30 = 1.50); the inverse (book/market) is a different relationship and understates the market's valuation premium.",
  "ExplanationWrongC": "Choice C (1.50 and 0.067) has the correct price-to-book but converts the P/E to its reciprocal: $3.00 / $45 = 0.067, the earnings yield. The P/E is $45 / $3.00 = 15.0; mixing the earnings yield in place of the P/E misstates the valuation multiple.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.497 profitability-driver-analysis",
  "QuestionID": "P2-A-497",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-497-profitability-driver-analysis",
  "Stem": "Adaeze Onuorah is investigating why Flash Manufacturing's gross profit margin declined from 40% to 32% while its net profit margin held steady at 8%. Which explanation is most consistent with these observations?",
  "Choices": {
    "A": "Operating expenses as a percentage of sales declined, offsetting the lower gross margin.",
    "B": "Operating expenses as a percentage of sales increased.",
    "C": "The decline in gross margin must also reduce the net margin.",
    "D": "Interest expense increased sharply."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The gross profit margin fell from 40% to 32% — an 8-point decline at the gross level. Yet the net profit margin held at 8%, meaning the difference between gross and net margin narrowed: operating expenses (and other items between gross profit and net income) must have fallen as a percentage of sales by roughly the same 8 points. Recomputed: if gross margin is 32% and net margin is 8%, the intermediate expenses are 24% of sales; previously, 40% gross and 8% net meant 32% of sales in intermediate expenses. The decline from 32% to 24% of sales in operating expenses offsets the gross-margin erosion, keeping the net margin constant. This is the analytically consistent explanation: the company improved cost control below the gross line while facing margin pressure at the product level.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (operating expenses increased as % of sales) is inconsistent with the data. If operating expenses rose as a percentage of sales while the gross margin fell, the net margin would decline — but it held steady. The only way the net margin stays at 8% when the gross margin falls is for intermediate expenses to fall as a percentage of sales.",
  "ExplanationWrongC": "Choice C (gross decline must reduce net margin) ignores the possibility of offsetting improvements below the gross line. The gross and net margins are linked, but the intermediate expense structure can change; a gross-margin decline does not mechanically force a net-margin decline.",
  "ExplanationWrongD": "Choice D (interest expense increased) would push the net margin DOWN, not hold it steady. Higher interest expense reduces net income for a given gross margin and operating expense structure, compounding the gross-margin decline rather than offsetting it.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.498 comprehensive-income",
  "QuestionID": "P2-A-498",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-498-comprehensive-income",
  "Stem": "Maya Caldwell is reviewing Flash Manufacturing's comprehensive income for the annual report. Flash's net income is $7,000,000. Unrealized gains on available-for-sale securities are $500,000, and foreign currency translation gains are $300,000. What is Flash's comprehensive income?",
  "Choices": {
    "A": "$7,000,000",
    "B": "$7,500,000",
    "C": "$6,200,000",
    "D": "$7,800,000"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Comprehensive income includes net income plus other comprehensive income (OCI) items — revenues, expenses, gains, and losses that are excluded from net income under GAAP. OCI items include unrealized gains and losses on available-for-sale securities and foreign currency translation adjustments. For Flash: comprehensive income = net income + unrealized gains on AFS securities + translation gains = $7,000,000 + $500,000 + $300,000 = $7,800,000. Recomputed independently: 7,000,000 + 500,000 = 7,500,000; 7,500,000 + 300,000 = 7,800,000. Comprehensive income provides a broader measure of the change in equity from non-owner sources, capturing items that bypass the income statement.",
  "ExplanationWrongA": "Choice D ($7,000,000) ignores OCI entirely, equating comprehensive income with net income. Comprehensive income is net income PLUS other comprehensive income; omitting the $800,000 of OCI items understates the measure.",
  "ExplanationWrongB": "Choice B ($7,500,000) includes only the unrealized gains on securities, omitting the translation gains: $7,000,000 + $500,000 = $7,500,000. Both the AFS gains and the translation gains are OCI items and must be added to net income to arrive at comprehensive income.",
  "ExplanationWrongC": "Choice C ($6,200,000) subtracts the OCI items: $7,000,000 − $500,000 − $300,000 = $6,200,000. OCI gains are ADDED to net income in computing comprehensive income; subtracting them treats unrealized gains as losses and understates total comprehensive income.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.499 ratio-consistency-limitation",
  "QuestionID": "P2-A-499",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-499-ratio-consistency-limitation",
  "Stem": "Lena Fischer is comparing Flash Manufacturing's ratios to the industry benchmark published by a trade association. Flash's inventory turnover is 6.5, but the industry average is 8.0. Before concluding Flash has an inventory problem, which limitation of ratio analysis should Lena consider first?",
  "Choices": {
    "A": "Differences in accounting methods (e.g., FIFO vs LIFO) and fiscal-year timing between Flash and the benchmark.",
    "B": "The industry average is always the correct target regardless of context.",
    "C": "Ratio analysis is only valid for service companies.",
    "D": "A higher turnover is always better, so Flash is underperforming."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Ratio analysis has well-documented limitations, including differences in accounting methods, fiscal-year timing, industry classification, and company size. Flash's inventory turnover of 6.5 versus the industry 8.0 may reflect differences in inventory costing (FIFO vs LIFO affects inventory carrying values and COGS), fiscal year-end timing (a December year-end vs June year-end captures different seasonal inventory levels), or the composition of the 'industry' benchmark. Before concluding Flash has an inventory-management problem, Lena must verify the comparability of the underlying data — whether Flash and the benchmark use consistent accounting policies, time periods, and definitions. An apparent ratio gap can be an artifact of measurement differences rather than a genuine performance deficiency.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (industry average always correct) ignores the comparability issue. The industry average is a summary statistic that may not be an appropriate target if the benchmark's composition, methods, or timing differ from Flash's. Benchmarks are reference points, not universal truths.",
  "ExplanationWrongC": "Choice C (ratio analysis only for service companies) is false. Ratio analysis applies broadly to manufacturing, retail, service, and financial firms, with appropriate industry-specific interpretations. This limitation claim is simply incorrect.",
  "ExplanationWrongD": "Choice D (higher always better) is an oversimplification. A very high inventory turnover can indicate inventory stockouts and lost sales, just as a low one can indicate overstocking. The appropriate level depends on the industry and business model; higher is not unconditionally better.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.500 integrative-ratio-verdict",
  "QuestionID": "P2-A-500",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-500-integrative-ratio-verdict",
  "Stem": "Adaeze Onuorah must give the board a final assessment of Flash Manufacturing's financial health. Flash's current ratio is 1.8, quick ratio is 1.1, debt-to-equity ratio is 1.2, times-interest-earned is 5.0, net profit margin is 9%, and return on equity is 18%. Which statement best synthesizes Flash's financial position?",
  "Choices": {
    "A": "No conclusion can be drawn without the statement of cash flows.",
    "B": "Flash is illiquid and insolvent, with declining profitability.",
    "C": "Flash's liquidity is strong, but its profitability and coverage are dangerously weak.",
    "D": "Flash is liquid and profitable, with moderate leverage and comfortable interest coverage."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Synthesizing the full ratio set: a current ratio of 1.8 and quick ratio of 1.1 indicate healthy short-term liquidity (current assets comfortably exceed current liabilities, and even the more conservative quick assets exceed them). A debt-to-equity ratio of 1.2 reflects moderate leverage — Flash has 20% more debt than equity, which is elevated but not extreme. Times-interest-earned of 5.0 indicates Flash generates five times its interest cost in operating earnings, providing a solid coverage cushion. The net profit margin of 9% and ROE of 18% show profitability that is solid, with the ROE enhanced by moderate leverage. Together, the ratios paint a picture of a liquid, profitable company with moderate leverage and comfortable coverage — the basis for a favorable overall assessment, with the caveat that trend and cash-flow analysis would complete the picture.",
  "ExplanationWrongA": "Choice D (no conclusion without cash flow) overstates the data requirement. While the statement of cash flows would add valuable information, the ratio set provided is sufficient to reach a well-supported preliminary assessment. Declining to draw any conclusion forfeits the analytical value of the data.",
  "ExplanationWrongB": "Choice B (illiquid, insolvent, declining profitability) is contradicted by every ratio in the set. The current and quick ratios show liquidity, the leverage and coverage ratios show manageable solvency, and the margin and ROE show profitability. None of the data support a distressed characterization.",
  "ExplanationWrongC": "Choice C (strong liquidity but weak profitability and coverage) misreads the profitability and coverage figures. A 9% net margin, 18% ROE, and 5.0 TIE are not weak; they indicate solid earnings and comfortable interest coverage. The synthesis in this choice contradicts the data.",
  "ExplanationWrongD": "",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
