var pack_p2_a_part48 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.410 debt-to-equity interpretation",
  "QuestionID": "P2-A-410",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-410-debt-to-equity-interpretation",
  "Stem": "Lena Fischer, a credit analyst at Flash Manufacturing, is explaining to a new hire why she tracks the company's debt-to-equity ratio before recommending trade credit terms. Which statement most accurately describes what the debt-to-equity ratio measures?",
  "Choices": {
    "A": "It measures how efficiently Flash converts sales revenue into net income.",
    "B": "It reports the percentage of Flash's assets that are financed by borrowed funds.",
    "C": "It shows how many times Flash's operating income covers its annual interest expense.",
    "D": "It compares creditor financing with owner financing, with higher values indicating heavier reliance on debt and greater default risk."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The debt-to-equity ratio, computed as total liabilities divided by total stockholders' equity, compares the financing Flash Manufacturing's creditors provide with the financing its owners provide, using the balance sheet classifications presented under U.S. GAAP (ASC 470 and ASC 505). Because debt carries contractual claims for interest and principal that must be satisfied before equity holders receive anything, a higher ratio indicates a thinner equity cushion to absorb losses and therefore greater financial risk. For a credit analyst such as Lena Fischer, the ratio is a starting point for judging capital structure; she then layers on coverage measures such as times-interest-earned and cash flow from operations to determine whether Flash's earnings are sufficient to service those fixed claims on a timely basis.",
  "ExplanationWrongA": "Profit margin (net income divided by sales) measures operating efficiency, not capital structure; while profitability affects Flash's ability to service debt, the debt-to-equity ratio specifically compares creditor claims with owners' equity rather than measuring how profitably sales are converted into income.",
  "ExplanationWrongB": "Total liabilities divided by total assets is the debt (liabilities-to-assets) ratio, which expresses the percentage of assets financed by debt; the debt-to-equity ratio instead compares total liabilities with stockholders' equity and can exceed 100 percent because it is not bounded by the value of Flash's assets.",
  "ExplanationWrongC": "Times-interest-earned (EBIT divided by interest expense) is a coverage ratio that measures Flash's ability to pay interest from operating earnings; it answers a liquidity and coverage question, whereas the debt-to-equity ratio describes the mix of financing sources on the balance sheet and contains no information about earnings levels.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-06: Debt-to-Equity",
  "CommonTrapReference": "Confusing debt-to-equity (D/E) with the debt ratio (liabilities/assets) and with times-interest-earned",
  "Authorities": [
    "ASC 470",
    "ASC 505"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.411 equity-multiplier",
  "QuestionID": "P2-A-411",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-411-equity-multiplier",
  "Stem": "Adaeze Onuorah, CFO of Flash Manufacturing, reviews the balance sheet and sees total assets of $2,400,000 and total stockholders' equity of $800,000. What is Flash Manufacturing's equity multiplier?",
  "Choices": {
    "A": "0.33",
    "B": "2.0",
    "C": "3.0",
    "D": "1.5"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The equity multiplier is a balance-sheet leverage measure computed as total assets divided by total stockholders' equity, using the classifications presented under U.S. GAAP (ASC 505). Recomputed: Equity multiplier = Total assets / Total stockholders' equity = $2,400,000 / $800,000 = 3.0. Flash Manufacturing's multiplier of 3.0 means each dollar of stockholders' equity supports $3.00 of assets; the remaining $1,600,000 of financing is creditor claims, which implies a debt-to-equity ratio of 2.0. In DuPont analysis the multiplier shows how financial leverage magnifies return on equity: a higher multiplier raises ROE when assets are profitable but amplifies losses when they are not.",
  "ExplanationWrongA": "0.33 inverts the ratio by dividing equity by assets ($800,000 / $2,400,000), which computes the equity-to-assets (proprietary) ratio rather than the equity multiplier; it understates Flash's leverage because the equity multiplier must exceed 1.0 whenever any debt is present in the capital structure.",
  "ExplanationWrongB": "2.0 is Flash's debt-to-equity ratio, computed as total liabilities of $1,600,000 divided by equity of $800,000; the equity multiplier instead divides total assets by equity, so the correct value must exceed 1.0 by an amount that reflects the leverage already embedded in Flash's capital structure.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "1.5 divides total assets by total liabilities ($2,400,000 / $1,600,000), reversing the leverage relationship by placing creditor claims in the denominator; the equity multiplier's denominator is stockholders' equity, so this figure does not measure how much asset support each dollar of equity provides.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-07: Equity Multiplier",
  "CommonTrapReference": "Confusing the equity multiplier with debt-to-equity; using the inverse (equity/assets) or dividing assets by liabilities",
  "Authorities": [
    "ASC 505"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Recomputed line matches CorrectChoice"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.412 times-interest-earned",
  "QuestionID": "P2-A-412",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-412-times-interest-earned",
  "Stem": "Lena Fischer, a credit analyst at Flash Manufacturing, is reviewing the income statement, which shows operating income (EBIT) of $360,000 and interest expense of $90,000. What is Flash Manufacturing's times-interest-earned ratio?",
  "Choices": {
    "A": "0.25",
    "B": "5.0",
    "C": "3.0",
    "D": "4.0"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Times-interest-earned (TIE) measures how many times Flash Manufacturing's operating earnings cover its interest obligations and is computed as EBIT divided by interest expense, using income statement amounts presented under U.S. GAAP (ASC 220; interest per ASC 470). Recomputed: TIE = EBIT / Interest expense = $360,000 / $90,000 = 4.0. Flash generates $4.00 of operating income for every $1.00 of interest it owes, so EBIT would have to fall roughly 75 percent before it failed to cover current interest. Lena Fischer views a TIE of 4.0 as a reasonable cushion, though she supplements it with the cash coverage ratio because TIE ignores noncash charges and principal repayments.",
  "ExplanationWrongA": "0.25 inverts the ratio by dividing interest expense by EBIT ($90,000 / $360,000), which measures the proportion of operating income consumed by interest (the interest burden), not how many times Flash can cover its interest obligations from operating earnings.",
  "ExplanationWrongB": "5.0 adds interest expense to EBIT ($450,000 / $90,000), counting the same interest cost twice; EBIT already represents all operating earnings before interest, so the correct numerator is $360,000, and inflating it overstates Flash's true interest coverage.",
  "ExplanationWrongC": "3.0 subtracts interest from EBIT before dividing ($270,000 / $90,000), using earnings before tax as the numerator; TIE is deliberately computed with EBIT, before interest is deducted, because the numerator must represent the earnings available to pay interest rather than what remains after paying it.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-08: Times-Interest-Earned",
  "CommonTrapReference": "Using EBT or net income instead of EBIT as the numerator; inverting the ratio (interest/EBIT)",
  "Authorities": [
    "ASC 220",
    "ASC 470"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Recomputed line matches CorrectChoice",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.413 operating-leverage",
  "QuestionID": "P2-A-413",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-413-operating-leverage",
  "Stem": "Adaeze Onuorah, CFO of Flash Manufacturing, wants to quantify how sensitive operating income is to a change in sales. Flash sells its product at $40 per unit, incurs variable costs of $24 per unit, has fixed operating costs of $200,000, and currently sells 25,000 units. What is Flash Manufacturing's degree of operating leverage at the current sales level?",
  "Choices": {
    "A": "0.5",
    "B": "3.0",
    "C": "5.0",
    "D": "2.0"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The degree of operating leverage (DOL) at a given sales level equals contribution margin divided by operating income (EBIT); it measures how a percentage change in sales flows through to a larger percentage change in operating income, an effect driven by fixed operating costs. Recomputed: Contribution margin per unit = $40 - $24 = $16; total contribution margin = $16 x 25,000 units = $400,000; EBIT = $400,000 - $200,000 fixed costs = $200,000; DOL = $400,000 / $200,000 = 2.0. If Flash's unit sales change by 10 percent, operating income will change by 20 percent. Adaeze Onuorah can use this result to anticipate earnings swings: the higher the DOL, the more operating income and cash flow react to sales volatility.",
  "ExplanationWrongA": "0.5 divides EBIT by contribution margin ($200,000 / $400,000), inverting the operating leverage relationship; the degree of operating leverage must exceed 1.0 whenever Flash carries fixed operating costs, because those costs magnify the percentage change in operating income relative to the percentage change in sales.",
  "ExplanationWrongB": "3.0 adds contribution margin to operating income ($600,000 / $200,000), counting the contribution available to cover fixed costs twice; the correct numerator is contribution margin alone ($400,000), and dividing it by EBIT of $200,000 yields a degree of operating leverage of 2.0.",
  "ExplanationWrongC": "5.0 divides total sales revenue by EBIT ($1,000,000 / $200,000), using revenue rather than contribution margin as the numerator; DOL relates the earnings available to cover fixed costs (contribution margin) to operating income, not total sales, so a revenue-based figure overstates Flash's sensitivity to volume changes.",
  "ExplanationWrongD": "",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-09: Operating Leverage",
  "CommonTrapReference": "Using total sales instead of contribution margin as the numerator; forgetting that fixed costs force DOL above 1.0",
  "Authorities": [
    "ASC 220"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Recomputed line matches CorrectChoice",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.414 financial-leverage",
  "QuestionID": "P2-A-414",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-414-financial-leverage",
  "Stem": "Lena Fischer, a credit analyst, is evaluating two financing plans for Flash Manufacturing. Both plans are expected to generate EBIT of $300,000; Plan 1 carries interest expense of $60,000 and Plan 2 carries interest expense of $120,000. Which statement correctly describes the degree of financial leverage under each plan and its implication for Flash's shareholders?",
  "Choices": {
    "A": "Both plans have a DFL of 1.00 because the degree of financial leverage depends only on EBIT, not on interest expense.",
    "B": "Plan 1 has a DFL of 1.67 and Plan 2 has a DFL of 1.25; Plan 1's EPS will fluctuate more for a given percentage change in EBIT.",
    "C": "Plan 1 has a DFL of 1.25 and Plan 2 has a DFL of 1.67; Plan 2's EPS will fluctuate more for a given percentage change in EBIT.",
    "D": "Plan 1 has a DFL of 1.25 and Plan 2 has a DFL of 1.67; the higher-leverage plan will produce higher EPS at every level of EBIT."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The degree of financial leverage (DFL) equals EBIT divided by earnings before tax (EBT), and it shows how fixed interest charges magnify the effect of an EBIT change on the residual earnings available to shareholders. Recomputed: Plan 1, DFL = $300,000 / ($300,000 - $60,000) = $300,000 / $240,000 = 1.25. Plan 2, DFL = $300,000 / ($300,000 - $120,000) = $300,000 / $180,000 = 1.67. Under Plan 2, a 10 percent change in EBIT changes EPS by 16.7 percent, versus 12.5 percent under Plan 1. Higher financial leverage therefore magnifies shareholders' returns in good years and their losses in bad ones, so Lena Fischer would weigh that added volatility against the potential for higher EPS.",
  "ExplanationWrongA": "This choice assumes DFL equals 1.00 because it ignores interest entirely; financial leverage arises precisely because fixed interest charges magnify the effect of EBIT changes on residual earnings — with zero debt DFL would be 1.00, but Plan 2's $120,000 interest obligation makes its DFL materially exceed 1.00.",
  "ExplanationWrongB": "This choice swaps the two computed values; Plan 1's earnings before tax are $240,000, so its DFL is 1.25, while Plan 2's EBT of $180,000 produces a DFL of 1.67 — the plan with the higher interest burden carries the higher financial leverage and the greater earnings-per-share sensitivity.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "This choice pairs correct DFL values with an overbroad conclusion; higher leverage magnifies EPS changes in both directions, so Plan 2 produces higher EPS only when EBIT is above the indifference point and produces lower EPS or losses when EBIT falls — leverage raises risk, it does not guarantee higher EPS at every operating level.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-10: Financial Leverage",
  "CommonTrapReference": "Assuming DFL equals 1.0 whenever EBIT is fixed; concluding that higher leverage always raises EPS rather than increasing EPS sensitivity in both directions",
  "Authorities": [
    "ASC 220",
    "ASC 470"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Recomputed line matches CorrectChoice",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.415 cash-coverage",
  "QuestionID": "P2-A-415",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-415-cash-coverage",
  "Stem": "Lena Fischer, a credit analyst at Flash Manufacturing, notes that times-interest-earned can overstate Flash's ability to service its debt because the ratio ignores noncash charges such as depreciation and amortization. Which ratio directly addresses that weakness by adjusting the numerator?",
  "Choices": {
    "A": "Equity multiplier, computed as total assets / total stockholders' equity.",
    "B": "Debt-to-equity ratio, computed as total liabilities / total stockholders' equity.",
    "C": "Cash coverage ratio, computed as (EBIT + noncash charges) / interest expense.",
    "D": "Degree of financial leverage, computed as EBIT / (EBIT - interest expense)."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The cash coverage ratio, computed as (EBIT + noncash charges) / interest expense, restores depreciation and amortization that were deducted in arriving at EBIT, because those charges reduce reported income without consuming cash (ASC 230 for cash flows; interest obligations per ASC 470). Times-interest-earned understates the cash available to pay interest precisely because its numerator is net of those noncash charges. For a credit analyst such as Lena Fischer, cash coverage is a better approximation of whether Flash Manufacturing can service its interest from internally generated funds, although it still excludes principal repayments, taxes, and capital expenditures — so she reviews the statement of cash flows before finalizing any credit recommendation.",
  "ExplanationWrongA": "The equity multiplier (total assets / total stockholders' equity) is a DuPont leverage factor showing how much asset base each dollar of equity supports; like debt-to-equity it is a balance-sheet measure that contains no cash-flow information and therefore cannot address the noncash-charge weakness in times-interest-earned.",
  "ExplanationWrongB": "The debt-to-equity ratio describes Flash's financing mix — creditor claims relative to owners' equity — but says nothing about the cash generated to service those claims; it is a balance-sheet leverage measure, not a coverage measure, so it cannot reveal whether operating cash flow covers interest obligations.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "The degree of financial leverage measures how sensitive Flash's earnings per share are to a given percentage change in EBIT; it captures the magnification effect of fixed interest costs but does not measure the cash available to pay interest, so it does not correct the noncash-charge omission that concerns Lena Fischer.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-08: Times-Interest-Earned (Cash Coverage)",
  "CommonTrapReference": "Relying on TIE alone and forgetting that depreciation and amortization are noncash charges; confusing cash coverage with balance-sheet leverage measures",
  "Authorities": [
    "ASC 230",
    "ASC 470"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.416 financial-leverage-evaluation",
  "QuestionID": "P2-A-416",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-416-financial-leverage-evaluation",
  "Stem": "Adaeze Onuorah, CFO of Flash Manufacturing, is evaluating a proposal to replace $1,000,000 of equity financing with debt carrying a 10% interest rate. Flash currently expects EBIT of $1,200,000, pays interest of $150,000, faces a 30% tax rate, and has 200,000 shares outstanding. If the swap is executed, annual interest rises to $250,000 and Flash repurchases 25% of its shares with the proceeds. Assuming EBIT remains at $1,200,000, what is the effect on EPS, and what is the most appropriate conclusion for Adaeze?",
  "Choices": {
    "A": "EPS rises from $3.68 to $4.43, so the swap clearly improves shareholder value regardless of what happens to operating income.",
    "B": "EPS stays at $3.68 because the additional interest expense is exactly offset by the reduction in shares outstanding.",
    "C": "EPS falls from $3.68 to $3.33, so the swap would dilute Flash's existing shareholders.",
    "D": "EPS rises from $3.68 to $4.43, but the gain must be weighed against the higher sensitivity of EPS to a decline in EBIT."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Evaluating the swap requires tracing the effect of higher interest and a smaller share base through the GAAP-based income statement (ASC 220; interest per ASC 470). Recomputed: Before — EBT = $1,200,000 - $150,000 = $1,050,000; tax at 30% = $315,000; net income = $735,000; EPS = $735,000 / 200,000 shares = $3.68. After — EBT = $1,200,000 - $250,000 = $950,000; tax = $285,000; net income = $665,000; shares = 150,000; EPS = $665,000 / 150,000 = $4.43. EPS rises roughly 21 percent, but the degree of financial leverage climbs from 1.14 to 1.26, so a 10 percent drop in EBIT now cuts EPS by about 12.6 percent instead of 11.4 percent. Because the higher EPS is contingent on EBIT holding at $1,200,000, Adaeze Onuorah should approve the swap only if Flash's operating earnings are stable enough to make the added interest risk acceptable.",
  "ExplanationWrongA": "Although the EPS figures ($3.68 to $4.43) are computed correctly, the conclusion ignores the cost of added risk; the higher interest burden raises Flash's degree of financial leverage, so the EPS gains reverse quickly if EBIT falls — declaring the swap clearly superior at every operating level ignores the downside that leverage creates.",
  "ExplanationWrongB": "This choice assumes the higher interest charge and the share reduction exactly cancel, leaving EPS unchanged; the arithmetic does not support that — interest rises $100,000, reducing after-tax earnings by $70,000, while the share base shrinks 25 percent, and the combined effect lifts EPS from $3.68 to $4.43 instead of holding it flat.",
  "ExplanationWrongC": "This choice reports EPS falling to $3.33, an error caused by dividing after-tax income of $665,000 by the original 200,000 shares; the $1,000,000 equity repurchase reduces the share count to 150,000, and dividing by that reduced count shows EPS actually rises to $4.43 — the repurchase concentrates the same earnings on fewer shares rather than diluting them.",
  "ExplanationWrongD": "",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-10: Financial Leverage",
  "CommonTrapReference": "Judging the financing decision on current EPS alone while ignoring the rise in the degree of financial leverage; forgetting to reduce the share count after a repurchase",
  "Authorities": [
    "ASC 220",
    "ASC 470"
  ],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Recomputed line matches CorrectChoice",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "leverage-coverage",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.417 working-capital-policy-tradeoff",
  "QuestionID": "P2-A-417",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-417-working-capital-policy-tradeoff",
  "Stem": "Flash Manufacturing's CFO, Adaeze Onuorah, is reviewing the company's working capital policy with the controller, Mariela Hoffmann. Flash has stable, predictable customer demand but operates with thin cash reserves. Adaeze notes that moving to a more aggressive working capital policy would reduce the cash conversion cycle and lower the amount of capital tied up in current assets. Which statement best describes the primary consequence of adopting a more aggressive working capital policy?",
  "Choices": {
    "A": "It increases the expected return on assets by holding larger cash and marketable-security balances.",
    "B": "It raises the current ratio because a larger share of financing comes from long-term sources.",
    "C": "It lowers the current ratio and increases the risk of a liquidity shortfall, while raising expected return on assets.",
    "D": "It has no effect on either liquidity risk or profitability because the policy affects only the maturity of financing."
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Working capital policy determines the level of investment in current assets and the maturity structure of the financing for those assets. An aggressive policy minimizes investment in cash, marketable securities, and inventory, financing current assets with short-term debt rather than long-term sources. Because current assets typically earn returns below the firm's cost of capital, reducing them raises expected return on assets. The trade-off is that smaller current-asset buffers and heavier reliance on short-term, rollover-sensitive financing increase the risk that the firm cannot meet obligations as they come due. This is the standard risk-return trade-off in working capital management under the IMA CMA Part 2 framework. Adaeze's observation that the cash conversion cycle shortens is consistent with this: faster conversion means less capital committed to receivables and inventory, but also less cushion.",
  "ExplanationWrongA": "This choice confuses the mechanism. Holding larger cash and marketable-security balances is the conservative approach, and those low-yielding liquid assets depress rather than raise return on assets. The aggressive policy achieves higher expected returns precisely by cutting these idle balances, not by increasing them.",
  "ExplanationWrongB": "This choice reverses the direction of the effect. An aggressive policy relies more heavily on short-term financing and holds fewer current assets, which LOWERS the current ratio, not raises it. Long-term financing is the hallmark of a conservative policy, which is why the conservative approach sustains a higher current ratio at the cost of lower return on assets.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "This choice denies the trade-off entirely. The maturity structure of financing directly affects both liquidity risk and profitability: short-term financing is cheaper but must be rolled over, exposing the firm to refinancing risk and potential liquidity shortfall, while long-term financing is more expensive but more stable. The policy choice therefore affects both dimensions.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->C via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, per-100 C rebalance (C10->22) + streak kill, chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.418 defensive-interval-ratio",
  "QuestionID": "P2-A-418",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-418-defensive-interval-ratio",
  "Stem": "Mariela Hoffmann, controller of Flash Manufacturing, is assessing how long the company could operate on its most liquid assets if cash inflows stopped. At year-end, Flash holds cash of $450,000, short-term marketable securities of $300,000, and net accounts receivable of $600,000. Flash's average daily operating expenditures, excluding noncash charges such as depreciation, are $75,000. What is Flash's defensive interval ratio in days?",
  "Choices": {
    "A": "10 days",
    "B": "24 days",
    "C": "6 days",
    "D": "18 days"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The defensive interval ratio measures the number of days a firm can cover its daily operating expenditures using its defensive (quick) assets alone, without additional inflows. Defensive assets = cash + marketable securities + net accounts receivable = $450,000 + $300,000 + $600,000 = $1,350,000. Daily operating expenditures, excluding noncash charges, are $75,000. Defensive interval = $1,350,000 / $75,000 = 18 days. Recomputed independently: 450,000 + 300,000 + 600,000 = 1,350,000; 1,350,000 / 75,000 = 18.0. The correct interpretation for Mariela is that Flash could sustain roughly eighteen days of normal operations from its defensive assets before needing new inflows. Inventory is excluded because converting it to cash requires a sale cycle, and prepaids are excluded because they are consumed, not converted to cash.",
  "ExplanationWrongA": "Choice A (10 days) omits accounts receivable from the defensive asset base: ($450,000 + $300,000) / $75,000 = 10 days. Net receivables ARE included in defensive assets because they are convertible to cash within the normal collection cycle. Omitting them understates the true defensive interval by eight days.",
  "ExplanationWrongB": "Choice D (24 days) reaches $1,800,000 / $75,000 by adding a non-defensive item to the asset base, most plausibly inventory carried at $450,000 or prepaid expenses. Inventory and prepaids are excluded from the defensive interval because they are not immediately convertible to cash; including them overstates Flash's resilience.",
  "ExplanationWrongC": "Choice C (6 days) uses only cash: $450,000 / $75,000 = 6 days. This understates the interval by excluding marketable securities and net receivables, both of which are legitimately defensive assets available to meet daily operating outlays without a sale cycle.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.419 inventory-credit-current-ratio",
  "QuestionID": "P2-A-419",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-419-inventory-credit-current-ratio",
  "Stem": "Flash Manufacturing's controller, Mariela Hoffmann, is projecting the effect of a planned purchase on the company's liquidity metrics. Flash currently has a current ratio of 2.0, with current assets of $2,000,000 and current liabilities of $1,000,000. Flash purchases $500,000 of raw materials on account, increasing both inventory and accounts payable by $500,000. What is the combined effect on Flash's current ratio and working capital?",
  "Choices": {
    "A": "Current ratio increases and working capital increases.",
    "B": "Current ratio increases and working capital is unchanged.",
    "C": "Current ratio decreases and working capital decreases.",
    "D": "Current ratio decreases and working capital is unchanged."
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Purchasing inventory on account increases both a current asset (inventory) and a current liability (accounts payable) by the same $500,000. Working capital, defined as current assets minus current liabilities, is therefore unchanged: ($2,000,000 + $500,000) − ($1,000,000 + $500,000) = $2,500,000 − $1,500,000 = $1,000,000, identical to the starting $2,000,000 − $1,000,000 = $1,000,000. The current ratio, however, moves toward 1.0 because equal absolute increases in numerator and denominator compress the ratio when it exceeds 1: $2,500,000 / $1,500,000 = 1.67, down from 2.0. Recomputed independently: 2,500,000 / 1,500,000 = 1.6667. This distinction — equal dollar changes leave working capital intact but always pull a ratio greater than 1 toward 1 — is the key liquidity insight Mariela needs for the projection.",
  "ExplanationWrongA": "Choice A incorrectly treats the equal $500,000 increase in current assets and current liabilities as raising the current ratio. Because the ratio exceeds 1.0, adding the same amount to numerator and denominator moves the ratio toward 1.0, so it decreases. Working capital also does not increase; the equal increases leave the difference unchanged.",
  "ExplanationWrongB": "Choice D correctly holds working capital constant but reverses the ratio effect. Financing the inventory with a credit purchase adds to both sides of the current ratio; when the starting ratio is greater than 1, an equal-dollar addition to both sides reduces the ratio, not increases it.",
  "ExplanationWrongC": "Choice C correctly identifies that the current ratio decreases but wrongly concludes working capital falls. The $500,000 rise in inventory is fully offset by the $500,000 rise in accounts payable, leaving current assets minus current liabilities exactly where it started. Working capital only changes when the two sides move by different amounts.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "liquidity-solvency-integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
