var pack_p2_a_part23 = [
{
  "QuestionID": "P2-A-195",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.8",
  "Topic": "A.195 combined-leverage-eps-impact",
  "UniqueConceptKey": "A-195-combined-leverage-propagation",
  "Authorities": [
    "Corporate finance theory (DOL/DFL combined leverage framework)"
  ],
  "FormulaReference": "FA-19",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Analyze",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CommonTrapReference": "Applying DOL and DFL additively instead of multiplicatively",
  "Stem": "Flash is a diversified manufacturer. Financial analyst Rafael Ortiz informs Flash's board that, at the current consolidated sales level, the degree of operating leverage is 2.5 and the degree of financial leverage is 1.6. He models a downside scenario in which consolidated sales decline by 8%. Under this scenario, the percentage change in operating income and in earnings per share will be closest to:",
  "Choices": {
    "A": "Operating income falls 20%; EPS falls 20%",
    "B": "Operating income falls 16%; EPS falls 16%",
    "C": "Operating income falls 20%; EPS falls 32%",
    "D": "Operating income falls 8%; EPS falls 12.8%"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Operating and financial leverage compound multiplicatively down the income statement. Operating income responds first through the degree of operating leverage: -8% x 2.5 = -20%. Earnings per share then respond through the degree of financial leverage applied to operating income: combined leverage = 2.5 x 1.6 = 4.0, so EPS changes by -8% x 4.0 = -32%. Rafael Ortiz's message to the board is that a modest 8% demand contraction doubles to a 20% profit decline and nearly quadruples to a 32% EPS decline, quantifying downside risk from stacking fixed financing costs on top of a heavy fixed operating base.",
  "ExplanationWrongA": "Option A stops after the operating stage, carrying the -20% operating-income hit straight through to EPS and dropping DFL. Fixed interest still must be paid regardless of demand, so EPS absorbs the second multiplier and falls 32%, not 20%.",
  "ExplanationWrongB": "Option B applies a 2.0 factor as if the two leverage components averaged together (-8% x 2 = -16%). Leverage components do not average; they multiply: 2.5 x 1.6 = 4.0, which doubles the assumed damage to a 32% EPS decline.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D lets the sales decline pass through undamped at the operating line (-8%) and then misapplies a partial factor to EPS (-12.8%). Leverage magnifies rather than filters downside moves, and the propagation order runs DOL first at the operating line, then DFL at the EPS line.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Difficult - multiplicative chaining of DOL and DFL across two income-statement levels under a downside scenario",
    "Independent recompute: dOI = 2.5 x 8% = 20%; DCL = 2.5 x 1.6 = 4.0; dEPS = 4.0 x 8% = 32%",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-196",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.7",
  "Topic": "A.196 off-balance-sheet-guarantee-adjustment",
  "UniqueConceptKey": "A-196-guarantee-debt-equivalence",
  "Authorities": [
    "FASB ASC 460 (Guarantees)"
  ],
  "FormulaReference": "FA-07",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Apply",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CommonTrapReference": "Leaving disclosed guarantees out of adjusted leverage ratios",
  "Stem": "Flash is a diversified manufacturer. Its year-end balance sheet shows total liabilities of $48.0 million and total shareholders' equity of $32.0 million. Flash has also guaranteed an $8.0 million term loan of an unconsolidated joint-venture affiliate; the guarantee is disclosed in the notes but not recorded as a liability. Credit analyst Jordan Blake, preparing Flash's covenant review for lender meetings, adjusts the debt-to-equity ratio to treat the guarantee as debt-equivalent. What adjusted debt-to-equity ratio should Jordan present?",
  "Choices": {
    "A": "1.50",
    "B": "1.75",
    "C": "2.00",
    "D": "1.40"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Analysts treat a disclosed loan guarantee as debt-equivalent because Flash stands ready to absorb the obligation if the affiliate defaults, even though ASC 460 keeps it off the balance sheet until payment becomes probable. Reported debt-to-equity = $48.0M / $32.0M = 1.50. Adjusted = ($48.0M + $8.0M guarantee) / $32.0M = $56.0M / $32.0M = 1.75. For Jordan Blake's lender presentation the quarter-turn increase matters: covenant tests and credit models keyed to reported leverage would otherwise understate Flash's committed risk exposure by ignoring a contingent claim Flash may have to fund.",
  "ExplanationWrongA": "Option A (1.50) reports the unadjusted book ratio and ignores the very guarantee Jordan Blake exists to capture. Disclosed contingent obligations are debt-equivalent for credit work because Flash would fund them upon an affiliate default.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C (2.00) double-counts the exposure by adding the $8.0M twice as if total debt were $64.0M. One guarantee dollar creates one dollar of contingent debt, so the adjusted quotient is $56.0M / $32.0M = 1.75.",
  "ExplanationWrongD": "Option D (1.40) adds the guarantee to both sides ($56.0M / $40.0M). A guarantee creates no equity; padding shareholders' equity with a contingent liability artificially understates leverage relative even to the unadjusted 1.50 basis.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate-Easy - one-step guarantee add-back applied to a familiar leverage ratio",
    "Independent recompute: (48.0+8.0)/32.0 = 56.0/32.0 = 1.75",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-197",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.9",
  "Topic": "A.197 sustainable-growth-dividend-policy",
  "UniqueConceptKey": "A-197-sgr-payout-constraint",
  "Authorities": [
    "Higgins sustainable growth model (corporate finance theory)"
  ],
  "FormulaReference": "FA-21",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Evaluate",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CommonTrapReference": "Confusing dividend yield with payout ratio in the SGR formula",
  "Stem": "Flash is a diversified manufacturer. Flash earns a return on equity of 18% and pays out 40% of earnings as dividends. The board has mandated 14% annual sales growth without issuing new outside equity and without increasing financial leverage beyond current levels. CFO Elena Vasquez must recommend a course of action reconciling the target with the sustainable growth rate framework. Which recommendation is most consistent with that analysis?",
  "Choices": {
    "A": "Hold the 40% payout and cover the growth-funding shortfall with additional borrowing while leaving asset turnover unchanged",
    "B": "Hold the 40% payout, issue no new equity, and accept that actual growth will run near 10.8%",
    "C": "Raise the dividend payout above 40% to signal confidence and thereby accelerate growth toward 14%",
    "D": "Cut the dividend payout to approximately 22% so the retention-driven sustainable growth rate reaches the 14% target with no new equity or added leverage"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The Higgins model states SGR = ROE x retention ratio, assuming constant margins, turnover, and capital structure with no new outside equity. Flash's current SGR = 18% x (1 - 0.40) = 10.8%. To reach 14% internally, required retention = 14% / 18% = 77.8%, implying a maximum payout near 22.2%; verification: 18% x 0.778 = 14.0%. Elena Vasquez's payout cut therefore reconciles the board's target with the model's constraints. Holding 40% caps growth near 10.8%, new borrowing breaks both the constant-leverage assumption and the explicit mandate, and raising the payout arithmetically lowers SGR further below target.",
  "ExplanationWrongA": "Option A plugs the gap with new debt, breaking the SGR model's constant-leverage assumption and Elena Vasquez's own constraint. Added borrowing also raises interest expense, depressing ROE and pulling SGR below the naive arithmetic before the plan is even tested.",
  "ExplanationWrongB": "Option B is arithmetically consistent but concedes the board-mandated objective, settling near 10.8% instead of the required 14%. The exercise demands reconciling the target within the model's constraints, not abandoning the target while calling the residual growth sustainable.",
  "ExplanationWrongC": "Option C inverts the payout logic: SGR = ROE x (1 - payout), so lifting the payout from 40% shrinks retention and drags SGR away from 14% toward roughly 9.9% at a 45% payout, compounding the shortfall it claims to cure.",
  "ExplanationWrongD": "",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Very Difficult - solving for the required payout and defending the choice against three plausible alternatives under binding constraints",
    "Independent recompute: SGR = 18% x 0.60 = 10.8%; required retention = 14/18 = 77.8%; required payout = 22.2%; check 0.18 x 0.778 = 14.0%",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-198",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.5",
  "Topic": "A.198 temporal-method-rate-selection",
  "UniqueConceptKey": "A-198-temporal-nonmonetary-historical-rate",
  "Authorities": [
    "FASB ASC 830 (Foreign Currency Matters) - temporal method"
  ],
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "CalculationItem": false,
  "CognitiveLevel": "Apply",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CommonTrapReference": "Remeasuring nonmonetary assets at the current rate under the temporal method",
  "Stem": "Flash is a diversified manufacturer. Its Monterrey assembly plant keeps its books in Mexican pesos, but the accounting policy team, working with treasurer Marcus Webb, has determined that the peso amounts measured by the plant's assets and liabilities are ultimately settled in U.S. dollars; the U.S. dollar is therefore the functional currency and the temporal (remeasurement) method applies. Controller Alicia Grant asks how the plant's production equipment, acquired several years ago when the exchange rate was 17.2 pesos per dollar, should be remeasured into Flash's reporting currency, given a year-end rate of 18.5 and an average rate for the year of 17.9.",
  "Choices": {
    "A": "At the historical exchange rate in effect when the equipment was acquired, 17.2 pesos per dollar",
    "B": "At the current exchange rate at the balance sheet date, 18.5 pesos per dollar",
    "C": "At the weighted-average exchange rate for the year, 17.9 pesos per dollar",
    "D": "At the forward exchange rate for the period in which disposal is expected"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Under the temporal method of ASC 830, when the U.S. dollar is the functional currency, monetary items are remeasured at the current rate, but nonmonetary assets and their related expense flows are carried at the historical exchange rates in force when they were acquired or incurred. The Monterrey production equipment is nonmonetary, so Alicia Grant remeasures it at the 17.2 acquisition-date rate rather than the 18.5 closing or 17.9 average rate. Remeasurement differences on monetary items run through net income, which is why correct rate selection materially shapes reported results whenever the peso moves against the dollar.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B applies the 18.5 current rate to a nonmonetary asset. Current-rate treatment belongs to the current-rate translation method; under the temporal method dictated by the dollar functional currency, only monetary items take the closing rate.",
  "ExplanationWrongC": "Option C remeasures the equipment at the 17.9 average rate. Average rates serve flow items such as revenue and expense when the temporal method applies; stock items like equipment acquired on a past date retain their acquisition-date rate of 17.2.",
  "ExplanationWrongD": "Option D reaches for a forward rate tied to hypothetical disposal. ASC 830 provides no forward-rate basis for carrying nonmonetary assets; remeasurement uses rates existing at transaction or reporting dates, not anticipated future settlement dates.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate - selecting the governing rate requires applying temporal-method classification rules to each item type",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-199",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.8",
  "Topic": "A.199 comparative-operating-risk-analysis",
  "UniqueConceptKey": "A-199-fixed-cost-wedge-risk-ranking",
  "Authorities": [
    "Managerial accounting leverage theory (cost-structure risk analysis)"
  ],
  "FormulaReference": "FA-19",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Analyze",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CommonTrapReference": "Equating low contribution margin ratio with high operating leverage",
  "Stem": "Flash is a diversified manufacturer. Director of financial planning Nadia Petrov is comparing two same-revenue divisions for COO Diane Foster. Robotics reported sales of $60.0 million, variable costs of $24.0 million, and fixed costs of $27.0 million. Sensors reported sales of $60.0 million, variable costs of $42.0 million, and fixed costs of $12.0 million. If a downturn cuts sales of BOTH divisions by 10%, which conclusion about the profit impact is accurate?",
  "Choices": {
    "A": "Robotics operating income falls about 40% versus about 30% for Sensors; Robotics carries the higher operating risk despite identical revenue",
    "B": "Sensors carries higher operating risk because its contribution margin ratio is lower than Robotics'",
    "C": "Both divisions lose approximately the same dollar amount of operating income, about $3.6 million each",
    "D": "Robotics loses about 30% of operating income and Sensors loses about 40%, reversing the intuitive ranking"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Operating risk tracks the fixed-cost wedge between contribution margin and operating income, not revenue or margin level alone. Robotics: contribution margin $36.0M / operating income $9.0M = DOL 4.0, so a 10% sales decline cuts operating income 40% ($9.0M to $5.4M, a $3.6M hit). Sensors: contribution margin $18.0M / operating income $6.0M = DOL 3.0, so the same decline cuts operating income 30% ($6.0M to $4.2M, a $1.8M hit). Nadia Petrov's takeaway for Diane Foster: Robotics' heavier fixed-cost base ($27.0M versus $12.0M) makes its profit stream more volatile despite equal revenue, so downturn buffers and breakeven planning differ sharply by division.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B equates a thinner contribution margin ratio (30% for Sensors versus 60% for Robotics) with greater risk. Risk follows the fixed-cost block sitting below contribution margin, and Sensors' small $12.0M fixed base produces the lower DOL of 3.0 and milder profit sensitivity.",
  "ExplanationWrongC": "Option C assumes symmetric dollar losses. Robotics sheds $3.6M (40% of $9.0M) while Sensors sheds $1.8M (30% of $6.0M); an equal percentage sales shock does not produce equal dollar profit hits across different cost structures.",
  "ExplanationWrongD": "Option D reverses the multipliers, assigning 30% to Robotics and 40% to Sensors. The arithmetic runs the other way: DOL 4.0 x 10% = 40% for Robotics and DOL 3.0 x 10% = 30% for Sensors, preserving Robotics as the riskier structure.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Difficult - dual-division DOL derivation followed by downside-scenario interpretation across cost structures",
    "Independent recompute: Robotics CM 36.0/OI 9.0 = 4.0 -> 40% decline ($9.0 to $5.4); Sensors CM 18.0/OI 6.0 = 3.0 -> 30% decline ($6.0 to $4.2)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-200",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.5",
  "Topic": "A.200 functional-currency-indicators",
  "UniqueConceptKey": "A-200-functional-currency-autonomy-indicators",
  "Authorities": [
    "FASB ASC 830 (Foreign Currency Matters) - functional currency indicators"
  ],
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "CalculationItem": false,
  "CognitiveLevel": "Apply",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CommonTrapReference": "Defaulting to the parent's currency without testing ASC 830 indicators",
  "Stem": "Flash is a diversified manufacturer. Group controller Wei Zhang must determine the functional currency of Flash's Sao Paulo components subsidiary for ASC 830 purposes. Fieldwork shows the subsidiary sells predominantly inside Brazil with prices set competitively in reais, incurs most materials and labor costs in reais, and retains and reinvests its operating cash flows locally with only modest routine remittances to the parent. Which conclusion should Wei Zhang support?",
  "Choices": {
    "A": "The U.S. dollar is functional because Flash's consolidated reporting currency anchors all subsidiaries by default",
    "B": "The U.S. dollar is functional because the parent's shares trade in a dollar market",
    "C": "The Brazilian real is functional because local pricing, local costs, and locally retained cash flows show the subsidiary's operations are largely autonomous of the parent's currency",
    "D": "The currency with the least historical volatility against the dollar should be adopted as functional to stabilize reported results"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "ASC 830 functional-currency indicators weigh which currency mainly influences sales prices, cost inputs, financing, and the autonomy of cash flows. Local-currency signals include prices set competitively in reais, predominantly local-currency costs, and operating cash flows retained and reinvested locally rather than serving as a conduit to the parent. Wei Zhang should designate the real on these facts. Dollar contracting for major costs, dollar price-setting responsive to exchange rates, or cash flows servicing parent obligations would point instead to the U.S. dollar, and the designation matters because it determines whether Flash translates under the current-rate method or remeasures under the temporal method.",
  "ExplanationWrongA": "Option A defaults to the parent's reporting currency without testing any ASC 830 indicator. Functional currency follows the economics of the subsidiary's operations, and nothing in the fact pattern ties Sao Paulo pricing, costs, or cash flows primarily to the dollar.",
  "ExplanationWrongB": "Option B leans on where the parent's shares trade. The listing venue of Flash's equity has no bearing on which currency drives the subsidiary's prices, costs, and cash flows under the ASC 830 indicator framework Wei Zhang must apply.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D imports a volatility-management criterion foreign to ASC 830. The standard asks which currency economically influences operations and cash flows; smoothing reported results is not a permitted basis and would misstate the subsidiary's underlying exposure profile.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate - applying multiple ASC 830 functional-currency indicators to a coordinated fact pattern",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-201",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.6",
  "Topic": "A.201 inflation-historical-cost-distortion",
  "UniqueConceptKey": "A-201-price-level-denominator-drift",
  "Authorities": [
    "FASB ASC 330 (Inventory) - LIFO historical-cost layering",
    "Price-level analysis theory"
  ],
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "CalculationItem": false,
  "CognitiveLevel": "Understand",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CommonTrapReference": "Assuming percentage ratios self-adjust for price-level changes",
  "Stem": "Flash is a diversified manufacturer. Internal audit lead Sofia Ramirez is reviewing why several of Flash's five-year ratio trends look steadily better even though operational interviews report no genuine efficiency gains during an extended inflationary period. Which statement best explains the distortion inflation introduces into historical-cost ratio trend analysis?",
  "Choices": {
    "A": "Inflation raises nominal sales faster than costs, so profitability ratios become understated relative to real performance",
    "B": "Because long-lived assets and LIFO inventory layers remain at older, lower historical costs while revenues reflect current price levels, return-on-asset and turnover-type ratios drift upward with no real improvement in efficiency",
    "C": "Inflation affects only income-statement captions, leaving every balance-sheet denominator at current economics",
    "D": "Ratios expressed as percentages neutralize inflation automatically because both numerator and denominator adjust to current prices"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Historical-cost measurement leaves long-lived assets and LIFO inventory layers at older, lower-dollar amounts while revenues and current-year costs reflect prevailing price levels. As inflation persists, denominators such as total assets and average inventory sit understated relative to current economics, so return on assets and turnover-style ratios drift upward with no underlying operational improvement, eroding year-over-year comparability. Sofia Ramirez should flag this artifact when certifying trend dashboards: part of the apparent gain is measurement noise, and analysts commonly supplement with replacement-cost or indexed data before crediting management with efficiency improvements.",
  "ExplanationWrongA": "Option A gets the direction wrong: inflation lifts nominal revenues and costs together, and the documented artifact here is understated asset bases inflating returns and turnover, not depressed profitability relative to real performance.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C confines inflation to the income statement. Price-level change also freezes balance-sheet carrying amounts, such as plant and LIFO layers, at dated dollars, which is exactly why ratio denominators drift away from current economics over time.",
  "ExplanationWrongD": "Option D claims percentage-form ratios self-neutralize. A ratio mixes a current-priced numerator with a historical-cost denominator, so the percentage itself inherits the mismatch rather than canceling it, which is what Sofia Ramirez observes in the trends.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate-Easy - explaining a known measurement artifact at concept level with direction-of-effect reasoning",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-202",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.7",
  "Topic": "A.202 off-balance-sheet-financing-choice",
  "UniqueConceptKey": "A-202-constrained-obbs-structuring",
  "Authorities": [
    "FASB ASC 842 (Leases)",
    "FASB ASC 460 (Guarantees)",
    "Legacy pre-ASC 842 operating-lease structuring practice"
  ],
  "FormulaReference": "FA-07",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Evaluate",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CommonTrapReference": "Treating recourse factoring as true off-balance-sheet financing",
  "Stem": "Flash is a diversified manufacturer. Flash's balance sheet carries total liabilities of $120.0 million against shareholders' equity of $80.0 million, and its credit agreement caps debt-to-equity at 1.60. CFO Elena Vasquez must fund a $45.0 million distribution-center expansion without issuing new equity and without breaching the covenant; Flash's trade receivables pool totals $30.0 million. Structuring precedent at Flash permits legacy pre-ASC 842 style operating-lease arrangements with footnote disclosure. Which recommendation best satisfies the funding need and both constraints simultaneously?",
  "Choices": {
    "A": "Structure the expansion through a sale-leaseback accounted for as an operating lease with a third-party lessor, keeping the obligation off the balance sheet with footnote disclosure and preserving covenant headroom",
    "B": "Borrow the full $45.0 million under a term loan and rely on future earnings growth to restore headroom",
    "C": "Factor the entire receivables pool with recourse and apply the proceeds to the expansion",
    "D": "Issue $45.0 million of new common equity to fund the project outright"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Reported leverage stands at $120.0M / $80.0M = 1.50 against a 1.60 ceiling, so headroom is thin. Straight borrowing of $45.0M pushes debt-to-equity to $165.0M / $80.0M = 2.06, an immediate breach; even a $20.0M draw breaches at 1.75. A sale-leaseback structured as a legacy-style operating lease funds the facility while the obligation remains off balance sheet with footnote disclosure, preserving headroom under both constraints. Recourse factoring tops out near the $30.0M receivables pool, well short of the $45.0M requirement, and invites secured-borrowing characterization; a $45.0M equity issuance restores ratios comfortably but directly violates Elena Vasquez's stated no-new-equity constraint.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B books the full $45.0M loan, driving leverage to $165.0M / $80.0M = 2.06 against the 1.60 ceiling, an immediate covenant breach inviting repricing or acceleration, so hoped-for earnings growth never gets the chance to matter.",
  "ExplanationWrongC": "Option C relies on recourse factoring capped by the ~$30.0M receivables pool, far short of the $45.0M need, and recourse terms invite secured-borrowing characterization that could push the arrangement back onto the balance sheet anyway.",
  "ExplanationWrongD": "Option D issues $45.0M of equity, which would repair the ratio but expressly violates Elena Vasquez's no-new-equity directive and dilutes existing holders; a constraint-satisfying answer cannot simply discard one of the constraints.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Very Difficult - constrained recommendation weighing covenant arithmetic, funding capacity, treatment risk, and a binding prohibition",
    "Independent recompute: 120/80 = 1.50 baseline; 165/80 = 2.06 > 1.60 breach; 140/80 = 1.75 > 1.60 breach; factor capacity 30.0 < 45.0 needed",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-203",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.6",
  "Topic": "A.203 lifo-fifo-turnover-comparability",
  "UniqueConceptKey": "A-203-lifo-fifo-turnover-bias",
  "Authorities": [
    "FASB ASC 330 (Inventory) - LIFO/FIFO cost-flow assumptions"
  ],
  "FormulaReference": "FA-04",
  "ItemStyle": "single-select",
  "CalculationItem": false,
  "CognitiveLevel": "Analyze",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CommonTrapReference": "Comparing LIFO and FIFO reporters' turnovers without valuation adjustment",
  "Stem": "Flash is a diversified manufacturer that accounts for resin inventory on a FIFO basis. Supply-chain analyst Marco Bellini is benchmarking Flash's inventory turnover against its closest competitor, an otherwise similar maker that uses LIFO, during a period of steadily rising resin prices. Marco wants to know how the accounting-method difference bears on the comparison. Which conclusion is analytically sound?",
  "Choices": {
    "A": "The LIFO reporter's turnover appears lower because LIFO reports smaller cost of goods sold during inflation",
    "B": "The two turnovers compare cleanly as published because both formulas divide COGS by inventory",
    "C": "The FIFO reporter's cost of goods sold is higher because FIFO charges the newest costs to expense",
    "D": "The LIFO reporter's turnover is overstated relative to the FIFO reporter's because LIFO pairs current, higher replacement costs in the numerator with older, cheaper layers in the denominator"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Under ASC 330 cost-flow assumptions, LIFO charges cost of goods sold at current, higher replacement costs while leaving ending inventory at older, cheaper layers; FIFO does the reverse. Inventory turnover equals COGS divided by average inventory, so the LIFO reporter's numerator is inflated and its denominator deflated relative to the FIFO reporter's, overstating apparent velocity during rising prices. Marco Bellini's sound conclusion is that the published turnovers cannot be compared without restatement, adjusting either company's inventory to a current-cost or common basis, because the divergence reflects accounting-method artifacts rather than genuine supply-chain speed differences between the two manufacturers.",
  "ExplanationWrongA": "Option A reverses the mechanics: LIFO raises COGS by charging current costs and shrinks reported inventory values, pushing the published turnover higher than FIFO during inflation, not lower as the option asserts.",
  "ExplanationWrongB": "Option B accepts face-value comparability. Identical formulas do not yield comparable outputs when the numerator and denominator embed different vintages of input prices under LIFO versus FIFO, so the raw quotients embed opposite biases.",
  "ExplanationWrongC": "Option C claims FIFO produces the higher COGS. FIFO releases the oldest, cheapest layers to cost of goods sold while LIFO releases the newest replacement-cost layers, so during inflation FIFO's COGS is lower, not higher.",
  "ExplanationWrongD": "",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Moderate - tracing a cost-flow assumption through both the numerator and the denominator of a benchmarking ratio",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-204",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.2",
  "Topic": "A.204 window-dressing-current-ratio",
  "UniqueConceptKey": "A-204-proportional-payment-ratio-mechanic",
  "Authorities": [
    "FASB ASC 205-10 (Presentation of Financial Statements)",
    "Ratio-analysis limitation theory (window dressing)"
  ],
  "FormulaReference": "FA-01",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Apply",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CommonTrapReference": "Missing that paying current liabilities raises the current ratio when above 1.0",
  "Stem": "Just before year-end, staff accountant Lucia Fernandez learns that Flash, a diversified manufacturer, paid $2.0 million of accounts payable out of cash on December 29. Prepayment figures showed current assets of $12.0 million and current liabilities of $8.0 million. What happened to Flash's current ratio as a result of the payment?",
  "Choices": {
    "A": "It fell from 1.50 to about 1.25",
    "B": "It rose from 1.50 to about 1.67",
    "C": "It remained unchanged at 1.50",
    "D": "It rose from 1.50 to about 1.43"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Paying $2.0M of accounts payable with cash reduces current assets and current liabilities by equal dollar amounts. Before: $12.0M / $8.0M = 1.50. After: ($12.0M - $2.0M) / ($8.0M - $2.0M) = $10.0M / $6.0M = 1.67. Whenever the current ratio exceeds 1.0, equal reductions on both sides raise the ratio, a classic window-dressing mechanic Lucia Fernandez surfaces as a limitation of point-in-time ratio analysis: underlying liquidity is unchanged and only the snapshot improves, which is why lenders routinely request pre-year-end transaction detail before relying on reported ratios.",
  "ExplanationWrongA": "Option A (1.25) cuts cash to $10.0M but forgets the matching $2.0M drop in current liabilities to $6.0M. Equal-sided payments raise the ratio whenever it starts above 1.0, so treating the payment as a pure asset reduction misreads the mechanics.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Option C holds the ratio at 1.50 as if equal dollar payments were proportionally neutral. Proportions shift: $10.0M / $6.0M = 1.67, because the liability base shrinks faster in percentage terms than the asset base does.",
  "ExplanationWrongD": "Option D's 1.43 applies only half the payoff (as in $10.0M / $7.0M). Both accounts move by the full $2.0M, so stopping halfway misstates the post-payment snapshot Lucia Fernandez must explain to the year-end review team.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Easy - single-step ratio update with one counterintuitive directional insight",
    "Independent recompute: (12.0-2.0)/(8.0-2.0) = 10.0/6.0 = 1.6667 ~ 1.67",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "QuestionID": "P2-A-205",
  "Part": 2,
  "Part2OnlyFlag": true,
  "Section": "A",
  "BlueprintDomain": "Financial Statement Analysis",
  "LOSTag": "A.8",
  "Topic": "A.205 dfl-preferred-dividend-grossup",
  "UniqueConceptKey": "A-205-preferred-dividend-tax-grossup",
  "Authorities": [
    "Corporate finance theory (DFL with preferred dividend tax gross-up)"
  ],
  "FormulaReference": "FA-20",
  "ItemStyle": "single-select",
  "CalculationItem": true,
  "CognitiveLevel": "Analyze",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CommonTrapReference": "Omitting the preferred-dividend tax gross-up in the DFL denominator",
  "Stem": "Flash is a diversified manufacturer. Consolidated operating income is $20.0 million, interest expense is $8.0 million, the marginal tax rate is 25%, and Flash pays $3.0 million of preferred dividends. Capital reporting manager Grace Lin is computing the degree of financial leverage for the board's risk dashboard, correctly adjusting for the after-tax nature of preferred dividends. What degree of financial leverage should Grace report?",
  "Choices": {
    "A": "1.67",
    "B": "2.22",
    "C": "2.50",
    "D": "3.75"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The degree of financial leverage equals EBIT divided by (EBIT - interest - preferred dividends grossed up for taxes), because preferred dividends are paid from after-tax dollars while EBIT is a pre-tax measure. Preferred burden = $3.0M / (1 - 0.25) = $4.0M. Denominator = $20.0M - $8.0M - $4.0M = $8.0M. DFL = $20.0M / $8.0M = 2.50. Grace Lin's figure tells the board that a 1% change in operating income moves earnings available to common shareholders by about 2.5%; ignoring the gross-up would understate leverage at 2.22, and dropping preferred dividends entirely would mask the senior claim at a misleading 1.67.",
  "ExplanationWrongA": "Option A (1.67) omits preferred dividends altogether, dividing $20.0M by $12.0M. Preferred claims rank ahead of common earnings, so skipping them understates the squeeze common holders experience and flatters the risk dashboard.",
  "ExplanationWrongB": "Option B (2.22) subtracts the $3.0M preferred dividend without the tax gross-up. Preferred dividends come from after-tax dollars while EBIT is pre-tax, so the divisor must charge $3.0M / 0.75 = $4.0M, which yields 2.50 rather than 2.22.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D (3.75) grosses up interest as well ($8.0M / 0.75 = $10.67M). Interest is already a pre-tax deduction; only the preferred dividend requires the (1 - t) conversion, so double-adjusting shrinks the denominator improperly and inflates DFL.",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Difficult - DFL computation requiring the preferred-dividend tax gross-up among four precise computational paths",
    "Independent recompute: PD/(1-t) = 3.0/0.75 = 4.0; DFL = 20.0/(20.0-8.0-4.0) = 20.0/8.0 = 2.50",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
}
];
