var pack_p2_a_part28 = [
{
  "Authorities": [
    "IMA CMA Part 2 Content Specification Outline, Section A (ratio terminology)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Quick ratio",
    "B": "Cash ratio",
    "C": "Current ratio",
    "D": "Debt-to-assets ratio"
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Attributing the legacy 'working capital ratio' label to the quick or cash ratio",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The working capital ratio is the traditional name for the current ratio — current assets divided by current liabilities — because it compares the resources constituting working capital against claims due within one year. Bank credit agreements drafted decades ago commonly use this legacy label. The quick ratio strips out inventory, the cash ratio keeps only cash and marketable securities, and debt-to-assets is a leverage measure, so none matches the traditional term. Business interpretation: finance director Renata Kovacs can map Flash's legacy covenant language directly onto the statements, because the 'working capital ratio' covenant line tests the same aggregate liquidity cushion modern analysts call the current ratio.",
  "ExplanationWrongA": "Choice A picks the quick ratio, which excludes inventory from the numerator; the misconception is associating the more conservative test with the older umbrella term. The working capital ratio traditionally spans the complete set of current assets, which describes the current ratio rather than its acid-test refinement.",
  "ExplanationWrongB": "Choice B picks the cash ratio, the narrowest liquidity measure counting only cash and marketable securities; the misconception is assuming the most stringent ratio carries the generic historical label. The traditional working capital ratio is the broadest liquidity comparison — total current assets against current liabilities.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D picks the debt-to-assets ratio, a solvency measure with no working capital linkage; the misconception is grabbing another familiar balance-sheet ratio without noting that working capital is by definition current assets minus current liabilities, a concept pointing squarely to the current ratio.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-246",
  "Section": "A",
  "Stem": "While onboarding a new financial analyst, Flash finance director Renata Kovacs runs a terminology check: several of Flash's legacy banking documents refer to the 'working capital ratio,' and she wants the analyst connecting that lender language to modern reporting terms. Which ratio is traditionally known as the working capital ratio?",
  "Topic": "A.246 workingcapital-ratio-name",
  "UniqueConceptKey": "A-246-working-capital-synonym",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Remember/Easy — single-fact nomenclature recall capped at score 1 per Rule 11",
    "Verification: conceptual item — no computation required",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Higgins (1977) sustainable growth framework",
    "Corporate dividend policy theory"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Hold the dividend at $3.60 per share: at projected EPS of $6.30 the payout falls to about 57.1%, and retention supports a sustainable growth rate of roughly 6.43% (15.0% x 0.429), exceeding the 6.0% target without approaching the 1.75 leverage cap",
    "B": "Raise the dividend to $4.20 per share to reward shareholders: the payout climbs to about 66.7%, retention drops to one-third, and the sustainable growth rate falls to roughly 5.0% (15.0% x 0.333), making growth beyond that point dependent on added debt",
    "C": "Suspend the dividend entirely to fund the expansion from 100% retention, maximizing the sustainable growth rate at 15.0% and eliminating covenant pressure",
    "D": "Raise the dividend to $4.20 and cover the expansion gap with a short-term borrowing facility structured to sit outside the debt-to-equity covenant calculation"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Judging dividend affordability apart from retention-driven sustainable growth",
  "CorrectChoice": "A",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "The Higgins sustainable growth lens ties dividend policy to achievable growth: SGR = ROE x retention. Holding $3.60 gives a payout of $3.60 / $6.30 = 57.14% and retention of 42.86%, so SGR = 15.0% x 0.4286 = 6.43% — above the 6.0% target with no incremental leverage. The activist proposal cuts retention to 33.3% (SGR of 5.0%), forcing expansion spending above 5.0% growth to be debt-financed against thin covenant room; full suspension over-retains, sacrificing shareholder returns for capacity the plan does not require. Vasquez should therefore hold the payout and commit to resuming distribution growth as expansion cash flows arrive. Business interpretation: the dividend is affordable only to the extent residual retention still finances strategy — here it does, but only at the current rate, which is the defensible balance between activist pressure and covenant discipline.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B is arithmetically coherent — a sustainable growth rate near 5.0% — but it inverts the priority: the misconception is that signaling generosity today is costless, when dropping below the 6.0% growth target shifts expansion funding into debt precisely when covenant headroom is limited. It remains a defensible shareholder-first stance, yet it fails the balanced-objective test Vasquez was asked to apply.",
  "ExplanationWrongC": "Choice C maximizes retention but overshoots the requirement; the misconception is treating maximum growth as an end in itself. With the 6.0% target met at roughly 43% retention, retaining 100% confiscates cash from shareholders without a disclosed use, inviting the very activist pressure the committee is managing and signaling weak reinvestment discipline.",
  "ExplanationWrongD": "Choice D engineers around the covenant rather than within it; the misconception is that form-over-substance structuring of a borrowing facility neutralizes leverage risk. Lenders and rating agencies look through such arrangements, and the governance exposure of appearing to evade the credit agreement compounds the financial risk created by the higher payout.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-247",
  "Section": "A",
  "Stem": "Flash's board dividend committee, chaired by CFO Elena Vasquez, confronts competing pressures: activist shareholders want the dividend raised from $3.60 to $4.20 per share, while management plans a plant expansion requiring maximum internal funding. Flash earned $6.00 per share in FY2026 with return on equity of 15.0%; FY2027 EPS is projected at $6.30, and management targets at least 6.0% annual growth. The credit agreement caps debt-to-equity at 1.75, leaving limited room for debt-funded payouts. Vasquez must recommend a dividend course to the committee. Which recommendation best balances the competing objectives?",
  "Topic": "A.247 dividend-policy-committee",
  "UniqueConceptKey": "A-247-payout-sustainability-decision",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Evaluate at VD — named chair weighs competing defensible alternatives with SGR recomputation per proposal",
    "Independent recomputation: 3.60/6.30 = 57.14% payout; SGR = 15.0%x0.4286 = 6.43% vs 6.0% target; $4.20 route: 4.20/6.30 = 66.67% payout, SGR = 15.0%x0.3333 = 5.0%",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Financial statement analysis theory (earnings-quality red flags)",
    "FASB ASC 606 (Revenue from Contracts with Customers)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The pattern is benign because receivables naturally track sales growth, and the DSO lengthening merely reflects normal seasonality",
    "B": "The divergence proves fraudulent revenue recognition has occurred and warrants immediate restatement of FY2026 results",
    "C": "The data indicate customers are paying earlier than in prior years, improving Flash's cash conversion",
    "D": "Receivables growing 2.25 times as fast as revenue, with DSO lengthening about 6.5 days, is a classic channel-stuffing indicator suggesting possible premature or accelerated revenue recognition that warrants cutoff testing and credit-file review"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Treating AR-outpacing-sales divergence as benign or as conclusive proof",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Earnings-quality analysis screens for divergence between revenue growth and its cash conversion. Receivables grew 27.0% against sales growth of 12.0% — a factor of 27.0/12.0 = 2.25 — stretching days sales outstanding from 48.7 to 55.2 days (+6.5 days) precisely when quota pressure was intense. That combination matches the documented signature of potential channel stuffing or aggressive credit extension under ASC 606 (revenue recognized before control transfers). The pattern is an investigative trigger, not proof: Grace Whitfield should commission quarter-end cutoff testing and review credit approvals. Business interpretation: until cleared, the quality of Flash's incremental 12.0% revenue growth should be discounted, because earnings backed by receivables rather than cash are lower-quality earnings.",
  "ExplanationWrongA": "Choice A waves off the divergence as natural tracking; the misconception is ignoring proportionality — receivables rose 27.0% against sales growth of 12.0%, and DSO does not lengthen 6.5 days through seasonality alone absent a shift in billing or collection terms. Benign patterns keep DSO roughly stable when customer mix is unchanged.",
  "ExplanationWrongB": "Choice B converts an indicator into a verdict; the misconception is jumping from statistical anomaly to proven fraud and restatement. Red-flag analytics establish suspicion sufficient to justify procedures such as quarter-end cutoff testing and receivable confirmations, but concluding fraud requires documented evidence the screen cannot supply.",
  "ExplanationWrongC": "Choice C reverses the direction of the deterioration; the misconception is misreading a lengthening DSO as faster collection. Faster-paying customers shrink receivables relative to sales, whereas Flash's receivables ballooned relative to sales — cash arrived more slowly, degrading rather than improving conversion quality.",
  "ExplanationWrongD": "",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-248",
  "Section": "A",
  "Stem": "Internal audit lead Grace Whitfield is reviewing Flash's FY2026 revenue cycle for the audit committee. Net sales grew 12.0%, from $300.00 million to $336.00 million, while trade receivables grew 27.0%, from $40.00 million to $50.80 million; days sales outstanding lengthened from 48.7 to 55.2 days. Regional managers exceeded stretch sales quotas two quarters running. Whitfield must characterize the earnings-quality implication for the committee. Which inference is best supported?",
  "Topic": "A.248 receivables-revenue-divergence",
  "UniqueConceptKey": "A-248-ar-sales-redflag",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Apply/Moderate — quantitative divergence interpretation with benign, overclaim, and inversion traps",
    "Verification: 27.0/12.0 = 2.25x divergence; DSO 55.2 - 48.7 = +6.5 days",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (operating and financial leverage interaction)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Ashford is riskier because its $36.00 million contribution margin is larger, so sales fluctuations move more dollars of profit",
    "B": "Brookfield is riskier because identical operating leverage (DOL 3.00) multiplies through a higher financial leverage factor (DFL 2.50 versus 1.50), producing combined leverage of 7.50 versus 4.50 — a 1% sales decline cuts Brookfield's earnings about 7.5% versus about 4.5% at Ashford",
    "C": "Risk is equal because both plants operate at DOL 3.00, and financing structure has no bearing on earnings sensitivity to sales",
    "D": "Plant-level risk cannot be compared because diversification across the two plants eliminates earnings sensitivity attributable to leverage"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Stopping at DOL and ignoring the DFL multiplier when ranking total risk",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Total earnings sensitivity combines the operating and financing layers: combined leverage = DOL x DFL, where DFL = operating income / (operating income - interest). Ashford: DFL = $12.00M / $8.00M = 1.50, so combined leverage = 3.00 x 1.50 = 4.50. Brookfield: DFL = $10.00M / $4.00M = 2.50, so combined leverage = 3.00 x 2.50 = 7.50. Identical operating structures therefore translate a given sales shock about 1.67 times more violently at Brookfield. Business interpretation: Omar Haddad's message to the CFO is that Brookfield's heavier debt load — not its operations — is the risk differentiator; deleveraging Brookfield would narrow EPS swings more than any operational change of comparable cost.",
  "ExplanationWrongA": "Choice A mistakes dollar magnitude for sensitivity; the misconception is equating a bigger contribution margin pool with greater proportional risk. Leverage measures percentage response to a percentage sales change — Ashford's larger dollar base dilutes its elasticity, and its lighter debt load holds combined leverage at 4.50 versus Brookfield's 7.50.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C stops the analysis at the operating layer; the misconception is that matching DOL of 3.00 equalizes risk. Financing is a second multiplier: Brookfield's DFL of 2.50 stacks onto the same 3.00 to compound swings that Ashford's DFL of 1.50 amplifies far less, so total risk diverges sharply despite identical operations.",
  "ExplanationWrongD": "Choice D invokes diversification to avoid the comparison; the misconception is conflating portfolio-level variance reduction with the mechanical leverage arithmetic inside each plant. For a given plant's sales change, the DOL x DFL chain applies deterministically — diversification may smooth consolidated results but does not erase Brookfield's higher per-unit sensitivity.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-249",
  "Section": "A",
  "Stem": "FP&A director Omar Haddad is briefing Flash's CFO on relative risk across the company's two stamping plants. Plant Ashford produces contribution margin of $36.00 million on operating income of $12.00 million, with allocated interest expense of $4.00 million; Plant Brookfield produces contribution margin of $30.00 million on operating income of $10.00 million, with allocated interest expense of $6.00 million. Both plants carry identical operating leverage (DOL 3.00), but their financing differs. Haddad must explain which plant subjects Flash's earnings to greater percentage swings from a given change in plant sales, and why. Which assessment is correct?",
  "Topic": "A.249 leverage-interaction-risk",
  "UniqueConceptKey": "A-249-dol-dfl-composition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Analyze/Difficult — two-stage leverage decomposition and cross-plant comparison",
    "Independent recomputation: DFL_A = 12/(12-4) = 1.50; DFL_B = 10/(10-6) = 2.50; combined leverage = 3.00x1.50 = 4.50 vs 3.00x2.50 = 7.50",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (dividend payout and retention; Higgins sustainable growth)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Rising dividends alongside flat EPS demonstrate that Flash's underlying earnings power has been strengthening each year",
    "B": "The payout ratio measures the dividend return on Flash's market price, so the climb signals a richer yield for income investors",
    "C": "Flash is distributing a growing share of flat earnings, so the retention ratio has fallen from 75.0% to 35.0%, narrowing the internally generated funding available for sustainable growth unless return on equity improves",
    "D": "A payout above 50% triggers mandatory dividend suspension under standard credit agreements, so Flash's policy is unsustainable by construction"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Confusing payout ratio with dividend yield or earnings growth",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "The payout ratio — dividends per share divided by earnings per share — determines retention, the engine of the sustainable growth rate (SGR = ROE x retention). Here $1.00 / $4.00 = 25.0% rose to $2.60 / $4.00 = 65.0%. Flat EPS means the dividend climb came entirely from redistribution: retention shrank from 75.0% to 35.0%, so for any given ROE, Flash's self-funded growth ceiling fell by more than half. Business interpretation: treasury analyst Lena Fischer should tell the finance committee that the policy remains affordable only while ROE holds or improves; otherwise the shrinking retained-earnings stream will force slower growth, additional borrowing, or an eventual dividend reset.",
  "ExplanationWrongA": "Choice A reads distribution growth as earnings growth; the misconception is confusing the payout share with earnings power. EPS stayed near $4.00 throughout — the dividend increase came from paying out a larger slice of unchanged earnings, not from any strengthening of profitability.",
  "ExplanationWrongB": "Choice B swaps in the dividend yield definition; the misconception is mixing market-relative income measures (dividends divided by price) with the earnings-relative payout ratio (dividends divided by EPS). The trend says nothing about price or yield — it measures how much of each earned dollar Flash returns versus retains.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D invents an automatic suspension rule at the 50% threshold; the misconception is treating a rule of thumb as a binding covenant. Credit agreements set negotiated thresholds specific to each borrower, and many mature firms sustain payouts above 50% — the genuine concern in Flash's trend is the shrinking retention ratio, not a universal trigger point.",
  "FormulaReference": "FA-22",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-250",
  "Section": "A",
  "Stem": "Treasury analyst Lena Fischer is preparing Flash's five-year dividend retrospective for the finance committee. Over FY2022 through FY2026, EPS held essentially flat near $4.00 while dividends per share climbed steadily from $1.00 to $2.60, lifting the payout ratio from 25.0% to 65.0%. A committee member asks what the trend implies for Flash's future self-funded growth. Which interpretation is correct?",
  "Topic": "A.250 payout-trend-interpretation",
  "UniqueConceptKey": "A-250-payout-ratio-trend",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Difficulty justified: Understand/ME — single-trend interpretation capped at score 2 per Rule 11",
    "Verification: 1.00/4.00 = 25.0% rising to 2.60/4.00 = 65.0%; retention 75.0% falling to 35.0%",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-065",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "ASC 830 Foreign Currency Matters"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Transaction exposure is the cash-effecting gain or loss on specific foreign-currency-denominated items such as receivables, payables, and loans already recorded on the books, while translation exposure is the consolidated reporting effect of restating the subsidiary's financial statements into U.S. dollars, producing no necessary cash flow",
    "B": "Both exposures produce realized cash gains or losses that must be recognized in Flash's operating income in the period the exchange rate moves",
    "C": "Translation exposure applies only to monetary accounts such as cash and payables, while transaction exposure covers the entire balance sheet of the German subsidiary",
    "D": "Transaction exposure is measured only when each invoice settles in cash, while translation exposure represents the cash gain or loss on individual customer invoices denominated in euros"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Reversing the definitions of transaction and translation exposure",
  "CorrectChoice": "A",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Under ASC 830 Foreign Currency Matters, transaction exposure arises from foreign-currency-denominated assets and liabilities already on the books - each euro receivable or payable Flash holds will settle in cash, so rate movements create measurable gains or losses recognized in income. Translation exposure, by contrast, is purely an accounting consequence: consolidating the German subsidiary requires converting its statements from euros into U.S. dollars at current rates for equity and mixed rates elsewhere, producing a translation adjustment that bypasses income entirely. Business interpretation: controller Marcus Webb can explain to the new hire that hedging priorities differ because transaction exposure affects cash and earnings directly while translation exposure affects reported equity until disposal. The common trap is treating the consolidated translation adjustment as a cash-flow risk equivalent to open monetary payables.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B asserts both exposures are realized cash events; the misconception ignores that translation exposure under ASC 830 is a restatement artifact flowing through other comprehensive income. Only transaction exposure - settled receivables, payables, and debt - produces cash gains or losses recognized in income.",
  "ExplanationWrongC": "Choice C reverses the scope of the two concepts; restricting translation to monetary accounts describes remeasurement under the temporal method for a USD functional currency. Translation converts the entire set of financial statements, including nonmonetary assets carried at historical exchange rates.",
  "ExplanationWrongD": "Choice D swaps the definitions outright; the misconception maps invoice-level cash effects onto translation and consolidated reporting onto transactions. ASC 830 assigns them the opposite way, which is why hedging programs target open monetary items rather than the consolidation entry.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-251",
  "Section": "A",
  "Stem": "Controller Marcus Webb is orienting a new hire on Flash's euro-denominated German subsidiary ahead of the quarterly close. He explains that Flash faces two distinct currency exposures tied to the subsidiary's operations and financing. The hire asks how translation exposure differs from transaction exposure under ASC 830. Which response is accurate?",
  "Topic": "A.251 translation-vs-transaction-exposure",
  "UniqueConceptKey": "A-251-asc830-exposure-distinction",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Easy/Understand recall of ASC 830 exposure taxonomy"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "ASC 830 Foreign Currency Matters (temporal method remeasurement)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$10,000 gain",
    "B": "$12,500 gain",
    "C": "$12,500 loss",
    "D": "$25,000 gain"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Remeasuring only cash or flipping the gain/loss sign on net monetary position",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Under the temporal method of ASC 830, monetary assets and liabilities are remeasured at the current exchange rate, so the rate movement on the net monetary position drives the remeasurement result through income. Net monetary assets = 200,000 + 300,000 - 250,000 = 250,000 euros. The euro strengthened from $1.15 to $1.20, so the gain = 250,000 x ($1.20 - $1.15) = $12,500. Business interpretation: treasury analyst Dana Okafor records a $12,500 remeasurement gain in second-quarter income because Flash's net euro claims purchase more dollars at quarter end than at quarter start. The classic traps are remeasuring nonmonetary items at the current rate, dropping the payables offset from the exposed base, or flipping the direction of the gain.",
  "ExplanationWrongA": "Choice A remeasures only the cash balance (200,000 x $0.05 = $10,000); the misconception forgets that receivables and payables are equally exposed monetary items. The temporal method captures the whole net monetary position, not cash alone.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C flips the sign; the misconception treats a strengthening euro as harmful to a net monetary asset position. Holding net euro claims when the euro appreciates produces a remeasurement gain, not a loss - the loss case belongs to a net monetary liability position.",
  "ExplanationWrongD": "Choice D remeasures gross monetary assets before netting payables (500,000 x $0.05 = $25,000); the misconception ignores that the 250,000-euro payable offsets exposure dollar for dollar. Only the net 250,000-euro position carries exchange risk.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-252",
  "Section": "A",
  "Stem": "Treasury analyst Dana Okafor is closing Flash's second quarter. Flash's German subsidiary keeps its books in euros, but ASC 830 classifies the U.S. dollar as the functional currency, so the euro-denominated accounts must be remeasured under the temporal method. At quarter start the spot rate was $1.15 per euro and at quarter end it was $1.20 per euro. Throughout the quarter the subsidiary held cash of 200,000 euros, receivables of 300,000 euros, and payables of 250,000 euros; nonmonetary items remained at historical rates that did not move. What remeasurement result should Dana record?",
  "Topic": "A.252 temporal-remeasurement-gain",
  "UniqueConceptKey": "A-252-temporal-method-monetary-net",
  "VerifiedChecks": [
    "Verification: net monetary assets 200,000 + 300,000 - 250,000 = 250,000 EUR; 250,000 x (1.20 - 1.15) = 12,500 USD gain",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: ME/Apply single-formula remeasurement with distractor errors"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Constant-dollar measurement convention (nominal-to-real deflation)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "9.00%",
    "B": "3.00%",
    "C": "2.83%",
    "D": "15.54%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Subtracting inflation from nominal growth instead of deflating the growth factor",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Converting nominal growth to real terms divides the growth factor by the inflation factor, consistent with constant-dollar measurement when prices change. Nominal growth = 2,180,000 / 2,000,000 - 1 = 9.00%. Real growth = (1 + 0.09) / (1 + 0.06) - 1 = 1.09 / 1.06 - 1 = 2.83%. Business interpretation: of the 9.00% headline increase, roughly two-thirds reflects price-level drift, leaving only 2.83% genuine volume-and-mix expansion - a materially weaker demand signal for Tomas Rivera's capacity planning and inventory commitments. The common trap is the subtraction shortcut (9.00% - 6.00% = 3.00%), which overstates real growth whenever inflation is meaningful; exact deflation compounds the factors.",
  "ExplanationWrongA": "Choice A quotes the nominal rate as though it were real; the misconception skips the deflation step entirely. Dividing the 1.09 growth factor by the 1.06 price factor is what strips purchasing-power drift from the headline figure.",
  "ExplanationWrongB": "Choice B applies the subtraction shortcut (9.00% minus 6.00% = 3.00%); this approximation error grows as inflation rises. Proper deflation compounds the factors: 1.09 / 1.06 yields 2.83%, seventeen basis points below the shortcut.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D multiplies the factors (1.09 x 1.06 - 1 = 15.54%), compounding nominal growth with inflation in the wrong direction. Inflation adjustment divides by the price factor to remove it; the arithmetic never adds inflation on top of nominal growth.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-253",
  "Section": "A",
  "Stem": "FP&A director Tomas Rivera is briefing Flash's executive team on last year's top-line performance. Flash reported net sales of $2,000,000 in the prior year and $2,180,000 this year. Over the same span, the regional price index most relevant to Flash's selling prices rose 6.0%. Tomas wants the team to quote growth in constant-dollar terms so the board does not mistake price drift for demand. What real growth rate should he present?",
  "Topic": "A.253 real-vs-nominal-growth",
  "UniqueConceptKey": "A-253-deflator-growth-adjustment",
  "VerifiedChecks": [
    "Verification: nominal 2,180,000/2,000,000 - 1 = 9.00%; real 1.09/1.06 - 1 = 0.0283 = 2.83%; cross-check 1.09 x 1.06 - 1 = 15.54% (distractor D reproduced)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Moderate/Apply two-step deflation"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Constant-dollar segment analysis (price-level adjusted comparison)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Deflating FY2026 to constant dollars shows real sales growth of 9.52% rather than the 15.00% headline, and the 0.50-point margin gain reflects a modest genuine efficiency improvement layered on top of price-level drift",
    "B": "Restating FY2026 operating income at $372,381 places it below FY2025 operating income, so the segment's real profitability actually declined during the year",
    "C": "Because each year's margin is computed from same-period prices, inflation has no bearing on the comparison and the 8.50% margin is fully comparable to 8.00% without adjustment",
    "D": "The data reveal that physical unit volume fell in FY2026, which explains why margin expansion lagged the sales growth rate"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Misreading deflated figures as declines or ignoring price-level drift",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Constant-dollar analysis deflates nominal amounts by the price index before comparing periods. Real FY2026 sales = 4,600,000 / 1.05 = $4,380,952, so real sales growth = 4,380,952 / 4,000,000 - 1 = 9.52%, far below the 15.00% nominal print. Deflated operating income = 391,000 / 1.05 = $372,381, up 16.37% versus $320,000 in real terms, and within-year margins (8.00% to 8.50%) remain legitimate same-price efficiency signals. Business interpretation: equity analyst Priya Raman can tell readers the Industrial Products segment genuinely improved, but nearly one-third of the headline growth is price rather than volume, tempering the momentum narrative. The trap is either dismissing nominal margins altogether or misreading the deflated comparison as deterioration.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B stops halfway through the deflation logic372,381 exceeds the $320,000 base, so real operating income rose 16.37%, not fell. The misconception compares a deflated current year against an unadjusted prior year and mislabels the direction.",
  "ExplanationWrongC": "Choice C dismisses cross-period comparability concerns wholesale; while each year's margin ratio is internally consistent, the 15.00% sales growth framing the story is inflated by 5.0% of price drift unless deflated to the true 9.52%. The misconception conflates ratio validity with trend validity.",
  "ExplanationWrongD": "Choice D invents a volume decline the data cannot support; deflated sales grew 9.52% in real terms, indicating positive unit-volume contribution. The misconception substitutes narrative for computation where the index math points the other way.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-254",
  "Section": "A",
  "Stem": "Equity analyst Priya Raman covers Flash and is decomposing segment profitability across two years for her initiation note. Flash's Industrial Products segment reported: FY2025 net sales $4,000,000 with operating income of $320,000 (an 8.00% margin); FY2026 net sales $4,600,000 with operating income of $391,000 (an 8.50% margin). The regional price index relevant to the segment's inputs and outputs rose 5.0% between the fiscal years. Priya must judge how much of the improvement survives inflation adjustment. Which conclusion follows from the data?",
  "Topic": "A.254 inflation-margin-analysis",
  "UniqueConceptKey": "A-254-price-level-segment-margin",
  "VerifiedChecks": [
    "Verification: 4,600,000/1.05 = 4,380,952; 4,380,952/4,000,000 - 1 = 9.52%; 391,000/1.05 = 372,381 vs 320,000 = +16.37%",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: Moderate/Analyze decomposition supported by stated data table"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
}
];
