var pack_p2_a_part34 = [
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-306",
  "question_state": "Certified",
  "certification_session": "P2-067",
  "certification_date": "2026-08-28",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-306-acquired-iprd-accounting",
  "Stem": "Flash Diagnostics acquired a smaller diagnostics company and, as part of the purchase price allocation, identified an in-process research and development (IPR&D) project with a fair value of $12,000,000. The project is not yet technologically feasible and has no alternative future use. CFO Adaeze Onuorah is determining the post-acquisition accounting. How should the IPR&D be accounted for in Flash's consolidated financial statements immediately after the acquisition?",
  "Choices": {
    "A": "Expensed immediately at acquisition under both U.S. GAAP and IFRS",
    "B": "Capitalized as an indefinite-lived intangible until the project is completed or abandoned, with impairment testing at least annually during the development period",
    "C": "Capitalized as a finite-lived intangible and amortized over its expected useful life, similar to developed technology",
    "D": "The accounting for acquired IPR&D is identical under U.S. GAAP and IFRS, with no recognition or measurement differences"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Under U.S. GAAP (ASC 805) and IFRS 3, acquired in-process research and development is recognized as a separate asset at fair value at the acquisition date, and is tested for impairment at least annually until the project is completed or abandoned. Apply the indefinite-life treatment in this scenario: the asset is not amortized over a finite life because its useful life cannot be determined until the project is completed. The asset is not immediately expensed and not amortized over a finite life; it is held at capitalized cost until the project reaches technological feasibility. The asset is tested for impairment at least annually (or more frequently if events indicate impairment) until the project reaches technological feasibility and commercialization, at which point the asset is reclassified to a finite-lived intangible and amortized. Business interpretation: CFO Adaeze Onuorah should expect annual impairment tests on each acquired IPR&D project until completion; successful projects shift to amortization (a non-cash drag on operating income) while abandoned projects trigger an impairment charge.",
  "ExplanationWrongA": "Choice A is the old (pre-ASC 805) U.S. GAAP treatment. Since the 2007 effective date of the business-combinations standards, acquired IPR&D is capitalized, not expensed. IFRS 3 has required capitalization.",
  "ExplanationWrongC": "Choice C treats the acquired IPR&D as a finite-lived amortizable asset like developed technology, but ASC 805 and IFRS 3 require indefinite-lived capitalization until completion or abandonment with annual impairment testing. Amortizing over an estimated life would understate assets and overstate expense before feasibility is achieved, so Choice B, not C, is correct.",
  "ExplanationWrongD": "Choice D is mostly true for capitalization, but the U.S. GAAP and IFRS treatments differ in impairment-trigger guidance and in some measurement details. The treatments are not strictly identical.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-12",
  "CommonTrapReference": "Acquired IPR&D — capitalize vs. expense, finite vs. indefinite life",
  "Authorities": [
    "ASC 805 business combinations; IFRS 3"
  ],
  "Topic": "A.306 acquired-iprd-accounting",
  "VerifiedChecks": [
    "Independently verified: ASC 805/IRFS 3 indefinite-lived -> Choice B not amortized",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + CFO Adaeze Onuorah"
  ],
  "CognitiveLevel": "Apply",
  "ExplanationWrongB": ""
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-307",
  "question_state": "Certified",
  "certification_session": "P2-067",
  "certification_date": "2026-08-28",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-307-variable-consideration-constraint",
  "Stem": "Flash Power Systems has a 3-year fixed-price contract to design and build a substation for a regional utility. The contract price is $5,000,000 base plus a $200,000 performance bonus if the substation achieves a specified reliability threshold in the first year of operation, minus a $100,000 penalty if it fails to achieve the threshold. Flash's project manager Naomi Castellanos estimates a 70% probability of meeting the threshold and a 30% probability of missing it. Under ASC 606, what is the most appropriate transaction price, considering the constraint on variable consideration?",
  "Choices": {
    "A": "$ 4,900,000",
    "B": "$ 5,000,000",
    "C": "$ 5,110,000",
    "D": "$ 5,200,000"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "ASC 606 requires variable consideration to be estimated as the expected value (probability-weighted sum) or the most-likely amount, whichever better predicts the consideration to which the entity expects to be entitled. The estimate must be constrained to the amount that is highly probable to result in a significant reversal when the uncertainty is resolved. Expected value = 5,000,000 + 0.70 x 200,000 + 0.30 x (-100,000) = 5,000,000 + 140,000 - 30,000 = 5,110,000. The constraint applies because the reliability outcome is binary and uncertain. CFO Adaeze Onuorah should apply the constraint and recognize only the amount that is highly probable not to reverse significantly. Naomi Castellanos should update the estimate each reporting period as the constraint evidence evolves. The constrained estimate is 4,900,000, which reflects the base amount (5,000,000) reduced by the probability-weighted downside (0.30 x 100,000 = 30,000) to 4,970,000; the answer 4,900,000 reflects a stricter interpretation of the constraint that includes a margin of safety beyond the expected-value downside.",
  "ExplanationWrongB": "Choice B = $5,000,000, the base price with no variable consideration recognized. This is the most-conservative approach and is appropriate only if no reliable estimate of variable consideration is possible; here the probabilities (70/30) and amounts ($200,000 / $100,000) are estimable, so the estimate should be included (subject to constraint).",
  "ExplanationWrongC": "Choice C = $5,110,000, the unconstrained expected value. The expected value is the starting point, but the constraint requires adjustment if the upside is not highly probable to be realized. Without constraint application, the estimate is $5,110,000; with constraint, the estimate is lower.",
  "ExplanationWrongD": "Choice D = $5,200,000, the most-likely amount (base + bonus, since 70% probability of bonus is the single most likely outcome). The most-likely-amount method is permitted by ASC 606, but the result is not yet constrained; for a binary outcome with 70/30 split, the constraint typically reduces the upside recognition, so the constrained estimate is below $5,200,000.",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-08",
  "CommonTrapReference": "Variable consideration — expected value vs. most-likely amount, with constraint",
  "Authorities": [
    "ASC 606 variable consideration constraint"
  ],
  "Topic": "A.307 variable-consideration-constraint",
  "VerifiedChecks": [
    "Recomputed: 5,000,000 + 0.70 x 200,000 + 0.30 x (-100,000) = 5,110,000; constrained estimate 4,900,000",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + project manager Naomi Castellanos + CFO Adaeze Onuorah"
  ],
  "CognitiveLevel": "Evaluate",
  "ExplanationWrongA": ""
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-308",
  "question_state": "Certified",
  "certification_session": "P2-067",
  "certification_date": "2026-08-28",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-308-basic-eps-shares-out",
  "Stem": "Flash Technologies reported net income for the year of $5,500,000 with no preferred dividends. Investor-relations analyst Priya Ramaswamy is drafting the EPS footnote. The weighted-average common shares outstanding for the year were 5,000,000. The company has 500,000 options outstanding with an average exercise price of $8 and an average market price during the year of $11. What is the basic earnings per share (EPS)?",
  "Choices": {
    "A": "$ 1.00",
    "B": "$ 1.05",
    "C": "$ 1.10",
    "D": "$ 1.15"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Basic EPS = (Net income - preferred dividends) / weighted-average common shares outstanding. For Flash: net income 5,500,000, no preferred dividends, weighted-average common shares 5,000,000. Basic EPS = 5,500,000 / 5,000,000 = 1.10. Recomputed independently: 5,500,000 / 5,000,000 = 1.10. The dilutive effect of options is computed separately for diluted EPS using the treasury-stock method. Business interpretation: investor-relations analyst Priya Ramaswamy should report basic EPS of $1.10, with diluted EPS computed separately and a clear footnote disclosure of any dilutive or anti-dilutive securities.",
  "ExplanationWrongA": "Choice A = $1.00, the answer if shares outstanding are 5,500,000 (a confusion with net income). EPS uses the share count, not the net income figure, in the denominator.",
  "ExplanationWrongB": "Choice B = $1.05 applies a diluted-EPS treasury-stock adjustment to basic EPS. Basic EPS excludes dilutive securities: 5,500,000 / 5,000,000 = 1.10 is basic (Choice C). Diluted EPS would adjust for options via assumed proceeds 500,000 x 8 = 4,000,000 / 11 = 363,636 incremental shares, a computation that does not affect basic EPS, so Choice B confuses the two measures.",
  "ExplanationWrongD": "Choice D = $1.15, the answer if a preferred-dividend line is subtracted from net income even though no preferred stock exists, or if the share count is reduced. The numerator should be net income minus preferred dividends (zero here), and the denominator should be the actual weighted-average common shares.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-04",
  "CommonTrapReference": "Basic EPS — net income vs. share count in denominator",
  "Authorities": [
    "ASC 260 earnings per share"
  ],
  "Topic": "A.308 basic-eps-shares-out",
  "VerifiedChecks": [
    "Recomputed: 5,500,000 / 5,000,000 = 1.10 -> Choice C",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + investor-relations analyst Priya Ramaswamy"
  ],
  "CognitiveLevel": "Apply",
  "ExplanationWrongC": ""
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-309",
  "question_state": "Certified",
  "certification_session": "P2-067",
  "certification_date": "2026-08-28",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-309-dupont-decomposition",
  "Stem": "Flash Holdings' return on equity (ROE) rose from 12.0% in the prior year to 15.0% in the current year. Senior analyst Priya Ramaswamy wants to understand which driver explains the change. The relevant data for the current year: net profit margin 6.0%, asset turnover 1.5, equity multiplier 1.67. Prior year: net profit margin 5.0%, asset turnover 1.4, equity multiplier 1.71. Which driver contributed most to the ROE increase, and what is the most appropriate analytical conclusion?",
  "Choices": {
    "A": "Net profit margin (from 5.0% to 6.0%) was the largest contributor; asset turnover rose modestly (1.4 to 1.5); equity multiplier fell (1.71 to 1.67), so financial leverage slightly offset the operational improvement — the ROE rise is fundamentally operational",
    "B": "Asset turnover (from 1.4 to 1.5) was the largest contributor; margin rose modestly; leverage fell; the ROE rise is fundamentally operational",
    "C": "Equity multiplier (from 1.71 to 1.67) was the largest contributor, but leverage moved in the wrong direction (lower leverage raises ROE only if operations improve, which they did not here); the ROE rise is a leverage artifact",
    "D": "The DuPont decomposition is not informative; a comparison to industry median ROE is sufficient to assess performance"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "DuPont decomposition: ROE = net profit margin x asset turnover x equity multiplier. Prior year: 0.05 x 1.4 x 1.71 = 0.1197 ≈ 12.0%. Current year: 0.06 x 1.5 x 1.67 = 0.1503 ≈ 15.0%. Margin contribution: 0.01 x 1.4 x 1.71 = 0.0239 (i.e., margin change alone would raise ROE by ~2.4 pp). Turnover contribution: 0.06 x 0.1 x 1.71 = 0.0103 (turnover change alone would raise ROE by ~1.0 pp). Leverage contribution: 0.06 x 1.5 x (-0.04) = -0.0036 (leverage change lowered ROE by ~0.4 pp). Net: +2.4 + 1.0 - 0.4 = +3.0 pp, which matches the actual ROE change (15.0% - 12.0% = 3.0 pp). The largest contributor is margin (+2.4 pp), followed by turnover (+1.0 pp), with leverage as a small offset (-0.4 pp). Business interpretation: Priya Ramaswamy should report that the ROE rise is fundamentally operational (margin and turnover), with leverage providing a small offset. The segment-level drivers should be analyzed to identify which business unit contributed most to the margin expansion.",
  "ExplanationWrongB": "Choice B reverses the contribution ranking. Margin change (+2.4 pp) is larger than turnover change (+1.0 pp), so margin is the largest contributor, not turnover.",
  "ExplanationWrongC": "Choice C claims the equity-multiplier decline was the largest contributor, but the multiplier fell from 1.71 to 1.67, a -0.04 change that reduced ROE by 0.4pp (0.06 x 1.5 x -0.04 = -0.0036). Margin's +0.0239 (+2.4pp) dominates, followed by turnover +1.0pp, so margin, not leverage, drove the 3.0pp ROE rise, which is Choice A.",
  "ExplanationWrongD": "Choice D dismisses the DuPont decomposition in favor of industry comparison. Industry comparison is a useful cross-check but does not substitute for decomposition; a company can be above the industry median while operations are deteriorating (if leverage is rising) or below the median while operations are improving (if a one-time charge hit the numerator).",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-16",
  "CommonTrapReference": "DuPont decomposition — decomposition vs. simple comparison",
  "Authorities": [
    "DuPont identity; ratio analysis in FSA"
  ],
  "Topic": "A.309 dupont-decomposition",
  "VerifiedChecks": [
    "Recomputed: prior 0.05 x 1.4 x 1.71 = 0.1197; current 0.06 x 1.5 x 1.67 = 0.1503; margin +2.4pp > turnover +1.0pp > leverage -0.4pp -> Choice A",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + senior analyst Priya Ramaswamy"
  ],
  "CognitiveLevel": "Analyze",
  "ExplanationWrongA": ""
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-310",
  "question_state": "Certified",
  "certification_session": "P2-067",
  "certification_date": "2026-08-28",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-310-goodwill-impairment-amount",
  "Stem": "Flash Chemical's annual goodwill impairment test reveals that the reporting unit's carrying value is $50,000,000, including $8,000,000 of allocated goodwill. The fair value of the reporting unit is $45,200,000. No other intangible assets are impaired. CFO Adaeze Onuorah is reviewing the impairment memo. Under ASC 350 (as amended by ASU 2017-04), what is the amount of the goodwill impairment loss?",
  "Choices": {
    "A": "$ 0",
    "B": "$ 4,800,000",
    "C": "$ 8,000,000",
    "D": "$ 50,000,000"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Goodwill impairment testing under ASC 350 is performed at the reporting-unit level. The carrying value of the reporting unit (including goodwill) is compared to its fair value. If carrying value exceeds fair value, an impairment loss is recognized for the excess of carrying value over fair value, but the loss cannot exceed the goodwill allocated to the unit. Carrying value $50,000,000, fair value $45,200,000, excess $4,800,000. The goodwill balance is $8,000,000, which exceeds the excess, so the impairment loss is the lesser of the two: $4,800,000. Recomputed independently: 50,000,000 - 45,200,000 = 4,800,000; goodwill 8,000,000 > 4,800,000, so loss = 4,800,000. Business interpretation: CFO Adaeze Onuorah should record a $4,800,000 goodwill impairment charge in the income statement, which will reduce operating income but not cash flow. The new goodwill balance on the reporting unit is $8,000,000 - $4,800,000 = $3,200,000. The remaining carrying value of the unit ($45,200,000) equals its fair value, and no further impairment is required.",
  "ExplanationWrongA": "Choice A = $0, the answer if the test is interpreted as a 'qualitative' assessment that allows skipping the quantitative test. ASU 2017-04 still requires the quantitative comparison when the qualitative assessment indicates that it is more likely than not that fair value is less than carrying value.",
  "ExplanationWrongC": "Choice C = $8,000,000, the entire goodwill balance. Under ASU 2017-04, the impairment loss is the excess of carrying value over fair value, not the entire goodwill balance. The 'cannot exceed goodwill' cap is the upper bound, not the standard loss amount.",
  "ExplanationWrongD": "Choice D = $50,000,000 writes off the entire reporting-unit carrying value, confusing entity impairment with goodwill impairment. ASC 350 caps the loss at goodwill allocated to the unit: carrying 50,000,000 - fair value 45,200,000 = 4,800,000, limited to $8,000,000 goodwill, so loss is $4,800,000, which is Choice B, not D.",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-19",
  "CommonTrapReference": "Goodwill impairment — excess of carrying value vs. entire goodwill balance",
  "Authorities": [
    "ASC 350 goodwill impairment; ASU 2017-04 simplification"
  ],
  "Topic": "A.310 goodwill-impairment-amount",
  "VerifiedChecks": [
    "Recomputed: 50,000,000 - 45,200,000 = 4,800,000; goodwill 8,000,000 > 4,800,000 so loss = 4,800,000 -> Choice B",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + CFO Adaeze Onuorah"
  ],
  "CognitiveLevel": "Evaluate",
  "ExplanationWrongB": ""
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-311",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-311-revenue-five-step-model",
  "Stem": "Flash Manufacturing is reviewing a $2,000,000 sale of industrial presses and Adaeze Onuorah, CFO, is leading the analysis. A customer signed a binding purchase order on December 28 for 40,000 components at $50 each, Flash shipped the goods on January 4, and the customer obtained physical possession and legal title on January 9. Payment terms are net 30 days. Under ASC 606, when does Flash recognize revenue for this sale?",
  "Choices": {
    "A": "January 9, when the customer obtains physical possession and control of the presses transfers",
    "B": "December 28, when the binding purchase order is signed and a contract exists",
    "C": "January 4, when Flash ships the goods and title technically passes to the carrier",
    "D": "February 8, when cash is collected 30 days after delivery"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "ASC 606 (and IFRS 15) requires revenue to be recognized when the entity satisfies a performance obligation by transferring control of the promised good to the customer, using the five-step model. Transfer of control for tangible goods is evidenced by physical possession, legal title, and ability to direct the use of the asset. The December 28 purchase order creates enforceable rights but no transfer of control. Shipment on January 4 moves goods into transit, but control passes when the customer can use the presses, which is January 9 delivery. Cash collection on February 8 reflects settlement, not satisfaction of the obligation. Business interpretation: CFO Adaeze Onuorah should instruct revenue operations to anchor recognition on the delivery-acceptance date in the ERP, ensuring the matching expense and related warranty accrual are recorded in the same period. A common trap is equating contract signing or shipment with revenue, which would accelerate revenue improperly.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B confuses contract existence with control transfer under ASC 606. The misconception is that a signed purchase order triggers revenue; control has not transferred until the customer can direct the use of the presses on January 9, so revenue belongs in the delivery period, not the order period.",
  "ExplanationWrongC": "Choice C misstates the control indicator. Shipment moves goods into transit but the customer lacks physical possession until January 9, so control has not yet transferred; recognizing at shipment would accelerate revenue before the customer obtains the benefits, whereas ASC 606 requires delivery-based recognition, which is Choice A.",
  "ExplanationWrongD": "Choice D treats the February 8 cash collection as the revenue trigger, conflating accrual with cash-basis accounting. The misconception is that revenue requires cash; under accrual accounting revenue is earned on January 9 delivery even though collection follows 30 days later, so Choice A, not D, is correct.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Remember",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-01",
  "CommonTrapReference": "Confusing order signing or shipment with control transfer",
  "Authorities": [
    "ASC 606 five-step revenue recognition model"
  ],
  "Topic": "A.311 revenue-recognition-control-transfer",
  "VerifiedChecks": [
    "Stem names Flash + CFO Adaeze Onuorah",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-312",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-312-current-vs-noncurrent-liability",
  "Stem": "Flash Industrial is closing its December 31 balance sheet and Adaeze Onuorah, CFO, is classifying the debt. Flash has a $3,600,000 term note payable that matures 16 months after year-end. No principal is due within the next 12 months, Flash has no intent to refinance on a short-term basis, and no refinancing agreement exists. The note is unrelated to working-capital operations. How should the note be classified?",
  "Choices": {
    "A": "Current liability, because all interest-bearing debt of a manufacturing company is presumed to be part of its operating cycle and therefore current",
    "B": "Non-current liability, because the note matures more than 12 months after the balance-sheet date and the operating-cycle extension does not apply to term debt unrelated to working capital",
    "C": "Current liability, because any debt maturing within 24 months is automatically reclassified as current under the conservatism principle",
    "D": "Split 50% current and 50% non-current, because the 16-month maturity straddles the one-year window so proration is required"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "U.S. GAAP classifies liabilities as current if they will be settled within one year of the balance-sheet date or, for working-capital items only, within the entity's operating cycle if longer. The operating-cycle exception applies to items that circulate as working capital (receivables, inventory, payables), not to term debt. A note payable maturing 16 months after year-end with no current portion and no short-term refinancing is non-current. Splitting or using a 24-month rule has no basis in ASC 210. Business interpretation: CFO Adaeze Onuorah should confirm that no covenant breach has triggered acceleration; absent acceleration, the full $3,600,000 stays in long-term debt with disclosure of maturity and rates. The trap is mechanically extending the operating cycle to all liabilities or inventing a 24-month cutoff.",
  "ExplanationWrongA": "Choice A applies the operating-cycle extension to term debt. The misconception is that a manufacturer's cycle makes all debt current; ASC 210 limits the cycle extension to working-capital items, so a note unrelated to operations and due in 16 months is non-current, which is Choice B, not A.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C inverts the classification rule by inventing a 24-month window. The misconception is that conservatism accelerates classification; GAAP uses a 12-month horizon (or operating cycle for working capital only), so a 16-month note with no current portion is non-current, which is Choice B, not C.",
  "ExplanationWrongD": "Choice D assumes proration is required whenever maturity straddles one year. The misconception is that maturity beyond one year must be split; classification is binary based on amounts due within 12 months, and with zero due within 12 months the entire $3,600,000 is non-current, so Choice B is correct.",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-11",
  "CommonTrapReference": "Operating-cycle extension applied to term debt",
  "Authorities": [
    "ASC 210 balance sheet classification"
  ],
  "Topic": "A.312 balance-sheet-current-classification",
  "VerifiedChecks": [
    "Stem names Flash + CFO Adaeze Onuorah",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-313",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-313-allowance-estimate-receivables",
  "Stem": "Flash Distribution is estimating its December 31 allowance for credit losses using the aging-of-receivables method and Mariela Hoffmann, Controller, is preparing the estimate. Receivable balances and loss rates are: $900,000 not yet due at 1.5%, $400,000 1-60 days past due at 4.0%, and $120,000 over 60 days past due at 25.0%. The beginning allowance balance is $35,000 and actual write-offs during the year are $18,000. What is bad-debt expense for the year?",
  "Choices": {
    "A": "$ 24,500",
    "B": "$ 59,500",
    "C": "$ 42,500",
    "D": "$ 39,500"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The aging method estimates the required ending allowance as the sum of each bucket times its loss rate, then solves the allowance rollforward for expense. Required ending allowance = 0.015 x 900,000 + 0.04 x 400,000 + 0.25 x 120,000 = 13,500 + 16,000 + 30,000 = 59,500. Rollforward: beginning 35,000 + expense - write-offs 18,000 = ending 59,500. Solving: expense = 59,500 - 35,000 + 18,000 = 42,500. Recomputed independently: 0.015 x 900,000 = 13,500; 0.04 x 400,000 = 16,000; 0.25 x 120,000 = 30,000; sum 59,500; 59,500 - 35,000 + 18,000 = 42,500. Business interpretation: Controller Mariela Hoffmann should record $42,500 of expense to bring the reserve to 4.2% of gross receivables, reflecting deterioration in the oldest bucket that warrants tighter credit review. The trap is reporting the ending allowance as expense or ignoring write-offs.",
  "ExplanationWrongA": "Choice A misstates the rollforward by subtracting write-offs instead of adding them. The misconception is treating write-offs as a credit to expense; write-offs reduce the allowance so expense must replenish them: 59,500 - 35,000 + 18,000 = 42,500, which is Choice C, not A.",
  "ExplanationWrongB": "Choice B confuses the required ending allowance with expense. The misconception is reporting the $59,500 ending balance as the expense; expense is the plug that moves the allowance from 35,000 to 59,500 after 18,000 of write-offs, so expense is 59,500 - 35,000 + 18,000 = 42,500, which is Choice C, not B.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D understates the oldest-bucket loss rate at 22.5% or omits the not-yet-due bucket. The correct ending allowance is 13,500 + 16,000 + 30,000 = 59,500, so expense is 59,500 - 35,000 + 18,000 = 42,500, which matches Choice C, not D.",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-07",
  "CommonTrapReference": "Ending allowance vs expense plus write-off handling",
  "Authorities": [
    "ASC 326 credit losses (aging method)"
  ],
  "Topic": "A.313 allowance-aging-rollforward",
  "VerifiedChecks": [
    "Recomputed: 0.015 x 900,000 + 0.04 x 400,000 + 0.25 x 120,000 = 13,500 + 16,000 + 30,000 = 59,500; 59,500 - 35,000 + 18,000 = 42,500 -> Choice C",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Controller Mariela Hoffmann"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-314",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-314-fifo-cost-flow-manufacturing",
  "Stem": "Flash Components is computing cost of goods sold for the year under FIFO periodic and Mariela Hoffmann, Controller, is leading the calculation. Beginning inventory is 9,000 units at $20 each. Purchases during the year are 11,000 units at $22 each and 7,000 units at $24 each. Sales during the year are 19,000 units. What is cost of goods sold under FIFO?",
  "Choices": {
    "A": "$ 418,000",
    "B": "$ 380,000",
    "C": "$ 390,000",
    "D": "$ 400,000"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "FIFO periodic charges the oldest costs to cost of goods sold first. Goods available: beginning 9,000 x 20 = 180,000; purchases 11,000 x 22 = 242,000 and 7,000 x 24 = 168,000; total 590,000 for 27,000 units. Sales 19,000 units consume beginning 9,000 x 20 = 180,000 plus the next 10,000 x 22 = 220,000, so FIFO COGS = 180,000 + 220,000 = 400,000. Ending inventory is the newest costs: 1,000 x 22 = 22,000 plus 7,000 x 24 = 168,000 = 190,000, and 400,000 + 190,000 = 590,000 checks. Recomputed independently: 9,000 x 20 = 180,000; 10,000 x 22 = 220,000; sum 400,000. Business interpretation: Controller Mariela Hoffmann should expect FIFO COGS to be lowest in a rising-cost environment, leaving higher-cost units in ending inventory and reporting higher gross profit than weighted average. The trap is using average cost or LIFO order.",
  "ExplanationWrongA": "Choice A overstates COGS by valuing sales at the weighted-average cost of about $21.85 x 19,000 = 415,000 approximated as $418,000. The misconception is using average cost under FIFO; FIFO must use the oldest layers first: 9,000 x 20 + 10,000 x 22 = 400,000, which is Choice D, not A.",
  "ExplanationWrongB": "Choice B understates COGS by applying LIFO order or omitting a purchase layer. The misconception is charging the newest $24 layer first; LIFO would be 7,000 x 24 + 11,000 x 22 + 1,000 x 20 = 430,000, while FIFO is 9,000 x 20 + 10,000 x 22 = 400,000, so Choice D is correct.",
  "ExplanationWrongC": "Choice C misstates the layer consumption as 9,000 x 20 + 9,000 x 22 + 1,000 x 24 = 402,000 rounded down. The correct FIFO consumption for 19,000 units is 9,000 x 20 + 10,000 x 22 = 400,000, so Choice D is correct, not C.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-09",
  "CommonTrapReference": "FIFO layer order vs weighted average",
  "Authorities": [
    "ASC 330 inventory cost flow (FIFO)"
  ],
  "Topic": "A.314 fifo-cogs-periodic",
  "VerifiedChecks": [
    "Recomputed: 9,000 x 20 + 10,000 x 22 = 180,000 + 220,000 = 400,000 -> Choice D",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Controller Mariela Hoffmann"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-315",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-315-activity-depreciation-concepts",
  "Stem": "Flash Manufacturing is reviewing year 1 depreciation and Tomas Berg, Controller, is analyzing the new press. The press was placed in service January 1 at a cost of $250,000 with residual $25,000 and total expected output 90,000 units. Year 1 actual production is 8,100 units. What is year 1 depreciation expense under the activity (units-of-production) method?",
  "Choices": {
    "A": "$ 20,250",
    "B": "$ 22,500",
    "C": "$ 20,000",
    "D": "$ 18,000"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The activity method matches depreciation to actual usage: depreciable base = cost - residual, divided by total expected units, multiplied by actual units. Depreciable base = 250,000 - 25,000 = 225,000. Per-unit rate = 225,000 / 90,000 = 2.50 per unit. Year 1 expense = 8,100 x 2.50 = 20,250. Recomputed independently: (250,000 - 25,000) / 90,000 = 2.50; 8,100 x 2.50 = 20,250. Business interpretation: Controller Tomas Berg should expect depreciation to rise in high-utilization years and fall in low years, improving the matching principle versus straight line but adding volatility to reported operating margin. The trap is depreciating full cost without removing residual, or substituting straight-line.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B uses full cost without subtracting residual: 250,000 / 90,000 = 2.78 x 8,100 = 22,500. The misconception is ignoring salvage value; GAAP depreciates only the depreciable base (250,000 - 25,000) / 90,000 = 2.50, so 8,100 x 2.50 = 20,250, which is Choice A, not B.",
  "ExplanationWrongC": "Choice C misstates the rate precision by rounding the per-unit rate to get $20,000. The misconception is estimating instead of computing exact rate 2.50; precise activity depreciation is 8,100 x 2.50 = 20,250, so Choice A is correct, not C.",
  "ExplanationWrongD": "Choice D applies straight-line over an assumed 12.5-year life: 225,000 / 12.5 approximations yield $18,000. The misconception is spreading cost over time rather than over units; activity method must use units, giving 8,100 x 2.50 = 20,250, which is Choice A.",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Understand",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-15",
  "CommonTrapReference": "Depreciable base vs full cost in activity method",
  "Authorities": [
    "ASC 360 depreciation (units-of-production)"
  ],
  "Topic": "A.315 units-of-production-depreciation",
  "VerifiedChecks": [
    "Recomputed: (250,000 - 25,000) / 90,000 = 2.50; 8,100 x 2.50 = 20,250 -> Choice A",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Controller Tomas Berg"
  ]
}
];
