var pack_p2_a_part15 = [
{
  "Authorities": [
    "ASC 830",
    "ASC 830-10-45"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "The EUR depreciation creates a translation loss of $3.5M recognized in net income because the subsidiary's functional currency differs from the parent's reporting currency.",
    "B": "Under ASC 830, because the subsidiary's functional currency (EUR) differs from the parent's reporting currency (USD), translation uses the current rate method. Net income (EUR 8M) is translated at the average rate; net assets (EUR 50M) at the year-end rate of $1.05. The resulting translation adjustment of approximately $3.5M is reported in Other Comprehensive Income (OCI), not net income.",
    "C": "The EUR depreciation creates a transaction loss of $3.5M recognized in net income because the subsidiary's euro-denominated assets are worth less in USD terms. The loss equals EUR 50M × ($1.12−$1.05).",
    "D": "No adjustment is required. Under ASC 830, when a foreign subsidiary's functional currency is the local currency, its financial statements are reported at the historical exchange rate from the date of initial investment."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Confusing translation adjustments (OCI, current rate method) with transaction gains/losses (net inco",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 830, the translation method depends on the functional currency. When the functional currency is the local currency (EUR), the current rate method applies: (1) assets and liabilities are translated at the year-end rate ($1.05), (2) income statement items at the weighted-average rate, and (3) the translation adjustment is reported in OCI. The weakening EUR from $1.12 to $1.05 means the subsidiary's net assets, previously worth approximately $56M at the beginning rate, are now worth $52.5M — a $3.5M reduction. This translation adjustment affects the consolidated balance sheet through accumulated OCI, not net income. The distinction is fundamental: translation adjustments (OCI) arise from consolidating foreign-currency financial statements; transaction gains/losses (net income) arise from actual foreign-currency-denominated transactions. The subsidiary's operations within the Eurozone mean its EUR functional currency is correct — there is no remeasurement requirement.",
  "ExplanationWrongA": "Under ASC 830, translation adjustments from subsidiaries with a local functional currency are reported in OCI, not net income. A translation loss would only flow through net income if the subsidiary operated in a highly inflationary economy or if its functional currency were the reporting currency (USD), requiring remeasurement rather than translation. Neither condition applies here.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "This confuses translation exposure with transaction exposure. Translation exposure arises from consolidating foreign-currency financial statements — it is an accounting construct affecting OCI. Transaction exposure arises from specific foreign-currency-denominated transactions (receivables, payables) where exchange rate changes between transaction and settlement dates create realized gains/losses flowing through net income. No specific foreign currency transactions are described here.",
  "ExplanationWrongD": "ASC 830 requires ALL foreign subsidiaries to be translated into the parent's reporting currency for consolidation — there is no exemption for autonomous operations. The functional currency determination selects the method (current rate vs. remeasurement), not whether translation occurs. Reporting at historical exchange rates indefinitely would violate the requirement for a single reporting currency in consolidated statements.",
  "FormulaReference": "Translation adjustment = Net assets × (End rate − Beginning rate); reported in OCI per ASC 830",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-109",
  "Section": "A",
  "Stem": "U.S.-based GlobalTech Industries owns a wholly-owned German subsidiary that manufactures and sells exclusively within the Eurozone. The subsidiary's functional currency is the euro (EUR). During the year, the EUR weakened from $1.12 to $1.05. The subsidiary reported net income of EUR 8 million and net assets of EUR 50 million. Controller Maria Santos must explain the exchange rate impact on GlobalTech's consolidated financial statements. Which analysis is correct?",
  "Topic": "A.109 Translation exposure — functional currency determination under ASC 830",
  "UniqueConceptKey": "A-109-translation-exposure-functional-currency-determination-",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: EUR 50M×(1.12−1.05)=$3.5M translation loss in OCI. B correctly identifies OCI treatment.",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 842",
    "ASC 840"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Adjusted D/E = 2.10. Pacific violates the 1.75 covenant. Capitalization adds $72M to debt (total $252M) without increasing equity ($120M). The adjusted D/E of $252M/$120M = 2.10 exceeds the 1.75 ceiling by 20%.",
    "B": "Adjusted D/E = 1.50. Operating leases are not debt under GAAP and should not be included in covenant calculations regardless of the analyst's preference. Pacific is in compliance.",
    "C": "Adjusted D/E = 2.25. Capitalization uses the undiscounted $90M in lease payments, giving total debt of $270M and D/E = $270M/$120M = 2.25. Pacific violates the covenant by an even wider margin.",
    "D": "Adjusted D/E = 1.625. Capitalization adds the annual lease expense ($90M/6 = $15M) rather than the PV, giving total debt of $195M and D/E = $195M/$120M ≈ 1.63. Pacific remains in compliance."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Using undiscounted lease commitments or single-year expense instead of the PV — both misstate the le",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Off-balance-sheet financing creates economic liabilities not recorded on the balance sheet. Under pre-ASC 842 treatment (and in standard credit analysis even after ASC 842 adoption), analysts capitalize operating leases by computing the PV of minimum lease payments and adding this amount to debt. Here, PV = $72M at a 7% rate over 6 years. Adjusted debt = $180M + $72M = $252M. Equity remains $120M (lease expense has already been reflected in retained earnings). Adjusted D/E = $252M / $120M = 2.10. This exceeds the 1.75 covenant ceiling by $0.35 (20%), placing Pacific in violation. The key insight: a company appearing to have a conservative D/E of 1.50 may have significantly higher economic leverage once off-balance-sheet obligations are recognized. Rating agencies and lenders routinely make these adjustments — the covenant definition of 'debt' in the loan agreement, not GAAP classification, governs covenant compliance.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "While it is true that operating leases were historically not recorded as debt under pre-ASC 842 GAAP, credit analysis and covenant compliance are not constrained by GAAP classification. Lenders define 'debt' in loan agreements to include capitalized operating leases, guarantees, and letters of credit — the covenant definition, not GAAP, governs. A CFO who relies on GAAP classification while ignoring the lender's stated methodology is failing to anticipate an entirely foreseeable covenant violation.",
  "ExplanationWrongC": "The undiscounted sum of $90M overstates the economic liability because it ignores the time value of money. A dollar of lease payment due in 6 years is worth less today than a dollar due next year. Standard analytical practice uses the PV of future lease payments discounted at the lessee's incremental borrowing rate. The undiscounted $90M represents the sum of cash outflows, not the economic liability.",
  "ExplanationWrongD": "The annual lease expense ($15M) represents one year's obligation, not the total economic liability. Capitalizing only one year's payment grossly understates the leverage impact — Pacific is contractually committed to make payments over 6 years that together constitute an economic obligation substantially larger than a single year's expense. The appropriate capitalization amount is the PV of all remaining lease payments.",
  "FormulaReference": "Capitalized lease PV = PV of minimum lease payments; Adjusted D/E = (Debt + PV of Leases) / Equity",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-110",
  "Section": "A",
  "Stem": "CFO Michael Torres is preparing Pacific Freight's debt covenant certificate. Pacific's balance sheet shows total debt $180M and total equity $120M (D/E = 1.50). The covenant requires D/E ≤ 1.75. Pacific also has $90M in non-cancelable operating lease commitments for its trucking fleet with a 6-year weighted-average remaining term and a 7% incremental borrowing rate. The PV of these lease payments is $72M. The bank's analyst will capitalize operating leases for covenant calculation. What is Pacific's adjusted D/E, and is the company in compliance?",
  "Topic": "A.110 Off-balance-sheet financing — operating lease capitalization impact on D/E",
  "UniqueConceptKey": "A-110-off-balance-sheet-financing-operating-lease-capitalizat",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: PV=$72M, Adj Debt=$252M, Adj D/E=2.10 — violates 1.75 covenant",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 810",
    "ASC 810-10-25"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "No. EnergyCo holds zero equity in PowerGen, and consolidation under ASC 810 requires an equity ownership interest. The guarantee and PPA are executory contracts, not ownership instruments.",
    "B": "Yes. EnergyCo is the primary beneficiary of PowerGen, a variable interest entity. Through the 90% guarantee (absorbing expected losses), the PPA terms (directing significant activities), and the nominal purchase option (receiving residual returns), EnergyCo satisfies both criteria for primary beneficiary status. The absence of equity is irrelevant — the VIE consolidation model looks through legal form to economic substance.",
    "C": "Partially. EnergyCo should proportionally consolidate 90% of PowerGen's assets and liabilities, corresponding to its 90% debt guarantee. It does not control the remaining 10%.",
    "D": "Only if non-consolidation would be misleading to investors. Under the management judgment provisions of ASC 810, VIE consolidation by a non-equity sponsor is optional."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Assuming equity ownership is required for consolidation — the VIE model under ASC 810 was specifical",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Under ASC 810, the VIE consolidation model requires consolidation by the primary beneficiary regardless of equity ownership. An entity is a VIE if equity is insufficient to finance operations without subordinated support — PowerGen qualifies because its equity cannot absorb losses without EnergyCo's 90% debt guarantee. The primary beneficiary is the party that has BOTH (a) power to direct activities that most significantly impact the VIE's economic performance, AND (b) the obligation to absorb losses or right to receive benefits that could be significant. EnergyCo satisfies (a) through the PPA terms and the purchase option, which together determine PowerGen's economic performance. It satisfies (b) through the 90% guarantee (obligation to absorb losses) and the nominal purchase option (right to receive essentially all residual returns). This was precisely the Enron structure — SPEs with nominal third-party equity, parent guarantees, and contractual arrangements making the parent the de facto owner. ASC 810 was revised in response to Enron specifically to require consolidation in these circumstances.",
  "ExplanationWrongA": "This analysis incorrectly assumes equity ownership is required for consolidation. Under ASC 810, the VIE model specifically addresses entities where voting equity is not the controlling factor — that is the entire purpose of the VIE guidance. EnergyCo's lack of equity ownership is the very reason the VIE analysis must be performed. If equity were the controlling factor, sponsors could avoid consolidation by structuring SPEs with nominal third-party equity while retaining all substantive economic exposure.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "ASC 810 does not provide for proportional consolidation of VIEs. The primary beneficiary must consolidate 100% of the VIE's assets, liabilities, and operations, regardless of the proportion of variable interests held. Proportional consolidation would understate EnergyCo's exposure — the full $180M guaranteed (90% × $200M) is EnergyCo's obligation even without 100% equity ownership.",
  "ExplanationWrongD": "VIE consolidation by the primary beneficiary is mandatory under ASC 810-10-25-38, not optional or subject to management judgment about whether non-consolidation would be misleading. This confuses the VIE standard with the general requirement that financial statements not be misleading. Consolidation is required when the criteria are met.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-111",
  "Section": "A",
  "Stem": "Controller Lisa Park reviews EnergyCo's relationship with PowerGen SPE LLC, created to finance and own a new power plant. EnergyCo holds no equity in PowerGen but: (1) guarantees 90% of PowerGen's $200M debt, (2) has a 20-year power purchase agreement with prices ensuring PowerGen can service debt, and (3) holds the right to purchase the plant for a nominal amount at the end of the PPA term. Management argues that because EnergyCo owns no equity, consolidation is not required. Under ASC 810, is consolidation required?",
  "Topic": "A.111 Variable interest entities — primary beneficiary determination under ASC 810",
  "UniqueConceptKey": "A-111-variable-interest-entities-primary-beneficiary-determin",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: EnergyCo is primary beneficiary (power+losses+returns) → must consolidate per ASC 810",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Pre-automation DOL = 2.50; Post-automation DOL = 3.00. The higher DOL post-automation means operating income is 20% more sensitive to sales changes — a 10% sales increase now produces a 30% OI increase instead of 25%.",
    "B": "Pre-automation DOL = 2.50; Post-automation DOL = 2.50. DOL is invariant because the ratio of fixed costs to operating income remains constant despite the cost structure change.",
    "C": "Pre-automation DOL = 1.67; Post-automation DOL = 2.00. Automation increases risk because higher fixed costs amplify earnings volatility.",
    "D": "Pre-automation DOL = 6.25; Post-automation DOL = 5.00. Automation reduces DOL because higher contribution margins offset the additional fixed costs."
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using revenue or variable costs as the numerator instead of contribution margin; confusing DOL = CM/OI with cost-structure ratios (CM/FC) or revenue-based ratios (Revenue/OI)",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "DOL = Contribution Margin / Operating Income. Pre-automation: CM = $50M − $30M = $20M. OI = $20M − $12M = $8M. DOL = $20M / $8M = 2.50. Post-automation: Variable costs at 52% of revenue = $26M. CM = $50M − $26M = $24M. Fixed costs = $12M + $4M = $16M. OI = $24M − $16M = $8M. Same OI but higher CM. DOL = $24M / $8M = 3.00. The DOL increased from 2.50 to 3.00 because the contribution margin increased proportionally more than operating income. Using the alternative formula DOL = 1 + (Fixed Costs / OI): Pre: 1 + ($12M/$8M) = 2.50. Post: 1 + ($16M/$8M) = 3.00. The increase in fixed costs ($12M→$16M) relative to unchanged OI ($8M) drives the higher DOL. Business interpretation: Post-automation, a 10% sales increase boosts OI by 30% (vs. 25% pre), but a 10% sales decline also reduces OI by 30% — automation increased both upside and downside earnings sensitivity.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "DOL is 2.50 post-automation only if the ratio of fixed costs to OI stays exactly at 1.50. Post-automation, FC=$16M and OI=$8M, yielding DOL = 1 + ($16M/$8M) = 3.00. The fixed cost increase ($12M→$16M, +33%) was proportionally larger than the OI change (which stayed flat because $24M−$16M=$8M, same as pre). The DOL changed — the assertion that it is invariant is incorrect.",
  "ExplanationWrongC": "Pre-automation DOL is $20M/$8M = 2.50, not 1.67. The value 1.67 might come from CM/Fixed Costs = $20M/$12M = 1.67 — a ratio that describes cost structure but is not the DOL formula. DOL = CM/OI, not CM/FC. The conceptual claim that automation increases risk is correct directionally, but both DOL values are miscalculated.",
  "ExplanationWrongD": "Pre-automation DOL is $20M/$8M = 2.50, not 6.25. The value 6.25 would result from Revenue/OI = $50M/$8M = 6.25 — this measures revenue relative to profit, not operating leverage. Automation increased DOL from 2.50 to 3.00, not decreased it. Higher fixed costs relative to OI always increase DOL.",
  "FormulaReference": "DOL = Contribution Margin / Operating Income = 1 + (Fixed Costs / OI)",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-112",
  "Section": "A",
  "Stem": "CFO Robert Chen evaluates operating leverage at Atlas Manufacturing. Last year: revenue $50M, variable costs $30M (60% of revenue), fixed operating costs $12M, operating income $8M. Atlas is considering automation that would increase fixed costs by $4M while reducing variable costs to 52% of revenue. Mr. Chen must compare the DOL before and after the change. What are the DOL values?",
  "Topic": "A.112 Degree of operating leverage — pre and post automation",
  "UniqueConceptKey": "A-112-degree-of-operating-leverage-pre-and-post-automation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Pre: CM=$20M, OI=$8M, DOL=2.50. Post: CM=$24M, FC=$16M, OI=$8M, DOL=3.00.",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "DuPont Framework",
    "Miller and Modigliani (1961)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Policy X (35% payout) is clearly superior because it maximizes internally fundable growth at 9.43%. Higher retention always creates more shareholder value.",
    "B": "Pacifica should pay zero dividends (100% retention) to maximize SGR at 14.5%, which nearly funds the 18% growth target. Any dividend payment destroys value by forcing the company to raise costly external capital.",
    "C": "Policy Y (55% payout) is preferable because returning more cash to shareholders signals management confidence and increases the stock price, which can then be used as acquisition currency for the new stores.",
    "D": "Neither policy alone funds 18% growth. Policy X's SGR of 9.43% leaves an 8.57-point gap; Policy Y's 6.53% SGR leaves an 11.47-point gap. Pacifica needs external financing under either policy. The choice between X and Y involves a trade-off: Policy X retains more earnings, reducing the external financing need (and its costs), but pays a lower dividend, which may disappoint income-oriented shareholders. Policy Y pays a higher dividend but requires more external financing, increasing leverage and flotation costs."
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Treating higher SGR as always superior — SGR is a constraint, not an objective; dividend policy invo",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "The sustainable growth rate (SGR = ROE × retention ratio) represents the maximum growth rate a company can sustain without changing its capital structure or issuing new equity. Policy X: SGR = 14.5% × 0.65 = 9.43%. Policy Y: SGR = 14.5% × 0.45 = 6.53%. Neither comes close to the 18% target growth rate. The gap must be funded externally — through additional debt (increasing leverage and risk), new equity (diluting existing shareholders), or a combination. The dividend policy choice involves balancing: higher retention (Policy X) reduces external financing needs and their associated costs but limits cash returned to shareholders; higher payout (Policy Y) satisfies income-oriented shareholders but increases dependence on external capital markets. Neither policy is universally superior — the optimal choice depends on shareholder preferences, the cost and availability of external financing, and the credibility of the growth plan. An analyst should present the SGR under each policy alongside the external financing gap rather than advocating for one policy as categorically correct.",
  "ExplanationWrongA": "Policy X maximizes SGR but does not fully fund growth — 9.43% is still 8.57 points below 18%. The assertion that higher retention always creates more value is incorrect: if the company's investment opportunities earn less than the cost of capital, retaining earnings to fund them destroys value. Dividends can be value-enhancing when internal investment opportunities are limited relative to the cost of capital.",
  "ExplanationWrongB": "Zero dividends (100% retention) would increase SGR to 14.5%, still 3.5 points below 18%. The company would need external financing even with no dividend. Furthermore, a sudden shift from paying dividends to paying none can signal distress, potentially increasing the cost of external financing. Dividend policy should be evaluated on its own merits (shareholder preferences, signaling, agency costs), not reduced to a single-variable SGR maximization.",
  "ExplanationWrongC": "The signaling argument for higher dividends is context-dependent. Paying a higher dividend while simultaneously borrowing to fund the growth gap increases financial leverage — the market may interpret this as management having weak growth opportunities (why return cash if the 22 stores are high-return?) or as undisciplined capital allocation. A higher dividend does not automatically increase stock price when the company must borrow to fund it.",
  "ExplanationWrongD": "",
  "FormulaReference": "Sustainable Growth Rate = ROE × (1 − Dividend Payout Ratio)",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-113",
  "Section": "A",
  "Stem": "CEO Elena Vasquez of Pacifica Apparel must choose between two dividend policies. Pacifica's ROE is 14.5%. Under Policy X: 35% dividend payout (65% retention), SGR = 14.5% × 0.65 = 9.43%. Under Policy Y: 55% payout (45% retention), SGR = 14.5% × 0.45 = 6.53%. The company plans 22 new stores requiring 18% annual revenue growth. Which policy analysis is correct?",
  "Topic": "A.113 Dividend payout ratio — SGR and growth implications",
  "UniqueConceptKey": "A-113-dividend-payout-ratio-sgr-and-growth-implications",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Policy X SGR=9.43%, Policy Y SGR=6.53%, neither meets 18% — external financing needed under both",
    "Authority citations match tested concept",
    "Rule4 recomputed: CorrectChoice B->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "DuPont Framework",
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Both companies earn 30% ROE, so they are equally attractive investments. The identical return means the market should value them similarly.",
    "B": "Alpha achieves 30% ROE through high asset efficiency (2.0× turnover), suggesting a high-volume, low-margin strategy — likely a discount or commodity retailer. Beta achieves 30% ROE through high margins (10.0%) and high leverage (3.0× multiplier), suggesting a premium-brand strategy financed with substantial debt. While ROE is identical, Beta's reliance on leverage (3.0× vs. 2.5×) means its ROE is more vulnerable to interest rate increases or credit tightening, and a margin compression would reduce ROE more severely than at Alpha since Beta's model depends on the premium margin.",
    "C": "Beta is the superior company because it earns a higher net profit margin (10.0% vs. 6.0%). Margin quality is more important than volume — it reflects pricing power and brand strength.",
    "D": "Alpha is the superior company because it uses less debt (equity multiplier 2.5× vs. 3.0×). Lower leverage means lower financial risk and more sustainable returns."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Comparing companies on ROE alone without decomposing the drivers — identical ROE can mask fundamenta",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The DuPont decomposition breaks ROE into three drivers: ROE = Net Profit Margin × Asset Turnover × Equity Multiplier. Alpha: 6.0% × 2.0 × 2.5 = 30.0%. Beta: 10.0% × 1.0 × 3.0 = 30.0%. Identical ROE masks fundamentally different paths: Alpha achieves it through volume efficiency — it earns only 6 cents per dollar of sales but generates $2.00 in sales per dollar of assets, with moderate leverage. Beta achieves it through premium pricing (10.0% margin) and higher leverage (3.0×), but its asset efficiency is only half of Alpha's. The investment implications differ: Beta's ROE relies on sustaining both the premium margin (vulnerable to competition) and the high leverage (vulnerable to rising rates). Alpha's ROE relies on sustaining high turnover (vulnerable to demand slowdowns). Neither company is categorically superior — the decomposition reveals different risk profiles that require different monitoring.",
  "ExplanationWrongA": "Identical ROE does not equal identical investment quality. Alpha's ROE is volume-and-efficiency-driven; Beta's is margin-and-leverage-driven. A change in interest rates affects Beta more (higher leverage); a demand slowdown affects Alpha more (lower margins, high fixed-cost base). The decomposition matters because it reveals WHY ROE is 30%, enabling risk assessment that the aggregate number alone cannot provide.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "While Beta's 10.0% margin is higher than Alpha's 6.0%, the DuPont framework shows this is part of a package — Beta pairs high margins with low turnover (1.0×) and high leverage (3.0×). The high margin may reflect premium pricing power, but it also makes Beta more sensitive to margin compression. A 1-percentage-point margin decline reduces Beta's ROE by 3.0 points (1% × 1.0 × 3.0) versus 5.0 points at Alpha (1% × 2.0 × 2.5). The sensitivity differs by component — evaluating only one component of the three-factor model is incomplete.",
  "ExplanationWrongD": "Alpha's lower leverage (2.5× vs. 3.0×) does mean lower financial risk, but lower leverage is not universally superior. If Beta's business generates stable, predictable cash flows, a 3.0× equity multiplier may be sustainable. Judging a company by leverage alone ignores the other two DuPont drivers. Alpha's higher turnover (2.0×) may reflect a low-margin model with high operating leverage — its own form of risk. The DuPont framework is designed for multi-dimensional analysis, not single-factor ranking.",
  "FormulaReference": "ROE = Net Profit Margin × Asset Turnover × Equity Multiplier (DuPont 3-factor)",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-114",
  "Section": "A",
  "Stem": "Analyst Sarah Reeves compares two retailers. Company Alpha: net profit margin 6.0%, asset turnover 2.0×, equity multiplier 2.5×. Company Beta: net profit margin 10.0%, asset turnover 1.0×, equity multiplier 3.0×. Both report ROE of 30%. Ms. Reeves must explain to the investment committee why two companies with identical ROE have fundamentally different business models. Which DuPont decomposition is correct?",
  "Topic": "A.114 DuPont ROE decomposition — comparing two companies",
  "UniqueConceptKey": "A-114-dupont-roe-decomposition-comparing-two-companies",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Alpha: 6%×2.0×2.5=30%. Beta: 10%×1.0×3.0=30%. Different drivers, different risk profiles.",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 255",
    "ASC 255-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Harbor's 10.5% ROA demonstrates superior asset utilization and should be reported to shareholders as evidence of management's effective capital allocation. The higher ROA versus NorthStar's 7.0% reflects operational excellence, not accounting artifacts.",
    "B": "Harbor's ROA is materially overstated because its fixed asset base (the denominator) is recorded at historical cost from 12-15 years ago. Adjusting for 55% cumulative inflation, the current-cost equivalent of Harbor's assets would be approximately 155% of book value, reducing adjusted ROA to roughly 10.5% / 1.55 = 6.8% — slightly below NorthStar's 7.0%. The apparent 350-bp outperformance is an inflation illusion. Harbor's ROA trend improvement (8.2%→10.5%) may also be partly attributable to fixed assets being increasingly understated relative to current costs as inflation accumulates.",
    "C": "Inflation affects all companies equally, so no adjustment is needed. NorthStar's 7.0% ROA and Harbor's 10.5% are directly comparable because both use GAAP historical cost accounting.",
    "D": "Harbor's ROA should be adjusted by adding back depreciation on the inflated asset base. The adjustment increases expenses (higher depreciation on current-cost assets), reducing net income as well as increasing the asset base. The combined effect on ROA cannot be determined from the data provided."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Comparing ROA across companies with different fixed-asset vintages during inflationary periods witho",
  "CorrectChoice": "B",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Under ASC 255 (changing prices), supplementary inflation-adjusted disclosures reveal that historical-cost financial statements systematically overstate returns for companies with older fixed assets during inflationary periods. The denominator (total assets) is understated because fixed assets are carried at historical cost from 12-15 years ago, while the numerator (net income) is recorded in current dollars. With 55% cumulative inflation, the current-cost equivalent of Harbor's assets is approximately 155% of book value. Adjusted ROA = 10.5% / 1.55 ≈ 6.8% — slightly below NorthStar's 7.0%. The apparent 350-bp outperformance disappears upon adjustment. Additionally, Harbor's trend improvement (8.2%→10.5%) is partly mechanical: as inflation accumulates, the fixed-asset denominator becomes increasingly understated relative to current dollars in the numerator, producing a rising ROA trend even if real economic returns are flat or declining. ASC 255-10 encourages disclosure of inflation-adjusted data to prevent users from being misled by historical-cost distortions. Without this adjustment, capital appears to earn higher returns as assets age.",
  "ExplanationWrongA": "The assertion that Harbor's higher ROA reflects operational excellence ignores the denominator effect. Harbor's fixed assets are 12-15 years old, acquired when prices were much lower. The same physical assets, if purchased today, would cost approximately 155% of their book value. Using historical cost, Harbor's asset base is understated by roughly 55%, inflating ROA. Management that reports unadjusted ROA as evidence of performance is claiming credit for an accounting artifact rather than genuine value creation.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Inflation does not affect all companies equally. A company with 15-year-old fixed assets (Harbor) experiences far greater historical-cost distortion than a company with recently constructed facilities (NorthStar). The asset age differential means that comparing the two companies' unadjusted ROAs is comparing assets measured in different purchasing-power units — 12-15-year-old dollars vs. current dollars. GAAP historical cost accounting does not neutralize this distortion; ASC 255 exists precisely because the distortion is material for companies with aged fixed assets.",
  "ExplanationWrongD": "This analysis correctly identifies that both numerator (via higher depreciation) and denominator (via higher asset values) need adjustment, creating offsetting effects. However, for a company with 12-15-year-old assets, the denominator effect is typically much larger (the entire fixed asset base is restated) than the numerator effect (only current-year depreciation increases). The net effect almost always reduces ROA. The direction can be reasonably estimated: since the asset base is understated by approximately 55% and depreciation on 12-15-year-old assets is a fraction of the total asset base, the denominator effect dominates.",
  "FormulaReference": "Inflation-adjusted ROA ≈ Reported ROA / (1 + cumulative inflation rate) for denominator effect",
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-115",
  "Section": "A",
  "Stem": "Director of Finance Priya Kapoor reviews Harbor Industrial's five-year ROA trend computed from historical cost financial statements. Year 1 ROA: 8.2%; Year 5 ROA: 10.5%. Harbor's fixed assets were purchased 12-15 years ago when the general price level was approximately 60% lower. Competitor NorthStar, with recently constructed facilities, reports ROA of 7.0%. Ms. Kapoor must assess whether Harbor's apparent outperformance is real. The cumulative inflation over the period is approximately 55%. Which analysis correctly interprets the inflation distortion?",
  "Topic": "A.115 Inflation-adjusted ratio analysis — historical cost distortion",
  "UniqueConceptKey": "A-115-inflation-adjusted-ratio-analysis-historical-cost-disto",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Adj ROA≈10.5%/1.55=6.8%, below NorthStar 7.0% — apparent outperformance is inflation illusion",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "Corporate finance theory",
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "10.65% — NOPAT divided by total capital before deducting non-operating cash ($21.3M ÷ $200M)",
    "B": "12.53% — NOPAT divided by invested capital net of non-operating cash ($21.3M ÷ $170M)",
    "C": "14.20% — EBIT divided by total capital ($28.4M ÷ $200M)",
    "D": "15.21% — NOPAT divided by shareholders' equity only ($21.3M ÷ $140M)"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Failing to exclude non-operating cash from invested capital, which dilutes the denominator and understates ROIC",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "ROIC measures the return generated on all capital provided by investors. NOPAT = EBIT × (1 − tax rate) = $28.4M × (1 − 0.25) = $21.3M. Invested capital = debt + equity − non-operating cash = $60M + $140M − $30M = $170M. ROIC = $21.3M ÷ $170M = 12.53%. Because idle cash earns roughly the risk-free rate rather than operating returns, it is excluded from invested capital; leaving it in understates ROIC and misleads the board's capital allocation review. Since 12.53% exceeds Nuvora's 10.5% cost of capital, the operating assets are creating value.",
  "ExplanationWrongA": "10.65% divides NOPAT by $200M of total capital without excluding the $30M of non-operating cash. Cash parked for an unexecuted acquisition is not deployed in operations, so it should not dilute the denominator; keeping it there understates the return earned by operating assets. Invested capital is debt plus equity minus excess cash: $60M + $140M − $30M = $170M.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "14.20% uses pre-tax EBIT in the numerator. ROIC requires after-tax operating profit (NOPAT) because investors can only consume after-tax returns. Applying the 25% tax rate converts $28.4M to $21.3M. Using EBIT overstates the return available to capital providers.",
  "ExplanationWrongD": "15.21% divides NOPAT by equity alone. ROIC covers all invested capital — debt holders and shareholders both finance the asset base. Excluding the $60M of debt understates the capital base and overstates the return.",
  "FormulaReference": "ROIC = NOPAT ÷ Invested Capital (Debt + Equity − Non-Operating Cash)",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-116",
  "Section": "A",
  "Stem": "At the capital allocation review for Nuvora Industries, the CFO presents operating income (EBIT) of $28.4M, a marginal tax rate of 25%, total interest-bearing debt of $60M, shareholders' equity of $140M, and $30M of cash and equivalents held for a planned but not yet executed acquisition. The board wants to know whether Nuvora's operating assets earn more than the company's 10.5% cost of capital. What return on invested capital (ROIC) should the CFO report?",
  "Topic": "A.116 Return on invested capital — NOPAT and invested capital computation",
  "UniqueConceptKey": "A-116-return-on-invested-capital-nopat-computation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: NOPAT=28.4×0.75=21.3; IC=60+140−30=170; ROIC=12.53% > 10.5% WACC",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
}
];
