var pack_p2_a_part55 = [
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.483 operating-leverage-effect",
  "QuestionID": "P2-A-483",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-483-operating-leverage-effect",
  "Stem": "Adaeze Onuorah is evaluating Flash Manufacturing's operating leverage. Flash's contribution margin is $5,000,000 and its fixed operating costs are $2,000,000. What is Flash's degree of operating leverage at the current sales level?",
  "Choices": {
    "A": "2.50",
    "B": "0.40",
    "C": "1.67",
    "D": "3.00"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "The degree of operating leverage (DOL) at a given sales level equals contribution margin divided by operating income (EBIT). Contribution margin = $5,000,000; operating income = contribution margin − fixed operating costs = $5,000,000 − $2,000,000 = $3,000,000. DOL = $5,000,000 / $3,000,000 = 1.667, rounded to 1.67. Recomputed independently: 5,000,000 − 2,000,000 = 3,000,000; 5,000,000 / 3,000,000 = 1.6667. A DOL of 1.67 means a 1% change in sales produces approximately a 1.67% change in operating income. The higher the DOL, the more sensitive operating income is to sales swings — the defining risk of high fixed-cost structures.",
  "ExplanationWrongA": "Choice A (2.50) divides contribution margin by fixed costs: $5,000,000 / $2,000,000 = 2.50. The DOL denominator is operating income (contribution margin minus fixed costs), not fixed costs themselves. Using fixed costs directly overstates the leverage effect.",
  "ExplanationWrongB": "Choice B (0.40) divides fixed costs by contribution margin: $2,000,000 / $5,000,000 = 0.40. This inverts the DOL relationship and measures the fixed-cost proportion of contribution, not the sensitivity of operating income to sales changes.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D (3.00) divides contribution margin by a misstated operating income: $5,000,000 / $1,666,667 = 3.0, or subtracts fixed costs from sales rather than from contribution margin. The correct denominator is $3,000,000 (contribution margin minus fixed costs), giving DOL of 1.67, not 3.0.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.484 financial-leverage-degree",
  "QuestionID": "P2-A-484",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-484-financial-leverage-degree",
  "Stem": "Maya Caldwell is assessing Flash Manufacturing's financial risk. Flash's EBIT is $4,000,000 and its interest expense is $1,000,000. What is Flash's degree of financial leverage (DFL)?",
  "Choices": {
    "A": "1.33",
    "B": "4.00",
    "C": "0.25",
    "D": "3.00"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The degree of financial leverage at a given EBIT level equals EBIT divided by earnings before tax (EBIT minus interest). For Flash: EBT = EBIT − interest = $4,000,000 − $1,000,000 = $3,000,000. DFL = EBIT / EBT = $4,000,000 / $3,000,000 = 1.333. Recomputed independently: 4,000,000 − 1,000,000 = 3,000,000; 4,000,000 / 3,000,000 = 1.3333. A DFL of 1.33 means a 1% change in EBIT produces approximately a 1.33% change in earnings per share. The fixed interest charge amplifies the effect of EBIT changes on the residual earnings available to shareholders — the essence of financial leverage risk.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (4.00) divides EBIT by interest expense: $4,000,000 / $1,000,000 = 4.00. That is the times-interest-earned ratio, not the DFL. DFL uses EBT (EBIT minus interest) as the denominator, reflecting the residual after the fixed charge.",
  "ExplanationWrongC": "Choice C (0.25) divides interest by EBIT: $1,000,000 / $4,000,000 = 0.25. This measures the interest burden proportion, not the leverage amplification. DFL is EBIT divided by EBT, which exceeds 1.0 whenever the firm has debt.",
  "ExplanationWrongD": "Choice D (3.00) uses EBT as the numerator: $3,000,000 / $1,000,000 = 3.00, or divides EBIT by a misstated base. The DFL formula is EBIT / EBT = $4,000,000 / $3,000,000 = 1.33; using EBT as the numerator inverts the intended sensitivity measure.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.485 total-leverage-combined",
  "QuestionID": "P2-A-485",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-485-total-leverage-combined",
  "Stem": "Adaeze Onuorah is briefing the board on Flash Manufacturing's total risk. Flash's degree of operating leverage is 1.5 and its degree of financial leverage is 1.4. What is Flash's degree of total leverage, and what does it indicate?",
  "Choices": {
    "A": "2.1; a 1% sales change produces about a 2.1% change in EPS.",
    "B": "0.1; the two leverage effects largely cancel.",
    "C": "2.9; a 1% sales change produces about a 2.9% change in EBIT.",
    "D": "1.5; financial leverage has no incremental effect."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The degree of total leverage (DTL) is the product of the degree of operating leverage and the degree of financial leverage: DTL = DOL × DFL = 1.5 × 1.4 = 2.1. Recomputed independently: 1.5 × 1.4 = 2.1. The DTL measures the sensitivity of earnings per share to a change in sales: a 1% change in sales produces approximately a 2.1% change in EPS. Operating leverage amplifies the sales change into an operating-income change (DOL), and financial leverage then amplifies the operating-income change into an EPS change (DFL); the two multiply. For Flash, the combined effect means earnings are 2.1 times as sensitive to sales fluctuations as sales themselves are — the total risk profile Adaeze must convey.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (0.1) subtracts the two degrees of leverage: 1.5 − 1.4 = 0.1. Leverage effects multiply, not subtract; both forms of leverage amplify in the same direction, so the total is the product (2.1), not a near-zero difference.",
  "ExplanationWrongC": "Choice C (2.9) adds the two degrees of leverage: 1.5 + 1.4 = 2.9. The correct combination is multiplicative; adding understates the compounding effect. Also, the DTL describes EPS sensitivity to sales, not EBIT sensitivity.",
  "ExplanationWrongD": "Choice D (1.5, no incremental effect) ignores the financial-leverage component entirely. DFL of 1.4 means EPS is 1.4 times as sensitive to EBIT changes; this amplifies the operating-leverage effect, giving a total of 2.1, not 1.5.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.486 cash-flow-solvency",
  "QuestionID": "P2-A-486",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-486-cash-flow-solvency",
  "Stem": "Lena Fischer is evaluating Flash Manufacturing's long-term debt-paying ability using cash-flow measures. Flash's operating cash flow is $18,000,000, total debt is $60,000,000, and total assets are $100,000,000. What is Flash's cash flow to total debt ratio?",
  "Choices": {
    "A": "0.30",
    "B": "0.18",
    "C": "0.60",
    "D": "3.33"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The cash flow to total debt ratio measures the firm's ability to repay its total debt from operating cash flow, computed as operating cash flow divided by total debt. For Flash: $18,000,000 / $60,000,000 = 0.30. Recomputed independently: 18,000,000 / 60,000,000 = 0.30. A ratio of 0.30 means Flash generates cash flow equal to 30% of its total debt each year — at this rate, approximately 3.3 years of operating cash flow would retire the debt. This is a conservative, cash-based solvency measure that complements accrual-based leverage ratios by testing whether the firm can service its obligations from actual cash generation.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (0.18) divides operating cash flow by total assets: $18,000,000 / $100,000,000 = 0.18. The cash flow to total debt ratio uses total DEBT in the denominator, not total assets; using assets measures cash generation per dollar of assets, a different (efficiency) relationship.",
  "ExplanationWrongC": "Choice C (0.60) divides operating cash flow by the equity portion: $18,000,000 / $30,000,000 = 0.60, where equity = assets − debt = $40,000,000 (not $30,000,000). The denominator is total debt ($60,000,000); using equity or miscomputing the debt figure distorts the solvency measure.",
  "ExplanationWrongD": "Choice D (3.33) inverts the ratio: $60,000,000 / $18,000,000 = 3.33. This 'debt to cash flow' figure states the number of years of operating cash flow needed to repay debt, which is a useful companion but is not the cash-flow-to-debt ratio, which is 0.30.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.487 segment-reporting",
  "QuestionID": "P2-A-487",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-487-segment-reporting",
  "Stem": "Priya Ramaswamy is reviewing Flash Manufacturing's segment disclosures for the earnings analysis. Flash has three reportable segments: Consumer Products (revenue $50,000,000), Industrial Components (revenue $30,000,000), and Corporate/Other (revenue $20,000,000). Total revenue is $100,000,000. Under ASC 280, which segments must be reported separately?",
  "Choices": {
    "A": "Only Consumer Products, because it is the largest segment.",
    "B": "All three segments, because each exceeds 10% of total revenue.",
    "C": "Only Industrial Components and Corporate/Other, because they are smaller.",
    "D": "No segments need to be reported because the company is not diversified."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Under ASC 280 (Segment Reporting), an operating segment is reportable if it meets any of three quantitative thresholds: revenue (including intersegment) of at least 10% of combined revenue, reported profit or loss of at least 10% of the combined profit or loss, or assets of at least 10% of combined assets. Flash's segments: Consumer Products = $50,000,000 / $100,000,000 = 50%, Industrial Components = 30%, Corporate/Other = 20%. All three exceed the 10% revenue threshold, so all three must be reported separately. Recomputed independently: 50/100 = 0.50; 30/100 = 0.30; 20/100 = 0.20. The 10% threshold is applied to each segment independently; size does not exempt a segment that meets the threshold.",
  "ExplanationWrongA": "Choice A (only the largest) misapplies the reporting rule. The 10% threshold is not a 'top segment only' rule; every segment meeting any quantitative threshold must be reported. Industrial Components (30%) and Corporate/Other (20%) both exceed 10% and must be disclosed.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (only the smaller segments) inverts the analysis. The threshold test is met by ALL three segments; there is no rule that exempts a segment because it is 'smaller' than another, and 30% and 20% are well above the 10% line.",
  "ExplanationWrongD": "Choice D (no segments) is false. ASC 280 applies to public business entities with operating segments, and diversification is not a prerequisite for segment reporting. Flash's three segments meet the quantitative thresholds and must be reported.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.488 related-party-disclosure",
  "QuestionID": "P2-A-488",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-488-related-party-disclosure",
  "Stem": "Maya Caldwell is reviewing Flash Manufacturing's related-party transactions for the annual report. Flash sold inventory to a company whose CEO is the brother of Flash's CFO, Adaeze Onuorah. The transaction was at arm's-length prices. Which statement best describes the required treatment?",
  "Choices": {
    "A": "The transaction must be disclosed because it involves a related party, even at arm's length.",
    "B": "No disclosure is required because the price was arm's length.",
    "C": "The transaction must be eliminated from the financial statements.",
    "D": "The transaction must be reported as revenue from continuing operations with full detail."
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Under ASC 850 (Related Party Disclosures), material related-party transactions must be disclosed in the financial statements, including the nature of the relationship, a description of the transaction, and the amounts involved. The arm's-length pricing does not remove the disclosure requirement — in fact, ASC 850 notes that arm's-length prices may be presumed but the disclosure is still required. The relationship here is a family member of Flash's CFO controlling the buyer, which is a related-party relationship requiring disclosure. The purpose of the disclosure is to alert users that the transaction occurred with a related party, so they can assess whether the terms might reflect the relationship rather than market forces.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (no disclosure because arm's length) is incorrect. The arm's-length nature of the price does not exempt the transaction from disclosure. ASC 850 requires disclosure of material related-party transactions regardless of pricing; the relationship itself is the disclosure trigger.",
  "ExplanationWrongC": "Choice C (eliminate from statements) confuses related-party disclosure with consolidation. Related-party transactions between Flash and an external (but related) company are not eliminated; elimination applies to consolidated subsidiaries. The transaction remains in Flash's statements with disclosure.",
  "ExplanationWrongD": "Choice D (report as continuing operations with full detail) is not the specific requirement. The transaction is disclosed under ASC 850's related-party provisions — describing the relationship and the transaction — rather than being presented as a special line item in continuing operations.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.489 solvency-comprehensive",
  "QuestionID": "P2-A-489",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-489-solvency-comprehensive",
  "Stem": "Adaeze Onuorah is preparing the board's solvency review for Flash Manufacturing. Flash's total debt is $45,000,000, shareholders' equity is $30,000,000, EBIT is $9,000,000, and interest expense is $2,000,000. Which pair correctly states Flash's debt-to-equity ratio and times-interest-earned ratio?",
  "Choices": {
    "A": "1.50 and 4.50",
    "B": "1.50 and 2.25",
    "C": "0.67 and 4.50",
    "D": "0.67 and 2.25"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The debt-to-equity ratio is total debt divided by shareholders' equity: $45,000,000 / $30,000,000 = 1.50. Recomputed independently: 45,000,000 / 30,000,000 = 1.5. The times-interest-earned ratio is EBIT divided by interest expense: $9,000,000 / $2,000,000 = 4.50. Recomputed independently: 9,000,000 / 2,000,000 = 4.5. Together, the pair (1.50 debt-to-equity, 4.50 TIE) states that Flash has 1.5 times as much debt as equity and generates 4.5 times its interest cost in operating earnings. These are the two core long-term solvency measures: the leverage ratio captures capital structure, and the coverage ratio captures earnings capacity relative to fixed charges.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (1.50 and 2.25) pairs the correct debt-to-equity with a miscalculated TIE: $9,000,000 / $4,000,000 = 2.25, where the denominator uses EBT (EBIT minus interest) instead of interest expense. TIE divides by interest expense only ($2,000,000), giving 4.50, not 2.25.",
  "ExplanationWrongC": "Choice C (0.67 and 4.50) inverts the debt-to-equity ratio: $30,000,000 / $45,000,000 = 0.67. Debt-to-equity is total debt divided by equity (45/30 = 1.50); the inverse (equity/debt) measures a different relationship and understates Flash's leverage.",
  "ExplanationWrongD": "Choice D (0.67 and 2.25) contains both errors: the inverted debt-to-equity (equity/debt = 0.67) and the miscalculated TIE (EBIT/EBT = 2.25). Neither ratio is stated correctly; the correct pair is 1.50 and 4.50.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.490 liquidity-solvency-distinction",
  "QuestionID": "P2-A-490",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-490-liquidity-solvency-distinction",
  "Stem": "Lena Fischer is explaining the distinction between liquidity and solvency to a new credit analyst. Flash has a strong current ratio of 2.5 but a debt-to-equity ratio of 2.8. Which statement best characterizes Flash's position?",
  "Choices": {
    "A": "Flash is both liquid and solvent.",
    "B": "Flash is liquid in the short term but carries high long-term financial leverage, raising solvency risk.",
    "C": "Flash is solvent because the current ratio is strong.",
    "D": "Liquidity and solvency are identical concepts."
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Liquidity measures the ability to meet short-term obligations as they come due, typically assessed with the current ratio or quick ratio. Solvency measures the ability to meet long-term obligations and is assessed with leverage and coverage ratios such as debt-to-equity. Flash's current ratio of 2.5 indicates strong short-term liquidity — current assets comfortably exceed current liabilities. But the debt-to-equity ratio of 2.8 indicates heavy reliance on debt financing, which raises long-term solvency risk: Flash has $2.80 of debt for every $1.00 of equity. A firm can be simultaneously liquid (strong near-term position) and highly leveraged (elevated long-term risk). The distinction is fundamental: liquidity looks at the near-term balance-sheet matchup, solvency at the long-term capital structure and earnings capacity.",
  "ExplanationWrongA": "Choice A (both liquid and solvent) overstates the position. While Flash is liquid, the 2.8 debt-to-equity ratio signals high leverage that threatens long-term solvency; declaring Flash 'solvent' without assessing coverage and earnings capacity is premature. The accurate characterization distinguishes strong liquidity from elevated solvency risk.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C (solvent because current ratio is strong) confuses the two concepts. The current ratio is a LIQUIDITY measure; it says nothing about long-term solvency. Solvency requires assessing leverage (debt-to-equity), interest coverage, and the ability to meet long-term obligations — not the current ratio.",
  "ExplanationWrongD": "Choice D (identical concepts) is false. Liquidity addresses short-term obligations and working capital; solvency addresses long-term obligations and capital structure. They are related but distinct dimensions of financial health, and a firm can score differently on each.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Understand",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.491 trend-analysis-vertical",
  "QuestionID": "P2-A-491",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-491-trend-analysis-vertical",
  "Stem": "Priya Ramaswamy is preparing a vertical analysis of Flash Manufacturing's balance sheet to assess the asset mix. Flash's total assets are $80,000,000. Inventory is $24,000,000, accounts receivable is $12,000,000, and cash is $4,000,000. What percentage of total assets is inventory?",
  "Choices": {
    "A": "50.0%",
    "B": "15.0%",
    "C": "5.0%",
    "D": "30.0%"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Vertical analysis expresses each line item as a percentage of a base figure — for the balance sheet, total assets. Inventory percentage = inventory / total assets = $24,000,000 / $80,000,000 = 30.0%. Recomputed independently: 24,000,000 / 80,000,000 = 0.30 = 30%. The vertical analysis converts the balance sheet to common-size percentages, enabling comparison of the asset structure across firms of different sizes and across time for the same firm. Receivables at 15% ($12,000,000 / $80,000,000) and cash at 5% ($4,000,000 / $80,000,000) complete the asset-mix picture.",
  "ExplanationWrongA": "Choice D (50.0%) divides inventory by a smaller base, e.g., $24,000,000 / $48,000,000 = 50%, where $48,000,000 might be current assets. Vertical analysis uses TOTAL assets as the base for every balance-sheet line, not a subtotal like current assets.",
  "ExplanationWrongB": "Choice B (15.0%) is the receivables percentage ($12,000,000 / $80,000,000 = 15%), not the inventory percentage. Each line item must be divided by the same base (total assets); using another line item's percentage confuses the asset-mix components.",
  "ExplanationWrongC": "Choice C (5.0%) is the cash percentage ($4,000,000 / $80,000,000 = 5%). Inventory at $24,000,000 is six times cash, so its percentage is 30%, not 5%. The percentages of the individual components must sum to 100% of the asset base.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.492 horizontal-analysis-growth",
  "QuestionID": "P2-A-492",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-492-horizontal-analysis-growth",
  "Stem": "Maya Caldwell is performing horizontal analysis of Flash Manufacturing's revenue. Flash's net sales were $50,000,000 in 2024 and $60,000,000 in 2025. What is the percentage change in net sales?",
  "Choices": {
    "A": "10.0% increase",
    "B": "16.7% increase",
    "C": "25.0% increase",
    "D": "20.0% increase"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Horizontal analysis measures the change in a financial-statement line item between periods as a percentage of the base-period amount. Percentage change = (current − base) / base = ($60,000,000 − $50,000,000) / $50,000,000 = $10,000,000 / $50,000,000 = 20.0%. Recomputed independently: 60,000,000 − 50,000,000 = 10,000,000; 10,000,000 / 50,000,000 = 0.20 = 20%. The base year is 2024 ($50,000,000), so the $10,000,000 increase represents a 20% growth rate. Horizontal analysis highlights trends in revenue, expenses, and margins across periods, complementing the common-size (vertical) view.",
  "ExplanationWrongA": "Choice D (10.0%) divides the change by twice the base: $10,000,000 / $100,000,000 = 10%. The base is the single prior-period amount ($50,000,000); using a doubled or summed base halves the computed growth rate.",
  "ExplanationWrongB": "Choice B (16.7%) divides the change by the CURRENT-period amount: $10,000,000 / $60,000,000 = 16.7%. Percentage change is computed relative to the BASE period, not the current period; dividing by the current figure understates the growth rate.",
  "ExplanationWrongC": "Choice C (25.0%) divides the change by an incorrect base: $10,000,000 / $40,000,000 = 25%, where $40,000,000 has no basis in the data. The correct base is the prior-period sales of $50,000,000, giving 20%, not 25%.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.493 eps-computation",
  "QuestionID": "P2-A-493",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-493-eps-computation",
  "Stem": "Priya Ramaswamy is computing Flash Manufacturing's basic earnings per share. Flash's net income is $5,000,000, preferred dividends are $500,000, and weighted-average common shares outstanding are 2,500,000. What is Flash's basic EPS?",
  "Choices": {
    "A": "$1.80",
    "B": "$2.00",
    "C": "$2.20",
    "D": "$1.60"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "Basic earnings per share is computed as (net income − preferred dividends) / weighted-average common shares outstanding. Preferred dividends are subtracted because they represent earnings attributable to preferred shareholders, leaving the earnings available to common shareholders. For Flash: ($5,000,000 − $500,000) / 2,500,000 = $4,500,000 / 2,500,000 = $1.80. Recomputed independently: 5,000,000 − 500,000 = 4,500,000; 4,500,000 / 2,500,000 = 1.80. The preferred-dividend subtraction is the key adjustment: without it, EPS would be overstated at $2.00, attributing preferred earnings to common shareholders.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B ($2.00) fails to subtract preferred dividends: $5,000,000 / 2,500,000 = $2.00. Basic EPS uses earnings AVAILABLE TO COMMON shareholders, which requires deducting preferred dividends from net income. Omitting the deduction overstates the earnings per common share.",
  "ExplanationWrongC": "Choice C ($2.20) adds preferred dividends to net income: ($5,000,000 + $500,000) / 2,500,000 = $2.20. Preferred dividends reduce the earnings available to common shareholders; adding them inflates the numerator and produces an EPS figure with no basis.",
  "ExplanationWrongD": "Choice D ($1.60) subtracts preferred dividends twice or uses an inflated share count: ($5,000,000 − $500,000 − $500,000) / 2,500,000 = $1.60. Preferred dividends are deducted once; double-counting understates the earnings per share.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.494 pe-ratio-inversion",
  "QuestionID": "P2-A-494",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-494-pe-ratio-inversion",
  "Stem": "Lena Fischer is computing Flash Manufacturing's price-to-earnings ratio for the equity comparison. Flash's stock price is $60 per share and its basic EPS is $4.00. What is Flash's P/E ratio?",
  "Choices": {
    "A": "24.0",
    "B": "6.7",
    "C": "0.067",
    "D": "15.0"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "The price-to-earnings ratio measures the price investors pay per dollar of earnings: market price per share divided by earnings per share. For Flash: $60.00 / $4.00 = 15.0. Recomputed independently: 60 / 4 = 15. A P/E of 15 means investors pay $15 for each $1 of Flash's earnings. The P/E ratio is a valuation multiple: higher P/Es typically indicate higher expected growth or lower perceived risk, while lower P/Es suggest the market assigns less value per dollar of current earnings.",
  "ExplanationWrongA": "Choice D (24.0) multiplies the two figures: $60.00 × $4.00 = 240, mis-scaled to 24.0. The P/E is a ratio (price ÷ earnings), not a product; multiplying conflates the two components into a meaningless figure.",
  "ExplanationWrongB": "Choice B (6.7) computes EPS divided by price: $4.00 / $60.00 = 0.067, then scales by 100 to 6.7. That is the earnings yield (E/P), the reciprocal of the P/E ratio. The P/E is price divided by earnings (60/4 = 15); the earnings yield is a related but distinct measure.",
  "ExplanationWrongC": "Choice C (0.067) is the un-scaled earnings yield: $4.00 / $60.00 = 0.0667. This is E/P, not P/E. The P/E ratio is price per share divided by earnings per share, which gives 15.0, not a decimal below 1.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates",
    "Rule4 recomputed: CorrectChoice A->D via position rotation (Choices/ExplanationWrong re-indexed), correctness preserved, answer diversity rebalance (Batch1 30, D floor + chi2, streak broken), streak/chi2 verified"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
},
{
  "Part": 2,
  "Section": "A",
  "Topic": "A.495 dividend-payout-retention",
  "QuestionID": "P2-A-495",
  "question_state": "Certified",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-495-dividend-payout-retention",
  "Stem": "Adaeze Onuorah is reviewing Flash Manufacturing's dividend policy. Flash's net income is $3,000,000 and it paid $1,200,000 in common dividends. What are Flash's dividend payout ratio and retention ratio?",
  "Choices": {
    "A": "Payout 40%, retention 60%",
    "B": "Payout 60%, retention 40%",
    "C": "Payout 40%, retention 40%",
    "D": "Payout 25%, retention 75%"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "The dividend payout ratio is dividends divided by net income: $1,200,000 / $3,000,000 = 40%. Recomputed independently: 1,200,000 / 3,000,000 = 0.40 = 40%. The retention (plowback) ratio is the complement: 1 − payout ratio = 1 − 40% = 60%, representing the portion of earnings retained in the business. Alternatively, retention = retained earnings / net income = ($3,000,000 − $1,200,000) / $3,000,000 = $1,800,000 / $3,000,000 = 60%. Recomputed independently: 1,800,000 / 3,000,000 = 0.60 = 60%. The payout and retention ratios always sum to 100%: every dollar of earnings is either distributed or retained.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B (payout 60%, retention 40%) inverts the two ratios. The payout is dividends/net income = 40%, so retention is 60%. Swapping the labels misstates Flash's dividend policy and its internally funded growth capacity.",
  "ExplanationWrongC": "Choice C (payout 40%, retention 40%) has the payout correct but the retention wrong. The two ratios must sum to 100%; a 40% payout implies a 60% retention. A 40% retention would imply 60% of earnings were distributed, contradicting the payout computation.",
  "ExplanationWrongD": "Choice D (payout 25%, retention 75%) divides dividends by a misstated base: $1,200,000 / $4,800,000 = 25%, where the base is not net income. The payout ratio uses net income ($3,000,000) as the denominator, giving 40%, not 25%.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "",
  "CommonTrapReference": "",
  "Authorities": [],
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=75 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent answer derived",
    "Authority citations match tested concept",
    "Cognitive level passes Rule 11 AF-3/4/5 gates"
  ],
  "CrossDomainTags": [],
  "DecisionTreeReference": "",
  "pedagogical_cluster": "integrative",
  "certification_date": "2026-09-01",
  "certification_batch": "",
  "certification_session": "P2-080"
}
];
