var pack_p2_a_part30 = [
{
  "Authorities": [
    "DuPont analysis framework",
    "Average-balance ratio convention"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "10.00%",
    "B": "16.07%",
    "C": "20.45%",
    "D": "18.00%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using period-end or beginning equity instead of average",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Return on equity divides net income by average shareholders' equity, pairing a flow measure with the capital base that generated it across the period. Average equity = (2,200,000 + 2,800,000) / 2 = $2,500,000. ROE = 450,000 / 2,500,000 = 18.00%. For context, average assets = (4,000,000 + 5,000,000) / 2 = $4,500,000, so ROA = 10.00%, and the spread between the two returns reflects leverage amplification. Business interpretation: division controller Owen Gallagher reports 18.00% so benchmarking services and lenders compare Flash consistently - period-end denominators distort growing companies by crediting the full year's income against capital raised late in the year. The traps are substituting the ROA figure, year-end equity (16.07%), or opening equity (20.45%) for the average-balance convention the question specifies.",
  "ExplanationWrongA": "Choice A answers the adjacent question, return on assets: 450,000 / 4,500,000 average assets = 10.00%. The misconception grabs the neighboring ratio from the review package instead of the equity-based measure requested.",
  "ExplanationWrongB": "Choice B divides by year-end equity (450,000 / 2,800,000 = 16.07%); the misconception penalizes intra-year capital formation by weighting only the December balance, understating the return earned on capital actually employed during the year.",
  "ExplanationWrongC": "Choice C divides by opening equity (450,000 / 2,200,000 = 20.45%); the misconception flatters results by ignoring the $600,000 of equity added during the year, crediting income to a capital base that was only partially in place.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-13",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-265",
  "Section": "A",
  "Stem": "Division controller Owen Gallagher prepares Flash's annual review package for the lender meeting. Net income for the year was $450,000. Total assets were $4,000,000 at the start of the year and $5,000,000 at year end; shareholders' equity was $2,200,000 at the start and $2,800,000 at year end, and no dividends were declared. What return on equity should Owen report under the standard average-balance convention?",
  "Topic": "A.265 roe-average-equity",
  "UniqueConceptKey": "A-265-average-balance-denominator",
  "VerifiedChecks": [
    "Verification: avg equity (2,200,000 + 2,800,000)/2 = 2,500,000; ROE 450,000/2,500,000 = 18.00%; avg assets (4,000,000 + 5,000,000)/2 = 4,500,000; ROA 450,000/4,500,000 = 10.00%",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW slots >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Difficulty justified: ME/Apply denominator-convention discrimination"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (liquidity measurement hierarchy; cash ratio as most conservative solvency screen)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The cash ratio counts only cash and marketable securities against current liabilities, isolating what Flash could deploy within days, while the current ratio still counts inventory that may take months to convert.",
    "B": "The cash ratio divides current liabilities by cash balances, so a falling value means Flash retired obligations faster than operating cash rebuilt the buffer.",
    "C": "GAAP prohibits including customer receivables in liquidity measures until collected in cash, so the cash ratio strips them while the current ratio improperly keeps them.",
    "D": "Loan covenants permit only the cash ratio, so the 1.85 current ratio is a disclosure artifact carrying no contractual significance for Flash's facility."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Treating the current ratio as equally protective of near-term default risk",
  "CorrectChoice": "A",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "The liquidity hierarchy runs from the cash ratio (only cash and marketable securities) through the quick ratio to the current ratio (all current assets). Flash's cash ratio of 0.18 means cash and equivalents cover just 18 cents of each dollar of current obligations, while the 1.85 current ratio depends on converting inventory that may sit for months. For covenant monitoring, the most conservative measure best approximates what Flash could mobilize within days if trade terms tightened. Business interpretation: Ingrid Solberg should treat the wide spread between 0.18 and 1.85 as a warning that headline liquidity overstates immediately deployable resources. Common trap: assuming a healthy current ratio guarantees payment capacity under stress.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B inverts the construction: the cash ratio places cash and marketable securities in the numerator over current liabilities, not liabilities over cash, so a falling reading signals shrinking liquid coverage of obligations rather than faster debt repayment.",
  "ExplanationWrongC": "Choice C invents a GAAP prohibition; receivables are entirely permissible inside the current ratio and the quick ratio. They are excluded from the cash ratio only because collection timing is uncertain, not because accounting rules forbid counting them.",
  "ExplanationWrongD": "Choice D asserts contractual exclusivity that standard loan agreements do not contain; covenants routinely test current ratio, quick ratio, or leverage measures. The cash ratio matters here because of its conservatism, not because the current ratio lacks standing.",
  "FormulaReference": "FA-03 Cash Ratio",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-266",
  "Section": "A",
  "Stem": "Flash's syndicate requires a quarterly compliance certificate, and credit manager Ingrid Solberg must decide which liquidity measure best protects the bank's near-term position. Flash reports a cash ratio of 0.18 against a current ratio of 1.85. Why does Ingrid weight the cash ratio more heavily when assessing Flash's immediate default exposure?",
  "Topic": "A.266 cash-ratio-default-proximity",
  "UniqueConceptKey": "A-266-cash-ratio-default-proximity",
  "VerifiedChecks": [
    "Definition check: cash ratio = (cash + marketable securities) / current liabilities; matches FA-03",
    "Logic pass: conservatism hierarchy verified against FA-01/FA-02/FA-03 definitions",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (receivables activity metrics; DSO computed on credit sales over average balances)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "29.2 days",
    "B": "25.4 days",
    "C": "21.8 days",
    "D": "25.1 days"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using total sales or ending receivables instead of credit sales and average balances",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Days Sales Outstanding links receivables to the credit sales that created them. Average receivables = ($520,000 + $700,000) / 2 = $610,000. Daily credit sales = $8,760,000 / 365 = $24,000. DSO = $610,000 / $24,000 = 25.4 days. Under the matching principle the denominator must be credit sales only, and the numerator should reflect the average balance carried during the period rather than a single snapshot. Business interpretation: Devon Marsh can report that Flash collects in roughly 25 days against the terms it grants, keeping receivables funding needs predictable for the treasury plan. Common trap: mixing cash sales into the denominator or snapshotting the year-end balance, both of which distort the collection clock.",
  "ExplanationWrongA": "Choice A anchors on the $700,000 ending balance alone, overstating DSO at 29.2 days; the snapshot ignores balances built and collected earlier in the quarter, which the two-point average of $610,000 correctly absorbs into the metric.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C divides by total sales of $10,200,000 including $1,440,000 of cash sales; those sales never create receivables, so the inflated denominator understates DSO at 21.8 days. Only credit sales drive the receivables balance the metric measures.",
  "ExplanationWrongD": "Choice D applies a 360-day convention to a fact pattern stated on a 365-day basis, trimming DSO to 25.1 days; switching the day-count without instruction changes the metric's scale rather than Flash's actual collection behavior.",
  "FormulaReference": "FA-05 Days Sales Outstanding",
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-267",
  "Section": "A",
  "Stem": "Closing the second quarter, controller Devon Marsh drafts receivables commentary for Flash. Flash posted credit sales of $8,760,000 (total sales $10,200,000, including $1,440,000 of cash sales). Receivables were $520,000 at the start of the quarter and $700,000 at the end. On a 365-day basis, what Days Sales Outstanding should Devon report?",
  "Topic": "A.267 dso-average-credit-sales",
  "UniqueConceptKey": "A-267-credit-sales-denominator",
  "VerifiedChecks": [
    "Recomputed: 610000/8760000 x 365 = 25.4 days",
    "Second pass: daily credit sales 8760000/365 = 24000; 610000/24000 = 25.4 (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "US GAAP EPS presentation (ASC 260 basic EPS weighted-average share computation)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$3.25",
    "B": "$3.90",
    "C": "$3.39",
    "D": "$3.44"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Weighting shares at year-end count or ignoring the mid-year issuance date",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Basic EPS divides income available to common shareholders by the weighted-average shares outstanding during the period. The April 1 issuance of 120,000 shares was outstanding nine months: weighted shares = (600,000 x 3/12) + (720,000 x 9/12) = 150,000 + 540,000 = 690,000. EPS = $2,340,000 / 690,000 = $3.39. Time-weighting under ASC 260 matches earnings to the capital actually employed to generate them. Business interpretation: Sofia Grimaldi should carry $3.39 as the trailing base for multiples while recognizing the enlarged 720,000-share count going forward. Common trap: dividing by the year-end share count, which quietly credits the full year with capital raised only in April.",
  "ExplanationWrongA": "Choice A divides by the 720,000 year-end share count for $3.25; it treats shares issued April 1 as outstanding from January 1, diluting EPS below the time-weighted figure ASC 260 requires for the period.",
  "ExplanationWrongB": "Choice B divides by the original 600,000 shares for $3.90, ignoring the offering entirely and crediting the year's earnings to capital Flash did not actually possess during three quarters of the year.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D weights the two share blocks at four and eight months (200,000 + 480,000 = 680,000), effectively dating the offering to May 1; the correct split from the April 1 closing is three and nine months, giving 690,000 weighted shares and $3.39.",
  "FormulaReference": "FA-15 Earnings per Share",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-268",
  "Section": "A",
  "Stem": "Equity research associate Sofia Grimaldi updates her Flash model after the April 1 closing of an equity offering that added 120,000 shares to the 600,000 shares outstanding since January 1. Income available to common shareholders totaled $2,340,000 for the year. What basic EPS should Sofia carry for Flash?",
  "Topic": "A.268 eps-weighted-shares",
  "UniqueConceptKey": "A-268-april-offering-weighting",
  "VerifiedChecks": [
    "Recomputed: 2340000/((600000 x 3 + 720000 x 9)/12) = 2340000/690000 = 3.39",
    "Second pass: 150000 + 540000 = 690000; 2340000/690000 = 3.391 rounds to 3.39 (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (liquidity ratio decomposition; quick versus current asset mix diagnostics)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Flash shifted the entire movement inside current assets: quick assets fell $1,050,000 while inventory rose the offsetting $1,050,000 against unchanged current liabilities, indicating an inventory build rather than any financing change.",
    "B": "Flash reduced its reliance on short-term financing, and the quick-ratio decline merely reflects scheduled repayment of current liabilities during the year.",
    "C": "Because the current ratio held at 2.10 in both years, Flash's working-capital risk is essentially unchanged and the quick-ratio movement is noise.",
    "D": "The quick-ratio slide evidences deteriorating receivables collections, since receivables dominate the quick-asset base in both years."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Reading a stable current ratio as proof working-capital quality is unchanged",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Decomposing the two ratios separates asset-mix effects from financing effects. Current liabilities held at $3,000,000 and total current assets at $6,300,000, so the 2.10 current ratio is unchanged by construction. Inside current assets, quick assets fell from $4,200,000 (quick ratio 1.40) to $3,150,000 (quick ratio 1.05), a $1,050,000 drop exactly mirrored by inventory rising from $2,100,000 to $3,150,000. The pattern therefore identifies an inventory build absorbed within an unchanged working-capital envelope. Business interpretation: Marcus Oyelaran should probe purchasing commitments and demand signals behind the 50 percent inventory increase rather than flag liquidity generically. Common trap: citing the stable current ratio as proof that working-capital risk is unchanged.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B asserts a liability reduction; the data show current liabilities flat at $3,000,000 in both years, so the quick-ratio slide originates wholly inside the current-asset mix, not in the financing side of the ratio.",
  "ExplanationWrongC": "Choice C treats the unchanged 2.10 current ratio as reassurance; that ratio aggregates inventory with cash-like assets and is structurally blind to the substitution that pushed quick assets down $1,050,000 beneath the same total.",
  "ExplanationWrongD": "Choice D pins the cause on receivables collections, yet the aggregate quick-asset decline cannot be attributed to receivables alone; cash and receivables together comprise the movement from $4,200,000 to $3,150,000 and no split between them is provided.",
  "FormulaReference": "FA-02 Quick Ratio",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-269",
  "Section": "A",
  "Stem": "Reviewing year-end working papers, internal auditor Marcus Oyelaran finds Flash's current ratio steady at 2.10 in both years on current assets of $6,300,000 and current liabilities of $3,000,000, yet quick assets fell from $4,200,000 (quick ratio 1.40) to $3,150,000 (quick ratio 1.05) as inventory rose from $2,100,000 to $3,150,000. Which conclusion is best supported?",
  "Topic": "A.269 quick-current-divergence",
  "UniqueConceptKey": "A-269-inventory-build-diagnosis",
  "VerifiedChecks": [
    "Delta check: quick assets 4200000 - 3150000 = -1050000 mirrors inventory 3150000 - 2100000 = +1050000",
    "Ratio check: 4200000/3000000 = 1.40 and 3150000/3000000 = 1.05 reproduce stated quick ratios; 6300000/3000000 = 2.10",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (quick ratio mechanics; covenant compliance and working-capital levers)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Pay down $800,000 of accounts payable immediately using cash on hand, reducing both current liabilities and cash balances.",
    "B": "Draw $1,200,000 on the 364-day revolving credit facility and hold the proceeds in cash until the certificate date.",
    "C": "Offer 2/10 net 30 discounts on selected invoices to accelerate $600,000 of collections from customers.",
    "D": "Convert $900,000 of slow-moving inventory into $900,000 of cash through the clearance channel at carrying value."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Assuming any cash increase lifts a sub-1.0 quick ratio regardless of offsets",
  "CorrectChoice": "D",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "With quick assets of $5,600,000 against $6,000,000 of current liabilities (quick ratio 0.93), the binding constraint is convertible quick coverage, so the chosen action must raise the numerator without enlarging current liabilities. Selling $900,000 of slow-moving inventory at carrying value converts a non-quick asset into cash: quick assets become $6,500,000 and the quick ratio = $6,500,000 / $6,000,000 = 1.08, clearing the 1.00 floor with no new debt, no interest, and no discount leakage. Business interpretation: Omar Haddad should certify compliance on the clearance-sale route because it repairs the covenant durably rather than dressing the ratio for one quarter. Common trap: assuming any increase in cash lifts a sub-1.0 quick ratio; entries that add an equal current liability pull the ratio toward, not past, 1.00.",
  "ExplanationWrongA": "Choice A pays down $800,000 of payables with cash, moving the quick ratio to $4,800,000 / $5,200,000 = 0.92; when the ratio sits below 1.00, stripping equal amounts from numerator and denominator drives it further down rather than up.",
  "ExplanationWrongB": "Choice B draws $1,200,000 on the revolver, lifting the quick ratio only to $6,800,000 / $7,200,000 = 0.94 because the proceeds create an identical current liability; the covenant still fails while committed borrowing costs begin accruing.",
  "ExplanationWrongC": "Choice C accelerates collections through discounts, swapping receivables for cash; both are quick assets, so the quick ratio stays pinned at $5,600,000 / $6,000,000 = 0.93 while the discount forfeits selling margin for zero covenant benefit.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-02 Quick Ratio",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-270",
  "Section": "A",
  "Stem": "Flash's amended credit agreement certifies a quick ratio of at least 1.00 within thirty days. Treasurer Omar Haddad faces current assets of $9,600,000 (cash $2,400,000, receivables $3,200,000, inventory $4,000,000) against $6,000,000 of current liabilities, a quick ratio of 0.93. Which single action should Omar take for the compliance certificate?",
  "Topic": "A.270 covenant-quick-ratio-action",
  "UniqueConceptKey": "A-270-clearance-sale-fix",
  "VerifiedChecks": [
    "Recomputed: base quick ratio 5600000/6000000 = 0.93",
    "Action A: (5600000 - 800000)/(6000000 - 800000) = 4800000/5200000 = 0.92 (worsens)",
    "Action B: (5600000 + 1200000)/(6000000 + 1200000) = 6800000/7200000 = 0.94 (still fails)",
    "Action C: AR-to-cash swap leaves 5600000/6000000 = 0.93 unchanged",
    "Action D: 6500000/6000000 = 1.08 clears the 1.00 floor",
    "Second pass confirms all four quotients independently",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "US GAAP inventory cost flows (ASC 330 LIFO; LIFO reserve disclosure and FIFO-equivalent conversion)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Accept Keystone's reported $3,900,000 gross profit as-is, since both issuers report under US GAAP and costing differences wash out over successive periods.",
    "B": "Restate Keystone's gross profit upward by the $150,000 increase in the LIFO reserve to a FIFO-equivalent $4,050,000, because only the current-period change in the reserve flows through that year's COGS.",
    "C": "Restate Keystone's gross profit upward by the full $450,000 ending LIFO reserve to $4,350,000, since the entire reserve represents cumulative benefits of FIFO costing.",
    "D": "Restate Keystone's gross profit downward by $450,000 to $3,450,000, penalizing the tax-driven understatement of inventory carrying value that LIFO produces."
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Adding the entire cumulative LIFO reserve to one year's gross profit",
  "CorrectChoice": "B",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Cross-company margin comparability requires aligning inventory cost-flow assumptions. Under rising prices, Keystone's LIFO COGS embeds current costs; converting to a FIFO-equivalent basis removes only the year-over-year change in the reserve: FIFO COGS = $8,200,000 - ($450,000 - $300,000) = $8,050,000. Normalized gross profit = $12,100,000 - $8,050,000 = $4,050,000, i.e., reported $3,900,000 plus the $150,000 current-year LIFO effect. The cumulative $450,000 reserve spans many prior periods and never enters one year's earnings. Business interpretation: Priya Raghavan should present the $4,050,000 figure beside Flash's FIFO margins so the fairness opinion compares like methodologies rather than penalizing or crediting an accounting election. Common trap: dumping the entire cumulative reserve into a single year's profit.",
  "ExplanationWrongA": "Choice A accepts the reported margin because both issuers follow US GAAP; GAAP permits either cost flow, but permitting both is exactly why unadjusted gross profits diverge structurally when prices trend, so as-reported figures embed a costing artifact Flash does not carry.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C adds the full $450,000 ending reserve, inflating normalized gross profit to $4,350,000; the reserve accumulated across many years of price increases, so only its $150,000 current-period increase belongs in this year's COGS bridge.",
  "ExplanationWrongD": "Choice D subtracts $450,000 to reach $3,450,000, erring in both direction and magnitude; moving LIFO toward FIFO under rising prices raises gross profit because FIFO carries older, cheaper cost layers into COGS than LIFO charges.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-271",
  "Section": "A",
  "Stem": "In diligence on acquisition target Keystone Components, M&A director Priya Raghavan must normalize margins against Flash's FIFO reporting. Keystone (LIFO) reports sales of $12,100,000, COGS of $8,200,000, and gross profit of $3,900,000, with a LIFO reserve of $300,000 at the start of the year and $450,000 at the end in a rising-price environment. Which normalization should Priya adopt for the comparability schedule?",
  "Topic": "A.271 lifo-reserve-normalization",
  "UniqueConceptKey": "A-271-fifo-equivalent-bridge",
  "VerifiedChecks": [
    "Recomputed: reserve change 450000 - 300000 = 150000",
    "FIFO COGS: 8200000 - 150000 = 8050000",
    "Normalized GP: 12100000 - 8050000 = 4050000",
    "Second pass: 3900000 + 150000 = 4050000 (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Management accounting practice (vertical common-size analysis; contemporaneous revenue base convention)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "22.80%, an increase of 3.30 percentage points versus the prior-year column.",
    "B": "16.92%, a decrease demonstrating that scale economies compressed the expense base.",
    "C": "19.00%, a decrease of 0.50 percentage points from the prior-year 19.50%.",
    "D": "19.50%, unchanged from the prior year on a comparable basis."
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Quoting a horizontal growth rate as a vertical common-size percentage",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Common-size analysis restates each income-statement line as a percentage of the same period's revenue, isolating intensity from scale. Current-year SG&A intensity = $4,560,000 / $24,000,000 = 19.00%, versus prior-year $3,900,000 / $20,000,000 = 19.50%, a decrease of 0.50 percentage points. The vertical base must be contemporaneous revenue for each year; comparing this year's dollars against last year's revenue answers a different question entirely. Business interpretation: Dana Whitfield can show the board that SG&A grew 16.92% while revenue grew 20.00%, delivering positive operating leverage worth half a point of margin. Common trap: quoting the 16.92% growth rate, a horizontal measure, as though it were the common-size percentage.",
  "ExplanationWrongA": "Choice A divides current SG&A of $4,560,000 by prior-year revenue of $20,000,000 to manufacture 22.80%; mixing periods breaks the vertical base and fabricates an intensity increase that never occurred in either column.",
  "ExplanationWrongB": "Choice B reports 16.92%, which is the year-over-year growth rate in SG&A dollars ($4,560,000 / $3,900,000 - 1), not a share of revenue; horizontal trend rates describe expansion speed, not expense intensity.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D carries forward the prior-year 19.50% unchanged, failing to recompute on current revenue and masking exactly the favorable 0.50-point improvement the common-size schedule exists to reveal to the board.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-272",
  "Section": "A",
  "Stem": "Preparing the board package, controller Dana Whitfield builds a common-size income statement for Flash. Current-year revenue is $24,000,000 with SG&A of $4,560,000; prior-year revenue was $20,000,000 with SG&A of $3,900,000. What SG&A percentage should the current-year column show, and what movement does it reveal?",
  "Topic": "A.272 commonsize-sga-intensity",
  "UniqueConceptKey": "A-272-vertical-base-discipline",
  "VerifiedChecks": [
    "Recomputed: 4560000/24000000 = 0.1900 = 19.00%",
    "Prior year: 3900000/20000000 = 0.1950; movement = -0.50 pp",
    "Growth cross-check: 4560000/3900000 - 1 = 0.1692 = 16.92%; 4560000/20000000 = 22.80%",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (financial leverage and trading on the equity; Higgins framework)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Issuing additional common shares so ownership of Flash trades on public exchanges at improving valuation multiples over time.",
    "B": "Employing fixed-cost debt financing so shareholders capture the spread whenever Flash earns more on invested funds than the after-tax cost of that debt, amplifying both expected ROE and its variability.",
    "C": "Selling minority stakes in Flash's subsidiaries to monetize hidden asset value while retaining day-to-day operational control of each business.",
    "D": "Timing share repurchases around option-grant dates so reported earnings per share optics improve for incentive-plan measurement."
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Hearing equity and thinking exchange listings or buyback timing, not fixed-cost leverage",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Trading on the equity denotes using fixed-cost capital, principally debt, to lever shareholder returns: whenever the return earned on invested funds exceeds the after-tax cost of the fixed charges, residual return on equity is amplified; below that threshold, losses amplify symmetrically. The mechanism is measured through debt-to-equity and coverage relationships, not through share-market activity of any kind. Business interpretation: Eleanor Vance should connect the term to Flash's capital-structure debate, where incremental borrowing raises both expected ROE and earnings volatility together, which is precisely the trade-off the treasurer was describing. Common trap: hearing the word equity and thinking of exchange trading, spin-offs, or buyback timing rather than the fixed-charge leverage mechanic.",
  "ExplanationWrongA": "Choice A recasts the phrase as listing or exchanging shares; the idiom concerns capital structure and the spread between earned returns and fixed financing costs, not where or how Flash's stock trades on any exchange.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C describes partial sell-downs of subsidiaries, a portfolio action affecting consolidation scope; it leaves Flash's own fixed-charge financing untouched and has no connection to leverage trading on the equity.",
  "ExplanationWrongD": "Choice D frames repurchase timing around option grants, an EPS-optics tactic; buybacks alter share count, but the term targets the debt-fixed-cost spread that swings returns earned on common shareholders' capital.",
  "FormulaReference": "FA-07 Debt-to-Equity Ratio",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-273",
  "Section": "A",
  "Stem": "At a governance orientation, board member Eleanor Vance asks which statement correctly captures the term 'trading on the equity' as Flash's treasurer applied it when arguing for the new term-loan structure.",
  "Topic": "A.273 trading-on-the-equity",
  "UniqueConceptKey": "A-273-fixed-charge-leverage-meaning",
  "VerifiedChecks": [
    "Definition check: leverage amplifies ROE when return on invested funds > after-tax cost of debt",
    "Concept verified against FA-07 leverage framing; no arithmetic required",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (times interest earned; sequential driver attribution in coverage analysis)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Holding interest at the prior $1,050,000, the EBIT decline alone would have taken coverage to 3.47x (a 0.53x operating drag), and the remaining 0.67x came from the interest step-up to $1,300,000, so costlier financing drove the larger share of the fall.",
    "B": "Operations dominated the decline because EBIT fell $560,000 while interest rose only $250,000, a difference of more than double in raw dollar impact.",
    "C": "The decline is entirely a financing event; once the interest charge is fixed by contract, operating performance has no bearing on coverage outcomes for the year.",
    "D": "Using average interest of $1,175,000 across the two years gives the economically meaningful reading of 3.10x, showing only modest erosion rather than a 1.20x collapse."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Ranking coverage drivers by dollar changes instead of sequential ratio effects",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Times interest earned = EBIT / interest. Sequential decomposition isolates each driver: start from last year's 4.00x ($4,200,000 / $1,050,000). Holding interest at $1,050,000, the EBIT slide to $3,640,000 takes coverage to $3,640,000 / $1,050,000 = 3.47x, an operating drag of 0.53x. Applying the new interest charge of $1,300,000 completes the fall to $3,640,000 / $1,300,000 = 2.80x, a financing drag of 0.67x. Costlier debt, not operations, supplied the majority (0.67 of the total 1.20x) of the deterioration. Business interpretation: Tomas Lindqvist should anchor repricing negotiations on the interest step-up, since restoring EBIT alone recovers less than half of the lost covenant headroom. Common trap: ranking causes by raw dollar changes instead of their ratio-level sensitivity.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B ranks causes by absolute dollars, EBIT down $560,000 against interest up $250,000; ratio impact scales each change by its base, and the smaller interest increase sits on a far smaller divisor, magnifying its coverage effect to 0.67x versus 0.53x.",
  "ExplanationWrongC": "Choice C dismisses operations entirely; the decomposition attributes 0.53x of the 1.20x fall to the EBIT decline, a material headroom loss that no financing-only narrative should erase from the repricing discussion.",
  "ExplanationWrongD": "Choice D averages the two years' interest to $1,175,000 and reports 3.10x; blending periods manufactures a hybrid neither year produced and obscures the year-end 2.80x coverage the covenant actually tests.",
  "FormulaReference": "FA-08 Times Interest Earned",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-274",
  "Section": "A",
  "Stem": "Ahead of repricing talks on Flash's revolver, treasury analyst Tomas Lindqvist decomposes the coverage decline. Last year EBIT was $4,200,000 against interest of $1,050,000 (coverage 4.00x); this year EBIT is $3,640,000 against interest of $1,300,000 (coverage 2.80x). Which attribution of the 1.20x decline is analytically sound?",
  "Topic": "A.274 tie-driver-attribution",
  "UniqueConceptKey": "A-274-coverage-step-decomposition",
  "VerifiedChecks": [
    "Recomputed: 4200000/1050000 = 4.00; 3640000/1050000 = 3.47; 3640000/1300000 = 2.80",
    "Drag split: operating 4.00 - 3.47 = 0.53; financing 3.47 - 2.80 = 0.67; total = 1.20 (agrees)",
    "Cross-check: average-interest variant 3640000/1175000 = 3.10 rejected as methodology error",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (activity ratios; total asset turnover on average total assets)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "1.44 times",
    "B": "1.70 times",
    "C": "1.56 times",
    "D": "1.30 times"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Dividing by year-end or beginning assets instead of the two-point average",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Total asset turnover measures revenue generated per dollar of assets employed: TAT = revenue / average total assets. Average total assets = ($18,400,000 + $21,600,000) / 2 = $20,000,000. TAT = $31,200,000 / $20,000,000 = 1.56 times. The two-point average matches the income-statement flow to the balance-sheet capacity actually available across the period, the same convention used for ROA and inventory turns. Business interpretation: Grace Okafor can present 1.56x as Flash's baseline efficiency and track whether the asset additions implied by the growing balance translate proportionally into sales next period. Common trap: dividing by the year-end balance, which penalizes late-year capacity purchased too recently to produce any revenue yet.",
  "ExplanationWrongA": "Choice A uses ending assets of $21,600,000 for 1.44 times; the year-end base double-counts capacity added near the close and understates the turnover earned on assets actually available through the year.",
  "ExplanationWrongB": "Choice B uses beginning assets of $18,400,000 for 1.70 times, crediting the full year's revenue to a base that had already grown roughly 17 percent before mid-year expansions landed on the books.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D divides by average net fixed assets of $24,000,000 for 1.30 times; fixed assets exclude working-capital balances entirely, and the metric specified is total asset turnover on the full asset base.",
  "FormulaReference": "FA-24 Total Asset Turnover",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-275",
  "Section": "A",
  "Stem": "Assembling the lender deck, assistant treasurer Grace Okafor presents Flash's asset efficiency. Revenue for the year was $31,200,000; total assets were $18,400,000 at the start and $21,600,000 at the end; average net fixed assets were $24,000,000. What total asset turnover should Grace present?",
  "Topic": "A.275 tat-average-assets",
  "UniqueConceptKey": "A-275-two-point-asset-base",
  "VerifiedChecks": [
    "Recomputed: (18400000 + 21600000)/2 = 20000000; 31200000/20000000 = 1.56",
    "Second pass: 1.56 x 20000000 = 31200000 reproduces revenue (agrees)",
    "Distractor checks: 31200000/21600000 = 1.44; 31200000/18400000 = 1.70; 31200000/24000000 = 1.30",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
}
];
