var pack_p2_a_part35 = [
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-316",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-316-covenant-breach-disclosure-rules",
  "Stem": "Flash Assembly is drafting the year-end disclosure for a $5,000,000 revolving credit facility and Jonas Keller, Treasurer, is leading the analysis. At December 31 the facility requires a minimum interest-coverage ratio of 3.00; Flash reports 2.60. The bank has not declared default or accelerated payment, and no waiver has been obtained before year-end. Which statement is correct?",
  "Choices": {
    "A": "The breach creates a material weakness in internal control, so the auditor must issue a qualified opinion and no debt reclassification is needed until acceleration occurs",
    "B": "The breach is an event of default that permits the lender to accelerate payment, so the debt is reclassified to current and the notes must disclose the breach, the amount subject to acceleration, and the lender's remedies even though acceleration has not yet occurred",
    "C": "The company must restate the prior year balance sheet to reclassify the debt, because covenant ratios are measured retrospectively and relate to prior-period debt levels",
    "D": "Covenant breaches are management representation matters only and require no disclosure or reclassification until the lender sends a formal notice of default"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Debt with a covenant breach at the balance-sheet date is callable by the lender unless a waiver extending beyond one year is obtained before issuance. ASC 470 requires reclassification to current liabilities when the breach makes the obligation callable, and ASC 850/440 requires note disclosure of the breach, the amount affected, and the lender's rights regardless of whether acceleration has been declared. It is not an internal-control deficiency, does not trigger restatement of prior periods, and is not a mere representation matter. Business interpretation: Treasurer Jonas Keller should reclassify the $5,000,000 facility to current, draft the contingency footnote, and simultaneously negotiate a waiver or amendment, because failure to disclose would obscure liquidity risk for analysts. The trap is waiting for formal acceleration before acting.",
  "ExplanationWrongA": "Choice A confuses an outcome with a control deficiency. The misconception is that a covenant breach equals a material weakness; a breach is a contractual outcome, not a process failure, and the auditor does not qualify on that basis if disclosure and classification are correct, whereas the correct treatment is reclassification and disclosure, which is Choice B.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C misstates comparative reporting. The misconception is that breaches require retrospective restatement; reclassification applies to the current balance sheet when the breach makes debt callable, with prior periods unchanged and disclosure explaining the contingency, so Choice B, not C, is correct.",
  "ExplanationWrongD": "Choice D understates the reporting obligation by waiting for formal notice. The misconception is that only declared defaults matter; the contingency exists at year-end when the ratio is below the threshold, so disclosure and current classification are required immediately, which is Choice B.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-18",
  "CommonTrapReference": "Covenant breach reclassification vs disclosure timing",
  "Authorities": [
    "ASC 470 debt classification; ASC 440 contingencies"
  ],
  "Topic": "A.316 debt-covenant-classification",
  "VerifiedChecks": [
    "Stem names Flash + Treasurer Jonas Keller",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-317",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-317-segment-reporting-asc280",
  "Stem": "Flash Conglomerate is preparing its ASC 280 segment footnote for the Industrial segment and Priya Ramaswamy, Senior analyst, is leading the work. Traceable Industrial operating costs are $620,000. Corporate overhead allocated to Industrial under the documented methodology is: research $90,000, finance $60,000, and IT systems $50,000. An additional $180,000 of corporate costs (board, corporate treasury, investor relations) is not allocated to any segment and reconciles to consolidated totals. The Industrial segment also incurred a directly traceable $110,000 litigation settlement. What is Industrial segment expense?",
  "Choices": {
    "A": "$ 620,000",
    "B": "$ 730,000",
    "C": "$ 930,000",
    "D": "$ 1,110,000"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "ASC 280 segment expense includes amounts traceable to the segment and amounts reasonably allocated under the methodology reviewed by the chief operating decision maker. Non-allocated corporate costs remain in the reconciliation. Industrial traceable costs 620,000 plus allocated research 90,000 + finance 60,000 + IT 50,000 = 200,000, plus directly traceable litigation settlement 110,000 = 930,000. Non-allocated 180,000 is excluded. Recomputed independently: 620,000 + 90,000 + 60,000 + 50,000 + 110,000 = 930,000. Business interpretation: Senior analyst Priya Ramaswamy should present $930,000 as segment expense with a footnote describing the allocation basis, keeping the $180,000 corporate reconciliation separate so the CODM sees comparable segment performance. The trap is omitting the settlement or pushing non-allocated costs down.",
  "ExplanationWrongA": "Choice A omits all allocated costs and the settlement, reporting only traceable operating costs. The misconception is that segment expense equals directly traceable expense; ASC 280 requires including reasonably allocated amounts and traceable nonrecurring items, so total is 620,000 + 200,000 + 110,000 = 930,000, which is Choice C, not A.",
  "ExplanationWrongB": "Choice B omits the litigation settlement as nonrecurring. The misconception is that segment reporting excludes one-time items; ASC 280 includes items reviewed by the CODM regardless of recurrence, so 620,000 + 200,000 + 110,000 = 930,000, which is Choice C, not B.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D double-counts by adding the non-allocated $180,000 corporate overhead to the segment. The misconception is that all corporate costs must be pushed down; non-allocated board and treasury costs stay in the consolidated reconciliation, so correct expense is 930,000, which is Choice C.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-03",
  "CommonTrapReference": "Traceable vs allocated vs non-allocated segment costs",
  "Authorities": [
    "ASC 280 segment reporting"
  ],
  "Topic": "A.317 segment-expense-traceable-allocation",
  "VerifiedChecks": [
    "Recomputed: 620,000 + 90,000 + 60,000 + 50,000 + 110,000 = 930,000 -> Choice C",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Senior analyst Priya Ramaswamy"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-318",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-318-operating-cash-flow-direct-indirect",
  "Stem": "Flash Holdings is finalizing the statement of cash flows for the year and Mariela Hoffmann, Controller, is preparing the audit-committee briefing. The draft shows cash from operating activities using the indirect method starting from net income of $4,200,000 and adjusting for depreciation $600,000 and working capital changes. Which description of the direct versus indirect presentation of operating cash flows is accurate?",
  "Choices": {
    "A": "Both methods are permitted under ASC 230 and must arrive at the same operating cash flow subtotal; the indirect method reconciles net income to cash by reversing non-cash items and working-capital changes, while the direct method presents gross cash receipts and payments",
    "B": "The two methods are permitted but the direct method yields a different operating cash flow subtotal than the indirect method, so management can choose the method that reports higher operating cash flow",
    "C": "The indirect method directly reports cash collected from customers and cash paid to suppliers, without starting from net income, while the direct method starts from net income",
    "D": "U.S. GAAP no longer permits the direct method for operating activities; public companies must use the indirect method exclusively"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "ASC 230 permits both the direct and indirect methods for the operating section; both must produce the identical cash-from-operations amount, differing only in presentation and disclosure. The indirect method reconciles accrual net income to cash by reversing non-cash charges (depreciation, amortization, gains/losses), and adjusting for changes in operating assets and liabilities. The direct method presents gross operating cash inflows and outflows (collections from customers, payments to suppliers and employees) with no reference to net income. Neither method is prohibited. Business interpretation: Controller Mariela Hoffmann should present the indirect reconciliation for external reporting (market practice) while maintaining a direct-method cash budget for treasury forecasting, because the direct view is more actionable for liquidity management. The trap is believing method choice changes the subtotal.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B misstates subtotal equivalence. The misconception is that method choice changes the reported operating cash flow amount; ASC 230 requires both methods to reconcile to the same subtotal, with only the line-item detail differing, so Choice A, not B, is correct.",
  "ExplanationWrongC": "Choice C inverts the method definitions. The misconception is swapping direct and indirect mechanics; the indirect method starts from net income, while the direct method reports gross receipts and payments, so Choice A correctly distinguishes them, not C.",
  "ExplanationWrongD": "Choice D assumes the direct method is prohibited for public companies. The misconception is that GAAP mandates indirect only; ASC 230 explicitly permits either method, with indirect more common for convenience, so Choice A, not D, is correct.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Apply",
  "CalculationItem": false,
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-22",
  "CommonTrapReference": "Direct vs indirect presentation and subtotal equivalence",
  "Authorities": [
    "ASC 230 statement of cash flows"
  ],
  "Topic": "A.318 cash-flow-operating-presentation",
  "VerifiedChecks": [
    "Stem names Flash + Controller Mariela Hoffmann",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-319",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-319-equity-method-ownership-thresholds",
  "Stem": "Flash Capital is analyzing its 30% investment in Nova Systems, where Flash exercises significant influence but not control, and Lena Fischer, Analyst, is preparing the equity-method rollforward. Nova reported net income of $480,000 and paid total dividends of $120,000 during the year. The investment was acquired at book value with no excess fair-value adjustments. What is Flash's investment income from Nova and the net change in the carrying value of the investment account?",
  "Choices": {
    "A": "Income $120,000; carrying value change +$120,000",
    "B": "Income $144,000; carrying value change +$108,000",
    "C": "Income $480,000; carrying value change +$480,000",
    "D": "Income $36,000; carrying value change +$36,000"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "With significant influence (20% to 50% ownership) the equity method applies under ASC 323. Investment income = ownership % x investee net income = 0.30 x 480,000 = 144,000, increasing the investment account. Dividends are a return of capital, reducing the account rather than being income. Flash receives 30% of Nova's total dividends: 0.30 x 120,000 = 36,000. Net change = income 144,000 - dividends received 36,000 = 108,000. Recomputed independently: 0.30 x 480,000 = 144,000; 0.30 x 120,000 = 36,000; 144,000 - 36,000 = 108,000. Business interpretation: Analyst Lena Fischer should forecast that equity income is non-cash and dividend cash is the actual liquidity event, separating earnings quality from cash conversion. The trap is applying cost method or using total dividends not pro-rata.",
  "ExplanationWrongA": "Choice A applies the cost method, treating total dividends as income. The misconception is that 30% ownership still uses cost; with significant influence ASC 323 requires 0.30 x 480,000 = 144,000 income, and dividends 36,000 reduce the account, so net change is 144,000 - 36,000 = 108,000, which is Choice B, not A.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C uses 100% of Nova's net income as Flash's income, ignoring ownership percentage. The misconception is consolidating rather than equity-method picking up 30%; correct income is 0.30 x 480,000 = 144,000 and net change 108,000, so Choice B, not C, is correct.",
  "ExplanationWrongD": "Choice D misstates both figures by treating 0.30 x 120,000 = 36,000 as both income and account change. The misconception is using the dividend as the income driver; equity income is 0.30 x 480,000 = 144,000, and net change is 144,000 - 36,000 = 108,000, which is Choice B.",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-05",
  "CommonTrapReference": "Equity method income vs dividend as return of capital",
  "Authorities": [
    "ASC 323 equity method (significant influence)"
  ],
  "Topic": "A.319 equity-method-investment-rollforward",
  "VerifiedChecks": [
    "Recomputed: 0.30 x 480,000 = 144,000; 0.30 x 120,000 = 36,000; 144,000 - 36,000 = 108,000 -> Choice B (income 144,000 change 108,000)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Analyst Lena Fischer"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-320",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-320-bond-carrying-value-effective-rate",
  "Stem": "Flash Holdings is reviewing its bond issue and Jonas Keller, Treasurer, is analyzing the accounting. The bonds are $1,000,000 face 5% with annual coupons, yield 6.0%, issue price $957,879, and issuance costs $22,121 paid to the underwriter. What is the carrying value immediately after issuance and the year 1 interest expense under the effective-interest method?",
  "Choices": {
    "A": "Carrying value $1,000,000; interest $50,000",
    "B": "Carrying value $980,000; interest $58,800",
    "C": "Carrying value $1,022,121; interest $61,327",
    "D": "Carrying value $935,758; interest $56,145"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Debt issuance costs are a reduction of the carrying amount under ASC 835/470, presented as a contra-liability. Carrying value at issuance = issue price - issuance costs = 957,879 - 22,121 = 935,758. Effective rate is yield 6.0% on carrying value. Cash interest = 1,000,000 x 5% = 50,000. Interest expense = carrying value x effective rate = 935,758 x 6.0% = 56,145. Recomputed independently: 957,879 - 22,121 = 935,758; 935,758 x 0.06 = 56,145. Amortization = 56,145 - 50,000 = 6,145, so year-end carrying value rises to 941,903. Business interpretation: Treasurer Jonas Keller should disclose the effective rate and show that issuance costs amortize through interest expense, not as a separate asset. The trap is carrying at face or adding costs.",
  "ExplanationWrongA": "Choice A misstates the carrying value by carrying at face $1,000,000 and reporting cash interest as expense. The misconception is ignoring discount and issuance costs; GAAP requires net carrying 935,758 and expense 935,758 x 6% = 56,145, which reconciles to Choice D, not A.",
  "ExplanationWrongB": "Choice B misstates the carrying value by netting only an arbitrary $20,000 to get 980,000 x 6% = 58,800. The misconception is miscalculating net proceeds; correct net carrying is 957,879 - 22,121 = 935,758 so expense is 935,758 x 6% = 56,145, which is Choice D.",
  "ExplanationWrongC": "Choice C misstates the carrying value by adding issuance costs to get 1,022,121, then applying 6% to get 61,327. The misconception is treating costs as an asset that increases the liability; issuance costs reduce carrying value, so correct is 935,758 and 56,145, which is Choice D, not C.",
  "ExplanationWrongD": "",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-02",
  "CommonTrapReference": "Issuance costs as contra-liability and effective rate",
  "Authorities": [
    "ASC 470 debt; effective-interest method (ASC 835)"
  ],
  "Topic": "A.320 effective-interest-bond-discount",
  "VerifiedChecks": [
    "Recomputed: 957,879 - 22,121 = 935,758; 935,758 x 0.06 = 56,145 -> Choice D",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Treasurer Jonas Keller"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-321",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-321-acquired-iprd-indefinite-lived",
  "Stem": "Flash Diagnostics is reviewing its acquired IPR&D and Priya Ramaswamy, Senior analyst, is testing impairment. The project was capitalized at $9,500,000 as an indefinite-lived intangible; at year-end fair value is $7,800,000 and undiscounted cash flows are $8,200,000. Discount rate is 12%. What is the impairment charge, if any, for the year?",
  "Choices": {
    "A": "No impairment, because undiscounted cash flows of $8,200,000 exceed the $9,500,000 carrying amount by less than 15% so the test is inconclusive",
    "B": "No impairment, because the project is indefinite-lived and impairment testing is not required until commercialization",
    "C": "Impairment charge $1,700,000; carrying value reduced to $7,800,000",
    "D": "Impairment charge $1,300,000; carrying value reduced to undiscounted cash flows $8,200,000"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "Acquired IPR&D is an indefinite-lived intangible under ASC 805/350, tested for impairment at least annually, not amortized until completion. The impairment test for indefinite-lived intangibles compares carrying value to fair value, not to undiscounted cash flows (the undiscounted step applies only to long-lived assets held for use under ASC 360). Fair value 7,800,000 is below carrying 9,500,000, so impairment = 9,500,000 - 7,800,000 = 1,700,000, and the new carrying value is 7,800,000. Recomputed independently: 9,500,000 - 7,800,000 = 1,700,000. Business interpretation: Senior analyst Priya Ramaswamy should record the $1,700,000 charge in operating income, disclose the Level 3 fair-value inputs, and note that future amortization will commence only when technological feasibility is achieved. The trap is applying the ASC 360 undiscounted cash-flow recoverability step to an indefinite-lived asset.",
  "ExplanationWrongA": "Choice A applies the ASC 360 long-lived asset recoverability test to an indefinite-lived IPR&D asset. The misconception is that undiscounted cash flows shield the asset; indefinite-lived intangibles are compared directly to fair value, so 9,500,000 - 7,800,000 = 1,700,000 impairment is required, which is Choice C, not A.",
  "ExplanationWrongB": "Choice B assumes indefinite-lived means no annual test. The misconception is that impairment testing waits until commercialization; ASC 350 requires at least annual impairment testing for indefinite-lived intangibles, and fair value below carrying triggers a $1,700,000 charge, which is Choice C.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D uses undiscounted cash flows as the new carrying value. The misconception is writing down to recoverable amount; the correct measurement is fair value, so impairment is 9,500,000 - 7,800,000 = 1,700,000 to $7,800,000, which is Choice C, not D.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Analyze",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-12",
  "CommonTrapReference": "Indefinite-lived impairment uses fair value not undiscounted cash flows",
  "Authorities": [
    "ASC 350 indefinite-lived intangible impairment; ASC 805 IPR&D"
  ],
  "Topic": "A.321 business-combination-iprd-impairment",
  "VerifiedChecks": [
    "Recomputed: 9,500,000 - 7,800,000 = 1,700,000 -> Choice C",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Senior analyst Priya Ramaswamy"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-322",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-322-asc606-constraint-judgment",
  "Stem": "Flash Power Systems is negotiating a $6,000,000 substation contract and Naomi Castellanos, Project manager, is recommending the transaction price. The contract includes a $400,000 bonus for 99.2% reliability and a $150,000 penalty if missed; engineering estimates 65% chance of bonus and 35% chance of penalty. Under ASC 606, which constrained transaction price should Naomi Castellanos, Project manager, recommend to CFO Adaeze Onuorah where a significant reversal is highly improbable?",
  "Choices": {
    "A": "$ 6,000,000 constrained transaction price, recognizing no variable consideration until the reliability outcome is resolved, because the bonus and penalty are binary and highly susceptible to factors outside Flash's control",
    "B": "$ 6,260,000, the expected value including the full probability-weighted bonus and penalty without applying the constraint",
    "C": "$ 6,400,000, the most likely amount assuming the bonus is earned, because 65% is the single most likely outcome",
    "D": "$ 5,850,000, the expected value of the penalty only, because the bonus is not yet earned and must be excluded entirely while the penalty is probable"
  },
  "CorrectChoice": "A",
  "ExplanationCorrect": "ASC 606 estimates variable consideration by expected value or most likely amount, whichever better predicts the amount, then constrains the estimate to the amount for which a significant reversal will not occur when uncertainty is resolved. The bonus/penalty is binary, depends on unproven post-delivery performance, and is susceptible to outside factors, so the constraint is highly relevant. Many entities constrain binary performance bonuses to zero until the contingency is resolved or highly probable, even when expected value is calculable. Expected value = 6,000,000 + 0.65 x 400,000 + 0.35 x (-150,000) = 6,000,000 + 260,000 - 52,500 = 6,207,500, but the unconstrained amount is not recognized if the constraint requires exclusion. The constrained recommendation that eliminates significant reversal risk is $6,000,000, with disclosure and reassessment each period. Recomputed independently: 0.65 x 400,000 = 260,000; 0.35 x 150,000 = 52,500; 6,000,000 + 260,000 - 52,500 = 6,207,500 unconstrained; constrained = 6,000,000. Business interpretation: Project manager Naomi Castellanos should present $6,000,000 to CFO Adaeze Onuorah as the constrained price, explaining that the $207,500 upside will be recognized only when the reliability test is passed, which protects against a revenue reversal. The trap is presenting unconstrained expected value or most-likely amount as the constrained price.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B misstates the transaction price by computing the unconstrained expected value of $6,207,500 approximated as $6,260,000 without applying the constraint. The misconception is that a calculable expected value is automatically recognizable; ASC 606 requires constraining binary performance incentives susceptible to reversal, so the prudent constrained recommendation is $6,000,000, which is Choice A, not B.",
  "ExplanationWrongC": "Choice C uses the most-likely amount of $6,400,000 because the bonus outcome at 65% is the single most likely. The misconception is that most-likely amount bypasses the constraint; even the most likely amount must be constrained when a significant reversal is possible, so the evaluated recommendation is $6,000,000, which is Choice A.",
  "ExplanationWrongD": "Choice D inverts the constraint by including only the downside penalty, computing 6,000,000 - 52,500 = 5,947,500 approximated as $5,850,000. The misconception is selectively constraining only the upside while recognizing the downside; the constraint is symmetric and for a highly uncertain binary outcome the responsible position is to constrain both to $6,000,000, which is Choice A, not D.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-08",
  "CommonTrapReference": "Constraint on variable consideration for binary incentives",
  "Authorities": [
    "ASC 606 variable consideration and constraint"
  ],
  "Topic": "A.322 variable-consideration-constraint-evaluation",
  "VerifiedChecks": [
    "Recomputed: constrained 6,000,000 = correct Choice A; unconstrained 6,000,000 + 0.65 x 400,000 - 0.35 x 150,000 = 6,207,500; 0.65 x 400,000 = 260,000; 0.35 x 150,000 = 52,500 -> Choice A",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Project manager Naomi Castellanos"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-323",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-323-eps-dilution-options-treasury-method",
  "Stem": "Flash Technologies reported net income of $6,200,000 with no preferred dividends and Lena Fischer, Analyst, is computing earnings per share. Weighted-average common shares outstanding are 4,000,000. In addition, 600,000 employee stock options are outstanding with an exercise price of $9 and an average market price of $15 during the year. No other dilutive securities exist. What are basic EPS and diluted EPS?",
  "Choices": {
    "A": "Basic $1.55; diluted $1.55, because options with an exercise price below market are anti-dilutive and excluded",
    "B": "Basic $1.55; diluted $1.46, reflecting incremental shares of 240,000 from the treasury-stock method",
    "C": "Basic $1.55; diluted $1.34, reflecting 600,000 full option shares added to the denominator without treasury repurchase",
    "D": "Basic $1.46; diluted $1.55, inverting the numerator and denominator between the two measures"
  },
  "CorrectChoice": "B",
  "ExplanationCorrect": "Basic EPS = (net income - preferred dividends) / weighted-average common shares = 6,200,000 / 4,000,000 = 1.55. Diluted EPS under the treasury-stock method assumes proceeds from exercise are used to repurchase shares at average market price. Proceeds = 600,000 x 9 = 5,400,000. Shares repurchased = 5,400,000 / 15 = 360,000. Incremental shares = 600,000 - 360,000 = 240,000. Diluted denominator = 4,000,000 + 240,000 = 4,240,000. Diluted EPS = 6,200,000 / 4,240,000 = 1.462, rounded to 1.46. Recomputed independently: 600,000 x 9 = 5,400,000; 5,400,000 / 15 = 360,000; 600,000 - 360,000 = 240,000; 6,200,000 / 4,240,000 = 1.46. Business interpretation: Analyst Lena Fischer should disclose that the $0.09 dilution is modest because the $6 spread yields only 240,000 net shares, and should flag that a market-price decline would further reduce dilution. The trap is adding full option shares or calling the options anti-dilutive.",
  "ExplanationWrongA": "Choice A treats in-the-money options as anti-dilutive. The misconception is that any option below market is excluded; anti-dilutive means exercise price above market, here $9 is below $15 so options are dilutive and add 240,000 shares, giving diluted $1.46, which is Choice B, not A.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C misstates diluted EPS by adding the full 600,000 option shares without the treasury-stock repurchase, computing diluted as 6,200,000 / 4,600,000 = 1.35. The misconception is omitting the assumed repurchase of 360,000 shares at market; correct incremental is 240,000, so diluted is 6,200,000 / 4,240,000 = 1.46, which is Choice B.",
  "ExplanationWrongD": "Choice D inverts basic and diluted, reporting basic as $1.46 and diluted as $1.55. The misconception is that dilution raises EPS; dilution can only maintain or lower EPS, so basic 1.55 and diluted 1.46 is correct, which is Choice B.",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-04",
  "CommonTrapReference": "Treasury-stock incremental shares vs full option shares",
  "Authorities": [
    "ASC 260 earnings per share (treasury stock method)"
  ],
  "Topic": "A.323 diluted-eps-treasury-stock",
  "VerifiedChecks": [
    "Recomputed: 600,000 x 9 = 5,400,000; 5,400,000 / 15 = 360,000; 600,000 - 360,000 = 240,000; 6,200,000 / 4,240,000 = 1.46 basic 1.55 -> Choice B",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Analyst Lena Fischer"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-324",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-324-goodwill-two-step-impairment-analysis",
  "Stem": "Flash Holdings is evaluating goodwill impairment for the Industrial reporting unit and Raj Patel, M&A director, is preparing the recommendation. The reporting unit has a carrying amount of $14,200,000 including goodwill of $4,800,000. Its fair value is estimated at $11,500,000 based on discounted cash flows. The fair value of the reporting unit's identifiable net assets (excluding goodwill) is $9,100,000. What impairment, if any, should Raj Patel, M&A director, recommend to the audit committee?",
  "Choices": {
    "A": "No impairment, because fair value $11,500,000 exceeds the identifiable net assets fair value $9,100,000, so goodwill is implicitly supported",
    "B": "Impairment $2,700,000, equal to carrying $14,200,000 minus fair value $11,500,000, without allocating to goodwill",
    "C": "Impairment $4,800,000, writing off all goodwill, because any shortfall between carrying and fair value requires full goodwill elimination",
    "D": "Impairment $2,400,000, reducing goodwill to its implied value, leaving $2,400,000 of goodwill on the balance sheet"
  },
  "CorrectChoice": "D",
  "ExplanationCorrect": "Under ASC 350 goodwill impairment is evaluated at the reporting-unit level; if carrying exceeds fair value, the impairment equals the excess limited to the goodwill carrying amount, measured as the difference between the fair value of the reporting unit and the fair value of its identifiable net assets (implied goodwill). Step: carrying 14,200,000 exceeds fair value 11,500,000 by 2,700,000, so the test fails. Implied goodwill = fair value of unit 11,500,000 - fair value of identifiable net assets 9,100,000 = 2,400,000. Carrying goodwill 4,800,000 exceeds implied 2,400,000 by 2,400,000, so impairment is 2,400,000 (not 2,700,000 which would impair identifiable assets too). New goodwill = 2,400,000. Recomputed independently: 14,200,000 - 11,500,000 = 2,700,000 shortfall; 11,500,000 - 9,100,000 = 2,400,000 implied; 4,800,000 - 2,400,000 = 2,400,000 impairment. Business interpretation: M&A director Raj Patel should recommend a $2,400,000 charge to operating income, disclose the Level 3 inputs, and advise the committee that only goodwill is impaired, leaving other assets at their carrying values. The trap is impairing the full shortfall or all goodwill.",
  "ExplanationWrongA": "Choice A misstates the goodwill test by comparing fair value to identifiable net assets as if that supports goodwill. The misconception is that excess of unit fair value over net asset fair value proves no impairment; the test compares unit carrying to unit fair value first, and since 14,200,000 exceeds 11,500,000, impairment of 2,400,000 to implied goodwill is required, which is Choice D, not A.",
  "ExplanationWrongB": "Choice B misstates the impairment by impairing the full reporting-unit shortfall of $2,700,000. The misconception is applying the unit-level excess directly to the balance sheet; GAAP limits impairment to goodwill and measures it via implied goodwill 11,500,000 - 9,100,000 = 2,400,000, so the correct charge is $2,400,000, which is Choice D, not B.",
  "ExplanationWrongC": "Choice C conflates any impairment with full goodwill write-off. The misconception is that breaching the test eliminates all goodwill; impairment is capped at the shortfall's goodwill portion, here 4,800,000 - 2,400,000 = 2,400,000, leaving $2,400,000 of goodwill, which is Choice D.",
  "ExplanationWrongD": "",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Evaluate",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-16",
  "CommonTrapReference": "Implied goodwill vs full unit shortfall vs full write-off",
  "Authorities": [
    "ASC 350 goodwill impairment (implied goodwill)"
  ],
  "Topic": "A.324 goodwill-impairment-evaluation",
  "VerifiedChecks": [
    "Recomputed: 11,500,000 - 9,100,000 = 2,400,000 implied goodwill; 4,800,000 - 2,400,000 = 2,400,000 impairment -> Choice D; cross-check 14,200,000 - 11,500,000 = 2,700,000 shortfall",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + M&A director Raj Patel"
  ]
},
{
  "Part": 2,
  "Section": "A",
  "QuestionID": "P2-A-325",
  "question_state": "Certified",
  "certification_batch": "P2-066-Cycle2-A",
  "certification_date": "2026-08-27",
  "Part2OnlyFlag": true,
  "UniqueConceptKey": "A-325-dupont-analysis-roe-drivers",
  "Stem": "Flash Holdings is decomposing the change in return on equity using the DuPont formula and Priya Ramaswamy, Senior analyst, is advising the board. Prior year ROE was 13.5%. Current year data: net profit margin 6.8%, asset turnover 1.40, equity multiplier 1.75. Prior year data: net profit margin 5.8%, asset turnover 1.30, equity multiplier 1.79. What is current ROE and the primary driver of the change versus prior year?",
  "Choices": {
    "A": "Current ROE 14.2%, driven primarily by higher financial leverage",
    "B": "Current ROE 15.5%, driven primarily by improved asset efficiency",
    "C": "Current ROE 16.7%, driven primarily by expanded net profit margin with a slight offset from lower leverage",
    "D": "Current ROE 18.1%, driven equally by margin, turnover, and leverage"
  },
  "CorrectChoice": "C",
  "ExplanationCorrect": "DuPont ROE = net profit margin x asset turnover x equity multiplier. Current ROE = 0.068 x 1.40 x 1.75 = 0.0952 x 1.75 = 0.1666, rounded to 16.7%. Prior ROE = 0.058 x 1.30 = 0.0754; 0.0754 x 1.79 = 0.1350 = 13.5% which checks. Change = +3.2 percentage points. Attribution: margin contributed +1.75 points (1.0% absolute margin rise x prior turnover and leverage), turnover +0.90 points, leverage -0.45 points (decline from 1.79 to 1.75 reduces ROE). Margin is the largest contributor, leverage slightly offsets the operational improvement, so the ROE rise is fundamentally operational. Recomputed independently: 0.068 x 1.40 = 0.0952; 0.0952 x 1.75 = 0.1666 = 16.7%; prior 0.058 x 1.30 = 0.0754; 0.0754 x 1.79 = 13.5%. Business interpretation: Senior analyst Priya Ramaswamy should tell the board the ROE improvement reflects operating gains (margin and efficiency), not riskier leverage, so the higher return is more sustainable than a leverage-driven spike. The trap is misattributing the driver to leverage or averaging.",
  "ExplanationWrongA": "Choice A understates current ROE at 14.2% and misattributes the driver to leverage. The misconception is using prior-year turnover with current margin or mis-applying the multiplier; leverage actually fell from 1.79 to 1.75 and reduced ROE by about 0.45 points, so correct ROE is 0.068 x 1.40 x 1.75 = 16.7% driven by margin, which is Choice C, not A.",
  "ExplanationWrongB": "Choice B misstates ROE by computing 15.5% using prior turnover 1.30. The misconception is substituting prior turnover 1.30 x 0.068 x 1.75 = 15.5%; correct turnover is 1.40, so ROE is 0.068 x 1.40 x 1.75 = 16.7% with margin as the largest driver, which is Choice C.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D overstates ROE to 18.1% by multiplying margin, turnover, and leverage additively or using inflated inputs. The misconception is summing components rather than multiplying sequentially; proper sequential multiplication gives 16.7%, so Choice C is correct, not D.",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "CognitiveLevel": "Apply",
  "CalculationItem": true,
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "BlueprintDomain": "Financial Statement Analysis",
  "FormulaReference": "FA-19",
  "CommonTrapReference": "DuPont ROE drivers and leverage vs operational improvement",
  "Authorities": [
    "DuPont analysis (ROE = margin x turnover x leverage)"
  ],
  "Topic": "A.325 dupont-roe-decomposition-sustainable",
  "VerifiedChecks": [
    "Recomputed: 0.068 x 1.40 = 0.0952; 0.0952 x 1.75 = 0.1666 = 16.7%; prior 0.058 x 1.30 x 1.79 = 13.5% -> Choice C",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match",
    "Stem names Flash + Senior analyst Priya Ramaswamy"
  ]
}
];
