var pack_p2_a_part8 = [
{
  "Authorities": [
    "ASC 205-10",
    "ASC 260-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "16.0%; Meridian outperforms the industry benchmark",
    "B": "16.8%; Meridian outperforms the industry benchmark",
    "C": "13.6%; Meridian underperforms the industry benchmark",
    "D": "18.4%; Meridian outperforms the industry benchmark"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Forgetting to deduct preferred dividends when computing return on common equity — candidates use total net income in the numerator, overstating the return available to common shareholders.",
  "CorrectChoice": "A",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "ROCE = (Net income - Preferred dividends) / Average common equity = ($840,000 - $40,000) / $5,000,000 = $800,000 / $5,000,000 = 16.0%. At 16.0%, Meridian exceeds the 14.0% industry benchmark by 200 basis points, indicating that the company generates above-average returns for its common shareholders relative to the homebuilding supply sector. A common error is to omit the preferred dividend deduction, which inflates the numerator and overstates the return attributable to common shareholders.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B is incorrect because it omits preferred dividends: $840,000 / $5,000,000 = 16.8%. Preferred dividends must be subtracted from net income when computing return on common equity because they represent earnings allocated to preferred shareholders, not common shareholders. A candidate who ignores preferred dividends overstates the common shareholders' return by 80 basis points. The correct numerator is net income available to common shareholders.",
  "ExplanationWrongC": "Option C is incorrect because it erroneously deducts interest expense from net income before computing ROE: ($840,000 - $40,000 - $120,000) / $5,000,000 = $680,000 / $5,000,000 = 13.6%. Interest expense is already reflected in net income — the candidate is double-counting this cost. Net income is the bottom-line earnings figure after all expenses, including interest. No further deduction is warranted.",
  "ExplanationWrongD": "Option D is incorrect because it adds back interest expense to net income: ($840,000 + $120,000 - $40,000) / $5,000,000 = $920,000 / $5,000,000 = 18.4%. Adding back interest converts the numerator toward an unlevered earnings measure, which is inconsistent with ROE. ROE measures the return to equity holders after all costs, including interest paid to creditors. The correct formula uses net income attributable to common shareholders.",
  "FormulaReference": "Return on Common Equity = (Net Income - Preferred Dividends) / Average Common Shareholders' Equity",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-041",
  "Section": "A",
  "Stem": "Meridian Corporation reports net income of $840,000, preferred dividends of $40,000, interest expense of $120,000, and average common shareholders' equity of $5,000,000 for 2026. The homebuilding supply industry median ROE is 14.0%. Compute Meridian's return on common equity and assess its performance relative to the benchmark.",
  "Topic": "A.041 Return on common equity — computation and benchmark comparison",
  "UniqueConceptKey": "A-041-return-on-common-equity-computation-and-benchmark-comparison",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 260-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Basic EPS is $2.40; the options are dilutive and add 45,000 incremental shares to the diluted EPS denominator",
    "B": "Basic EPS is $2.30; the options are antidilutive and are excluded from diluted EPS altogether",
    "C": "Basic EPS is $2.30; the options are dilutive and add 45,000 incremental shares to the diluted EPS denominator",
    "D": "Basic EPS is $2.30; the options are dilutive and add 150,000 shares to the diluted EPS denominator"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Using the full option or warrant share count in the diluted EPS denominator without applying the treasury stock method — candidates forget that the assumed repurchase of shares with exercise proceeds partially offsets the dilution.",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Basic EPS = (Net income - Preferred dividends) / Weighted-average common shares = ($2,400,000 - $100,000) / 1,000,000 = $2.30. Under ASC 260-10-45, the treasury stock method determines incremental shares from options: Repurchase shares = Cash proceeds / Average market price = (150,000 x $35) / $50 = $5,250,000 / $50 = 105,000 shares. Incremental shares = 150,000 - 105,000 = 45,000. Since the exercise price ($35) is less than the market price ($50), the options are dilutive and must be included in the diluted EPS denominator. A common error is to use the gross option share count (150,000) instead of the treasury-stock-method net incremental shares.",
  "ExplanationWrongA": "Option A is incorrect because it computes basic EPS without deducting preferred dividends: $2,400,000 / 1,000,000 = $2.40. Under ASC 260-10-45, basic EPS must subtract preferred dividends from net income before dividing by common shares outstanding because preferred dividends are earnings attributable to preferred shareholders, not common shareholders. The candidate identified the correct dilutive share count but used the wrong basic EPS numerator.",
  "ExplanationWrongB": "Option B is incorrect because it classifies the options as antidilutive. Under ASC 260-10-45, stock options are dilutive when the exercise price ($35) is below the average market price ($50). The treasury stock method yields 45,000 incremental shares, which increases the denominator and reduces EPS — confirming dilutive status. A candidate reaching this conclusion likely confused the condition for antidilution (exercise price > market price), which would produce zero incremental shares under the treasury stock method.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D is incorrect because it uses the gross option share count (150,000) without applying the treasury stock method. Under ASC 260-10-45, the treasury stock method assumes that option proceeds ($5,250,000) are used to repurchase shares at the average market price ($50), reducing the net share increase to 45,000. Using the full 150,000 shares overstates the dilutive impact because it ignores the cash inflow that partially offsets the share issuance.",
  "FormulaReference": "Basic EPS = (Net Income - Preferred Dividends) / Weighted-Average Common Shares; Treasury Stock Method Incremental Shares = Options Outstanding - (Proceeds / Average Market Price)",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-042",
  "Section": "A",
  "Stem": "Ridgeline Corporation reported net income of $2,400,000 and paid $100,000 in preferred dividends during 2026. The weighted-average number of common shares outstanding was 1,000,000. Ridgeline has 150,000 outstanding stock options with an exercise price of $35; the average market price per common share during the year was $50. Under ASC 260-10, which of the following is correct regarding Ridgeline's basic EPS and the dilutive effect of the options?",
  "Topic": "A.042 Earnings per share — basic computation and dilutive security identification",
  "UniqueConceptKey": "A-042-earnings-per-share-basic-computation-and-dilutive-security-ident",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10",
    "ASC 225-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "18.0%; does not meet the 22% target",
    "B": "15.0%; does not meet the 22% target",
    "C": "10.0%; does not meet the 22% target",
    "D": "25.0%; meets the 22% target"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Including depreciation and amortization in the EBITDA computation — candidates compute EBIT (or even net income) instead of EBITDA because they forget that the 'DA' in EBITDA stands for depreciation and amortization, which must be excluded.",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "EBITDA = Revenue - COGS - Selling & Admin = $10,000,000 - $6,000,000 - $1,500,000 = $2,500,000. EBITDA margin = EBITDA / Revenue = $2,500,000 / $10,000,000 = 25.0%. EBITDA excludes depreciation, amortization, interest, and taxes — these items are not deducted when computing EBITDA. At 25.0%, Northpoint exceeds the 22% target by 300 basis points. A common error is to subtract depreciation and amortization from EBITDA, converting it to EBIT and producing a lower margin.",
  "ExplanationWrongA": "Option A is incorrect because it computes the EBIT margin instead of EBITDA. Subtracting depreciation ($500,000) and amortization ($200,000) from EBITDA yields: $2,500,000 - $700,000 = $1,800,000; $1,800,000 / $10,000,000 = 18.0%. EBIT includes depreciation and amortization charges, whereas EBITDA explicitly excludes them. The candidate computed the correct EBIT margin but did not complete the step of adding back D&A to arrive at EBITDA.",
  "ExplanationWrongB": "Option B is incorrect because it computes the pretax margin. Subtracting depreciation ($500,000), amortization ($200,000), and interest ($300,000) from EBITDA yields: $2,500,000 - $1,000,000 = $1,500,000; $1,500,000 / $10,000,000 = 15.0%. The candidate moved two levels below EBITDA — first to EBIT by subtracting D&A, then to EBT by subtracting interest. EBITDA stands above all of these deductions.",
  "ExplanationWrongC": "Option C is incorrect because it computes the net profit margin. Subtracting all non-revenue items yields net income of $1,000,000; $1,000,000 / $10,000,000 = 10.0%. Net income reflects every expense including depreciation, amortization, interest, and taxes. EBITDA deliberately excludes all four of these charges to isolate operating earnings before capital-related and financing costs. The correct EBITDA computation stops after deducting only COGS and SG&A.",
  "ExplanationWrongD": "",
  "FormulaReference": "EBITDA Margin = (Revenue - COGS - SG&A) / Revenue",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-043",
  "Section": "A",
  "Stem": "Northpoint Industries provided selected income statement data for the year ended December 31, 2026: Revenue $10,000,000, Cost of Goods Sold $6,000,000, Selling and Administrative Expenses $1,500,000, Depreciation Expense $500,000, Amortization Expense $200,000, Interest Expense $300,000, and Income Tax Expense $500,000. Management targets an EBITDA margin of at least 22%. Compute Northpoint's EBITDA margin and determine whether it meets the target.",
  "Topic": "A.043 EBITDA margin — computation and target comparison",
  "UniqueConceptKey": "A-043-ebitda-margin-computation-and-target-comparison",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 280-10",
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "30.0%; exceeds the 18.0% company operating margin",
    "B": "20.0%; exceeds the 18.0% company operating margin",
    "C": "30.0%; falls below the 18.0% company operating margin",
    "D": "22.5%; exceeds the 18.0% company operating margin"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Deducting allocated common corporate expenses when computing segment margin — candidates treat common costs as segment costs, understating the segment's true contribution to corporate profitability.",
  "CorrectChoice": "A",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Segment margin = Segment revenue - Traceable costs = $4,500,000 - $3,150,000 = $1,350,000. Segment margin percentage = $1,350,000 / $4,500,000 = 30.0%. Under ASC 280-10, segment margin is computed before allocated common corporate expenses because those costs are not traceable to individual segments and would not be avoided if the segment were discontinued. At 30.0%, the Consumer Products division exceeds the 18.0% company operating margin by 1,200 basis points, indicating above-average divisional profitability. A common error is to deduct allocated common expenses from segment revenue, which understates the segment's true contribution.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B is incorrect because it deducts allocated common corporate expenses from segment revenue before computing the margin: ($4,500,000 - $3,150,000 - $450,000) / $4,500,000 = $900,000 / $4,500,000 = 20.0%. Under ASC 280-10, common corporate expenses are not segment expenses because they are not directly traceable to the division's operations. Including them in the segment margin computation penalizes the division for costs it does not control.",
  "ExplanationWrongC": "Option C is incorrect because it computes the segment margin correctly at 30.0% but reaches the wrong comparative conclusion. A 30.0% segment margin exceeds 18.0% by a wide margin—the division is substantially more profitable than the company average. The candidate may have reversed the comparison direction or misread the benchmark. The Consumer Products division clearly outperforms the company-wide operating margin.",
  "ExplanationWrongD": "Option D is incorrect because it applies Westfield's effective tax rate to the segment margin before computing the percentage: $1,350,000 x (1 - 0.25) / $4,500,000 = $1,012,500 / $4,500,000 = 22.5%. Segment margin is a pretax measure under ASC 280-10 — taxes are assessed at the corporate level, not the segment level. Applying a tax rate to a segment's traceable results conflates corporate-level tax allocation with operational segment performance.",
  "FormulaReference": "Segment Margin = Segment Revenue - Traceable Costs; Segment Margin % = Segment Margin / Segment Revenue",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-044",
  "Section": "A",
  "Stem": "Westfield Corporation operates three divisions. The Consumer Products division reported segment revenue of $4,500,000, traceable costs of $3,150,000, and allocated common corporate expenses of $450,000. Westfield's overall company operating margin is 18.0%. Compute the Consumer Products division's segment margin as a percentage of segment revenue and compare it to the company's overall operating margin.",
  "Topic": "A.044 Segment profitability — segment margin vs. company operating margin",
  "UniqueConceptKey": "A-044-segment-profitability-segment-margin-vs-company-operating-margin",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 225-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "40.0%; Pendleton outperforms the industry median",
    "B": "10.0%; Pendleton matches the industry median",
    "C": "12.0%; Pendleton outperforms the industry median",
    "D": "20.0%; Pendleton outperforms the industry median"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Selecting gross margin or operating margin instead of net profit margin when the question specifies the net profit margin — the candidate computes the correct ratio at the wrong tier of the income statement.",
  "CorrectChoice": "C",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Net profit margin = Net Income / Net Revenue = $840,000 / $7,000,000 = 12.0%. Under ASC 225-10, net profit margin is the most comprehensive single-period profitability ratio. At 12.0%, Pendleton exceeds the apparel manufacturing industry median of 10.0% by 200 basis points, indicating stronger cost control and/or pricing power relative to peer companies. A common error is to select the gross margin (40.0%) or operating margin (20.0%) instead of the net margin — each margin answers a different question about profitability.",
  "ExplanationWrongA": "Option A is incorrect because it reports the gross margin: ($7,000,000 - $4,200,000) / $7,000,000 = $2,800,000 / $7,000,000 = 40.0%. Gross margin reflects only the direct cost of goods sold and ignores operating expenses, interest, and taxes. Net profit margin is computed using net income — the final bottom-line figure after all costs. The candidate selected a margin from the wrong tier of the income statement.",
  "ExplanationWrongB": "Option B is incorrect because it reports the industry median (10.0%) rather than Pendleton's own computed net profit margin. The candidate likely substituted the benchmark figure for Pendleton's actual result without performing the computation. Pendleton's net income of $840,000 divided by revenue of $7,000,000 yields a net profit margin of 12.0%, not 10.0%. The industry benchmark is a comparison point, not a substitute for the company-specific ratio.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D is incorrect because it reports the operating margin: ($7,000,000 - $4,200,000 - $1,400,000) / $7,000,000 = $1,400,000 / $7,000,000 = 20.0%. Operating margin excludes interest and taxes and therefore overstates the proportion of revenue that flows to the bottom line. Net profit margin requires using net income, which is $840,000, not operating income of $1,400,000. The candidate selected a margin from too high on the income statement.",
  "FormulaReference": "Net Profit Margin = Net Income / Net Revenue",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-045",
  "Section": "A",
  "Stem": "Pendleton Corporation's 2026 income statement shows: Net Revenue $7,000,000, Cost of Goods Sold $4,200,000, Operating Expenses $1,400,000, Interest Expense $140,000, Income Tax Expense $210,000, and Net Income $840,000. The apparel manufacturing industry's median net profit margin is 10.0%. Compute Pendleton's net profit margin and determine whether it outperforms the industry median.",
  "Topic": "A.045 Profitability benchmarking — net profit margin vs. industry median",
  "UniqueConceptKey": "A-045-profitability-benchmarking-net-profit-margin-vs-industry-median",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "5.6%",
    "B": "16.0%",
    "C": "24.6%",
    "D": "10.4%"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Using the dividend payout ratio instead of the retention ratio in the SGR formula — candidates multiply ROE by the payout ratio (5.6%) instead of by (1 - payout ratio) (10.4%), producing the dividend component rather than the growth component.",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Sustainable growth rate = ROE x Retention ratio = ROE x (1 - Payout ratio) = 16.0% x (1 - 0.35) = 16.0% x 0.65 = 10.4%. The SGR represents the maximum rate at which a company can grow revenue and assets without issuing new equity or increasing financial leverage. Brightstone can sustain 10.4% annual growth using only internally generated earnings, assuming stable margins and capital structure. A common error is to multiply ROE by the payout ratio (5.6%), which would represent the portion of ROE distributed to shareholders rather than reinvested.",
  "ExplanationWrongA": "Option A is incorrect because it multiplies ROE by the payout ratio: 16.0% x 0.35 = 5.6%. The payout ratio measures earnings distributed as dividends — the sustainable growth rate uses the retention ratio (1 minus the payout ratio), which measures earnings reinvested in the business. A candidate reaching 5.6% has computed the dividend yield contribution from ROE, not the growth rate.",
  "ExplanationWrongB": "Option B is incorrect because it reports the ROE itself (16.0%) as the sustainable growth rate, implicitly assuming a 100% retention ratio. While ROE is a key driver of SGR, the company only retains 65% of earnings — the remaining 35% is paid as dividends and is unavailable for reinvestment. SGR must reflect the portion of ROE actually plowed back into the business.",
  "ExplanationWrongC": "Option C is incorrect because it divides ROE by the retention ratio: 16.0% / 0.65 = 24.6%. This inverts the SGR formula — the candidate mistakenly applied division where multiplication is required. The correct formula multiplies ROE by the retention ratio because only retained earnings (not total ROE) can fund internal growth. Dividing produces a result that exceeds ROE, which overstates Brightstone's true sustainable growth capacity.",
  "ExplanationWrongD": "",
  "FormulaReference": "Sustainable Growth Rate = ROE x (1 - Dividend Payout Ratio)",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-046",
  "Section": "A",
  "Stem": "Brightstone Corporation reported a return on common equity of 16.0% and paid out 35% of its net income as dividends during 2026. Brightstone's capital structure and profit margins are expected to remain stable, with no planned equity issuances. Compute Brightstone's sustainable growth rate.",
  "Topic": "A.046 Sustainable growth rate computation",
  "UniqueConceptKey": "A-046-sustainable-growth-rate-computation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 470-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "1.64; Crestview meets the 1.50 covenant requirement.",
    "B": "4.38; Crestview easily meets the covenant with substantial headroom.",
    "C": "2.63; Crestview meets the covenant with comfortable margin.",
    "D": "1.27; Crestview fails the 1.50 covenant and may face technical default."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Confusing DSCR (which includes principal payments in the denominator) with times interest earned (which includes only interest expense)",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 470-10, the debt service coverage ratio measures a borrower's ability to generate sufficient earnings to cover all mandatory debt payments. DSCR = EBITDA / (Principal + Interest) = $840,000 / ($320,000 + $192,000) = $840,000 / $512,000 = 1.64. Since 1.64 exceeds the 1.50 covenant minimum, Crestview is in compliance. A DSCR above 1.0 indicates positive coverage; the 1.50 covenant provides a 50% cushion against earnings declines. A common error is confusing DSCR with times interest earned — DSCR incorporates mandatory principal repayments in the denominator, making it a more stringent test of debt-servicing capacity than TIE alone.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Option B is incorrect because it divides EBITDA by interest expense alone ($840,000 / $192,000 = 4.38), completely ignoring the $320,000 annual principal obligation. DSCR requires total debt service in the denominator — both principal and interest — because lenders evaluate whether the borrower can meet all required cash outflows, not merely the interest coupon. A candidate selecting this option likely confused DSCR with the times interest earned ratio, which uses only interest in the denominator.",
  "ExplanationWrongC": "Option C is incorrect because it divides EBITDA by principal payments alone ($840,000 / $320,000 = 2.63), omitting the $192,000 annual interest charge. Total debt service includes both components — a borrower that cannot pay interest is in default regardless of its ability to repay principal. The correct DSCR of 1.64 reflects both the $320,000 principal amortization and the $192,000 interest obligation, providing a complete measure of Crestview's debt-servicing capacity under the loan agreement.",
  "ExplanationWrongD": "Option D is incorrect because it subtracts interest expense from EBITDA before dividing by total debt service, computing ($840,000 - $192,000) / $512,000 = 1.27. This double-counts interest by removing it from both the numerator and the denominator. DSCR intentionally uses EBITDA as the numerator precisely because EBITDA represents operating income available to service debt before any debt-service payments are made. The correct ratio is $840,000 / $512,000 = 1.64.",
  "FormulaReference": "Debt Service Coverage Ratio",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-047",
  "Section": "A",
  "Stem": "Crestview Distribution reported EBITDA of $840,000 for the fiscal year. Its $3,200,000 term loan requires annual principal payments of $320,000 and annual interest of $192,000 at a 6.0% fixed rate. The loan covenant requires a minimum debt service coverage ratio (DSCR) of 1.50, measured as EBITDA divided by total annual debt service. Credit analyst Elena Voss must determine whether Crestview complies with the covenant. Which of the following correctly states Crestview's DSCR and compliance status?",
  "Topic": "A.047 debt service coverage ratio",
  "UniqueConceptKey": "A-047-debt-service-coverage-ratio",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 470-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Atlas is in technical default because 'at least 2.50' means the ratio must strictly exceed 2.50; equaling the stated minimum does not satisfy a financial maintenance covenant under standard credit agreement interpretation.",
    "B": "The TIE is properly 2.20, computed as ($600,000 + $500,000) / $500,000. Atlas fails the covenant, and the CFO's claim of 2.50 represents an improper rounding of 2.20 upward.",
    "C": "Atlas is in compliance because EBIT of $1,250,000 divided by $500,000 interest expense yields a TIE of exactly 2.50, and a covenant requiring 'at least' a stated ratio includes the threshold value itself.",
    "D": "Atlas fails the covenant because the correct TIE is ($600,000 + $150,000) / $500,000 = 1.50. Interest expense is a real cash outflow that reduces earnings and should not be added back to the numerator under the indenture's definition of 'earnings.'"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Misinterpreting 'at least' as requiring strict exceedance of the covenant threshold, or omitting income tax expense when computing EBIT for the TIE numerator",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "The times interest earned ratio measures a company's ability to meet interest obligations from operating earnings. TIE = EBIT / Interest Expense. EBIT = Net Income + Income Tax Expense + Interest Expense = $600,000 + $150,000 + $500,000 = $1,250,000. TIE = $1,250,000 / $500,000 = 2.50. Under standard contractual interpretation, a covenant requiring 'at least 2.50' or a 'minimum of 2.50' is satisfied when the ratio equals or exceeds 2.50 — the phrase 'at least' is inclusive of the stated threshold. Atlas is therefore in compliance. A common error is assuming 'minimum' means the ratio must strictly exceed the stated value; in fact, absent explicit language to the contrary (e.g., 'greater than 2.50'), equaling the minimum satisfies the covenant under ASC 470-10 debt classification guidance.",
  "ExplanationWrongA": "Option A is incorrect because it misinterprets the contractual meaning of 'at least.' In both accounting practice and contract law, 'at least X' means greater than or equal to X, not strictly greater than X. A TIE of exactly 2.50 satisfies a covenant requiring a ratio of at least 2.50. The statement that standard credit agreements require strictly exceeding the minimum is not correct — if the lender intended to require exceeding 2.50, the indenture would use language such as 'greater than 2.50' or 'in excess of 2.50.'",
  "ExplanationWrongB": "Option B is incorrect on two counts. First, the TIE numerator is EBIT, not net income plus interest alone. Omitting income tax expense understates EBIT: ($600,000 + $500,000) = $1,100,000, not $1,250,000, producing a TIE of $1,100,000 / $500,000 = 2.20 rather than the correct 2.50. Second, rounding a computed ratio is not an accepted practice in covenant compliance — the ratio is reported as calculated, and 2.20 does not round to 2.50.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Option D is incorrect because it omits interest expense from the TIE numerator, computing ($600,000 + $150,000) / $500,000 = 1.50. The numerator $750,000 represents earnings before tax (EBT), not earnings before interest and tax (EBIT). The very purpose of the TIE ratio is to measure income available to cover interest — interest must be added back to the numerator because it represents the obligation being tested.",
  "FormulaReference": "Times Interest Earned",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-048",
  "Section": "A",
  "Stem": "Atlas Industries reported net income of $600,000, income tax expense of $150,000, and interest expense of $500,000 for the year. Its senior note indenture requires the times interest earned ratio to be 'at least 2.50' as a maintenance covenant. Credit analyst James Okonkwo computes the TIE and must determine whether Atlas is in compliance. Which of the following correctly resolves the compliance question?",
  "Topic": "A.048 times interest earned covenant interpretation",
  "UniqueConceptKey": "A-048-times-interest-earned-covenant-interpretation",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 842",
    "ASC 470-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "GAAP D/E: 1.20; Covenant D/E: 1.20 — both calculations are identical because the bank covenant follows GAAP recognition and measurement principles.",
    "B": "GAAP D/E: 1.20; Covenant D/E: 1.50 — ASC 842 affects only footnote disclosure and does not alter balance sheet recognition, so the covenant calculation adds back lease obligations that GAAP omits.",
    "C": "GAAP D/E: 1.50; Covenant D/E: 1.50 — ASC 842 standardizes all lease accounting, and loan agreements automatically incorporate GAAP changes under standard amendment provisions.",
    "D": "GAAP D/E: 1.50; Covenant D/E: 1.20 — ASC 842 requires operating leases to be recognized on the balance sheet as liabilities, but the loan covenant specifically excludes operating lease obligations from the D/E computation."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Assuming that loan covenant ratio definitions automatically match GAAP; failing to recognize that ASC 842 brings operating leases onto the balance sheet, increasing reported leverage",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 842, lessees must recognize a right-of-use asset and a corresponding lease liability for virtually all leases, including operating leases. Pacific's post-adoption total liabilities = $1,920,000 + $480,000 = $2,400,000, producing a GAAP D/E ratio of $2,400,000 / $1,600,000 = 1.50. However, loan covenants are contractual agreements negotiated between borrower and lender — they define financial ratios on their own terms, which may differ from GAAP. Because Pacific's covenant specifically excludes operating lease obligations, the covenant D/E ratio uses only the pre-ASC 842 liability balance: $1,920,000 / $1,600,000 = 1.20. This divergence is common in credit analysis: the lender may believe operating leases represent a lower credit risk than funded debt or may have negotiated the exclusion to avoid a technical default triggered by an accounting standards change. A credit analyst must compute both measures to assess GAAP leverage and covenant headroom separately.",
  "ExplanationWrongA": "Option A is incorrect because it assumes the bank covenant automatically mirrors GAAP. In reality, loan covenants define financial ratios using negotiated definitions that often diverge from GAAP — a practice explicitly recognized in ASC 470-10. Pacific's GAAP D/E increases from 1.20 to 1.50 upon ASC 842 adoption because operating leases become recognized liabilities. The covenant D/E remains at 1.20 because the agreement specifically excludes operating lease obligations from the definition of debt.",
  "ExplanationWrongB": "Option B is incorrect on two fronts. First, ASC 842 does alter balance sheet recognition — it requires lessees to record operating lease right-of-use assets and corresponding lease liabilities, contrary to prior GAAP which kept operating leases off-balance-sheet. Second, the covenant D/E of 1.20 is lower than the GAAP D/E of 1.50, not higher, because the covenant excludes the $480,000 in operating lease obligations that GAAP now requires to be recognized.",
  "ExplanationWrongC": "Option C is incorrect because loan covenants do not automatically incorporate GAAP changes. Lenders and borrowers negotiate covenant definitions at loan origination, and many credit agreements contain 'frozen GAAP' provisions that lock the accounting standards in effect at closing. Even without a frozen GAAP clause, Pacific's covenant explicitly excludes operating lease obligations — a definitional choice that operates independently of whether GAAP recognizes those obligations on the balance sheet.",
  "ExplanationWrongD": "",
  "FormulaReference": "Debt-to-Equity Ratio",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-049",
  "Section": "A",
  "Stem": "Pacific Logistics reported total liabilities of $1,920,000 and shareholders' equity of $1,600,000 before adopting ASC 842. The company has $480,000 in operating lease obligations that ASC 842 now requires to be recognized as lease liabilities on the balance sheet. Pacific's loan agreement with Bay Commercial Bank defines the debt-to-equity ratio to exclude operating lease obligations from total debt. Credit analyst Priya Mehta needs to compute Pacific's D/E ratio both under GAAP reporting post-ASC 842 adoption and under the bank covenant definition. Which of the following is correct?",
  "Topic": "A.049 debt-to-equity with lease adjustment",
  "UniqueConceptKey": "A-049-debt-to-equity-with-lease-adjustment",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Independent answer derived matches stored CorrectChoice",
    "Authority citation matches tested concept"
  ],
  "question_state": "Certified"
}
];
