var pack_p2_a_part20 = [
{
  "Authorities": [
    "ASC 210-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Cash ratio of 0.50 — cash plus marketable securities divided by current liabilities",
    "B": "Current ratio of 1.50 — all current assets divided by current liabilities",
    "C": "Quick ratio of 1.08 — current assets minus inventory divided by current liabilities",
    "D": "Cash-only coverage of 0.375 — cash divided by current liabilities"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Including receivables and inventory in the cash ratio",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 210-10, the balance sheet distinguishes current assets and current liabilities, and the cash ratio is the strictest measure of Flash's immediate liquidity: (Cash + Marketable Securities) / Current Liabilities = ($4.5M + $1.5M) / $12M = $6M / $12M = 0.50. The ratio answers the credit committee's question directly — every dollar of near-term obligations is backed by 50 cents of instantly spendable resources — because it excludes receivables, inventory, and prepaids that must still convert to cash. For Flash, a 0.50 cash ratio signals thin same-week liquidity, so the bank will likely attach a covenant floor before extending the $40M line. A common exam trap is reporting the current ratio (1.50) or the quick ratio (1.08) when the question demands the strictest test; the distinguishing feature is which assets the numerator admits.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "1.50 is the current ratio: all current assets ($18M, including receivables, inventory, and prepaids) divided by current liabilities of $12M. The cash ratio excludes those slower-to-convert assets — the committee asked for the strictest measure of Flash's liquidity, so including them overstates the company's ability to meet near-term claims.",
  "ExplanationWrongC": "1.08 is the quick ratio, which excludes inventory but still includes accounts receivable and prepaid expenses. Receivables are not yet cash — Flash's committee is testing same-week debt-service capacity — so requiring only cash and marketable securities in the numerator makes 0.50 the correct strictest measure, not 1.08.",
  "ExplanationWrongD": "0.375 divides cash alone ($4.5M) by current liabilities, omitting the $1.5M in marketable securities that can be converted to cash immediately. Because the cash ratio expressly includes marketable securities, this understates Flash's true immediate liquidity and is not the ratio the committee requested.",
  "FormulaReference": "Cash ratio = (Cash + Marketable Securities) / Current Liabilities (FA-03)",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-161",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, is negotiating a $40M revolving credit line. The bank's credit committee requires the strictest possible measure of Flash's immediate liquidity before approving the facility. Flash reports cash of $4.5M, marketable securities of $1.5M, accounts receivable of $6M, inventory of $5M, prepaid expenses of $1M, and current liabilities of $12M. Which ratio should Sharma present to the committee, and at what value?",
  "Topic": "A.161 Cash ratio — strictest liquidity measure",
  "UniqueConceptKey": "A-161-cash-ratio",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: (4.5+1.5)/12 = 0.50; quick 13/12 = 1.08; current 18/12 = 1.50; cash-only 0.375",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 330-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Turnover of 4.09 times and DIO of 89 days",
    "B": "Turnover of 5.00 times and DIO of 73 days",
    "C": "Turnover of 6.00 times and DIO of 61 days",
    "D": "Turnover of 5.00 times and DIO of 72 days"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using ending inventory or sales instead of COGS and average inventory",
  "CorrectChoice": "B",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 330-10, inventory is measured at cost, and holding efficiency is evaluated through turnover: COGS / Average Inventory = $900M / (($140M + $220M) / 2) = $900M / $180M = 5.0 times. Days inventory outstanding = 365 / 5.0 = 73 days. The 73 days tell Flash's CFO that inventory turns over every 73 days on average, so the production team can benchmark against the industry norm and measure whether the new kanban program shortened the holding period. Average inventory is the required base because a single year-end snapshot ignores seasonal build-ups. A common exam trap is using ending inventory only (4.09 turns, 89 days) or dividing sales instead of COGS by average inventory (6.0 turns, 61 days); either error flatters or distorts Flash's holding efficiency.",
  "ExplanationWrongA": "A turnover of 4.09 divides COGS by ending inventory ($900M / $220M) instead of average inventory; the same error drives DIO to 89 days. Beginning inventory of $140M must be averaged with the ending balance — using only the year-end figure overstates Flash's inventory holding period and misstates the kanban program's effect.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "A turnover of 6.00 divides sales of $1,080M by average inventory, but inventory turnover must use cost of goods sold, not revenue. Sales include the gross margin that never sits in inventory, which inflates the turnover figure and deflates DIO to 61 days for Flash.",
  "ExplanationWrongD": "Turnover of 5.00 is correct, but 72 days uses a 360-day banker's year. The standard convention for days inventory outstanding is 365 days: 365 / 5.0 = 73 days. The 360-day shortcut understates Flash's true holding period by one full day.",
  "FormulaReference": "Inventory turnover = COGS / Average Inventory; DIO = 365 / Turnover (FA-04)",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-162",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, is evaluating the new kanban inventory program against last year's performance. Flash's controller reports beginning inventory of $140M and ending inventory of $220M, with cost of goods sold of $900M and sales of $1,080M. What inventory turnover and days inventory outstanding should the CFO use to benchmark Flash's holding efficiency?",
  "Topic": "A.162 Inventory turnover and days inventory outstanding",
  "UniqueConceptKey": "A-162-inventory-turnover-dio",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: avg inv 180; 900/180 = 5.0; DIO 365/5 = 73; ending 4.09/89; sales 6.0/61",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 310-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "60 days — ending receivables divided by credit sales, annualized",
    "B": "40 days — beginning receivables divided by credit sales, annualized",
    "C": "50 days — average receivables divided by credit sales, annualized",
    "D": "13.7% — average receivables as a percentage of credit sales"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using ending receivables or omitting the ×365 conversion",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 310-10, receivables are reported at net realizable value, and days sales outstanding converts the receivable balance into a collection period: Average AR / Credit Sales x 365 = (($80M + $120M) / 2) / $730M x 365 = $100M / $730M x 365 = 50 days. The 50 days means Flash collects an average credit sale within 50 days, and credit analyst Marcus Webb can now compare that to the 45-day terms Flash grants customers: the 5-day slippage signals collections need monitoring — or that the new customer financing terms are stretching payments. DSO uses average receivables because beginning and ending balances average out intra-year spikes. A common exam trap is using ending receivables only (60 days) or expressing the ratio as a percentage of sales without the ×365 conversion (13.7%); both misstate Flash's true collection period.",
  "ExplanationWrongA": "60 days divides ending receivables ($120M) by credit sales and multiplies by 365, ignoring the beginning balance of $80M. DSO must use average receivables — Flash's average is $100M — so the year-end balance overstates the collection period and would wrongly suggest Flash is missing its 45-day terms by more than it is.",
  "ExplanationWrongB": "40 days uses beginning receivables of $80M, which reflects last year's collection behavior rather than this year's. DSO requires average receivables of $100M: $100M / $730M x 365 = 50 days. A single opening snapshot understates Flash's collection period and hides the slippage versus the 45-day terms.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "13.7% is $100M / $730M without the days conversion — a percentage of sales, not a collection period. The DSO formula multiplies the ratio by 365 to annualize it: $100M / $730M x 365 = 50 days. Reporting 13.7% answers a different question and cannot be compared against Flash's 45-day terms.",
  "FormulaReference": "DSO = Average AR / Credit Sales x 365 (FA-05)",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-163",
  "Section": "A",
  "Stem": "Flash Manufacturing's credit analyst, Marcus Webb, is reviewing whether Flash's collections are keeping pace with the 45-day terms Flash grants customers. Credit sales for the year were $730M; accounts receivable were $80M at the start of the year and $120M at year-end. What days sales outstanding should Webb compute to assess the collection period?",
  "Topic": "A.163 Days sales outstanding — receivables collection",
  "UniqueConceptKey": "A-163-days-sales-outstanding",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: avg AR 100; 100/730×365 = 50; ending 60; beginning 40; no-×365 13.7%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 405-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "30 days",
    "B": "40 days",
    "C": "32 days",
    "D": "50 days"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Substituting COGS for purchases or skipping the average in DPO",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Days payable outstanding measures how long Flash takes to pay its suppliers: Average AP / Purchases x 365 = (($60M + $100M) / 2) / $730M x 365 = $80M / $730M x 365 = 40 days. The 40 days means Flash holds payables for 40 days on average, and VP Finance Sofia Alvarez can now weigh the supplier's 2% early-payment discount against the cost of stretching the payable: at Flash's 8% borrowing rate, taking the 2% discount is cheaper than financing the payable for the full 40 days, because the annualized cost of forgoing the discount far exceeds the borrowing cost. The denominator is purchases, not COGS, because accounts payable arise from inventory purchases. A common exam trap is substituting cost of goods sold for purchases or using ending payables without averaging.",
  "ExplanationWrongA": "30 days divides beginning payables of $60M by purchases, capturing last year's payables policy rather than this year's. DPO uses average accounts payable — $80M here — so the correct figure is 40 days, and Alvarez's discount decision would be distorted by the understated stretch.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "32 days substitutes cost of goods sold ($900M) for purchases ($730M) in the denominator. Payables arise from inventory purchases, not from all goods sold — purchases and COGS differ here because inventory levels change — so substituting COGS distorts the payables period; the correct figure is 40 days, not 32.",
  "ExplanationWrongD": "50 days uses ending payables of $100M without averaging against the $60M beginning balance. Payables fluctuate through the year; the standard formula requires average payables ($80M), which yields 80 / 730 x 365 = 40 days for Flash and a materially different picture of the payables stretch.",
  "FormulaReference": "DPO = Average AP / Purchases x 365 (FA-06)",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-164",
  "Section": "A",
  "Stem": "Flash Manufacturing's VP Finance, Sofia Alvarez, is reviewing supplier payment terms before deciding whether to take a 2% early-payment discount. Flash purchased $730M of materials during the year; accounts payable were $60M at the start and $100M at year-end, and cost of goods sold was $900M. What days payable outstanding should Alvarez use to evaluate the payables stretch?",
  "Topic": "A.164 Days payable outstanding",
  "UniqueConceptKey": "A-164-days-payable-outstanding",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: avg AP 80; 80/730×365 = 40; beginning 30; COGS 32.4; ending 50",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 470-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "1.50 — Flash is more leveraged than the 1.25 industry average, so the bond issue will push leverage further above the norm",
    "B": "0.60 — Flash carries less debt than the industry average and can issue the bonds comfortably",
    "C": "0.40 — Flash's equity finances most of its assets, so the bond issue is easily absorbed",
    "D": "2.50 — Flash's equity multiplier shows it can support additional borrowing"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using the debt ratio or equity multiplier instead of debt-to-equity",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 470-10, debt is a liability claim that stands ahead of equity, and debt-to-equity compares creditor financing to owner financing: Total Liabilities / Total Equity = $720M / $480M = 1.50. Flash carries $1.50 of debt for every $1.00 of equity, and CFO Priya Sharma must weigh the proposed $150M bond issue against the 1.25 industry average: each additional dollar of debt pushes the ratio further above the peer norm, raising the cost of future borrowing and tightening covenant headroom. The ratio is computed on total liabilities — current and long-term — because all creditor claims rank ahead of equity. A common exam trap is computing the debt ratio (liabilities / assets = 0.60), the equity ratio (equity / assets = 0.40), or the equity multiplier (assets / equity = 2.50); each measures a related but different balance-sheet relationship.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "0.60 is the debt ratio — total liabilities divided by total assets ($720M / $1,200M). Debt-to-equity divides by shareholders' equity instead: $720M / $480M = 1.50. The two ratios describe different proportions of Flash's balance sheet, and only the 1.50 comparison against the 1.25 industry average is relevant to the board memo.",
  "ExplanationWrongC": "0.40 is the equity ratio — total equity divided by total assets. Debt-to-equity compares liabilities to equity, not to assets: $720M / $480M = 1.50. Reporting the equity ratio answers how much of Flash's assets are owner-financed, not how creditor financing compares with owner financing.",
  "ExplanationWrongD": "2.50 is the equity multiplier — total assets divided by total equity ($1,200M / $480M). Debt-to-equity uses total liabilities as the numerator: $720M / $480M = 1.50. The multiplier captures the assets supported per dollar of equity — a related leverage measure, but the board memo requires the debt-to-equity ratio.",
  "FormulaReference": "Debt-to-equity = Total Liabilities / Total Equity (FA-07)",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-165",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, is preparing the board memo supporting a $150M bond issue. Flash reports total assets of $1,200M, total liabilities of $720M, and total equity of $480M. The industry average debt-to-equity ratio is 1.25. What is Flash's current debt-to-equity ratio, and what does the comparison indicate?",
  "Topic": "A.165 Debt-to-equity ratio and financial leverage",
  "UniqueConceptKey": "A-165-debt-to-equity",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 720/480 = 1.50; debt ratio 0.60; equity ratio 0.40; EM 2.50",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 470-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "3.0 — met, since net income plus interest covers the charge exactly at the covenant level",
    "B": "2.0 — not met, because net income alone covers interest only twice",
    "C": "0.25 — not met, because interest expense is four times EBIT",
    "D": "4.0 — met with margin, since EBIT covers the interest charge four times"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using net income instead of EBIT in the coverage numerator",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Times interest earned measures how many times earnings before interest and taxes cover the interest charge: EBIT / Interest Expense = $48M / $12M = 4.0. Flash's earnings cover its interest obligations four times over, and the lender's 3.0 covenant is comfortably met — but CFO Priya Sharma should note coverage is thinner than the 5.2x of prior years, so the refinancing plan must not add interest that pushes the ratio below the covenant. EBIT is the correct numerator because interest is paid from earnings before the interest charge itself is deducted, and taxes are computed after it. A common exam trap is using net income in the numerator (24 / 12 = 2.0), net income plus interest (36 / 12 = 3.0), or inverting the ratio (12 / 48 = 0.25); each misstates Flash's real debt-servicing capacity.",
  "ExplanationWrongA": "3.0 divides net income plus interest ($36M) by interest expense — a coverage variant some lenders use. The times-interest-earned ratio must use EBIT of $48M, because interest is paid out of earnings before the interest charge and before taxes; $48M / $12M = 4.0 is Flash's true coverage.",
  "ExplanationWrongB": "2.0 divides net income ($24M) alone by interest expense. Net income already has interest and taxes removed, so it understates the earnings available to service debt. EBIT of $48M / $12M = 4.0 measures Flash's actual coverage and satisfies the 3.0 covenant.",
  "ExplanationWrongC": "0.25 inverts the ratio — interest expense divided by EBIT. TIE expresses how many times EBIT covers interest, so the earnings figure must be the numerator: $48M / $12M = 4.0. The inverted number is a burden measure, not the coverage ratio the covenant requires.",
  "ExplanationWrongD": "",
  "FormulaReference": "TIE = EBIT / Interest Expense (FA-08)",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-166",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, must certify Flash's compliance with a lending covenant requiring times interest earned of at least 3.0. Flash reports EBIT of $48M, interest expense of $12M, income taxes of $12M, and net income of $24M. What is Flash's times interest earned ratio, and is the covenant met?",
  "Topic": "A.166 Times interest earned — interest coverage",
  "UniqueConceptKey": "A-166-times-interest-earned",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 48/12 = 4.0; (24+12)/12 = 3.0; 24/12 = 2.0; 12/48 = 0.25",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 205-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Net profit margin",
    "B": "Operating margin",
    "C": "Gross margin percentage",
    "D": "Contribution margin ratio"
  },
  "CognitiveLevel": "Remember",
  "CommonTrapReference": "Confusing gross margin with operating or contribution margin",
  "CorrectChoice": "C",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Gross margin percentage is (Sales - COGS) / Sales, expressing the portion of each sales dollar retained after the cost of goods sold is deducted. On Flash's income statement, cost of goods sold is the first expense deducted, and the remainder is gross profit; the gross margin percentage is that remainder stated per dollar of sales. It differs from operating margin, which also deducts operating expenses, and from net profit margin, which deducts all expenses including interest and taxes. The definition-match structure of this item is deliberate: the task is to identify which margin corresponds to the (Sales - COGS) / Sales computation under ASC 205-10 presentation.",
  "ExplanationWrongA": "Net profit margin divides net income by sales, so it reflects all expenses — operating costs, interest, and taxes. The computation described stops at cost of goods sold, which makes net profit margin a broader, later-stage profitability measure than the gross margin percentage the controller needs.",
  "ExplanationWrongB": "Operating margin uses operating income (EBIT) as the numerator — earnings after operating expenses but before interest and taxes. The description specifies subtracting only cost of goods sold, which is the gross margin computation, not the operating margin one.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Contribution margin ratio divides sales minus variable costs by sales. Variable costs include selling and administrative costs beyond goods sold, so the contribution margin ratio is a managerial-accounting measure rather than the financial-statement ratio the controller must report in the MD&A.",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-167",
  "Section": "A",
  "Stem": "Flash Manufacturing's controller, Dan Okafor, is preparing the quarterly MD&A and needs to report the ratio that measures the percentage of each sales dollar retained after the cost of goods sold is deducted. Flash's income statement shows sales of $1,080M and cost of goods sold of $900M. Which ratio answers Okafor's question?",
  "Topic": "A.167 Gross margin percentage definition",
  "UniqueConceptKey": "A-167-gross-margin-percentage",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: definition item — gross margin = (Sales - COGS) / Sales",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "Financial statement analysis principles — ratio decomposition"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "ROA is 9% (6% margin x 1.5 turnover), and the gap versus the benchmark is driven by asset turnover — Flash must reach 2.0x to match the industry at its current margin",
    "B": "ROA is 10%, computed on beginning total assets, which is the correct base for the industry comparison",
    "C": "ROA is 8.18%, computed on ending total assets, and the shortfall is driven by Flash's profit margin",
    "D": "ROA is 6%, the same as Flash's profit margin, since asset turnover of 1.5 is below the industry norm"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Computing ROA on a single asset balance instead of the average",
  "CorrectChoice": "A",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Return on assets = Net Income / Average Total Assets = $54M / $600M = 9%, which decomposes into profit margin x asset turnover: 6% x 1.5 = 9%. The decomposition shows Flash's shortfall versus the 12% industry benchmark is driven by asset utilization, not margins: Flash's 6% margin equals the industry norm, but its 1.5x turnover must rise to 2.0x (12% / 6%) to close the gap. CFO Priya Sharma should therefore focus on inventory and receivables intensity — the same working-capital lines flagged in the DSO and DIO analyses — rather than pricing, since margin is already at parity with the industry. Average total assets is the required base because Flash's asset base grew during the year. A common exam trap is computing ROA on ending assets (8.18%) or beginning assets (10%); the decomposition then misattributes the gap to the wrong driver.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "10% divides net income by beginning total assets only ($54M / $540M). ROA requires average total assets — $600M here — so the correct result is 9%. A single opening snapshot ignores the capital Flash deployed during the year and would mislead the board about the size of the gap.",
  "ExplanationWrongC": "8.18% divides net income by ending total assets ($54M / $660M). ROA uses average total assets of $600M, yielding 54 / 600 = 9%. The year-end base overstates Flash's asset base, understates the return, and misattributes the shortfall to margin when turnover is the actual driver.",
  "ExplanationWrongD": "6% is Flash's profit margin — net income divided by sales — not return on assets. ROA decomposes into margin x turnover: 6% x 1.5 = 9%. Stopping at the margin ignores the 1.5x turnover Flash earns on its asset base and gives the board no decomposition of the gap.",
  "FormulaReference": "ROA = Net Income / Average Total Assets = Profit Margin x Asset Turnover (FA-12)",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-168",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, is explaining to the board why Flash's return on assets lags the 12% industry benchmark. Flash reports net income of $54M on sales of $900M; total assets were $540M at the start of the year and $660M at year-end. The industry profit margin is 6%. Which analysis should Sharma present?",
  "Topic": "A.168 Return on assets — decomposition into margin and turnover",
  "UniqueConceptKey": "A-168-return-on-assets-decomposition",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: avg assets 600; 54/600 = 9% = 6% x 1.5; turnover to match 12% = 2.0; ending 8.18%; beginning 10%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 505-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "ROE is 7.5%, and the shortfall is driven by insufficient asset turnover",
    "B": "ROE is 15% (5% margin x 1.5 turnover x 2.0 leverage), and the gap traces to Flash's 5% margin versus the 8% peer norm — margin recovery, not more leverage, is the lever",
    "C": "ROE is 10%, and the gap is driven by Flash's equity multiplier",
    "D": "ROE is 22.5%, computed on ending equity, so Flash's leverage explains its outperformance"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Omitting a DuPont component or using ending equity in the multiplier",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "DuPont ROE = Net Profit Margin x Asset Turnover x Equity Multiplier = ($36M / $720M) x ($720M / $480M) x ($480M / $240M) = 5% x 1.5 x 2.0 = 15%, which reconciles with net income / average equity = $36M / $240M = 15%. The decomposition isolates the driver: Flash's margin (5%) trails the 8% peer norm, while its turnover (1.5x) and leverage (2.0x) are in line. CFO Priya Sharma's conclusion is that the ROE gap traces to pricing and cost control, not to asset efficiency or capital structure — the strategic lever is margin recovery, and mechanically raising leverage to compensate would violate the debt covenant. A common exam trap is omitting one DuPont component (7.5% or 10%) or using ending equity in the multiplier (22.5%), which misattributes the gap to leverage rather than margin.",
  "ExplanationWrongA": "7.5% multiplies net profit margin by asset turnover only (5% x 1.5), omitting the equity multiplier. Flash's equity multiplier of 2.0 is what converts return on assets into return on equity; without it the calculation yields the ROA, not the 15% ROE the board is benchmarking.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "10% multiplies net profit margin by the equity multiplier (5% x 2.0) but omits asset turnover. The DuPont identity requires all three components — margin, turnover, and leverage: 5% x 1.5 x 2.0 = 15%. Dropping turnover severs the link to Flash's sales-generating efficiency and misstates the driver analysis.",
  "ExplanationWrongD": "22.5% computes the equity multiplier from ending equity ($480M / $160M = 3.0) instead of average equity. DuPont ROE uses average equity — $240M here — giving a multiplier of 2.0 and ROE of 15%. The year-end equity figure is depressed by the large dividend paid during the year.",
  "FormulaReference": "DuPont ROE = Net Profit Margin x Asset Turnover x Equity Multiplier (FA-14)",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-169",
  "Section": "A",
  "Stem": "Flash Manufacturing's CFO, Priya Sharma, is analyzing why Flash's return on equity trails the 18% peer average. Flash reports net income of $36M on sales of $720M; average total assets were $480M and average equity was $240M (equity was $320M at the start and $160M at year-end after a large dividend). The peer average net margin is 8%. Which conclusion should Sharma draw from the DuPont decomposition?",
  "Topic": "A.169 DuPont ROE decomposition",
  "UniqueConceptKey": "A-169-dupont-roe",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: 5% x 1.5 x 2.0 = 15%; omitting EM 7.5%; omitting turnover 10%; ending-equity EM 3.0 → 22.5%",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 260-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$2.50",
    "B": "$3.00",
    "C": "$1.93",
    "D": "$2.25"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Forgetting preferred dividends or share weighting in basic EPS",
  "CorrectChoice": "D",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 260-10, basic EPS = (Net Income - Preferred Dividends) / Weighted Average Common Shares = ($60M - $6M) / (20M + 8M x 6/12) = $54M / 24M = $2.25. The $2.25 is the per-share claim of common shareholders — the base the controller will use for the price-to-earnings table in the board package — and the mid-year issuance must be weighted by months outstanding, which is why the 8M shares add only 4M to the weighted count. Preferred dividends are deducted because preferred claims rank ahead of common. A common exam trap is omitting preferred dividends ($2.50), ignoring the mid-year weighting ($3.00), or using the full ending share count ($1.93); each distorts Flash's per-share earnings.",
  "ExplanationWrongA": "$2.50 divides net income ($60M) by 24M weighted shares without first deducting preferred dividends. Basic EPS belongs to common shareholders only: ($60M - $6M) / 24M = $2.25. Including the preferred claim overstates Flash's per-common-share earnings and would misstate the report.",
  "ExplanationWrongB": "$3.00 divides $60M by 20M shares — the count at the start of the year. The 8M shares issued July 1 were outstanding for half the year, so the weighted average is 20M + 8M x 6/12 = 24M shares; the correct EPS is $2.25, and ignoring the issuance overstates earnings per share by one-third.",
  "ExplanationWrongC": "$1.93 divides $54M by 28M shares — the full ending share count. Shares issued mid-year must be weighted by the months outstanding (8M x 6/12 = 4M), giving 24M weighted shares and EPS of $2.25 for Flash; the unweighted denominator understates earnings per share.",
  "ExplanationWrongD": "",
  "FormulaReference": "EPS = (Net Income - Preferred Dividends) / Weighted Average Shares (FA-15)",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-170",
  "Section": "A",
  "Stem": "Flash Manufacturing's controller, Dan Okafor, is computing basic earnings per share for the board package. Flash earned net income of $60M and paid $6M in preferred dividends; 20M common shares were outstanding at the start of the year, and 8M additional shares were issued on July 1. What basic EPS should Okafor report?",
  "Topic": "A.170 Earnings per share — basic computation",
  "UniqueConceptKey": "A-170-basic-eps",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: wtd 20 + 8×6/12 = 24; (60−6)/24 = $2.25; no-pref-div 2.50; 60/20 = 3.00; 54/28 = 1.93",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
},
{
  "Authorities": [
    "ASC 260-10"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Flash is the cheaper stock, because the higher multiple means investors pay less per share",
    "B": "The market expects Flash's earnings to grow faster than the peer's — the premium is justified only if that growth materializes",
    "C": "Flash's earnings are undervalued, because the market assigns them a premium multiple",
    "D": "Flash must pay a higher dividend than the peer, since its P/E is higher"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Reading a high P/E as cheaper or confusing P/E with dividend yield",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "P/E = Market Price / EPS, and a higher multiple means the market pays more for each dollar of current earnings. Flash's 18x versus the peer's 12x signals that investors expect Flash's earnings to grow faster — a premium justified only if future earnings deliver. The analyst's job is to test that expectation against Flash's sustainable growth rate and the durability of its margins: if the growth never materializes, the premium compresses and the stock falls to a peer-like multiple. A common exam trap is reading the higher multiple as 'cheaper' or confusing P/E with dividend yield; the multiple is a price the market is willing to pay, not a verdict on value, and it says nothing about Flash's payout policy.",
  "ExplanationWrongA": "A higher P/E means the market pays more per dollar of current earnings, which is the opposite of cheaper. Flash at 18x costs more than the peer at 12x for every dollar of earnings, so the comparison signals a premium price, not a bargain, and would mislead the client about relative value.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Calling Flash undervalued inverts the signal: a P/E of 18x is a high multiple, so the market is paying up for Flash's earnings. Higher multiples are only justified if future earnings growth delivers — labeling the premium 'undervaluation' mistakes the market's willingness to pay for evidence of cheapness.",
  "ExplanationWrongD": "Price-to-earnings measures the price per dollar of earnings; dividends appear in dividend yield, a different ratio. A high P/E says nothing about payout policy — a firm can carry a high multiple while paying a minimal dividend, and Flash's reinvestment strategy is exactly that case.",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-171",
  "Section": "A",
  "Stem": "Equity analyst Nina Patel is screening Flash Manufacturing for a value-focused client. Flash trades at 18 times trailing earnings, while its closest peer trades at 12 times. Both firms have similar dividend yields. What should Patel conclude from the P/E comparison?",
  "Topic": "A.171 Price-to-earnings ratio interpretation",
  "UniqueConceptKey": "A-171-price-earnings-ratio",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: conceptual — P/E = price/EPS; higher P/E → higher expected growth",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified",
  "certification_session": "P2-060"
}
];
