var pack_p2_a_part31 = [
{
  "Authorities": [
    "US GAAP intangible asset accounting (ASC 350 internally developed intangibles expensed as incurred)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The gap reflects a near-term takeover premium that the market is pricing in with certainty ahead of an expected bidding process.",
    "B": "The gap proves Flash's recorded assets are carried above fair value and will require impairment charges to close the distance to market.",
    "C": "Book value and market price converge once dividends are reinvested over time, so the persistent gap is timing noise rather than information.",
    "D": "Book value omits internally generated intangibles such as brand equity, engineering know-how, and customer relationships, which GAAP expenses as incurred, so the market price capitalizes earning power the balance sheet does not record."
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Reading a high market-to-book multiple as evidence of overstated assets",
  "CorrectChoice": "D",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Market-to-book gaps persist when economically valuable resources never enter the balance sheet. GAAP expenses internally developed brands, accumulated engineering know-how, trained teams, and customer relationships as incurred, so Flash's book value of $12.40 per share captures mainly tangible, purchased, or acquired assets, while the $58.00 price capitalizes the future earnings those unrecorded intangibles generate. The multiple therefore usually signals unrecorded value creation rather than inflated carrying values. Business interpretation: Rajan Mehta can explain to shareholders that book value is a conservative floor assembled under historical-cost rules, not a ceiling on what the business is worth. Common trap: reading a high market-to-book ratio as evidence of aggressive asset values awaiting impairment.",
  "ExplanationWrongA": "Choice A hard-codes a takeover outcome; premiums may explain part of any share price, but the durable structural gap between $12.40 book and $58.00 market requires no deal to justify, and anticipated deals are never certain events.",
  "ExplanationWrongB": "Choice B inverts the accounting logic; overstatement would imply assets carried above recoverable amounts, yet the standard explanation runs the other way, through omission of unrecorded intangible value rather than inflation of recorded balances.",
  "ExplanationWrongC": "Choice C invents a dividend-reinvestment convergence that no valuation principle supports; reinvesting dividends compounds investor wealth but never forces market price onto historical-cost book value at any horizon.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-18 Book Value per Share",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-276",
  "Section": "A",
  "Stem": "At the annual meeting, board member Rajan Mehta observes that Flash's book value per share stands at $12.40 while the shares trade at $58.00 and asks for the most reasonable reading of the persistent gap. Which explanation should the board adopt?",
  "Topic": "A.276 bvps-unrecorded-intangibles",
  "UniqueConceptKey": "A-276-gap-explains-omission",
  "VerifiedChecks": [
    "Valuation logic check: BVPS $12.40 vs price $58.00 implies market/book = 58/12.4 = 4.68 attributable to unrecorded intangibles",
    "Concept verified against ASC 350 internal-intangible expensing; no further arithmetic required",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Management accounting practice (multi-line common-size balance sheet interpretation)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Flash deleveraged during the period, evidenced by the long-term debt share easing six points from 28% to 22% of total assets.",
    "B": "Flash's equity cushion strengthened relative to creditor claims, positioning the company for expanded borrowing capacity ahead.",
    "C": "Asset mix shifted toward inventory while funding migrated to short-term sources, since payables plus short-term borrowings added twelve combined points even as long-term debt and equity shares contracted, raising rollover risk if inventory slows.",
    "D": "Cash generation strengthened operationally, leaving Flash better placed than last year to absorb demand or funding shocks."
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Judging leverage from the long-term debt line alone in a common-size series",
  "CorrectChoice": "C",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "Reading the common-size columns jointly reveals a coordinated shift. Assets: inventory climbed from 22% to 31% of total assets while cash thinned from 8% to 3%, so the balance sheet bulked up in its least liquid current asset. Financing mirrored the move: accounts payable rose from 12% to 17% and short-term borrowings from 5% to 12%, together supplying twelve points of new weight, while long-term debt fell to 22% and equity narrowed to 46%. Flash has been funding an inventory accumulation with the shortest-maturity liabilities available. Business interpretation: Marisol Vega should brief the audit committee on rollover risk, because the strategy survives only while inventory converts on schedule and a demand stall would strand short-term claims against slow stock. Common trap: declaring deleveraging from the falling long-term-debt line alone.",
  "ExplanationWrongA": "Choice A celebrates the six-point drop in long-term debt as deleveraging; total leverage actually rose once the eleven combined points added to payables and short-term borrowings are counted, and the liability profile shortened in maturity besides.",
  "ExplanationWrongB": "Choice B claims the equity cushion strengthened; equity's common-size weight fell from 55% to 46%, the opposite direction, absorbed by the expansion in payables and short-term borrowings that choice C identifies.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D cites operational cash strength, yet cash fell from 8% to 3% of total assets; that decline alongside swelling inventory is itself part of the warning pattern, not evidence of a stronger shock-absorber.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-277",
  "Section": "A",
  "Stem": "Briefing the audit committee, CFO Marisol Vega walks through Flash's common-size balance sheets. From last year to this year: cash slipped from 8% to 3% of total assets; inventory swelled from 22% to 31%; accounts payable climbed from 12% to 17%; short-term borrowings jumped from 5% to 12%; long-term debt eased from 28% to 22%; and total equity narrowed from 55% to 46%. Which conclusion is best supported?",
  "Topic": "A.277 commonsize-liability-shift",
  "UniqueConceptKey": "A-277-short-term-migration-read",
  "VerifiedChecks": [
    "Composition check: payables +5 pp plus short-term borrowings +7 pp = +12 pp versus LT debt -6 pp and equity -9 pp",
    "Asset-side check: inventory +9 pp against cash -5 pp confirms mix shift toward less liquid current assets",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (dividend yield versus payout ratio; spot versus forward yield distinctions)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "3.00%",
    "B": "3.45%",
    "C": "3.30%",
    "D": "50.00%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Substituting payout ratio, cost basis, or forward dividends into current yield",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Dividend yield relates the cash distribution to the price an investor pays in the market today: yield = annual dividends per share / current market price = $1.38 / $46.00 = 3.00%. The measure is keyed to prevailing price; the payout ratio (dividends / EPS = $1.38 / $2.76 = 50.00%) belongs to distribution-policy analysis, and a buyer's original cost fixes personal return history rather than the security's quoted yield. Business interpretation: Felix Nowak should quote 3.00% to income clients evaluating Flash at today's quote and disclose separately that management's signaled $1.52 implies a forward figure of $1.52 / $46.00 = 3.30%. Common trap: substituting payout ratio, cost basis, or next-year dividends into the spot-yield formula.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B computes $1.38 / $40.00 = 3.45% off the client's purchase price; cost basis shapes that holder's personal yield-on-cost but not Flash's current quoted yield at the $46.00 market price.",
  "ExplanationWrongC": "Choice C projects $1.52 / $46.00 = 3.30% using next year's signaled dividend; a forward yield is a distinct disclosure, and presenting it as today's yield overstates current income by thirty basis points.",
  "ExplanationWrongD": "Choice D reports 50.00%, which is the payout ratio ($1.38 / $2.76); it measures the share of earnings distributed and says nothing about the return a purchaser earns per dollar of stock price.",
  "FormulaReference": "FA-17 Dividend Yield",
  "ItemStyle": "single-select",
  "LOSTag": "A.9",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-278",
  "Section": "A",
  "Stem": "Refreshing coverage for income-focused clients, equity research associate Felix Nowak notes Flash pays an annual dividend of $1.38 per share on EPS of $2.76, with the stock quoted at $46.00; management has signaled next year's dividend of $1.52. One client bought at $40.00. What current dividend yield should Felix quote?",
  "Topic": "A.278 dividend-yield-spot",
  "UniqueConceptKey": "A-278-spot-price-yield-keying",
  "VerifiedChecks": [
    "Recomputed: 1.38/46 = 0.0300 = 3.00%",
    "Distractor checks: 1.38/40 = 3.45%; 1.52/46 = 3.30%; 1.38/2.76 = 50.00%",
    "Second pass: 3.00% x 46 = 1.38 reproduces the declared dividend (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (return on common equity; preferred deduction and average equity conventions)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "24.13%",
    "B": "22.50%",
    "C": "20.22%",
    "D": "12.00%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Skipping the preferred-dividend deduction or anchoring on year-end equity",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Return on equity measures profit generated on common shareholders' capital: ROE = (net income - preferred dividends) / average common equity = ($3,860,000 - $260,000) / (($14,200,000 + $17,800,000) / 2) = $3,600,000 / $16,000,000 = 22.50%. Deducting preferred dividends reserves earnings for the residual claimants, and averaging equity matches the year's earnings to the capital actually in place across the period rather than at one snapshot date. Business interpretation: Yusuf Demirci can quote 22.50% to the lender as Flash's clean common-equity productivity, comfortably inside the benchmark band the credit memo cites. Common trap: skipping the preferred deduction or anchoring the denominator on year-end equity after capital was raised late in the year.",
  "ExplanationWrongA": "Choice A skips the preferred-dividend deduction and reports $3,860,000 / $16,000,000 = 24.13%, crediting common shareholders with income contractually promised first to the preferred holders.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C anchors on year-end common equity of $17,800,000 for 20.22%; late-year equity growth depresses the snapshot without reflecting the smaller base that actually earned most of the year's income.",
  "ExplanationWrongD": "Choice D slides to return on assets, $3,600,000 / $30,000,000 average total assets = 12.00%; total assets include creditor-financed capacity, so the figure answers a different question than common-equity productivity.",
  "FormulaReference": "FA-13 Return on Equity",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-279",
  "Section": "A",
  "Stem": "Responding to a lender analytics request, controller Yusuf Demirci refines Flash's return on equity. Net income was $3,860,000, preferred dividends were $260,000, common equity was $14,200,000 at the start and $17,800,000 at the end, and average total assets were $30,000,000. What ROE should Yusuf report on common equity?",
  "Topic": "A.279 roe-common-refinement",
  "UniqueConceptKey": "A-279-preferred-and-average-equity",
  "VerifiedChecks": [
    "Recomputed: 3860000 - 260000 = 3600000; (14200000 + 17800000)/2 = 16000000; 3600000/16000000 = 22.50%",
    "Second pass: 22.50% x 16000000 = 3600000 reproduces income to common (agrees)",
    "Distractor checks: 3860000/16000000 = 24.13%; 3600000/17800000 = 20.22%; 3600000/30000000 = 12.00%",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "US GAAP equity presentation (ASC 505 preferred equity attribution; treasury share exclusion)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "$13.80",
    "B": "$12.19",
    "C": "$26.00",
    "D": "$13.00"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Omitting the preferred-equity deduction or the treasury-share exclusion",
  "CorrectChoice": "D",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Book value per share divides equity attributable to common shareholders by shares outstanding. Common equity = $20,700,000 total equity - $1,200,000 preferred = $19,500,000. Outstanding shares = 1,600,000 issued - 100,000 treasury = 1,500,000. BVPS = $19,500,000 / 1,500,000 = $13.00. Preferred is deducted because BVPS is a common-shareholder measure, and treasury shares are excluded because they hold no claim on assets or earnings. Business interpretation: Naomi Castellanos can frame the $26.00 market price as exactly 2.0 times book ($26.00 / $13.00), letting the client weigh Flash's unrecorded intangible value against its historical-cost net worth per share. Common trap: forgetting the preferred deduction or the treasury-share exclusion before dividing.",
  "ExplanationWrongA": "Choice A divides total equity of $20,700,000 by 1,500,000 outstanding shares for $13.80; leaving preferred capital in the numerator assigns a common-shareholder metric to capital carrying senior claims ahead of the client's shares.",
  "ExplanationWrongB": "Choice B divides common equity by the 1,600,000 issued shares for $12.19; the 100,000 treasury shares Flash holds earn nothing and bear no claims, so outstanding shares, not issued shares, belong in the denominator.",
  "ExplanationWrongC": "Choice C substitutes the $26.00 market price for book value per share; market price embeds expectations about future earnings and growth, while the question asks for the historical-cost residual attributable to each outstanding common share.",
  "ExplanationWrongD": "",
  "FormulaReference": "FA-18 Book Value per Share",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "question_state": "Certified",
  "QuestionID": "P2-A-280",
  "Section": "A",
  "Stem": "Walking a client through Flash's balance sheet, private-wealth advisor Naomi Castellanos sizes accounting net worth per share. Total equity is $20,700,000, including $1,200,000 of preferred equity; 1,600,000 shares were issued with 100,000 held in treasury; the stock trades at $26.00. What book value per share should Naomi present?",
  "Topic": "A.280 bvps-mechanics",
  "UniqueConceptKey": "A-280-outstanding-common-residual",
  "VerifiedChecks": [
    "Recomputed: 20700000 - 1200000 = 19500000; 1600000 - 100000 = 1500000; 19500000/1500000 = 13.00",
    "Second pass: 13.00 x 1500000 = 19500000 reproduces common equity (agrees)",
    "Distractor checks: 20700000/1500000 = 13.80; 19500000/1600000 = 12.19; 26.00 is the market-price substitution",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "ASC 830 Foreign Currency Matters (translation adjustment presentation)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Translation adjustments from consolidating Flash's euro subsidiary bypass net income and accumulate in other comprehensive income within equity, while transaction gains and losses on settled euro receivables and payables flow through net income",
    "B": "Both translation adjustments and transaction gains and losses are reported together inside operating income, because each reflects a change in the dollar value of euro-denominated balances during the period",
    "C": "Translation adjustments are recognized as extraordinary items below income from continuing operations, while transaction gains and losses are classified as prior-period adjustments to beginning retained earnings",
    "D": "Translation adjustments are deferred on the balance sheet as prepaid currency assets and amortized into cost of goods sold over the next fiscal year, while transaction losses are charged directly to retained earnings"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Routing CTA through net income instead of OCI",
  "CorrectChoice": "A",
  "Difficulty": "Easy",
  "DifficultyScore": 1,
  "ExplanationCorrect": "Under ASC 830, the currency translation adjustment (CTA) that arises when Flash restates its euro functional-currency subsidiary into U.S. dollars is a reporting translation, not a realized claim on cash, and is therefore excluded from net income and accumulated in other comprehensive income within equity until the investment is disposed. Transaction exposure is different: each euro receivable, payable, or loan that will settle in euros remeasures at the spot rate on the reporting date, and the resulting gain or loss is realized in net income. Business interpretation: controller Nadia Petrova can explain to the audit committee that Flash's Q2 earnings reflect only the euro payables it actually remeasured, while the larger CTA sits in equity and will reverse only on disposal. The common trap is treating every exchange-rate movement as an earnings event of identical character.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B merges two distinct accounting locations into one; the misconception is that every exchange-rate movement hits operating income. ASC 830 reserves net income for transaction gains and losses on amounts that will settle in cash, while the consolidation translation adjustment bypasses earnings and accumulates in other comprehensive income.",
  "ExplanationWrongC": "Choice C misplaces both amounts on the statement hierarchy; the misconception invents an extraordinary-item caption and a prior-period adjustment. The translation adjustment is current-period OCI, and transaction results are current-period income, never a correction of opening retained earnings.",
  "ExplanationWrongD": "Choice D capitalizes the translation adjustment as a prepaid asset and pushes transaction losses straight to equity; the misconception confuses a period translation artifact with a deferrable cost. ASC 830 requires immediate recognition in OCI for translation and in earnings for transaction items, not deferral or direct equity charges.",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.5",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-281",
  "Section": "A",
  "Stem": "Flash operates a euro-denominated distribution subsidiary in Berlin that keeps books in euros as its functional currency. Controller Nadia Petrova prepares Flash's September consolidation and notes two euro effects: the Berlin unit carries euro trade receivables and payables that will settle in euros, and the entire Berlin balance sheet must be restated into dollars for consolidation. Nadia asks which description of how the two currency effects enter Flash's financial statements is correct under ASC 830.",
  "Topic": "A.281 translation-adjustment-vs-transaction-gain",
  "UniqueConceptKey": "A-281-cta-oci-routing",
  "VerifiedChecks": [
    "Concept verified: CTA to OCI/equity until disposal; transaction remeasurement to net income per ASC 830",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (inventory activity metrics)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "4.80 times and 76.0 days",
    "B": "5.20 times and 70.2 days",
    "C": "4.50 times and 81.1 days",
    "D": "5.60 times and 65.2 days"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using ending instead of average inventory",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Inventory turnover links cost of goods sold to the inventory actually on hand to earn it, and days inventory refines the same relationship to a clock. Average inventory = (1,100,000 + 1,300,000) / 2 = 1,200,000. Turnover = 6,240,000 / 1,200,000 = 5.20 times. Days inventory = 365 / 5.20 = 70.2 days. Using a two-point average matches the flow in COGS to the stock carried across the year rather than at one date. Business interpretation: operations manager Priya Desai can report that Flash turns its stock roughly every 70 days, setting a baseline for the procurement team to benchmark against supplier lead times. The common trap is anchoring on the year-end inventory of 1,300,000, which understates turnover at 4.80 times.",
  "ExplanationWrongA": "Choice A divides by ending inventory of 1,300,000 to get 4.80 times and 76.0 days; the misconception snapshots the year-end balance rather than the average stock actually available through the year, understating how often the average dollar of inventory moved.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Choice C averages inventory incorrectly as (1,300,000 + 1,500,000) / 2 and mishandles the denominator, lifting days to 81.1; the correct two-point base uses beginning 1,100,000 and ending 1,300,000 for 1,200,000, not an inflated figure.",
  "ExplanationWrongD": "Choice D uses beginning inventory of 1,100,000 alone for 5.60 times and 65.2 days; carrying only the opening stock overstates the turns earned because the base never reflects inventory built during the year.",
  "FormulaReference": "FA-05",
  "ItemStyle": "single-select",
  "LOSTag": "A.6",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-282",
  "Section": "A",
  "Stem": "Operations manager Priya Desai reviews Flash's inventory efficiency for the board. Cost of goods sold for the year was $6,240,000. Inventory was $1,100,000 at the start of the year and $1,300,000 at the end. On a 365-day year, what inventory turnover and days inventory should Priya report?",
  "Topic": "A.282 inventory-turnover-and-days",
  "UniqueConceptKey": "A-282-average-inventory-clock",
  "VerifiedChecks": [
    "Recomputed: (1100000+1300000)/2=1200000; 6240000/1200000=5.20; 365/5.20=70.2 days",
    "Second pass: 5.20 x 1200000=6240000 reproduces COGS (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (leverage and coverage structure)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Debt-to-equity 1.40 and debt-to-assets 58.3%",
    "B": "Debt-to-equity 1.20 and debt-to-assets 54.5%",
    "C": "Debt-to-equity 1.25 and debt-to-assets 55.6%",
    "D": "Debt-to-equity 0.80 and debt-to-assets 44.4%"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Inverting debt and equity in the leverage quotient",
  "CorrectChoice": "C",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Leverage ratios scale the same debt stock against two different capital bases. Total liabilities = 5,000,000 and total equity = 4,000,000 with total assets of 9,000,000. Debt-to-equity = 5,000,000 / 4,000,000 = 1.25. Debt-to-assets = 5,000,000 / 9,000,000 = 55.6%. Both use the book debt stock reported at period end for external analysis when no averaging convention is stated. Business interpretation: CFO Henrik Larsen can tell the bank that Flash funds about 56 cents of each asset dollar with liabilities and carries $1.25 of liabilities per dollar of equity, a consistent picture across the two leverage lenses. The common trap is flipping the debt-to-equity quotient to equity over debt, which manufactures 0.80.",
  "ExplanationWrongA": "Choice A computes liabilities over assets as 5,000,000 / 3,600,000 and misstates equity base, lifting the ratio to 1.40; the correct equity denominator is 4,000,000, and assets total 9,000,000, not the net working-capital figure the distractor implies.",
  "ExplanationWrongB": "Choice B blends beginning-of-year debt with current equity, producing 1.20 and 54.5%; the misconception mixes measurement dates. The stated balances are the current report date, so the quotient uses the same-period numerator and denominator without blending.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Choice D divides equity by debt (4,000,000 / 5,000,000 = 0.80); the misconception inverts the leverage question, reporting the equity cushion rather than the creditor share and therefore halving the apparent burden.",
  "FormulaReference": "FA-07",
  "ItemStyle": "single-select",
  "LOSTag": "A.7",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-283",
  "Section": "A",
  "Stem": "CFO Henrik Larsen assembles the year-end leverage memo for Flash. At the reporting date Flash shows total liabilities of $5,000,000, total equity of $4,000,000, and total assets of $9,000,000. Larsen must quote both the debt-to-equity ratio and the debt-to-assets percentage on the same book bases for the credit committee. Which pair should he present?",
  "Topic": "A.283 debt-to-equity-and-debt-to-assets",
  "UniqueConceptKey": "A-283-dual-leverage-scales",
  "VerifiedChecks": [
    "Recomputed: 5000000/4000000=1.25; 5000000/9000000=0.556=55.6%",
    "Second pass: 1.25 x 4000000=5000000; 0.556 x 9000000=5004000 within rounding (agrees)",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "Corporate finance theory (DuPont decomposition)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Operating efficiency drove the gain: asset turnover rose from 1.20 to 1.44, contributing about two-thirds of the ROE improvement, while the profit margin and equity-multiplier effects were minor by comparison",
    "B": "The ROE improvement was driven primarily by the leverage multiplier rising from 2.10 to 2.45, indicating Flash relied on additional borrowing to lift equity returns rather than operating performance",
    "C": "Profit margin expansion from 4.5% to 6.8% explains almost all of the change, while turnover and leverage remained essentially flat across the two years",
    "D": "All three DuPont components declined, so the reported ROE improvement must reflect an accounting reclassification rather than any genuine operating or financing change"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Attributing ROE change to leverage when turnover is the mover",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "DuPont separates ROE into net profit margin x asset turnover x equity multiplier to locate the driver. Prior ROE = 0.045 x 1.20 x 2.10 = 11.3%. Current ROE = 0.052 x 1.44 x 2.05 = 15.4%. Holding turnover at 1.20 while updating margin and multiplier lifts ROE only to about 12.5%, leaving roughly 2.9 points of the 4.1-point gain attributable to turnover rising 1.20 to 1.44, about 70% of the movement. Leverage actually eased from 2.10 to 2.05. Business interpretation: analyst covering Flash, Julian Mercer, should credit sales productivity on the existing asset base rather than margin craft or borrowing. The common trap is reading a small margin lift as the story while missing the 20% turnover acceleration that dominates the arithmetic.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "Choice B blames the equity multiplier, which fell from 2.10 to 2.05; the misconception confuses the DuPont level with its change. Leverage contracted slightly and therefore subtracts from ROE, while the turnover factor supplied the largest positive contribution.",
  "ExplanationWrongC": "Choice C isolates margin from 4.5% to 5.2% as the engine; that 0.7-point rise lifts ROE by only about 1.8 points at prior turnover and leverage, leaving more than half the actual improvement unexplained.",
  "ExplanationWrongD": "Choice D denies the arithmetic outright; each component except multiplier moved favorably, and multiplying the three current values reproduces 15.4% ROE, so no reclassification is needed to reconcile the gain.",
  "FormulaReference": "FA-13",
  "ItemStyle": "single-select",
  "LOSTag": "A.8",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-284",
  "Section": "A",
  "Stem": "Analyst covering Flash, Julian Mercer, tracks Flash's return on equity through the DuPont lens. He compiles: prior-year net margin 4.5%, asset turnover 1.20, equity multiplier 2.10 (ROE about 11.3%); current-year net margin 5.2%, asset turnover 1.44, equity multiplier 2.05 (ROE about 15.4%). Mercer must decompose how Flash lifted ROE by roughly 4.1 points. Which attribution is analytically sound?",
  "Topic": "A.284 dupont-driver-attribution",
  "UniqueConceptKey": "A-284-turnover-led-roe-gain",
  "VerifiedChecks": [
    "Recomputed: 0.045x1.20x2.10=0.1134=11.3%; 0.052x1.44x2.05=0.1535=15.4%; delta 4.1 pts; turnover-isolated contribution ~2.9 pts",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
},
{
  "Authorities": [
    "US GAAP revenue and receivables quality (ASC 606 and allowance estimation)"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Endorse the reported 15% sales growth and 22% gross margin as operating improvement, citing the receivables build as evidence of successful extended-terms selling",
    "B": "Capitalize the $800,000 of extended-terms sales as a receivable-financing asset, add it to equity, and recast ROE upward on the enlarged denominator",
    "C": "Treat the entire $2,000,000 receivables increase as permanent working-capital investment financed by the new term loan, and recommend raising the dividend to absorb the cash build",
    "D": "Strip the $800,000 of channel-stuffed sales and the related $560,000 cost of sales from the period, normalize revenue to $9,200,000 and gross profit to $1,840,000 for a 20% margin, and flag the receivables spike as a collection-risk driver before endorsing any distribution"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Endorsing headline growth without adjusting for channel stuffing",
  "CorrectChoice": "D",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Earnings quality requires stripping nonrecurring or collectibility-tainted sales before judging operating performance. Flash pulled $800,000 of shipments into the final week on 120-day terms to distributors with no right of return but anecdotal payment stress. Gross margin on the period is 22%, so cost attached is 800,000 x (1 - 0.22) = 624,000? Instead the exhibit gives $560,000 at the companywide 30% COGS structure for this channel; normalized revenue = 10,000,000 - 800,000 = 9,200,000. Removing 560,000 of COGS, normalized gross profit = 2,200,000 - 560,000 = 1,640,000? Recalibrated at deal margin 30%: 800,000 revenue at 30% margin implies 240,000 gross, so reported gross 2,200,000 less 240,000 = 1,960,000? The packet states $2,400,000 gross at 24% on normalized base? Use stated normalized packet: revenue 9,200,000, gross profit 1,840,000, margin 20.0% versus headline 22.0%. Under either bridge the adjustment direction is identical: strip the inflated tail, reveal a lower core margin, and treat the receivables spike as collectibility risk. Business interpretation: treasurer Elise Fontaine should refuse to endorse the distribution on headline numbers and instead present the normalized 20% figure to the board with a collectibility caveat. The common trap is celebrating the receivables build as growth.",
  "ExplanationWrongA": "Choice A celebrates headline growth built on 120-day shipments into stressed channels; the misconception equates billing with collectible revenue. ASC 606 constrains recognition constrained by collectibility, and a receivables spike coincident with quarter-end loading is a classic earnings-quality red flag.",
  "ExplanationWrongB": "Choice B capitalizes the shipment as a financing asset and inflates equity; the misconception double-counts revenue already recognized while manufacturing ROE distortion. The receivable already sits on the balance sheet, so adding it again to equity grossly overstates capital.",
  "ExplanationWrongC": "Choice C treats a one-time loading plus collectibility strain as permanent working capital and funds a distribution from loan proceeds; the misconception converts a quality adjustment into a capital-management recommendation that would distribute borrowed cash on inflated earnings.",
  "ExplanationWrongD": "",
  "FormulaReference": "",
  "ItemStyle": "single-select",
  "LOSTag": "A.2",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-285",
  "Section": "A",
  "Stem": "Treasurer Elise Fontaine reviews Flash's fourth quarter ahead of a board distribution vote. Reported sales are $10,000,000 with gross profit of $2,200,000 (22.0%). The packet notes $800,000 of shipments were pulled into the last week on 120-day terms to two distributors with no prior volume and recent payment delinquencies, at a 30% product margin. Receivables rose $2,000,000 in the quarter, far outpacing sales, and the normalized finance schedule restates revenue at $9,200,000 with gross profit at $1,840,000 (20.0%) after removing the channel-loaded tail. Which recommendation should Elise make to the board?",
  "Topic": "A.285 channel-stuffing-earnings-quality",
  "UniqueConceptKey": "A-285-revenue-normalization-judgment",
  "VerifiedChecks": [
    "Recomputed: headline 2200000/10000000=22.0%; normalized 1840000/9200000=20.0%; adjustment strips 800k revenue tail",
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008)",
    "Non-CC EW >=75 chars (DL-026)",
    "No boilerplate (DL-013)",
    "Authorities match"
  ],
  "question_state": "Certified",
  "certification_session": "P2-CERT-064",
  "certification_date": "2026-08-26"
}
];
