var pack_p2_a_part17 = [
{
  "Authorities": [
    "Market-based ratio",
    "Dividend yield analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "The higher yield reflects the price decline, not dividend growth — a rising yield caused by a falling price is a distress signal, not an income opportunity",
    "B": "The company has increased its dividend 67%, making the stock more attractive to income investors",
    "C": "The yield remains 3%, because dividend yield is computed on the investor's original purchase price",
    "D": "A higher dividend yield always indicates a stronger, more shareholder-friendly company"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Reading a rising dividend yield as dividend growth when the price, not the dividend, moved",
  "CorrectChoice": "A",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "Dividend yield = annual dividend ÷ current market price. Northstar's dividend was unchanged at $1.50; the price fell from $50 to $30. The yield rose from 3.0% ($1.50 ÷ $50) to 5.0% ($1.50 ÷ $30) solely because the denominator fell. A yield that rises on a falling price signals the market's deteriorating view of the company, not increased shareholder returns — an analyst must check whether the yield is high because the dividend grew or because the stock price collapsed before recommending the stock for income.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "The dividend did not change. The $1.50 payout is identical; only the price moved. Attributing the higher yield to dividend growth mistakes a denominator effect for a payout decision.",
  "ExplanationWrongC": "Yield is computed on the CURRENT market price, not the investor's cost basis. At $30, the yield is $1.50 ÷ $30 = 5.0%. Computing yield on the purchase price measures the investor's personal return, not the market's pricing of the dividend.",
  "ExplanationWrongD": "Yield is a ratio, not a quality signal. A very high yield often reflects a beaten-down price as investors anticipate a dividend cut or business decline. Dividend sustainability must be assessed against earnings and cash flow.",
  "FormulaReference": "FA-17: Dividend Yield = Annual Dividend per Share ÷ Market Price",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-128",
  "Section": "A",
  "Stem": "Northstar Capital's stock fell from $50 to $30 during the year while its annual dividend remained unchanged at $1.50 per share. A broker newsletter now touts the stock's 'attractive 5% yield.' Which interpretation is correct?",
  "Topic": "A.128 Dividend yield trap — falling price versus rising payout",
  "UniqueConceptKey": "A-128-dividend-yield-trap-falling-price",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Yield 3.0%→5.0% purely from price decline; dividend unchanged",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 310",
    "Receivables analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Credit quality is stable because DSO has not changed over the two-year period",
    "B": "The aging shift is irrelevant — only the allowance for doubtful accounts ratio matters for credit quality",
    "C": "Collections improved, because receivables in the current (0-30 day) bucket grew faster than sales",
    "D": "DSO masks deteriorating collectability — a stable DSO with a rising share of aged receivables means newer sales are collected quickly while older balances are stalling; the allowance for doubtful accounts must be tested for adequacy"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Treating a stable DSO as evidence of stable credit quality without examining the aging schedule",
  "CorrectChoice": "D",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "DSO aggregates all receivables into a single number, so a stable DSO can hide a shift in the composition of the portfolio. Here, receivables over 90 days grew from 8% to 22% of the total while DSO held at 45 days — new sales are being collected promptly, masking the fact that older balances are not being collected at all. The correct analytical response is to disaggregate: test the aging buckets, compare the allowance against the aged balance, and assess whether write-offs are imminent. An allowance that has not grown with the aged receivables means earnings quality and balance sheet values are at risk.",
  "ExplanationWrongA": "A stable DSO is consistent with deteriorating credit quality when the mix shifts. The aging schedule shows the over-90-day bucket nearly tripled as a share of receivables — exactly the deterioration DSO alone cannot reveal.",
  "ExplanationWrongB": "The allowance ratio and the aging schedule are complements, not substitutes. The aging is the primary evidence of collectability; the allowance is management's response to it. A low allowance against a growing aged balance is a red flag, not a reassurance.",
  "ExplanationWrongC": "The data shows the OPPOSITE — the aged (over-90-day) bucket grew from 8% to 22% of receivables. Rapid collection of current sales combined with stalled collection of old balances is the classic pattern of credit deterioration.",
  "ExplanationWrongD": "",
  "FormulaReference": "DSO = Avg AR ÷ (Credit Sales ÷ 365); aging analysis disaggregates by age bucket",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-129",
  "Section": "A",
  "Stem": "Analyst Marcus Lee reviews Riverdale Apparel's receivables. DSO has held steady at 45 days for two years, but the aging schedule shows receivables over 90 days old grew from 8% to 22% of the total, while the allowance for doubtful accounts is unchanged as a percentage of receivables. Which conclusion is correct?",
  "Topic": "A.129 Receivables aging — DSO masking collectability deterioration",
  "UniqueConceptKey": "A-129-receivables-aging-dso-masking",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Stable DSO + rising >90d bucket = collection stall masked by fast current collections",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 835-20",
    "Analytical adjustments"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Capitalized interest improves ROA permanently because the financing cost is never expensed",
    "B": "Capitalizing interest shifts financing cost from the income statement to the balance sheet — current EBIT and interest coverage are overstated, asset turnover is understated, and future depreciation will depress earnings; analysts should restate the capitalized portion as expense for comparability",
    "C": "Capitalized interest must be amortized to interest expense in the year it is incurred",
    "D": "Interest capitalization has no effect on any ratio because total cash flows are unchanged"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Treating interest capitalization as a permanent earnings improvement rather than a timing shift",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Under ASC 835-20, interest on debt financing the construction of qualifying assets is capitalized as part of the asset's cost rather than expensed. The capitalized $12M leaves the income statement, so current EBIT and the interest coverage ratio are overstated; it enters the asset base, so asset turnover is understated; and it returns to the income statement later as higher depreciation over the asset's life. For comparability, analysts commonly treat the capitalized portion as an expense of the period and add it back to interest expense when computing coverage ratios, particularly when capitalization is growing — growing capitalization can create a rising EBIT trend that is partly a deferral artifact.",
  "ExplanationWrongA": "The financing cost does not disappear — it is embedded in the asset and returns as depreciation over the asset's useful life. Current-period ROA rises only because of the deferral; future periods carry the expense.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Capitalized interest is not amortized to interest expense. It is included in the asset's carrying amount and expensed through depreciation as the asset is used. Treating it as immediate interest expense is the analytical restatement, not the GAAP recording.",
  "ExplanationWrongD": "Total cash flows are indeed unchanged, but every accrual-based ratio — EBIT, margins, coverage, turnover, ROA — shifts when the cost is reclassified from expense to asset. Ratio analysis operates on accrual income, so the classification matters materially.",
  "FormulaReference": "Analytical restatement: treat capitalized interest as expense; add back to interest for coverage ratios",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-130",
  "Section": "A",
  "Stem": "Analyst Grace Liu compares two hotel chains. Hotel chain A capitalized $12M of interest on a new flagship property this year; chain B expensed all interest. Chain A's EBIT and interest coverage look strong and its asset turnover fell slightly. Which analysis of the capitalized interest is correct?",
  "Topic": "A.130 Capitalized interest — ratio distortion and restatement",
  "UniqueConceptKey": "A-130-capitalized-interest-ratio-distortion",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Capitalization = deferral: EBIT/coverage overstated, turnover understated, future depreciation drag",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 230",
    "Cash flow quality analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Healthy — the company generated positive net cash flow across all three activities",
    "B": "The company is investing for growth, and operating cash flow will improve as the new assets generate returns",
    "C": "The company is funding operating losses by selling productive assets and borrowing — an unsustainable pattern; negative operating cash flow covered by asset liquidation signals distress or earnings-quality problems",
    "D": "Operating losses are acceptable as long as financing cash flows are positive"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Reading a positive change in cash as financial health without examining the composition of the cash flow statement",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The cash flow statement's three sections tell one story only when read together. Crestline's operations consumed $20M; its investing section produced $18M not from investments maturing but from SELLING a production plant; and $5M of new borrowing plugged the remainder. Selling productive capacity to fund operating losses is not sustainable — assets can be sold only once, and borrowing to cover operating deficits increases leverage. This pattern is a red flag for distress and for earnings quality: accrual earnings may look stable while the cash engine behind them is being dismantled.",
  "ExplanationWrongA": "Positive net cash is not health when it comes from asset liquidation and borrowing. The operating engine itself is cash-negative, and the investing section shows divestiture, not expansion. Cash composition, not the net change, is the diagnostic.",
  "ExplanationWrongB": "The investing section shows an $18M INFLOW from selling a plant — divestiture, not investment. A company investing for growth would show investing OUTFLOWS for capital expenditures.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Financing inflows are not a substitute for operating cash flow. Debt funds the deficit today and must be repaid from operations later; if operations remain negative, the company is on a path to insolvency regardless of how much lenders currently advance.",
  "FormulaReference": "Cash flow composition analysis — operating vs investing vs financing quality",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-131",
  "Section": "A",
  "Stem": "Crestline Steel's cash flow statement shows: operating activities −$20M; investing activities +$18M, composed almost entirely of proceeds from selling a production plant; financing activities +$5M from new borrowings. Net change in cash: +$3M. Which assessment is correct?",
  "Topic": "A.131 Cash flow composition — asset sales funding operating losses",
  "UniqueConceptKey": "A-131-cash-flow-composition-red-flags",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: OCF<0 funded by divestiture + borrowing = unsustainable composition",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 330",
    "ASC 330-10-35"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "Current ratio falls from 2.00 to 1.87 and inventory turnover rises — the write-down reduces current assets and the charge flows through COGS",
    "B": "Current ratio rises because the inventory write-down reduces liabilities",
    "C": "Only the balance sheet is affected; COGS is unchanged because the write-down is reported as a separate loss",
    "D": "The write-down is recorded directly against equity, leaving the current ratio unchanged"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Treating an LCM write-down as a balance-sheet-only event or as an equity adjustment",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Under ASC 330-10-35 (lower of cost or net realizable value), the write-down reduces inventory on the balance sheet and is charged to cost of goods sold. Balance sheet: current assets fall from $300M to $280M, so the current ratio falls from 2.00 to 1.87. Income statement: COGS rises from $400M to $420M. Inventory turnover rises from 4.0 ($400M ÷ $100M average) to 4.67 ($420M ÷ $90M average — beginning $100M, ending $80M). The write-down simultaneously weakens liquidity ratios and mechanically improves the turnover ratio — a caution against reading turnover in isolation.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "The write-down reduces ASSETS (inventory), not liabilities. Current liabilities are untouched at $150M; the current ratio falls to $280M ÷ $150M = 1.87.",
  "ExplanationWrongC": "The charge flows through COGS, reducing gross profit and net income. Inventory write-downs are an operating cost under ASC 330 — they are not reported outside operating income.",
  "ExplanationWrongD": "The write-down hits inventory and COGS — two accounts that flow through the income statement and retained earnings in the normal course. There is no direct charge to equity, and the current ratio cannot remain unchanged when current assets fall.",
  "FormulaReference": "LCM write-down → COGS charge; turnover = COGS ÷ average inventory",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-132",
  "Section": "A",
  "Stem": "Nuvora Industries writes down $20M of inventory to net realizable value. Before the write-down: current assets $300M, current liabilities $150M, COGS $400M, beginning inventory $100M, ending inventory $80M (post-write-down). What are the effects on the current ratio and inventory turnover?",
  "Topic": "A.132 Inventory write-down — ratio effects under LCM",
  "UniqueConceptKey": "A-132-inventory-write-down-ratio-effects",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: CR: 300/150=2.00→280/150=1.87; T/O: 420/90=4.67 vs 400/100=4.00",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 740",
    "Analytical classification"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Always exclude the deferred tax liability from debt because it is not a contractual obligation",
    "B": "Always include the full deferred tax liability as interest-bearing debt because it will reverse in cash",
    "C": "Deferred tax liabilities are always treated as equity because they originate from timing differences",
    "D": "Classify based on reversal expectations — a liability that grows steadily and reverses only if the business shrinks behaves like equity for leverage analysis, while one expected to reverse soon is more debt-like; consistent treatment matters more than the label"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Applying a blanket all-debt or all-equity treatment to deferred tax liabilities regardless of reversal expectations",
  "CorrectChoice": "D",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Deferred tax liabilities sit between debt and equity: they are not contractual obligations to creditors, yet some portion will settle in cash as timing differences reverse. The practical analytical treatment follows the reversal pattern. A DTL that grows every year with continued capital spending — reversing only in a liquidation or contraction — behaves like equity: the liability keeps being deferred and costs the firm nothing currently. A DTL expected to reverse within the next few years (e.g., from a one-time installment sale) is more debt-like. The analyst's job is consistency: classify the DTL one way and apply it across all leverage, coverage, and ROE computations, and disclose the sensitivity of the conclusion to the choice.",
  "ExplanationWrongA": "A blanket exclusion ignores reversals that will produce real tax payments. The portion of the DTL expected to reverse soon creates cash obligations and should be treated as debt-like. Categorical treatment loses information.",
  "ExplanationWrongB": "Treating the entire DTL as interest-bearing debt overstates leverage: a growing DTL imposes no current cash burden and no interest cost, and it does not carry default risk the way debt does.",
  "ExplanationWrongC": "The DTL is a liability under ASC 740, not equity. Its origin in timing differences does not convert it to equity; the analytical question is how much of it will settle in cash and when.",
  "ExplanationWrongD": "",
  "FormulaReference": "Leverage restatement: DTL classified by expected reversal horizon",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-133",
  "Section": "A",
  "Stem": "Analyst Jordan Reyes computes leverage ratios for Harbor Industrial, which carries a $60M deferred tax liability that has grown every year for a decade alongside rising capital spending. The controller asks whether the DTL should be treated as debt, as equity, or excluded. How should the analyst treat the deferred tax liability when computing leverage ratios?",
  "Topic": "A.133 Deferred tax liabilities — debt versus equity classification",
  "UniqueConceptKey": "A-133-deferred-tax-liability-classification",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Growing DTL behaves equity-like; near-term reversal is debt-like; consistency is key",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 205-10",
    "Comparative analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Calendar differences are immaterial — both retailers follow GAAP, so their annual results are directly comparable",
    "B": "Year-end differences distort seasonal comparisons — a January year end captures the entire holiday season in one fiscal year, while a December end splits it across two; analysts should compare like periods or use trailing-twelve-month data",
    "C": "A later fiscal year end always makes a company look more profitable than a calendar year end",
    "D": "Fiscal year choice is arbitrary and never affects ratio comparability"
  },
  "CognitiveLevel": "Understand",
  "CommonTrapReference": "Comparing seasonal companies across different fiscal year ends without period alignment",
  "CorrectChoice": "B",
  "Difficulty": "Moderate-Easy",
  "DifficultyScore": 2,
  "ExplanationCorrect": "For seasonal businesses, the fiscal year end determines which holiday or peak season falls in which annual period. Retailer A (December 31) splits the holiday season across two fiscal years; Retailer B (January 31) captures it in one. Same-quarter comparisons can be equally misleading when the quarters contain different weeks of the peak season. The standard remedies are comparing identical periods (e.g., the 4-week December of both), or using trailing-twelve-month metrics that wash out calendar timing. GAAP compliance does not create comparability — period alignment does.",
  "ExplanationWrongA": "GAAP governs recognition and measurement, not seasonality alignment. Two GAAP-compliant retailers with different year ends can report materially different annual results purely from calendar timing.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "The direction depends on which season each year end captures and how strong that season was — a later year end can just as easily understate profit when the peak season straddles the cut-off. No mechanical profitability bias exists.",
  "ExplanationWrongD": "Fiscal year choice has no economic effect but a real measurement effect: it shifts which transactions land in which reporting period. Ratios computed on misaligned periods are distorted even though the underlying business is identical.",
  "FormulaReference": "Comparability adjustment — trailing-twelve-month or like-period alignment",
  "ItemStyle": "single-select",
  "LOSTag": "A.4",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-134",
  "Section": "A",
  "Stem": "Analyst Priya Sharma compares two retailers: Meridian Mart has a December 31 fiscal year end; Brixton Retail uses January 31. Both generate over half their annual sales in November and December. What is the correct approach to comparing their results?",
  "Topic": "A.134 Fiscal year-end differences — seasonal comparability",
  "UniqueConceptKey": "A-134-fiscal-year-end-comparability",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: Year-end alignment needed for seasonal comparability — TTM or like-period comparison",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "Beneish M-Score framework",
    "Earnings quality analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Approve the facility — all reported figures were audited, and audited statements carry no earnings-quality risk",
    "B": "Approve but monitor — these red flags are normal for fast-growing companies",
    "C": "Escalate before extending credit — the combination of receivables growing far faster than sales, gross margin expansion diverging from the industry, and a sharp rise in accruals matches known earnings-manipulation profiles; demand disaggregated disclosures and stress-test the allowance",
    "D": "Reject the application automatically — any red flag proves fraud has occurred"
  },
  "CognitiveLevel": "Evaluate",
  "CommonTrapReference": "Equating an audit with zero earnings-quality risk, or treating red flags as proof of fraud",
  "CorrectChoice": "C",
  "Difficulty": "Very Difficult",
  "DifficultyScore": 5,
  "ExplanationCorrect": "The Beneish M-Score framework identifies quantitative signatures of earnings manipulation: receivables growing much faster than sales (DSO jumping from 60 to 90 days), gross margin improving while every competitor's margin deteriorates, and accruals rising sharply relative to total assets. The auditor's opinion attests to compliance with GAAP, not to earnings quality — aggressive recognition can be within GAAP and still be misleading. The correct credit decision is neither automatic approval nor automatic rejection: escalate the file, require the borrower to explain the divergence (customer terms, product mix, channel expansion), obtain an aging schedule and allowance rollforward, and test what normalized earnings and cash flow would be before sizing the facility. Red flags are triggers for evidence-gathering, not verdicts.",
  "ExplanationWrongA": "An audit reduces, not eliminates, earnings-quality risk, and manipulation often operates within GAAP through aggressive estimates (returns, allowances, revenue cut-off). The auditor's clean opinion does not override visible red flags in the borrower's own ratios.",
  "ExplanationWrongB": "Fast-growing companies DO see receivables rise — but receivables growing 50% faster than sales, margin expansion against a declining industry, and ballooning accruals together are the specific signatures of overstatement, not ordinary growth. Monitoring without escalation leaves the bank exposed.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "Red flags are evidence of risk, not proof of fraud. Automatic rejection is as unsound as automatic approval — the bank should investigate, quantify, and then decide. Over-reaction destroys legitimate customer relationships; under-reaction destroys capital.",
  "FormulaReference": "Beneish M-Score inputs: DSI, GMI, AQI, TATA (accruals) divergence patterns",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-135",
  "Section": "A",
  "Stem": "Senior credit officer Dana Walsh reviews a $40M borrowing request from a prospective client. Over three years: days sales outstanding rose from 60 to 90 while sales grew 10% annually; gross margin improved from 30% to 36% while every industry peer's margin declined; and total accruals relative to assets rose sharply. The statements carry a clean audit opinion. What should the credit officer do?",
  "Topic": "A.135 Earnings manipulation red flags — M-Score profile in credit decisions",
  "UniqueConceptKey": "A-135-earnings-manipulation-red-flags-credit",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: DSI+GMI+AQC signatures → escalate and evidence-gather, not auto-approve or auto-reject",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 210-10-45",
    "Liquidity analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": true,
  "Choices": {
    "A": "0.20 — net working capital of $100M divided by total assets of $500M",
    "B": "0.48 — current assets of $240M divided by total assets of $500M",
    "C": "0.71 — net working capital of $100M divided by current liabilities of $140M",
    "D": "0.28 — current liabilities of $140M divided by total assets of $500M"
  },
  "CognitiveLevel": "Apply",
  "CommonTrapReference": "Using current assets or current liabilities alone in the numerator instead of their net difference",
  "CorrectChoice": "A",
  "Difficulty": "Moderate",
  "DifficultyScore": 3,
  "ExplanationCorrect": "Net working capital is current assets minus current liabilities: $240M − $140M = $100M. Net working capital to total assets = $100M ÷ $500M = 0.20. This ratio measures the proportion of Meridian's asset base tied up in net working capital — each dollar of assets is supported by 20 cents of net current-asset investment. Under ASC 210-10-45, the current/noncurrent classification defines the ratio's components, and the analyst should interpret the result against Meridian's industry peers: higher ratios signal greater liquidity but can also flag inefficient capital deployment. A common exam trap is dividing current assets by total assets (0.48), which ignores the $140M of current liabilities that must be funded out of those assets.",
  "ExplanationWrongA": "",
  "ExplanationWrongB": "0.48 divides current assets ($240M) by total assets ($500M), treating all current assets as net working capital. Meridian must fund $140M of current liabilities out of those assets, so the correct numerator is $240M − $140M = $100M. This choice overstates Meridian's working-capital intensity by ignoring the liability side entirely.",
  "ExplanationWrongC": "0.71 divides net working capital ($100M) by current liabilities ($140M) — a coverage ratio, not an asset-proportion ratio. The credit memorandum scales net working capital by total assets ($500M) to measure the share of Meridian's asset base invested in working capital. Dividing by current liabilities answers a different question than the template asks.",
  "ExplanationWrongD": "0.28 divides current liabilities ($140M) by total assets ($500M). The template asks for net working capital to total assets; dividing liabilities by assets measures liability intensity, not working-capital intensity. Meridian's net working capital of $100M belongs in the numerator.",
  "FormulaReference": "NWC ÷ Total Assets",
  "ItemStyle": "single-select",
  "LOSTag": "A.1",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-136",
  "Section": "A",
  "Stem": "CFO Maria Chen of Meridian Manufacturing is preparing the annual credit package for Meridian's lenders. The balance sheet shows current assets of $240M, current liabilities of $140M, and total assets of $500M. The bank's credit memorandum template asks for net working capital to total assets. What is the correct ratio?",
  "Topic": "A.136 Net working capital to total assets",
  "UniqueConceptKey": "A-136-net-working-capital-to-total-assets",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: NWC=240−140=100; 100/500=0.20",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 606",
    "Earnings quality analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "Recognize the revenue — the goods have been invoiced, and invoicing is the definitive evidence that a sale has occurred under GAAP",
    "B": "Escalate for evidence-gathering — under ASC 606, revenue requires transfer of control, and bill-and-hold requires a substantive reason for the hold; demand the shipping terms, customer requests, and risk-of-loss documentation before recognizing any of the Q4 surge",
    "C": "Recognize the revenue — the auditors will review the arrangements during the year-end audit, and their sign-off will retroactively validate the Q4 treatment",
    "D": "Recognize revenue only for the goods that physically left the warehouse — shipment, not control, is the sole criterion for revenue recognition"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Treating invoicing as proof of revenue when ASC 606 requires transfer of control",
  "CorrectChoice": "B",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "Under ASC 606, revenue is recognized when control transfers to the customer, and its bill-and-hold guidance permits recognition without shipment only when the arrangement is substantive: the customer requests the hold, the goods are separately identified and ready for transfer, and the seller cannot redirect them. Meridian's file shows invoices but no documented substantive reason for the holds — a textbook revenue-timing red flag. The 62% Q4 surge is likely accelerated recognition: revenue pulled forward to flatter the quarter. The correct action is escalation and evidence-gathering, not automatic recognition or automatic reversal; Vasquez must obtain the customer requests, shipping terms, and risk-of-loss documentation before certifying. A common exam trap is treating invoicing as proof of revenue when ASC 606's core principle is control, not billing.",
  "ExplanationWrongA": "Invoicing is a billing event, not a control-transfer event. Under ASC 606, Meridian may invoice before, at, or after recognition; the invoice itself proves nothing about whether the customer obtained control of the goods sitting in Meridian's warehouse. Recognizing the 62% Q4 surge on invoices alone would overstate revenue if the bill-and-hold arrangements lack substance.",
  "ExplanationWrongB": "",
  "ExplanationWrongC": "Audit sign-off does not retroactively make an aggressive Q4 recognition decision correct, and relying on it inverts the control hierarchy: Meridian's controller must conclude on ASC 606 before the auditors opine. If Vasquez certifies now and the auditors later object, Meridian faces a restatement risk on the very quarter being certified.",
  "ExplanationWrongD": "Physical shipment is a common way control transfers, but ASC 606 permits bill-and-hold recognition without shipment when the hold is substantive and at the customer's request. The defect in Meridian's arrangements is not the absence of shipment per se — it is the absence of evidence that the holds were substantive, which is why escalation for documentation is the correct response.",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-137",
  "Section": "A",
  "Stem": "Controller Elena Vasquez of Meridian Manufacturing is closing the books for Q4. Reported revenue surged 62% from Q3, driven almost entirely by new 'bill-and-hold' arrangements: Meridian invoiced customers for goods that were not shipped, remain in Meridian's warehouse, and are covered only by customer billing documentation. The invoices reference customer requests for delayed delivery, but Vasquez finds no documentation of any substantive business reason for the holds. What should she do before certifying the Q4 results to CFO Maria Chen?",
  "Topic": "A.137 Bill-and-hold arrangements — revenue timing red flag",
  "UniqueConceptKey": "A-137-bill-and-hold-revenue-timing-red-flag",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: ASC 606 bill-and-hold requires substantive reason — escalate for evidence, not auto-recognize",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
},
{
  "Authorities": [
    "ASC 450-20",
    "Earnings quality analysis"
  ],
  "BlueprintDomain": "Financial Statement Analysis",
  "CalculationItem": false,
  "Choices": {
    "A": "High earnings quality — building reserves in good years is conservative accounting, and conservative reserves always mean trustworthy earnings",
    "B": "Neutral — warranty reserves are audited each year, so the accrual and release pattern reflects genuine estimation changes, not managerial intent",
    "C": "Earnings smoothing — Meridian over-accrued in good years and released the excess in a weak year, inflating current earnings; Reed should restate earnings using a normalized warranty rate across all years",
    "D": "Genuine improvement — the release shows Meridian's actual warranty costs declined, so current earnings are understated, not overstated"
  },
  "CognitiveLevel": "Analyze",
  "CommonTrapReference": "Equating reserve conservatism with earnings quality — the test is consistency of estimates over time, not their size",
  "CorrectChoice": "C",
  "Difficulty": "Difficult",
  "DifficultyScore": 4,
  "ExplanationCorrect": "The pattern — reserves ballooning in strong years and releasing in a weak year — is the classic 'cookie-jar reserve' signature of earnings smoothing. Under ASC 450-20, warranty accruals must reflect management's best estimate of probable losses; over-accruing when earnings are strong and releasing when they are weak is exactly the manipulation this standard exists to prevent. Meridian's $9M release offset roughly half the year's operating decline, meaning reported earnings materially overstate the underlying operating trend. The analyst's remedy is normalization: apply a consistent warranty rate (claims ÷ sales) across all years to restate the earnings series and strip out the reserve's timing effect. The release is an accounting estimate, not a cash flow — credit analysis should focus on the normalized series. A common exam trap is equating reserve conservatism with earnings quality; the question is whether estimates are consistent over time, not whether they are large.",
  "ExplanationWrongA": "Building reserves can be conservative, but the sequence matters: Meridian's reserves grew in exactly the years it could afford the charge and reversed in the year it could not. That timing is the signature of smoothing, not conservatism. Conservative accounting would show a stable, justified warranty rate every year, not a $9M release precisely when operating income fell.",
  "ExplanationWrongB": "Audits verify that Meridian's estimates are supportable within a range, not that they are free of managerial bias. Warranty estimation offers a wide legitimate range, and management can pick the favorable end in any given year. The audited status of the reserve does not neutralize the timing pattern of accrual and release.",
  "ExplanationWrongC": "",
  "ExplanationWrongD": "The release reflects an accounting-estimate change, not evidence of lower real warranty costs. Meridian's claims were flat during the accrual years — if the reserve were genuinely excessive, the buildup itself was an error. Treating the $9M release as improved economics would double-count the manipulation: Reed would be rewarding the same overstatement that inflated the prior strong years.",
  "ItemStyle": "single-select",
  "LOSTag": "A.3",
  "Part": 2,
  "Part2OnlyFlag": true,
  "QuestionID": "P2-A-138",
  "Section": "A",
  "Stem": "Equity analyst Marcus Reed is reviewing Meridian Manufacturing's warranty reserve. During two strong years, the reserve balance grew from $8M to $22M even though warranty claims were flat, and the income statement absorbed unusually large warranty accruals. In the current weak year, Meridian released $9M of the reserve into income, which offset almost half of the year's operating decline. What pattern does this reveal, and how should Reed restate the earnings series?",
  "Topic": "A.138 Cookie-jar reserves — earnings smoothing detection",
  "UniqueConceptKey": "A-138-cookie-jar-reserves-earnings-smoothing",
  "VerifiedChecks": [
    "Part2OnlyFlag verified true",
    "EW[CC] empty (DL-008 compliant)",
    "Non-CC EW slots >=50 chars (DL-026 compliant)",
    "No boilerplate text (DL-013 prevention)",
    "Difficulty justified",
    "Independent: accrual-then-release across earnings cycle = smoothing; normalize warranty rate",
    "Authority citations match tested concept"
  ],
  "question_state": "Certified"
}
];
