const MCQ_BANK_E_PART_61 = [
  {
    "QuestionID": "P1E-B-S09",
    "Part": 1,
    "Section": "B",
    "SectionName": "Planning, Budgeting, and Forecasting",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "ProductionStatus": "Draft",
    "question_state": "Certified",
    "Part1OnlyFlag": true,
    "StudyLink": "IMA CMA Part 1 CSO Section B.2 — Budgeting concepts (LOS B.2.a–B.2.d)",
    "VerifiedChecks": [
      "Calculations independently verified — no arithmetic computation required (conceptual Evaluate item)",
      "Distractors written as plausible CMA-style traps targeting distinct misconceptions",
      "DL-008 compliant — ExplanationWrong[CorrectChoice] is empty string",
      "DL-026 compliant — all non-CorrectChoice ExplanationWrong slots are ≥150 characters with choice-specific text",
      "ExplanationCorrect ≥300 characters with principle, reasoning chain, business interpretation, and exam trap"
    ],
    "Topic": "B-S09 budgeting philosophy incremental ZBB ABB rolling evaluation",
    "LOSTag": "P1-B.2 Budgeting concepts",
    "primaryTheory": "B3",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Evaluate",
    "Stem": "Atlas Manufacturing has used incremental budgeting for fifteen years — each department's budget is last year's figure plus a uniform 3% increase. The CEO believes this approach has embedded $2,800,000 in unnecessary costs and wants a \"clean-sheet\" review of every expense. Division heads argue their operations are stable and predictable; they warn that requiring every line item to be justified from zero will consume months of management time and demoralize their teams. As controller, you must recommend which budgeting approach best balances the CEO's cost-reduction objective against the operational reality of a mature, stable-demand manufacturing environment.",
    "Choices": {
      "A": "Retain incremental budgeting but reduce the annual increase from 3% to 1.5%, achieving cost discipline without disrupting operations.",
      "B": "Transition to activity-based budgeting (ABB), which allocates resources based on the cost of activities consumed rather than historical spending levels.",
      "C": "Adopt a continuous (rolling) budget with a twelve-month horizon updated quarterly, shifting the focus from annual negotiation to ongoing forecasting.",
      "D": "Implement zero-based budgeting (ZBB) for administrative and support functions where embedded waste is most likely, while retaining incremental budgeting for direct production operations where costs are stable."
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Option D is correct because it applies zero-based budgeting selectively — the hallmark of prudent managerial judgment. Under the CMA Part 1 budgeting concepts framework, ZBB requires every expense to be justified from zero each period, which eliminates embedded waste and forces managers to re-examine whether each activity still serves organizational objectives. However, full-enterprise ZBB is exceptionally costly in management time: every division head must prepare decision packages for every line item, defend them through multiple review rounds, and absorb the morale cost of perpetual justification. Atlas's division heads correctly identify this burden. Their production operations — stable demand, mature processes, predictable cost structures — do not benefit proportionally from ZBB because their costs are already well-understood and efficiency is high. The administrative and support functions (HR, legal, facilities, IT, marketing overhead), by contrast, are where incremental budgeting's \"creep\" effect most commonly embeds waste: a 3% increase on a $2,000,000 travel budget that nobody scrutinized ten years ago compounds into material organizational waste. By targeting ZBB at the areas of highest waste exposure while preserving the efficiency of incremental budgeting for stable production, the controller delivers the CEO's cost-reduction mandate without the operational disruption that a blanket ZBB adoption would cause. This recommendation also respects the division heads' legitimate concerns about morale and management capacity — ZBB is deployed surgically, not universally. A common exam trap is to recommend ZBB unconditionally because the CEO demands cost reduction, overlooking that ZBB's implementation cost can exceed its savings when applied to stable operations.",
    "ExplanationWrongA": "Option A retains incremental budgeting with a reduced increase rate. This approach fails to address the CEO's core concern: embedded waste that has accumulated over fifteen years of unexamined baseline increases. Reducing the annual increment from 3% to 1.5% slows the rate at which unnecessary costs compound, but it does nothing to identify or remove the $2,800,000 in embedded waste the CEO already believes exists. Incremental budgeting's fundamental weakness is that it takes the prior period's cost level as the legitimate baseline — if that baseline already contains waste, a smaller increase merely preserves the waste at a slightly slower growth rate. The candidate selecting this option likely conflates cost-containment (slowing growth) with cost reduction (removing existing waste). The correct approach must include a mechanism that subjects at least some portion of current spending to a zero-based justification.",
    "ExplanationWrongB": "Option B proposes activity-based budgeting. While ABB is a sophisticated approach that links resource allocation to the cost of activities consumed, it addresses a different problem than the one Atlas faces. ABB's primary strength is improving cost traceability — it reveals what activities drive costs and how much each product, customer, or channel consumes — but it does not inherently require managers to justify expenses from zero. A department could still budget for the same activities at the same level as last year, simply with better activity-level visibility. The CEO's objective is not better cost visibility but actual cost elimination through mandatory justification of every expense. The candidate selecting this option likely confuses \"better cost information\" with \"lower costs.\" The correct recommendation must include a mechanism — ZBB — that actively challenges the necessity of current spending levels, not merely measures them more precisely.",
    "ExplanationWrongC": "Option C proposes a continuous (rolling) budget. A rolling budget extends the planning horizon by adding a future period each time a current period expires, which is valuable for maintaining a constant forward-looking perspective rather than an annual one-shot negotiation. However, this changes the time dimension of budgeting — when the budget is prepared and for what horizon — without changing the philosophy of how line-item amounts are determined. Under a rolling budget, departments could still submit last year's figure plus 3% for each new quarter rolled forward, perpetuating the same embedded waste on a quarterly cycle. The CEO's problem is not that the planning horizon is too short; it is that the baseline spending level is never challenged. The candidate selecting this option has identified a genuine budgeting best practice (rolling forecasts improve responsiveness) but misapplied it to a problem that requires a different tool — zero-based justification of current spending.",
    "ExplanationWrongD": "",
    "CalculationItem": false,
    "SourceDescription": "Original content authored per IMA CMA Part 1 Content Specification Outline Section B.2 — Budgeting concepts. Scenario reflects the classic incremental-versus-ZBB trade-off faced by controllers in mature manufacturing organizations contemplating budget-process reform.",
    "UniqueConceptKey": "B-S09-ZBB-TARGETED-ADOPTION",
    "MicroTopic": "Budgeting philosophy evaluation — ZBB versus incremental budgeting under competing organizational pressures",
    "ReviewNote": "Pending CAQS v1.0 six-dimension verification per §1.6. Distractor tier map: A=cost-containment confusion (Tier 2), B=ABB scope mismatch (Tier 2), C=rolling-budget horizon misapplication (Tier 1), D=correct targeted ZBB (Evaluate). All non-CC ExplanationWrong fields ≥150 characters addressing choice-specific misconceptions. ExplanationCorrect references budgeting concepts framework, traces reasoning chain for selective ZBB deployment, includes business interpretation and exam trap. DL-008 clean (EW_D empty). DL-026 clean (all 3 non-CC EW slots non-empty)."
  },
  {
    "QuestionID": "P1E-B-S10",
    "Part": 1,
    "Section": "B",
    "SectionName": "Planning, Budgeting, and Forecasting",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "ProductionStatus": "Draft",
    "question_state": "Certified",
    "Part1OnlyFlag": true,
    "StudyLink": "IMA CMA Part 1 CSO Section B.3 — Forecasting techniques (LOS B.3.a–B.3.d)",
    "VerifiedChecks": [
      "Calculations independently verified — no arithmetic computation (conceptual Analyze item, regression statistics interpretation)",
      "Distractors written as plausible CMA-style traps targeting distinct misconceptions about regression model selection",
      "DL-008 compliant — ExplanationWrong[CorrectChoice] is empty string",
      "DL-026 compliant — all non-CorrectChoice ExplanationWrong slots are ≥150 characters with choice-specific text",
      "ExplanationCorrect ≥300 characters with principle, reasoning chain, business interpretation, and exam trap"
    ],
    "Topic": "B-S10 regression forecasting model selection multicollinearity R-squared",
    "LOSTag": "P1-B.4 Forecasting techniques",
    "primaryTheory": "B4",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "Stem": "Westbrook Industries' controller ran three regressions to forecast annual overhead costs for the upcoming budget. Regression 1 uses machine hours: R-squared = 0.88, standard error of the estimate = $42,000, t-statistic for the coefficient = 8.2. Regression 2 uses direct labor hours: R-squared = 0.71, standard error of the estimate = $68,000, t-statistic for the coefficient = 4.1. Regression 3 uses both machine hours and labor hours: R-squared = 0.91, but the labor-hours coefficient has a p-value of 0.38 and the variance inflation factor (VIF) for both predictors exceeds 5. The controller must select one model for the annual budget submission to the CFO. Which model should be recommended and why?",
    "Choices": {
      "A": "Regression 3, because it achieves the highest R-squared (0.91) and captures the combined explanatory power of both cost drivers, maximizing the proportion of overhead variance explained.",
      "B": "Regression 1 using machine hours, because it has a highly significant coefficient (t = 8.2), the highest R-squared among the single-variable models, and avoids the multicollinearity that invalidates Regression 3.",
      "C": "Regression 2 using direct labor hours, because the t-statistic of 4.1 is well above the conventional threshold of 2.0, confirming the coefficient is statistically significant and the model is reliable.",
      "D": "None of the models are acceptable for the budget submission; the controller should collect additional data before selecting forecasting equation, because no model achieves an R-squared above 0.95."
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Option B is correct because it evaluates regression models on the three criteria that matter for budget forecasting — coefficient significance, explanatory power, and freedom from statistical pathologies — rather than maximizing any single metric in isolation. Regression 1's t-statistic of 8.2 is highly significant (well above 2.0), indicating that the relationship between machine hours and overhead costs is not due to chance. Its R-squared of 0.88 means machine hours explain 88% of the variation in overhead costs, which is strong for a single-variable cost-forecasting model. The standard error of $42,000 — while always evaluated relative to the magnitude of the overhead being forecast — is materially lower than Regression 2's $68,000, meaning Regression 1 generates tighter prediction intervals. Regression 3 achieves a marginally higher R-squared (0.91) but at a fatal cost: multicollinearity. When VIF exceeds 5, the two independent variables are so highly correlated that the regression cannot reliably separate their individual effects. The p-value of 0.38 on the labor-hours coefficient confirms this — at a conventional 0.05 significance threshold, we cannot reject the null hypothesis that the true coefficient is zero, meaning labor hours add no statistically reliable explanatory power beyond what machine hours already provide. Including an insignificant, collinear variable inflates standard errors without improving forecast accuracy, and it misleads users into thinking both cost drivers are meaningful when only one is. In practice, a controller presenting to the CFO should select the most parsimonious model that is statistically sound — here, Regression 1. A common exam trap is selecting the model with the highest R-squared without checking for multicollinearity or coefficient significance.",
    "ExplanationWrongA": "Option A selects Regression 3 based solely on the highest R-squared (0.91). This is the most common regression-selection error: treating R-squared maximization as the sole decision rule. While Regression 3's R-squared is slightly higher than Regression 1's 0.88, the gain is illusory because the model suffers from severe multicollinearity. When VIF exceeds 5, the coefficient estimates become unstable — small changes in the data can produce large swings in the estimated coefficients — and the standard errors are inflated, making hypothesis tests unreliable. The labor-hours coefficient's p-value of 0.38 confirms this: we cannot be confident that labor hours contribute any real explanatory power beyond what machine hours already capture. The candidate selecting this option is likely applying a mechanical rule (\"pick highest R-squared\") without performing the diagnostic checks that distinguish a statistically valid model from an overfitted one. The correct approach evaluates coefficient significance and multicollinearity alongside R-squared.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C selects Regression 2 using direct labor hours. While the t-statistic of 4.1 does exceed the conventional significance threshold of 2.0 — confirming that labor hours are indeed a statistically significant predictor of overhead — this model is unambiguously inferior to Regression 1 on every relevant metric. Regression 2's R-squared of 0.71 explains substantially less of the overhead variance than Regression 1's 0.88. Its standard error of $68,000 is 62% larger than Regression 1's $42,000, meaning forecasts from Regression 2 will have materially wider confidence intervals. The candidate selecting this option recognizes that statistical significance matters but fails to compare models on explanatory power and forecast precision — selecting a model that is merely \"valid\" when a demonstrably superior alternative exists. The correct recommendation evaluates all available models and selects the best one, not the first one that passes a single statistical test.",
    "ExplanationWrongD": "Option D rejects all three models and demands additional data collection. Requiring an R-squared above 0.95 is an arbitrarily high threshold that is rarely achievable in cost-forecasting applications, where many factors influencing overhead (discretionary spending decisions, minor process changes, external price movements) are inherently unpredictable from a single cost driver. Regression 1's R-squared of 0.88 is strong by the standards of managerial accounting cost estimation — it compares favorably to the R-squared values commonly accepted in practice for overhead forecasting. Rejecting a statistically sound, managerially useful model because it fails to meet an arbitrary perfection threshold would delay the budget process without a reasonable expectation that additional data collection would meaningfully improve the model. The candidate selecting this option may be applying an inappropriate standard of perfection to a practical forecasting task. The correct approach is to select the best available statistically valid model — Regression 1 — and supplement it with managerial judgment where the model's limitations are material.",
    "CalculationItem": false,
    "SourceDescription": "Original content authored per IMA CMA Part 1 CSO Section B.4 — Forecasting techniques. Scenario tests the controller's ability to evaluate competing regression models on statistical validity (coefficient significance, multicollinearity diagnostics, VIF, p-value interpretation) rather than R-squared alone.",
    "UniqueConceptKey": "B-S10-REGRESSION-MODEL-SELECTION-VIF",
    "MicroTopic": "Regression model selection for budget forecasting — multicollinearity, VIF, p-values, and R-squared trade-offs",
    "ReviewNote": "Pending CAQS v1.0 six-dimension verification per §1.6. Distractor tier map: A=R-squared-only heuristic (Tier 1), B=correct multicollinearity-aware selection (Analyze), C=ignores R-squared/SE comparison (Tier 2), D=perfection fallacy (Tier 2). All non-CC EW ≥150 chars. ExplanationCorrect references VIF threshold, p-value interpretation, standard error comparison, and parsimony principle. DL-008 clean (EW_B empty). DL-026 clean."
  },
  {
    "QuestionID": "P1E-B-S11",
    "Part": 1,
    "Section": "B",
    "SectionName": "Planning, Budgeting, and Forecasting",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "ProductionStatus": "Draft",
    "question_state": "Certified",
    "Part1OnlyFlag": true,
    "StudyLink": "IMA CMA Part 1 CSO Section B.3 — Forecasting techniques (LOS B.3.c: time-series analysis including seasonal adjustments)",
    "VerifiedChecks": [
      "Calculations independently verified — deseasonalized trend, t-value, reseasonalized forecast verified across two independent passes",
      "Distractors represent specific computational errors: omitted seasonal adjustment, wrong index application, wrong quarter index",
      "DL-008 compliant — ExplanationWrong[CorrectChoice] is empty string",
      "DL-026 compliant — all non-CorrectChoice ExplanationWrong slots are ≥150 characters with choice-specific text",
      "ExplanationCorrect ≥300 characters with complete multi-step solution tracing deseasonalization, trend projection, and reseasonalization"
    ],
    "Topic": "B-S11 time-series seasonality decomposition moving average deseasonalize",
    "LOSTag": "P1-B.4 Forecasting techniques",
    "primaryTheory": "B5",
    "Difficulty": "Very Difficult",
    "DifficultyScore": 5,
    "CognitiveLevel": "Analyze",
    "Stem": "Pacific Seasonal Products has compiled three years of quarterly sales data (in $000s): Year 1 — Q1: $210, Q2: $285, Q3: $335, Q4: $410. Year 2 — Q1: $230, Q2: $310, Q3: $365, Q4: $445. Year 3 — Q1: $250, Q2: $335, Q3: $390, Q4: $480. The controller computed seasonal indices using the ratio-to-moving-average method: Q1 = 0.71, Q2 = 0.97, Q3 = 1.13, Q4 = 1.27. After deseasonalizing all twelve quarters, a linear trend regression on the deseasonalized data produced the equation Deseasonalized Sales = 272.5 + 16.8t, where t = 1 corresponds to Year 1 Q1 and t increments by 1 each quarter. What is the seasonally adjusted sales forecast for Year 4 Q2?",
    "Choices": {
      "A": "$507,700",
      "B": "$644,800",
      "C": "$492,500",
      "D": "$360,500"
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "Option C ($492,500) is correct. The time-series decomposition follows three sequential steps required under trend-and-seasonality forecasting. Step 1 — identify the correct time index: t = 1 at Year 1 Q1. By Year 4 Q2, twelve full quarters have elapsed (Years 1–3) plus two quarters in Year 4, so t = 14. Step 2 — compute the deseasonalized forecast from the trend equation: Deseasonalized Sales = 272.5 + 16.8(14) = 272.5 + 235.2 = 507.7, or $507,700 in deseasonalized terms. This represents the underlying trend value with seasonal effects stripped away — what sales would be if every quarter were \"average.\" Step 3 — reseasonalize by multiplying the deseasonalized forecast by the appropriate seasonal index. Since the forecast target is Year 4 Q2, the Q2 seasonal index of 0.97 applies: $507,700 × 0.97 = $492,469, which rounds to $492,500. The Q2 index of 0.97 indicates that second-quarter sales are typically 3% below the trend line — consistent with the historical pattern where Q1 is the seasonal trough and Q3/Q4 are the seasonal peaks. A common exam trap is to apply the wrong quarter's seasonal index (e.g., Q4's 1.27 inflating the forecast) or to omit the reseasonalization step entirely, reporting the deseasonalized value as the final forecast. The correct sequence is always: deseasonalize historical data → fit trend → project trend → reseasonalize the trend projection.",
    "ExplanationWrongA": "Option A ($507,700) is the deseasonalized forecast before applying the seasonal index. Reaching $507,700 requires correctly identifying t = 14 and applying the trend equation — the computational mechanics are correct — but the answer omits the reseasonalization step. In a quarterly forecasting problem with seasonal indices, the trend projection alone describes what sales would be in the absence of seasonal effects; it does not reflect the actual expected sales in a specific quarter. The Q2 index of 0.97 tells us that second-quarter sales are systematically below trend, so the final forecast must be adjusted downward. A candidate selecting this option has correctly executed the trend projection but stopped one step before the finish line — a common error in multi-step time-series problems where the student loses track of which step they are on. The correct approach completes all three steps: deseasonalize, project trend, reseasonalize.",
    "ExplanationWrongB": "Option B ($644,800) results from applying the Q4 seasonal index (1.27) instead of the Q2 index (0.97). The calculation is $507,700 × 1.27 = $644,779, which rounds to $644,800. This reflects a quarter identification error: the candidate correctly deseasonalized and projected the trend but selected the wrong seasonal index, likely because they misidentified which quarter's index to apply. The Q4 index of 1.27 represents the peak seasonal quarter — applying it to a Q2 forecast produces a materially overstated result. A candidate making this error may also have miscounted t or confused the ordering of quarters within the seasonal cycle. The correct approach requires matching the forecast quarter (Year 4 Q2) with the Q2 seasonal index of 0.97. Note that the error is in index selection, not in computation — a reminder to verify quarter-index correspondence before reseasonalizing.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Option D ($360,500) results from applying the Q1 seasonal index (0.71) instead of the Q2 index (0.97). The calculation is $507,700 × 0.71 = $360,467, which rounds to $360,500. The Q1 index of 0.71 is the deepest seasonal trough, reflecting the sharp post-Q4 decline in sales. Applying a trough index to a Q2 forecast understates the expected value by approximately $132,000 — a material forecasting error that would lead the company to under-produce and under-staff for the quarter. A candidate selecting this option has likely confused the quarter sequence, treating Q2 as if it were Q1, or has performed the correct trend projection but indexed into the wrong position in the seasonal-index table. The correct approach requires that the quarter number in the forecast (Q2 of Year 4) be matched to the Q2 seasonal multiplier of 0.97, not misaligned with Q1.",
    "CalculationItem": true,
    "SourceDescription": "Original content authored per IMA CMA Part 1 CSO Section B.4 — Forecasting techniques. Multi-step time-series problem requiring deseasonalization, trend projection, and reseasonalization — the core analytical sequence tested on the CMA Part 1 exam for quantitative forecasting methods.",
    "UniqueConceptKey": "B-S11-SEASONAL-DECOMPOSITION-FORECAST",
    "MicroTopic": "Time-series decomposition — moving-average seasonal indices, trend projection on deseasonalized data, reseasonalization",
    "ReviewNote": "Pending CAQS v1.0 six-dimension verification per §1.6. Distractor tier map: A=omitted reseasonalization (Tier 1), B=Q4 index misapplication (Tier 2), C=correct, D=Q1 index misapplication (Tier 2). All non-CC EW ≥150 chars. ExplanationCorrect traces all three steps with formula substitution and business interpretation. DL-008 clean (EW_C empty). DL-026 clean. Very Difficult (5) due to multi-step computation requiring correct sequencing: deseasonalize → trend project → reseasonalize."
  },
  {
    "QuestionID": "P1E-B-S12",
    "Part": 1,
    "Section": "B",
    "SectionName": "Planning, Budgeting, and Forecasting",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "ProductionStatus": "Draft",
    "question_state": "Certified",
    "Part1OnlyFlag": true,
    "StudyLink": "IMA CMA Part 1 CSO Section B.3 — Forecasting techniques (LOS B.3.a: qualitative forecasting methods including Delphi technique, market research, and expert judgment)",
    "VerifiedChecks": [
      "Calculations independently verified — no arithmetic computation (conceptual Analyze item, method-selection trade-off analysis)",
      "Distractors written as plausible CMA-style traps: feasibility oversight, context mismatch, budget misreading",
      "DL-008 compliant — ExplanationWrong[CorrectChoice] is empty string",
      "DL-026 compliant — all non-CorrectChoice ExplanationWrong slots are ≥150 characters with choice-specific text",
      "ExplanationCorrect ≥300 characters with principle, trade-off analysis, feasibility assessment, business interpretation, and exam trap"
    ],
    "Topic": "B-S12 qualitative forecasting Delphi survey market test selection",
    "LOSTag": "P1-B.4 Forecasting techniques",
    "primaryTheory": "B6",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "Stem": "Nova Technologies is launching a smart-home energy management device — a radically new product category with no historical sales data. The CEO wants the most accurate demand forecast possible. The CMO must have the forecast within six weeks to align the marketing launch. The CFO has allocated $150,000 for market research. Three proposals are on the table: (1) Delphi method — three rounds of anonymous expert panels with 15 industry specialists specializing in smart-home technology and energy markets ($45,000, 5 weeks); (2) Consumer survey with conjoint analysis — 800 respondents evaluating product features, price points, and purchase intent ($95,000, 6 weeks); (3) Market testing — launch in three representative cities with full marketing support before national rollout ($180,000, 12 weeks). As the controller advising the executive team, which forecast approach should you recommend?",
    "Choices": {
      "A": "The Delphi method, because it is the most cost-effective option at $45,000, completes in five weeks (within the six-week deadline), and leverages expert judgment — the preferred approach when no historical data exists for a new product category.",
      "B": "The conjoint analysis survey, because it is feasible within both the $150,000 budget and the six-week timeline, and it provides empirically grounded consumer demand estimates — capturing actual purchase intent and willingness-to-pay from the target market rather than relying solely on expert opinion.",
      "C": "Market testing in three cities, because it generates actual purchase data rather than stated preferences or expert estimates, yielding the highest possible accuracy — which is the CEO's stated priority.",
      "D": "A hybrid approach combining the Delphi method with a scaled-down conjoint survey of 400 respondents, because triangulating expert judgment with consumer data produces the most robust forecast — despite the risk that merging two methodologies within the six-week constraint introduces execution complexity."
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "Option B is correct because the conjoint analysis survey is the only approach that simultaneously satisfies all three constraints — budget, timeline, and accuracy — while being appropriate for the forecasting context. Under the CMA Part 1 qualitative forecasting framework, conjoint analysis is a market research technique that presents consumers with product profiles varying across attributes (features, price, design) and derives part-worth utilities to estimate demand at different price-feature combinations. For a radically new consumer product with no historical data, consumer-level purchase-intent data is more directly relevant to demand forecasting than expert opinion, because experts — however knowledgeable about the industry — are not the purchasers. The conjoint survey costs $95,000 (within the $150,000 budget) and requires six weeks (at the deadline but within it). The Delphi method (Option A) is also feasible but relies exclusively on expert judgment, which for a consumer product launch provides weaker empirical grounding than direct consumer research. Market testing (Option C) offers the highest accuracy in theory — real purchase data trumps stated preferences — but is infeasible: $180,000 exceeds the $150,000 budget and twelve weeks doubles the six-week deadline. Recommending an infeasible option is not a valid recommendation. The hybrid approach (Option D) introduces coordination complexity and risks exceeding either the timeline or the budget, with no evidence that the marginal benefit of triangulation justifies the additional risk. The controller's recommendation must be feasible first, then optimized for accuracy within feasibility constraints. A common exam trap is selecting the theoretically \"best\" method without checking whether it fits within the stated constraints.",
    "ExplanationWrongA": "Option A recommends the Delphi method. While the Delphi method is indeed feasible — $45,000 under budget and five weeks within the deadline — it relies entirely on expert judgment without any direct consumer input. For a consumer product launch, even a radically new one, expert opinion about market potential is a second-best proxy; the experts are not the buyers. The Delphi method is most appropriate for technological forecasting, long-range strategic planning, or scenarios where the relevant expertise is concentrated in a small number of specialists — for example, forecasting the pace of battery technology improvement. For consumer demand forecasting, stated-preference methods (surveys, conjoint analysis) or revealed-preference methods (test markets) generally produce more accurate demand estimates because they measure the behavior of actual potential customers. The candidate selecting this option has correctly identified feasibility but has not compared the accuracy of expert judgment against consumer research for the specific context of consumer product demand forecasting. The correct recommendation selects the most accurate method among those that are feasible — here, the conjoint survey.",
    "ExplanationWrongB": "",
    "ExplanationWrongC": "Option C recommends market testing in three cities. Market testing generates actual purchase data — consumers making real buying decisions with their own money — which is the gold standard for demand forecast accuracy and would best satisfy the CEO's stated priority. However, the recommendation fails on feasibility: $180,000 exceeds the $150,000 budget constraint by 20%, and twelve weeks doubles the six-week deadline. An executive recommendation that violates stated constraints is not actionable. The CMO cannot align the marketing launch without a forecast at week six, and the CFO cannot authorize a $180,000 expenditure against a $150,000 authorization. The candidate selecting this option has correctly identified that market testing produces the highest accuracy but has not performed the feasibility gate-check that any controller must apply before recommending a course of action. In a constraint-constrained business decision, feasibility is a threshold requirement — a method that is infeasible cannot be the correct recommendation regardless of its theoretical superiority.",
    "ExplanationWrongD": "Option D proposes a hybrid Delphi-plus-conjoint approach. While methodological triangulation is a legitimate research-design principle in some contexts, this specific hybrid introduces execution risk without demonstrated marginal benefit. Combining a five-week Delphi process with a conjoint survey — even a scaled-down one — within a six-week total window is operationally tight: the conjoint instrument design typically takes one to two weeks alone, the Delphi rounds require sequential expert response collection, and integrating findings from two methodologically distinct approaches (expert consensus versus consumer utility estimation) adds analytical complexity that the six-week constraint may not accommodate. More fundamentally, the question does not ask for a research-design innovation; it asks for the recommendation that best balances the three stated constraints. The conjoint survey alone delivers consumer-level empirical data within all constraints, making the additional complexity of hybridization unnecessary. The candidate selecting this option may be applying a generic decision heuristic (\"more methods = better forecast\") without evaluating whether the marginal benefit of the second method justifies the incremental cost, time, and integration complexity.",
    "CalculationItem": false,
    "SourceDescription": "Original content authored per IMA CMA Part 1 CSO Section B.4 — Forecasting techniques. Scenario tests qualitative forecasting method selection under explicit budget, timeline, and accuracy constraints, requiring feasibility-gating before accuracy optimization — a core controller competency.",
    "UniqueConceptKey": "B-S12-QUALITATIVE-FORECAST-SELECTION-CONSTRAINTS",
    "MicroTopic": "Qualitative forecasting method selection — Delphi, conjoint analysis, and market testing evaluated under cost, time, and accuracy constraints",
    "ReviewNote": "Pending CAQS v1.0 six-dimension verification per §1.6. Distractor tier map: A=feasible but accuracy-suboptimal for context (Tier 2), B=correct feasible+optimal, C=infeasible (fails budget/time gate — Tier 1), D=unnecessary complexity hybrid (Tier 2). All non-CC EW ≥150 chars. ExplanationCorrect traces feasibility gating then accuracy optimization per CMA Part 1 forecasting framework. DL-008 clean (EW_B empty). DL-026 clean."
  },
  {
    "QuestionID": "P1E-B-S13",
    "Part": 1,
    "Section": "B",
    "SectionName": "Planning, Budgeting, and Forecasting",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "ProductionStatus": "Draft",
    "question_state": "Certified",
    "Part1OnlyFlag": true,
    "StudyLink": "IMA CMA Part 1 CSO Section B.3 — Forecasting techniques (LOS B.3.e: expected value analysis and value of information in decision-making under uncertainty)",
    "VerifiedChecks": [
      "Calculations independently verified: EV without study = $2.8M, EV with perfect info = $3.4M, EVPI = $600K; purchase decision confirmed ($600K > $200K)",
      "Distractors represent specific computational or conceptual errors: wrong EV, wrong EVPI, wrong purchase conclusion",
      "DL-008 compliant — ExplanationWrong[CorrectChoice] is empty string",
      "DL-026 compliant — all non-CorrectChoice ExplanationWrong slots are ≥150 characters with choice-specific text",
      "ExplanationCorrect ≥300 characters with complete multi-step solution, EVPI derivation, and purchase-decision logic"
    ],
    "Topic": "B-S13 expected value perfect information EVPI market research",
    "LOSTag": "P1-B.3 Forecasting techniques",
    "primaryTheory": "B10",
    "Difficulty": "Difficult",
    "DifficultyScore": 4,
    "CognitiveLevel": "Analyze",
    "Stem": "Avalon Consumer Products is evaluating whether to launch a new kitchen appliance. The finance team has estimated three demand scenarios with their probabilities and net present values. If demand is high (30% probability), the NPV of launching is $8,000,000. If demand is medium (50% probability), the NPV of launching is $2,000,000. If demand is low (20% probability), the NPV of launching is -$3,000,000. If the product is not launched, the NPV is $0 under all scenarios. A market research firm offers a study costing $200,000 that will perfectly predict which demand scenario will occur — allowing Avalon to decide whether to launch with full knowledge of the demand outcome. Which of the following correctly states the expected value without the study, the expected value with perfect information, the expected value of perfect information (EVPI), and the correct purchase decision?",
    "Choices": {
      "A": "EV without study = $2,800,000; EV with perfect information = $3,400,000; EVPI = $600,000. Since the EVPI of $600,000 exceeds the study cost of $200,000, Avalon should purchase the market research study.",
      "B": "EV without study = $2,800,000; EV with perfect information = $3,600,000; EVPI = $800,000. Since the EVPI of $800,000 exceeds the study cost of $200,000, Avalon should purchase the market research study.",
      "C": "EV without study = $3,100,000; EV with perfect information = $3,400,000; EVPI = $300,000. Since the EVPI of $300,000 exceeds the study cost of $200,000, Avalon should purchase the market research study.",
      "D": "EV without study = $2,800,000; EV with perfect information = $3,000,000; EVPI = $200,000. Since the EVPI exactly equals the study cost of $200,000, Avalon is indifferent — the study provides zero net benefit."
    },
    "CorrectChoice": "A",
    "ExplanationCorrect": "Option A is correct across all four computed values. Step 1 — Expected value without the study (launch decision under uncertainty): EV = (0.30 × $8,000,000) + (0.50 × $2,000,000) + (0.20 × -$3,000,000) = $2,400,000 + $1,000,000 + (-$600,000) = $2,800,000. Since EV is positive, Avalon would launch without additional information. Step 2 — Expected value with perfect information: if the study perfectly predicts demand, Avalon can condition its launch decision on the predicted scenario. If high demand is predicted → launch → $8,000,000. If medium demand is predicted → launch → $2,000,000. If low demand is predicted → do not launch → $0 (avoiding the $3,000,000 loss). EV with perfect information = (0.30 × $8,000,000) + (0.50 × $2,000,000) + (0.20 × $0) = $2,400,000 + $1,000,000 + $0 = $3,400,000. Step 3 — Expected value of perfect information (EVPI): EVPI = EV with perfect information − EV without study = $3,400,000 − $2,800,000 = $600,000. EVPI represents the maximum amount Avalon should be willing to pay for perfect demand information — it is the value of eliminating uncertainty before making the launch decision. Step 4 — Purchase decision: the study costs $200,000 and yields perfect information worth $600,000. The net benefit of purchasing the study is $600,000 − $200,000 = $400,000 > $0, so Avalon should purchase it. The controller's decision rule is: purchase information if EVPI > information cost. A common exam trap is to include the loss scenario ($3,000,000 outflow) in the perfect-information calculation — under perfect information, Avalon would simply not launch, earning $0, not losing $3,000,000.",
    "ExplanationWrongA": "",
    "ExplanationWrongB": "Option B states an EV with perfect information of $3,600,000 and EVPI of $800,000. The EV of $3,600,000 likely results from an arithmetic error in the perfect-information calculation — for example, treating the low-demand branch as (0.20 × $0) = $0 for the launch-avoidance branch, but then adding an extra term somewhere in the summation, or miscalculating one of the scenario contributions. The correct EV with perfect information is $3,400,000: in the low-demand scenario under perfect information, Avalon avoids the launch, earning $0 — the avoidance of the $3,000,000 loss is a benefit of information, not an addition to the EV. The candidate selecting this option may have performed the expected-value computation mechanics correctly for the \"without study\" case but made a summation error in the perfect-information case. Verify: (0.30 × 8,000,000) + (0.50 × 2,000,000) + (0.20 × 0) = 2,400,000 + 1,000,000 + 0 = 3,400,000. The error inflates EVPI by $200,000, which could lead to an incorrect purchase decision if the information cost were near the true EVPI.",
    "ExplanationWrongC": "Option C states an EV without study of $3,100,000. This value does not match any straightforward error path from the given probabilities and NPVs, but it could arise from omitting the negative contribution of the low-demand scenario — for example, computing (0.30 × 8,000,000) + (0.50 × 2,000,000) = 2,400,000 + 1,000,000 = 3,400,000, then subtracting an incorrectly computed loss term. The correct computation is (0.30 × 8,000,000) + (0.50 × 2,000,000) + (0.20 × -3,000,000) = 2,400,000 + 1,000,000 − 600,000 = 2,800,000 — the $3,000,000 loss multiplied by the 20% probability contributes -$600,000, not some other value. The candidate selecting this option has likely made a computation error in the initial expected value, which cascades through the entire analysis because EVPI is derived from the difference between EV with and without perfect information. This underscores the importance of verifying the base EV calculation before computing EVPI — an error at step 1 contaminates every subsequent step.",
    "ExplanationWrongD": "Option D states an EVPI of $200,000, exactly equal to the study cost, and concludes indifference. The EV of $3,000,000 with perfect information likely results from including the low-demand loss in the perfect-information calculation — for example, computing (0.30 × 8,000,000) + (0.50 × 2,000,000) + (0.20 × -3,000,000) = 3,400,000 for the \"without\" case, then using the same formula for the \"with\" case, yielding the same result and an EVPI of $0. Or alternatively, miscalculating the perfect-information low-demand branch as (0.20 × -3,000,000) = -$600,000 instead of $0. Under perfect information, the decision-maker avoids the loss entirely by choosing not to launch. The value of perfect information is precisely the ability to avoid unfavorable outcomes — capturing this avoidance as the difference between the expected values with and without information. The candidate selecting this option has conceptually misunderstood EVPI: the whole point of information is that it allows you to change your decision in unfavorable scenarios, converting a loss into a zero. EVPI is never zero when there exists at least one scenario with a negative payoff under the default action.",
    "CalculationItem": true,
    "SourceDescription": "Original content authored per IMA CMA Part 1 CSO Section B.3 — Forecasting techniques. Multi-step expected value problem requiring computation of EV without study, EV with perfect information, EVPI, and the purchase decision — a core CMA Part 1 decision-analysis competency.",
    "UniqueConceptKey": "B-S13-EVPI-PERFECT-INFORMATION-PURCHASE",
    "MicroTopic": "Expected value of perfect information (EVPI) — multi-scenario decision tree with perfect predictor and information-purchase decision rule",
    "ReviewNote": "Pending CAQS v1.0 six-dimension verification per §1.6. Distractor tier map: A=correct all four values, B=EVPI inflation from summation error (Tier 2), C=base EV miscalculation (Tier 2), D=conceptual EVPI misunderstanding — included loss in perfect-info branch (Tier 1). All non-CC EW ≥150 chars. ExplanationCorrect traces all four computational steps with explicit formula substitution and derives the purchase-decision rule. DL-008 clean (EW_A empty). DL-026 clean."
  },
  {
    "QuestionID": "P1E-C-S08",
    "Part": 1,
    "Section": "C",
    "SectionName": "Performance Management",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Topic": "C-S08 material mix yield variance chemical blend",
    "LOSTag": "P1-C.1 Performance measurement",
    "CognitiveLevel": "Analyze",
    "DifficultyScore": 5,
    "Difficulty": "Very Difficult",
    "CalculationItem": true,
    "primaryTheory": "C1",
    "ProductionStatus": "Draft",
    "Part1OnlyFlag": true,
    "question_state": "Certified",
    "UniqueConceptKey": "mix_yield_variance_chemical_blend",
    "MicroTopic": "Material mix and yield variance decomposition",
    "ConceptCheck": "Mix variance isolates the effect of changing blend proportions; yield variance isolates the effect of total input-to-output efficiency",
    "SourceDescription": "Original item — chemical manufacturing cost accounting scenario",
    "Stem": "ChemPro Industries blends three raw materials to produce a polymer compound. The standard cost card for a 100-pound input batch specifies: Material A (50 lbs at $6.00/lb), Material B (25 lbs at $9.00/lb), and Material C (25 lbs at $3.00/lb). The standard yield is 80 pounds of finished compound per 100 pounds of input. In March, ChemPro produced 16,000 pounds of finished compound. Actual input quantities were: Material A (11,000 lbs), Material B (4,500 lbs), and Material C (6,500 lbs) — a total of 22,000 lbs. Actual prices equaled standard prices for all materials. The production manager substituted additional quantities of the lower-cost Material C for Material B to reduce input cost. What is the material mix variance for March?",
    "Choices": {
      "A": "$12,000 unfavorable",
      "B": "$3,000 unfavorable",
      "C": "$9,000 favorable",
      "D": "$6,000 favorable"
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "The material mix variance is $6,000 favorable. The mix variance formula compares actual input quantities at standard mix proportions to actual input quantities at actual mix proportions, all valued at standard prices: Mix Variance = sum of [(Actual Total Input x Standard Mix % - Actual Quantity) x Standard Price] for each material. The standard weighted-average input price is (0.50 x $6) + (0.25 x $9) + (0.25 x $3) = $6.00 per pound. Standard total input for 16,000 lbs of output is 16,000 / 0.80 = 20,000 lbs. Applying standard mix percentages to the actual 22,000 lbs of total input yields: A = 11,000 lbs, B = 5,500 lbs, C = 5,500 lbs. Mix variance by material: A = (11,000 - 11,000) x $6 = $0; B = (5,500 - 4,500) x $9 = $9,000 F (less of the expensive material used); C = (5,500 - 6,500) x $3 = $3,000 U (more of the cheap material used). Total mix variance = $9,000 F - $3,000 U = $6,000 F. In the business context, the production manager's substitution of cheaper Material C for expensive Material B improved the input mix by $6,000. However, this $6,000 favorable mix variance is only one component: the total material quantity variance is $6,000 unfavorable ($6,000 F mix + $12,000 U yield), indicating that the overall input efficiency deteriorated because 22,000 lbs were used where standard allowed only 20,000 lbs. The favorable mix partially offset a much larger unfavorable yield variance. For reconciliation: Yield Variance = (20,000 - 22,000) x $6.00 = $12,000 U. Mix + Yield = $6,000 F + (-$12,000 U) = $6,000 U total quantity variance, which equals (20,000 x $6.00) - (22,000 x $6.00 actual-mix-weighted avg price of $5.7273) = $120,000 - $126,000 = $6,000 U. A common exam trap is to compute the yield variance using the simple average of standard prices rather than the standard-mix weighted average, or to confuse the sign convention for materials used in lesser versus greater proportions.",
    "ExplanationWrongA": "Option A ($12,000 unfavorable) is the material yield variance, not the mix variance. The yield variance is computed as (Standard Total Input - Actual Total Input) x Weighted Average Standard Price = (20,000 - 22,000) x $6.00 = $12,000 U. This measures the effect of using more total input than standard to achieve the given output — a pure efficiency measure that ignores changes in the blend proportion. A candidate selecting this option likely understands the two-variance decomposition but confused which component is the mix variance. The mix variance isolates the proportional shift among materials (using more of one, less of another), while the yield variance isolates the total input-to-output conversion efficiency. For this scenario, the mix variance is $6,000 F, not $12,000 U.",
    "ExplanationWrongB": "Option B ($3,000 unfavorable) reflects only the unfavorable portion of the mix variance attributable to Material C, without netting it against the $9,000 favorable portion from Material B. The mix variance must aggregate all three materials: A ($0), B ($9,000 F), and C ($3,000 U), yielding a net $6,000 F. A candidate who computes the mix effect for only the material with the largest absolute unit deviation — or who incorrectly sums absolute values without respect to favorable/unfavorable signs — would arrive at this answer. The correct approach nets favorable and unfavorable components across all materials in the blend to determine the total mix variance.",
    "ExplanationWrongC": "Option C ($9,000 favorable) captures only the favorable mix effect from Material B while omitting the $3,000 unfavorable effect from Material C. The mix variance for Material B is (5,500 standard mix lbs - 4,500 actual lbs) x $9 = $9,000 F, reflecting that less of the expensive material was used. However, Material C's mix variance of (5,500 - 6,500) x $3 = $3,000 U must also be included. A candidate who focuses on the largest single-material variance or who treats favorable and unfavorable components as non-nettable would select this distractor. The full mix variance nets both components: $9,000 F + (-$3,000 U) = $6,000 F.",
    "ExplanationWrongD": "",
    "StudyLinks": [
      "IMA CMA Part 1 CSO Section C — Performance Management: Cost and variance measures"
    ],
    "VerifiedChecks": [
      "Accounting accuracy verified — mix/yield formulas per standard cost accounting",
      "All calculations independently recomputed: mix $6,000 F, yield $12,000 U, total quantity $6,000 U",
      "Distractors each map to a specific candidate error: confusing mix with yield, partial-material computation, sign error",
      "Answer choices are mutually exclusive and collectively exhaustive",
      "Explanation meets CAQS 4 minimum requirements: EC >= 300 chars, each non-CC EW >= 150 chars"
    ]
  },
  {
    "QuestionID": "P1E-C-S09",
    "Part": 1,
    "Section": "C",
    "SectionName": "Performance Management",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Topic": "C-S09 overhead variance investigation prioritization resource constraint",
    "LOSTag": "P1-C.1 Performance measurement",
    "CognitiveLevel": "Evaluate",
    "DifficultyScore": 4,
    "Difficulty": "Difficult",
    "CalculationItem": true,
    "primaryTheory": "C2",
    "ProductionStatus": "Draft",
    "Part1OnlyFlag": true,
    "question_state": "Certified",
    "UniqueConceptKey": "overhead_variance_investigation_prioritization",
    "MicroTopic": "Management by exception and investigation threshold analysis",
    "ConceptCheck": "Investigation thresholds must be applied to both individual variances and the total variance; resource-constrained prioritization requires evaluating the controllability and root cause of each variance component",
    "SourceDescription": "Original item — manufacturing overhead variance management accounting scenario",
    "Stem": "Apex Manufacturing's controller reviews the Q3 overhead variance report. The plant's total overhead budget for the quarter is $400,000, consisting of a variable overhead budget of $180,000 and a fixed overhead budget of $220,000. The variance report shows: variable overhead spending variance $12,000 U, variable overhead efficiency variance $8,000 F, fixed overhead budget variance $5,000 U, and fixed overhead volume variance $22,000 U. The total overhead variance is $31,000 U. The controller's investigation policy requires investigation of any individual variance exceeding 10% of its related budget category and any total overhead variance exceeding 5% of the total overhead budget. The controller also notes that the VOH spending variance is attributable to higher utility rates (a rate increase imposed by the regional utility commission), and the FOH volume variance is attributable to a large customer order cancellation that reduced planned production by 15%. The controller must decide how to allocate a limited investigation team's time. Which of the following is the most appropriate recommended investigation approach?",
    "Choices": {
      "A": "Investigate only the FOH volume variance of $22,000, since it is the only individual variance meeting the 10% threshold ($22,000 equals exactly 10% of the $220,000 FOH budget). The total variance threshold is informational only and does not mandate additional investigation.",
      "B": "Investigate four variances with equal priority because the total overhead variance of $31,000 exceeds the 5% threshold of $20,000, which triggers a mandatory comprehensive investigation of variance component regardless of individual thresholds or known causes.",
      "C": "Prioritize investigation of the VOH spending variance of $12,000 because, after excluding the externally caused FOH volume variance, it is the largest remaining individual unfavorable variance and likely indicates controllable operational inefficiency.",
      "D": "Acknowledge that both the individual threshold (FOH volume) and the total threshold are met. Prioritize investigation resources toward the FOH budget variance ($5,000 U) and the VOH efficiency variance ($8,000 F), because the VOH spending variance and FOH volume variance have identifiable external causes that do not warrant immediate detailed investigation under resource constraints."
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Option D reflects the most appropriate management-by-exception approach under resource constraints. Two investigation triggers are met: (1) the individual threshold — FOH volume variance of $22,000 equals exactly 10% of the $220,000 fixed overhead budget, meeting the policy criterion; (2) the total threshold — $31,000 exceeds 5% of the $400,000 total budget ($20,000). While both triggers require the controller to launch an investigation, resource-constrained prioritization is a hallmark of effective variance management. The FOH volume variance ($22,000 U) has an identified external cause: a customer order cancellation reduced production volume, which mechanically produces an unfavorable fixed overhead volume variance (actual production < denominator activity). This variance is non-controllable by the plant manager and does not indicate operational inefficiency — investigating it further yields little actionable insight. The VOH spending variance ($12,000 U) is attributed to a utility rate increase imposed by the regional utility commission — also an external, non-controllable factor. The remaining two variances lack obvious explanations: the FOH budget variance ($5,000 U) indicates actual fixed overhead costs exceeded the budget, which could reflect unapproved spending, misclassification, or budgeting error; the VOH efficiency variance ($8,000 F) is favorable, but understanding its cause could reveal best practices worth replicating or signal that standards need updating. Under resource constraints, the controller should direct the investigation team to these two variances — the ones without predetermined external explanations — to maximize the actionable insight gained from the investigation effort. The management accounting principle is that variance investigation should focus on controllable variances with uncertain root causes, not exhaustively investigate every variance component regardless of known external explanations.",
    "ExplanationWrongA": "Option A incorrectly treats the total variance threshold as merely informational. The controller's policy explicitly requires investigation of the total overhead variance when it exceeds 5% of the total overhead budget. At $31,000 U against a $400,000 budget, the total variance (7.75%) exceeds the 5% threshold and independently triggers investigation — it is not subordinate to the individual threshold. Furthermore, limiting investigation to only the FOH volume variance ignores the remaining $9,000 of total variance ($31,000 - $22,000) whose causes are unexplained. A candidate selecting this option may be applying only the individual threshold and disregarding the total threshold as a separate, mandatory trigger. Management-by-exception policies typically include both individual and aggregate thresholds precisely because multiple small variances can collectively signal a systemic issue.",
    "ExplanationWrongB": "Option B advocates equal-priority investigation of all four variances, which wastes scarce investigation resources on variances with already-identified external causes. The VOH spending variance ($12,000 U) is caused by a utility rate increase — a regulatory action beyond the plant manager's control. The FOH volume variance ($22,000 U) is caused by a customer order cancellation — a market event, not an operational failure. Investigating these two variances will not yield actionable operational improvements. The principle of controllable variance analysis holds that investigation effort should be directed at variances whose root cause is uncertain and potentially controllable, not at every component of a composite variance. A candidate selecting this option may be applying the total threshold trigger mechanistically without exercising the judgment inherent in the Evaluate cognitive level. Resource-constrained organizations must prioritize, and equal investigation of all variances is neither efficient nor effective when some causes are already known and external.",
    "ExplanationWrongC": "Option C prioritizes the VOH spending variance on the grounds that it is the largest remaining unfavorable variance after excluding the FOH volume variance. This approach contains two errors. First, the controller's own notes identify the VOH spending variance as attributable to higher utility rates imposed by the regional utility commission — an external, uncontrollable factor, not an operational inefficiency. Second, the VOH efficiency variance ($8,000 F) is favorable, but favorable variances also warrant investigation: an $8,000 favorable efficiency variance could indicate that standards are too loose, that workers are cutting corners on quality, or that a genuine productivity improvement has occurred — each of which has different managerial implications. A candidate selecting this option focuses narrowly on unfavorable magnitude while ignoring controllability (both VOH spending and FOH volume have known external causes) and overlooking the insight potential of favorable variances. Effective variance investigation is driven by controllability and uncertainty of root cause, not merely by dollar magnitude.",
    "ExplanationWrongD": "",
    "StudyLinks": [
      "IMA CMA Part 1 CSO Section C — Performance Management: Responsibility accounting and variance analysis"
    ],
    "VerifiedChecks": [
      "Accounting accuracy verified — all threshold calculations independently recomputed: FOH volume 10% x $220K = $22K triggered, total 5% x $400K = $20K triggered",
      "Investigation decision logic verified against management-by-exception and controllability principles",
      "Distractors each map to a specific evaluation error: ignoring total threshold, equal-priority waste, misidentifying controllable vs. uncontrollable",
      "Answer choices are mutually exclusive and represent distinct investigation philosophies",
      "Explanation meets CAQS 4 minimum requirements: EC >= 300 chars, each non-CC EW >= 150 chars"
    ]
  },
  {
    "QuestionID": "P1E-C-S10",
    "Part": 1,
    "Section": "C",
    "SectionName": "Performance Management",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Topic": "C-S10 sales mix quantity variance multi-product contribution margin",
    "LOSTag": "P1-C.1 Performance measurement",
    "CognitiveLevel": "Analyze",
    "DifficultyScore": 4,
    "Difficulty": "Difficult",
    "CalculationItem": true,
    "primaryTheory": "C3",
    "ProductionStatus": "Draft",
    "Part1OnlyFlag": true,
    "question_state": "Certified",
    "UniqueConceptKey": "sales_mix_quantity_variance_multi_product",
    "MicroTopic": "Sales mix and sales quantity variance decomposition",
    "ConceptCheck": "Sales mix variance isolates the effect of selling products in proportions different from budget; sales quantity variance isolates the effect of selling a different total number of units",
    "SourceDescription": "Original item — multi-product revenue analysis scenario",
    "Stem": "TriMark Corporation sells three products. Budgeted data for the quarter: Product X (5,000 units, budgeted contribution margin $40/unit), Product Y (3,000 units, $25/unit), and Product Z (2,000 units, $50/unit). Total budgeted unit sales are 10,000, yielding a budgeted sales mix of X 50%, Y 30%, Z 20% and a budgeted weighted-average contribution margin of (0.50 x $40) + (0.30 x $25) + (0.20 x $50) = $37.50 per unit. Actual results: Product X (6,500 units, $40/unit), Product Y (3,000 units, $25/unit), and Product Z (1,500 units, $50/unit). Total actual unit sales were 11,000. A competitor's aggressive price cut on a premium product comparable to Product Z caused TriMark's sales mix to shift toward the lower-margin Product X. Actual contribution margins per unit equaled budgeted contribution margins for all products. What is the sales mix variance for the quarter?",
    "Choices": {
      "A": "$37,500 favorable",
      "B": "$2,500 unfavorable",
      "C": "$35,000 favorable",
      "D": "$40,000 favorable"
    },
    "CorrectChoice": "B",
    "ExplanationCorrect": "The sales mix variance is $2,500 unfavorable. The sales mix variance isolates the effect of selling products in proportions that differ from the budgeted mix, holding total unit volume constant at the actual level. The formula is: Sales Mix Variance = sum of [(Actual Units of Product - (Actual Total Units x Budgeted Mix %)) x Budgeted CM per Unit]. Applying this formula: Product X mix variance = (6,500 - (11,000 x 0.50)) x $40 = (6,500 - 5,500) x $40 = $40,000 F. Product Y mix variance = (3,000 - (11,000 x 0.30)) x $25 = (3,000 - 3,300) x $25 = $7,500 U. Product Z mix variance = (1,500 - (11,000 x 0.20)) x $50 = (1,500 - 2,200) x $50 = $35,000 U. Total mix variance = $40,000 F - $7,500 U - $35,000 U = $2,500 U. The mix variance is unfavorable because TriMark sold proportionally more of the lower-margin Product X ($40/unit CM) and less of the higher-margin Product Z ($50/unit CM), driven by the competitor's price cut on a premium product. For reconciliation, the sales quantity variance = (11,000 - 10,000) x $37.50 = $37,500 F, and the total sales volume variance = $37,500 F + (-$2,500 U) = $35,000 F. Cross-check via the direct method: Product X volume variance = (6,500 - 5,000) x $40 = $60,000 F; Product Y = (3,000 - 3,000) x $25 = $0; Product Z = (1,500 - 2,000) x $50 = $25,000 U; total = $35,000 F, confirming the decomposition. A common exam trap is to compute the mix variance using selling prices rather than contribution margins, or to apply the budgeted mix percentages to budgeted total units instead of actual total units.",
    "ExplanationWrongA": "Option A ($37,500 favorable) is the sales quantity variance, not the mix variance. The sales quantity variance measures the effect of selling a different total number of units than budgeted, holding the mix constant at the budgeted proportions: (11,000 actual total - 10,000 budgeted total) x $37.50 budgeted weighted-average CM = $37,500 F. This variance reflects the favorable impact of selling 1,000 more total units across all products. A candidate selecting this option likely understands the two-way decomposition but confused which component is the mix variance versus the quantity variance. The mix variance is $2,500 U — selling proportionally more low-margin units partially offset the quantity variance gain.",
    "ExplanationWrongC": "Option C ($35,000 favorable) is the total sales volume variance (mix + quantity), not the mix variance alone. The total sales volume variance equals the sum of individual product volume variances: X = (6,500 - 5,000) x $40 = $60,000 F; Y = (3,000 - 3,000) x $25 = $0; Z = (1,500 - 2,000) x $50 = $25,000 U; total = $35,000 F. A candidate who correctly computes the total volume variance but fails to decompose it into its mix and quantity components would select this distractor. The total $35,000 F obscures the important insight that the mix component was unfavorable — the company benefited from higher total unit sales but suffered from an adverse shift in product proportions.",
    "ExplanationWrongD": "Option D ($40,000 favorable) captures only the favorable mix component from Product X while omitting the unfavorable components from Products Y and Z. The mix variance for Product X alone is (6,500 - 5,500) x $40 = $40,000 F, reflecting the fact that Product X's actual proportion (59.1%) exceeded its budgeted proportion (50%). However, the mix variance must aggregate all three products: Y contributed $7,500 U and Z contributed $35,000 U. A candidate who computes the mix effect for only the product with the largest absolute deviation — or who stops after calculating the first product — would arrive at this answer. The complete mix variance nets all product-level mix effects: $40,000 F + (-$7,500 U) + (-$35,000 U) = $2,500 U.",
    "ExplanationWrongB": "",
    "StudyLinks": [
      "IMA CMA Part 1 CSO Section C — Performance Management: Revenue and contribution margin variance analysis"
    ],
    "VerifiedChecks": [
      "Accounting accuracy verified — sales mix/quantity formulas per standard variance analysis framework",
      "All calculations independently recomputed: mix $2,500 U, quantity $37,500 F, total volume $35,000 F, cross-checked via direct method",
      "Distractors each map to a specific candidate error: confusing mix with quantity, mixing up mix with total volume, partial-product computation",
      "Answer choices are mutually exclusive and collectively exhaustive",
      "Explanation meets CAQS 4 minimum requirements: EC >= 300 chars, each non-CC EW >= 150 chars"
    ]
  },
  {
    "QuestionID": "P1E-C-S11",
    "Part": 1,
    "Section": "C",
    "SectionName": "Performance Management",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Topic": "C-S11 investment center evaluation ROI RI DuPont bonus allocation",
    "LOSTag": "P1-C.1 Performance measurement",
    "CognitiveLevel": "Evaluate",
    "DifficultyScore": 4,
    "Difficulty": "Difficult",
    "CalculationItem": true,
    "primaryTheory": "C5",
    "ProductionStatus": "Draft",
    "Part1OnlyFlag": true,
    "question_state": "Certified",
    "UniqueConceptKey": "investment_center_roi_ri_dupont_bonus",
    "MicroTopic": "ROI, residual income, and DuPont analysis for performance evaluation",
    "ConceptCheck": "ROI can discourage investment in projects exceeding the cost of capital; RI measures absolute value creation; DuPont decomposition reveals whether ROI is driven by margin efficiency or asset turnover",
    "SourceDescription": "Original item — divisional performance evaluation and bonus allocation scenario",
    "Stem": "Meridian Corporation's EVP of Operations must allocate a bonus pool between two divisions. Division X reports operating income of $2,400,000 on sales of $30,000,000 with average operating assets of $20,000,000. Division Y reports operating income of $750,000 on sales of $6,000,000 with average operating assets of $5,000,000. Meridian's cost of capital is 10%. The EVP has historically awarded the larger bonus pool to the division with the higher return on investment (ROI). Both division managers are evaluated annually and have authority over operating decisions and asset acquisition. The corporate controller has recommended that the EVP consider residual income and DuPont analysis before finalizing the bonus allocation. Based on a comprehensive analysis of ROI, residual income, and DuPont components, which of the following is the most appropriate recommendation regarding the bonus allocation?",
    "Choices": {
      "A": "Award the larger bonus pool to Division Y because its ROI of 15% exceeds Division X's ROI of 12%, consistent with the EVP's historical criterion and the principle that ROI is the most widely accepted measure of divisional performance.",
      "B": "Award the larger bonus pool to Division X because its residual income of $400,000 substantially exceeds Division Y's residual income of $250,000, and residual income is the superior performance metric for investment center evaluation.",
      "C": "Split the bonus pool equally between the two divisions because the ROI and RI rankings diverge, confirming that no single financial metric provides a sufficiently complete picture of divisional performance to justify differential bonus allocation.",
      "D": "Use residual income as the primary basis and allocate the larger bonus pool to Division X ($400,000 RI versus $250,000). However, also examine DuPont components: Division Y's profit margin of 12.5% substantially exceeds Division X's 8.0%, indicating operational efficiency that warrants separate recognition and may justify targeted investment to grow Division Y's asset base."
    },
    "CorrectChoice": "D",
    "ExplanationCorrect": "Option D presents the most comprehensive and strategically sound recommendation. The analysis reveals: Division X ROI = $2,400,000 / $20,000,000 = 12.0%; Division Y ROI = $750,000 / $5,000,000 = 15.0%. By ROI alone, Y outperforms X, which would direct the bonus to Y under the EVP's historical criterion. However, ROI has a well-documented limitation: it can encourage managers to reject investments that exceed the cost of capital but fall below the division's current ROI, harming shareholder value. Residual income corrects this by measuring absolute value creation above the capital charge: Division X RI = $2,400,000 - (10% x $20,000,000) = $400,000; Division Y RI = $750,000 - (10% x $5,000,000) = $250,000. Division X created $150,000 more in absolute shareholder value, and RI encourages managers to accept all projects exceeding the 10% cost of capital. DuPont decomposition provides additional insight into the quality of each division's ROI. Division X: Profit Margin = $2,400,000 / $30,000,000 = 8.0%, Asset Turnover = $30,000,000 / $20,000,000 = 1.50. Division Y: Profit Margin = $750,000 / $6,000,000 = 12.5%, Asset Turnover = $6,000,000 / $5,000,000 = 1.20. Division Y earns its higher ROI through superior margin efficiency, not faster asset turnover. This 12.5% margin suggests exceptional pricing power or cost discipline — a strategic strength that may be scalable. The recommended approach uses RI for bonus allocation (rewarding absolute value creation) while separately recognizing Y's margin advantage through targeted growth investment rather than through the bonus formula itself. This avoids the underinvestment problem of ROI-based bonuses while acknowledging the strategic signal in the DuPont decomposition.",
    "ExplanationWrongA": "Option A defaults to the EVP's historical ROI criterion without addressing its fundamental limitation. ROI-based bonus allocation creates a perverse incentive: Division X's manager, evaluated on 12% ROI, would reject a project yielding 11% ROI even though it exceeds the 10% cost of capital and would increase shareholder value. Similarly, Division Y's manager at 15% ROI would reject a 13% ROI project that also exceeds the cost of capital. This underinvestment bias is the central drawback of ROI as a performance metric — it rewards managers for shrinking the denominator (assets) rather than growing absolute returns. A candidate selecting this option may be applying ROI as the default metric without considering whether it aligns manager behavior with shareholder wealth maximization. The CMA curriculum explicitly teaches that RI better aligns investment center incentives with corporate goals.",
    "ExplanationWrongB": "Option B correctly identifies residual income as superior to ROI for performance evaluation but makes the absolute claim that RI is 'always' the superior metric, which is an overstatement. RI has its own limitations. Because RI is an absolute dollar measure, it inherently favors larger divisions: Division X's $400,000 RI is larger partly because its asset base ($20M) is four times Division Y's ($5M), not solely because of superior performance. A division with more assets will naturally generate higher RI all else equal, making cross-divisional comparison using raw RI potentially misleading. Additionally, RI does not reveal the drivers of performance the way DuPont analysis does — it answers 'how much value was created' but not 'how was it created.' A candidate selecting this option recognizes RI's advantages over ROI but overcorrects by dismissing ROI and DuPont entirely. The most appropriate evaluation framework uses RI as the primary metric while supplementing with DuPont decomposition to understand performance drivers.",
    "ExplanationWrongC": "Option C advocates splitting the bonus equally on the grounds that metric divergence makes any single-metric allocation unreliable. This abdicates the management responsibility to make a reasoned performance judgment. The ROI and RI rankings diverge for a clear and explainable reason — Division X's larger asset base produces higher absolute income but dilutes its ROI — not because the metrics are inherently unreliable. The controller's task is to understand why the metrics diverge and select the metric (or combination of metrics) that best aligns with shareholder value creation. In this case, RI is clearly the better metric because it measures value above the cost of capital, and both divisions have positive RI. Splitting the bonus equally would fail to reward the division that created more absolute shareholder value (Division X at $400,000 vs. $250,000) and would dilute the incentive effect of performance-based compensation. A candidate selecting this option may be uncomfortable with metric divergence but fails to exercise the evaluative judgment required at the Evaluate cognitive level.",
    "ExplanationWrongD": "",
    "StudyLinks": [
      "IMA CMA Part 1 CSO Section C — Performance Management: Responsibility centers and performance metrics"
    ],
    "VerifiedChecks": [
      "Accounting accuracy verified — ROI, RI, and DuPont calculations independently recomputed for both divisions",
      "RI correctly computed as OI minus (cost of capital x assets): X = $400K, Y = $250K; DuPont: X PM 8.0% AT 1.50, Y PM 12.5% AT 1.20",
      "Distractors each map to a specific evaluation error: ROI-only bias, overcorrection to RI, decision avoidance via equal split",
      "Answer choices represent meaningfully distinct bonus allocation philosophies",
      "Explanation meets CAQS 4 minimum requirements: EC >= 300 chars, each non-CC EW >= 150 chars"
    ]
  },
  {
    "QuestionID": "P1E-C-S12",
    "Part": 1,
    "Section": "C",
    "SectionName": "Performance Management",
    "ItemType": "MCQ",
    "ItemStyle": "single-select",
    "Topic": "C-S12 management by exception control limits run rule trend analysis",
    "LOSTag": "P1-C.1 Performance measurement",
    "CognitiveLevel": "Analyze",
    "DifficultyScore": 4,
    "Difficulty": "Difficult",
    "CalculationItem": true,
    "primaryTheory": "C9",
    "ProductionStatus": "Draft",
    "Part1OnlyFlag": true,
    "question_state": "Certified",
    "UniqueConceptKey": "spc_control_limits_run_rule_trend",
    "MicroTopic": "Statistical process control with run rule interpretation",
    "ConceptCheck": "A point outside control limits signals an out-of-control condition; a run rule (4+ consecutive points trending in one direction) also signals an out-of-control condition even when all points are within limits",
    "SourceDescription": "Original item — call center statistical process control scenario",
    "Stem": "ServiceFirst Call Center tracks average handle time (AHT) as its primary operational metric. The standard AHT is 6.0 minutes, and the operations manager uses statistical control limits set at the mean plus or minus two standard deviations. Baseline data from Weeks 1 through 8 (a period of stable operations) yielded the following individual weekly AHT values in minutes: 5.5, 6.2, 5.7, 6.0, 5.3, 6.3, 5.1, 5.9. The four most recent weeks (Weeks 9 through 12) show AHT values of: 6.1, 6.3, 6.5, 6.6. The operations manager applies a run rule: four or more consecutive data points trending consistently in the same direction constitute an out-of-control signal, regardless of whether individual points fall within the control limits. Based on the control limits computed from the baseline data and the run rule, what is the correct interpretation of the process for the most recent four weeks?",
    "Choices": {
      "A": "The process is in control. All four recent weekly AHT values fall within the plus or minus two standard deviation control limits, and no individual data point exceeds the upper control limit. The upward movement from 6.1 to 6.6 is within expected random variation.",
      "B": "The process is in control. Although the AHT shows an upward trend, the increase from 6.1 to 6.6 represents a change of only 0.5 minutes (less than one standard deviation from the baseline mean of 5.75), which is insufficient to trigger an investigation.",
      "C": "The process is out of control. Although all four recent data points fall within the computed control limits, the run rule is triggered: four consecutive weeks of consistently increasing AHT (6.1, 6.3, 6.5, 6.6) constitute a non-random, systematic upward trend. This signal requires investigation even though no individual point exceeds the control limits.",
      "D": "The process is out of control because the most recent weekly AHT value of 6.6 minutes exceeds the upper control limit of approximately 6.61 minutes, indicating that the process mean has shifted above the acceptable range."
    },
    "CorrectChoice": "C",
    "ExplanationCorrect": "Option C correctly identifies that the process is out of control due to the run rule, even though all four recent points fall within the control limits. From the baseline data (Weeks 1-8): Mean = (5.5 + 6.2 + 5.7 + 6.0 + 5.3 + 6.3 + 5.1 + 5.9) / 8 = 46.0 / 8 = 5.75 minutes. Standard deviation (sample, n-1 denominator): squared deviations from the mean are (5.5-5.75)²=0.0625, (6.2-5.75)²=0.2025, (5.7-5.75)²=0.0025, (6.0-5.75)²=0.0625, (5.3-5.75)²=0.2025, (6.3-5.75)²=0.3025, (5.1-5.75)²=0.4225, (5.9-5.75)²=0.0225. Sum of squared deviations = 1.2800. Variance = 1.2800 / 7 = 0.1829. Standard deviation = sqrt of 0.1829 = 0.428 minutes. Upper control limit (UCL) = 5.75 + (2 x 0.428) = 5.75 + 0.856 = 6.606 approximately 6.61 minutes. Lower control limit (LCL) = 5.75 - 0.856 = 4.894 approximately 4.89 minutes. The four most recent AHT values (6.1, 6.3, 6.5, 6.6) all fall within the 4.89-6.61 control limits — no individual point exceeds the UCL. However, the run rule is unambiguously triggered: four consecutive weeks of increasing AHT (6.1 < 6.3 < 6.5 < 6.6) represent a non-random pattern. In statistical process control, a run of four or more consecutive points trending in the same direction has a probability well below 1% under random variation, signaling a systematic shift in the process mean. In the business context, the operations manager should investigate what changed after Week 8 — possible causes include new-hire training gaps, system performance degradation, or changes in call complexity — rather than waiting for a point to breach the control limit. The upward trend toward the UCL (6.6 is approaching 6.61) further reinforces the urgency of investigation. A common exam trap is to treat control limits as the sole out-of-control criterion and ignore run rules entirely.",
    "ExplanationWrongA": "Option A incorrectly concludes that the process is in control because all points fall within the control limits, ignoring the run rule entirely. Statistical process control recognizes two categories of out-of-control signals: (1) a point outside the control limits, and (2) a non-random pattern within the control limits, such as a run, trend, or cycle. The run rule — four or more consecutive points trending in one direction — is a standard SPC signal because the probability of observing such a pattern under pure random variation is extremely low (approximately 0.4% for four consecutive increases). A candidate selecting this option is applying only half of the SPC framework. The operations manager's policy explicitly states that the run rule triggers investigation regardless of whether individual points fall within control limits. Treating control limits as the exclusive out-of-control criterion is a common but incomplete interpretation of statistical process control.",
    "ExplanationWrongB": "Option B incorrectly dismisses the upward trend as insufficiently large to warrant investigation. The magnitude of change (0.5 minutes over four weeks) is not the relevant criterion — the pattern of change is. Under random variation, four consecutive increases would occur by chance less than 1% of the time, making the pattern itself statistically significant. Furthermore, the run rule is applied to the direction and sequence of points, not to their absolute magnitude relative to the standard deviation. A candidate selecting this option may be evaluating the trend against an informal materiality threshold rather than applying the formal SPC run rule. A trend of four consecutive increases signals that a systematic force — not random variation — is pushing AHT upward, and the operations manager should investigate before the trend eventually breaches the control limit. Waiting for a point to exceed the UCL before acting is reactive management; the run rule enables proactive, preventive investigation.",
    "ExplanationWrongC": "",
    "ExplanationWrongD": "Option D incorrectly asserts that the most recent data point (6.6) exceeds the upper control limit. The computed UCL is 5.75 + (2 x 0.428) = 6.606, approximately 6.61 minutes. The most recent AHT value of 6.6 minutes is below 6.61 — it does not breach the upper control limit. A candidate selecting this option correctly recognizes that the process is out of control but attributes it to the wrong signal (point outside limit rather than run rule). This reflects an error in either the control limit calculation (possibly using the population standard deviation formula with n=8 denominator yielding 0.400, giving UCL = 6.55, which would flag 6.6 as out of control) or in the rounding of the final UCL value. The correct calculation uses n-1 = 7 for the sample standard deviation, yielding a UCL of approximately 6.61, which the 6.6 value does not exceed. The process is out of control, but the correct reason is the run rule, not a limit breach.",
    "StudyLinks": [
      "IMA CMA Part 1 CSO Section C — Performance Management: Quality and process performance measurement"
    ],
    "VerifiedChecks": [
      "Accounting accuracy verified — control limit calculations independently recomputed: mean 5.75, sample std dev 0.428, UCL 6.61, LCL 4.89",
      "Run rule interpretation verified against standard SPC principles: 4 consecutive increases = out-of-control signal",
      "Distractors each map to a specific analysis error: ignoring run rules, magnitude-over-pattern error, and miscomputed control limit",
      "Answer choices are mutually exclusive and collectively exhaustive",
      "Explanation meets CAQS 4 minimum requirements: EC >= 300 chars, each non-CC EW >= 150 chars"
    ]
  }
];